### ISSUE TITLE
Installing packages fails when already cached on Windows (making 1.1.9+ unusable on Windows)

### ISSUE THREAD

**Issue by bparzella** [python-poetry/poetry#4535] opened 2021-09-21 09:40 UTC
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10
- **Poetry version**: 1.1.9-1.1.11
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**:
```[tool.poetry]
name = "poetry_test"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.6"
lxml = "^4.6.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

## Issue

Installing a package that is already in the local pypoetry cache on windows fails since poetry 1.1.9.

```
$ poetry install -vvv --no-root
Using virtualenv: D:\user\src\temp\poetry_test\poetry_env
Installing dependencies from lock file

Finding the necessary packages for the current system

Package operations: 1 install, 0 updates, 0 removals

  • Installing lxml (4.6.3): Pending...
  • Installing lxml (4.6.3): Failed

  ValueError

  File \C:\Users\user\AppData\Local\pypoetry\Cache\artifacts\f7\90\e7\2d9752b05431b2ba90b4626b90f1674c505301a7cdbab89fd620aee824\lxml-4.6.3-cp36-cp36m-win_amd64.whl does not exist

  at D:\user\src\temp\poetry_test\poetry_env\lib\site-packages\poetry\core\packages\file_dependency.py:40 in __init__
       36│             except FileNotFoundError:
       37│                 raise ValueError("Directory {} does not exist".format(self._path))
       38│
       39│         if not self._full_path.exists():
    →  40│             raise ValueError("File {} does not exist".format(self._path))
       41│
       42│         if self._full_path.is_dir():
       43│             raise ValueError("{} is a directory, expected a file".format(self._path))
       44│
```

The problem does not occur, if the package is not cached.

Python version used is 3.6.8

### Workaround
As a workaround we downgraded to 1.1.8 and poetry-core 1.0.4.

### IMHO
It seems like this issue comes from the commit https://github.com/python-poetry/poetry/commit/8238cab2e1690b4e1b7ea4a460c6295b1b2c6cb7

The call to "archive.path" in line 615 of 'poetry/installation/executor.py' seems to remove only two of the three slashes for Windows file URLs (file:///c:/.....). This results in an invalid path with a leading slash (visible in the command output `File \C:\Users\user\AppData`), which in the end leads to a missing file exception.

**Comment by klnrdknt** [comment] 2021-09-21 10:23
I believe this is the same issue https://github.com/python-poetry/poetry/issues/4479

**Comment by bparzella** [comment] 2021-09-21 11:14
The basic issue seems to be the same, but #4479 is about about the pre-release version 1.2.0a1 from the beginning of august.

Now the latest stable release 1.1.9 (september 18th) is affected which is supposed to be run on productive systems and makes it pretty much unusable on windows (at least in the conditions we are using it).

This information is missing in #4479 IMHO.

**Comment by bparzella** [comment] 2021-09-21 12:03
That I don't know.

**Comment by Suween** [comment] 2021-09-21 17:31
The workaround works. It seems that 1.1.8 is not compatible with core 1.0.5, but if you pip install==1.1.8, it comes with peotry core 1.0.5.

**Comment by jnoelvictorino** [comment] 2021-09-23 11:41
Workaround works at 1.1.8

**Comment by DavisDmitry** [comment] 2021-09-23 11:57
I have a similar problem when poetry tries to install colorama
```
Package operations: 10 installs, 0 updates, 0 removals

  • Installing colorama (0.4.4)

  ValueError

  File \C:\Users\Admin\AppData\Local\pypoetry\Cache\artifacts\9e\b3\11\7d87ac44fdb2d557301f1f4086a37c080d1482a98751abe7cdbabbad26\colorama-0.4.4-py2.py3-none-any.whl does not exist

  at ~\.poetry\lib\poetry\_vendor\py3.9\poetry\core\packages\file_dependency.py:40 in __init__
       36│             except FileNotFoundError:
       37│                 raise ValueError("Directory {} does not exist".format(self._path))
       38│
       39│         if not self._full_path.exists():
    →  40│             raise ValueError("File {} does not exist".format(self._path))
       41│
       42│         if self._full_path.is_dir():
       43│             raise ValueError("{} is a directory, expected a file".format(self._path))
       44│

```

Windows 10 19043.1237
Python 3.9.7
Poetry 1.1.10
Poetry-core 1.0.6

**Comment by mario-bermonti** [comment] 2021-09-25 00:47
I am having the same issue on github’s CI Windows machine.

**Comment by bparzella** [comment] 2021-09-27 06:35
Tested with 1.1.10, same problem.

A pull request that seems to fix this issue: https://github.com/python-poetry/poetry/pull/4531

**Comment by mario-bermonti** [comment] 2021-09-29 12:13
The work around worked for me, but I had to install poetry-core manually (poetry-core==1.0.4)

**Comment by travfu** [comment] 2021-10-02 11:39
I had the same issue today. It's because for some reason the path is prepended with a '\' so when Path.exists() is called, it's false. A temporary fix is to just add the line `path = Path(str(path)[1:])` to the start of the class init method.

**Comment by thearchitector** [comment] 2021-10-02 17:36
Uninstalling poetry, removing all poetry folders and files, then reinstalling, also worked for the initial `poetry install/add/remove` command (but not any latter ones).

The workaround resolved the issue across the board for me as well.

**Comment by serverwentdown** [comment] 2021-10-09 16:29
Will be fixed by #4531 (1.2) and #4549 (1.1)

**Comment by serverwentdown** [comment] 2021-10-09 18:17
If any of you have some free time, can you help me run [these tests](https://github.com/python-poetry/poetry/pull/4531/files#diff-05df631d2a04ad78670e1c9c24d50d383262f0b7e56743b4e49d0d643bffb3cbR469-R507) on Windows without the fix applied?

**Comment by rubendibattista** [comment] 2021-10-18 07:49
I think #2795 is related

**Comment by Diggsey** [comment] 2021-11-03 18:55
For those with this issue, the following fix worked for me:

- Open `~\.poetry\lib\poetry\_vendor\py3.8\poetry\core\packages\utils\link.py` (may need to change python version)
- Add `import urllib.request` at the top
- Modify `Link.path` to look like the following:

```python

    @property
    def path(self):  # type: () -> str
        res = urlparse.urlsplit(self.url)
        if res.scheme == 'file':
            netloc = res.netloc
            if netloc:
                netloc = '\\\\' + netloc
            return urllib.request.url2pathname(netloc + res.path)
        else:
            return urlparse.unquote(res.path)
```

This seems quite a bit simpler than the "fix" PR?

**Closed** 2021-11-12 15:31 UTC
Labels: Bug, Triage

**Comment by serverwentdown** [comment] 2021-11-17 16:15
@pohlt Wait a while for the next release. In the meantime, you can install the 1.2 branch with:

```
(Invoke-WebRequest -Uri https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py -UseBasicParsing).Content | python - --git git+https://github.com/python-poetry/poetry.git@master
```

**Comment by lars-reimann** [comment] 2021-11-23 10:14
> @pohlt Wait a while for the next release. In the meantime, you can install the 1.2 branch with:
> 
> ```
> (Invoke-WebRequest -Uri https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py -UseBasicParsing).Content | python - --git git+https://github.com/python-poetry/poetry.git@master
> ```

This gives me an error
```
ERROR: Invalid requirement: 'git+git+https://github.com/python-poetry/poetry.git@master' 
```

Removing the `git+` works, though:
```
(Invoke-WebRequest -Uri https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py -UseBasicParsing).Content | python - --git https://github.com/python-poetry/poetry.git@master
```

**Comment by teucer** [comment] 2021-11-23 13:35
@neersighted  @serverwentdown  Seems that  the PR has been merged. When can we expect a new release?

**Comment by Ivoz** [comment] 2021-12-19 09:37
1.1.12 is released with this fix

**Comment by mohghaderi** [comment] 2023-02-21 23:38
Same problem exists with Poetry==1.3.2 and poetry-core==1.4.0 installed inside conda env. Windows 11 (and 10), Python=3.9.7 (Github Actions, Miniconda)


```
CalledProcessError

  Command 'C:\Miniconda3\envs\repo-name\python.exe -m pip install --disable-pip-version-check --isolated --no-input --prefix C:\Miniconda3\envs\repo-name --upgrade --no-deps C:\Users\runneradmin\AppData\Local\pypoetry\Cache\artifacts\eb\e4\7b\0856e7bf2096007a4407c92df58e703b0b78c2b5c6d63ef9d18d23d724\charset_normalizer-3.0.1-cp39-cp39-win_amd64.whl' returned non-zero exit status 1.

  at C:\Miniconda3\envs\repo-name\lib\subprocess.py:528 in run
       524|             # We don't call process.wait() as .__exit__ does that for us.
       525|             raise
       526|         retcode = process.poll()
       527|         if check and retcode:
    >  528|             raise CalledProcessError(retcode, process.args,
       529|                                      output=stdout, stderr=stderr)
       530|     return CompletedProcess(process.args, retcode, stdout, stderr)
       531| 
       532| 

The following error occurred when trying to handle this error:


  EnvCommandError

  Command C:\Miniconda3\envs\repo-name\python.exe -m pip install --disable-pip-version-check --isolated --no-input --prefix C:\Miniconda3\envs\repo-name --upgrade --no-deps C:\Users\runneradmin\AppData\Local\pypoetry\Cache\artifacts\eb\e4\7b\0856e7bf2096007a4407c92df58e703b0b78c2b5c6d63ef9d18d23d724\charset_normalizer-3.0.1-cp39-cp39-win_amd64.whl errored with the following return code 1, and output: 
  Processing c:\users\runneradmin\appdata\local\pypoetry\cache\artifacts\eb\e4\7b\0856e7bf2096007a4407c92df58e703b0b78c2b5c6d63ef9d18d23d724\charset_normalizer-3.0.1-cp39-cp39-win_amd64.whl

  Installing collected packages: charset-normalizer

    Attempting uninstall: charset-normalizer

      Found existing installation: charset-normalizer 2.1.1

      Uninstalling charset-normalizer-2.1.1:

        Successfully uninstalled charset-normalizer-2.1.1

  ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\runneradmin\\AppData\\Local\\Temp\\pip-uninstall-hvwco4b4\\normalizer.exe'

  Consider using the `--user` option or check the permissions.

  

  

  at C:\Miniconda3\envs\repo-name\lib\site-packages\poetry\utils\env.py:1540 in _run
      1536|                 output = subprocess.check_output(
      1537|                     command, stderr=subprocess.STDOUT, env=env, **kwargs
      1538|                 )
      1539|         except CalledProcessError as e:
    > 1540|             raise EnvCommandError(e, input=input_)
      1541| 
      1542|         return decode(output)
      1543| 
      1544|     def execute(self, bin: str, *args: str, **kwargs: Any) -> int:

The following error occurred when trying to handle this error:


  PoetryException

  Failed to install C:/Users/runneradmin/AppData/Local/pypoetry/Cache/artifacts/eb/e4/7b/0856e7bf2096007a4407c92df58e703b0b78c2b5c6d63ef9d18d23d724/charset_normalizer-3.0.1-cp39-cp39-win_amd64.whl

  at C:\Miniconda3\envs\repo-name\lib\site-packages\poetry\utils\pip.py:58 in pip_install
       54| 
       55|     try:
       56|         return environment.run_pip(*args)
       57|     except EnvCommandError as e:
    >  58|         raise PoetryException(f"Failed to install ***path.as_posix()***") from e
       59| 

Error: Process completed with exit code 1.
```

any suggestions?

**Comment by neersighted** [comment] 2023-02-21 23:39
That is a completely different issue as evidenced by the stack trace; can you please open a new issue with reproduction instructions (e.g. a pyproject.toml **tested** to reliably reproduce + version information)?
