### ISSUE TITLE
Unexpected poetry build error when using --directory option to set working directory

### ISSUE THREAD

**Issue by mikemckibben** [python-poetry/poetry#8524] opened 2023-10-09 22:45 UTC
- **Poetry version**: 1.6.1
- **Python version**: 3.10.12
- **OS version and name**: macOS 13.6
- **project-a/pyproject.toml**: 
```
[tool.poetry]
name = "project-a"
version = "0.1.0"
description = "Example namespaced package project"
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "myorg"}]

[tool.poetry.dependencies]
python = "^3.10"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```
- **project-b/pyproject.toml**:
```
[tool.poetry]
name = "project-b"
version = "0.1.0"
description = "Example non-namespace package project"
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "project_b"}]

[tool.poetry.dependencies]
python = "^3.10"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

Minimal project example showing unexpected behavior building poetry packages within a monorepo. project-a uses namespace source package layout and project-b uses traditional source package layout.
```
.
├── README.md
├── project-a
│   ├── README.md
│   ├── myorg
│   │   └── project_a
│   │       └── __init__.py
│   └── pyproject.toml
└── project-b
    ├── README.md
    ├── project_b
    │   └── __init__.py
    └── pyproject.toml
```

From inside the project-a directory, building works as expected
```
# CWD /Users/mmckib201/Development/source/de49b7fa323d21a3f5c7df88e81ed878/project-a
cd project-a
poetry build
Building project-a (0.1.0)
  - Building sdist
  - Built project_a-0.1.0.tar.gz
  - Building wheel
  - Built project_a-0.1.0-py3-none-any.whl
```

Running poetry build from the top-level project directory, passing in --directory project-a, building fails
```
# CWD /Users/mmckib201/Development/source/de49b7fa323d21a3f5c7df88e81ed878
poetry build -vvvv --directory project-a
Building project-a (0.1.0)
  - Building sdist
Ignoring:
  - Adding: project-a/myorg/project_a/__init__.py
  - Adding: README.md
  - Adding: pyproject.toml
  
Stack trace:

  10  /opt/homebrew/Cellar/poetry/1.6.1_1/libexec/lib/python3.11/site-packages/cleo/application.py:327 in run
       325│
       326│             try:
     → 327│                 exit_code = self._run(io)
       328│             except BrokenPipeError:
       329│                 # If we are piped to another process, it may close early and send a

   9  /opt/homebrew/Cellar/poetry/1.6.1_1/libexec/lib/python3.11/site-packages/poetry/console/application.py:190 in _run
       188│         self._load_plugins(io)
       189│
     → 190│         exit_code: int = super()._run(io)
       191│         return exit_code
       192│

   8  /opt/homebrew/Cellar/poetry/1.6.1_1/libexec/lib/python3.11/site-packages/cleo/application.py:431 in _run
       429│             io.input.interactive(interactive)
       430│
     → 431│         exit_code = self._run_command(command, io)
       432│         self._running_command = None
       433│

   7  /opt/homebrew/Cellar/poetry/1.6.1_1/libexec/lib/python3.11/site-packages/cleo/application.py:473 in _run_command
       471│
       472│         if error is not None:
     → 473│             raise error
       474│
       475│         return terminate_event.exit_code

   6  /opt/homebrew/Cellar/poetry/1.6.1_1/libexec/lib/python3.11/site-packages/cleo/application.py:457 in _run_command
       455│
       456│             if command_event.command_should_run():
     → 457│                 exit_code = command.run(io)
       458│             else:
       459│                 exit_code = ConsoleCommandEvent.RETURN_CODE_DISABLED

   5  /opt/homebrew/Cellar/poetry/1.6.1_1/libexec/lib/python3.11/site-packages/cleo/commands/base_command.py:119 in run
       117│         io.input.validate()
       118│
     → 119│         status_code = self.execute(io)
       120│
       121│         if status_code is None:

   4  /opt/homebrew/Cellar/poetry/1.6.1_1/libexec/lib/python3.11/site-packages/cleo/commands/command.py:62 in execute
        60│
        61│         try:
     →  62│             return self.handle()
        63│         except KeyboardInterrupt:
        64│             return 1

   3  /opt/homebrew/Cellar/poetry/1.6.1_1/libexec/lib/python3.11/site-packages/poetry/console/commands/build.py:34 in handle
        32│
        33│             builder = Builder(self.poetry)
     →  34│             builder.build(fmt, executable=env.python)
        35│
        36│         return 0

   2  /opt/homebrew/Cellar/poetry/1.6.1_1/libexec/lib/python3.11/site-packages/poetry/core/masonry/builder.py:39 in build
        37│
        38│         for builder in builders:
     →  39│             builder(self._poetry, executable=executable).build(target_dir)
        40│

   1  /opt/homebrew/Cellar/poetry/1.6.1_1/libexec/lib/python3.11/site-packages/poetry/core/masonry/builders/sdist.py:83 in build
        81│
        82│             for file in sorted(files_to_add, key=lambda x: x.relative_to_source_root()):
     →  83│                 tar_info = tar.gettarinfo(
        84│                     str(file.path),
        85│                     arcname=pjoin(tar_dir, str(file.relative_to_source_root())),

  FileNotFoundError

  [Errno 2] No such file or directory: '/Users/mmckib201/Development/source/de49b7fa323d21a3f5c7df88e81ed878/project-a/project-a/myorg/project_a/__init__.py'

  at /opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tarfile.py:2037 in gettarinfo
      2033│
      2034│         # Use os.stat or os.lstat, depending on if symlinks shall be resolved.
      2035│         if fileobj is None:
      2036│             if not self.dereference:
    → 2037│                 statres = os.lstat(name)
      2038│             else:
      2039│                 statres = os.stat(name)
      2040│         else:
      2041│             statres = os.fstat(fileobj.fileno())
```

Basically, the directory option causes build to create invalid paths `project-a/project-a/myorg/project_a/__init__.py`. Based on the usage description, --directory should set the working directory for the build command to project-a. I get the same error for project-b example, which is not a namespaced source package layout.

```
poetry build --help

Description:
  Builds a package, as a tarball and a wheel by default.

Usage:
  build [options]

Options:
  -f, --format=FORMAT        Limit the format to either sdist or wheel.
  -h, --help                 Display help for the given command. When no command is given display help for the list command.
  -q, --quiet                Do not output any message.
  -V, --version              Display this application version.
      --ansi                 Force ANSI output.
      --no-ansi              Disable ANSI output.
  -n, --no-interaction       Do not ask any interactive question.
      --no-plugins           Disables plugins.
      --no-cache             Disables Poetry source caches.
  -C, --directory=DIRECTORY  The working directory for the Poetry command (defaults to the current working directory).
  -v|vv|vvv, --verbose       Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug.
```

It's not huge deal to workaround this in build scripts to add an explicit `cd` command, but I'm not sure what the is point of supporting the --directory flag for the build command if it is not going to work relative to the directory passed in the command.

**Comment by finswimmer** [comment] 2023-10-11 05:27
Duplicate of https://github.com/python-poetry/poetry/issues/7897

**Closed by finswimmer** 2023-10-11 05:27 UTC
Labels: kind/bug, status/triage
