### ISSUE TITLE
(🐞) Optional dependency is installed with pip

### ISSUE THREAD

**Issue by KotlinIsland** [python-poetry/poetry#7787] opened 2023-04-11 04:32 UTC
- **Poetry version**:  1.4.2
- **Python version**:  3.11
- **OS version and name**:  windows 10
- **pyproject.toml**: 

<details><summary>Details</summary>
<p>

```toml
[tool.poetry]
name = "test"
description = "test"
version = "0.0.0"
authors = []

[tool.poetry.dependencies]
python = "^3.7"
black = ">=19.10b0"
# typed-ast = { version = "*", optional = true }

[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

</p>
</details> 

- [🚀] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [🚀] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [🚀] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [🚀] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

I am trying to constrain a transitive dependency (related #4991) by making this dependency optional, `poetry install` doesn't add this dependency, but `pip install` does despite it not being needed? Is this an issue with pip, or with poetry?

```
👉 poetry install
Installing dependencies from lock file

No dependencies to install or update
👉 pip install .
...
Requirement already satisfied: black>=19.10b0
Requirement already satisfied: click>=8.0.0
Requirement already satisfied: mypy-extensions>=0.4.3
Requirement already satisfied: packaging>=22.0
Requirement already satisfied: pathspec>=0.9.0
Requirement already satisfied: platformdirs>=2
Requirement already satisfied: colorama
...
Successfully installed test-0.0.0

👉 uncomment typed-ast in pyproject.toml

👉 poetry install
Installing dependencies from lock file

No dependencies to install or update
👉 pip install .
...
      building '_ast27' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> typed-ast

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

**Comment by dimbleby** [comment] 2023-04-11 07:33
your configuration doesnt make sense.  You forgot to say what extras `typed-ast` should be installed as part of.

**Comment by KotlinIsland** [comment] 2023-04-11 07:35
Like I said in the OP, it's not an extra, it's a constraint of a transitive dependency.

**Comment by dimbleby** [comment] 2023-04-11 07:38
I do not know what you can mean by that.
```toml
# typed-ast = { version = "*", optional = true }
```
is the mechanism for defining the dependencies to be installed as extras of your package.

If you are trying to do something else: that's not the way to do it.

**Comment by dimbleby** [comment] 2023-04-11 11:28
Yes, I understand.  If you want to rework this issue so that it says "poetry fails to reject this invalid configuration" then that would make sense.

What I am telling you is that what you are trying to do is not expected to work, and so an issue that says "this does not work as I expect" is unlikely to get traction.

**Comment by dimbleby** [comment] 2023-04-11 11:50
however that would be a duplicate of #2357, so this can be closed

**Comment by finswimmer** [comment] 2023-04-28 07:17
Closing this as either a duplicate of #2357 or #4991.

**Closed by finswimmer** 2023-04-28 07:17 UTC
Labels: kind/bug, status/triage
