### ISSUE TITLE
Unconditional reinstallation of packages

### ISSUE THREAD

**Issue by OceanManOne** [python-poetry/poetry#7106] opened 2022-11-27 19:44 UTC
- [ x ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ x ] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request
I'm using poetry to install my package which is built on pypi packages and local packages (using {path = '../../lib'}) where the local packages versions aren't updating.

If I change some local package code and run poetry install for the 2nd time, poetry doesn't detect a change and says: "No dependencies to install or update"

I would like to be able to specify which packages to re-install (through groups or any other method) even if exist to allow both using the existing pypi cache but also to update my local packages code.

**Comment by dimbleby** [comment] 2022-11-27 20:20
sounds like you maybe wanted to install your local path packages in editable mode?

nb per #7088 you'll have to recreate your virtual environment when you make that change.

**Comment by OceanManOne** [comment] 2022-11-27 20:36
> sounds like you maybe wanted to install your local path packages in editable mode?
> 
> nb per #7088 you'll have to recreate your virtual environment when you make that change.

The problem is that I can't use develop = true as I'm using the following flag:
poetry config virtualenvs.in-project true

to output a "build" directory to be used as a full code app in a docker container.
If I use develop = true it won't copy the actual local package code but just reference to it (and I can't copy the local package itself as it is mixed with other non related local packages).

**Comment by neersighted** [comment] 2022-11-27 20:53
I think we've got some X-Y problem here: what you want to achieve for Docker image building (side-note: you should build in a Dockerfile and not bind-mount in a virtual environment from the host -- unless you ensure symmetric glibc/Python/distro versions, things will break) is possible once python-poetry/poetry-plugin-bundle#37 is fixed.

Regarding your other ask, it should be addressed by #6843 but is not in a released version yet.

**Comment by OceanManOne** [comment] 2022-11-27 21:17
> I think we've got some X-Y problem here: what you want to achieve for Docker image building (side-note: you should build in a Dockerfile and not bind-mount in a virtual environment from the host -- unless you ensure symmetric glibc/Python/distro versions, things will break) is possible once [python-poetry/poetry-plugin-bundle#37](https://github.com/python-poetry/poetry-plugin-bundle/issues/37) is fixed.
> 
> Regarding your other ask, it should be addressed by #6843 but is not in a released version yet.

Thanks for the reply, I've actually tested the the #6843 fix by using the latest master but it doesn't seem to fix my issue,
running poetry install again for the 2nd time and changing some of the local packages doesn't re-trigger a re-installation / update of the package code.
And there is still no hash value in the poetry.lock file for local packages so I'm not sure if it intended to my use.

I've also tried the poetry plugin bundle yesterday and it looks great but I had an issue where it doesn't work with local package referencing other local package, I've actually opened a issue regarding that:
[Issue #40](https://github.com/python-poetry/poetry-plugin-bundle/issues/40)

**Comment by neersighted** [comment] 2022-11-27 21:56
Right, that doesn't refresh code, but it refreshes metadata. Combined with `develop = true`, it does what you want.

The solution I am suggesting is to make `develop = true` work for your use case, by making bundle work as intended (create a 'portable as possible' venv).

I don't think this ask makes much sense, instead solving the deficiencies in tools intended to serve this use case makes more sense.

**Comment by neersighted** [comment] 2022-11-27 21:57
Looks like this user also created a discussion post with the same content; given that detecting code-only changes is fraught and always reinstalling (requiring a potentially expensive build) is also fraught, I'm going to close this and suggest discussion can continue there: https://github.com/orgs/python-poetry/discussions/7105.

**Closed by neersighted** 2022-11-27 21:57 UTC
Labels: kind/feature
