### ISSUE TITLE
git dependency with extra dependency not working as direct extra dependency

### ISSUE THREAD

**Issue by poetryuser** [python-poetry/poetry#8808] opened 2023-12-19 11:04 UTC
Poetry version: 1.7.1
Python version: 3.10.6

In PackageA toml file:
[tool.poetry.dependencies]
optionaldependency= {version = "1.7.0", source = "private-repo", optional = true}
[tool.poetry.extras]
extra-dependency=["optionaldependency"]

In packageB toml file:
packageA= {git = "https://package-a-fit-repo.git"}

PackageB has the packageA as a required dependency.
I want package B to install "extra-dependency" in package A on demand, i want to run the command line:
packageB.whl[extra-dependency] 
and have packageB, packageA and "extra-dependency" in packageA.

Is it possible? If so can you provide me with both packageA and packageB toml files, and the appropriate command line for installation?

**Comment by dimbleby** [comment] 2023-12-19 12:58
duplicate #834 (and many more) please close

**Comment by GOGKI** [comment] 2024-03-01 12:01
@dimbleby could you point to the resolved issue? I see a lot of those threads where people mark duplicates, but with such a large number of issues it is very difficult to find anything anymore.

**Comment by dimbleby** [comment] 2024-03-01 12:40
this is a duplicate of #834, I don't know how I could more clearly have pointed at that?

it is a duplicate regardless of whether #834 is resolved

**Closed** 2024-03-01 12:47 UTC
Labels: kind/bug, status/duplicate

**Comment by GOGKI** [comment] 2024-03-01 13:24
@dimbleby I understand it is a duplicate. But as I am saying in a developers community when we are trying to solve problems, stating only something is a duplicate does not help anyone. If you want be helpful instead of quickly closing issues, you could e.g. point out that a partly solution is available in https://github.com/python-poetry/poetry/issues/7748, but the issue is still not fixed.
