### ISSUE TITLE
Configuration Option for Default Version Constraint

### ISSUE THREAD

**Issue by adam-grant-hendry** [python-poetry/poetry#8291] opened 2023-08-09 21:12 UTC
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request

Would it be possible to provide a configuration setting to `poetry` to let users choose between upper bound constraining (e.g. `^`) or unbound constraining (e.g. `>=3.4`) when adding new dependencies?

I know this has historically been a hot issue, but it would be nice (esp. since [the docs](https://python-poetry.org/docs/faq/#are-unbound-version-constraints-a-bad-idea) now acknowledge differences between libraries and apps).

**Comment by dimbleby** [comment] 2023-08-09 21:50
I don't know that a configurable value for the default makes enough of a difference to be worth the complexity: you still have to have a default value for _that_!  So for the 95% of users who just use the defaults nothing has changed, and for the 5% who care to think about their version constraints - well they were thinking about their version constraints anyway.

As someone who falls into that 5% I don't much care what the default behaviour is, either way I will arrange that my constraints are what I want them to be.

Personally I wouldn't want to stir the hornet's nest but I think that trying to get people to agree that the default behaviour should simply be changed is more logical.

FWIW: I personally mostly don't buy the arguments claiming that upper bounds are not helpful - there are recent examples even reported in this repository of minor ecosystem kerfuffles where semantic versioning either did or would have saved users a bunch of trouble (eg urllib3 2.0 and cachecontrol; or cython 3.0 and pyyaml).  And my experience is that - at least among packages that are sufficiently well maintained that I would want to use them - the problems potentially caused by upper bounds are in fact extremely rare.  So - again personally - I'd be a soft minus one on changing this.

**Comment by adam-grant-hendry** [comment] 2023-08-09 22:08
What if I wrote and published a plugin instead?

**Comment by dimbleby** [comment] 2023-08-09 22:11
sure, anyone can do write a plugin whenever they want!  in fact last time this came up someone _did_ do something in this area (I've not looked at it myself so I have no view on whether it is useful or what you want) - https://github.com/python-poetry/poetry/issues/3427#issuecomment-1252995748.

Also the above is just my opinion: as you hint, this is a topic that draws many opinions - it's far from impossible that actual maintainers will feel differently about it than I do.

**Comment by adam-grant-hendry** [comment] 2023-08-09 22:15
Ya, I'm less keen to re-open a potentially hot issue/can-of-worms and the quickest way to give users an option does seem to me to be a plugin. I'll give that a whirl and report back with what I got.

**Comment by abn** [comment] 2024-03-02 13:34
I am going to close this for now as we do not plan on working on this. As was pointed out earlier in the issue, the use case for this might be way too niche for the effort involved and additional cognitive load introduced for majority users.

If there is a plugin that comes about, feel free to post a show and tell discussion. For help during development try the discord community.

**Closed by abn** 2024-03-02 13:34 UTC
Labels: kind/feature, status/waiting-on-response
