### ISSUE TITLE
Regression of config virtualenvs.create false on 1.2

### ISSUE THREAD

**Issue by AleksandrLiadov** [python-poetry/poetry#6326] opened 2022-09-01 10:35 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Mac Catalina 10.15.7 (intel)
- **Poetry version**: 1.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue
I have notice a regression in last version. The problem is I don't want that Poetry creates a virtual environment inside a Docker.
Before the last version all works fine. I have tested 1.1.15 there isn't this problem.
I tried to figure out:

>  Command ['/usr/local/bin/python', '/usr/local/lib/python3.8/site-packages/virtualenv/seed/wheels/embed/pip-22.2.2-py3-none-any.whl/pip', 'install', '--disable-pip-version-check', '--prefix', '/usr/local', '--no-deps', '/root/.cache/pypoetry/artifacts/a6/f7/5e/59a43ec23ade0888631b3f24244da7f5d5a0b6b40849c86b8c6b4c54d1/pyasn1-0.4.8-py2.py3-none-any.whl'] errored with the following return code 2, and output: 
>   /usr/local/bin/python: can't open file '/usr/local/lib/python3.8/site-packages/virtualenv/seed/wheels/embed/pip-22.2.2-py3-none-any.whl/pip': [Errno 2] No such file or directory

So we can notice that Poetry try to go to` /usr/local/lib/python3.8/site-packages/virtualenv/...` but, there isn't this directory, because we have chose  `virtualenvs.create false` option.

**Comment by neersighted** [comment] 2022-09-01 10:43
This is not related to virtualenv creation, but likely instead due to a combination of factors.

Poetry depends on the `virtualenv` package for an embedded copy of pip, even when creation is turned off. If you are installing both Poetry and your project into system site-packages, you may run into an issue where Poetry sabotages its own dependencies by trying to install your project's dependencies.

It is always suggested, even in a container, to install into a virtual environment. This is because of the nature of Python packaging/environments and how the distro-packaged Python modules may interfere with your project. Generally you can install Poetry into the system environment just fine as we make a best effort attempt to not conflict with what is usually found in a system `site-package`, but that is not a guarantee.

To give you a rough idea of what I would suggest in a container:
```shell
python3 -m venv /opt/poetry
/opt/poetry/bin/pip install poetry
cd myproject
/opt/poetry/bin/poetry config virtualenvs.in-project true
/opt/poetry/bin/poetry install
.venv/bin/python3 -m myproject
```

**Comment by AleksandrLiadov** [comment] 2022-09-01 10:52
Thanks for your feedback!
However, is it normal that the versions 1.1.15 and 1.2 behave differently? 
So there is no a "safe" way to install my project with poetry inside a container without creation a virtual environement?

**Comment by neersighted** [comment] 2022-09-01 10:56
It was more of a happy chance that you did not run into issues, as best I can tell. Installing two Python projects with external dependencies (aka Poetry and your project) into the same environment has always been fraught -- you just didn't get bit until now.

At least one of them should be in a virtual environment, and preferably both, to avoid unexpected breakage if your distro/base image makes an unexpected change.

**Comment by stevanmilic** [comment] 2022-09-01 11:01
Sorry for jumping into the issue, but I'm having troubles installing packages within the docker container too. But it looks like this a different type of issue – `poetry` isn't respecting the local user set-up and tries to install dependencies into root user site-packages for some reason (previously the same command has worked perfectly fine):
```
poetry install --without dev
 ---> Running in 02df11ae6af1
Skipping virtualenv creation, as specified in config file.
Installing dependencies from lock file

Package operations: 167 installs, 1 update, 0 removals

  • Installing pyasn1 (0.4.8)

  CalledProcessError

  Command '['/usr/local/bin/python3.9', '/home/webuser/.local/share/pypoetry/venv/lib/python3.9/site-packages/virtualenv/seed/wheels/embed/pip-22.2.2-py3-none-any.whl/pip', 'install', '--disable-pip-version-check', '--prefix', '/usr/local', '--no-deps', '/home/webuser/.cache/pypoetry/artifacts/7b/3a/54/42ce43b579bda01b9d79022fb733811594441e7a32e9f9a5a98f672bdc/pyasn1-0.4.8-py2.py3-none-any.whl']' returned non-zero exit status 1.

  at /usr/local/lib/python3.9/subprocess.py:528 in run
       524│             # We don't call process.wait() as .__exit__ does that for us.
       525│             raise
       526│         retcode = process.poll()
       527│         if check and retcode:
    →  528│             raise CalledProcessError(retcode, process.args,
       529│                                      output=stdout, stderr=stderr)
       530│     return CompletedProcess(process.args, retcode, stdout, stderr)
       531│ 
       532│ 

The following error occurred when trying to handle this error:


  EnvCommandError

  Command ['/usr/local/bin/python3.9', '/home/webuser/.local/share/pypoetry/venv/lib/python3.9/site-packages/virtualenv/seed/wheels/embed/pip-22.2.2-py3-none-any.whl/pip', 'install', '--disable-pip-version-check', '--prefix', '/usr/local', '--no-deps', '/home/webuser/.cache/pypoetry/artifacts/7b/3a/54/42ce43b579bda01b9d79022fb733811594441e7a32e9f9a5a98f672bdc/pyasn1-0.4.8-py2.py3-none-any.whl'] errored with the following return code 1, and output: 
  Processing /home/webuser/.cache/pypoetry/artifacts/7b/3a/54/42ce43b579bda01b9d79022fb733811594441e7a32e9f9a5a98f672bdc/pyasn1-0.4.8-py2.py3-none-any.whl
  Installing collected packages: pyasn1
  ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/usr/local/lib/python3.9/site-packages/pyasn1'
  Consider using the `--user` option or check the permissions.
  
  

  at ~/.local/share/pypoetry/venv/lib/python3.9/site-packages/poetry/utils/env.py:1473 in _run
      1469│                 output = subprocess.check_output(
      1470│                     command, stderr=subprocess.STDOUT, env=env, **kwargs
      1471│                 )
      1472│         except CalledProcessError as e:
    → 1473│             raise EnvCommandError(e, input=input_)
      1474│ 
      1475│         return decode(output)
      1476│ 
      1477│     def execute(self, bin: str, *args: str, **kwargs: Any) -> int:

The following error occurred when trying to handle this error:


  PoetryException

  Failed to install /home/webuser/.cache/pypoetry/artifacts/7b/3a/54/42ce43b579bda01b9d79022fb733811594441e7a32e9f9a5a98f672bdc/pyasn1-0.4.8-py2.py3-none-any.whl

  at ~/.local/share/pypoetry/venv/lib/python3.9/site-packages/poetry/utils/pip.py:51 in pip_install
       47│ 
       48│     try:
       49│         return environment.run_pip(*args)
       50│     except EnvCommandError as e:
    →  51│         raise PoetryException(f"Failed to install {path.as_posix()}") from e
       52│ 

The command '/bin/sh -c export PYCURL_SSL_LIBRARY=openssl && PYTHONUSERBASE="/home/webuser/.local/" poetry install --without dev' returned a non-zero code: 1

Exited with code exit status 1
```

**Comment by neersighted** [comment] 2022-09-01 11:08
It looks like you may have turned off virtual environment creation, which will indeed cause Poetry to install to the system site-packages. This is tangential to this issue -- can you please migrate to Discord or a discussion if you require additional advice on using Poetry in a container?

**Comment by neersighted** [comment] 2022-09-01 11:09
I'm going to close this as it appears to not be a regression, but instead transient conflicts between the union of Poetry and the root project's dependency trees resulting in expected instability when installing both into the same environment.

**Closed by neersighted** 2022-09-01 11:09 UTC
Labels: Bug, Triage

**Comment by sullivancolin** [comment] 2022-09-01 16:33
I'm encountering this issue as well, and a bit confused.

My Dockerfile has the following lines:

```docker
RUN pip install --upgrade pip
RUN curl -sSL https://install.python-poetry.org | python3 -
ENV PATH "/home/vscode/.poetry/bin:$PATH"
RUN /home/vscode/.local/bin/poetry config virtualenvs.create false
```

As you can see I am using the currently recommended way of installing poetry (1.2).  

The documentation says: 
> We provide a custom installer that will install Poetry in a new virtual environment to isolate it from the rest of your system. This ensures that dependencies will not be accidentally upgraded or uninstalled, and allows Poetry to manage its own environment.

I interpreted this to mean that it would be safe to install dependencies into system python inside a Docker container because poetry itself was in it's own environment (same with a pipx install).

Was it never the case in poetry<1.2 that it was safe to install in dependencies without a virtual environment?  If so, what's changed that allowed it to succeed previously and fail now?
