### ISSUE TITLE
Need a way to override PyPi globally as a default repo

### ISSUE THREAD

**Issue by Felix-neko** [python-poetry/poetry#5005] opened 2022-01-07 23:37 UTC
Hi folks! I'm working at a infosec-fetishist organization and have to include

```
[[tool.poetry.source]]
name = "blablabla_artifactory"
url = "http://binary/artifactory/api/pypi/pipy-virtual/simple"
default = true
```

in each of my projects that I deploy on our private servers that don't have direct access to PyPi (we have access only to private artifactory server in local network)

And when I'm working remotely and debugging my projects at home, I have to comment this out to be able to download and install dependencies from PyPi.

If I include this snippet to `~/.config/pypoetry/config.toml` it does not help: Poetry still tries to download packages directly from PyPi.

I need a way to set a per-user global config option to download packages from a given private repo as a default one (just like it's done in `pip.conf`). Please add this, we **really** need it.

**Comment by Felix-neko** [comment] 2022-01-08 13:11
UPD: The only workaround I can make just now is `poetry export -o requirements.txt` at home, add it to Git and `pip install` it manually with virtualenv on the server (without Poetry). But it's also extremely inconvenient = ((

**Comment by bmarroquin** [comment] 2022-01-08 19:42
@Felix-neko I added a PR to address this, check out #4944 and let me know if you have any feedback. This issue will probably be closed as this has been asked many times. See #1632 and #3355

**Comment by Felix-neko** [comment] 2022-01-08 21:13
@bmarroquin , thank you, i'll surely try it tomorrow  (i'm away from keyboard now). I'll write you in comments if I get stuck ^_^

**Comment by Felix-neko** [comment] 2022-01-09 09:52
> @Felix-neko I added a PR to address this, check out #4944 and let me know if you have any feedback. This issue will probably be closed as this has been asked many times. See #1632 and #3355

I've tested it. It worked, and it's really helpful in my case. I'm glad that, finally, poetry community implemented this ^__^

**Comment by neersighted** [comment] 2022-10-04 01:29
Closing as a duplicate of #1632

**Closed by neersighted** 2022-10-04 01:29 UTC
Labels: status/duplicate
