### ISSUE TITLE
Have a way to bypass TooManyRedirects 

### ISSUE THREAD

**Issue by pierresouchay** [python-poetry/poetry#5826] opened 2022-06-10 11:32 UTC
- [x] I am on the poetry version 1.1.13
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Mac OS or Linux, any version
- **Poetry version**: 1.1.13

## Issue
Hello,

Since today, it seems that some packages on pypi return some kind of infinite loop, example:

```bash
curl -L https://pypi.org/pypi/Werkzeug/json
curl: (47) Maximum (50) redirects followed
```

Such package cause poetry to fail:
```
poetry add Werkzeug

  TooManyRedirects

  Exceeded 30 redirects.

  at ~/hello-pip/venv/lib/python3.10/site-packages/requests/sessions.py:191 in resolve_redirects
      187│             except (ChunkedEncodingError, ContentDecodingError, RuntimeError):
      188│                 resp.raw.read(decode_content=False)
      189│
      190│             if len(resp.history) >= self.max_redirects:
    → 191│                 raise TooManyRedirects(
      192│                     f"Exceeded {self.max_redirects} redirects.", response=resp
      193│                 )
      194│
      195│             # Release the connection back into the pool.
```

But this issue also appear on existing projects with existing lock file, eg:

```
poetry install
Installing dependencies from lock file

Package operations: 1 install, 0 updates, 0 removals

  • Installing werkzeug (2.0.3): Failed

  TooManyRedirects

  Exceeded 30 redirects for https://pypi.org/pypi/Werkzeug/2.0.3/json.

  at ~/work/python-dev/butterfly/venv/lib/python3.9/site-packages/requests/sessions.py:166 in resolve_redirects
      162│             except (ChunkedEncodingError, ContentDecodingError, RuntimeError):
      163│                 resp.raw.read(decode_content=False)
      164│
      165│             if len(resp.history) >= self.max_redirects:
    → 166│                 raise TooManyRedirects('Exceeded {} redirects for {}.'.format(self.max_redirects, url), response=resp)
      167│
      168│             # Release the connection back into the pool.
      169│             resp.close()
      170│
```

=> If I simply remove the package from venv, it get broken.

Is the is a way to avoid such behavior? (Currently, all of our CIs are broken because of this package)

Note that pip does not have this behavior:
```bash
pip install Werkzeug
Looking in indexes: https://pypi.python.org/simple/
Collecting Werkzeug
  Downloading Werkzeug-2.1.2-py3-none-any.whl (224 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 224.9/224.9 KB 4.5 MB/s eta 0:00:00
Installing collected packages: Werkzeug
Successfully installed Werkzeug-2.1.2
```

**Comment by rubenaranamorera** [comment] 2022-06-10 11:40
Experiencing this also, is there any known workarround?

**Comment by johnthagen** [comment] 2022-06-10 11:41
This broke all of our CI that uses Poetry. This should probably be marked critical.

**Comment by iamhatesz** [comment] 2022-06-10 11:42
Same situation for me, can't do `poetry lock`.

**Comment by johnthagen** [comment] 2022-06-10 11:44
PyPA status update:

- https://github.com/pypa/warehouse/issues/11554#issuecomment-1152273038

**Comment by studio3104** [comment] 2022-06-10 11:46
I'm facing completely the same situation.
In my case, `poetry install` doesn't work if `TA-Lib` contains in `pyproject.toml`, works if it's commented out. But of cource the project doesn't work if I do so...

**Comment by olegZastavnyi** [comment] 2022-06-10 12:19
I've got the same problem for poetry v.1.1.6.

**Comment by paul-tharun** [comment] 2022-06-10 12:25
@olegZastavnyi it is not an issue with poetry. Pypi is facing some issues so it would be fixed in 1-2 hours

**Comment by YongWookHa** [comment] 2022-06-10 12:26
Same problem here.
`poetry add`, `poetry install`, any commands don't work.
Is it a server problem?

**Comment by gmagannaDevelop** [comment] 2022-06-10 12:41
@paul-tharun are you sure about this? To me it seems to be an issue related to `poetry` because using `pip` and `conda` do not fail when trying to install pillow, while `poetry` does.

**Comment by roma-glushko** [comment] 2022-06-10 12:45
Hey people, I have just faced the same issue with the deprecated lib:
<img width="839" alt="image (2)" src="https://user-images.githubusercontent.com/9402690/173066916-5214eb7b-dccb-4ff4-84fb-e4e1b578351d.png">

Have we come up any fix for this issue? 🙏

**Comment by lars-reimann** [comment] 2022-06-10 12:45
> @paul-tharun are you sure about this? To me it seems to be an issue related to `poetry` because using `pip` and `conda` do not fail when trying to install pillow, while `poetry` does.

poetry uses a different endpoint than pip/conda.

**Comment by neersighted** [comment] 2022-06-10 13:10
Hi, there's no way to work around a broken PyPI in Poetry as the API endpoints we need returning junk data mean we can't find packages to install. I'm going to close this for now since the relevant PyPI issue has been linked -- this should be resolved shortly according to upstream.

**Closed by neersighted** 2022-06-10 13:10 UTC
Labels: Bug, Upstream Issue

**Comment by txels** [comment] 2022-06-10 14:31
This is how I have implemented falling back to pip in my CI from poetry:

```
poetry export --dev > requirements.txt
pip install -r requirements.txt
```

**Comment by dstufft** [comment] 2022-06-10 14:42
FWIW, PyPI considers the Simple API to be our "Tier 1" API, and we will typically go to great lengths to try not to break that.

Any other part of PyPI we consider to be a best effort "Tier 2" endpoint, and we're more willing to have short term breakages if needed. It's not recommended for any sort of critical system to rely on anything but the Simple API. If something needs more than that, we suggest writing a PEP to help promote more pieces into a "Tier 1" endpoint.

**Comment by roma-glushko** [comment] 2022-06-10 14:47
Based on the @dstufft comment, Poetry is better to use tier 1 APIs, right? 
@neersighted to your point about junk responses, this is something to consider in order to avoid the same things happening over and over again.

**Comment by roma-glushko** [comment] 2022-06-10 14:50
@sithembiso the latest update from pypi:

<img width="656" alt="Screen Shot 2022-06-10 at 17 50 08" src="https://user-images.githubusercontent.com/9402690/173091843-42bfd448-ac90-44b5-a6ad-5533080feac4.png">
 
Seems like libs that starts with "p" is still impacted by the issue.

**Comment by sithembiso** [comment] 2022-06-10 14:52
Thank you @roma-glushko that's very helpful.

**Comment by dstufft** [comment] 2022-06-10 14:54
To be clear, I have no idea what data poetry is pulling from the JSON API, so it's entirely possible that the data poetry is using doesn't exist in the simple api. In that case you're kinda stuck picking between:

1. Status quo, and accepting the increased chances of breakage every now and then.
    - I don't want to overstate this, we still do try not to break it or have downtime, but with no standard or documentated expectations for things like the JSON API, changes there tend to be at a larger risk to falling to [Hyrum's Law](https://www.hyrumslaw.com/).
2. Stop using that data, and use only the data available in the Simple API.
3. Go through the process to standardize an API that has the data you need or to add it to an existing standardized API.

We're OK with people picking any of those options :) I just wanted to call it out explicitly that if you're able to pick (2) or (3), you're less likely to run into random problems, but if you want to pick (1), that's totally fine.

**Comment by neersighted** [comment] 2022-06-10 14:55
> Based on the @dstufft comment, Poetry is better to use tier 1 APIs, right? @neersighted to your point about junk responses, this is something to consider in order to avoid the same things happening over and over again.

Poetry uses the [JSON API](https://warehouse.pypa.io/api-reference/json.html) to avoid the need to download distfiles in order to gather metadata. While we do still have support for the [Legacy API](https://warehouse.pypa.io/api-reference/legacy.html) in our codebase and we could technically switch PyPI back to using it by default, it would represent a significant regression for Poetry as our use case requires us to have package metadata during solving/locking and not merely at runtime like pip.

Similarly, it could be possible to fall back to the Legacy API, but I am really not sure that it's a good idea to maintain an untested/rarely used code path for the rare cases that PyPI is down. Falling back would also make Poetry much slower and download more data with seemingly no explanation.

Ultimately, I think that if the JSON API is less supported than the Legacy API, upstream should call that out in docs for downstreams first, and we should then reason about what kind of failure is acceptable if there is an issue with PyPI itself.

> Facing the same issue here:
> 
> ```
> ...
>   • Installing pillow (8.4.0)
>   • Installing pycodestyle (2.8.0)
>   TooManyRedirects
>   Exceeded 30 redirects.
>   at /usr/local/lib/python3.9/site-packages/requests/sessions.py:191 in resolve_redirects
>       187│                 url = urljoin(resp.url, requote_uri(url))
>       188│             else:
>       189│                 url = requote_uri(url)
>       190│ 
>     → 191│             prepared_request.url = to_native_string(url)
>       192│ 
>       193│             self.rebuild_method(prepared_request, resp)
>       194│ 
>       195│             # https://github.com/requests/requests/issues/1084
>   • Installing python-crontab (2.6.0)
> ...
> ```

Per upstream this is not fully resolved yet.

**Comment by dstufft** [comment] 2022-06-10 15:30
> Poetry uses the [JSON API](https://warehouse.pypa.io/api-reference/json.html) to avoid the need to download distfiles in order to gather metadata. While we do still have support for the [Legacy API](https://warehouse.pypa.io/api-reference/legacy.html) in our codebase and we could technically switch PyPI back to using it by default, it would represent a significant regression for Poetry as our use case requires us to have package metadata during solving/locking and not merely at install time like pip.

I'm sure you're aware, but just in case you're not, the metadata in the JSON API is historically very unreliable, and has a lot of caveats to trusting it. It will semi regularly just be missing and/or wrong depending on a number of factors.

> Ultimately, I think that if the JSON API is less supported than the Legacy API, upstream should call that out in docs for downstreams first, and we should then reason about what kind of failure is acceptable if there is an issue with PyPI itself.

The "Tier 1" thing isn't an official designation or anything, just in practice that's how we've typically regarded the APIs. We've primarily been concerned with getting people off of things like the XMLRPC api which are like, "please never use this" and haven't though too hard about it. Some of it is the nature of the JSON API being a wholly unstandardized API, so there's not as good of a sense of what we *can* change without breaking someone.

I do agree we should formalize this though, so I opened https://github.com/pypa/warehouse/issues/11559 :)
