### ISSUE TITLE
Parse git+https with URL formats different from Github does not work

### ISSUE THREAD

**Issue by Shawe82** [python-poetry/poetry#1857] opened 2020-01-10 07:26 UTC
- [ x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [ x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**:  MAC OS
- **Poetry version : 1.0.0

## Issue
Add git dependencies with https to URLs that differ from the URL format used by github does not work. I am using gitlab. The URL structure is like https://gitlab.something.io/f1/f2/my-repo.git. If I try to add that using
```
poetry add git+https://gitlab.something.io/f1/f2/my-repo.git
```
The URL is parsed incorrectly or rather not at all. This results in poetry executing
```
git clone  git+https://gitlab.something.io/f1/f2/my-repo.git
````
which certainly does not work because of the leading git+. From playing around, I think github URLS look like https://main-url/username/my-repo.git. The regex parser seems to expect something like that. However, gitlab can have several layers after the main URL until the actual repo name. This is not parsed correctly. Hence, I cannot add the repo using https. With ssh, everything works like a charm.

**Comment by finswimmer** [comment] 2020-01-10 07:32
Hello @Shawe82,

this is a duplicate of https://github.com/python-poetry/poetry/issues/1746 and will be fixed in the next release.

fin swimmer

**Closed by finswimmer** 2020-01-10 07:32 UTC
Labels: Bug
