### ISSUE TITLE
`cpython` interaction issue (`undefined symbol: _PyModule_Add`) which seems to occur with `poetry` on `python=3.11.0`

### ISSUE THREAD

**Issue by femtomc** [python-poetry/poetry#8452] opened 2023-09-19 14:47 UTC
Hello! Recently my CI/CD pipeline (with `poetry` -- installed via https://github.com/snok/install-poetry) has been broken suddenly. I tracked the problem to this issue -- which seems to involve some interaction with `poetry`:

https://github.com/python/cpython/issues/108525

As far as I can tell, there's no open issue investigating this.

**Comment by dimbleby** [comment] 2023-09-19 16:33
You haven't said what you think this project should be doing: but I expect a merge request fixing whatever it is that you think is broken would be welcome

**Comment by femtomc** [comment] 2023-09-19 19:18
I have no idea what I think this project should be doing, nor do I have the expertise to submit a merge request to fix it. Anecdotally, my read of the original issue thread is that there's some sort of ABI interaction (and possibly, `cpython` is the source).

It seems that updating Python version to 3.11.5 fixes the problem with latest `poetry` -- (my CI was running on 3.11.0).

If anything, it seems useful to have a issue which tags this problem for other users -- as I had to dig deep in my CI logs (and then, Googling to find the above issue in `cpython`).

Does that sound fair?

**Comment by dimbleby** [comment] 2023-09-19 19:21
if you can provide a way to reproduce a problem and a reason to think that it's a poetry bug, then raising an issue is the right thing to do.

However you haven't done either of those - or even said what the problem is that you are trying to report.  I don't see anything useful that anyone can do with this.

**Comment by femtomc** [comment] 2023-09-20 00:12
Sure, I can attempt to put together a reproducer.

Separately — I’m just trying to be helpful by pointing out something I noticed while developing a package, and finding a thread _where several people seemed to note that the same issue stemmed from something in poetry_ — all seemingly users of poetry.

After a search for similar issues, I decided to open one _assuming it would be useful for someone to know about_ outside of the cpython repo (perhaps, say, in poetry — a common use point for responders in the linked issue)

You are of course allowed to respond in whatever way you choose — but I’m a little surprised that your response is “fix it yourself, and it’s not useful to know about this” irrespective of whether I can provide a reproducer.

Why would I want to contribute a PR to a package when a maintainer responds in that sort of way?

**Comment by femtomc** [comment] 2023-09-20 00:41
Here's a simple reproducer (as a repo, with a CI job): https://github.com/femtomc/8452-minimal-repro/actions/runs/6242454039/job/16946411608

I don't believe that the other actions are causing the issue e.g. https://github.com/snok/install-poetry/blob/main/main.sh (for instance) is using the officially recommended way to install `poetry` (via `curl`).

I've created two jobs -- one with `python=3.11.0` and one with `python=3.11.5`. One passes, and one fails.

**Comment by dimbleby** [comment] 2023-09-20 07:36
I notice that stack also includes python 3.11.5, even though it's from the intended python 3.11.0 repro.

Perhaps what you are discovering here is actually some confusion in github's caching of tools in CI pipelines.

**Comment by femtomc** [comment] 2023-09-21 00:43
I will retry and remove `nox-poetry`, thanks for noticing that.

**Comment by lazka** [comment] 2023-09-24 18:50
Drive by comment: The _PyModule_Add symbol was added in 3.11.5 and is also used by some of the included extension modules in CPython. Afair this is the first time such a change happened with a bugfix release in the past years. So this exposes broken environments where libpython and the stdlib of different cpython patch versions are mixed for some reason.

**Comment by abn** [comment] 2024-03-03 22:22
Root cause is as identified by @lazka. This is not a Poetry issue, but rather an issue with the system environment setup. The project at https://github.com/snok/install-poetry is not affiliated with nor maintained by the Poetry project maintainers.

Closing this issue as there is no Poetry action here.

**Closed by abn** 2024-03-03 22:22 UTC
Labels: kind/bug, status/triage
