### ISSUE TITLE
[EnvCommandError] returned on `poetry install` and `poetry env`

### ISSUE THREAD

**Issue by ernopp** [python-poetry/poetry#2629] opened 2020-07-03 18:43 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**:  Windows 10 Pro
- **Poetry version**:  1.0.9
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://github.com/ernopp/smilebot/blob/master/pyproject.toml

## Issue

Hi

There is an issue with my poetry installation

I am on version 1.0.9

```
C:\Users\ernest\dev\smilebot>poetry -V
Poetry version 1.0.9
```

My TOML appears correct

```
C:\Users\ernest\dev\smilebot>poetry check
All set!
```

But when I try to run `poetry env info` or `poetry install` (and same is true of many other commands I suspect) I get:

```
C:\Users\ernest\dev\smilebot>poetry install -vvv

[EnvCommandError]
Command ['C:\\Users\\ernest\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\shoponsmile-python-ovOS_Rxi-py3.8\\Scripts\\python.exe', '-'] errored with the following return code 1, and output:
The system cannot find the path specified.
input was : import sys

if hasattr(sys, "real_prefix"):
    print(sys.real_prefix)
elif hasattr(sys, "base_prefix"):
    print(sys.base_prefix)
else:
    print(sys.prefix)


Traceback (most recent call last):
  File "C:\Users\ernest\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\clikit\console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "C:\Users\ernest\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\clikit\api\command\command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "C:\Users\ernest\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\clikit\api\command\command.py", line 163, in _do_handle
    self._dispatcher.dispatch(PRE_HANDLE, event)
  File "C:\Users\ernest\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\clikit\api\event\event_dispatcher.py", line 22, in dispatch
    self._do_dispatch(listeners, event_name, event)
  File "C:\Users\ernest\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\clikit\api\event\event_dispatcher.py", line 89, in _do_dispatch
    listener(event, event_name, self)
  File "C:\Users\ernest\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\poetry\console\config\application_config.py", line 89, in set_env
    env = env_manager.create_venv(io)
  File "C:\Users\ernest\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\poetry\utils\env.py", line 489, in create_venv
    env = self.get(reload=True)
  File "C:\Users\ernest\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\poetry\utils\env.py", line 352, in get
    return VirtualEnv(venv)
  File "C:\Users\ernest\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\poetry\utils\env.py", line 1022, in __init__
    self._base = Path(self.run("python", "-", input_=GET_BASE_PREFIX).strip())
  File "C:\Users\ernest\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\poetry\utils\env.py", line 856, in run
    return self._run(cmd, **kwargs)
  File "C:\Users\ernest\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\poetry\utils\env.py", line 1089, in _run
    return super(VirtualEnv, self)._run(cmd, **kwargs)
  File "C:\Users\ernest\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\poetry\utils\env.py", line 893, in _run
    raise EnvCommandError(e, input=input_)
```

I can see and run the python executable at `C:\Users\ernest\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\shoponsmile-python-ovOS_Rxi-py3.8\Scripts`...

This happens whether I install poetry via pip or via the curl command (tried both)

Any help appreciated

Thanks

**Comment by tomzx** [comment] 2020-08-08 06:21
Can you make sure that the virtual environment in `C:\\Users\\ernest\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\shoponsmile-python-ovOS_Rxi-py3.8` was properly created?

It looks like you're having conflicting pythons running. Do you happen to either be in an existing virtual environment or using PyCharm by chance/bad luck?

**Comment by LeGmask** [comment] 2020-08-29 09:19
I have the same issue, but removing virtualenv fix the thing...

**Comment by tulis** [comment] 2021-01-29 23:20
I'm also experiencing the same thing. I just installed python 3.9 from windows store and install poetry version 1.1.4.

Here is the error message:
```
$ poetry -V
Poetry version 1.1.4

$ poetry check
All set!

$ poetry install -vvv

  Stack trace:

  11  ~\.poetry\lib\poetry\_vendor\py3.9\clikit\console_application.py:131 in run
       129│             parsed_args = resolved_command.args
       130│
     → 131│             status_code = command.handle(parsed_args, io)
       132│         except KeyboardInterrupt:
       133│             status_code = 1

  10  ~\.poetry\lib\poetry\_vendor\py3.9\clikit\api\command\command.py:120 in handle
       118│     def handle(self, args, io):  # type: (Args, IO) -> int
       119│         try:
     → 120│             status_code = self._do_handle(args, io)
       121│         except KeyboardInterrupt:
       122│             if io.is_debug():

   9  ~\.poetry\lib\poetry\_vendor\py3.9\clikit\api\command\command.py:163 in _do_handle
       161│         if self._dispatcher and self._dispatcher.has_listeners(PRE_HANDLE):
       162│             event = PreHandleEvent(args, io, self)
     → 163│             self._dispatcher.dispatch(PRE_HANDLE, event)
       164│
       165│             if event.is_handled():

   8  ~\.poetry\lib\poetry\_vendor\py3.9\clikit\api\event\event_dispatcher.py:22 in dispatch
        20│
        21│         if listeners:
     →  22│             self._do_dispatch(listeners, event_name, event)
        23│
        24│         return event

   7  ~\.poetry\lib\poetry\_vendor\py3.9\clikit\api\event\event_dispatcher.py:89 in _do_dispatch
        87│                 break
        88│
     →  89│             listener(event, event_name, self)
        90│
        91│     def _sort_listeners(self, event_name):  # type: (str) -> None

   6  ~\.poetry\lib\poetry\console\config\application_config.py:119 in set_env
       117│
       118│         env_manager = EnvManager(poetry)
     → 119│         env = env_manager.create_venv(io)
       120│
       121│         if env.is_venv() and io.is_verbose():

   5  ~\.poetry\lib\poetry\utils\env.py:626 in create_venv
        624│
        625│         cwd = self._poetry.file.parent
     →  626│         env = self.get(reload=True)
        627│
        628│         if not env.is_sane():

   4  ~\.poetry\lib\poetry\utils\env.py:489 in get
        487│                 return SystemEnv(Path(sys.prefix))
        488│
     →  489│             return VirtualEnv(venv)
        490│
        491│         if env_prefix is not None:

   3  ~\.poetry\lib\poetry\utils\env.py:1248 in __init__
       1246│         # from inside the virtualenv.
       1247│         if base is None:
     → 1248│             self._base = Path(self.run("python", "-", input_=GET_BASE_PREFIX).strip())
       1249│
       1250│     @property

   2  ~\.poetry\lib\poetry\utils\env.py:1037 in run
       1035│         bin = self._bin(bin)
       1036│         cmd = [bin] + list(args)
     → 1037│         return self._run(cmd, **kwargs)
       1038│
       1039│     def run_pip(self, *args, **kwargs):

   1  ~\.poetry\lib\poetry\utils\env.py:1332 in _run
       1330│             self.unset_env("__PYVENV_LAUNCHER__")
       1331│
     → 1332│             return super(VirtualEnv, self)._run(cmd, **kwargs)
       1333│
       1334│     def execute(self, bin, *args, **kwargs):

  EnvCommandError

  Command C:\Users\foobar\AppData\Local\pypoetry\Cache\virtualenvs\helloworld-2Fe2M40X-py3.9\Scripts\python.exe - errored with the following return code 1, and output:
  The system cannot find the path specified.
  input was : import sys

  if hasattr(sys, "real_prefix"):
      print(sys.real_prefix)
  elif hasattr(sys, "base_prefix"):
      print(sys.base_prefix)
  else:
      print(sys.prefix)


  at ~\.poetry\lib\poetry\utils\env.py:1074 in _run
      1070│                 output = subprocess.check_output(
      1071│                     cmd, stderr=subprocess.STDOUT, **kwargs
      1072│                 )
      1073│         except CalledProcessError as e:
    → 1074│             raise EnvCommandError(e, input=input_)
      1075│
      1076│         return decode(output)
      1077│
      1078│     def execute(self, bin, *args, **kwargs):
```

This is my `pyproject.toml` file just in case:
```
[tool.poetry]
name = "helloworld"
version = "0.1.0"
description = ""
authors = ["tulis"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pytest = "^4.6"
black = "^20.8b1"
isort = "^5.7.0"
flake8 = "^3.8.4"
mypy = "^0.800"
pre-commit = "^2.10.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

**Comment by adriaanbd** [comment] 2021-02-03 03:04
Similar error here but my stack trace is short. It seems the system can't find the path specified:

```
~C:\Users\johndoe\AppData\Local\pypoetry\Cache\virtualenvs\sampleapp-qzB4MRJW-py3.9\Scripts\python.exe - errored with the following return code 1, and output:
  The system cannot find the path specified.

      print(sys.real_prefix)
  elif hasattr(sys, "base_prefix"):
      print(sys.base_prefix)
  else:
      print(sys.prefix)


  at ~\.poetry\lib\poetry\utils\env.py:1074 in _run
      1070│                 output = subprocess.check_output(
      1071│                     cmd, stderr=subprocess.STDOUT, **kwargs
      1072│                 )
      1073│         except CalledProcessError as e:
    → 1074│             raise EnvCommandError(e, input=input_)
      1075│
      1076│         return decode(output)
      1077│
      1078│     def execute(self, bin, *args, **kwargs):
```

**Comment by hendrikweisser** [comment] 2021-02-24 18:19
I'm having the same issue (with Poetry 1.1.4, Python 3.8.8 on Windows 10). I'm trying to install dependencies for this project: https://github.com/tleonardi/nanocompore (see `pyproject.toml` there).

Here's my error output (very similar to @adriaanbd's above):
```
Creating virtualenv nanocompore-jTAgZUEe-py3.8 in C:\Users\hendrik.weisser\AppData\Local\pypoetry\Cache\virtualenvs

  EnvCommandError

  Command C:\Users\hendrik.weisser\AppData\Local\pypoetry\Cache\virtualenvs\nanocompore-jTAgZUEe-py3.8\Scripts\python.exe - errored with the following return code 1, and output:
  The system cannot find the path specified.
  input was : import sys

  if hasattr(sys, "real_prefix"):
      print(sys.real_prefix)
  elif hasattr(sys, "base_prefix"):
      print(sys.base_prefix)
  else:


  at ~\.poetry\lib\poetry\utils\env.py:1074 in _run
      1070│                 output = subprocess.check_output(
      1071│                     cmd, stderr=subprocess.STDOUT, **kwargs
      1072│                 )
      1073│         except CalledProcessError as e:
    → 1074│             raise EnvCommandError(e, input=input_)
      1075│
      1076│         return decode(output)
      1077│
      1078│     def execute(self, bin, *args, **kwargs):
```

Note that the `C:\Users\hendrik.weisser\AppData\Local\pypoetry\` folder doesn't exist in my case.


Based on [this comment](https://github.com/python-poetry/poetry/issues/2746#issuecomment-739439858), I tried commenting out the two lines in `Env._run`, but that gave a similar error:
```
  EnvCommandError

  Command ['C:\\Users\\hendrik.weisser\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\nanocompore-jTAgZUEe-py3.8\\Scripts\\python.exe', '-'] errored with the following return code 106, and output:
  No pyvenv.cfg file

[then same information as above]
```

**Comment by Riverfount** [comment] 2021-03-12 13:28
I'm having the same issue:
```$ poetry install
Creating virtualenv tests-F6YQ1RRR-py3.9 in /home/river/.cache/pypoetry/virtualenvs
Updating dependencies
Resolving dependencies... (11.9s)

Writing lock file

Package operations: 13 installs, 0 updates, 0 removals

  • Installing pyparsing (2.4.7)
  • Installing attrs (20.3.0)
  • Installing iniconfig (1.1.1)
  • Installing packaging (20.9)
  • Installing pluggy (0.13.1)
  • Installing py (1.10.0)
  • Installing toml (0.10.2)
  • Installing asgiref (3.3.1)
  • Installing pytest (6.2.2)
  • Installing pytz (2021.1)
  • Installing sqlparse (0.4.1)
  • Installing django (3.1.7): Failed

  EnvCommandError

  Command ['/home/river/.cache/pypoetry/virtualenvs/tests-F6YQ1RRR-py3.9/bin/pip', 'install', '--no-deps', 'file:///home/river/.cache/pypoetry/artifacts/80/9f/e8/7dbac946baeff06413dea73548571fa188758ff084c6258f4e50a09137/Django-3.1.7-py3-none-any.whl'] errored with the following return code 2, and output: 
  Processing /home/river/.cache/pypoetry/artifacts/80/9f/e8/7dbac946baeff06413dea73548571fa188758ff084c6258f4e50a09137/Django-3.1.7-py3-none-any.whl
  ERROR: Exception:
  Traceback (most recent call last):
    File "/home/river/.cache/pypoetry/virtualenvs/tests-F6YQ1RRR-py3.9/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 216, in _main
      status = self.run(options, args)
    File "/home/river/.cache/pypoetry/virtualenvs/tests-F6YQ1RRR-py3.9/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
      return func(self, options, args)
    File "/home/river/.cache/pypoetry/virtualenvs/tests-F6YQ1RRR-py3.9/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 324, in run
      requirement_set = resolver.resolve(
    File "/home/river/.cache/pypoetry/virtualenvs/tests-F6YQ1RRR-py3.9/lib/python3.9/site-packages/pip/_internal/resolution/legacy/resolver.py", line 183, in resolve
      discovered_reqs.extend(self._resolve_one(requirement_set, req))
    File "/home/river/.cache/pypoetry/virtualenvs/tests-F6YQ1RRR-py3.9/lib/python3.9/site-packages/pip/_internal/resolution/legacy/resolver.py", line 391, in _resolve_one
      dist = abstract_dist.get_pkg_resources_distribution()
    File "/home/river/.cache/pypoetry/virtualenvs/tests-F6YQ1RRR-py3.9/lib/python3.9/site-packages/pip/_internal/distributions/wheel.py", line 29, in get_pkg_resources_distribution
      with ZipFile(self.req.local_file_path, allowZip64=True) as z:
    File "/home/river/.pyenv/versions/3.9.0/lib/python3.9/zipfile.py", line 1257, in __init__
      self._RealGetContents()
    File "/home/river/.pyenv/versions/3.9.0/lib/python3.9/zipfile.py", line 1324, in _RealGetContents
      raise BadZipFile("File is not a zip file")
  zipfile.BadZipFile: File is not a zip file
  WARNING: You are using pip version 20.2.2; however, version 21.0.1 is available.
  You should consider upgrading via the '/home/river/.cache/pypoetry/virtualenvs/tests-F6YQ1RRR-py3.9/bin/python -m pip install --upgrade pip' command.
  

  at ~/.poetry/lib/poetry/utils/env.py:1074 in _run
      1070│                 output = subprocess.check_output(
      1071│                     cmd, stderr=subprocess.STDOUT, **kwargs
      1072│                 )
      1073│         except CalledProcessError as e:
    → 1074│             raise EnvCommandError(e, input=input_)
      1075│ 
      1076│         return decode(output)
      1077│ 
      1078│     def execute(self, bin, *args, **kwargs):

  • Installing pytest-django (4.1.0)
```

**Comment by pawamoy** [comment] 2021-03-12 20:42
And one more!

The same thing happens when you cache and restore the Poetry cache directory in a Windows job in GitHub Workflow: https://github.com/pawamoy/duty/runs/2098485547?check_suite_focus=true. The only solution is to delete the virtualenv and recreate it. By the way I can't even `poetry env remove` it because it fails the same way, so I have to `rm -rf $(poetry env info -p)`.

**Comment by pawamoy** [comment] 2021-03-12 21:47
Here's what I ended up with in CI. Took me the entire evening to make things work on Windows.

```yaml
env:
  # To fix an error when running Poetry on Windows
  # (https://github.com/python-poetry/poetry/issues/2629),
  # we set Poetry's cache directory to .poetry_cache in the current directory.
  # It makes it easier to later remove the virtualenv when it's broken.
  # Absolute path is necessary to avoid this issue:
  # https://github.com/python-poetry/poetry/issues/3049
  POETRY_CACHE_DIR: ${{ github.workspace }}/.poetry_cache

jobs:

  tests:

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]

    runs-on: ${{ matrix.os }}

    steps:

    # checkout repo, setup python, install poetry, etc.

    - name: Set up the cache
      uses: actions/cache@v1
      with:
        path: .poetry_cache
        key: tests-poetry-cache-${{ matrix.os }}-py${{ matrix.python-version }}

    - name: Set up the project
      run: poetry install -vv || { rm -rf .poetry_cache/virtualenvs/*; poetry install -vv; }
```

**Comment by Riverfount** [comment] 2021-03-13 01:07
I solve my issue here changed the Python version. If I use Python 3.9.0 I have this problem, but if I use Python 3.8.6 (the last version of Python 3.8) all works ok! I'm in the Debian GNU/Linux system!

**Comment by GGleGrand** [comment] 2021-04-09 12:58
Simplest fix on windows for me was
$env:POETRY_CACHE_DIR =  'C:\Users\Myuser\.poetry_cache'

**Comment by mcous** [comment] 2021-07-12 18:56
I ran into this issue trying to use Poetry with Windows + Python 3.6 in GitHub actions, where I have `actions/cache` configured to cache and restore Poetry's virtualenv directory. After doing a little digging, I discovered that Poetry's own GitHub Actions CI for Windows + Python 3.6 (which also caches the `.venv` folder and restores it) is [experiencing this same issue](https://github.com/python-poetry/poetry/runs/3039982756?check_suite_focus=true#step:10:7).

Poetry's CI workflow includes a step to nuke the virtualenv if it appears unhealthy after a cache restore, which looks to be how they work around it.

https://github.com/python-poetry/poetry/blob/527882380fd7aecd7c34922a7bc888226a5737ff/.github/workflows/main.yml#L75-L78

**Comment by dkrystki** [comment] 2021-09-14 01:48
I was having the same issue when caching .venv directory on a Windows runner. 
It turns out restoring cache breaks symlinks in the virtual env.

The solution is to first create virtualenv manually with:
`python -m venv .venv --copies`

Which does not rely on symlinks and then run:
`poetry install`

**Comment by vinhloc30796** [comment] 2021-09-17 18:19
Same here for me: Python 3.9.6 gets this problem, but not Python 3.8.6. I'm on Windows 11.

**Comment by khanh41** [comment] 2021-09-25 16:09
You need check your python version and install again.
Example: `Windows x86-64` or `Windows x86`.
https://www.python.org/downloads/release/python-375/

I didn't check my window and installed `Python - Windows x86` then get error. 
After that, i uninstall python and reinstall with `Python - Windows x86-64`. 
remove `venv` and `poetry install` again

**Comment by jmorgadov** [comment] 2021-11-18 15:10
> I solve my issue here changed the Python version. If I use Python 3.9.0 I have this problem, but if I use Python 3.8.6 (the last version of Python 3.8) all works ok! I'm in the Debian GNU/Linux system!

Thi works for me, Thx!! (also in Debian GNU/Linux system)

**Comment by floatingpurr** [comment] 2021-12-15 09:55
> 8/7dbac946baeff06413dea73548571fa188758ff084c6258f4e50a09137/Django-3.1.7-py3-none-any.whl
>   ERROR: Exception:
>   Traceback (most recent call last):

Same problem here for Python 3.6 on Win 10: https://github.com/floatingpurr/sync_with_poetry/runs/4523910263?check_suite_focus=true. I'm going to disable caching for that environment. @pawamoy, I saw you got rid of poetry in your CI and you switched to pdm. May I ask you if this issue played a role in this choice?

**Comment by floatingpurr** [comment] 2021-12-22 15:11
After working for a while in GH Actions with Windows + Python 3.10.0, now it doesn't work anymore since GH Actions started using 3.10.1. 

GH Action [here](https://github.com/floatingpurr/sync_with_poetry/blob/2e88cd82c11815a638b06e3f52688b51956daeef/.github/workflows/tests.yml)

Error:

```
Run poetry install

  EnvCommandError

  Command D:\a\sync_with_poetry\sync_with_poetry\.venv\Scripts\python.exe -W ignore - errored with the following return code 103, and output: 
  No Python at 'C:\hostedtoolcache\windows\Python\3.10.0\x64\python.exe'
````
See the complete test run here: https://github.com/floatingpurr/sync_with_poetry/runs/4608289123?check_suite_focus=true

Any hints?

**Comment by 1Mark** [comment] 2022-05-11 15:33
> I ran into this issue trying to use Poetry with Windows + Python 3.6 and 3.9 in GitHub actions, where I have `actions/cache` configured to cache and restore Poetry's virtualenv directory. After doing a little digging, I discovered that Poetry's own GitHub Actions CI for Windows + Python 3.6 (which also caches the `.venv` folder and restores it) is [experiencing this same issue](https://github.com/python-poetry/poetry/runs/3039982756?check_suite_focus=true#step:10:7).
> 
> Poetry's CI workflow includes a step to nuke the virtualenv if it appears unhealthy after a cache restore, which looks to be how they work around it.
> 
> https://github.com/python-poetry/poetry/blob/527882380fd7aecd7c34922a7bc888226a5737ff/.github/workflows/main.yml#L75-L78

Alternatively clicking "Clear runner caches" in (Gitlab) CI works too.

**Comment by GeoXydias** [comment] 2022-05-31 14:35
> 

I was facing the issue with Python3.10.4

**Comment by ashrasmun** [comment] 2022-07-06 11:35
I found another case when this error appears. It's very specific, but I'd rather add it here if someone comes here from google.

I have custom setup for command line aliases whenever I access command line. I do it by adding AutoRun field in regedit for "Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Command Processor" record. If the path points to wrong location, you will get the aforementioned error with poetry.

**Comment by 1Mark** [comment] 2022-08-24 15:08
Does anyone here also have https://pypi.org/project/uuid/ this package installed im wondering if there is some weird bug in this package.

**Comment by jduprey** [comment] 2022-09-23 22:12
> I was having the same issue when caching .venv directory on a Windows runner. It turns out restoring cache breaks symlinks in the virtual env.
> 
> The solution is to first create virtualenv manually with: `python -m venv .venv --copies`
> 
> Which does not rely on symlinks and then run: `poetry install`

This worked for me.. but why?  poetry version 1.1.11

**Comment by neersighted** [comment] 2022-09-23 22:16
Closing this for now as there are a variety of issues talked about here -- all of them unrelated and disparate. The original issue was with Microsoft Store Python -- environments created using MS Store Python should be mostly working now, please open a new ticket for any specific issues.

Others in here have issues with bad caching across Python versions -- using a symlink virtual environment will break when the Python executable changes. To guard against this, you should either better control your cache invalidation in CI.

The final issue that @jduprey chimes in on is unclear on what the root cause is -- details and a reproduction are needed to reason about it. However, Poetry 1.1 is not receiving updates, so reports that only apply to 1.1 are not being accepted. Please test again on Poetry 1.2 if you think you are hitting a bug (and file a detailed bug report).

**Closed by neersighted** 2022-09-23 22:16 UTC
Labels: kind/bug, status/triage

**Comment by 1Mark** [comment] 2022-09-29 09:10
I really dislike this approach, an issue was reported against an old version, has all the details, and it wasn't fixed yet it's closed, then another user will have to open another ticket for the same problem. I appreciate the original reported version is no longer supported but if the issue exists in the latest poetry version it doesn't make sense to close this ticket.

**Comment by neersighted** [comment] 2022-09-29 14:31
@1Mark The issue is that this is years old, the OP never provided sufficient detail to reproduce/check that this was fixed for them, and many users have chimed in with related but not the same (mostly configuration/usage) issues in the comments.

It's hard enough to reason about a years and version old issue report with no response or reproduction, let alone what has become a grab bag of "me too" that may or may not be the same root cause or even operating system.

It does create a higher barrier if someone runs into trouble, but **this issue** was already not helpful to both those experiencing this issue and those trying to solve it -- without high quality issue reports it is very hard to fix bugs that are not obvious.

**Comment by 1Mark** [comment] 2022-09-29 17:58
> @1Mark The issue is that this is years old, the OP never provided sufficient detail to reproduce/check that this was fixed for them, and many users have chimed in with related but not the same (mostly configuration/usage) issues in the comments.
> 
> It's hard enough to reason about a years and version old issue report with no response or reproduction, let alone what has become a grab bag of "me too" that may or may not be the same root cause or even operating system.
> 
> It does create a higher barrier if someone runs into trouble, but **this issue** was already not helpful to both those experiencing this issue and those trying to solve it -- without high quality issue reports it is very hard to fix bugs that are not obvious.

That's very enlightening thank you @neersighted

**Comment by Mawar2** [comment] 2022-11-08 00:49
> I was having the same issue when caching .venv directory on a Windows runner. It turns out restoring cache breaks symlinks in the virtual env.
> 
> The solution is to first create virtualenv manually with: `python -m venv .venv --copies`
> 
> Which does not rely on symlinks and then run: `poetry install`

Thank you this worked for me.
