### ISSUE TITLE
Transitive private dependencies from `explicit` sources are not pulled

### ISSUE THREAD

**Issue by maksbotan** [python-poetry/poetry#7981] opened 2023-05-22 09:26 UTC
- **Poetry version**: 1.5.0
- **Python version**: 3.10.11
- **OS version and name**: macOS 12.6.3
- **pyproject.toml**: 

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

Consider this scenario. I add a private source with `priority = explicit` and then add package A from that repo. A, in turn, depends on B, also in that repo. However, poetry will not look for `B` in the repo, only on PyPI:

```
poetry add A --source=biocad-gitlab --lock -vvv
```

```
Source (biocad-gitlab): 1 packages found for A >=0.4.42,<0.5.0
   1: selecting A (0.4.42)
   1: derived: B (>=4.2.1,<5.0.0)
[urllib3.connectionpool] https://pypi.org:443 "GET /simple/B/ HTTP/1.1" 404 13
Source (PyPI): No packages found for B
Source (PyPI): 0 packages found for B >=4.2.1,<5.0.0
Falling back to installed packages to discover metadata for B
Found 1 compatible packages for B
Source (PyPI): Getting info for B (4.2.10) from PyPI
[urllib3.connectionpool] https://pypi.org:443 "GET /pypi/B/4.2.10/json HTTP/1.1" 404 24
Falling back to installed packages to discover metadata for B
Found 1 compatible packages for B
```

4.2.10 is the version that was cached somewhere, I was not able to find it. It is not the latest fitting version in the repo.

If I change repo to `secondary` or `supplemental`, everything works fine:

```
Source (PyPI): Getting info for B (4.2.10) from PyPI
[keyring.backend] Loading KWallet
[keyring.backend] Loading SecretService
[keyring.backend] Loading Windows
[keyring.backend] Loading chainer
[keyring.backend] Loading libsecret
[keyring.backend] Loading macOS
Creating new session for pypi.org
[urllib3.connectionpool] Starting new HTTPS connection (1): pypi.org:443
[urllib3.connectionpool] https://pypi.org:443 "GET /pypi/B/4.2.10/json HTTP/1.1" 404 24
Creating new session for gitlab.math.bio
[urllib3.connectionpool] Starting new HTTPS connection (1): gitlab.math.bio:443
[urllib3.connectionpool] https://gitlab.math.bio:443 "GET /api/v4/groups/biocad/-/packages/pypi/simple/B/ HTTP/1.1" 200 None
```

This may be related to #7957, but I'm not sure.

I think this is really a limitation in `explicit` repository support.

**Comment by dimbleby** [comment] 2023-05-22 09:46
seems completely expected - you haven't explicitly said that you want B from the explicit source, so poetry won't look there.

**Comment by maksbotan** [comment] 2023-05-22 09:51
@dimbleby so I am supposed to list all transitive deps in my `pyproject.toml` when using `explicit` sources? Does not seem like good UX.

First of all, there may be a lot of them.

Second, this would mean manual version management for those deps instead of relying completely on poetry's resolver.

**Comment by dimbleby** [comment] 2023-05-22 09:59
If this is your use case, then don't use an explicit source.

The docs are very clear that the behaviour you are seeing is exactly as intended:

> [Explicit sources](https://python-poetry.org/docs/master/repositories/#explicit-package-sources) are considered only for packages that explicitly [indicate their source](https://python-poetry.org/docs/master/repositories/#package-source-constraint).

**Comment by maksbotan** [comment] 2023-05-22 10:09
Well, I did indicate a source for a package I added to my pyproject.toml (A in my example). I did not expect transitive dependencies to require special handling on my part.

If this is the official poetry position, then I guess the issue may be closed.

**Comment by ralbertazzi** [comment] 2023-05-22 12:53
This is both expected _and_ [documented](https://python-poetry.org/docs/master/repositories/#package-source-constraint)
> Package source keys are not inherited by their dependencies. In particular, if package-A is configured to be found in source = internal-pypi, and package-A depends on package-B that is also to be found on internal-pypi, then package-B needs to be configured as such in pyproject.toml

Poetry needs to support all use cases. Yours requires A and B to be fetched from the same source, while other use cases may want just A to be fetched from the explicit source, while keep fetching its dependencies from the default source.

You may also want to consider the `supplemental` priority option, which may better suit your needs (it won't require you to specify transitive dependencies in your toml file). A and B will be both fetched from your private source (assuming they don't exist in higher priority repositories) without requiring you to explicitly define B.

Closing as there's no actionable

**Closed by ralbertazzi** 2023-05-22 12:53 UTC
Labels: kind/bug, status/triage

**Comment by maksbotan** [comment] 2023-05-22 13:03
Oh, sorry, I must've missed that in the docs. Still very counterintuitive for me.

I'll probably stick to `supplemental` then.
