### ISSUE TITLE
Switch default dependency specification in configs

### ISSUE THREAD

**Issue by Tointoin** [python-poetry/poetry#5361] opened 2022-03-25 15:13 UTC
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

By default, a simple `poetry add mypackage` (without any specified version) would add a [caret requirement](https://python-poetry.org/docs/dependency-specification/#caret-requirements) to the `pyproject.toml` as follow: `mypackage = "^x.y.z"` (with latest version of `mypackage`).

It would be nice to be able to specify our favorite default dependency specification to the `poetry add` for instance with a specific `poetry config` option. Hence a good new default dependency specification could be a [wildcard requirement](https://python-poetry.org/docs/dependency-specification/#wildcard-requirements) `mypackage = "x.y.*"` with x and y latest major and minor.

**Comment by zEdS15B3GCwq** [comment] 2022-06-01 05:55
Similar to #5020

**Comment by finswimmer** [comment] 2022-06-01 06:05
Duplicate of #5020

**Closed by finswimmer** 2022-06-01 06:05 UTC
Labels: Feature, Triage
