### ISSUE TITLE
Problem with cache when installing in 2 Projects

### ISSUE THREAD

**Issue by FZetting** [python-poetry/poetry#4789] opened 2021-11-17 18:45 UTC
Hello,
i have here a problem when installing the same new modules in 2 Projects.

I delete the cache manually and install the modules in one project. Then i swithch to the next project and try to install the same modules and got these error messages.

After deleting the cache again manually the install work as expected.

PS C:\Users\fzett\Workspace\healthstorage-testing> poetry add sphinx myst-parser --dev
Using version ^4.3.0 for Sphinx
Using version ^0.15.2 for myst-parser

Updating dependencies
Resolving dependencies...

Writing lock file

Package operations: 18 installs, 0 updates, 0 removals

  • Installing markupsafe (2.0.1)
  • Installing alabaster (0.7.12)
  • Installing babel (2.9.1)
  • Installing docutils (0.17.1)
  • Installing jinja2 (3.0.3)
  • Installing markdown-it-py (1.1.0)
  • Installing imagesize (1.3.0)
  • Installing pygments (2.10.0)
  • Installing sphinxcontrib-htmlhelp (2.0.0)
  • Installing sphinxcontrib-applehelp (1.0.2)
  • Installing sphinxcontrib-jsmath (1.0.1)
  • Installing snowballstemmer (2.2.0)
  • Installing sphinxcontrib-devhelp (1.0.2)

  ValueError

  File \C:\Users\fzett\AppData\Local\pypoetry\Cache\artifacts\43\28\92\79000933ad30371dc938d9b368a9000e20ac0bb467a716c19ef1fbd3c7\docutils-0.17.1-py2.py3-none-any.whl does not exist

  at ~\AppData\Roaming\Python\Python39\site-packages\poetry\core\packages\file_dependency.py:40 in __init__
       36│             except FileNotFoundError:
       37│                 raise ValueError("Directory {} does not exist".format(self._path))
       38│
       39│         if not self._full_path.exists():
    →  40│             raise ValueError("File {} does not exist".format(self._path))
       41│
       42│         if self._full_path.is_dir():
       43│             raise ValueError("{} is a directory, expected a file".format(self._path))
       44│

  • Installing sphinxcontrib-qthelp (1.0.3)

  ValueError

  File \C:\Users\fzett\AppData\Local\pypoetry\Cache\artifacts\1e\28\b6\110e8fc8ccc0dafe21bbc521139d0d0674574f7daa6f6f90137bdb4759\Babel-2.9.1-py2.py3-none-any.whl does not exist

  at ~\AppData\Roaming\Python\Python39\site-packages\poetry\core\packages\file_dependency.py:40 in __init__
       36│             except FileNotFoundError:
       37│                 raise ValueError("Directory {} does not exist".format(self._path))
       38│
       39│         if not self._full_path.exists():
    →  40│             raise ValueError("File {} does not exist".format(self._path))
       41│
       42│         if self._full_path.is_dir():
       43│             raise ValueError("{} is a directory, expected a file".format(self._path))
       44│

  • Installing sphinxcontrib-serializinghtml (1.1.5)

  ValueError

  File \C:\Users\fzett\AppData\Local\pypoetry\Cache\artifacts\56\a5\74\11ccaa7737f06a10422027e0595b24d243af7a7a1dc4982dec22044c28\sphinxcontrib_devhelp-1.0.2-py2.py3-none-any.whl does not exist

  at ~\AppData\Roaming\Python\Python39\site-packages\poetry\core\packages\file_dependency.py:40 in __init__
       36│             except FileNotFoundError:
       37│                 raise ValueError("Directory {} does not exist".format(self._path))
       38│
       39│         if not self._full_path.exists():
    →  40│             raise ValueError("File {} does not exist".format(self._path))
       41│
       42│         if self._full_path.is_dir():
       43│             raise ValueError("{} is a directory, expected a file".format(self._path))
       44│

  ValueError

  File \C:\Users\fzett\AppData\Local\pypoetry\Cache\artifacts\be\b4\d9\6321eeb7ae4984092aa8c991c35508f61dc94cb47357699536c3ec7393\markdown_it_py-1.1.0-py3-none-any.whl does not exist

  at ~\AppData\Roaming\Python\Python39\site-packages\poetry\core\packages\file_dependency.py:40 in __init__
       36│             except FileNotFoundError:
       37│                 raise ValueError("Directory {} does not exist".format(self._path))
       38│
       39│         if not self._full_path.exists():
    →  40│             raise ValueError("File {} does not exist".format(self._path))
       41│
       42│         if self._full_path.is_dir():
       43│             raise ValueError("{} is a directory, expected a file".format(self._path))
       44│

  ValueError

  File \C:\Users\fzett\AppData\Local\pypoetry\Cache\artifacts\8d\eb\86\eec708bb3ff50c9780e78f36a9cb82cd9ff8030a90bd23b9a6f20aecca\sphinxcontrib_applehelp-1.0.2-py2.py3-none-any.whl does not exist

  at ~\AppData\Roaming\Python\Python39\site-packages\poetry\core\packages\file_dependency.py:40 in __init__
       36│             except FileNotFoundError:
       37│                 raise ValueError("Directory {} does not exist".format(self._path))
       38│
       39│         if not self._full_path.exists():
    →  40│             raise ValueError("File {} does not exist".format(self._path))
       41│
       42│         if self._full_path.is_dir():
       43│             raise ValueError("{} is a directory, expected a file".format(self._path))
       44│

  ValueError

  File \C:\Users\fzett\AppData\Local\pypoetry\Cache\artifacts\96\5c\68\c505397f41dd445fe3305ed42a0c203fe0f36fee2cbb522ef564d90d71\imagesize-1.3.0-py2.py3-none-any.whl does not exist

  at ~\AppData\Roaming\Python\Python39\site-packages\poetry\core\packages\file_dependency.py:40 in __init__
       36│             except FileNotFoundError:
       37│                 raise ValueError("Directory {} does not exist".format(self._path))
       38│
       39│         if not self._full_path.exists():
    →  40│             raise ValueError("File {} does not exist".format(self._path))
       41│
       42│         if self._full_path.is_dir():
       43│             raise ValueError("{} is a directory, expected a file".format(self._path))
       44│

  ValueError

  File \C:\Users\fzett\AppData\Local\pypoetry\Cache\artifacts\48\57\b7\0e44080d4c6f80ece83e427f90368b376fdec42759b60c2c37a04da23b\alabaster-0.7.12-py2.py3-none-any.whl does not exist

  at ~\AppData\Roaming\Python\Python39\site-packages\poetry\core\packages\file_dependency.py:40 in __init__
       36│             except FileNotFoundError:
       37│                 raise ValueError("Directory {} does not exist".format(self._path))
       38│
       39│         if not self._full_path.exists():
    →  40│             raise ValueError("File {} does not exist".format(self._path))
       41│
       42│         if self._full_path.is_dir():
       43│             raise ValueError("{} is a directory, expected a file".format(self._path))
       44│

  ValueError

  File \C:\Users\fzett\AppData\Local\pypoetry\Cache\artifacts\d2\22\96\2076357e64b369910aa24a20d5b719beb24a1487146e4742476ee1e2d8\sphinxcontrib_jsmath-1.0.1-py2.py3-none-any.whl does not exist

  at ~\AppData\Roaming\Python\Python39\site-packages\poetry\core\packages\file_dependency.py:40 in __init__
       36│             except FileNotFoundError:
       37│                 raise ValueError("Directory {} does not exist".format(self._path))
       38│
       39│         if not self._full_path.exists():
    →  40│             raise ValueError("File {} does not exist".format(self._path))
       41│
       42│         if self._full_path.is_dir():
       43│             raise ValueError("{} is a directory, expected a file".format(self._path))
       44│

  ValueError

  File \C:\Users\fzett\AppData\Local\pypoetry\Cache\artifacts\66\d0\cb\7228297c74d9280e7246b52187704724b0b0881e2762cdef34e04be778\sphinxcontrib_htmlhelp-2.0.0-py2.py3-none-any.whl does not exist

  at ~\AppData\Roaming\Python\Python39\site-packages\poetry\core\packages\file_dependency.py:40 in __init__
       36│             except FileNotFoundError:
       37│                 raise ValueError("Directory {} does not exist".format(self._path))
       38│
       39│         if not self._full_path.exists():
    →  40│             raise ValueError("File {} does not exist".format(self._path))
       41│
       42│         if self._full_path.is_dir():
       43│             raise ValueError("{} is a directory, expected a file".format(self._path))
       44│

  ValueError

  File \C:\Users\fzett\AppData\Local\pypoetry\Cache\artifacts\32\fc\a9\112a82396d53ec629c1450253a6ded4d94d7ffffd63acd49879543ece9\sphinxcontrib_qthelp-1.0.3-py2.py3-none-any.whl does not exist

  at ~\AppData\Roaming\Python\Python39\site-packages\poetry\core\packages\file_dependency.py:40 in __init__
       36│             except FileNotFoundError:
       37│                 raise ValueError("Directory {} does not exist".format(self._path))
       38│
       39│         if not self._full_path.exists():
    →  40│             raise ValueError("File {} does not exist".format(self._path))
       41│
       42│         if self._full_path.is_dir():
       43│             raise ValueError("{} is a directory, expected a file".format(self._path))
       44│

  ValueError

  File \C:\Users\fzett\AppData\Local\pypoetry\Cache\artifacts\e6\9a\17\830e357f3aee36549c613a2d660b5cf38d70c27ecb7c218d15c7bfffe1\sphinxcontrib_serializinghtml-1.1.5-py2.py3-none-any.whl does not exist

  at ~\AppData\Roaming\Python\Python39\site-packages\poetry\core\packages\file_dependency.py:40 in __init__
       36│             except FileNotFoundError:
       37│                 raise ValueError("Directory {} does not exist".format(self._path))
       38│
       39│         if not self._full_path.exists():
    →  40│             raise ValueError("File {} does not exist".format(self._path))
       41│
       42│         if self._full_path.is_dir():
       43│             raise ValueError("{} is a directory, expected a file".format(self._path))
       44│

Failed to add packages, reverting the pyproject.toml file to its original content.
P

**Comment by brandonaut** [comment] 2021-11-17 19:55
Possibly a duplicate of https://github.com/python-poetry/poetry/issues/4535

**Closed** 2022-07-29 11:53 UTC
