### ISSUE TITLE
Poetry not passing through SHAs for certain package versions.

### ISSUE THREAD

**Issue by TNonet** [python-poetry/poetry#5967] opened 2022-07-07 17:17 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: 'macOS-12.0.1-arm64-arm-64bit'
- **Poetry version**:  1.1.13
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: (https://gist.github.com/TNonet/c3774fdc624cd2d183997e18c9a453d4)

## Issue

Poetry is not passing through SHA values of packages in the `poetry.lock` file.

MWE:
```bash
poetry new test-sha
cd test-sha
poetry add requests==2.27.1
```
```
Updating dependencies
Resolving dependencies... (0.1s)

Writing lock file

Package operations: 5 installs, 0 updates, 0 removals

  • Installing certifi (2022.6.15)
  • Installing charset-normalizer (2.0.12)
  • Installing idna (3.3)
  • Installing urllib3 (1.26.10)
  • Installing requests (2.27.1)
```

Results in a `poetry.lock` file that is missing hashes.
```
...
packaging = []
pluggy = [
    {file = "pluggy-0.13.1-py2.py3-none-any.whl", hash = "sha256:966c145cd83c96502c3c3868f50408687b38434af77734af1e9ca461a4081d2d"},
    {file = "pluggy-0.13.1.tar.gz", hash = "sha256:15b2acde666561e1298d71b523007ed7364de07029219b604cf808bfa1c765b0"},
]
py = []
pyparsing = [
    {file = "pyparsing-3.0.9-py3-none-any.whl", hash = "sha256:5026bae9a10eeaefb61dab2f09052b9f4307d44aee4eda64b309723d8d206bbc"},
    {file = "pyparsing-3.0.9.tar.gz", hash = "sha256:2b020ecf7d21b687f219b71ecad3631f644a47f01403fa1d1036b0c6416d70fb"},
]
pytest = [
    {file = "pytest-5.4.3-py3-none-any.whl", hash = "sha256:5c0db86b698e8f170ba4582a492248919255fcd4c79b1ee64ace34301fb589a1"},
    {file = "pytest-5.4.3.tar.gz", hash = "sha256:7979331bfcba207414f5e1263b5a0f8f521d0f457318836a7355531ed1a4c7d8"},
]
requests = []
urllib3 = []
wcwidth = [
    {file = "wcwidth-0.2.5-py2.py3-none-any.whl", hash = "sha256:beb4802a9cebb9144e99086eff703a642a13d6a0052920003a230f3294bbe784"},
    {file = "wcwidth-0.2.5.tar.gz", hash = "sha256:c4d647b99872929fdb7bdcaa4fbe7f01413ed3d98077df798530e5b04f116c83"},
]
```

**Comment by TNonet** [comment] 2022-07-07 17:23
When `requests` is set to version `2.28.1` we now see the hash but it still is missing for several packages.

```
...
]
requests = [
    {file = "requests-2.28.1-py3-none-any.whl", hash = "sha256:8fefa2a1a1365bf5520aac41836fbee479da67864514bdb821f31ce07ce65349"},
    {file = "requests-2.28.1.tar.gz", hash = "sha256:7c5599b102feddaa661c826c56ab4fee28bfd17f5abca1ebbe3e7f19d7c97983"},
]
urllib3 = []
...
```

**Comment by mkniewallner** [comment] 2022-07-07 19:42
Can't reproduce on Linux amd64, so I'm wondering if it could not be specific to arm64.
Could you try with version [1.2.0b2](https://github.com/python-poetry/poetry/releases/tag/1.2.0b2) and see if you notice the same issue?

**Comment by TNonet** [comment] 2022-07-07 19:52
I am still seeing this issue with `Poetry (version 1.2.0b2)`.

**Comment by dpp23** [comment] 2022-07-08 08:26
This reproduces reliably on Ubuntu for me:

```
poetry cache clear pypi --all
poetry lock --no-update
```

then a lot of packages lose their hashes. This makes me think that it is an issue with pulling the data from PyPi.

**Comment by mkniewallner** [comment] 2022-07-08 08:49
It looks like https://github.com/pypi/warehouse/pull/11775 is most likely the cause, per https://github.com/python-poetry/poetry/issues/5967.

**Comment by jonapich** [comment] 2022-07-08 09:13
I started using `poetry export` and ran into this issue as well with the `boto3-stubs` package. I wrote a bug over there thinking they packaged it in a weird way, but I guess I will link it back here and close it.

**Closed** 2022-07-08 12:19 UTC
Labels: Bug
