### ISSUE TITLE
[[tool.poetry.source]] at last line of pyproject.toml causes all poetry commands to hang indefinitely

### ISSUE THREAD

**Issue by iandesj** [python-poetry/poetry#5592] opened 2022-05-11 13:11 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS Monterey Version 12.3.1
- **Poetry version**: 1.1.13
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/iandesj/a584b988f09778192e06d5739d49bfb2

## Issue
I ran into an issue where if and only if the `[[tool.poetry.source]]` array of tables was the last element in my `pyproject.toml` file, any `poetry command` would hang indefinitely. Anything from `poetry config --list` to `poetry update|install|shell -vvv`, like so:
<img width="616" alt="Screen Shot 2022-05-10 at 12 12 32 PM" src="https://user-images.githubusercontent.com/2693790/167857753-f0c73954-2444-4b14-aee3-48c2106dc0e7.png">

Once I moved it up a position in the file (or anywhere above the last position) everything began working as expected. I wasn't sure if it had to do with a poor file encoding or phantom character that was throwing the whole thing off, so I deleted and re-wrote the pyproject from scratch several times. All with the same result or a hanging command.

**Comment by abn** [comment] 2022-05-11 15:05
The root cause here is a buggy tomlkit version being used in core. This should have been fixed via https://github.com/python-poetry/poetry-core/pull/336.

You can test this using both poetry and poetry-core at master.

```sh
pipx install --suffix=@master 'poetry @ git+https://github.com/python-poetry/poetry@master'
pipx inject poetry@master 'poetry-core @ git+https://github.com/python-poetry/poetry-core@master'
```

**Closed by abn** 2022-05-11 15:05 UTC
Labels: Bug, Triage
