### ISSUE TITLE
option to prefer versions without local version identifier

### ISSUE THREAD

**Issue by StefanSchulz-Tesyo** [python-poetry/poetry#3267] opened 2020-10-22 06:53 UTC
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request
Assume a package "mypackage" exists with the following versions:
 - 0.1.0
 - 0.1.0+dirty.1
 - 0.1.1

And we define the following dependency in poetry:
`mypackage = {version = ">=0.1.0,<0.1.1", allow-prereleases = false}`
Poetry will resolve to version `0.1.0+dirty.1`.

A feature similar to `allow-prereleases` that disables local version identifiers in the search would be helpful.
Example:
`mypackage = {version = ">=0.1.0,<0.1.1", allow-local = false}` should resolve to `0.1.0`.

AFAIK the only possible way to do that now is:
`mypackage = {version = ">=0.1.0,<0.1.1,!=0.1.0+dirty.1"}`, i.e. listing any version with a local identifier.

Possibly related to #2543

**Comment by ralbertazzi** [comment] 2023-05-20 09:22
Duplicate of https://github.com/python-poetry/poetry/issues/7256

**Closed by ralbertazzi** 2023-05-20 09:22 UTC
Labels: kind/feature, status/triage
