### ISSUE TITLE
Undocumented change in handling of private repository credentials in 1.2.0

### ISSUE THREAD

**Issue by jakob-keller** [python-poetry/poetry#6277] opened 2022-08-31 09:54 UTC
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

The following issue might be too exotic to warrant an update of the documentation or release notes for 1.2.x. However, if the previous behaviour was intended, it could well represent a regression that might need fixing.

A private, password-protected repository may at the same time be configured both as a [package source](https://python-poetry.org/docs/repositories/#simple-api-repository) in pyproject.toml as well as a [publishable repository](https://python-poetry.org/docs/repositories/#publishable-repositories) in poetry.toml. Both configurations require a user-defined repository identifier that may differ, e.g. `pypi-test-source` and `pypi-test-publishable` respectively. [Credentials](https://python-poetry.org/docs/repositories/#configuring-credentials) may be provided as environment variables. So far, so good.

Prior to Poetry 1.2.0, it was sufficient to provide credentials for one of the repository configurations, e.g. the publishable repository. Poetry would implicitly use the provided credentials both for accessing sources as well as for publishing despite mismatched repository identifiers.

Since 1.2.0, the credentials are only used if their identifier matches the identifier used in the configuration. This could break existing setups, as it did with our CI pipeline.

As a work-around, one might either provide a second set of credentials to match the other repository identifier or use the same identifier in both configuration files. We did the later and or CI pipeline is back to normal.

_Originally posted by @jakob-keller in https://github.com/python-poetry/poetry/issues/6262#issuecomment-1232602757_

**Comment by sryabkov** [comment] 2022-08-31 16:04
This might help: https://github.com/python-poetry/poetry/issues/2692#issuecomment-900347237

In our Dockerfiles, we are doing

```
# https://github.com/python-poetry/poetry/issues/2692
ENV PYTHON_KEYRING_BACKEND="keyring.backends.null.Keyring"
```

**Comment by neersighted** [comment] 2022-08-31 17:06
Closing as not a bug -- this is pretty obscure for the docs, as you were relying on an unexpected edge case with credentials handling that was changed as part of an overall correctness refactor. We could migrate this to a discussion if you'd like, but I think that's about as much visibility as it needs.

**Closed by neersighted** 2022-08-31 17:06 UTC
Labels: Documentation, Triage
