### ISSUE TITLE
PEP440 with the version of python  in new version 1.2.0 

### ISSUE THREAD

**Issue by Jemmy4s** [python-poetry/poetry#6334] opened 2022-09-01 16:11 UTC
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version. 
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: zuul github ci
- **Poetry version**:1.2.0
- **Link of a [Gist](https://gist.github.com/Jemmy4s/21c1a580c7f0a244e251a8a300db2475) with the contents of your pyproject.toml file**: 

## Issue
I have upgrade poetry in my github ci in my tox.ini. My ci have problem. 
I use zuul. 
When I use poetry `pip install -v poetry==1.1.15`. I have no problem But when I use 1.2.0 I have this error :

`Invalid PEP 440 version: '3.8.13+'`

I see in previous issues we have the problem with dependencies.
https://github.com/python-poetry/poetry/issues/6013
But I don't understand why I have problem with python version and not the previous version.

**Comment by dimbleby** [comment] 2022-09-01 16:29
poetry 1.2.0 is more careful about understanding version numbers.  

This is a duplicate of #6013 and also #6332, and can be closed.

**Comment by AleksandrLiadov** [comment] 2022-09-02 10:32
I have the same issue : "Invalid PEP 440 version: **0.23ubuntu1**"
Poetry 1.2.0

**Comment by dimbleby** [comment] 2022-09-02 11:14
work in a virtual environment that does not contain the badly versioned packages

**Comment by AleksandrLiadov** [comment] 2022-09-02 11:25
@dimbleby thanks for your feedback!
It's nice to respect Pep440, but in production we can have the bad named dependencies...like **0.23ubuntu1**
What should we do in this case? Stay on 1.1.15?
Is there will be any solution on this issue in future update?
Maybe smth like **--ignore_bad_named_packages** ?

**Comment by dimbleby** [comment] 2022-09-02 11:36
this was already discussed in #6013, the position taken there was that version numbers need to be well formed or poetry can't know what to do.

> in production we can have the bad named dependencies

recommend running in production in a virtual environment that does not have the badly versioned dependencies

(or don't use poetry)

**Comment by finswimmer** [comment] 2022-09-02 12:18
In addition to the link @dimbleby: https://github.com/python-poetry/poetry/issues/2167#issuecomment-748436046

> What should we do in this case? 

Use the recommended installer, which will install poetry in its own virtual environment.

**Closed by finswimmer** 2022-09-02 12:18 UTC
Labels: kind/bug, status/triage

**Comment by robtaylor** [comment] 2022-11-04 13:29
Hmm, this issue will crop up regularly unless debian package versioning changes... and will always likely happen for distro-info...

Maybe ignore system installed libraries, or special case this?

**Comment by neersighted** [comment] 2022-11-04 14:10
#6925 is tracking the Python version number; there is now way to tell what is a "system" dep and virtual environments protect against questionable distro choices.

**Comment by robtaylor** [comment] 2022-11-04 14:49
Forcing every exsiting user into a venv is definitely a bit of a regression..

Frustratingly, even if you have a correct version installed, poetry-core is still parsing every package on your pythonpath, so seems only fix on ubuntu focal is to remove /usr/lib/python3/dist-packages from the path..

Maybe one fix is to ignore the Package if there is already a Package with a correct version?

**Comment by neersighted** [comment] 2022-11-04 15:37
Ignoring **any** package is more likely to cause issues than asking people to use a virtual environment when incompatible versions are present: Python includes an isolation mechanism that is explicitly designed to help in these situations, and ignoring malformed versions creates a lot more surface area for defects. There is some discussion about 'unparsed' versions since PEP 440 allows for a literal comparison operation, but that would be evolutionary rather than 'ignoring.'

**Comment by robtaylor** [comment] 2022-11-04 16:45
Makes sense. I guess we just need a bit of useful guidance for folk when they hit the issue, and gradually it will go away. Looks like debian has moved to pep440 standards for python package versions now.
