### ISSUE TITLE
Support .env file loading on shell & run

### ISSUE THREAD

**Issue by yoav-orca** [python-poetry/poetry#3324] opened 2020-11-04 14:00 UTC
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

I'm working on migrating from pipenv to poetry, and I found I'm missing a feature from pipenv, the automatic loading of `.env` files - https://pipenv-fork.readthedocs.io/en/latest/advanced.html#automatic-loading-of-env 
We use it extensively as a way of setting per project environment variables without requiring additional scripts.

**Comment by sinoroc** [comment] 2020-11-04 15:52
Seems like a good candidate for a [plugin](https://github.com/python-poetry/poetry/labels/Plugins), once the [_plugin system_](https://github.com/python-poetry/poetry/pull/1237) is in place.

On the other hand, isn't it what [_python-dotenv_](https://pypi.org/project/python-dotenv/) does?

**Comment by yoav-orca** [comment] 2020-11-04 16:24
Hi, it would be a very good candidate once poetry provides a plugin system.

The functionality is very similar to what `python-dotenv` provides, but it's supported natively in `pipenv`. 
It means that I don't have to litter the code with environment variable loading, and let the `pipenv shell/run` do it once for me on entry.

**Comment by sinoroc** [comment] 2020-11-04 19:22
***Related***:

* [_Support for .env files (#337)_](https://github.com/python-poetry/poetry/issues/337)

**Comment by finswimmer** [comment] 2021-12-29 19:48
Duplicate of #337.

Solution: https://github.com/python-poetry/poetry/issues/337#issuecomment-894503871

**Closed by finswimmer** 2021-12-29 19:48 UTC
Labels: Feature, Triage
