### ISSUE TITLE
app version retrieving the wrong version

### ISSUE THREAD

**Issue by pitosalas** [python-poetry/poetry#4323] opened 2021-07-27 18:08 UTC
A script managed by poetry:
```
 import pkg_resources
    return(pkg_resources.get_distribution('otproject').version)
```
seems to be returning the "wrong version". Here's what I mean:

1. in the toml file, I have 0.1.1 (this was edited from an earlier time when it was 0.1.0)
2. when I run my code from a. poetry shell, I get the right version
3. if I run it with a [tool.poetry.scripts] I get the "older" version

It's as if there's some cache or other left over that is coming into play. Any clue? Thanks!

**Comment by finswimmer** [comment] 2021-07-28 14:38
Hello @pitosalas,

can you check if this happens with the latest preview release (1.2.0a1)? I thinks this is a duplicate of https://github.com/python-poetry/poetry/issues/3289 which is already fixed in master by https://github.com/python-poetry/poetry/pull/3900.

fin swimmer

**Comment by pitosalas** [comment] 2021-07-28 16:00
Will try. The documentation by the way gives two contradictory instructions about how to install:



Do I use get-poetry or install-poetry? I was concerned that I installed it "wrong"...


Pito Salas
Faculty, Computer Science
Brandeis University

**Comment by pitosalas** [comment] 2021-07-28 16:28
Hi fin

I uninstalled poetry fully and then reinstalled the latest (not 1.2.0a1 but 1.1.7 and it seems to be a lot better.

By the way, if I want to launch a specific script that relies on the poetry venv from crontab, how do I do that? I think it's not picking up the venv. Thanks!

Pito Salas
Faculty, Computer Science
Brandeis University

**Comment by finswimmer** [comment] 2021-07-30 12:57
> By the way, if I want to launch a specific script that relies on the poetry venv from crontab, how do I do that?

You could activate the venv first before running any other command e.g. `source /path/to/venv/bin/activate && python script.py`

**Closed by finswimmer** 2021-07-30 12:57 UTC
Labels: awaiting response
