### ISSUE TITLE
Poetry does not create virtual environment directory into project in quite mode in some cases

### ISSUE THREAD

**Issue by GeorgeFischhof** [python-poetry/poetry#6217] opened 2022-08-23 15:08 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: AWS linux 2
- **Poetry version**: 1.1.14 experimental install method

## Issue

Hi,
 
**I used the following environment on AWS lambda:**
Python 3.10.4
AWS linux 2, AMD64
Poetry 1.1.14 experimental install method

**aws build script:**

"echo 'install poetry...'",
"curl -sSL https://install.python-poetry.org/ | python3 -",
'export PATH="$PATH:/root/.local/bin"',
"poetry config virtualenvs.in-project true",

“poetry config –list”,

result:
cache-dir = "/root/.cache/pypoetry"
experimental.new-installer = true
installer.parallel = true
virtualenvs.create = true
virtualenvs.in-project = true
virtualenvs.path = "{cache-dir}/virtualenvs"  # /root/.cache/pypoetry/virtualenvs

**script continued:**

"echo 'install packages...'",
"poetry install --no-root",
"ls -la",

result:

drwxr-xr-x 4 root root 64 Aug 17 09:54 .venv

---

I wanted to use -q option to suppress output, but there was no .venv folder, so I tried out --no-root option:
"poetry -q install --no-root",

The "--no-root" option does not exist.

Poetry said: there is no --no-root option

---

"poetry -q install",
"ls -la",

no .venv diretory

Maybe there is something related to Python 3.10.4 , as I saw a bug about Python 3.10.4

BR,
George

**Comment by finswimmer** [comment] 2022-08-23 15:28
Hello @GeorgeFischhof,

I have no idea why you want to use the `--no-root` option. However I'm able to reproduce the error message with Poetry 1.1.15 but not with 1.2.0rc1.

fin swimmer

**Comment by GeorgeFischhof** [comment] 2022-08-24 13:03
Hello @finswimmer ,
I did not know why there is no .venv folder in the project, so I started to try other things what I found; and just found --no-root, so I tried it, whether that helps something, and it remained in the script.

BR,
George

**Comment by finswimmer** [comment] 2022-09-05 18:32
Closing this, because 1.2 is now released and issue seems to be solved there.

**Closed by finswimmer** 2022-09-05 18:32 UTC
Labels: kind/bug, status/triage, status/waiting-on-response
