### ISSUE TITLE
Docker: Official docker image with poetry on Docker Hub

### ISSUE THREAD

**Issue by caniko** [python-poetry/poetry#5366] opened 2022-03-28 09:41 UTC
Hello

I tried getting attention on Docker Hub, but [failed](https://forums.docker.com/t/request-docker-images-with-python-poetry/122509). My last attempt is to make an issue here on GitHub.

I really do think that there is huge demand for officially maintaned poetry images, please consider.

**Comment by finswimmer** [comment] 2022-03-29 07:20
Duplicate of https://github.com/python-poetry/poetry/issues/4036

**Closed by finswimmer** 2022-03-29 07:20 UTC
Labels: Feature, Triage
