### ISSUE TITLE
Can I use poetry for a hardware/platform specific build?

### ISSUE THREAD

**Issue by dbogdoll** [python-poetry/poetry#5315] opened 2022-03-15 13:21 UTC
I'm writing a wrapper for a windows DLL and would like to publish the wheel with the DLL.
The DLL is only available for Windows and such the resulting wheel is not usable for any other platform.
The wheel build and works, but the wheel naming does not indicate that it is only usable for windows:

`example_name-0.1.0-py3-none-any.whl`

Of course I could just rename the wheel, but the meta data within the wheel also refers that this library is
`Root-Is-Purelib: true`
which is IMHO wrong.

Is there any way to tell poetry that this wheel is platform specific and works only on Windows?

**Comment by ianscottknight** [comment] 2022-11-03 20:39
I also want to know if there is a way to implement this.

**Comment by neersighted** [comment] 2022-11-03 20:44
This is actually a duplicate of #2740, more-or-less. Poetry will tag your wheel to the platform when you use a build script (which can perform an extension build, or copy around files/trigger another build system as needed). If you want explicit control over tags without a build script, that's something more like #2051, but as the project format is declarative, `build =` is a more direct way to get what you want.

**Closed by neersighted** 2022-11-03 20:44 UTC
