### ISSUE TITLE
get/install-poetry.py - confusing installation instructions

### ISSUE THREAD

**Issue by vlcinsky** [python-poetry/poetry#4598] opened 2021-10-05 20:38 UTC
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue
User trying to install poetry using current documentation might have following experience:

[Installation](https://python-poetry.org/docs/#installation) contains infobox:

> The `get-poetry.py` script described here will be replaced in Poetry 1.2 by `install-poetry.py`. From Poetry 1.1.7 onwards, you can already use this script as described here.

Following [osx / linux / bashonwindows install instructions](https://python-poetry.org/docs/#osx--linux--bashonwindows-install-instructions) show only url to download an run `get-poetry.py`

Running `get-poetry.py` prints "this installation script is obsolete".

Beside that, with poetry 1.1.1 I had an issue with "ModuleCannotBeFound" for cleo module.

## Proposal - add or change the link to `install-poetry.py`
Taking into account, that even obsolete `get-poetry.py` script installs the version higher than 1.1.7, it would be better to change the instruction to use `install-poetry.py` instead.

Change it to:

```bash
curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -
```

It saves the "obsolete" message and to me it worked better.

**Comment by vlcinsky** [comment] 2021-10-05 20:44
I see, that the "master" version of documentation already contains proposed change.

However, for version 1.1 it shows the older instruction.

It would be great to have it changed for 1.1 too.

**Comment by finswimmer** [comment] 2021-10-07 18:01
Hello @vlcinsky,

the infobox you are citing includes the link to the description of `install-poetry.py`. So I'm not sure what you are missing here.

fin swimmer

**Comment by finswimmer** [comment] 2021-10-14 12:19
The word "here" is linking to the documentation of `install-poetry.py`, isn't it?

**Comment by DanielJamesEvans** [comment] 2021-12-20 18:19
I couldn't get `get-poetry.py` to work with Python 3.10, but I solved my issue by switching to `install-poetry.py`.  Perhaps I was making an error, but I don't think so: [here](https://github.com/python-poetry/poetry/issues/3345#issuecomment-956318007) also suggests that switching to `install-poetry.py` fixes issues.  Users are still erroneously using `get-poetry.py`, as seen [here](https://github.com/pymedphys/pymedphys/issues/1587#issue-1073942564).

While it's good practice to use the most current software version, nothing in the current docs suggests that using the old version (`get-poetry.py`) is incorrect.  To me, the issue is that _users can follow an allegedly correct procedure and get an error message._.

**Comment by finswimmer** [comment] 2021-12-20 18:37
> While it's good practice to use the most current software version, nothing in the current docs suggests that using the old version (get-poetry.py) is incorrect.

In general there's nothing wrong with using `get-poetry.py`. It's just deprecated, which means "be aware that this will be replaced by another way of doing it soon". The problems with python 3.10 in windows are due to the missing `_vendor` folder in the release (see https://github.com/python-poetry/poetry/issues/4846#issuecomment-988806589). This was not intended and will be fixed by a new release.

**Closed** 2022-05-23 08:57 UTC
Labels: Documentation, Triage
