### ISSUE TITLE
poetry install extremely slow when installing scipy

### ISSUE THREAD

**Issue by jannesklee** [python-poetry/poetry#4995] opened 2022-01-06 09:50 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Arch Linux & Docker environment [python:latest](https://hub.docker.com/_/python/) (currently python-3.10 with debian bullseye)
- **Poetry version**: 1.1.12
- **Link of a [Gist](https://gist.github.com/jannesklee/0708ba1d3b201bd6b8c9e7e9cbdb42dc) **

## Issue
Installation of scipy takes a very long time (>5 min) when running

    poetry install

The Gist above is a reduced version where the long installation occurs because scipy is a dependency for [spatialmath-python](https://github.com/petercorke/spatialmath-python). I ran with -vvv at the beginning and it is shown again that Python 3.10 is used. When coming to scipy it say

   1: fact: scipy (1.7.3) requires Python >=3.7,<3.11
   1: derived: not scipy (==1.7.3)
   1: fact: scipy (1.7.2) requires Python >=3.7,<3.11
   1: derived: not scipy (==1.7.2)
   1: fact: scipy (1.7.1) requires Python >=3.7,<3.10
   1: derived: not scipy (==1.7.1)
   1: fact: scipy (1.7.0) requires Python >=3.7,<3.10
   1: derived: not scipy (==1.7.0)
   1: fact: scipy (1.6.3) requires Python >=3.7,<3.10
   1: derived: not scipy (==1.6.3)
   1: fact: scipy (1.6.2) requires Python >=3.7,<3.10
   1: derived: not scipy (==1.6.2)
   1: fact: scipy (1.6.1) depends on numpy (>=1.16.5)
   1: selecting scipy (1.6.1)

which I don't understand, since Python 3.10 is used.

**Comment by clintonroy** [comment] 2022-01-06 10:14
Hrm, seems pretty quick for me. Now that your cache is warm, try removing it, then re-adding it, see if that's quicker?

poetry remove spatialmath-python

poetry add spatialmath-python

**Comment by jannesklee** [comment] 2022-01-06 11:28
Unfortunately, no changes..

**Comment by jannesklee** [comment] 2022-01-06 11:42
I don't know if this is directly related, but trying to add scipy with

    poetry add scipy

direclty, leads to an **SolverProblemError**, because ^1.7.3 is not compatible with the project Python requirements.

    The current project's Python requirement (>=3.10,<4.0) is not compatible with some of the required packages Python requirement:
      - scipy requires Python >=3.7,<3.11, so it will not be satisfied for Python >=3.11,<4.0

**Comment by clintonroy** [comment] 2022-01-06 11:47
Oh, I think i see it now, it's compiling stuff in the background, fortran stuff.

**Comment by clintonroy** [comment] 2022-01-06 11:52
Right, so at a guess there are pre compiled eggs for everything for python 3.9, but not for 3.10.

**Comment by clintonroy** [comment] 2022-01-06 11:53
err, wheels ;)

**Comment by jannesklee** [comment] 2022-01-06 11:54
Ah ok, so I just need to downgrade to Python 3.9?

**Comment by clintonroy** [comment] 2022-01-06 11:56
Yup, that's the easiest thing to do when relying on a lot of compiled wheels, lots of things have not been built for 3.10 yet.

**Comment by jannesklee** [comment] 2022-01-06 12:24
I tried out to downgrade by changing the environment in pyenv and testet it with two version: 3.8.12 and 3.9.9. Unfortunately the problem still remains. My calls:

    pyenv local 3.8.12
    poetry env use python
    poetry add scipy
    poetry add spatialmath-python

Adding scipy still gives me the SolverProblemError with abortion and spatialmath-python leads to the downgrading of scipy to 1.6.1 and then most probably compilation.

Can I somehow get more information on why poetry is thinking the Python version is not fitting to scipy and about the compilation?

**Comment by clintonroy** [comment] 2022-01-06 23:23
It sounds like you still have to modify the pyproject.toml to use lower versions of python to me.

**Comment by jannesklee** [comment] 2022-01-07 11:33
I think I found the issue:

I installed poetry on Python 3.10.1 and the [new  installation script](https://python-poetry.org/docs/)

     curl -sSL https://install.python-poetry.org | python3 -

afterwards I changed with pyenv to version 3.9.9 and scipy needs long installation time.

Removing poetry and installation with Python 3.9.9 with

     curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -

installs scipy much faster from binaries.

So from my point I have a solution, thanks a lot for your help! 


There are maybe still two open points that I want to mention that might be worth their own issues:
- The downgrading of scipy by adding spatialmath-python is still the case and adding scipy directly without version still gives me the error above (also with Python 3.9.9 installation).
- Both times the installed poetry versions were 1.1.12. Should it be a possible behaviour to have here a different results or is it not related to poetry (but scipy)? The virtualenv that was used by poetry was definitely ending with _py3.9 and _py3.10 respectively. It was stated at the beginning of the packages by poetry itself.

**Comment by DetachHead** [comment] 2022-01-09 23:52
if this is still an issue with python 3.10 i don't think it should be closed

**Comment by weetster** [comment] 2022-03-11 16:29
I had a very similar problem. My project's dependencies were `python = "^3.10"` and `statsmodels = "0.13.1"`, which resulted in Poetry deciding to pull in `scipy@1.6.1` for whatever reason (which does not have pre-built wheels for Python 3.10). I explicitly did `poetry add scipy@1.8.0`, which resulted in `SolveFailure`:

```
The current project's Python requirement (>=3.10,<4.0) is not compatible with some of the required packages Python requirement:
  - scipy requires Python >=3.8,<3.11, so it will not be satisfied for Python >=3.11,<4.0
```

This makes sense, because `python = "^3.10"` does not guarantee scipy's requirement for <3.11. I changed my Python dependency to `python = "3.10"` (explicitly == 3.10, not >= 3.10), which allowed scipy@1.8.0 to be added. Then I tried a fresh `poetry install`, which finished in a matter of seconds because the pre-built scipy@1.8.0 wheel is now being used.

I think the root cause of all this (at least in my case) is the fact that Poetry chose `scipy@1.6.1` (which required building from source) instead of a later version that has a pre-built wheel available.

**Comment by weetster** [comment] 2022-03-11 17:15
I did some further testing by creating a Poetry project whose only dependencies are Python >= 3.10 and `statsmodels@0.13.1`. This reproduced the behaviour of choosing `scipy@1.6.1`.

```
~/poetry_test$ poetry install --no-root -vvv
The currently activated Python version 3.8.10 is not supported by the project (^3.10).

Trying to find and use a compatible version.

Trying python3

Trying python3.10

Using python3.10 (3.10.2)

Creating virtualenv poetry-test-iQ9fdmEn-py3.10 in /home/redacted/.cache/pypoetry/virtualenvs

Using virtualenv: /home/redacted/.cache/pypoetry/virtualenvs/poetry-test-iQ9fdmEn-py3.10

Updating dependencies

Resolving dependencies...

   1: fact: poetry-test is 0.1.0

   1: derived: poetry-test

   1: fact: poetry-test depends on statsmodels (0.13.1)

   1: selecting poetry-test (0.1.0)

   1: derived: statsmodels (==0.13.1)

   1: fact: statsmodels (0.13.1) depends on numpy (>=1.17)

   1: fact: statsmodels (0.13.1) depends on scipy (>=1.3)

   1: fact: statsmodels (0.13.1) depends on pandas (>=0.25)

   1: fact: statsmodels (0.13.1) depends on patsy (>=0.5.2)

   1: selecting statsmodels (0.13.1)

   1: derived: patsy (>=0.5.2)

   1: derived: pandas (>=0.25)

   1: derived: scipy (>=1.3)

   1: derived: numpy (>=1.17)

   1: fact: patsy (0.5.2) depends on six (*)

   1: fact: patsy (0.5.2) depends on numpy (>=1.4)

   1: selecting patsy (0.5.2)

   1: derived: six

   1: fact: scipy (1.8.0) requires Python >=3.8,<3.11

   1: derived: not scipy (==1.8.0)

   1: fact: scipy (1.7.3) requires Python >=3.7,<3.11

   1: derived: not scipy (==1.7.3)

   1: fact: scipy (1.7.2) requires Python >=3.7,<3.11

   1: derived: not scipy (==1.7.2)

   1: fact: scipy (1.7.1) requires Python >=3.7,<3.10

   1: derived: not scipy (==1.7.1)

   1: fact: scipy (1.7.0) requires Python >=3.7,<3.10

   1: derived: not scipy (==1.7.0)

   1: fact: scipy (1.6.3) requires Python >=3.7,<3.10

   1: derived: not scipy (==1.6.3)

   1: fact: scipy (1.6.2) requires Python >=3.7,<3.10

   1: derived: not scipy (==1.6.2)

   1: fact: scipy (1.6.1) depends on numpy (>=1.16.5)

   1: selecting scipy (1.6.1)

   1: selecting six (1.16.0)

   1: fact: pandas (1.4.1) depends on python-dateutil (>=2.8.1)

   1: fact: pandas (1.4.1) depends on pytz (>=2020.1)

   1: fact: pandas (1.4.1) depends on numpy (>=1.21.0)

   1: selecting pandas (1.4.1)

   1: derived: numpy (>=1.21.0)

   1: derived: pytz (>=2020.1)

   1: derived: python-dateutil (>=2.8.1)

   1: fact: python-dateutil (2.8.2) depends on six (>=1.5)

   1: selecting python-dateutil (2.8.2)

   1: selecting pytz (2021.3)

   1: selecting numpy (1.22.3)

   1: Version solving took 5.151 seconds.

   1: Tried 1 solutions.

Writing lock file

Finding the necessary packages for the current system

Package operations: 8 installs, 0 updates, 0 removals

  • Installing six (1.16.0): Pending...
  • Installing six (1.16.0): Installing...
  • Installing six (1.16.0)
  • Installing numpy (1.22.3): Pending...
  • Installing numpy (1.22.3): Downloading... 100%
  • Installing numpy (1.22.3): Installing...
  • Installing numpy (1.22.3)
  • Installing python-dateutil (2.8.2): Pending...
  • Installing python-dateutil (2.8.2): Installing...
  • Installing python-dateutil (2.8.2)
  • Installing pytz (2021.3): Pending...
  • Installing pytz (2021.3): Installing...
  • Installing pytz (2021.3)
  • Installing pandas (1.4.1): Pending...
  • Installing pandas (1.4.1): Downloading... 100%
  • Installing pandas (1.4.1): Installing...
  • Installing pandas (1.4.1)
  • Installing patsy (0.5.2): Pending...
  • Installing patsy (0.5.2): Installing...
  • Installing patsy (0.5.2)
  • Installing scipy (1.6.1): Pending...
  • Installing scipy (1.6.1): Installing...
```

It appears `scipy@1.6.1` is the newest version that does not specify a Python version range, which therefore matches the requirement of Python >= 3.10. So my best assessment is that Poetry is working as intended when choosing a version of scipy that fits the requirements, which happens to be a version that is old enough that it doesn't have pre-built wheels for newer Python versions.

I don't think there is an explicit bug in Poetry, other than possibly better transparency or indication of  package version choice and whether pre-built wheels are available for the given configuration.

**Comment by abn** [comment] 2022-05-12 20:24
Since the issue has to do with packages not having wheels causing poetry to rebuild packages locally, I suspe this issue has no action. Closing.

**Closed by abn** 2022-05-12 20:24 UTC
Labels: Bug, Triage

**Comment by baggiponte** [comment] 2022-06-19 20:44
Why doesn't `poetry` choose `scipy1.8.0`? I don't understand this line:
> fact: scipy (1.8.0) requires Python >=3.8,<3.11
   derived: not scipy (==1.8.0)

**Comment by mbwgh** [comment] 2022-07-20 18:42
> Why doesn't `poetry` choose `scipy1.8.0`? I don't understand this line:
> 
> > fact: scipy (1.8.0) requires Python >=3.8,<3.11
> > derived: not scipy (==1.8.0)

Correct me if I'm wrong, but according to the [dependency specification](https://python-poetry.org/docs/dependency-specification/), OP had `python = "^3.10"` in their `pyproject.toml`, which should be equal to `>=3.10.0,<4.0.0`.
In particular, you could have an environment with python 3.11 in it and it would be legal so far. But then of course, scipy *requires* `<3.11` so it's not compatible.
