### ISSUE TITLE
poetry removes setuptools in a specific combination of versions

### ISSUE THREAD

**Issue by spapanik** [python-poetry/poetry#6897] opened 2022-10-26 20:58 UTC
- **Poetry version**: Poetry (version 1.2.2)
- **Python version**: Python 3.10.8
- **OS version and name**: Arch Linux
- **pyproject.toml**: https://gist.github.com/spapanik/eb29fdee675d9c757f8a264dce76358f

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

A specific combination of flake8, sphinx, and  python versions (the one in my gist) leads to setuptools being removed when I try to install the project with --sync. Removing flake8 or sphinx or requiring python 3.10 doesn't lead to setuptools removal. Requiring only a less complex sphinx version also doesn't lead to setuptools being removed.

```console
stephanos@sanji $ pip install setuptools && poetry install --sync -vvv
Collecting setuptools
  Using cached setuptools-65.5.0-py3-none-any.whl (1.2 MB)
Installing collected packages: setuptools
Successfully installed setuptools-65.5.0
Loading configuration file /home/stephanos/.config/pypoetry/config.toml
Loading configuration file /home/stephanos/.config/pypoetry/auth.toml
Using virtualenv: /home/stephanos/.local/share/virtualenvs/bug
Project environment contains an empty path in sys_path, ignoring.
Installing dependencies from lock file

Finding the necessary packages for the current system

Package operations: 0 installs, 0 updates, 1 removal, 27 skipped

  • Removing setuptools (65.5.0): Pending...
  • Removing setuptools (65.5.0): Removing...
  • Removing setuptools (65.5.0)
  • Installing alabaster (0.7.12): Pending...
  • Installing alabaster (0.7.12): Skipped for the following reason: Already installed
  • Installing babel (2.10.3): Pending...
  • Installing babel (2.10.3): Skipped for the following reason: Already installed
  • Installing certifi (2022.9.24): Pending...
  • Installing certifi (2022.9.24): Skipped for the following reason: Already installed
  • Installing charset-normalizer (2.1.1): Pending...
  • Installing charset-normalizer (2.1.1): Skipped for the following reason: Already installed
  • Installing docutils (0.19): Pending...
  • Installing docutils (0.19): Skipped for the following reason: Already installed
  • Installing flake8 (5.0.4): Pending...
  • Installing flake8 (5.0.4): Skipped for the following reason: Already installed
  • Installing idna (3.4): Pending...
  • Installing idna (3.4): Skipped for the following reason: Already installed
  • Installing imagesize (1.4.1): Pending...
  • Installing imagesize (1.4.1): Skipped for the following reason: Already installed
  • Installing jinja2 (3.1.2): Pending...
  • Installing jinja2 (3.1.2): Skipped for the following reason: Already installed
  • Installing mccabe (0.7.0): Pending...
  • Installing mccabe (0.7.0): Skipped for the following reason: Already installed
  • Installing markupsafe (2.1.1): Pending...
  • Installing markupsafe (2.1.1): Skipped for the following reason: Already installed
  • Installing pycodestyle (2.9.1): Pending...
  • Installing pycodestyle (2.9.1): Skipped for the following reason: Already installed
  • Installing pyflakes (2.5.0): Pending...
  • Installing pyflakes (2.5.0): Skipped for the following reason: Already installed
  • Installing pygments (2.13.0): Pending...
  • Installing pygments (2.13.0): Skipped for the following reason: Already installed
  • Installing pyparsing (3.0.9): Pending...
  • Installing pyparsing (3.0.9): Skipped for the following reason: Already installed
  • Installing pytz (2022.5): Pending...
  • Installing pytz (2022.5): Skipped for the following reason: Already installed
  • Installing snowballstemmer (2.2.0): Pending...
  • Installing snowballstemmer (2.2.0): Skipped for the following reason: Already installed
  • Installing sphinx (5.3.0): Pending...
  • Installing sphinx (5.3.0): Skipped for the following reason: Already installed
  • Installing packaging (21.3): Pending...
  • Installing packaging (21.3): Skipped for the following reason: Already installed
  • Installing sphinxcontrib-applehelp (1.0.2): Pending...
  • Installing sphinxcontrib-applehelp (1.0.2): Skipped for the following reason: Already installed
  • Installing sphinxcontrib-serializinghtml (1.1.5): Pending...
  • Installing sphinxcontrib-serializinghtml (1.1.5): Skipped for the following reason: Already installed
  • Installing requests (2.28.1): Pending...
  • Installing requests (2.28.1): Skipped for the following reason: Already installed
  • Installing sphinxcontrib-htmlhelp (2.0.0): Pending...
  • Installing sphinxcontrib-htmlhelp (2.0.0): Skipped for the following reason: Already installed
  • Installing sphinxcontrib-devhelp (1.0.2): Pending...
  • Installing sphinxcontrib-devhelp (1.0.2): Skipped for the following reason: Already installed
  • Installing sphinxcontrib-jsmath (1.0.1): Pending...
  • Installing sphinxcontrib-jsmath (1.0.1): Skipped for the following reason: Already installed
  • Installing urllib3 (1.26.12): Pending...
  • Installing urllib3 (1.26.12): Skipped for the following reason: Already installed
  • Installing sphinxcontrib-qthelp (1.0.3): Pending...
  • Installing sphinxcontrib-qthelp (1.0.3): Skipped for the following reason: Already installed
```

**Comment by dimbleby** [comment] 2022-10-26 21:59
- setuptools does get named in your lockfile because the older version of sphinx (for pythin < 3.10) requires it
- but you are installing in a python 3.10 environment, with the new version of sphinx, which does not require setuptools

the first bullet means that poetry decides that setuptools is under poetry management, the second means that it removes it

**Comment by neersighted** [comment] 2022-10-27 04:08
Indeed, not a bug. Poetry installs in isolated mode so that we can install/upgrade/generally manipulate setuptools without breaking sdists builds, so this shouldn't really change anything for you. If you depend on setuptools you should just declare it as a dependency -- the Python ecosystem is moving to a world where setuptools is just another package/is not implicitly available in every environment (and indeed, it was a convention, not specification, that virtual environments come with setuptools).

**Closed by neersighted** 2022-10-27 04:08 UTC
Labels: kind/question
