### ISSUE TITLE
Conflicting dependencies even if dependency group is not installed

### ISSUE THREAD

**Issue by Cito** [python-poetry/poetry#6611] opened 2022-09-23 14:28 UTC
- **Poetry version**: 1.2.1
- **Python version**: 3.9.13
- **OS version and name**: Windows 10
- **pyproject.toml**: 

```
[tool.poetry.group.lint]
optional = true

[tool.poetry.group.lint.dependencies]
flake8 = "^5.0"

[tool.poetry.group.doc]
optional = true

[tool.poetry.group.doc.dependencies]
sphinx = "^5.1"
```

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

Since the current versions of  Flake8 and Sphinx have conflicting dependencies, I have put these into separate, optional dependency groups. But no matter how I install (without one of the dependency groups or without both of them, running a simpe `poetry install`), I still get the error message `because my-project depends on both flake8 (^5.0) and sphinx (^5.1), version solving failed.` Shouldn't the optional dependency groups avoid such kinds of problems?

In the debug log I see 
```     
  1: fact: my-project depends on flake8 (^5.0)        
  1: fact: my-project depends on sphinx (^5.1)        
```

So it seems Poetry thinks that my project depends on both flake8 and sphinx, but it only *optionally* depends on them, and it should only give an error if both groups are installed at the same time, i.e. `with lint,doc`.

**Comment by neersighted** [comment] 2022-09-23 14:30
Poetry's current resolver module ensures that every possible combination of dependencies, extras, and groups is installable. This is a key feature of Poetry, and while we have discussed future support for mutually exclusive groups or extras, such support would require a major refactor and (likely breaking) changes, and no one has seriously expressed interest in implementing similar.

Partially a dupe of #6419 as the same refactoring of the resolver is required, even if extras and dependencies are not the same.

**Closed by neersighted** 2022-09-23 14:30 UTC
Labels: kind/question, status/duplicate

**Comment by Cito** [comment] 2022-09-23 14:42
Thanks for the quick answer @neersighted. I really had hoped this issue could be solved with dependency groups. Would be glad if this will eventually be implemented. If anybody has found a good alternative solution or workaround (extras seem to have the same problem as far as I understand), please let me know.

**Comment by neersighted** [comment] 2022-09-23 19:43
We are looking to add a new type of dependency management for `non-importable` dependencies that keeps tools in their own venvs and doesn't force them to be part of the dependency tree. Very early days, but it will solve this in the long run for you.

I forget where the draft PR/work was parked -- @abn could you link your work?
