### ISSUE TITLE
Invalid hash in lockfile not causing an error

### ISSUE THREAD

**Issue by remram44** [python-poetry/poetry#3765] opened 2021-03-10 00:21 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 20.04
- **Poetry version**: 1.1.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gitlab.com/ViDA-NYU/auctus/auctus/-/blob/master/pyproject.toml

## Issue

I ran `poetry lock`, committed a version bump, but forgot to commit the corresponding hash in the `[metadata.files]` section. However `poetry install` didn't report any problem (both locally and on CI), even though it installed a file that did not have a corresponding hash in the lock file. This seems to defeat the purpose of putting hashes in the file, if the wrong file is silently accepted.

Extracts from my `poetry.lock`:

```
[[package]]
name = "defusedxml"
version = "0.7.1"
description = "XML bomb protection for Python stdlib modules"
category = "main"
optional = false
python-versions = ">=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*"
```

```
defusedxml = [
    {file = "defusedxml-0.6.0-py2.py3-none-any.whl", hash = "sha256:6687150770438374ab581bb7a1b327a847dd9c5749e396102de3fad4e8a3ef93"},
    {file = "defusedxml-0.6.0.tar.gz", hash = "sha256:f684034d135af4c6cbb949b8a4d2ed61634515257a67299e5f940fbaa34377f5"},
]
```

Output from Poetry:

```
$ poetry install
Installing dependencies from lock file

Package operations: 0 installs, 1 update, 0 removals

  • Updating defusedxml (0.6.0 -> 0.7.1)
```

**Comment by remram44** [comment] 2021-03-10 00:29
Equivalent pip command:

```
$ cat reqs.txt
defusedxml==0.7.1 --hash=sha256:6687150770438374ab581bb7a1b327a847dd9c5749e396102de3fad4e8a3ef93 --hash=sha256:f684034d135af4c6cbb949b8a4d2ed61634515257a67299e5f940fbaa34377f5

$ poetry run pip install -r reqs.txt
Collecting defusedxml==0.7.1
  Using cached defusedxml-0.7.1-py2.py3-none-any.whl (25 kB)
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    defusedxml==0.7.1 from https://files.pythonhosted.org/packages/07/6c/aa3f2f849e01cb6a001cd8554a88d4c77c5c1a31c95bdf1cf9301e6d9ef4/defusedxml-0.7.1-py2.py3-none-any.whl#sha256=a352e7e428770286cc899e2542b6cdaedb2b4953ff269a210103ec58f6198a61 (from -r reqs.txt (line 1)):
        Expected sha256 6687150770438374ab581bb7a1b327a847dd9c5749e396102de3fad4e8a3ef93
        Expected     or f684034d135af4c6cbb949b8a4d2ed61634515257a67299e5f940fbaa34377f5
             Got        a352e7e428770286cc899e2542b6cdaedb2b4953ff269a210103ec58f6198a61
```

**Comment by pietrodn** [comment] 2021-04-19 14:59
Duplicate of https://github.com/python-poetry/poetry/issues/2422

**Closed** 2021-05-19 14:38 UTC
Labels: Bug, Triage
