### ISSUE TITLE
poetry prune

### ISSUE THREAD

**Issue by tchaton** [python-poetry/poetry#2929] opened 2020-09-17 13:08 UTC
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Sometimes we have old project with requirements.txt file.

To add them up to poetry, I used this cmd:
for item in $(cat requirements.txt); do poetry add "${item}"; done

However, I think it would be interesting to have a poetry prune cmd removing all sub-level packages.

**Comment by abn** [comment] 2020-09-17 13:46
Is this even reliably possible? Wouldn't this depend on what your project actually imports? I can't think of any way of knowing this short of ispecting your project source.

**Comment by agoose77** [comment] 2020-09-29 13:39
I imagine you could implement a tool that works out the necessary top level dependencies to reproduce a flat requirements.txt. It wouldn't necessarily be correct w.r.t to the user requirements e.g. it would not treat sub-dependencies as top-level dependencies, but it would *work*. I imagine most dependencies are indeed sub-dependencies, so this would be a good starting point for converting to a pyproject.toml format.

**Comment by finswimmer** [comment] 2021-12-29 07:53
Hello,

this is something out of scope for Poetry, because it would need source code parsing.

**Closed by finswimmer** 2021-12-29 07:53 UTC
Labels: Feature, Triage
