### ISSUE TITLE
Impossible to install Black 19.3b0

### ISSUE THREAD

**Issue by Xowap** [python-poetry/poetry#1505] opened 2019-10-26 14:03 UTC
- **OS version and name**: `elementary OS 0.4.1 Loki`
- **Poetry version**: `0.12.17`
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://github.com/Xowap/typefit/blob/develop/pyproject.toml

## Issue
I'm trying to install Black, and I'm kind of succeeding thanks to comments in #767. However, the version of Black I'm getting is not the latest one:

```
> poetry run black --version
black, version 18.9b0
```

The latest one being [`19.3b0`](https://github.com/psf/black/releases/tag/stable).

I was wondering if this could be due to black not respecting semver, so I put the version number manually to see what happens, but turns out it's not helping much.

```toml
black = {version = "19.3b0", allows-prereleases = true}
```

```
[SolverProblemError]                                                                    
Because typefit depends on black (19.3b0) which doesn't match any versions, version solving failed.
```

Thanks for your help!

**Comment by n8sty** [comment] 2019-10-26 19:20
I'm running 1.0.0b3 and I can successfully install `black`. What happens if you upgrade to a newer, preview version of poetry?

**Comment by Xowap** [comment] 2019-10-26 19:59
Interestingly enough, I'm getting this

```
> poetry run black --version
Poetry version 1.0.0b3
```

But I guess it's another bug on its own.

To answer the actual question:

```
> poetry show black
name         : black
version      : 18.9b0
description  : The uncompromising code formatter.

dependencies
 - appdirs *
 - attrs >=17.4.0
 - click >=6.5
 - toml >=0.9.4
```

**Comment by b0g3r** [comment] 2019-10-27 20:19
Do you create a lock file before installing?

**Comment by Xowap** [comment] 2019-10-27 21:06
I believe that I tried many things. Latest attempts had a lock file but in order to make sure I've tried to reproduce the problem from scratch.

Using poetry 0.12.17 and Python 3.8.0, I went to an empty folder and did a `poetry init` which gave the following file:

```toml
[tool.poetry]
name = "test-poetry"
version = "0.1.0"
description = ""
authors = ["Rémy Sanchez <remy.sanchez@hyperthese.net>"]

[tool.poetry.dependencies]
python = "^3.7"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```

Then I ran `poetry add -D --allow-prereleases black` and it still did...

```  - Installing black (18.9b0)```

That's pretty accurately reproducible for me. On this machine, on my other one or when using Python `3.6` instead of `3.8`

**Comment by pikeas** [comment] 2019-11-07 19:28
I have `black = "^19.3b0"`, which currently resolves to `19.10b0`. Everything is working correctly with Poetry 1.0.0b3 under Python 3.7 and 3.8.

**Comment by Xowap** [comment] 2019-11-07 21:23
Interesting, I tried again and put the exact same requirement as you using the same version of poetry and yet this still happens:

```[SolverProblemError]
Because typefit depends on black (^19.3b0) which doesn't match any versions, version solving failed.```

**Comment by bibz** [comment] 2019-12-03 16:45
What does `pip` say about black? Poetry relies on the same source of packages after all.

```
% pip search --isolated black | grep '^black '
black (19.10b0)                        - The uncompromising code formatter.
```

(Note the `--isolated` here to make sure `pip` is config-free.)

And if `pip` sees the right version, try again without the `--isolated` flag.

**Comment by Xowap** [comment] 2019-12-04 13:25
I've tested this:

```
%  poetry run pip search --isolated black | grep '^black '
black (19.10b0)                        - The uncompromising code formatter.
```

Weirdly enough, I've had a case where the right Black version installed properly but I realized too late and this happened not on one of my computers. I'll try to reproduce.

**Comment by bibz** [comment] 2019-12-10 10:32
And without the `--isolated` flag? Just to rule out any specific pip configuration that was overlooked.

```
% pip search black | grep '^black '
black (19.10b0)
```

Is it different than searching with Poetry?
```
% poetry search black | grep '^black '
black (19.10b0)
```

I successfully found the latest Black version with Poetry `0.12.17` and `1.0.0b9`.

**Comment by Rosswell** [comment] 2019-12-20 08:50
I can't reproduce either. `poetry init` resulted in 
```
[tool.poetry]
name = "test"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```
then using the same command for installation
```
$ poetry add -D --allow-prereleases black
Creating virtualenv test-wix2tCvA-py3.7 in /Users/rblanchard/Library/Caches/pypoetry/virtualenvs
Using version ^19.10b0 for black

Updating dependencies
Resolving dependencies... (1.0s)

Writing lock file


Package operations: 8 installs, 0 updates, 0 removals

  - Installing appdirs (1.4.3)
  - Installing attrs (19.3.0)
  - Installing click (7.0)
  - Installing pathspec (0.6.0)
  - Installing regex (2019.12.19)
  - Installing toml (0.10.0)
  - Installing typed-ast (1.4.0)
  - Installing black (19.10b0)
```

```
$ poetry --version
Poetry version 1.0.0
$ python3 -V
Python 3.7.4
```

**Comment by hitshydev** [comment] 2020-03-05 12:42
I'm experiencing a smiliar problem by trying to add essentia to my dependencies. I'm also using elementary OS. But I solved it, here is how:

I edit the first line of `~/.poetry/bin/poetry` to `#!/usr/bin/env python3`

Here is some explanation:
elementary OS comes with preinstalled python 2.x , that's why the python environment variable is already occupied and one has to run `sudo apt install python3` to get python 3.x which then occupies the python3 environment variable. I would guess that many ubuntu based systems are installing python 3.* in this way that's why sometimes poetry won't run at all or is behaving in an unexpected manner.
But that said, the bug can only be reproduced when running poetry with python 2.x (2.7 in my case).

**Comment by Olegt0rr** [comment] 2021-04-07 11:20
Can't reproduce on Windows 10.
But it's reproduced easily on MacOS

<img width="276" alt="Screenshot 2021-04-07 at 14 15 18" src="https://user-images.githubusercontent.com/25399456/113857852-b1048f80-97ab-11eb-97e5-04188043d482.png">


```
Hardware Overview
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro14,2
  Processor Name:	Dual-Core Intel Core i5
  Processor Speed:	3,1 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	4 MB
  Hyper-Threading Technology:	Enabled
  Memory:	8 GB
  System Firmware Version:	429.80.1.0.0
  SMC Version (system):	2.44f6

System Software Overview:
  System Version:	macOS 11.2.3 (20D91)
  Kernel Version:	Darwin 20.3.0
  Boot Volume:	Macintosh HD
  Boot Mode:	Normal
  Secure Virtual Memory:	Enabled
  System Integrity Protection:	Enabled

Pycharm:
PyCharm 2020.3.5 (Professional Edition)
Build #PY-203.7717.81, built on March 25, 2021
Runtime version: 11.0.10+8-b1145.96 x86_64
```

**Comment by Xowap** [comment] 2021-06-29 12:44
To be honest I've never hard the problem for quite a while now so I'm guessing that the bug is gone

**Comment by sanmai-NL** [comment] 2021-06-29 13:09
@Xowap You may close the issue then.

**Closed** 2021-08-03 13:36 UTC
Labels: Bug
