### ISSUE TITLE
got a expected string or bytes-like object when running install

### ISSUE THREAD

**Issue by ElricleNecro** [python-poetry/poetry#4311] opened 2021-07-23 16:29 UTC
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Arch Linux
- **Poetry version**: 1.1.7
- ```toml
  [tool.poetry]
  name = "testy"
  version = "0.1.0"
  description = ""
  authors = ["Test user"]

  [tool.poetry.dependencies]
  python = ">=3.7,<4.0"
  dgl = [
  	{ git = "https://github.com/dmlc/dgl.git", tag = "v0.7.0", markers = "sys_platform == 'linux'"},
  	{ version="^0.7", markers = "sys_platform == 'darwin'"}
  ]

  [build-system]
  requires = ["poetry-core>=1.0.0"]
  build-backend = "poetry.core.masonry.api"
  ```
## Issue
When using this `pyproject.toml`, I get the following exception:
```
  TypeError

  expected string or bytes-like object

  at /usr/lib/python3.9/site-packages/poetry/core/utils/helpers.py:27 in canonicalize_name
       23│ _canonicalize_regex = re.compile(r"[-_]+")
       24│ 
       25│ 
       26│ def canonicalize_name(name):  # type: (str) -> str
    →  27│     return _canonicalize_regex.sub("-", name).lower()
       28│ 
       29│ 
       30│ def module_name(name):  # type: (str) -> str
       31│     return canonicalize_name(name).replace(".", "_").replace("-", "_")
```

**Comment by aalok-sathe** [comment] 2021-11-02 17:27
Indeed, the bug seems to be stemming from [this line](https://github.com/python-poetry/poetry/blob/10d555984485088cf5d55979c1b235286de8e456/poetry/repositories/installed_repository.py#L115).

In what circumstance is the name returned by distribution metadata not a string? When it is `None` for some reason?

**Comment by aalok-sathe** [comment] 2021-11-02 17:32
But yes, I am encountering this bug quite often, and arbitrarily, so it's pretty annoying.
Sometimes poetry works fine, but then suddenly it will start throwing this error out of nowhere.

**Comment by abn** [comment] 2022-05-19 11:43
Closing as a duplicate of #3628 as it has more information.

**Closed by abn** 2022-05-19 11:43 UTC
Labels: Bug, Triage
