### ISSUE TITLE
Command poetry env use get error on windows 10

### ISSUE THREAD

**Issue by JWillSP** [python-poetry/poetry#3524] opened 2021-01-01 14:19 UTC
python 3.9.1
poetry 1.1.4

PS C:\Users\jw_wi\OneDrive\Desktop\primeiro programa> poetry env use 3.9
Creating virtualenv primeiro_programa-rBrVYlXr-py3.9 in C:\Users\jw_wi\AppData\Local\pypoetry\Cache\virtualenvs

  EnvCommandError

  Command C:\Users\jw_wi\AppData\Local\pypoetry\Cache\virtualenvs\primeiro_programa-rBrVYlXr-py3.9\Scripts\python.exe - errored with the following return code 1, and output:
  O sistema nÆo pode encontrar o caminho especificado.
  input was : import sys

  if hasattr(sys, "real_prefix"):
      print(sys.real_prefix)
  elif hasattr(sys, "base_prefix"):
      print(sys.base_prefix)
  else:
      print(sys.prefix)

  at ~\.poetry\lib\poetry\utils\env.py:1074 in _run
      1070│                 output = subprocess.check_output(
_)
      1075│
      1076│         return decode(output)
      1077│
      1078│     def execute(self, bin, *args, **kwargs):
 

- [ ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [ ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: 
- **Poetry version**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**:

**Comment by AlexJoz** [comment] 2021-01-05 01:04
Confirm the same on win10 and py3.8

**Comment by BrieoRobino** [comment] 2021-01-06 06:04
Tried fresh install many times and getting same error on Windows 10.

**Comment by Yajo** [comment] 2021-02-01 19:53
Same here. Any workaround?

**Comment by frankier** [comment] 2021-02-10 11:03
Looks like it's a line ending problem in the activate script? http://randomwits.com/blog/poetry-python-fail-windows

**Comment by pawamoy** [comment] 2021-03-12 20:44
Probably a duplicate of #2629, though the title here is more explicit.

**Comment by nh916** [comment] 2022-01-19 09:20
any luck on this issue?

**Comment by neersighted** [comment] 2022-09-24 13:36
Closing for now as this has changed significantly with 1.2. If you run into this and can reproduce it, please open an issue with detailed information on OS version, Python version, install method, and anything else that makes your configuration unique.

**Closed by neersighted** 2022-09-24 13:36 UTC
Labels: kind/bug, area/windows, status/needs-reproduction
