### ISSUE TITLE
[question] How to use poetry on Ubuntu?

### ISSUE THREAD

**Issue by jabbalaci** [python-poetry/poetry#1543] opened 2019-11-05 10:43 UTC
I made a poetry-based project on Manjaro, where python3 is the default.

On another machine, which has Ubuntu 18.04, I wanted to re-create the virt. env. but I got the following error:

```
$ poetry install                              
/home/jabba/.poetry/lib/poetry/_vendor/py2.7/subprocess32.py:149: RuntimeWarning: The _posixsubprocess module is not being used. Child process reliability may suffer if your program uses threads.
  "program uses threads.", RuntimeWarning)
                                                                              
[RuntimeError]                                                 
The current Python version (2.7.15) is not supported by the project (^3.6)  
Please activate a compatible Python version.
```

Under my Ubuntu python points to Python 2.7, it's true, but Ubuntu has a python3 symlink that points to Python 3.6.

I think poetry should pick Python 3 automatically. But anyway, how can I create a Python 3 virt. env. in this case? Thanks.

**Comment by jabbalaci** [comment] 2019-11-05 10:48
I even tried this trick:

    curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python3

Notice "python3" at the end, but it didn't solve my problem. I still get the same error, i.e. it's still using Python 2.7.

**Comment by pmav99** [comment] 2019-11-05 10:50
@jabbalaci you can create a virtualenv manually, activate it and then poetry will use that one. E.g.
```
python3 -mvenv ./.venv
./.venv/bin/activate
poetry ...
```

**Comment by jabbalaci** [comment] 2019-11-05 10:53
@pmav99 Thanks, but it's a workaround solution. If poetry wants to be better than pipenv, then it should just work out of the box.

**Comment by jabbalaci** [comment] 2019-11-05 11:04
OK, I found a way (using https://github.com/sdispater/poetry/issues/721):

Install with Python 3:

    curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python3

Then edit the file `~/.poetry/bin/poetry` and change the first line to:

    #!/usr/bin/env python3

That is, `python` is changed to `python3`.

The bad news is that if you update poetry to a new version, this change will be overwritten very likely.

**Comment by aizelauna** [comment] 2019-11-05 21:36
Thanks for this solution.
It solved my issue similar to the #1257.

**Comment by RileyMShea** [comment] 2019-11-14 11:27
Thanks @jabbalaci fixed my issue too.

**Comment by matthijskooijman** [comment] 2019-11-17 17:07
I think this is essentially a duplicate of #721

**Comment by jabbalaci** [comment] 2019-11-17 17:31
@matthijskooijman Previously, I put a reference on https://github.com/sdispater/poetry/issues/721 .

**Comment by danieleades** [comment] 2019-12-16 13:56
this workaround is not working for me on ubuntu 18.04

**Comment by jabbalaci** [comment] 2019-12-30 12:55
@danieleades Did you install it with python3? Notice that I have python3 at the end of this line:
```
curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python3
```
I didn't try it under Ubuntu though. Under Manjaro it worked for me. Under Ubuntu, `python` points to Python 2.

**Comment by danieleades** [comment] 2019-12-30 12:57
@jabbalaci yep.

**Comment by pmav99** [comment] 2019-12-30 15:24
For the record, installing using [pipx](https://github.com/pipxproject/pipx) is probably much easier... 
And this does not apply just to `poetry` but to any python utility.

**Comment by finswimmer** [comment] 2019-12-30 17:14
Hello @all,

I'm closing this issue, because the original issue is resolved in poetry 1.0.

If poetry is installed with python2 and a `pyproject.toml` defines python3 as a dependency, poetry will try to find `python3` for creating the venv. The same the other way round.

Furthermore, you can set the python executable, to use for the venv, with the new `env` subcommand, e.g. `poetry env use python3`.

More information are available in the [docs](https://python-poetry.org/docs/managing-environments/).

**Closed by finswimmer** 2019-12-30 17:14 UTC
Labels: Bug

**Comment by danieleades** [comment] 2019-12-30 18:41
Hi @finswimmer i've just tested this on ubuntu-
the same issue occurs if poetry is installed using python3, however the workaround now works (namely changing the shebang in `/bin/poetry` to "python3").

I don't think its fair to say the issue is *completely* resolved.

I didn't test installing with python2, it's practically 2020 after all ;)

**Comment by seanwu1105** [comment] 2020-01-08 08:03
I faced the same issue when I try to install poetry on clean Ubuntu 18.04 as it does not install built-in `python` (2.x). By using the workaround (`#!/usr/bin/env python3`), I still could not use the poetry with [the error messages on this issue](https://github.com/python-poetry/poetry/issues/1837#issue-545931526).

**Comment by Jarmos-san** [comment] 2020-05-20 15:17
The issue is still very prevalent on Ubuntu 19.10, so I don't think so its wise closing this issue yet. I tried @jabalacci's workaround, it installs fine but when I try checking if it installed properly using the `poetry --version` command, I get a `poetry: command not found error`.

Please look into it.

**Comment by matthijskooijman** [comment] 2020-05-20 16:03
Also: I think the problem reported in *this* issue has been fixed. If you run into new issues that happen to be on Ubuntu, better to open up a new issue (or look at other existing issues, such as #721 or #1837).

**Comment by McKenlly** [comment] 2021-06-30 19:53
see env file into poetry hidden dir 
```export PATH="$HOME/.poetry/bin:$PATH"```
