### ISSUE TITLE
Changing `develop` option is not reflected

### ISSUE THREAD

**Issue by tamuhey** [python-poetry/poetry#3085] opened 2020-10-05 11:54 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Mac OS X 10.14.6
- **Poetry version**: 1.1.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://github.com/tamuhey/poetry111_bug_mvce (not gist)

## Issue

TLDR; changing `develop` of a dependency field and `poetry update` don't have any effect.

I have a project consists of two poetry project:

```
. --  foo/
  |     |- pyproject.toml
  |-- bar/
        |- pyproject.toml
```

`foo` depends on `bar` as follows: 

```toml
# pyproject.toml
...
[tool.poetry.dependencies]
python = "^3.8"
bar = {path="../bar"}
...
```

(Full example here: https://github.com/tamuhey/poetry111_bug_mvce/blob/master/foo/pyproject.toml)

Since the editable mode is false by default from poetry v1.1, `bar` is copied into another directory. It's ok.

But, after changing the dependency of `bar` to editable (`develop = true`) as follows and running `poetry update` don't change anything, as I expected that `bar` is changed to editable dependency.

```toml
# pyproject.toml
...
[tool.poetry.dependencies]
python = "^3.8"
bar = {path="../bar", develop=true}
...
```

**Comment by ginty** [comment] 2020-10-05 21:03
I came here to say the same thing.

I expect that with `develop=true` a link will be created to the given path, such that when the files are updated they are automatically reflected in the parent app.

That works fine on `1.0.10` (without develop=true) but on `1.1.0` the dependency is copied into the virtualenv so that updates to the original source have no effect, even with `develop=true`.

**Comment by abn** [comment] 2020-10-05 22:52
@ginty that is what happens. The dependency is not copied, but installed as an editable dependency. However, since we do not use the `egg-link` hack, `pip` will not show it as a "develop" depenency.

@tadeoos am I correct in assuming that your scenario is an existing virtual environment created using `1.0.10`? If so you will have to either re-add the dependency or re-create the virtualenvironment or do `poetry run pip uninstall bar` first. The previous installation would have used `egg-links`, when doing an update with `develop=true` nothing will change, since it is what it was defaulting to previously.

**Comment by tamuhey** [comment] 2020-10-06 03:29
> am I correct in assuming that your scenario is an existing virtual environment created using 1.0.10?

No. The venv is created by poetry v1.1.1

> If so you will have to either re-add the dependency or re-create the virtualenvironment or do poetry run pip uninstall bar first.

Ok, I'll deal with it that way for now.

**Comment by tamuhey** [comment] 2020-10-06 03:32
One question: Changing the default value for `develop` breaks backwards compatibility (e.g. in case of using symlink). Why this change is introduced in `v1.1`?

**Comment by ginty** [comment] 2020-10-06 08:31
Thanks for the quick replay @abn. I don't really understand what you mean, however, as this may be going off on a tangent from the original thread I've opened #3096 for further discussion on it.

**Comment by lochsh** [comment] 2021-12-07 11:15
I am still seeing this issue on poetry 1.1.12. To be explicit:

* `pyproject.toml` has `dep = {path = "/path/to/dep"}`
* I run `poetry update`
* `/path/to/dep` is copied into the venv, as expected
* I edit `pyproject.toml` to have `dep = {path = "/path/to/dep", develop=true}`
* I run `poetry update`
* Instead of the `dep` in the venv being replaced by ` dep.pth` file, it is not replaced and so I do not have an editable dependency.

Issues such as this and https://github.com/python-poetry/poetry/issues/3958 make it hard to feel confident that `poetry update` has done the right thing -- it's a shame to spend time cautiously deleting venvs just in case.

**Comment by kkuriata** [comment] 2022-04-11 19:27
Yeah. I can confirm that it is really annoying. It's hard to develop anything when you have to `poetry update` after changes... And it takes much time to do that.

**Comment by smcoll** [comment] 2022-11-07 23:02
Using 1.2.1 i was able to get an editable install working by updating to `develop = true` in the lockfile as well, then deleting the virtual environment (i'm using local .venv dir) before a `poetry install`.  This method is creating a `.pth` file for each dependency in `site-packages`.

Of course, the issue description is still valid.

**Comment by neersighted** [comment] 2022-11-08 00:21
Resolved in https://github.com/python-poetry/poetry/pull/6843.

**Closed by neersighted** 2022-11-08 00:21 UTC
Labels: area/solver, kind/enhancement
