### ISSUE TITLE
1.1a3 sometimes removes pkg_resources with --remove-untracked

### ISSUE THREAD

**Issue by PetterS** [python-poetry/poetry#2673] opened 2020-07-16 07:37 UTC
Filing an issue about this as well (there is also a PR; #2624)

Reproduces quite easily for me:
```
$ poetry install --remove-untracked
Creating virtualenv testenv-wETKOq8S-py3.8 in /home/petter/.cache/pypoetry/virtualenvs
Installing dependencies from lock file

Package operations: 22 installs, 0 updates, 1 removal

  • Removing pkg-resources (0.0.0)
  • Installing decorator (4.4.2)
  • Installing ipython-genutils (0.2.0)
  • Installing parso (0.7.0)
  • Installing ptyprocess (0.6.0)
  • Installing pyparsing (2.4.7)
  • Installing six (1.14.0)
  • Installing wcwidth (0.1.9)
  • Installing attrs (19.3.0)
  • Installing backcall (0.1.0): Failed

  EnvCommandError

  Command ['/home/petter/.cache/pypoetry/virtualenvs/testenv-wETKOq8S-py3.8/bin/python', '-m', 'pip', 'install', '--no-deps', '/home/petter/.cache/pypoetry/artifacts/bd/9e/06/91ad63fb068b06d5a00cd3f0e232424bd7000532c6babbfb1e9ce3333f/backcall-0.1.0.tar.gz'] errored with the following return code 1, and output:
  Processing /home/petter/.cache/pypoetry/artifacts/bd/9e/06/91ad63fb068b06d5a00cd3f0e232424bd7000532c6babbfb1e9ce3333f/backcall-0.1.0.tar.gz
      ERROR: Command errored out with exit status 1:
       command: /home/petter/.cache/pypoetry/virtualenvs/testenv-wETKOq8S-py3.8/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-rdqg7x73/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-rdqg7x73/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-rdqg7x73/pip-egg-info
           cwd: /tmp/pip-req-build-rdqg7x73/
      Complete output (7 lines):
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/home/petter/.cache/pypoetry/virtualenvs/testenv-wETKOq8S-py3.8/lib/python3.8/site-packages/setuptools/__init__.py", line 18, in <module>
          import setuptools.version
        File "/home/petter/.cache/pypoetry/virtualenvs/testenv-wETKOq8S-py3.8/lib/python3.8/site-packages/setuptools/version.py", line 1, in <module>
          import pkg_resources
      ModuleNotFoundError: No module named 'pkg_resources'
      ----------------------------------------
  ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.


  at /usr/local/lib/python3.8/dist-packages/poetry/utils/env.py:937 in _run
       933│                 output = subprocess.check_output(
       934│                     cmd, stderr=subprocess.STDOUT, **kwargs
       935│                 )
       936│         except CalledProcessError as e:
    →  937│             raise EnvCommandError(e, input=input_)
       938│
       939│         return decode(output)
       940│
       941│     def execute(self, bin, *args, **kwargs):

  • Installing jedi (0.17.0)
  • Installing more-itertools (8.2.0)
  • Installing packaging (20.3)
  • Installing pexpect (4.8.0)
  • Installing pickleshare (0.7.5)
  • Installing pluggy (0.13.1)
  • Installing prompt-toolkit (3.0.3)
  • Installing py (1.8.1)
  • Installing pygments (2.6.1)
  • Installing traitlets (4.3.3)
```

pyproject.toml:
```
[tool.poetry]
name = "testenv"
version = "0.1.0"
description = ""
authors = ["Petter"]

[tool.poetry.dependencies]
python = "^3.6"
pytest = "^5.4.2"
quickjs = "^1.12.0"
ipython = "^7.14.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```

**Comment by PetterS** [comment] 2020-07-16 07:38
After the above happens, the virtualenv is broken and must be deleted.

**Comment by PetterS** [comment] 2020-07-16 07:39
Possibly happens only in Ubuntu? https://stackoverflow.com/questions/39577984/what-is-pkg-resources-0-0-0-in-output-of-pip-freeze-command

**Comment by PetterS** [comment] 2020-07-16 07:50
Reproduces for me every time on WSL Ubuntu 20.04 with the attached pyproject file:
```
Description:    Ubuntu 20.04 LTS
Release:        20.04  
Codename:       focal
```

Removing the python3-virtualenv package as suggested on SO does not help because it is not installed.

**Comment by abn** [comment] 2020-07-17 08:53
@PetterS I'll try it in a VM later see if I can help narrow down the issue. In the meantime, would it be possible to install from the `develop` branch, see if that helps? There is a change relating to virtual environment creation on there that's not yet released.

**Comment by PetterS** [comment] 2020-07-17 15:23
Is there an easy way of installing the `develop` version of Poetry? I know of one way: builing the wheel and then pip installing it.

**Comment by PetterS** [comment] 2020-07-17 15:31
```
$ python3 -m virtualenv .
created virtual environment CPython3.8.2.final.0-64 in 2287ms
  creator CPython3Posix(dest=/tmp/test, clear=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/petter/.local/share/virtualenv)
    added seed packages: pip==20.1.1, setuptools==49.2.0, wheel==0.34.2
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
$ source bin/activate
test $ pip freeze
test $
```
So just creating a virtualenv does not list `pkg-resources` for me (as suggested by SO).

**Comment by PetterS** [comment] 2020-07-17 15:41
Latest `develop` branch works!
```
$ rm -rf /home/petter/.cache/pypoetry/virtualenvs/testenv-wETKOq8S-py3.8
$ poetry install --remove-untracked
Creating virtualenv testenv-wETKOq8S-py3.8 in /home/petter/.cache/pypoetry/virtualenvs
Installing dependencies from lock file

Package operations: 22 installs, 0 updates, 1 removal

  • Removing wheel (0.34.2)
  • Installing decorator (4.4.2)
  • Installing ipython-genutils (0.2.0)
  • Installing parso (0.7.0)
  • Installing ptyprocess (0.6.0)
  • Installing pyparsing (2.4.7)
  • Installing six (1.14.0)
  • Installing wcwidth (0.1.9)
  • Installing attrs (19.3.0): Installing...
  • Installing attrs (19.3.0)
  • Installing backcall (0.1.0)
  • Installing jedi (0.17.0)
  • Installing more-itertools (8.2.0)
  • Installing packaging (20.3)
  • Installing pexpect (4.8.0)
  • Installing pickleshare (0.7.5)
  • Installing pluggy (0.13.1)
  • Installing prompt-toolkit (3.0.3)
  • Installing py (1.8.1)
  • Installing pygments (2.6.1)
  • Installing traitlets (4.3.3)
  • Installing ipython (7.14.0)
  • Installing pytest (5.4.2)
  • Installing quickjs (1.12.0)
$ poetry install --remove-untracked
Installing dependencies from lock file


No dependencies to install or update
```

But note that it now does `Removing wheel (0.34.2)`.

**Comment by PetterS** [comment] 2020-07-17 17:06
It will still give a quite unpleasant upgrade experience from 1.0.x to 1.1.0.

**Comment by abn** [comment] 2020-07-18 07:43
> Is there an easy way of installing the `develop` version of Poetry?

If you have used pip to install `poetry`, then you use:
```sh
pip install --user git+https://github.com/python-poetry/poetry.git@develop
```

> But note that it now does `Removing wheel (0.34.2)`. Not a big problem I think, since that (unlike pkg-resources) can be added to pyproject.toml.

We might need to add wheel to the `UNSAFE_PACKAGES` list, since it is now installed into the environment. Although, I am not sure if we need really the wheel package at all when we create the venv, since poetry already manages the download and build of wheel packages. We could disable it at creation.

> It could still give a quite unpleasant upgrade experience from 1.0.x to 1.1.0, since the virtualenv may have to be deleted and rebuilt from scratch (once).

Considering that this issue is isolated to very specific environments (as best as we can tell), the effort to workaround an issue like this might be significantly higher than the benefits. And especially since we still do not know what the root cause was here. I think having to rebuilt a `venv` is an acceptable workaround.

**Comment by PetterS** [comment] 2020-07-19 20:09
> Considering that this issue is isolated to very specific environments (as best as we can tell), the effort to workaround an issue like this might be significantly higher than the benefits. And especially since we still do not know what the root cause was here. I think having to rebuilt a venv is an acceptable workaround.

I think it should affect all (or at the very least all in 20.04) environment created with <1.1. If using poetry in production (like we do), this has to be taken into account when migrating from 1.0.x to 1.1. The fact that virtualenvs may need to be recreated should be clearly mentioned in the release notes for 1.1.

**Comment by abn** [comment] 2020-07-19 20:39
> I think it should affect all (or at the very least all in 20.04) environment created with <1.1. If using poetry in production (like we do), this has to be taken into account when migrating from 1.0.x to 1.1. The fact that virtualenvs may need to be recreated should be clearly mentioned in the release notes for 1.1.

I should have been clearer. The upgrade to `1.1.0` from `1.0.x` should not require a recreation of virtual environment. I am referring to the use of `--remove-untracked` feature breaking the environment, which is not reproducible using `develop`. Any existing environment should function as is if upgrading from `1.0.x` to `1.1.0`. 

> If using poetry in production (like we do)
I would not recommend using poetry for managing your production environments. While it is certainly a pattern projects have been using in the wild - `poetry run app` or the like, this is not really best practice.

**Comment by PetterS** [comment] 2020-07-20 08:50
> I should have been clearer. The upgrade to 1.1.0 from 1.0.x should not require a recreation of virtual environment. I am referring to the use of --remove-untracked feature breaking the environment, which is not reproducible using develop. Any existing environment should function as is if upgrading from 1.0.x to 1.1.0.

But if I create an environment with 1.0.x it will use the old method of creating the virtualenv. Then, after upgrading to 1.1.0 and running `install --remove-untracked`, it will run into this bug, right?

**Comment by snejus** [comment] 2020-07-23 03:49
I Have just experienced it myself and after quite a lot of digging and confusion had to rebuild the environment. Having realised that `1.1.0a3` doesn't install the root project in the editable mode had to downgrade it back to `1.1.0a1`, even though I loved the new installer.

**Comment by abn** [comment] 2020-07-23 13:59
> But if I create an environment with 1.0.x it will use the old method of creating the virtualenv. Then, after upgrading to 1.1.0 and running `install --remove-untracked`, it will run into this bug, right?

@PetterS You might run into it on very specific scenarios where this could be an issue. And even then, it is seems like an issue of the environment and not necessarily how poetry manages it. I am still not sure how `pkg_resources` is detected as an installed package in your environment since the namespace is installed due to `setuptools` installation, any insights into this welcome. In these cases, the fix really is to recreate your virtual environment. And I feel that is not necessarily a bad compromise considering that the issue is an edge case and requires multiple pre-conditions to be met. If this is more widespread than I suspect it is and the root cause is complex to fix, we could discuss marking the package as protected as you originally suggested.

> Having realised that 1.1.0a3 doesn't install the root project in the editable mode had to downgrade it back to 1.1.0a1, even though I loved the new installer.

@snejus that should be resolved with the next pre-relese.

**Comment by PetterS** [comment] 2020-08-03 07:37
Since we are apparently not the only ones running into this issue, I think a notice or warning that the virtualenv may need to be recreated is in order.

For me personally, it is not a big issue or course, since I am aware of this issue and the work-around.

**Comment by PetterS** [comment] 2020-09-21 14:18
Still would be nice if Poetry recreated the virtualenv automatically, or had some protection against

> Removing pkg-resources (0.0.0)

**Comment by PetterS** [comment] 2020-09-21 14:21
@abn is there a way to detect if a virtualenv was created with Poetry 1.0.x so we, after upgrading to 1.1, can delete it automatically and recreate it?

**Comment by abn** [comment] 2020-09-21 17:32
@PetterS unfortunately no, since poetry does not have a notion of this all it cares about is pip and python. 

Regarding this issue. Can you try reproducing this with a migration form `1.0.10` to `1.1.0b3` please? There has been a few improvements in package detection.

**Comment by PetterS** [comment] 2020-09-26 15:22
I tried this in a Windows Sandbox (therefore having a clean install).  Could not reproduce it there, which is good!

**Comment by PetterS** [comment] 2020-09-26 15:26
Let's close this since it no longer reproduces! 👍

**Comment by PetterS** [comment] 2020-11-06 12:25
Happened to me when upgrading a machine from 1.0.10 to 1.1.4 today.

**Comment by IceTDrinker** [comment] 2021-08-15 11:42
Hitting the same issue with Poetry version 1.1.7 installed via pip and a venv created via `python3 -m venv venv`

Forcing the reinstallation of setuptools while inside the venv works around it :
`pip3 install -U --force setuptools`

but the remove untracked breaks the venv again

**Comment by kroeschl** [comment] 2021-11-18 18:07
I'm running into the same issue with poetry 1.1.11 on Debian 11 using Python 3.9. I'm currently working around this by manually adding `pkg-resources` to `UNSAFE_PACKAGES` (per [this comment above](https://github.com/python-poetry/poetry/issues/2673#issuecomment-660444795)).

```
$ python3.9 -m venv --clear ./venv-bug
$ . ./venv-bug/bin/activate
(venv-bug) $ POETRY_VIRTUALENVS_CREATE=false poetry install --remove-untracked
Installing dependencies from lock file

Package operations: 2 installs, 0 updates, 1 removal

  • Removing pkg-resources (0.0.0)
  • Installing pyasn1 (0.4.8)
  • Installing pysmb (1.2.7): Failed

  EnvCommandError

  Command ['/home/foo/poetry-bug/venv-bug/bin/pip', 'install', '--no-deps', 'file:///home/foo/.cache/pypoetry/artifacts/d8/12/7e/db5c09bbeef9f045e6c6866fd4c9ab5139ba81dbac512372c0d783e563/pysmb-1.2.7.zip'] errored with the following return code 1, and output:
  Looking in indexes: https://pypi.ni.systems
  Processing /home/foo/.cache/pypoetry/artifacts/d8/12/7e/db5c09bbeef9f045e6c6866fd4c9ab5139ba81dbac512372c0d783e563/pysmb-1.2.7.zip
      ERROR: Command errored out with exit status 1:
       command: /home/foo/poetry-bug/venv-bug/bin/python3.9 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-6nhzup0v/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-6nhzup0v/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-nb8jp9xd
           cwd: /tmp/pip-req-build-6nhzup0v/
      Complete output (7 lines):
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/home/foo/poetry-bug/venv-bug/lib/python3.9/site-packages/setuptools/__init__.py", line 18, in <module>
          import setuptools.version
        File "/home/foo/poetry-bug/venv-bug/lib/python3.9/site-packages/setuptools/version.py", line 1, in <module>
          import pkg_resources
      ModuleNotFoundError: No module named 'pkg_resources'
      ----------------------------------------
  WARNING: Discarding file:///home/foo/.cache/pypoetry/artifacts/d8/12/7e/db5c09bbeef9f045e6c6866fd4c9ab5139ba81dbac512372c0d783e563/pysmb-1.2.7.zip. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.


  at ~/.local/share/pypoetry/venv/lib/python3.9/site-packages/poetry/utils/env.py:1183 in _run
      1179│                 output = subprocess.check_output(
      1180│                     cmd, stderr=subprocess.STDOUT, **kwargs
      1181│                 )
      1182│         except CalledProcessError as e:
    → 1183│             raise EnvCommandError(e, input=input_)
      1184│
      1185│         return decode(output)
      1186│
      1187│     def execute(self, bin, *args, **kwargs):
```
`pyproject.toml` and `poetry.lock`:
<details>

```
[tool.poetry]
name = "foo"
version = "0.1"
description = "bar"
authors = []

[tool.poetry.dependencies]
python = "*"
pysmb = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```

```
[[package]]
name = "pyasn1"
version = "0.4.8"
description = "ASN.1 types and codecs"
category = "main"
optional = false
python-versions = "*"

[[package]]
name = "pysmb"
version = "1.2.7"
description = "pysmb is an experimental SMB/CIFS library written in Python to support file sharing between Windows and Linux machines"
category = "main"
optional = false
python-versions = "*"

[package.dependencies]
pyasn1 = "*"

[metadata]
lock-version = "1.1"
python-versions = "*"
content-hash = "080ba167fcc9a27176053264c6dd4c8e536be6c6448a42bcca30eb7a0da0b73a"

[metadata.files]
pyasn1 = [
    {file = "pyasn1-0.4.8-py2.4.egg", hash = "sha256:fec3e9d8e36808a28efb59b489e4528c10ad0f480e57dcc32b4de5c9d8c9fdf3"},
    {file = "pyasn1-0.4.8-py2.5.egg", hash = "sha256:0458773cfe65b153891ac249bcf1b5f8f320b7c2ce462151f8fa74de8934becf"},
    {file = "pyasn1-0.4.8-py2.6.egg", hash = "sha256:5c9414dcfede6e441f7e8f81b43b34e834731003427e5b09e4e00e3172a10f00"},
    {file = "pyasn1-0.4.8-py2.7.egg", hash = "sha256:6e7545f1a61025a4e58bb336952c5061697da694db1cae97b116e9c46abcf7c8"},
    {file = "pyasn1-0.4.8-py2.py3-none-any.whl", hash = "sha256:39c7e2ec30515947ff4e87fb6f456dfc6e84857d34be479c9d4a4ba4bf46aa5d"},
    {file = "pyasn1-0.4.8-py3.1.egg", hash = "sha256:78fa6da68ed2727915c4767bb386ab32cdba863caa7dbe473eaae45f9959da86"},
    {file = "pyasn1-0.4.8-py3.2.egg", hash = "sha256:08c3c53b75eaa48d71cf8c710312316392ed40899cb34710d092e96745a358b7"},
    {file = "pyasn1-0.4.8-py3.3.egg", hash = "sha256:03840c999ba71680a131cfaee6fab142e1ed9bbd9c693e285cc6aca0d555e576"},
    {file = "pyasn1-0.4.8-py3.4.egg", hash = "sha256:7ab8a544af125fb704feadb008c99a88805126fb525280b2270bb25cc1d78a12"},
    {file = "pyasn1-0.4.8-py3.5.egg", hash = "sha256:e89bf84b5437b532b0803ba5c9a5e054d21fec423a89952a74f87fa2c9b7bce2"},
    {file = "pyasn1-0.4.8-py3.6.egg", hash = "sha256:014c0e9976956a08139dc0712ae195324a75e142284d5f87f1a87ee1b068a359"},
    {file = "pyasn1-0.4.8-py3.7.egg", hash = "sha256:99fcc3c8d804d1bc6d9a099921e39d827026409a58f2a720dcdb89374ea0c776"},
    {file = "pyasn1-0.4.8.tar.gz", hash = "sha256:aef77c9fb94a3ac588e87841208bdec464471d9871bd5050a287cc9a475cd0ba"},
]
pysmb = [
    {file = "pysmb-1.2.7.zip", hash = "sha256:298605b8f467ce15b412caaf9af331c135e88fa2172333af14b1b2916361cb6b"},
]
```

</details>

Environment info:
```
$ poetry --version
Poetry version 1.1.11
$ which poetry
/home/foo/.local/bin/poetry
$ . venv-bug/bin/activate
(venv-bug) $ pip freeze --all
pip==20.3.4
pyasn1 @ file:///home/foo/.cache/pypoetry/artifacts/7b/3a/54/42ce43b579bda01b9d79022fb733811594441e7a32e9f9a5a98f672bdc/pyasn1-0.4.8-py2.py3-none-any.whl
setuptools==44.1.1
```

System Python packages:
<details>

```
$ ls /usr/lib/python3/dist-packages/ | grep "setuptools\|pkg_resources"
pkg_resources
setuptools
setuptools-58.2.0.egg-info
$ apt list --installed python3*
Listing... Done
python3-apt/now 2.2.1 amd64 [installed,upgradable to: 2.3.0]
python3-bcrypt/now 3.1.7-4 amd64 [installed,upgradable to: 3.2.0-1]
python3-blinker/now 1.4+dfsg1-0.3 all [installed,upgradable to: 1.4+dfsg1-0.4]
python3-breezy/testing,now 3.1.0-8 amd64 [installed,automatic]
python3-brlapi/now 6.3+dfsg-1 amd64 [installed,upgradable to: 6.4-2]
python3-bs4/now 4.9.3-1 all [installed,upgradable to: 4.10.0-2]
python3-cairo/testing,now 1.16.2-4+b2 amd64 [installed,automatic]
python3-certifi/testing,testing,now 2020.6.20-1 all [installed,automatic]
python3-cffi-backend/now 1.14.5-1 amd64 [installed,upgradable to: 1.15.0-1]
python3-chardet/testing,testing,now 4.0.0-1 all [installed,automatic]
python3-click/testing,testing,now 7.1.2-1 all [installed,automatic]
python3-colorama/testing,testing,now 0.4.4-1 all [installed,automatic]
python3-configobj/now 5.0.6-4 all [installed,upgradable to: 5.0.6-5]
python3-crypto/now 2.6.1-13.1+b3 amd64 [installed,local]
python3-cryptography/testing,now 3.3.2-1 amd64 [installed,automatic]
python3-cups/now 2.0.1-4+b1 amd64 [installed,upgradable to: 2.0.1-5]
python3-cupshelpers/testing,testing,now 1.5.14-1 all [installed,automatic]
python3-dbus.mainloop.pyqt5/now 5.15.2+dfsg-3 amd64 [installed,upgradable to: 5.15.6+dfsg-1]
python3-dbus/now 1.2.16-5 amd64 [installed,upgradable to: 1.2.18-3]
python3-debconf/now 1.5.77 all [installed,upgradable to: 1.5.79]
python3-debian/now 0.1.39 all [installed,upgradable to: 0.1.42]
python3-debianbts/now 3.1.0 all [installed,upgradable to: 3.2.0]
python3-deprecated/now 1.2.11-1 all [installed,upgradable to: 1.2.13-2]
python3-dev/testing,now 3.9.7-1 amd64 [installed]
python3-distro-info/now 1.0 all [installed,upgradable to: 1.1]
python3-distro/now 1.5.0-1 all [installed,upgradable to: 1.6.0-2]
python3-distutils/testing,testing,now 3.9.7-1 all [installed,automatic]
python3-dnspython/testing,testing,now 2.0.0-1 all [installed,automatic]
python3-docopt/now 0.6.2-3 all [installed,upgradable to: 0.6.2-4]
python3-dulwich/now 0.20.15-1 amd64 [installed,upgradable to: 0.20.25-1+b1]
python3-fastimport/testing,testing,now 0.9.8-5 all [installed,automatic]
python3-flake8/testing,testing,now 3.8.4-1 all [installed,automatic]
python3-flask/now 1.1.2-2 all [installed,upgradable to: 1.1.2-3]
python3-gi-cairo/now 3.38.0-2 amd64 [installed,upgradable to: 3.42.0-1+b1]
python3-gi/now 3.38.0-2 amd64 [installed,upgradable to: 3.42.0-1+b1]
python3-github/now 1.43.7-1 all [installed,upgradable to: 1.55-1]
python3-gitlab/now 1:2.5.0-1 all [installed,upgradable to: 1:2.10.0-1]
python3-gpg/now 1.14.0-1+b2 amd64 [installed,upgradable to: 1.16.0-1.1]
python3-html5lib/testing,testing,now 1.1-3 all [installed,automatic]
python3-httplib2/testing,testing,now 0.18.1-3 all [installed,automatic]
python3-ibus-1.0/now 1.5.23-2 all [installed,upgradable to: 1.5.25-2]
python3-idna/testing,testing,now 2.10-1 all [installed,automatic]
python3-invoke/testing,testing,now 1.4.1+ds-0.1 all [installed,automatic]
python3-itsdangerous/now 1.1.0-3 all [installed,upgradable to: 2.0.1-1]
python3-jeepney/testing,testing,now 0.6.0-1 all [installed,automatic]
python3-jinja2/now 2.11.3-1 all [installed,upgradable to: 3.0.1-2]
python3-jwt/now 1.7.1-2 all [installed,upgradable to: 2.1.0-1]
python3-keyring/now 22.0.1-1 all [installed,upgradable to: 23.2.0-1]
python3-keyrings.alt/now 4.0.2-1 all [installed,upgradable to: 4.1.0-1]
python3-launchpadlib/now 1.10.13-1 all [installed,upgradable to: 1.10.15.1-1]
python3-lazr.restfulclient/now 0.14.2-2 all [installed,upgradable to: 0.14.4-1]
python3-lazr.uri/now 1.0.5-1 all [installed,upgradable to: 1.0.6-1]
python3-ldb/now 2:2.2.0-3.1 amd64 [installed,upgradable to: 2:2.2.3-2]
python3-lib2to3/testing,testing,now 3.9.7-1 all [installed,automatic]
python3-libvirt/testing,now 7.0.0-2 amd64 [installed,automatic]
python3-libxml2/now 2.9.10+dfsg-6.7 amd64 [installed,upgradable to: 2.9.12+dfsg-5]
python3-louis/now 3.16.0-1 all [installed,upgradable to: 3.19.0-2]
python3-lxml/now 4.6.3+dfsg-0.1 amd64 [installed,upgradable to: 4.6.3+dfsg-1]
python3-magic/now 2:0.4.20-3 all [installed,upgradable to: 2:0.4.24-2]
python3-mako/testing,testing,now 1.1.3+ds1-2 all [installed,automatic]
python3-markdown/testing,testing,now 3.3.4-1 all [installed,automatic]
python3-markupsafe/now 1.1.1-1+b3 amd64 [installed,upgradable to: 2.0.1-2]
python3-mccabe/testing,testing,now 0.6.1-3 all [installed,automatic]
python3-minimal/testing,now 3.9.7-1 amd64 [installed,automatic]
python3-nacl/testing,now 1.4.0-1+b1 amd64 [installed,automatic]
python3-numpy/testing,now 1:1.19.5-1 amd64 [installed,automatic]
python3-oauthlib/now 3.1.0-2 all [installed,upgradable to: 3.1.1-1]
python3-openssl/now 20.0.1-1 all [installed,upgradable to: 21.0.0-1]
python3-paramiko/now 2.7.2-1 all [installed,upgradable to: 2.8.0-1]
python3-parse/testing,testing,now 1.6.6-0.2 all [installed]
python3-path-and-address/testing,testing,now 2.0.1-2 all [installed,automatic]
python3-patiencediff/testing,now 0.2.1-1+b1 amd64 [installed,automatic]
python3-pip/testing,testing,now 20.3.4-4 all [installed]
python3-pkg-resources/testing,testing,now 58.2.0-1 all [installed]
python3-psutil/now 5.8.0-1 amd64 [installed,upgradable to: 5.8.0-2]
python3-pyatspi/testing,testing,now 2.38.1-1 all [installed,automatic]
python3-pycodestyle/testing,testing,now 2.6.0-1 all [installed,automatic]
python3-pycryptodome/testing,now 3.9.7+dfsg1-1+b2 amd64 [installed,automatic]
python3-pycurl/now 7.43.0.6-5 amd64 [installed,upgradable to: 7.44.1-3]
python3-pyflakes/now 2.2.0-2 all [installed,upgradable to: 2.2.0-3]
python3-pygments/testing,testing,now 2.7.1+dfsg-2.1 all [installed,automatic]
python3-pyinotify/testing,testing,now 0.9.6-1.3 all [installed,automatic]
python3-pyqt5.sip/now 12.8.1-1+b2 amd64 [installed,upgradable to: 12.9.0-3]
python3-pyqt5/now 5.15.2+dfsg-3 amd64 [installed,upgradable to: 5.15.6+dfsg-1]
python3-pysimplesoap/testing,testing,now 1.16.2-3 all [installed,automatic]
python3-pyudev/testing,testing,now 0.22.0-2 all [installed,automatic]
python3-reportbug/now 7.10.3 all [installed,upgradable to: 11.1.0]
python3-requests-toolbelt/testing,testing,now 0.9.1-1 all [installed,automatic]
python3-requests/testing,testing,now 2.25.1+dfsg-2 all [installed,automatic]
python3-rpm/testing,now 4.16.1.2+dfsg1-3 amd64 [installed]
python3-samba/now 2:4.13.5+dfsg-2 amd64 [installed,upgradable to: 2:4.13.14+dfsg-1+b1]
python3-scour/testing,testing,now 0.38.2-1 all [installed,automatic]
python3-secretstorage/testing,testing,now 3.3.1-1 all [installed,automatic]
python3-setuptools/testing,testing,now 58.2.0-1 all [installed]
python3-simplejson/now 3.17.2-1 amd64 [installed,upgradable to: 3.17.5-3]
python3-six/testing,testing,now 1.16.0-2 all [installed,automatic]
python3-smbc/now 1.0.23-1+b1 amd64 [installed,upgradable to: 1.0.23-2]
python3-socks/testing,testing,now 1.7.1+dfsg-1 all [installed,automatic]
python3-software-properties/testing,testing,now 0.96.20.2-2.1 all [installed,automatic]
python3-soupsieve/now 2.2.1-1 all [installed,upgradable to: 2.3-1]
python3-speechd/now 0.10.2-2 all [installed,upgradable to: 0.10.2-3]
python3-talloc/testing,now 2.3.1-2+b1 amd64 [installed,automatic]
python3-tdb/testing,now 1.4.3-1+b1 amd64 [installed,automatic]
python3-tk/now 3.9.2-1 amd64 [installed,upgradable to: 3.9.7-1]
python3-unidiff/testing,testing,now 0.5.5-2 all [installed,automatic]
python3-uno/now 1:7.0.4-4 amd64 [installed,upgradable to: 1:7.2.2-1]
python3-urllib3/testing,testing,now 1.26.5-1~exp1 all [installed,automatic]
python3-venv/testing,now 3.9.7-1 amd64 [installed]
python3-wadllib/now 1.3.5-1 all [installed,upgradable to: 1.3.6-1]
python3-webencodings/now 0.5.1-2 all [installed,upgradable to: 0.5.1-4]
python3-werkzeug/now 1.0.1+dfsg1-2 all [installed,upgradable to: 2.0.1+dfsg1-2]
python3-wheel/testing,testing,now 0.34.2-1 all [installed,automatic]
python3-wrapt/testing,now 1.12.1-4+b1 amd64 [installed,automatic]
python3-xdg/testing,testing,now 0.27-2 all [installed,automatic]
python3-yaml/now 5.3.1-5 amd64 [installed,upgradable to: 5.4.1-1]
python3.9-dev/testing,now 3.9.8-1 amd64 [installed,automatic]
python3.9-minimal/testing,now 3.9.8-1 amd64 [installed,automatic]
python3.9-venv/testing,now 3.9.8-1 amd64 [installed,automatic]
python3.9/testing,now 3.9.8-1 amd64 [installed,automatic]
python3/testing,now 3.9.7-1 amd64 [installed,automatic]
```

</details>

I did try this with Poetry 1.2.0a2 and saw no problem, but I'm unable to use that version due to some unrelated issues (and it being pre-release).

**Comment by neersighted** [comment] 2022-10-04 08:02
Long stale and resolved -- please comment or open a new issue if you think this still occurs.

**Closed by neersighted** 2022-10-04 08:02 UTC
Labels: kind/bug, status/triage

**Comment by ClaudiaSchulz** [comment] 2022-10-10 13:49
On Ubuntu 20.04.3 LTS with Python 3.8 and Poetry 1.2.1, using `--sync` option that now replaces `--remove-untracked` removes pgk-resources for me, which then leads to failure when installing other packages.

**Comment by neersighted** [comment] 2022-10-10 14:18
@ClaudiaSchulz can you please open a new issue with a reproduction that occurs in a container?
