### ISSUE TITLE
Lack hashes for all the wheels available on PyPi

### ISSUE THREAD

**Issue by vwxyzjn** [python-poetry/poetry#6067] opened 2022-07-25 13:34 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Pop!_OS 21.10 x86_64 
- **Poetry version**:  1.1.14
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/vwxyzjn/0103c26201d341cd8028ad128e045041

## Issue

In Python 3.9 and poetry 1.1.14, `poetry add envpool` results in a `Unable to find installation candidates for envpool (0.6.3)` error. Upon further inspection, the command only adds the hash for the py37 wheel

```
envpool = [
    {file = "envpool-0.6.3-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl", hash = "sha256:b0a758def66273fc3d0a75179f8c64a3287674507b041e8b0b9ea6dae5d5d97e"},
]
```

but the py38 and py39 wheels are clearly available on [PyPi](https://pypi.org/project/envpool/#modal-close): 

<img width="1222" alt="image" src="https://user-images.githubusercontent.com/5555347/180789479-112c93ba-166f-4757-b82e-1ddb7dca4b12.png">

Also this problem does happen w/ `poetry add envpool@0.6.2`

```
poetry add envpool
Creating virtualenv o-prh-08vR-py3.9 in /home/costa/.cache/pypoetry/virtualenvs
Using version ^0.6.3 for envpool

Updating dependencies
Resolving dependencies... (5.9s)

Writing lock file

Package operations: 12 installs, 0 updates, 0 removals

  • Installing zipp (3.8.1)
  • Installing absl-py (1.2.0)
  • Installing cloudpickle (2.1.0)
  • Installing dm-tree (0.1.7)
  • Installing gym-notices (0.0.7)
  • Installing importlib-metadata (4.12.0)
  • Installing numpy (1.23.1)
  • Installing dm-env (1.5)
  • Installing gym (0.25.0)
  • Installing types-protobuf (3.19.22)
  • Installing typing-extensions (4.3.0)
  • Installing envpool (0.6.3): Failed

  RuntimeError

  Unable to find installation candidates for envpool (0.6.3)

  at ~/.local/pipx/venvs/poetry/lib/python3.9/site-packages/poetry/installation/chooser.py:72 in choose_for
       68│ 
       69│             links.append(link)
       70│ 
       71│         if not links:
    →  72│             raise RuntimeError(
       73│                 "Unable to find installation candidates for {}".format(package)
       74│             )
       75│ 
       76│         # Get the best link


Failed to add packages, reverting the pyproject.toml file to its original content.
➜  o poetry add -vvv envpool
Using virtualenv: /home/costa/.cache/pypoetry/virtualenvs/o-prh-08vR-py3.9
PyPI: 19 packages found for envpool *
Using version ^0.6.3 for envpool

Updating dependencies
Resolving dependencies...
   1: fact: o is 0.1.0
   1: derived: o
   1: fact: o depends on envpool (^0.6.3)
   1: selecting o (0.1.0)
   1: derived: envpool (>=0.6.3,<0.7.0)
PyPI: 1 packages found for envpool >=0.6.3,<0.7.0
   1: fact: envpool (0.6.3) depends on typing-extensions (*)
   1: fact: envpool (0.6.3) depends on types-protobuf (>=3.17.3)
   1: fact: envpool (0.6.3) depends on numpy (>=1.19)
   1: fact: envpool (0.6.3) depends on gym (>=0.18)
   1: fact: envpool (0.6.3) depends on dm-env (>=1.4)
   1: selecting envpool (0.6.3)
   1: derived: dm-env (>=1.4)
   1: derived: gym (>=0.18)
   1: derived: numpy (>=1.19)
   1: derived: types-protobuf (>=3.17.3)
   1: derived: typing-extensions
PyPI: 2 packages found for dm-env >=1.4
PyPI: No release information found for gym-0.0.1, skipping
PyPI: 11 packages found for gym >=0.18
PyPI: No release information found for numpy-0.9.6, skipping
PyPI: No release information found for numpy-0.9.8, skipping
PyPI: No release information found for numpy-1.0.3, skipping
PyPI: No release information found for numpy-1.0.4, skipping
PyPI: No release information found for numpy-1.0b1, skipping
PyPI: No release information found for numpy-1.0b4, skipping
PyPI: No release information found for numpy-1.0b5, skipping
PyPI: No release information found for numpy-1.0rc1, skipping
PyPI: No release information found for numpy-1.0rc2, skipping
PyPI: No release information found for numpy-1.0rc3, skipping
PyPI: No release information found for numpy-1.1.1, skipping
PyPI: No release information found for numpy-1.2.0, skipping
PyPI: No release information found for numpy-1.2.1, skipping
PyPI: No release information found for numpy-1.4.0, skipping
PyPI: 24 packages found for numpy >=1.19
PyPI: 31 packages found for types-protobuf >=3.17.3
PyPI: 18 packages found for typing-extensions *
   1: fact: dm-env (1.5) depends on numpy (*)
   1: fact: dm-env (1.5) depends on dm-tree (*)
   1: fact: dm-env (1.5) depends on absl-py (*)
   1: selecting dm-env (1.5)
   1: derived: absl-py
   1: derived: dm-tree
PyPI: No release information found for absl-py-0.0, skipping
PyPI: 38 packages found for absl-py *
PyPI: 7 packages found for dm-tree *
   1: selecting dm-tree (0.1.7)
   1: fact: gym (0.25.0) depends on numpy (>=1.18.0)
   1: fact: gym (0.25.0) depends on cloudpickle (>=1.2.0)
   1: fact: gym (0.25.0) depends on gym_notices (>=0.0.4)
   1: fact: gym (0.25.0) depends on importlib_metadata (>=4.8.0)
   1: selecting gym (0.25.0)
   1: derived: importlib_metadata (>=4.8.0)
   1: derived: gym_notices (>=0.0.4)
   1: derived: cloudpickle (>=1.2.0)
PyPI: 13 packages found for importlib-metadata >=4.8.0
PyPI: 4 packages found for gym-notices >=0.0.4
PyPI: No release information found for cloudpickle-0.2.0, skipping
PyPI: 10 packages found for cloudpickle >=1.2.0
   1: selecting gym-notices (0.0.7)
   1: selecting cloudpickle (2.1.0)
   1: selecting typing-extensions (4.3.0)
   1: selecting numpy (1.23.1)
   1: selecting types-protobuf (3.19.22)
   1: selecting absl-py (1.2.0)
   1: fact: importlib-metadata (4.12.0) depends on zipp (>=0.5)
   1: selecting importlib-metadata (4.12.0)
   1: derived: zipp (>=0.5)
PyPI: 28 packages found for zipp >=0.5
   1: selecting zipp (3.8.1)
   1: Version solving took 0.067 seconds.
   1: Tried 1 solutions.

Writing lock file

Finding the necessary packages for the current system

Package operations: 1 install, 0 updates, 0 removals, 11 skipped

  • Installing zipp (3.8.1): Pending...
  • Installing zipp (3.8.1): Skipped for the following reason: Already installed
  • Installing absl-py (1.2.0): Pending...
  • Installing absl-py (1.2.0): Skipped for the following reason: Already installed
  • Installing cloudpickle (2.1.0): Pending...
  • Installing cloudpickle (2.1.0): Skipped for the following reason: Already installed
  • Installing dm-tree (0.1.7): Pending...
  • Installing dm-tree (0.1.7): Skipped for the following reason: Already installed
  • Installing gym-notices (0.0.7): Pending...
  • Installing gym-notices (0.0.7): Skipped for the following reason: Already installed
  • Installing importlib-metadata (4.12.0): Pending...
  • Installing importlib-metadata (4.12.0): Skipped for the following reason: Already installed
  • Installing numpy (1.23.1): Pending...
  • Installing numpy (1.23.1): Skipped for the following reason: Already installed
  • Installing dm-env (1.5): Pending...
  • Installing dm-env (1.5): Skipped for the following reason: Already installed
  • Installing gym (0.25.0): Pending...
  • Installing gym (0.25.0): Skipped for the following reason: Already installed
  • Installing types-protobuf (3.19.22): Pending...
  • Installing types-protobuf (3.19.22): Skipped for the following reason: Already installed
  • Installing typing-extensions (4.3.0): Pending...
  • Installing typing-extensions (4.3.0): Skipped for the following reason: Already installed
  • Installing envpool (0.6.3): Pending...
  • Installing envpool (0.6.3): Failed

  RuntimeError

  Unable to find installation candidates for envpool (0.6.3)

  at ~/.local/pipx/venvs/poetry/lib/python3.9/site-packages/poetry/installation/chooser.py:72 in choose_for
       68│ 
       69│             links.append(link)
       70│ 
       71│         if not links:
    →  72│             raise RuntimeError(
       73│                 "Unable to find installation candidates for {}".format(package)
       74│             )
       75│ 
       76│         # Get the best link


Failed to add packages, reverting the pyproject.toml file to its original content.
```

**Comment by neersighted** [comment] 2022-07-25 14:14
Closing as a duplicate of #3543

**Closed by neersighted** 2022-07-25 14:14 UTC
Labels: Bug, Triage
