### ISSUE TITLE
PermissinError while trying to add new package after install with POETRY_VIRTUALENVS_CREATE=false

### ISSUE THREAD

**Issue by kamilglod** [python-poetry/poetry#2049] opened 2020-02-17 14:45 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Docker, image python:3.8.1
- **Poetry version**: 1.0.3

## Issue
After first installation of project packages, with `POETRY_VIRTUALENVS_CREATE` flag set to false, when I try to install some extra package I get:
```bash
[EnvCommandError]
Command ['/usr/local/bin/python', '-m', 'pip', 'uninstall', 'pyparsing', '-y'] errored with the following return code 2, and output: 
Found existing installation: pyparsing 2.4.6
Uninstalling pyparsing-2.4.6:
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/shutil.py", line 781, in move
    os.rename(src, real_dst)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.8/site-packages/__pycache__/pyparsing.cpython-38.pyc' -> '/tmp/pip-uninstall-xhob42h4/pyparsing.cpython-38.pyc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/commands/uninstall.py", line 78, in run
    uninstall_pathset = req.uninstall(
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 687, in uninstall
    uninstalled_pathset.remove(auto_confirm, verbose)
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/req/req_uninstall.py", line 394, in remove
    moved.stash(path)
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/req/req_uninstall.py", line 283, in stash
    renames(path, new_path)
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/utils/misc.py", line 334, in renames
    shutil.move(old, new)
  File "/usr/local/lib/python3.8/shutil.py", line 796, in move
    os.unlink(src)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.8/site-packages/__pycache__/pyparsing.cpython-38.pyc'
```
This is happening because I installed poetry by root user and then try to install packages as unprivileged user. However when I try to install poetry as unprivileged user and then install project dependencies: everything works fine - I can install extra packages without facing this error. So the problem is that poetry installs dependencies in different location based on poetry binary location.
Question is whether it is intended or it is a bug. If it's not a bug maybe it should be placed somewhere in the docs to make it clear as I was trying to track this error for a couple of hours.

**Comment by winter-code** [comment] 2020-07-07 23:19
I have used symlink to link python3.8.3 to python. 
I am getting error with poetry install. I am not sure if using sudo to give permission to install in /usr/local/bin should be fine.

``
poetry install
Skipping virtualenv creation, as specified in config file.
Installing dependencies from lock file


Package operations: 101 installs, 0 updates, 0 removals

  - Installing lazy-object-proxy (1.4.3)

[EnvCommandError]
Command ['/usr/bin/python', '-m', 'pip', 'install', '--no-deps', 'lazy-object-proxy==1.4.3'] errored with the following return code 1, and output: 
Collecting lazy-object-proxy==1.4.3
  Using cached https://files.pythonhosted.org/packages/34/8c/74acd0ad5a0518be9e0f3b4d022e84da0c1d9b78972afce73259ac85d78b/lazy_object_proxy-1.4.3-cp38-cp38-manylinux1_x86_64.whl
Installing collected packages: lazy-object-proxy
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/lib/python3.8/site-packages/lazy_object_proxy-1.4.3.dist-info'
Consider using the `--user` option or check the permissions.
``

**Comment by agoose77** [comment] 2020-12-01 15:31
I reproduced this today in a Docker container. It appears the cause is https://github.com/python-poetry/poetry/blob/bf30ca696aa47bcc42937910d620c95c95c0741e/poetry/installation/pip_installer.py#L240-L248

**Comment by lpsinger** [comment] 2021-09-28 16:44
I am encountering this too with Poetry 1.1.10. I would request that when Poetry is not managing its own virtual environment, either because `POETRY_VIRTUALENVS_CREATE=false` is set, or because the user has run `poetry env use system`, that Poetry should behave more like pip when upgrading packages. If the user site-packages directory is writable but the system site-packages directory is not, and the system site-packages directory contains an older version of the package then requested, then Poetry should install the new version in the user site-packages directory but should not try to remove the old version.

**Comment by finswimmer** [comment] 2023-02-01 11:53
Hello,

you haven't come back to this issue for a long while. So I assume this is solved in the meantime and I can close this ticket.

Feel free to leave a comment if you disagree.

fin swimmer

**Comment by lpsinger** [comment] 2023-02-01 13:59
No, it's still broken. I observed this just the other day.

**Comment by neersighted** [comment] 2023-02-01 14:33
This isn't a bug, but a duplicate feature request of #1214.

**Comment by pmareke** [comment] 2023-04-20 11:51
Hi everyone, I have the same error.

Use `poetry config virtualenvs.create false` instead works for me.

**Comment by dimbleby** [comment] 2023-05-31 07:52
should be closed, per https://github.com/python-poetry/poetry/issues/2049#issuecomment-1412160071

**Closed** 2023-05-31 07:56 UTC
Labels: kind/bug, status/triage
