### ISSUE TITLE
SolverProblemError when including version constraints for ipython and ipdb in pyproject.toml

### ISSUE THREAD

**Issue by mjfinney** [python-poetry/poetry#4802] opened 2021-11-19 19:10 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**:  7.9.2009 CentOS
- **Poetry version**: 1.1.11
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: [Minimal pyproject.toml to reproduce issue](https://gist.github.com/mjfinney/fa96a737612c39ea3fe72ce060ab7385)

## Issue
Poetry fails with a SolverProblemError when both ipython and ipdb are constrained in pyproject.toml but removing ipython and running it again installs the same versions that are defined in pyproject.toml.

I start with these lines in my pyproject.toml:
```
python = "^3.6"
ipython = "7.16.1"
ipdb = "^0.13.9"
```

I run the following commands in my terminal to setup my environment and it works fine.
```
pyenv local 3.6.8
poetry install --no-root
```

I run the following to update packages and I get a SolverProblemError:
```
poetry update
  SolverProblemError

  Because no versions of ipdb match >0.13.9,<0.14.0
   and ipdb (0.13.9) depends on ipython (>=7.17.0), ipdb (>=0.13.9,<0.14.0) requires ipython (>=7.17.0).
  So, because test depends on both ipython (7.16.1) and ipdb (^0.13.9), version solving failed.
```

If I edit my pyproject.toml to remove the constraint for ipython and only include:
```
python = "^3.6"
ipdb = "^0.13.9"
```
Now `poetry install --no-root` and `poetry update` work as expected. When I run `poetry show` I get the following versions for ipdb and ipython:
```
ipdb             0.13.9 IPython-enabled pdb
ipython          7.16.1 IPython: Productive Interactive Computing`
```

If I edit my pyproject.toml to remove the ^ for the python version:
```
python = "3.6"
ipython = "7.16.1"
ipdb = "^0.13.9"
```
poetry update now works but creating an environment does now work.
```
poetry env remove 3.6.8
poetry install --no-root
    NoCompatiblePythonVersionFound
    Poetry was unable to find a compatible version. If you have one, you can explicitly use it via the "env use" command.
```
This makes sense to me because 3.6.8 is greater than 3.6. But it demonstrates that `poetry update` works in this instance.

I believe the problem I'm experiencing might be caused by [this line in the setup.py for ipd](https://github.com/gotcha/ipdb/blob/fc83b4f5fee210a6fd33f720b500f7011494a60c/setup.py#L67).

I do not know enough about defining python_version to know if poetry is correct, but it is an inconsistency with what `poetry update` tells me when I have ipython and ipdb constrained and what it actually installs when only ipdb is constrained.

**Comment by dimbleby** [comment] 2022-06-04 12:27
Cannot reproduce:
```
python = "^3.6"
ipython = "7.16.1"
ipdb = "^0.13.9"
```
simply doesn't solve (because indeed ipdb requires a later version of ipython)

Removing the ipython constraint I get ipython 7.34.0, not 7.16.1

**Comment by ralbertazzi** [comment] 2023-05-28 17:29
Same here. Closing as not reproducible

**Closed by ralbertazzi** 2023-05-28 17:29 UTC
Labels: kind/bug, status/triage
