### ISSUE TITLE
KeyError 'None' while running poetry lock

### ISSUE THREAD

**Issue by themarcelor** [python-poetry/poetry#3555] opened 2021-01-08 20:57 UTC
I'm facing the following error while running `poetry lock`:
```
Updating dependencies
Resolving dependencies... (9.9s)
  KeyError
  'None'
  at ~/.poetry/lib/poetry/mixology/version_solver.py:112 in _propagate
      108│             # Iterate in reverse because conflict resolution tends to produce more
      109│             # general incompatibilities as time goes on. If we look at those first,
      110│             # we can derive stronger assignments sooner and more eagerly find
      111│             # conflicts.
    → 112│             for incompatibility in reversed(self._incompatibilities[package]):
      113│                 result = self._propagate_incompatibility(incompatibility)
      114│
      115│                 if result is _conflict:
      116│                     # If the incompatibility is satisfied by the solution, we use
```

Python & Poetry versions:
```
% python --version
Python 3.8.0
% poetry --version
Poetry version 1.1.4
```

Thoughts?

**Comment by glacion** [comment] 2021-01-08 22:27
Do you have a reproducible repo or pyproject.toml?

**Comment by themarcelor** [comment] 2021-01-08 23:06
Sure: https://github.com/uc-cdis/fence/blob/master/pyproject.toml

Thanks for helping out.

**Comment by glacion** [comment] 2021-01-09 00:30
So; 

`fact: email-validator (1.1.2) depends on idna (>=2.0.0)`

this restricts idna versions to greater than or equal to 2.0.0, so poetry greedily(?) selects 

`idna (3.1)`

_then_ it breaks down trying to install requests;

```   1: fact: requests (2.25.1) depends on idna (>=2.5,<3)
   1: fact: requests (2.25.0) depends on idna (>=2.5,<3)
   1: fact: requests (2.24.0) depends on idna (>=2.5,<3)
   1: fact: requests (2.23.0) depends on idna (>=2.5,<3)
   1: fact: requests (2.22.0) depends on idna (>=2.5,<2.9)
   1: fact: requests (2.21.0) depends on idna (>=2.5,<2.9)
   1: fact: requests (2.20.1) depends on idna (>=2.5,<2.8)
   1: fact: requests (2.20.0) depends on idna (>=2.5,<2.8)
   1: fact: requests (2.19.1) depends on idna (>=2.5,<2.8)
   1: fact: requests (2.19.0) depends on idna (>=2.5,<2.8)
   1: fact: requests (2.18.4) depends on idna (>=2.5,<2.7)
   1: fact: requests (2.18.3) depends on idna (>=2.5,<2.6)
   1: fact: requests (2.18.2) depends on idna (>=2.5,<2.6)
   1: fact: requests (2.18.1) depends on idna (>=2.5,<2.6)
   1: fact: requests (2.18.0) depends on idna (>=2.5,<2.6)
```
It couldn't find a suitable version for requests because it has already installed idna 3.1, and no requests version can match that.

Pip, however, selects idna 2.10 after the following commands;

```
poetry export -f requirements.txt --output requirements.txt
pip install -r requirements.txt
```

So.. it's time to page a maintainer 😅

**Comment by dimbleby** [comment] 2022-04-18 12:33
The given pyproject.toml works fine with poetry 1.1.3 (and also master).

Hard to be sure whether that's because poetry has been fixed or whether it's because there are now a different set of packages available and so it just doesn't go down some bad path - but either way, I don't think there's much to be done with it now.

**Comment by mkniewallner** [comment] 2022-05-29 22:15
Tested on more recent versions too, and it does seem to work now.
Closing this, but feel free to re-open if you still have the issue.

**Closed by mkniewallner** 2022-05-29 22:15 UTC
