### ISSUE TITLE
ValueError on installing modin

### ISSUE THREAD

**Issue by antaradas94** [python-poetry/poetry#4878] opened 2021-12-09 19:09 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **10 Windows** 
- **1.1.11** 

## Issue

i have trying to install Modin using poetry. However i come across
` ValueError 
....path\9a\43\f3de85734550733b2588a3b64f5df53f82fbe7230a71b0c3b904746750\azureml_telemetry-1.
36.0-py3-none-any.whl  does not exist`. 
`poetry add modin
Using version ^0.12.0 for modin
Updating dependencies
Resolving dependencies...
Package operations: 3 installs, 19 updates, 0 removals
  • Updating azureml-telemetry (1.34.0 -> 1.36.0)

  ValueError

  File \C:\Users\username\AppData\Local\pypoetry\Cache\artifacts\2c\9a\43\f3de85734550733b2588a3b64f5df53f82fbe7230a71b0c3b904746750\azureml_telemetry-1.
36.0-py3-none-any.whl does not exist

  at ~\.poetry\lib\poetry\_vendor\py3.8\poetry\core\packages\file_dependency.py:40 in __init__
       36│             except FileNotFoundError:
       37│                 raise ValueError("Directory {} does not exist".format(self._path))
       38│
       39│         if not self._full_path.exists():
    →  40│             raise ValueError("File {} does not exist".format(self._path))
       41│ 
       42│         if self._full_path.is_dir():
       43│             raise ValueError("{} is a directory, expected a file".format(self._path))
       44│

Failed to add packages, reverting the pyproject.toml file to its original content.
 `
I am a bit confused as to what could be wrong here because this file actually exists in my file system.
i tried to delete the poetry.lock file and run a poetry lock --no-update after adding modin in the pypoetry.toml file, which shows that now modin is installed when i run poetry show. But however , modin isnt installed and isnt recognised with the IDE (using PyCharm here.)

Thanks for any lead.

**Comment by Kaltsoon** [comment] 2021-12-13 07:41
I've bumped into a similar error message with a pre 1.1.12 version. However, I haven't faced similar issues with the latest version. Have you tried this with the latest Poetry version?

**Comment by antaradas94** [comment] 2021-12-13 20:15
thanks for the response @Kaltsoon 
i am using poetry 1.1.11.
i tried to update with poetry self update and ran into another issue 
`ModuleNotFoundError: No module named 'poetry.console'
`

**Comment by sudomaze** [comment] 2021-12-16 05:07
I have the same issue with `1.1.8` and after updating to `1.1.12` the issue is gone. Thanks, @Kaltsoon! 

Can we know what might be the issue for this issue?

**Comment by mkniewallner** [comment] 2022-06-11 00:05
Hi, I don't know what fixed the issue, but since it's fixed, let's close this issue.

**Closed by mkniewallner** 2022-06-11 00:05 UTC
Labels: Bug, Triage
