### ISSUE TITLE
Fails to choose compatible version for version-less dependency

### ISSUE THREAD

**Issue by colllin** [python-poetry/poetry#1589] opened 2019-11-16 21:03 UTC
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] **N/A** If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: ubuntu 16.04
- **Poetry version**: 0.12.17
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/colllin/a612f1ddbafbde91b1da2a9a213bf430

## Issue
👋 `pipenv` user trying `poetry` for the first time.  Please forgive me if I'm misunderstanding the usage of this tool. I expected to be able to (after `poetry init`):
```
poetry add torch==1.2.*
poetry add torchvision
```
... and that `poetry` would automatically resolve the correct version of `torchvision` which is compatible with `torch==1.2.*`.  Instead, I get the following:
```
$ poetry add torchvision
Using version ^0.4.2 for torchvision

Updating dependencies
Resolving dependencies... (0.0s)
                                                                                                           
[SolverProblemError]                                                                        
Because no versions of torchvision match >0.4.2,<0.5.0                                                   
 and torchvision (0.4.2) depends on torch (1.3.1), torchvision (>=0.4.2,<0.5.0) requires torch (1.3.1).  
So, because lulc-dvc depends on both torch (=1.2) and torchvision (^0.4.2), version solving failed.
```

Why is it selecting an incompatible version (`^0.4.2`) without accounting for existing dependencies?

**Comment by smsegal** [comment] 2020-01-23 17:04
Are there any updates or workarounds for this? I'm getting the exact same issue with torchvision v0.5.0

**Comment by mkniewallner** [comment] 2022-09-18 02:02
Duplicate of #707.

**Closed by mkniewallner** 2022-09-18 02:02 UTC
Labels: kind/bug, area/solver, status/duplicate
