### ISSUE TITLE
The --with and --without options don't seem to have any effects during installation of packages

### ISSUE THREAD

**Issue by happyhuman** [python-poetry/poetry#5299] opened 2022-03-10 21:05 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Mac OS Monterey - Using Python 3.8.12 and Pyenv
- **Poetry version**:1.2.0a2
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**:  https://gist.github.com/happyhuman/234fe54b1fda17645e0ccaaf9be4d825

## Issue

I have two groups in my `pyproject.toml` file, namely, `docs` and `pipeline`. I tried running `poetry install --with=pipeline` or `poetry install --without=docs`. However, in either case, I noticed that all the packages in both groups get installed. I have tried using a pyenv virtual environment, and also creating a virtual env by doing a `poetry shell` first. In all scenarios, both `pandas` and `flask` got installed. These two packages are independent of one another. So, it seems like a bug.

**Comment by finswimmer** [comment] 2022-03-11 09:54
Hello @happyhuman,

the `--with` option is only meant for installing dependency groups marked as optional.

I cannot reproduce your problem with the `--without` option:

```
poetry install --without docs
Creating virtualenv mypackage in /home/finswimmer/tmp/poetry/.venv
Installing dependencies from lock file

Package operations: 9 installs, 0 updates, 0 removals

  • Installing typing-extensions (4.1.1)
  • Installing zipp (3.7.0)
  • Installing importlib-metadata (4.11.2)
  • Installing markupsafe (2.1.0)
  • Installing click (8.0.4)
  • Installing itsdangerous (2.1.1)
  • Installing jinja2 (3.0.3)
  • Installing werkzeug (2.0.3)
  • Installing flask (2.0.3)
```

pandas gets not installed.

fin swimmer

**Comment by finswimmer** [comment] 2022-03-25 20:10
Hello @happyhuman,

if you still have a problem, please try the latest changes in the master branch. The group handling have been improved.

fin swimmer

**Comment by finswimmer** [comment] 2022-04-29 20:58
Hey,

I will close this issue because we haven't received any feedback for a long time. Feel free to leave a comment if you disagree.

fin swimmer

**Closed by finswimmer** 2022-04-29 20:58 UTC
Labels: Bug, Triage, Awaiting Reponse
