### ISSUE TITLE
Cannot install click.

### ISSUE THREAD

**Issue by kierun** [python-poetry/poetry#1475] opened 2019-10-17 12:46 UTC
- [X] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: CentOS 7, running under Python 3.7
- **Poetry version**: Poetry 0.12.17
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**:  Not needed.

## Issue

[There is an issue in click about this.](https://github.com/pallets/click/issues/1366)

When I run `poetry add click`,  I get:
```
usignals-py3.7(poetry L|+1…2); poetry add click      
Using version ^7.0 for click

Updating dependencies

Resolving dependencies... (0.8s)                                               
[ValueError]                    
Could not parse version constraint: <empty>  
                                               
add [-D|--dev] [--git GIT] [--path PATH] [-E|--extras EXTRAS] [--optional] [--python PYTHON] [--platform PLATFORM] [--allow-prereleases] [--dry-run] [--] <name> (<name>)...
```

and running it with full debugging, I get the following trace:

```
Exception trace:
 /home/usr/.poetry/lib/poetry/_vendor/py3.7/cleo/application.py in run() at line 94
   status_code = self.do_run(input_, output_)
 /home/usr/.poetry/lib/poetry/console/application.py in do_run() at line 88
   return super(Application, self).do_run(i, o)
 /home/usr/.poetry/lib/poetry/_vendor/py3.7/cleo/application.py in do_run() at line 197
   status_code = command.run(input_, output_)
 /home/usr/.poetry/lib/poetry/console/commands/command.py in run() at line 77
   return super(BaseCommand, self).run(i, o)
 /home/usr/.poetry/lib/poetry/_vendor/py3.7/cleo/commands/base_command.py in run() at line 146
   status_code = self.execute(input_, output_)
 /home/usr/.poetry/lib/poetry/_vendor/py3.7/cleo/commands/command.py in execute() at line 107
   return self.handle()
 /home/usr/.poetry/lib/poetry/console/commands/add.py in handle() at line 139
   status = installer.run()
 /home/usr/.poetry/lib/poetry/installation/installer.py in run() at line 73
   self._do_install(local_repo)
 /home/usr/.poetry/lib/poetry/installation/installer.py in _do_install() at line 165
   ops = solver.solve(use_latest=self._whitelist)
 /home/usr/.poetry/lib/poetry/puzzle/solver.py in solve() at line 38
   packages, depths = self._solve(use_latest=use_latest)
 /home/usr/.poetry/lib/poetry/puzzle/solver.py in _solve() at line 171
   self._package, self._provider, locked=locked, use_latest=use_latest
 /home/usr/.poetry/lib/poetry/mixology/__init__.py in resolve_version() at line 7
   return solver.solve()
 /home/usr/.poetry/lib/poetry/mixology/version_solver.py in solve() at line 79
   next = self._choose_package_version()
 /home/usr/.poetry/lib/poetry/mixology/version_solver.py in _choose_package_version() at line 377
   version = self._provider.complete_package(version)
 /home/usr/.poetry/lib/poetry/puzzle/provider.py in complete_package() at line 592
   package.dependency.python_constraint
 /home/usr/.poetry/lib/poetry/packages/dependency.py in transitive_python_versions() at line 109
   self._transitive_python_constraint = parse_constraint(value)
 /home/usr/.poetry/lib/poetry/semver/__init__.py in parse_constraint() at line 31
   constraint_objects.append(parse_single_constraint(and_constraints[0]))
 /home/usr/.poetry/lib/poetry/semver/__init__.py in parse_single_constraint() at line 164
   raise ValueError("Could not parse version constraint: {}".format(constraint))
```

**Comment by kierun** [comment] 2019-10-17 13:14
It might not be a click issue at all after all. 

Here is my `pyproject.toml` file:

```
[tool.poetry]
name = "usignals"
version = "0.4.0"
description = ""
authors = [""]

[tool.poetry.dependencies]
pymysql = "^0.9.3"
click = "^7.0"
click-help-colors = "^0.6.0"

[tool.poetry.dev-dependencies]
bumpversion = "^0.5.3"
coverage = [
    {version = "^3", python = ">=3"}
]
pytest = [
    {version = "^4", python = ">=3"}
]
docformatter = "^1.3"
flake8 = "^3.7"
mock = "^3.0"
sure = "^1.4"
```

I was able to install click fine by deleting everything and starting again. However, I am getting the same error when I run:

```
usignals-py3.7(poetry L|+1…2); poetry add --dev tox
zsh: correct 'tox' to '.tox' [nyae]? n
Using version ^3.14 for tox

Updating dependencies
Resolving dependencies... (0.2s)
                                               
[ValueError]                    
Could not parse version constraint: <empty>  
```
*What am I doing wrong?*

**Comment by kierun** [comment] 2019-10-18 08:32
After much random hacking, I think the issue has something to do with the `python = "*"` flag I had. I changed that to `python = ">=3.6"` and suddenly all the problems vanished. If that is the case, there need to be a better error message…

**Comment by finswimmer** [comment] 2020-02-02 17:12
Hello,

I cannot reproduce this with poetry 1.0.3. So I will close the issue. If you disagree feel free to leave a comment.

fin swimmer

**Closed by finswimmer** 2020-02-02 17:12 UTC
Labels: Bug
