### ISSUE TITLE
top level module package with submodules - installation fails in external system with poetry built distributable

### ISSUE THREAD

**Issue by aprath1** [python-poetry/poetry#7284] opened 2023-01-03 13:24 UTC
- **Poetry version**:  1.3.1  
- **Python version**: 3.10.8 
- **OS version and name**: Windows 11 
- **pyproject.toml**: [top_module pyproject.toml](https://gist.github.com/aprath1/dd9fb8f54891c72fdf2041c935ec8050) 

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
NOTE: some issues are closely related and discusses this current case, which leads to the current issue.
_Related issues:_
#4709
#5273 
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.

## Issue

The distributable (wheel) installation fails for the following package design - top_module packages with submodule packages such as the sample base tree file structure below:
```
│   pyproject.toml
│   README.md
│
└───top_module
    │   __init__.py
    │
    ├───submodule_a
    │   │   pyproject.toml
    │   │   README.md
    │   │   setup.py
    │   │
    │   ├───submodule_a
    │           __init__.py          
    │
    └───submodule_b
        │   pyproject.toml
        │   README.md
        │   setup.py
        │
        ├───submodule_b
                __init__.py
        
```
when distributable is built with `poetry build` it has the local system absolute path in the metadata, for example in the above sample tree case the wheel metadata include the following:
```
...
Requires-Dist: submodule_a @ file:///<absolute_path_local_to_system>/top_module/top_module/submodule_a
Requires-Dist: submodule_b @ file:///<absolute_path_local_to_system>/top_module/top_module/submodule_b
...
```
which means this will impact the distributable installation in any other external systems, which is failing the purpose of distributable - just like it is mentioned in this https://github.com/python-poetry/poetry/issues/5273#issuecomment-1272571033. (Even though cloning the source repo and installing works). dist installation will trigger following error as the installation is looking for absolute paths local to the system which generated the distributable:
`ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory:`

currently the submodules are provided as relative path dependencies in pyproject.toml as below; is there any alternate approach available for this scenario to facilitate dist installation in external systems?
```
[tool.poetry.dependencies]
python = "^3.10, < 3.11"
submodule_a = { path = "top_module/submodule_a", develop=true }
submodule_b = { path = "top_module/submodule_b", develop=true
```

_Impact:_ 
for projects with sub packages such as those with git submodules, distributable installation will not be possible in any other external systems.

**Comment by neersighted** [comment] 2023-01-03 14:43
What you want might be covered by #4583 (vendoring in files, essentially). Path dependencies will not do what you want, @dimbleby is right to point out that Poetry is doing exactly what you tell it to (building a package with a dependency on an absolute path). You might also be interested in #1168 if the modules can have a dependency by name outside of development.

Either way, this is a duplicate of existing issues/misapplication of the tool.

**Closed by neersighted** 2023-01-03 14:43 UTC
Labels: kind/bug, status/triage

**Comment by aprath1** [comment] 2023-01-03 14:44
Thanks for your reply. 
agreed with the relative paths not being valid, and the second point as being the reason for this issue. 
I was looking today for performing the mentioned distributable wheel generation with other tool but haven't actually found any yet. 

yes, using separate wheels is what was considered as an alternative.

So this actually leads to a question of why are package designs with git submodules not distributable friendly!  
Considering the above I would close this issue for now.
