### ISSUE TITLE
poetry add azure-iot-hub infinite loop

### ISSUE THREAD

**Issue by aressler38** [python-poetry/poetry#4154] opened 2021-06-08 00:34 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ x If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**:  Debian GNU/Linux 10 (buster)
- **Poetry version**: 1.1.6
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/aressler38/c6d04be4616c06b8354c0a964b435073

## Issue
I cannot add `azure-iot-hub` to a project. I can't add it to a blank project or one with existing dependencies. I see it looping infinitely when I try to add it. Even if I add `six`, `azure-core`, and `requests` manually, it still loops infinitely.

The part that loops forever looks like this.
```
   1: selecting azure-core (1.15.0)
   1: fact: azure-core (1.15.0) depends on requests (>=2.18.4)
   1: fact: azure-core (1.15.0) depends on six (>=1.11.0)
   1: selecting azure-core (1.15.0)
   1: fact: azure-core (1.15.0) depends on requests (>=2.18.4)
   1: fact: azure-core (1.15.0) depends on six (>=1.11.0)
   1: selecting azure-core (1.15.0)
   1: fact: azure-core (1.15.0) depends on requests (>=2.18.4)
   1: fact: azure-core (1.15.0) depends on six (>=1.11.0)
   1: selecting azure-core (1.15.0)
   1: fact: azure-core (1.15.0) depends on requests (>=2.18.4)
   1: fact: azure-core (1.15.0) depends on six (>=1.11.0)
```

It happens when I run `poetry add -D azure-iot-hub` or `poetry add azure-iot-hub`.

**Comment by aressler38** [comment] 2021-06-08 00:35
[save.log](https://github.com/python-poetry/poetry/files/6612672/save.log)

**Comment by davidmweber** [comment] 2021-08-16 11:59
This is a duplicate of #4054

**Comment by mkniewallner** [comment] 2022-07-09 16:02
Similar to #4054, so closing as duplicate.

**Closed by mkniewallner** 2022-07-09 16:02 UTC
Labels: Bug, Triage
