### ISSUE TITLE
Poetry detects Python 3.10 as Python 3.1

### ISSUE THREAD

**Issue by 9999years** [python-poetry/poetry#4354] opened 2021-08-04 19:31 UTC
```python
from pathlib import Path

import poetry.utils.env

print(
    poetry.utils.env.VirtualEnv(path=Path("./.tox/py310")).marker_env["python_version"]
)
# Prints "3.1"
```

- **OS version and name**: Fedora 34
- **Poetry version**: 1.1.7

**Comment by 9999years** [comment] 2021-08-04 19:42
Looks like this originated in https://github.com/python-poetry/poetry/commit/7a12c390d2e9e04566d36eb774db8aa64822a3be#diff-48120c42d1d0a5860b317966e7d1e0a65e48e4fee6f6a0795fad5848dcf43ef0

**Comment by apollo13** [comment] 2021-08-16 11:41
Dupe of the older https://github.com/python-poetry/poetry/pull/4340 which just got merged

**Closed** 2021-08-16 13:12 UTC
Labels: Bug, Triage
