### ISSUE TITLE
Issue installing local packages

### ISSUE THREAD

**Issue by Qu4tro** [python-poetry/poetry#1809] opened 2019-12-31 14:42 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: ArchLinux
- **Poetry version**: poetry 1.0.0b9-1
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: None

## Issue

Hello there. I'm trying to create a set of packages that have some dependencies within themselves. Since I'm still kicking things off, everything is local.
My problem arises when installing a local package, that itself depends on a local package.

I've created a small script to reproduce the issue:
```
#!/bin/bash

set -e
TMPDIR=$(mktemp -d) && echo "$TMPDIR" && cd "$TMPDIR"

poetry new aa
poetry new ab
poetry new ac

cd ab && poetry add ../aa && cd ..

cd ac && poetry add -vvv ../ab # boom
```
and the resulting output in this [gist](https://gist.github.com/Qu4tro/7ea92b1743d6e59d1928be03ba174274)

Is there anything I'm doing wrong?

And thank you in advance.

**Comment by finswimmer** [comment] 2019-12-31 14:46
Hello @Qu4tro ,

this is a duplicate of https://github.com/python-poetry/poetry/issues/1689. So I'm closing this here.

fin swimmer

**Closed by finswimmer** 2019-12-31 14:46 UTC
Labels: Bug

**Comment by Qu4tro** [comment] 2019-12-31 15:09
Thanks.
