### ISSUE TITLE
 poetry add djoser Using version ^2.0.3 for djoser  Updating dependencies Resolving dependencies...  [PackageNotFound] Package djoser (2.0.3) not found.

### ISSUE THREAD

**Issue by hian18** [python-poetry/poetry#2224] opened 2020-03-26 11:43 UTC
- [ ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [ ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: 
- **Poetry version**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**:

**Comment by hian18** [comment] 2020-03-26 11:43
poetry add djoser
Using version ^2.0.3 for djoser

Updating dependencies
Resolving dependencies...

[PackageNotFound]
Package djoser (2.0.3) not found.

**Comment by simion** [comment] 2020-03-26 12:06
Maybe duplicate of https://github.com/python-poetry/poetry/issues/2223

**Comment by finswimmer** [comment] 2020-03-26 16:45
Yes, it's a duplicate of #2223.

**Closed by finswimmer** 2020-03-26 16:45 UTC
Labels: Bug
