### ISSUE TITLE
Cannot update to the latest version of a library

### ISSUE THREAD

**Issue by LeFakeMimit** [python-poetry/poetry#6066] opened 2022-07-25 13:21 UTC
- [ ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 20.04 WSL1
- **Poetry version**: Poetry (version 1.2.0b3)
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

```toml
[tool.poetry]
name = "template-python"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "template_python", from = "src"}]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
# To be update to latest version when available
plantuml-markdown = "~3.6.2"

[build-system]
requires = ["poetry-core>=1.1.0a6"]
build-backend = "poetry.core.masonry.api"

```

## Issue

I am trying to install the version `3.6.2` of `plantuml-markdown` which is recent. But I cannot get it using poetry.
I got an exception telling me that the version does not exist. 

I tried to install it with `pip install plantuml-markdown==3.6.2` and I can install it this way.
Seems related to poetry since I can get the version `3.6.1` but not the version `3.6.2`.

I tried to remove the cache with the following commands but the problem was still there:

```console
rm -rf ~/.cache/pypoetry/artifacts/
rm -rf ~/.cache/pypoetry/cache/
```

Here is the error:

```console
Project environment contains an empty path in sys_path, ignoring.
Updating dependencies
Resolving dependencies...
   1: fact: template-python is 0.1.0
   1: derived: template-python
   1: fact: template-python depends on plantuml-markdown (~3.6.2)
   1: selecting template-python (0.1.0)
   1: derived: plantuml-markdown (>=3.6.2,<3.7.0)
[keyring.backend] Loading KWallet
[keyring.backend] Loading SecretService
[keyring.backend] Loading Windows
[keyring.backend] Loading chainer
[keyring.backend] Loading libsecret
[keyring.backend] Loading macOS
No suitable keyring backend found
No suitable keyring backends were found
Keyring is not available, credentials will be stored and retrieved from configuration files as plaintext.
Creating new session for pypi.org
Source (PyPI): 0 packages found for plantuml-markdown >=3.6.2,<3.7.0
Falling back to installed packages to discover metadata for plantuml-markdown
Found 0 compatible packages for plantuml-markdown
   1: fact: no versions of plantuml-markdown match >=3.6.2,<3.7.0
   1: conflict: no versions of plantuml-markdown match >=3.6.2,<3.7.0
   1: ! plantuml-markdown (>=3.6.2,<3.7.0) is satisfied by plantuml-markdown (>=3.6.2,<3.7.0)
   1: ! which is caused by "template-python depends on plantuml-markdown (~3.6.2)"
   1: ! thus: version solving failed
   1: Version solving took 0.251 seconds.
   1: Tried 1 solutions.

  Stack trace:

  4  ~/.local/pipx/venvs/poetry/lib/python3.10/site-packages/poetry/puzzle/solver.py:141 in _solve
      139│ 
      140│         try:
    → 141│             result = resolve_version(
      142│                 self._package, self._provider, locked=locked, use_latest=use_latest
      143│             )

  3  ~/.local/pipx/venvs/poetry/lib/python3.10/site-packages/poetry/mixology/__init__.py:24 in resolve_version
       22│     solver = VersionSolver(root, provider, locked=locked, use_latest=use_latest)
       23│ 
    →  24│     return solver.solve()
       25│ 

  2  ~/.local/pipx/venvs/poetry/lib/python3.10/site-packages/poetry/mixology/version_solver.py:124 in solve
      122│             next: str | None = self._root.name
      123│             while next is not None:
    → 124│                 self._propagate(next)
      125│                 next = self._choose_package_version()
      126│ 

  1  ~/.local/pipx/venvs/poetry/lib/python3.10/site-packages/poetry/mixology/version_solver.py:163 in _propagate
      161│                     # where that incompatibility will allow us to derive new assignments
      162│                     # that avoid the conflict.
    → 163│                     root_cause = self._resolve_conflict(incompatibility)
      164│ 
      165│                     # Back jumping erases all the assignments we did at the previous

  SolveFailure

  Because template-python depends on plantuml-markdown (~3.6.2) which doesn't match any versions, version solving failed.

  at ~/.local/pipx/venvs/poetry/lib/python3.10/site-packages/poetry/mixology/version_solver.py:362 in _resolve_conflict
      358│             )
      359│             self._log(f'! which is caused by "{most_recent_satisfier.cause}"')
      360│             self._log(f"! thus: {incompatibility}")
      361│ 
    → 362│         raise SolveFailure(incompatibility)
      363│ 
      364│     def _choose_package_version(self) -> str | None:
      365│         """
      366│         Tries to select a version of a required package.

The following error occurred when trying to handle this error:


  Stack trace:

  11  ~/.local/pipx/venvs/poetry/lib/python3.10/site-packages/cleo/application.py:329 in run
       327│ 
       328│             try:
     → 329│                 exit_code = self._run(io)
       330│             except Exception as e:
       331│                 if not self._catch_exceptions:

  10  ~/.local/pipx/venvs/poetry/lib/python3.10/site-packages/poetry/console/application.py:188 in _run
       186│         self._load_plugins(io)
       187│ 
     → 188│         exit_code: int = super()._run(io)
       189│         return exit_code
       190│ 

   9  ~/.local/pipx/venvs/poetry/lib/python3.10/site-packages/cleo/application.py:423 in _run
       421│             io.input.set_stream(stream)
       422│ 
     → 423│         exit_code = self._run_command(command, io)
       424│         self._running_command = None
       425│ 

   8  ~/.local/pipx/venvs/poetry/lib/python3.10/site-packages/cleo/application.py:465 in _run_command
       463│ 
       464│         if error is not None:
     → 465│             raise error
       466│ 
       467│         return event.exit_code

   7  ~/.local/pipx/venvs/poetry/lib/python3.10/site-packages/cleo/application.py:449 in _run_command
       447│ 
       448│             if event.command_should_run():
     → 449│                 exit_code = command.run(io)
       450│             else:
       451│                 exit_code = ConsoleCommandEvent.RETURN_CODE_DISABLED

   6  ~/.local/pipx/venvs/poetry/lib/python3.10/site-packages/cleo/commands/base_command.py:119 in run
       117│         io.input.validate()
       118│ 
     → 119│         status_code = self.execute(io)
       120│ 
       121│         if status_code is None:

   5  ~/.local/pipx/venvs/poetry/lib/python3.10/site-packages/cleo/commands/command.py:83 in execute
        81│ 
        82│         try:
     →  83│             return self.handle()
        84│         except KeyboardInterrupt:
        85│             return 1

   4  ~/.local/pipx/venvs/poetry/lib/python3.10/site-packages/poetry/console/commands/lock.py:54 in handle
        52│         self._installer.lock(update=not self.option("no-update"))
        53│ 
     →  54│         return self._installer.run()
        55│ 

   3  ~/.local/pipx/venvs/poetry/lib/python3.10/site-packages/poetry/installation/installer.py:111 in run
       109│             self._execute_operations = False
       110│ 
     → 111│         return self._do_install()
       112│ 
       113│     def dry_run(self, dry_run: bool = True) -> Installer:

   2  ~/.local/pipx/venvs/poetry/lib/python3.10/site-packages/poetry/installation/installer.py:244 in _do_install
       242│                 source_root=self._env.path.joinpath("src")
       243│             ):
     → 244│                 ops = solver.solve(use_latest=self._whitelist).calculate_operations()
       245│         else:
       246│             self._io.write_line("Installing dependencies from lock file")

   1  ~/.local/pipx/venvs/poetry/lib/python3.10/site-packages/poetry/puzzle/solver.py:73 in solve
        71│         with self._provider.progress():
        72│             start = time.time()
     →  73│             packages, depths = self._solve(use_latest=use_latest)
        74│             end = time.time()
        75│ 

  SolverProblemError

  Because template-python depends on plantuml-markdown (~3.6.2) which doesn't match any versions, version solving failed.

  at ~/.local/pipx/venvs/poetry/lib/python3.10/site-packages/poetry/puzzle/solver.py:149 in _solve
      145│             packages = result.packages
      146│         except OverrideNeeded as e:
      147│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
      148│         except SolveFailure as e:
    → 149│             raise SolverProblemError(e)
      150│ 
      151│         combined_nodes = depth_first_search(PackageNode(self._package, packages))
      152│         results = dict(aggregate_package_nodes(nodes) for nodes in combined_nodes)
      153│ 
```

Thanks for your help.

**Comment by neersighted** [comment] 2022-07-25 14:15
Closing as dupe of #3543

**Closed by neersighted** 2022-07-25 14:15 UTC
Labels: Bug, Triage

**Comment by LeFakeMimit** [comment] 2022-07-25 14:44
Thanks a lot @dimbleby to have looked into this. This is clear now why it is now working 👍 I will wait for the refresh. Hopefully it will be fixed soon.
