### ISSUE TITLE
mypy says "no type hints or library stubs" although it parses package's .pyi

### ISSUE THREAD

**Issue by yanoom** [python-poetry/poetry#2194] opened 2020-03-18 13:32 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: win10
- **Poetry version**: 1.0.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/yanoom/b0a757aa512e6cb0a122ca3cfbc7f416

## Issue

We are in the process of releasing our library, called "Pyctuator".

I successfully created stubs for the package using stubgen.
I added the `MYPYPATH` environment variable with the location of the previously created "stub output folder" for mypy to find the stubs.

I use `poetry run mypy` on an example application that uses our new package:
I see that mypy is parsing the desired `pyctuator.pyi`
![image](https://user-images.githubusercontent.com/14986120/76965295-bbe44c00-692c-11ea-87e2-e28bf1c1d5ce.png)

But still fails in the end stating that no type hints or library stubs have been found:
![image](https://user-images.githubusercontent.com/14986120/76965377-d8808400-692c-11ea-8b85-9160835b55f2.png)

Your assistance is highly appreciated- thanks!
:)

**Comment by bryanforbes** [comment] 2020-04-22 15:34
Did you include a `py.typed` file in `pyctuator`?

**Comment by fwallacevt** [comment] 2020-07-08 19:11
@yanoom was this ever resolved?

**Comment by sobolevn** [comment] 2020-10-03 21:53
I am facing the same issue with the `1.1.0` release.

**Comment by abn** [comment] 2020-10-03 22:24
@sobolevn can you provide a bit more context please? 

@yanoom I believe this was resolved in python-poetry/poetry#2000 for `1.0.6`. This was also resolved in python-poetry/poetry-core#28 and should be available in `poetry-1.1.0` via `poetry-core-1.0.0`.

If you are building the wheen under PEP 517, you should update your `pyproject.toml` to use the following.

```toml
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

**Comment by sobolevn** [comment] 2020-10-04 08:20
@abn here's the full reproduction: https://github.com/dry-python/returns/pull/659

**Comment by abn** [comment] 2020-10-04 12:08
@sobolevn am I correct in understanding that this was a plugin issue caused due to poetry's editable installs using dist-info insted of setuptool's `egg-link` mechanism for "develop" installs?

**Comment by sobolevn** [comment] 2020-10-04 14:37
Yes, exactly. We needed to add a hack around `MYPYPATH` to make this working again.

**Comment by abn** [comment] 2020-10-04 16:02
@sobolevn so I can close this issue then? Assuming there is nothing to be done on the poetry side since we are following standard mechanisms to load path into python site.

**Comment by sobolevn** [comment] 2020-10-04 17:37
Yeap, this can be closed. Solution: use `MYPYPATH` env var or `mypy_path` option when `mypy` fails to detect your stubs.

**Closed** 2020-10-04 21:32 UTC
Labels: Bug
