### ISSUE TITLE
poetry doesn't install extras

### ISSUE THREAD

**Issue by devkral** [python-poetry/poetry#1145] opened 2019-06-01 21:32 UTC
setup:
only a pytoml file with the new build system

to reproduce:
poetry install -E foo
or
poetry install --extras "foo"
or
pip install ".[foo]"

result:
the dependencies of the foo group won't be installed

I think the issue here is that the extras system stops to work if no setup.py bails out.

**Comment by bersace** [comment] 2019-06-04 15:30
I confirm this with poetry 1.0.0a3.

**Comment by bersace** [comment] 2019-06-04 15:30
I think there is a bug around option handling. cf. #1141

**Comment by paveldedik** [comment] 2019-06-27 11:54
I had the same issue, but it seems to work correctly if I specify the extra dependencies in the `tool.poetry.dependencies` section instead of the `dev-dependencies` section which seems to be broken.

Can any of you confirm this behavior?

**Comment by dgilge** [comment] 2019-07-02 22:08
In my case it sometimes works and sometimes not. They are listed in `tool.poetry.dependencies`.
Poetry 0.12.16

**Comment by thedrow** [comment] 2019-07-26 08:46
Same issue here with latest.

**Comment by mrezzamoradi** [comment] 2019-07-29 23:45
I have this issue when installing from password protected private repo which does not have the package:

```toml
[[tool.poetry.source]]
name = "private"
url = "https://private.repo.com/simple"

[tool.poetry.dependencies]
python = "^3.7"
scikit-learn = {version = "0.19.0",extras = ["alldeps"]}
```
and then:
```bash
$ poetry update
Updating dependencies
Resolving dependencies... (18.2s)


Package operations: 5 installs, 0 updates, 0 removals

  - Installing scikit-learn (0.19.0)
                                                                                                                                                                        
[EnvCommandError]                                                                                                                                        
Command ['/home/reza/projects/virtualenvs/nava_37/bin/python', '-m', 'pip', 'install', '--no-deps', '--index-url', 'https://xxxx:yyyyyy@private.repo.com/simple',        
 'scikit-learn==0.19.0'] errored with the following return code 1, and output:                                                                                        
Looking in indexes: https://xxxx:****@private.repo.com/simple                                                                                                         
Collecting scikit-learn==0.19.0                                                                                                                                       
  Using cached https://files.pythonhosted.org/packages/c2/38/e3b0333e661ab411545583cb24940223917fe7ffc9c68a77730dce3b10b0/scikit-learn-0.19.0.tar.gz                  
Installing collected packages: scikit-learn                                                                                                                           
  Running setup.py install for scikit-learn: started                                                                                                                  
    Running setup.py install for scikit-learn: finished with status 'error'                                                                                           
    ERROR: Command errored out with exit status 1:                                                                                                                    
     command: /home/reza/projects/virtualenvs/nava_37/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-pifc_oyo/scikit-learn/                
setup.py'"'"'; __file__='"'"'/tmp/pip-install-pifc_oyo/scikit-learn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\  
n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-s3itmoyt/install-record.txt --single-version-externa  
lly-managed --compile --install-headers /home/reza/projects/virtualenvs/nava_37/include/site/python3.7/scikit-learn                                                   
         cwd: /tmp/pip-install-pifc_oyo/scikit-learn/                                                                                                                 
    Complete output (19 lines):                                                                                                                                       
    Partial import of sklearn during the build process.                                                                                                               
    Traceback (most recent call last):                                                                                                                                
      File "/tmp/pip-install-pifc_oyo/scikit-learn/setup.py", line 168, in get_numpy_status                                                                           
        import numpy                                                                                                                                                  
    ModuleNotFoundError: No module named 'numpy'                                                                                                                      
    Traceback (most recent call last):                                                                                                                                
      File "/tmp/pip-install-pifc_oyo/scikit-learn/setup.py", line 148, in get_scipy_status                                                                           
        import scipy                                                                                                                                                  
    ModuleNotFoundError: No module named 'scipy'                                                                                                                      
    Traceback (most recent call last):                                                                                                                                
      File "<string>", line 1, in <module>                                                                                                                            
      File "/tmp/pip-install-pifc_oyo/scikit-learn/setup.py", line 269, in <module>                                                                                   
        setup_package()                                                                                                                                               
      File "/tmp/pip-install-pifc_oyo/scikit-learn/setup.py", line 249, in setup_package                                                                              
        .format(numpy_req_str, instructions))                                                                                                                         
    ImportError: Numerical Python (NumPy) is not installed.                                                                                                           
    scikit-learn requires NumPy >= 1.8.2.                                                                                                                             
    Installation instructions are available on the scikit-learn website: http://scikit-learn.org/stable/install.html                                                  
                                                                                                                                                                      
    ----------------------------------------                                                                                                                          
ERROR: Command errored out with exit status 1: /home/reza/projects/virtualenvs/nava_37/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/p                
ip-install-pifc_oyo/scikit-learn/setup.py'"'"'; __file__='"'"'/tmp/pip-install-pifc_oyo/scikit-learn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file_  
_);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-s3itmoyt/install-re  
cord.txt --single-version-externally-managed --compile --install-headers /home/reza/projects/virtualenvs/nava_37/include/site/python3.7/scikit-learn Check the logs   
for full command output.                                                                                                                                              
                                                                                                                                                                        
update [--no-dev] [--dry-run] [--lock] [--] [<packages>]...
```
**Note**: the same `pyproject.toml` without `[tool.poetry.source]` section works fine.

<details>
<summary>Debug info</summary>

- pip: 19.2.1
- setup-tools: 41.0.1

Poetry
======

 * Version: 0.12.17
 * Python:  3.7.3


Virtualenv
==========

 * Python:         3.7.3
 * Implementation: CPython
 * Path:           /home/reza/projects/virtualenvs/nava_37
 * Valid:          True


System
======

 * Platform: linux
 * OS:       posix
 * Python:   /usr


</details>

**Comment by esciara** [comment] 2019-08-29 10:18
@devkral
> setup:
> only a pytoml file with the new build system

Could you give a gist link to your `pyproject.toml` file? 

Because what I found out is that adding packages in extras using `poetry add foo_package -E foo` generates the following:

```toml
# ~~ snip ~~

[tool.poetry.dependencies]
foo_package = {version = "^1.0", extras = ["foo"]}

# ~~ snip ~~
```
Which is not what is explained on the [doc for `extras`](https://poetry.eustace.io/docs/pyproject/#extras), which should be:

```toml
# ~~ snip ~~

[tool.poetry.dependencies]
foo_package = {version = "^1.0", optional = true}

[tool.poetry.extras]
foo = ["foo_package"]

# ~~ snip ~~
```
`poetry install -E foo` will not work with the former, and will in the later.

**Comment by bersace** [comment] 2019-08-29 12:03
@esciara `add -E` allows to add a dependency and some extras of the mentionned dependency. It's not meant to manage `tool.poetry.extras`. I don't know if there is CLI for this.

**Comment by esciara** [comment] 2019-08-29 12:07
Thanks @bersace . I don't quite understand the difference. Could you point to some references or the doc clarifying this?

**Comment by bersace** [comment] 2019-08-29 12:26
@esciara poetry add X -E Y is equivalent to appending `X[Y]` in `install_requires`. That's all.

What you understood is editing `setup(extras)`.

Maybe `poetry add` should have a `--optionnal extra_name` option for editing `tools.poetry.extras`

``` console
$ poetry add foo_package -E foo_extra --optionnal foo
```

This add foo_package[foo_extra] as depency of mypackage[foo]. Do you get it ?

**Comment by esciara** [comment] 2019-08-29 13:27
Aha! Yes got it. 

Yes I was expecting that everything `poetry` uses within `pyproject.toml` could be modified through the `cli` rather than manually only. Does that make sense?

If this logic is followed, then yes, doing something like adding a `--optional extra_name` to `poetry add`. 

Do you reckon it would be the most intuitive way to add to `tools.poetry.extras`?

And by the way, do you have an example where `--optional` would be used on its own, without any `extra_name`?

**Comment by bersace** [comment] 2019-08-29 13:48
Maybe `poetry add foo_package[foo_extras] -E myextra` seems easier for us used to setuptools.

**Comment by bersace** [comment] 2019-08-29 13:48
I don't know of usage of --optionnal out of extras.

**Comment by esciara** [comment] 2019-08-29 14:35
anyone else? @sdispater ?

**Comment by fgimian** [comment] 2019-10-13 05:31
I'm personally still really confused by this behaviour in Poetry.

Clearly `poetry add <name> -E <extra>` is intended to install package with `<name>` with optional extras for that package.

However, `poetry install -E <extra>` seems to be doing something completely different where a set of optional extra packages are installed.

I just tried this sample config:

```toml
[tool.poetry]
name = "testing"
...

[tool.poetry.dependencies]
python = "^3.6"
fastapi = "^0.42.0"
virtualenv-tools3 = {version = "^2.0", optional = true}

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[tool.poetry.extras]
packaging = ["virtualenv-tools3"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```

But `poetry install -E packaging` doesn't work:

```
Installing dependencies from lock file
Warning: The lock file is not up to date with the latest changes in pyproject.toml. You may be getting outdated dependencies. Run update to update them.

[ValueError]
Extra [packaging] is not specified.

install [--no-dev] [--dry-run] [-E|--extras EXTRAS] [--develop DEVELOP]

```

Perhaps a step by step tutorial on how extras is to be used would be handy here.  Just a basic example.

If the `--extra` flag has a different meaning in `add` and `install`, I think it may be wise to rename the flag.  However, it's totally possible I've completely misunderstood this feature 😄

**Comment by M5oul** [comment] 2019-11-09 15:14
I also thought the *extra* feature was for optional dependencies.
Yes, that would be great to be able to specify optional dependencies.
In my case, I want to be able to install just one dependency for a CI job, in order to have a faster job, without installing all dependencies.

**Comment by msiemens** [comment] 2019-11-15 18:05
> I had the same issue, but it seems to work correctly if I specify the extra dependencies in the `tool.poetry.dependencies` section instead of the `dev-dependencies` section which seems to be broken.
> 
> Can any of you confirm this behavior?

I have the same behavior. From a quick search it seems like this is by design, see https://github.com/sdispater/poetry/pull/606#issuecomment-437943927

**Comment by devkral** [comment] 2020-01-18 12:14
it was the missing optional dependency (but still it seems to not resolve clean for tox (pip install .[foo])). Sry for the late answer.

**Comment by leosussan** [comment] 2020-05-05 17:13
This seems like a really important addition, IMO. Users are forced to add it manually to an `extras` list & run `poetry lock` otherwise - and deploys dependent on that list are inevitably going to break as a result.

(quick: tip for folks reading this comment: implement `pre-commit` with a hook that runs `poetry check` or `poetry lock` on commit to prevent somebody from forgetting to run `poetry lock`)

For the purpose of matching the `-E` and `--extras` flags present in other parts of the library, and keeping `poetry` consistent with other parts of the ecosystem, @bersace's [suggested syntax](https://github.com/python-poetry/poetry/issues/1145#issuecomment-526193403) feels most appropriate!

**Comment by taidinh-tiki** [comment] 2020-05-30 05:13
Is it true that this problem has not been fixed yet? :(

**Comment by bersace** [comment] 2020-06-05 10:39
It looks like https://github.com/python-poetry/poetry/blob/master/poetry/installation/installer.py#L147-L159 does not pass extras to solver.

**Comment by matthijskooijman** [comment] 2020-06-05 15:29
Is it me, or are there two issues being mixed up here? This was originally about "extras" not being installed, but most discussion seems to be about needing a CLI instead of manually addin "extras" to pyproject.toml (and to poetry.lock using `poetry lock`)? Maybe the latter should move to a new issue if there isn't already?

**Comment by matthijskooijman** [comment] 2020-06-05 16:12
From https://github.com/python-poetry/poetry/issues/1145#issuecomment-526184709 of @esciara 

> And by the way, do you have an example where --optional would be used on its own, without any extra_name?

Isn't this how `--optional` works now, you can do `git add some_package --optional` without further arguments? Or am I misunderstanding the question?

I *think* `--optional` now means to not remove the package if it is installed, but not install it autmatically either? I wonder if reusing `--optional` to *also* specify extras-only dependencies might not only make things more confusing? See also #1076.

From https://github.com/python-poetry/poetry/issues/1145#issuecomment-526193403 of @bersace 

> Maybe poetry add foo_package[foo_extras] -E myextra seems easier for us used to setuptools.

Are you there proposing to repurpose `poetry add -E` from meaning "extras to apply to the given package" to mean "extras needed for this dependency to be installed" (e.g. from 1. to 2. as described in https://github.com/python-poetry/poetry/issues/1076#issuecomment-639569322)? Wouldn't that bring compatibility problems and maybe more confusion?

One way to somewhat sidestep this question of how to add a dependency into an "extras", would be to move towards a "dependency-group" terminology (as proposed in #1644), which might be more natural to reason about?

**Comment by tony** [comment] 2020-09-27 23:46
@matthijskooijman 
 
> Is it me, or are there two issues being mixed up here? This was originally about "extras" not being installed, but most discussion seems to be about needing a CLI instead of manually addin "extras" to pyproject.toml (and to poetry.lock using `poetry lock`)? Maybe the latter should move to a new issue if there isn't already?

I'm not able to understand this issue at the moment.  It's both a bug and feature thread.  I still don't know if this is 1.0 working as designed, a bug, if they're workarounds, etc.  Ideally we'd be collecting / cross-referencing bugs and reproductions

@finswimmer @sdispater Cna we close this and make 2 new issues: 

1. Bug reports / reproductions / workarounds for extras not being installed in 1.0
2. For discussing CLI aesthetics / features around extra/optional packages?

**Comment by abn** [comment] 2020-09-28 00:05
Thanks for going through this @tony. 

The original reported issue is can no longer be reproduced.

```console
$ cat pyproject.toml 
[tool.poetry]
name = "foobar"
version = "0.1.0"
description = ""
authors = ["Your Name <your.name@exaple.com>"]

[tool.poetry.dependencies]
python = "^3.8"
psycopg2-binary = {version = "^2.8.6", optional = true}

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.extras]
pg = ["psycopg2-binary"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
$ poetry@1.0.10 install -E pg --no-dev
Creating virtualenv foobar in /tmp/foobar/.venv
Installing dependencies from lock file


Package operations: 1 install, 0 updates, 0 removals

  - Installing psycopg2-binary (2.8.6)
  - Installing foobar (0.1.0)
```

Regarding (2) I think this warrants its own issue to discuss the options. The current options will likely not be repurposed. However, the CLI is tday lacking management of project extras. This migh also include a new option to specify what project extra an optional dependency should be added to. Documentation fixes can also be assessed if the current wording is causing confusion.

**Comment by matthijskooijman** [comment] 2020-09-28 08:01
Note that this also interacts with #1644, which is about extending the `extras` feature into a more generic `groups` feature. If that is indeed implemented, that would also be a good moment to add new CLI options to manage the groups/extras of the package itself, I think.

**Comment by abey79** [comment] 2020-11-10 15:40
> The original reported issue is can no longer be reproduced.

@abn I disagree. As suggested, I opened a new issue for this: #3348.

**Comment by jfaleiro** [comment] 2021-03-26 23:11
In poetry `1.1.5` optional and extras dependencies do not work for `dev-dependencies`. It fails silently.

**Comment by njgrisafi** [comment] 2021-09-09 15:51
experiencing the same issue `Poetry version 1.1.8`

Manually adding the extras to the `poetry.lock` and then running `poetry install -E my_extra` works. However, I'd except the extra section to be populated in the lock file by default.

**Comment by njgrisafi** [comment] 2021-09-15 20:00
Can confirm this is only happening with `dev-dependencies`. Created an example repository here to reproduce: https://github.com/njgrisafi/poetry-example

If you run `poetry install --extras lint` nothing will be installed. If you run `poetry install --extras non_dev` the expected dependencies will be installed.

You can also notice the lock file is [missing dev-dependency extras](https://github.com/njgrisafi/poetry-example/blob/b3ad2b15b6f1edb702426781ef6cec255ab17181/poetry.lock#L248) but [includes normal dependencies` extras](https://github.com/njgrisafi/poetry-example/blob/b3ad2b15b6f1edb702426781ef6cec255ab17181/poetry.lock#L249).

I believe the expected behavior for extras would be identical for `dev-dependencies` and `dependencies`.

**Comment by finswimmer** [comment] 2021-09-16 04:24
Hello @njgrisafi,

"extras" are only meant for `dependencies` not for `dev-dependencies`. So this is an expected behavior. From the current preview release (1.2.0a2) on there are [dependency groups](https://python-poetry.org/docs/master/managing-dependencies/#dependency-groups) that allow something similar.

fin swimmer

**Closed by finswimmer** 2021-09-16 04:24 UTC
Labels: Bug, Feature, Triage

**Comment by njgrisafi** [comment] 2021-09-16 18:11
ahh got it thank you @finswimmer!
