### ISSUE TITLE
Extra marker is ignored in `poetry install`, but respected in `pip install`

### ISSUE THREAD

**Issue by Omegastick** [python-poetry/poetry#7748] opened 2023-03-31 11:37 UTC
- **Poetry version**: 1.4.1
- **Python version**: 3.9
- **OS version and name**: Ubuntu 22.04 on WSL2
- **pyproject.toml**: https://gist.github.com/Omegastick/713164402b450b16b35c84f425db0a29

- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
If my understanding is correct, a dependency like this should install the PyPI repository version of the dependency if installed as `package_a[repo]`, and the path dependency if installed as `package_a{local]`:
```toml
[tool.poetry.dependencies]
package-b = [
    {version = "^0.1.0", markers = "extra == 'repo'", optional = true},
    {path = "../package_b", develop = true, markers = "extra == 'local'", optional = true},
]

[tool.poetry.extras]
repo = ["package-b"]
local = ["package-b"]
```
`pip install -e .[local]` installs the path dependency, and `pip install -e .[repo]` fails because `package_b` doesn't exist (as it should). `poetry install -E local` and `poetry install -E repo` both install the path dependency, though.

## Use case
I have quite a few repos, all using Poetry, that I would like to install locally with a single `poetry install` at the top of the dependency tree.

Example dependency tree:
```
package_a -> package_b -> package_c
```

If you alter the `package_b` dependency specification to add the right extras:
```toml
package-b = [
    {version = "^0.1.0", extras = ["repo"], markers = "extra == 'repo'", optional = true},
    {path = "../package_b", extras = ["local"], develop = true, markers = "extra == 'local'", optional = true},
]
```

You could use `poetry install -E local` to install the whole tree for local development. `pip install -e .[local]` seems to work this way, unless I'm missing something.

I'm aware that including path dependencies outside of groups specifies the full path (not relative) in `PKG-INFO`. That's not a problem for us, because the packages are only being uploaded to a private PyPI.

**Comment by dimbleby** [comment] 2023-03-31 11:40
you are stretching poetry quite far here, I dunno whether I'd expect this to work or not.  

But I'd try an explicit `source = "pypi"` on the repo version of the dependency, so that poetry knows that requirement it can't be satisfied by the path version.

**Comment by Omegastick** [comment] 2023-03-31 11:45
```toml
package-b = [
    {version = "^0.1.0", source = "pypi", markers = "extra == 'repo'", optional = true},
    {path = "../package_b", develop = true, markers = "extra == 'local'", optional = true},
]
```
This doesn't seem to work either. Interestingly, even with explicitly specifying the source, only the path dependency makes it into `poetry.lock`.

```toml
[[package]]
name = "package-b"
version = "0.1.0"
description = ""
category = "main"
optional = true
python-versions = "^3.9"
files = []
develop = true

[package.source]
type = "directory"
url = "../package_b"

[extras]
local = ["package-b", "package-b"]
repo = ["package-b", "package-b"]
```

**Comment by dimbleby** [comment] 2023-03-31 11:45
probably duplicate #7722 then, there's a suggested fix in there if you want to run with it

**Comment by Omegastick** [comment] 2023-03-31 12:24
Thanks for the help. It could be the same underlying issue. I installed Poetry from source and tried the suggested fix, but the code path doesn't seem to be hitting that method. I ran it in pdb and put a breakpoint there to be sure.

After looking at that issue, I tried switching the order of the dependencies. Putting the path dependency first, and the PyPI dependency second raises the `Because package-a depends on package-b (^0.1.0) which doesn't match any versions, version solving failed.` error, implying that it's the _second_ package (rather than the first as in #7722) that is being installed.

I tried swapping out `package_b` for `requests` to confirm with a package that actually exists on PyPI, but that doesn't show the same behaviour. This dependency always installs the path dependency, regardless of the order:
```toml
requests = [
    {version = "^2.28.2", source = "pypi", markers = "extra == 'repo'", optional = true},
    {path = "../requests", develop = true, markers = "extra == 'local'", optional = true},
]
```

I'm happy to help with a fix, but I don't really know enough about Poetry's internals to suggest one.

**Comment by rafaela00castro** [comment] 2023-06-27 14:28
It would be nice to have this feature working in poetry because it's extremely useful to have a separate version depending on the environment and be able to control that with `--extras`.

**Comment by marhoy** [comment] 2023-09-19 10:21
> It would be nice to have this feature working in poetry because it's extremely useful to have a separate version depending on the environment and be able to control that with `--extras`.

Agreed! I'm facing a similar issue where I want to install `torch` with either GPU- or CPU-support. I want to be able to control which one to choose with either a group or with extras.

**Comment by david-waterworth** [comment] 2024-02-14 22:47
For me using

```
[tool.poetry.extras]
cpu = ["torch"]
cu117 = ["torch"]

[tool.poetry.dependencies]
python = "^3.10"
torch = [
    {version = "2.0.0", markers = "extra == 'cpu' and extra != 'cu117'", source = "torch+cpu", optional=true},
    {version = "2.0.0", markers = "extra == 'cu117' and extra != 'cpu'", source = "torch+cu117", optional=true}
    ]
```

Results in poetry (1.7.1) trying to install both version (i.e. `poetry install -E cu117`

```
Installing torch (2.0.0+cpu)
Updating torch (2.0.0+cu117)
```

And then next time it tried to upgrade to 2.0.0+cu117 despite in theory already installing it. It's clear that markers don't work as we'd like.

Also I'd prefer to be able to add torch to optional groups, each with different versions because my project generates AWS Sagemaker ML Pipelines and I need to build/test containers - each with it's own requirements - so I'm using/abusing poetry to create separate environments for each step (in the container). My build script itself only needs sagemaker/boto3 but my tests/container Dockerfiles install specific groups from my poetry file. I know this pushes poetry beyond it's intended use.

**Comment by david-waterworth** [comment] 2024-02-14 23:12
So I sort of figured out what's going on by studying the lock file - I have 3 sources, our (private) codeartifact PyPI (which has pypi.com as upstream) along with the torch cpu and cuda sources.

So in my lock file there's 3 torch sections, one from each source.

I think this is caused by me adding `transformers` as 

```
[tool.poetry.dependencies]
python = "^3.10"
torch = [
    {version = "2.0.0", markers = "extra == 'cpu' and extra != 'cu117'", source = "torch+cpu", optional=true},
    {version = "2.0.0", markers = "extra == 'cu117' and extra != 'cpu'", source = "torch+cu117", optional=true}
    ]
transformers = {version = "^4.28.1", extras = ["torch"], optional=true}
```

I assume its searching our codeartifact for the torch extra and not respecting the fact that it's an explicit dependency with a custom source.

I removed the `torch` extra from `transformers` and it still added `torch` from `private` to `poetry.lock` (along with 2 other entries from the pytorch repo) but at least it didn't try and install it.

**Comment by david-waterworth** [comment] 2024-02-14 23:32
So part of what's happening here is I have 3 sources, our private codeartifact repo (which has PyPI as upstream) and two pytorch sources (CPU and GPU).

When I added `transformers[torch]` it's resolving the transformer extra (torch) against private rather than the pytorch sources so there's a conflict.

So I've replaced `transformers[torch]` with `transformers` and given up trying to use markers to select cpu/gpu for now.

**Comment by QuentinSoubeyranAqemia** [comment] 2024-02-15 09:47
IMHO fixing this would provide the last missing piece to be able to use PyTorch and Poetry in all situations, using the setup outline in [this earlier comment](https://github.com/python-poetry/poetry/issues/7748#issuecomment-1944892320).


Poetry currently supports a single hardware variant of pytorch, but not switching between hardware variants, due this issue. This would be an awesome capability.

**Comment by GOGKI** [comment] 2024-04-19 08:23
Hello Everyone, Is there a progress on this issue?

**Comment by suvobratlendbuzz** [comment] 2024-05-14 18:29
For anyone looking for a solution, the following hack worked for me on Poetry version `1.8.2`:

```
[tool.poetry.dependencies]
torch = { version = "~1.13", source = "pytorch-cpu", markers = "extra=='cpu' and extra!='cuda'" }
torchvision = { version="~0.14", source = "pytorch-cpu", markers = "extra=='cpu' and extra!='cuda'" }

[tool.poetry.group.cuda]
optional = true

[tool.poetry.group.cuda.dependencies]
torch = { version = "~1.13", source = "pypi", markers = "extra=='cuda' and extra!='cpu'" }
torchvision = { version="~0.14", source = "pypi", markers = "extra=='cuda' and extra!='cpu'" }

[tool.poetry.extras]
cuda = ["torch", "torchvision"]
cpu = ["torch", "torchvision"]

[[tool.poetry.source]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
priority = "explicit"
```
`poetry install -E cpu` install `torch-cpu`, while `poetry install -E cuda --with cuda` will fetch `torch-cuda`. Should technically work with `wheel` source for `cuda` too. Hope this helps!

**Comment by shuvamg007** [comment] 2024-05-14 18:31
For anyone looking for a solution, the following hack worked for me on Poetry version `1.8.2`:

```
[tool.poetry.dependencies]
torch = { version = "~1.13", source = "pytorch-cpu", markers = "extra=='cpu' and extra!='cuda'" }
torchvision = { version="~0.14", source = "pytorch-cpu", markers = "extra=='cpu' and extra!='cuda'" }

[tool.poetry.group.cuda]
optional = true

[tool.poetry.group.cuda.dependencies]
torch = { version = "~1.13", source = "pypi", markers = "extra=='cuda' and extra!='cpu'" }
torchvision = { version="~0.14", source = "pypi", markers = "extra=='cuda' and extra!='cpu'" }

[tool.poetry.extras]
cuda = ["torch", "torchvision"]
cpu = ["torch", "torchvision"]

[[tool.poetry.source]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
priority = "explicit"
```

`poetry install -E cpu` install `torch-cpu`, while `poetry install -E cuda --with cuda` will fetch `torch-cuda`. Should technically work with `wheel` source for `cuda` too (didn't test it).

**Closed** 2024-11-30 06:14 UTC
Labels: kind/bug, status/triage, area/deps
