### ISSUE TITLE
Improper dependency check against nonexistent python 4.0

### ISSUE THREAD

**Issue by slobodaapl** [python-poetry/poetry#7711] opened 2023-03-23 23:08 UTC
- **Poetry version**: 1.4.1
- **Python version**: 3.10.6
- **OS version and name**: ubuntu-22.04 ver. 20230317.1
- **pyproject.toml**: [Link to pyproject.toml](https://gist.github.com/slobodaapl/faa62486832238c05fbf52b811d56102)

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
I'm running a GitHub Actions workflow where I use poetry to install my dependencies based on pyproject.toml .. I have tried replicating this issue locally, but it doesn't seem to happen locally at all, only during the workflow. It appears that Poetry thinks, that Python 3.11 doesn't match `pytest-socket`'s required versions of `python>=3.7,<4.0`.

1. I set up the system (see OS and name above)
2. I install poetry using pipx: `pipx install poetry`
    Output: `installed package poetry 1.4.1, installed using Python 3.10.6`
3. I set up python 3.11.2
    Output: `Successfully setup CPython (3.11.2)`
4. `run poetry install --with dev`

Output:
```
poetry install --with dev
  pip install -e .
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.11.2/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.11.2/x64/lib
  
The currently activated Python version 3.10.6 is not supported by the project (>=3.11).
Trying to find and use a compatible version. 
Using python3 (3.11.2)
Creating virtualenv xxxx-urPOA57N-py3.11 in /home/runner/.cache/pypoetry/virtualenvs
Updating dependencies
Resolving dependencies...

The current project's Python requirement (>=3.11) is not compatible with some of the required packages Python requirement:
  - pytest-socket requires Python >=3.7,<4.0, so it will not be satisfied for Python >=4.0

Because xxxx depends on pytest-socket (0.6.0) which requires Python >=3.7,<4.0, version solving failed.

  • Check your dependencies Python requirement: The Python requirement can be specified via the `python` or `markers` properties
    
    For pytest-socket, a possible solution would be to set the `python` property to ">=3.11,<4.0"

    https://python-poetry.org/docs/dependency-specification/#python-restricted-dependencies,
    https://python-poetry.org/docs/dependency-specification/#using-environment-markers
```

Full workflow file: [workflow.yml](https://gist.github.com/slobodaapl/820591d3b65f02f39a1649f0a3436c2c)

**Comment by clintonroy** [comment] 2023-03-24 01:16
The current project's Python requirement (>=3.11)

that appears to be different to the pyproject.toml referenced, which has ==3.11

**Comment by clintonroy** [comment] 2023-03-24 03:57
If I take your referenced pyproject.toml  (with a small tweak to use python 3.11.2 which is what i've got) and run poetry update, it resolves.

If I modify that pyproject.toml to have

```
[tool.poetry.dependencies]
python = ">=3.11.2"
```

I get really similar errors to what you are reporting.

```
clintonr@rassilon:~/projects/poet/poetryplay$ poetry update
Updating dependencies
Resolving dependencies... (0.5s)

The current project's Python requirement (>=3.11.2) is not compatible with some of the required packages Python requirement:
  - pytest-socket requires Python >=3.7,<4.0, so it will not be satisfied for Python >=4.0

Because xxxx depends on pytest-socket (0.6.0) which requires Python >=3.7,<4.0, version solving failed.

  • Check your dependencies Python requirement: The Python requirement can be specified via the `python` or `markers` properties
    
    For pytest-socket, a possible solution would be to set the `python` property to ">=3.11.2,<4.0"

    https://python-poetry.org/docs/dependency-specification/#python-restricted-dependencies,
    https://python-poetry.org/docs/dependency-specification/#using-environment-markers

```

It very much looks like the pyrproject.toml you're running is not the one you've linked, specifically the python version does not match the error you are getting.

Your assumption about python==3.11 being equivalent to python>3.11 is incorrect.

**Comment by slobodaapl** [comment] 2023-03-24 04:45
@clintonroy My assumption is that `python==3.11` is similar to `python>=3.11` rather than `python>3.11`, but I still understand your point. And you're right, I've gone over the action, and it used a `pyprojct.toml` file that's not up-to-date in reference to the latest commit in the pull request for some reason.

I found that indeed, inside the proper `pyproject.toml`, the python version is set to `python>=3.11` though that still doesn't make much sense to me that it would cause this dependency issue, since Python 3.11, which is the version that gets installed (`Using python3 (3.11.2)`), is consistent with both `python==3.11` and `python>=3.11`.

It still satisfies the condition of `pytest-socket` where `python>=3.7,<4.0`, so it shouldn't fail in my opinion.

**Comment by clintonroy** [comment] 2023-03-24 05:45
https://python-poetry.org/docs/faq/#why-is-poetry-telling-me-that-the-current-projects-python-requirement-is-not-compatible-with-one-or-more-packages-python-requirements

Your project allows, say python version 4.1.2 to be used, but that is not consistent with one of your projects dependencies which requires a version of python less than 4.0.0 to be used.

Your project dependencies are inconsistent, that is what poetry is reporting.

**Comment by dimbleby** [comment] 2023-03-24 08:44
not a bug per the faq, please close

**Comment by slobodaapl** [comment] 2023-03-24 13:56
@clintonroy @dimbleby 

Unfortunately, even following the advice and comments, I am unable to get Poetry to correctly recognize Python 3.11 to be used with the project, even after changing `pyprojectl.toml` and the workflow file:

[pyproject.toml](https://gist.github.com/slobodaapl/58a673190d2e2b6473e5bdd6150fd97f)
[workflow.yml](https://gist.github.com/slobodaapl/4c03bda86c44095cbba8c1ea5ae0fbd6)

These are directly taken from the workflow run commit, so they should be the actual versions.

With the `poetry env use 3.11` line commented, the output is the following, and crashed during the 'Install dependencies' step:

```
pipx install poetry
  # poetry env use 3.11
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.11.2/x[6](https://github.com/slobodaapl/xxxx/actions/runs/4511853294/jobs/7944525631?pr=19#step:4:6)4
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.11.2/x64/lib
creating virtual environment...
installing poetry...
done! ✨ 🌟 ✨
  installed package poetry 1.4.1, installed using Python 3.[10](https://github.com/slobodaapl/xxxx/actions/runs/4511853294/jobs/7944525631?pr=19#step:4:11).6
  These apps are now globally available
    - poetry
0s
Run poetry install --with dev
The currently activated Python version 3.10.6 is not supported by the project (3.[11](https://github.com/slobodaapl/xxxx/actions/runs/4511853294/jobs/7944525631?pr=19#step:4:12)).
Trying to find and use a compatible version. 

Poetry was unable to find a compatible version. If you have one, you can explicitly use it via the "env use" command.
Error: Process completed with exit code [1](https://github.com/slobodaapl/xxxx/actions/runs/4511853294/jobs/7944525631?pr=19#step:5:1).
```

And with it not commented out, the output is the following, and crashes during 'Set up Poetry' step:

```
pipx install poetry
  poetry env use 3.11
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.11.2/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.11.2/x64/lib
creating virtual environment...
installing poetry...
done! ✨ 🌟 ✨
  installed package poetry 1.4.1, installed using Python 3.[10](https://github.com/slobodaapl/xxxx/actions/runs/4511900112/jobs/7944632217?pr=19#step:4:11).6
  These apps are now globally available
    - poetry

The specified Python version (3.[11](https://github.com/slobodaapl/xxxx/actions/runs/4511900112/jobs/7944632217?pr=19#step:4:12).2) is not supported by the project (3.11).
Please choose a compatible version or loosen the python constraint specified in the pyproject.toml file.
```

**Comment by dimbleby** [comment] 2023-03-24 17:37
you are now talking about something quite different.  There are lots of open issues talking about "poetry env use", this angle is surely a duplicate of one of those.

**Comment by slobodaapl** [comment] 2023-03-24 17:47
Even if I don't use `poetry env use`, we can agree that with Python 3.11.2 installed on the system, Poetry fails to recognize it as compatible with the project which specifies `python==3.11` right? We can also agree that `python=3.11` is within the specified requirements of `python-pysocket` which is `python>=3.7,<4.0` … which is the original issue once again, because Poetry fails to recognize it as compatible.

**Comment by dimbleby** [comment] 2023-03-24 17:49
`python==3.11` is the same as `python==3.11.0` which is not compatible with 3.11.2

re python-pysocket please read the faq that clintonroy pointed you at: this is not a bug and this issue should be closed.

**Closed** 2023-03-24 17:53 UTC
Labels: kind/bug, status/triage
