### ISSUE TITLE
Cannot install llvmlite due to incorrectly enforced python version constraint

### ISSUE THREAD

**Issue by hugocool** [python-poetry/poetry#4081] opened 2021-05-19 21:39 UTC
- [X ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **mac OS Catalina**:
- **Poetry version**: 1.1.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/hugocool/6952ae7491b42c22c99c9e4e2417fc25

## Issue
installing llvmlite as a dependacy to SHAP, gives the following traceback:
```
PyPI: No release information found for llvmlite-0.1, skipping
PyPI: 1 packages found for llvmlite >=0.36.0,<0.37.0
   1: fact: llvmlite (0.36.0) requires Python >=3.6,<3.10
   1: derived: not llvmlite (==0.36.0)
   1: fact: no versions of llvmlite match >0.36.0,<0.37.0
   1: conflict: no versions of llvmlite match >0.36.0,<0.37.0
   1: derived: not llvmlite (>0.36.0,<0.37.0)
   1: conflict: llvmlite (0.36.0) requires Python >=3.6,<3.10
   1: !  llvmlite (0.36.0) is partially satisfied by not  llvmlite (>0.36.0,<0.37.0)
   1: ! which is caused by "no versions of llvmlite match >0.36.0,<0.37.0"
   1: ! thus: llvmlite is forbidden
   1: !  llvmlite (>=0.36.0,<0.37.0) is satisfied by  llvmlite (^0.36.0)
   1: ! which is caused by "diabetes dashboard depends on llvmlite (^0.36.0)"
   1: ! thus: version solving failed
   1: Version solving took 0.872 seconds.
   1: Tried 1 solutions.

  Stack trace:

  8  ~/.poetry/lib/poetry/_vendor/py3.9/clikit/console_application.py:131 in run
      129│             parsed_args = resolved_command.args
      130│ 
    → 131│             status_code = command.handle(parsed_args, io)
      132│         except KeyboardInterrupt:
      133│             status_code = 1

  7  ~/.poetry/lib/poetry/_vendor/py3.9/clikit/api/command/command.py:120 in handle
      118│     def handle(self, args, io):  # type: (Args, IO) -> int
      119│         try:
    → 120│             status_code = self._do_handle(args, io)
      121│         except KeyboardInterrupt:
      122│             if io.is_debug():

  6  ~/.poetry/lib/poetry/_vendor/py3.9/clikit/api/command/command.py:171 in _do_handle
      169│         handler_method = self._config.handler_method
      170│ 
    → 171│         return getattr(handler, handler_method)(args, io, self)
      172│ 
      173│     def __repr__(self):  # type: () -> str

  5  ~/.poetry/lib/poetry/_vendor/py3.9/cleo/commands/command.py:92 in wrap_handle
       90│         self._command = command
       91│ 
    →  92│         return self.handle()
       93│ 
       94│     def handle(self):  # type: () -> Optional[int]

  4  ~/.poetry/lib/poetry/console/commands/add.py:173 in handle
      171│             self._installer.whitelist([r["name"] for r in requirements])
      172│ 
    → 173│             status = self._installer.run()
      174│         except BaseException:
      175│             # Using BaseException here as some exceptions, eg: KeyboardInterrupt, do not inherit from Exception

  3  ~/.poetry/lib/poetry/installation/installer.py:103 in run
      101│         local_repo = Repository()
      102│ 
    → 103│         return self._do_install(local_repo)
      104│ 
      105│     def dry_run(self, dry_run=True):  # type: (bool) -> Installer

  2  ~/.poetry/lib/poetry/installation/installer.py:235 in _do_install
      233│             )
      234│ 
    → 235│             ops = solver.solve(use_latest=self._whitelist)
      236│         else:
      237│             self._io.write_line("Installing dependencies from lock file")

  1  ~/.poetry/lib/poetry/puzzle/solver.py:65 in solve
       63│         with self._provider.progress():
       64│             start = time.time()
    →  65│             packages, depths = self._solve(use_latest=use_latest)
       66│             end = time.time()
       67│ 

  SolverProblemError

  The current project's Python requirement (>=3.7.10,<4.0.0) is not compatible with some of the required packages Python requirement:
    - llvmlite requires Python >=3.6,<3.10, so it will not be satisfied for Python >=3.10,<4.0.0
  
  Because llvmlite (0.36.0) requires Python >=3.6,<3.10
   and no versions of llvmlite match >0.36.0,<0.37.0, llvmlite is forbidden.
  So, because diabetes dashboard depends on llvmlite (^0.36.0), version solving failed.

  at ~/.poetry/lib/poetry/puzzle/solver.py:241 in _solve
      237│             packages = result.packages
      238│         except OverrideNeeded as e:
      239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
      240│         except SolveFailure as e:
    → 241│             raise SolverProblemError(e)
      242│ 
      243│         results = dict(
      244│             depth_first_search(
      245│                 PackageNode(self._package, packages), aggregate_package_nodes

  • Check your dependencies Python requirement: The Python requirement can be specified via the `python` or `markers` properties
    
    For llvmlite, a possible solution would be to set the `python` property to ">=3.7.10,<3.10"

    https://python-poetry.org/docs/dependency-specification/#python-restricted-dependencies,
    https://python-poetry.org/docs/dependency-specification/#using-environment-markers
```

However, the python version i enforced IS python 3.7.1, and this problem also occurs with higher versions of python.

When building an environment using pipenv there is no problem in building an environment nor running the code.
I can also build the environment using poetry when using a docker file and using the docker container as an interpreter (using remote container development), it also works in gitpod. But when using poetry on my mac, it just doesn't work :-(.

**Comment by Natureshadow** [comment] 2021-05-22 10:51
I can confirm that Python version constraints are broken (or behave very strange):

```plain
The current project's Python requirement (>=3.7,<4.0) is not compatible with some of the required packages Python requirement:
    - aleksis-core requires Python >=3.9,<4.0, so it will not be satisfied for Python >=3.7,<3.9
```

Where does the final `<3.9` come from?

**Comment by finswimmer** [comment] 2021-06-04 11:27
Hello @hugocool,

the `pyproject.toml` you've linked, contains this:

```toml
[tool.poetry.dependencies]
python = "^3.7.10"
```

This means you project's python requirement is >=3.7.10,<4.0.0, which is a problem for llvmlite which upper bound in <3.10. Why do you think you've enforced the version to 3.7.1?

@Natureshadow: This looks indeed a bit strange. Can you provide a reproducible example, please?

fin swimmer

**Comment by Natureshadow** [comment] 2021-06-04 13:20
> This means you project's python requirement is >=3.7.10,<4.0.0, which is a problem for llvmlite which upper bound is <3.10. Why do you think you've enforced the version to 3.7.1?

3.9 fulfills both constraints, so unless someone has Python 3.10 or 3.11 or so installed, the dependencies should resolve.


> @Natureshadow[https://github.com/Natureshadow]: This looks indeed a bit strange. Can you provide a reproducible example, please?

Will do later.

**Comment by hugocool** [comment] 2021-06-04 13:26
I’ve enforced the Python version to 3.7.10 to match the version of Python used in Google Colab (such that my environment can be reproduced in an academic setting easily, which it does).

should I do
[tool.poetry.dependencies]
python = "3.7.10"

**Comment by finswimmer** [comment] 2021-06-11 12:22
> 3.9 fulfills both constraints, so unless someone has Python 3.10 or 3.11 or so installed, the dependencies should resolve.

When poetry resolves dependencies it doesn't care about the local python version. It cares about the version constraint in the `pyproject.toml`.

> should I do:
> [tool.poetry.dependencies]
> python = "3.7.10"

If you really want to force the exact version, than this is the correct way.

**Comment by finswimmer** [comment] 2021-06-23 19:09
Hello @hugocool,

I'm closing this issue because I believe the original issue is solved/explained. Feel free to leave a comment if you disagree.

fin swimmer

**Closed by finswimmer** 2021-06-23 19:09 UTC
Labels: Bug, Triage
