### ISSUE TITLE
poetry installer fails on slim containers due to missing dependency on gcc

### ISSUE THREAD

**Issue by ryboe** [python-poetry/poetry#6428] opened 2022-09-06 17:45 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: debian bullseye amd64
- **Poetry version**: 1.2.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue

The poetry installer currently fails on `python:slim` containers because it depends on `gcc`, which isn't present in slim containers.

Here's a minimal reproducible error:

```sh
docker container run --platform linux/amd64 python:3.10.6-slim /bin/bash -c 'apt-get update && apt-get install -y --no-install-recommends curl && curl -sfSL https://install.python-poetry.org | python -'
```

<details>
  <summary>The error logs</summary>
  
```txt
Collecting poetry==1.2.0
  Downloading poetry-1.2.0-py3-none-any.whl (210 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 210.9/210.9 kB 4.8 MB/s eta 0:00:00
Collecting poetry-plugin-export<2.0.0,>=1.0.6
  Downloading poetry_plugin_export-1.0.6-py3-none-any.whl (9.6 kB)
Collecting shellingham<2.0,>=1.5
  Downloading shellingham-1.5.0-py2.py3-none-any.whl (9.3 kB)
Collecting virtualenv
  Downloading virtualenv-20.16.4-py3-none-any.whl (8.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.8/8.8 MB 19.3 MB/s eta 0:00:00
Collecting packaging>=20.4
  Downloading packaging-21.3-py3-none-any.whl (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.8/40.8 kB 5.5 MB/s eta 0:00:00
Collecting jsonschema<5.0.0,>=4.10.0
  Downloading jsonschema-4.15.0-py3-none-any.whl (82 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 82.7/82.7 kB 9.7 MB/s eta 0:00:00
Collecting crashtest<0.4.0,>=0.3.0
  Downloading crashtest-0.3.1-py3-none-any.whl (7.0 kB)
Collecting requests-toolbelt<0.10.0,>=0.9.1
  Downloading requests_toolbelt-0.9.1-py2.py3-none-any.whl (54 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.3/54.3 kB 7.2 MB/s eta 0:00:00
Collecting cachy<0.4.0,>=0.3.0
  Downloading cachy-0.3.0-py2.py3-none-any.whl (20 kB)
Collecting urllib3<2.0.0,>=1.26.0
  Downloading urllib3-1.26.12-py2.py3-none-any.whl (140 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.4/140.4 kB 12.0 MB/s eta 0:00:00
Collecting html5lib<2.0,>=1.0
  Downloading html5lib-1.1-py2.py3-none-any.whl (112 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 112.2/112.2 kB 11.6 MB/s eta 0:00:00
Collecting pkginfo<2.0,>=1.5
  Downloading pkginfo-1.8.3-py2.py3-none-any.whl (26 kB)
Collecting dulwich<0.21.0,>=0.20.44
  Downloading dulwich-0.20.46.tar.gz (426 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 426.5/426.5 kB 18.8 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting keyring>=21.2.0
  Downloading keyring-23.9.1-py3-none-any.whl (35 kB)
Collecting platformdirs<3.0.0,>=2.5.2
  Downloading platformdirs-2.5.2-py3-none-any.whl (14 kB)
Collecting poetry-core==1.1.0
  Downloading poetry_core-1.1.0-py3-none-any.whl (526 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 526.2/526.2 kB 20.5 MB/s eta 0:00:00
Collecting requests<3.0,>=2.18
  Downloading requests-2.28.1-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 kB 7.5 MB/s eta 0:00:00
Collecting cleo<2.0.0,>=1.0.0a5
  Downloading cleo-1.0.0a5-py3-none-any.whl (78 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.7/78.7 kB 9.3 MB/s eta 0:00:00
Collecting tomlkit!=0.11.2,!=0.11.3,<1.0.0,>=0.11.1
  Downloading tomlkit-0.11.4-py3-none-any.whl (35 kB)
Collecting pexpect<5.0.0,>=4.7.0
  Downloading pexpect-4.8.0-py2.py3-none-any.whl (59 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.0/59.0 kB 8.2 MB/s eta 0:00:00
Collecting cachecontrol[filecache]<0.13.0,>=0.12.9
  Downloading CacheControl-0.12.11-py2.py3-none-any.whl (21 kB)
Collecting msgpack>=0.5.2
  Downloading msgpack-1.0.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (316 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 317.0/317.0 kB 16.8 MB/s eta 0:00:00
Collecting lockfile>=0.9
  Downloading lockfile-0.12.2-py2.py3-none-any.whl (13 kB)
Collecting pylev<2.0.0,>=1.3.0
  Downloading pylev-1.4.0-py2.py3-none-any.whl (6.1 kB)
Collecting six>=1.9
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting webencodings
  Downloading webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Collecting attrs>=17.4.0
  Downloading attrs-22.1.0-py2.py3-none-any.whl (58 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.8/58.8 kB 7.5 MB/s eta 0:00:00
Collecting pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0
  Downloading pyrsistent-0.18.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (115 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.8/115.8 kB 12.2 MB/s eta 0:00:00
Collecting SecretStorage>=3.2
  Downloading SecretStorage-3.3.3-py3-none-any.whl (15 kB)
Collecting jaraco.classes
  Downloading jaraco.classes-3.2.2-py3-none-any.whl (6.0 kB)
Collecting jeepney>=0.4.2
  Downloading jeepney-0.8.0-py3-none-any.whl (48 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.4/48.4 kB 7.0 MB/s eta 0:00:00
Collecting pyparsing!=3.0.5,>=2.0.2
  Downloading pyparsing-3.0.9-py3-none-any.whl (98 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.3/98.3 kB 11.4 MB/s eta 0:00:00
Collecting ptyprocess>=0.5
  Downloading ptyprocess-0.7.0-py2.py3-none-any.whl (13 kB)
Collecting certifi>=2017.4.17
  Downloading certifi-2022.6.15-py3-none-any.whl (160 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 160.2/160.2 kB 9.9 MB/s eta 0:00:00
Collecting charset-normalizer<3,>=2
  Downloading charset_normalizer-2.1.1-py3-none-any.whl (39 kB)
Collecting idna<4,>=2.5
  Downloading idna-3.3-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.2/61.2 kB 8.3 MB/s eta 0:00:00
Collecting distlib<1,>=0.3.5
  Downloading distlib-0.3.6-py2.py3-none-any.whl (468 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 468.5/468.5 kB 5.3 MB/s eta 0:00:00
Collecting filelock<4,>=3.4.1
  Downloading filelock-3.8.0-py3-none-any.whl (10 kB)
Collecting cryptography>=2.0
  Downloading cryptography-37.0.4-cp36-abi3-manylinux_2_24_x86_64.whl (4.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.1/4.1 MB 20.9 MB/s eta 0:00:00
Collecting more-itertools
  Downloading more_itertools-8.14.0-py3-none-any.whl (52 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.2/52.2 kB 5.8 MB/s eta 0:00:00
Collecting cffi>=1.12
  Downloading cffi-1.15.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (441 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 441.8/441.8 kB 20.2 MB/s eta 0:00:00
Collecting pycparser
  Downloading pycparser-2.21-py2.py3-none-any.whl (118 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.7/118.7 kB 12.1 MB/s eta 0:00:00
Using legacy 'setup.py install' for dulwich, since package 'wheel' is not installed.
Installing collected packages: webencodings, pylev, ptyprocess, msgpack, lockfile, distlib, urllib3, tomlkit, six, shellingham, pyrsistent, pyparsing, pycparser, poetry-core, platformdirs, pkginfo, pexpect, more-itertools, jeepney, idna, filelock, crashtest, charset-normalizer, certifi, cachy, attrs, virtualenv, requests, packaging, jsonschema, jaraco.classes, html5lib, dulwich, cleo, cffi, requests-toolbelt, cryptography, cachecontrol, SecretStorage, keyring, poetry-plugin-export, poetry
  Running setup.py install for dulwich: started
  Running setup.py install for dulwich: finished with status 'error'
  error: subprocess-exited-with-error

  × Running setup.py install for dulwich did not run successfully.
  │ exit code: 1
  ╰─> [143 lines of output]
      running install
      /root/.local/share/pypoetry/venv/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-310
      creating build/lib.linux-x86_64-cpython-310/dulwich
      copying dulwich/file.py -> build/lib.linux-x86_64-cpython-310/dulwich
      copying dulwich/log_utils.py -> build/lib.linux-x86_64-cpython-310/dulwich
      copying dulwich/__main__.py -> build/lib.linux-x86_64-cpython-310/dulwich
      copying dulwich/index.py -> build/lib.linux-x86_64-cpython-310/dulwich
      copying dulwich/diff_tree.py -> build/lib.linux-x86_64-cpython-310/dulwich
      copying dulwich/mailmap.py -> build/lib.linux-x86_64-cpython-310/dulwich
      copying dulwich/repo.py -> build/lib.linux-x86_64-cpython-310/dulwich
      copying dulwich/objectspec.py -> build/lib.linux-x86_64-cpython-310/dulwich
      copying dulwich/patch.py -> build/lib.linux-x86_64-cpython-310/dulwich
      copying dulwich/lru_cache.py -> build/lib.linux-x86_64-cpython-310/dulwich
      copying dulwich/object_store.py -> build/lib.linux-x86_64-cpython-310/dulwich
      copying dulwich/fastexport.py -> build/lib.linux-x86_64-cpython-310/dulwich
      copying dulwich/graph.py -> build/lib.linux-x86_64-cpython-310/dulwich
      copying dulwich/client.py -> build/lib.linux-x86_64-cpython-310/dulwich
      copying dulwich/objects.py -> build/lib.linux-x86_64-cpython-310/dulwich
      copying dulwich/errors.py -> build/lib.linux-x86_64-cpython-310/dulwich
      copying dulwich/archive.py -> build/lib.linux-x86_64-cpython-310/dulwich
      copying dulwich/__init__.py -> build/lib.linux-x86_64-cpython-310/dulwich
      copying dulwich/line_ending.py -> build/lib.linux-x86_64-cpython-310/dulwich
      copying dulwich/server.py -> build/lib.linux-x86_64-cpython-310/dulwich
      copying dulwich/config.py -> build/lib.linux-x86_64-cpython-310/dulwich
      copying dulwich/pack.py -> build/lib.linux-x86_64-cpython-310/dulwich
      copying dulwich/refs.py -> build/lib.linux-x86_64-cpython-310/dulwich
      copying dulwich/stash.py -> build/lib.linux-x86_64-cpython-310/dulwich
      copying dulwich/hooks.py -> build/lib.linux-x86_64-cpython-310/dulwich
      copying dulwich/greenthreads.py -> build/lib.linux-x86_64-cpython-310/dulwich
      copying dulwich/reflog.py -> build/lib.linux-x86_64-cpython-310/dulwich
      copying dulwich/protocol.py -> build/lib.linux-x86_64-cpython-310/dulwich
      copying dulwich/lfs.py -> build/lib.linux-x86_64-cpython-310/dulwich
      copying dulwich/ignore.py -> build/lib.linux-x86_64-cpython-310/dulwich
      copying dulwich/submodule.py -> build/lib.linux-x86_64-cpython-310/dulwich
      copying dulwich/porcelain.py -> build/lib.linux-x86_64-cpython-310/dulwich
      copying dulwich/walk.py -> build/lib.linux-x86_64-cpython-310/dulwich
      copying dulwich/web.py -> build/lib.linux-x86_64-cpython-310/dulwich
      copying dulwich/cli.py -> build/lib.linux-x86_64-cpython-310/dulwich
      copying dulwich/bundle.py -> build/lib.linux-x86_64-cpython-310/dulwich
      creating build/lib.linux-x86_64-cpython-310/dulwich/cloud
      copying dulwich/cloud/__init__.py -> build/lib.linux-x86_64-cpython-310/dulwich/cloud
      copying dulwich/cloud/gcs.py -> build/lib.linux-x86_64-cpython-310/dulwich/cloud
      creating build/lib.linux-x86_64-cpython-310/dulwich/tests
      copying dulwich/tests/test_ignore.py -> build/lib.linux-x86_64-cpython-310/dulwich/tests
      copying dulwich/tests/test_line_ending.py -> build/lib.linux-x86_64-cpython-310/dulwich/tests
      copying dulwich/tests/test_web.py -> build/lib.linux-x86_64-cpython-310/dulwich/tests
      copying dulwich/tests/test_grafts.py -> build/lib.linux-x86_64-cpython-310/dulwich/tests
      copying dulwich/tests/test_blackbox.py -> build/lib.linux-x86_64-cpython-310/dulwich/tests
      copying dulwich/tests/test_walk.py -> build/lib.linux-x86_64-cpython-310/dulwich/tests
      copying dulwich/tests/test_object_store.py -> build/lib.linux-x86_64-cpython-310/dulwich/tests
      copying dulwich/tests/test_diff_tree.py -> build/lib.linux-x86_64-cpython-310/dulwich/tests
      copying dulwich/tests/test_server.py -> build/lib.linux-x86_64-cpython-310/dulwich/tests
      copying dulwich/tests/test_objects.py -> build/lib.linux-x86_64-cpython-310/dulwich/tests
      copying dulwich/tests/test_repository.py -> build/lib.linux-x86_64-cpython-310/dulwich/tests
      copying dulwich/tests/__init__.py -> build/lib.linux-x86_64-cpython-310/dulwich/tests
      copying dulwich/tests/test_refs.py -> build/lib.linux-x86_64-cpython-310/dulwich/tests
      copying dulwich/tests/test_index.py -> build/lib.linux-x86_64-cpython-310/dulwich/tests
      copying dulwich/tests/test_reflog.py -> build/lib.linux-x86_64-cpython-310/dulwich/tests
      copying dulwich/tests/test_client.py -> build/lib.linux-x86_64-cpython-310/dulwich/tests
      copying dulwich/tests/test_graph.py -> build/lib.linux-x86_64-cpython-310/dulwich/tests
      copying dulwich/tests/test_patch.py -> build/lib.linux-x86_64-cpython-310/dulwich/tests
      copying dulwich/tests/test_fastexport.py -> build/lib.linux-x86_64-cpython-310/dulwich/tests
      copying dulwich/tests/test_greenthreads.py -> build/lib.linux-x86_64-cpython-310/dulwich/tests
      copying dulwich/tests/test_config.py -> build/lib.linux-x86_64-cpython-310/dulwich/tests
      copying dulwich/tests/test_lru_cache.py -> build/lib.linux-x86_64-cpython-310/dulwich/tests
      copying dulwich/tests/test_archive.py -> build/lib.linux-x86_64-cpython-310/dulwich/tests
      copying dulwich/tests/test_bundle.py -> build/lib.linux-x86_64-cpython-310/dulwich/tests
      copying dulwich/tests/test_protocol.py -> build/lib.linux-x86_64-cpython-310/dulwich/tests
      copying dulwich/tests/test_stash.py -> build/lib.linux-x86_64-cpython-310/dulwich/tests
      copying dulwich/tests/test_hooks.py -> build/lib.linux-x86_64-cpython-310/dulwich/tests
      copying dulwich/tests/test_lfs.py -> build/lib.linux-x86_64-cpython-310/dulwich/tests
      copying dulwich/tests/test_file.py -> build/lib.linux-x86_64-cpython-310/dulwich/tests
      copying dulwich/tests/utils.py -> build/lib.linux-x86_64-cpython-310/dulwich/tests
      copying dulwich/tests/test_mailmap.py -> build/lib.linux-x86_64-cpython-310/dulwich/tests
      copying dulwich/tests/test_missing_obj_finder.py -> build/lib.linux-x86_64-cpython-310/dulwich/tests
      copying dulwich/tests/test_objectspec.py -> build/lib.linux-x86_64-cpython-310/dulwich/tests
      copying dulwich/tests/test_pack.py -> build/lib.linux-x86_64-cpython-310/dulwich/tests
      copying dulwich/tests/test_utils.py -> build/lib.linux-x86_64-cpython-310/dulwich/tests
      copying dulwich/tests/test_porcelain.py -> build/lib.linux-x86_64-cpython-310/dulwich/tests
      creating build/lib.linux-x86_64-cpython-310/dulwich/tests/compat
      copying dulwich/tests/compat/server_utils.py -> build/lib.linux-x86_64-cpython-310/dulwich/tests/compat
      copying dulwich/tests/compat/test_web.py -> build/lib.linux-x86_64-cpython-310/dulwich/tests/compat
      copying dulwich/tests/compat/test_server.py -> build/lib.linux-x86_64-cpython-310/dulwich/tests/compat
      copying dulwich/tests/compat/test_repository.py -> build/lib.linux-x86_64-cpython-310/dulwich/tests/compat
      copying dulwich/tests/compat/__init__.py -> build/lib.linux-x86_64-cpython-310/dulwich/tests/compat
      copying dulwich/tests/compat/test_client.py -> build/lib.linux-x86_64-cpython-310/dulwich/tests/compat
      copying dulwich/tests/compat/test_patch.py -> build/lib.linux-x86_64-cpython-310/dulwich/tests/compat
      copying dulwich/tests/compat/utils.py -> build/lib.linux-x86_64-cpython-310/dulwich/tests/compat
      copying dulwich/tests/compat/test_pack.py -> build/lib.linux-x86_64-cpython-310/dulwich/tests/compat
      copying dulwich/tests/compat/test_utils.py -> build/lib.linux-x86_64-cpython-310/dulwich/tests/compat
      copying dulwich/tests/compat/test_porcelain.py -> build/lib.linux-x86_64-cpython-310/dulwich/tests/compat
      creating build/lib.linux-x86_64-cpython-310/dulwich/contrib
      copying dulwich/contrib/requests_vendor.py -> build/lib.linux-x86_64-cpython-310/dulwich/contrib
      copying dulwich/contrib/test_swift_smoke.py -> build/lib.linux-x86_64-cpython-310/dulwich/contrib
      copying dulwich/contrib/swift.py -> build/lib.linux-x86_64-cpython-310/dulwich/contrib
      copying dulwich/contrib/__init__.py -> build/lib.linux-x86_64-cpython-310/dulwich/contrib
      copying dulwich/contrib/test_paramiko_vendor.py -> build/lib.linux-x86_64-cpython-310/dulwich/contrib
      copying dulwich/contrib/test_release_robot.py -> build/lib.linux-x86_64-cpython-310/dulwich/contrib
      copying dulwich/contrib/test_swift.py -> build/lib.linux-x86_64-cpython-310/dulwich/contrib
      copying dulwich/contrib/paramiko_vendor.py -> build/lib.linux-x86_64-cpython-310/dulwich/contrib
      copying dulwich/contrib/diffstat.py -> build/lib.linux-x86_64-cpython-310/dulwich/contrib
      copying dulwich/contrib/release_robot.py -> build/lib.linux-x86_64-cpython-310/dulwich/contrib
      running egg_info
      writing dulwich.egg-info/PKG-INFO
      writing dependency_links to dulwich.egg-info/dependency_links.txt
      writing entry points to dulwich.egg-info/entry_points.txt
      writing requirements to dulwich.egg-info/requires.txt
      writing top-level names to dulwich.egg-info/top_level.txt
      reading manifest file 'dulwich.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no directories found matching 'dulwich/tests/data'
      adding license file 'COPYING'
      adding license file 'AUTHORS'
      writing manifest file 'dulwich.egg-info/SOURCES.txt'
      copying dulwich/_diff_tree.c -> build/lib.linux-x86_64-cpython-310/dulwich
      copying dulwich/_objects.c -> build/lib.linux-x86_64-cpython-310/dulwich
      copying dulwich/_pack.c -> build/lib.linux-x86_64-cpython-310/dulwich
      copying dulwich/py.typed -> build/lib.linux-x86_64-cpython-310/dulwich
      copying dulwich/stdint.h -> build/lib.linux-x86_64-cpython-310/dulwich
      creating build/lib.linux-x86_64-cpython-310/docs
      creating build/lib.linux-x86_64-cpython-310/docs/tutorial
      copying dulwich/../docs/tutorial/conclusion.txt -> build/lib.linux-x86_64-cpython-310/dulwich/../docs/tutorial
      copying dulwich/../docs/tutorial/encoding.txt -> build/lib.linux-x86_64-cpython-310/dulwich/../docs/tutorial
      copying dulwich/../docs/tutorial/file-format.txt -> build/lib.linux-x86_64-cpython-310/dulwich/../docs/tutorial
      copying dulwich/../docs/tutorial/index.txt -> build/lib.linux-x86_64-cpython-310/dulwich/../docs/tutorial
      copying dulwich/../docs/tutorial/introduction.txt -> build/lib.linux-x86_64-cpython-310/dulwich/../docs/tutorial
      copying dulwich/../docs/tutorial/object-store.txt -> build/lib.linux-x86_64-cpython-310/dulwich/../docs/tutorial
      copying dulwich/../docs/tutorial/porcelain.txt -> build/lib.linux-x86_64-cpython-310/dulwich/../docs/tutorial
      copying dulwich/../docs/tutorial/remote.txt -> build/lib.linux-x86_64-cpython-310/dulwich/../docs/tutorial
      copying dulwich/../docs/tutorial/repo.txt -> build/lib.linux-x86_64-cpython-310/dulwich/../docs/tutorial
      copying dulwich/../docs/tutorial/tag.txt -> build/lib.linux-x86_64-cpython-310/dulwich/../docs/tutorial
      copying dulwich/contrib/README.md -> build/lib.linux-x86_64-cpython-310/dulwich/contrib
      running build_ext
      building 'dulwich._objects' extension
      creating build/temp.linux-x86_64-cpython-310
      creating build/temp.linux-x86_64-cpython-310/dulwich
      gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/root/.local/share/pypoetry/venv/include -I/usr/local/include/python3.10 -c dulwich/_objects.c -o build/temp.linux-x86_64-cpython-310/dulwich/_objects.o
      error: command 'gcc' failed: No such file or directory
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> dulwich

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

Traceback:

  File "<stdin>", line 909, in main
  File "<stdin>", line 545, in run
  File "<stdin>", line 567, in install
  File "<stdin>", line 670, in install_poetry
  File "<stdin>", line 362, in pip
  File "<stdin>", line 359, in python
  File "<stdin>", line 352, in run
```

</details>

**Comment by jorgebodega** [comment] 2022-09-06 17:52
Same here!

The curious thing is that I merged a PR an hour and a half ago and it worked.

I'm using the `python:3.10-slim` container on github.

[Failing log](https://github.com/Oipie/oipie-api-core/runs/8213118959?check_suite_focus=true)
[Working log](https://github.com/Oipie/oipie-api-core/runs/8210596965?check_suite_focus=true)

**Comment by mrosales** [comment] 2022-09-06 17:53
Was writing up another bug but saw this was just published. This is causing all of our docker images to fail building on `python:*-slim` variants too.

Root cause seems to be that `dulwich` was released without wheels on PyPi and the new official poetry installer no longer pins dependencies when installing poetry

https://github.com/jelmer/dulwich/issues/1034

**Comment by jorgebodega** [comment] 2022-09-06 17:54
By my side, there is no urgency on fix this, so I can help providing more info if it helps.

**Comment by kylebarron** [comment] 2022-09-06 17:58
If you're installing `poetry` via pip, I would expect it would work if you manually pin to the previous `dulwich` version

```
pip install dulwich==0.20.45 poetry==1.2.0
```

**Comment by jorgebodega** [comment] 2022-09-06 18:00
I prefer not to do it, if it's possible, so I'll wait for dulwich.

Also, would be great if poetry just pin its dependencies, so this kind of errors would not exist in the future.

**Comment by dimbleby** [comment] 2022-09-06 18:11
Seems like this is fixed upstream and can be closed

**Comment by neersighted** [comment] 2022-09-06 19:21
> I prefer not to do it, if it's possible, so I'll wait for dulwich.
> 
> Also, would be great if poetry just pin its dependencies, so this kind of errors would not exist in the future.

All in good time -- it's very much on the roadmap (that we probably need to spell out -- it mostly lives in contributor's heads right now) to support locked builds from source, and locked bdists.

**Closed by neersighted** 2022-09-06 19:21 UTC
Labels: kind/bug, status/triage
