### ISSUE TITLE
No module named `poetry.core` on Py3.9.0b1

### ISSUE THREAD

**Issue by itsthejoker** [python-poetry/poetry#2449] opened 2020-05-21 15:15 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 20.04
- **Poetry version**: 1.1.0a1
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: N/A

## Issue

I've installed Py3.9.0b1 through pyenv (listed as `3.9-dev`) and am attempting to use poetry. Using Poetry 1.0.5, I receive:

```sh
Traceback (most recent call last):
  File "/home/joe/.poetry/bin/poetry", line 12, in <module>
    from poetry.console import main
  File "/home/joe/.poetry/lib/poetry/console/__init__.py", line 1, in <module>
    from .application import Application
  File "/home/joe/.poetry/lib/poetry/console/application.py", line 1, in <module>
    from cleo import Application as BaseApplication
ModuleNotFoundError: No module named 'cleo'
```

...so I reinstalled from get-poetry.py asking for the preview version. This gives:

```
Traceback (most recent call last):
  File "/home/joe/.poetry/bin/poetry", line 16, in <module>
    from poetry.console import main
  File "/home/joe/.poetry/lib/poetry/console/__init__.py", line 1, in <module>
    from .application import Application
  File "/home/joe/.poetry/lib/poetry/console/application.py", line 5, in <module>
    from .commands.about import AboutCommand
  File "/home/joe/.poetry/lib/poetry/console/commands/__init__.py", line 4, in <module>
    from .check import CheckCommand
  File "/home/joe/.poetry/lib/poetry/console/commands/check.py", line 1, in <module>
    from poetry.factory import Factory
  File "/home/joe/.poetry/lib/poetry/factory.py", line 9, in <module>
    from poetry.core.factory import Factory as BaseFactory
ModuleNotFoundError: No module named 'poetry.core'
```

...on every call to Poetry.

**Comment by WesleyBatista** [comment] 2020-12-05 19:40
I experienced the same issue when upgrading from 1.0.5 using the `poetry self update` command.

```
$ poetry self update
Updating to 1.1.4
 - Downloading poetry-1.1.4-linux.tar.gz 100%

Poetry (1.1.4) is installed now. Great!

$ poetry --help     
Traceback (most recent call last):
  File "/home/wesley/.poetry/bin/poetry", line 12, in <module>
    from poetry.console import main
  File "/home/wesley/.poetry/lib/poetry/console/__init__.py", line 1, in <module>
    from .application import Application
  File "/home/wesley/.poetry/lib/poetry/console/application.py", line 7, in <module>
    from .commands.about import AboutCommand
  File "/home/wesley/.poetry/lib/poetry/console/commands/__init__.py", line 2, in <module>
    from .add import AddCommand
  File "/home/wesley/.poetry/lib/poetry/console/commands/add.py", line 8, in <module>
    from .init import InitCommand
  File "/home/wesley/.poetry/lib/poetry/console/commands/init.py", line 16, in <module>
    from poetry.core.pyproject import PyProjectException
ModuleNotFoundError: No module named 'poetry.core'
```

what solved it for me was:
```
$ pip install -U poetry
```

**Comment by doremifasollasi** [comment] 2021-07-08 14:59
I created a virtual environment. Then I needed to install Apache Airflow. But the program stopped and reported an error (ModuleNotFoundError: No module named 'poetry'). 
The command `$ pip install -U poetry` helped me solve this problem.

**Comment by DetachHead** [comment] 2021-12-22 00:16
having the same issue. as far as i can tell i've removed all remnants of 1.0.5 but still seeing this error

```
C:\Users\user\IdeaProjects\python-project>python -m pip show poetry-core      
WARNING: Package(s) not found: poetry-core

C:\Users\user\IdeaProjects\python-project>poetry
Traceback (most recent call last):
  File "C:\Users\user\.poetry\bin\poetry", line 17, in <module>
    from poetry.console import main
  File "C:\Users\user\.poetry\lib\poetry\console\__init__.py", line 1, in <module>
    from .application import Application
  File "C:\Users\user\.poetry\lib\poetry\console\application.py", line 7, in <module>
    from .commands.about import AboutCommand
  File "C:\Users\user\.poetry\lib\poetry\console\commands\__init__.py", line 2, in <module>
    from .add import AddCommand
  File "C:\Users\user\.poetry\lib\poetry\console\commands\add.py", line 8, in <module>
    from .init import InitCommand
  File "C:\Users\user\.poetry\lib\poetry\console\commands\init.py", line 16, in <module>
    from poetry.core.pyproject import PyProjectException
ModuleNotFoundError: No module named 'poetry.core'
```

this is incredibly frustrating. the install script and/or the `poetry self update` command seems to have has completely messed up my install and i have no idea how to fix it

**Comment by clintonroy** [comment] 2021-12-22 00:33
Please try using pipx to install poetry. Honestly, I just don't understand why everyone tries to use weird scripts rather than bog standard tools.

**Comment by DetachHead** [comment] 2021-12-22 00:47
because the documentation [tells you to](https://python-poetry.org/docs/#installation), and scares you away from using pip with a big red warning

i was wondering the same thing. maybe the install scripts should be removed if they don't work properly?

**Comment by clintonroy** [comment] 2021-12-22 00:50
pipx, not pip, it's a supported installation technique; not to undersell pipx at all, but it does a pip install into a virtual environment, which is really what we want.

**Comment by DetachHead** [comment] 2021-12-22 03:40
ah i see. using pipx seemed to work, thanks!

kinda strange how the pipx method is buried below the janky install script and the non-recommended pip method tho

**Comment by Jamesits** [comment] 2021-12-30 06:19
I can reproduce this exact bug.

My environment:
- OS: Windows 11 22000.376
- Python: 3.10.1 (tags/v3.10.1:2cd268a, installer downloaded from the official website)
- Poetry: 1.11.2, installed using the PowerShell script

**Comment by clintonroy** [comment] 2021-12-30 06:36
@Jamesits there is a known bug with python3.10 and the install scripts, the 3.10 stuff wasn't vendored. Please use an alternative installation technique, such as pipx. (I think you'll find that you'll use pipx to install all your python cli tools in the future, not just poetry)

**Comment by Secrus** [comment] 2022-05-16 21:50
I believe the bug is fixed now.

**Closed by Secrus** 2022-05-16 21:50 UTC
Labels: Bug

**Comment by ice1x** [comment] 2023-09-15 10:40
Reproduced on Python 3.11
