### ISSUE TITLE
Timer appears dark on dark terminal

### ISSUE THREAD

**Issue by jtrakk** [python-poetry/poetry#2228] opened 2020-03-26 21:07 UTC
With a dark terminal background, the timer is hard to see.

![image](https://user-images.githubusercontent.com/43392409/77696726-1011b080-6f6b-11ea-8185-6992b68704ac.png)

**Comment by bhaveshpraveen** [comment] 2020-04-25 10:59
I'd like to work on this issue if no one's picked it up yet.

**Comment by abn** [comment] 2020-04-25 11:40
@bhaveshpraveen feel free to, but @sdispater might have some thoughts here. I'd suggest creating a draft PR if you have a solution to propose.

**Comment by sdispater** [comment] 2020-04-27 10:54
This issue was caused by the fact that we were using a black color in bold which could be too dark in some terminals and this has already been fixed in this PR: #2230.

This was already reported in https://github.com/python-poetry/poetry/pull/2150.

So I am closing this since it's already been handled.

**Closed by sdispater** 2020-04-27 10:54 UTC
Labels: CLI, Good First Issue
