### ISSUE TITLE
Poetry Hooks

### ISSUE THREAD

**Issue by jefer94** [python-poetry/poetry#9906] opened 2024-12-17 05:26 UTC
### Issue Kind

Brand new capability

### Description

Installations hooks like NPM and PDM do

### Impact

Could add pre-commit by default during the dependency resolution

### Workarounds

I have no idea, a possible alternative to this is, if we cannot set hooks, we could preselect the Poetry add-ons and these must be installed after a dependency resolution

**Comment by Secrus** [comment] 2024-12-18 12:36
Duplicate of #5443

**Closed by Secrus** 2024-12-18 12:36 UTC
Labels: kind/feature, status/triage
