### ISSUE TITLE
Poetry raises a [TypeError]'encoding' is an invalid keyword argument for this function when running in Python2.7 virtual environment

### ISSUE THREAD

**Issue by badrobit** [python-poetry/poetry#1290] opened 2019-08-09 15:53 UTC
- [X] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 18.04 
- **Poetry version**: 0.12.17
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: I am not allowed due to company rules

## Issue
When running poetry (command: `poetry update`) from within a 2.7 virtual environment while parsing a package defined as a git repository the following error occurs: 

```
[TypeError]                                     
'encoding' is an invalid keyword argument for this function  
```

when run with the -vvv option I get the following: 

```
Exception trace:
 /home/mroscoe/.poetry/lib/poetry/_vendor/py2.7/cleo/application.py in run() at line 94
   status_code = self.do_run(input_, output_)
 /home/mroscoe/.poetry/lib/poetry/console/application.py in do_run() at line 88
   return super(Application, self).do_run(i, o)
 /home/mroscoe/.poetry/lib/poetry/_vendor/py2.7/cleo/application.py in do_run() at line 197
   status_code = command.run(input_, output_)
 /home/mroscoe/.poetry/lib/poetry/console/commands/command.py in run() at line 77
   return super(BaseCommand, self).run(i, o)
 /home/mroscoe/.poetry/lib/poetry/_vendor/py2.7/cleo/commands/base_command.py in run() at line 146
   status_code = self.execute(input_, output_)
 /home/mroscoe/.poetry/lib/poetry/_vendor/py2.7/cleo/commands/command.py in execute() at line 107
   return self.handle()
 /home/mroscoe/.poetry/lib/poetry/console/commands/update.py in handle() at line 41
   return installer.run()
 /home/mroscoe/.poetry/lib/poetry/installation/installer.py in run() at line 73
   self._do_install(local_repo)
 /home/mroscoe/.poetry/lib/poetry/installation/installer.py in _do_install() at line 290
   self._execute(op)
 /home/mroscoe/.poetry/lib/poetry/installation/installer.py in _execute() at line 306
   getattr(self, "_execute_{}".format(method))(operation)
 /home/mroscoe/.poetry/lib/poetry/installation/installer.py in _execute_install() at line 331
   self._installer.install(operation.package)
 /home/mroscoe/.poetry/lib/poetry/installation/pip_installer.py in install() at line 35
   self.install_git(package)
 /home/mroscoe/.poetry/lib/poetry/installation/pip_installer.py in install_git() at line 230
   self.install_directory(pkg)
 /home/mroscoe/.poetry/lib/poetry/installation/pip_installer.py in install_directory() at line 196
   with open(setup, "w", encoding="utf-8") as f:
```

I was able to resolve the issue by adding the following import to the `pip_installer.py` file: 
```python
from io import open
```

**Comment by gramosg** [comment] 2019-09-11 10:51
I have the same issue, does not happen in Poetry 0.12.16. Using it until this issue is solved.

**Comment by badrobit** [comment] 2019-11-14 00:40
Yes it is still relevant and needs to be fixed

**Comment by RoelantStegmann** [comment] 2020-04-08 18:38
Also have this :)

**Comment by jerpint** [comment] 2020-04-23 20:06
Same Poetry version 1.0.2 on Ubuntu 18.04, using poetry inside a conda environment

**Comment by lamivan** [comment] 2020-05-08 08:04
hey guys, when i use msgpack-python 1.0.0, it raises the same error. then i downgrade msgpack-python to 0.6.1, no error is raised. u can have a try.

**Comment by finswimmer** [comment] 2020-05-10 18:08
Hello @jerpint ,

can you please retry with the current release of poetry (1.0.5)? If the issue still exists, can you please describe step by step how one can reproduce it?

Thanks!

fin swimmer

**Comment by RoelantStegmann** [comment] 2020-05-18 15:31
Still doesn't work for me. 

```
conda create --name poetry python=3.7
conda install poetry
activate poetry
pip install poetry --upgrade
poetry install 
```

**Comment by jerpint** [comment] 2020-05-18 20:20
Here's what ended up working for me:

`poetry env use python3.7`

Before doing poetry install

**Comment by v5y8** [comment] 2020-05-26 19:31
I also ran into this issue, on Poetry version 1.0.5 on Ubuntu 18.04 and running poetry inside a conda environment.

Apparently this can be caused by an outdated `msgback-python` package documented [here](https://github.com/firebase/firebase-admin-python/issues/377) and [here](https://bugs.launchpad.net/ubuntu/+source/calibre/+bug/1838862).

I was able to solve this by running `pip install --upgrade --user msgpack-python`.

**Comment by mirosval** [comment] 2020-10-24 17:41
I actually had to downgrade: `pip install msgpack==0.6.2` pyenv & macOS

**Comment by finswimmer** [comment] 2021-07-23 09:38
Closing this because no more comments have been added for a long time and according to @v5y8 this seems not be a poetry issue.

**Closed by finswimmer** 2021-07-23 09:38 UTC
Labels: Bug
