### ISSUE TITLE
[SolverProblemError] Wrong dependency solving

### ISSUE THREAD

**Issue by Olegt0rr** [python-poetry/poetry#3901] opened 2021-04-09 05:18 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**:  macOS 11.2.3 (20D91)
- **Poetry version**: 1.1.5
- **pyproject.toml**: https://gist.github.com/Olegt0rr/a464bc0f8fc6db6c87d9ba547273f8cb#file-pyproject-toml
- **Log output**: https://gist.github.com/Olegt0rr/a464bc0f8fc6db6c87d9ba547273f8cb#file-console-log

### Actions

1. Create empty project
2. Add dependency `pymongo = {version = "3.11.3", extras = ["srv"]}`
3. Run `poetry add dnspython`

### Expected output:
```toml
# pyproject.toml

[tool.poetry.dependencies]
python = "^3.8"
pymongo = {version = "3.11.3", extras = ["srv"]}
dnspython = "~1.16"
```

### Real output
```log
poetry add dnspython     
Using version ^2.1.0 for dnspython

Updating dependencies
Resolving dependencies... (0.0s)

[SolverProblemError]
Because tree depends on pymongo (3.11.3) which depends on dnspython (>=1.16.0,<1.17.0), dnspython is required.
So, because tree depends on dnspython (^2.1.0), version solving failed.
```
Rich log: https://gist.github.com/Olegt0rr/a464bc0f8fc6db6c87d9ba547273f8cb#file-console-log

**Comment by finswimmer** [comment] 2021-08-02 15:21
Hello @Olegt0rr,

it seems that the resolver tries to find a solution for the latest major version of the dependency only and gives up if it cannot find a solution. Giving poetry a hint where to start searching works as a workaround, e.g. `poetry add "dnspython=~1.16"`.

fin swimmer

**Comment by Olegt0rr** [comment] 2021-08-02 15:49
@finswimmer, 
Thanks for manual workaround, but it so weird for me to make hints about version resolving :)
Still waiting for fixing this behaviour

**Comment by dimbleby** [comment] 2022-10-23 16:54
another duplicate of #707

**Comment by neersighted** [comment] 2022-10-23 16:59
Good catch.

**Closed by neersighted** 2022-10-23 16:59 UTC
Labels: status/duplicate
