### ISSUE TITLE
Optional dependencies get included as non-optional in the lock file when also specified as a dev dependency

### ISSUE THREAD

**Issue by provinzkraut** [python-poetry/poetry#7747] opened 2023-03-31 08:54 UTC
- **Poetry version**: 1.4.0
- **Python version**: 3.10.10
- **OS version and name**: Ubuntu 22.10
- **pyproject.toml**: https://gist.github.com/provinzkraut/5639f88ebdf34da06feb9745bfc1bbb8

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

When marking a dependency as optional (as seen in the linked `pyproject.toml`), they will be marked as non-optional in `poetry.lock` (and subsequently generated dists) when this dependency is also included as a dev dependency.

I could not find any documentation that tells me this behaviour is intended, so I'm assuming it is a bug. Maybe this is intended or expected, in which case it would be great to have a section about this restriction in the documentation.

This is the `poetry.lock` that has been generated for the `pyproject.toml` linked above:
```toml
# This file is automatically @generated by Poetry 1.4.0 and should not be changed by hand.

[[package]]
name = "bottle"
version = "0.12.25"
description = "Fast and simple WSGI-framework for small web-applications."
category = "main"
optional = false
python-versions = "*"
files = [
    {file = "bottle-0.12.25-py3-none-any.whl", hash = "sha256:d6f15f9d422670b7c073d63bd8d287b135388da187a0f3e3c19293626ce034ea"},
    {file = "bottle-0.12.25.tar.gz", hash = "sha256:e1a9c94970ae6d710b3fb4526294dfeb86f2cb4a81eff3a4b98dc40fb0e5e021"},
]

[metadata]
lock-version = "2.0"
python-versions = "^3.10"
content-hash = "abdf8ce488b5fe74f1c5c603626ec03e1afcb7ae02c53f1a03736160e03a4e6c"
```

**Comment by dimbleby** [comment] 2023-06-04 16:37
as well as the poetry-export issue above, this duplicates https://github.com/python-poetry/poetry/issues/3188

(both of those are better than this one because they exhibit actual user-facing symptoms, rather than only expressing surprise about the content of the lockfile)

**Comment by provinzkraut** [comment] 2023-06-04 17:33
> they exhibit actual user-facing symptoms, rather than only expressing surprise about the content of the lockfile

This is a user facing problem. It causes unnecessary dependencies to be installed when a package like this is distributed. 

This is not only surprising, but also not a good behaviour. If my package for example claims to have no dependencies, a broken lockfile like this will make it unusable *without* installing dependencies. 

It might also been seen as malicious to include dependencies that are unexpected.

Another issue would be environments where size is of concern. Having large libraries only intended for development be included in the distribution is far from ideal.

**Comment by dimbleby** [comment] 2023-06-04 17:55
>  It causes unnecessary dependencies to be installed when a package like this is distributed.

that's not what the issue report says, it just says that there some lines that you didn't expect in an internal-facing file.

no need to argue about it though, either way this is a duplicate of #3188, #4401, and the poetry-export bug

please close

**Closed** 2023-06-04 19:30 UTC
Labels: kind/bug, status/triage
