### ISSUE TITLE
Python script execution does not relay exit code

### ISSUE THREAD

**Issue by cwichel** [python-poetry/poetry#5773] opened 2022-06-05 15:48 UTC
- [ ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10 (Build 19044)
- **Poetry version**: 1.2.0b1
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: Not required.

## Issue

**Note:** 
* This could be related to issues #2369 #2904 #4456
* Also, a related PR was opened on POE project [#71](https://github.com/nat-n/poethepoet/issues/71#issue-1260435346)

Poetry is not relaying the exit codes when running python scripts on the console: 
```shell
>  poetry run python -c "import sys; sys.exit(1)"
> echo %errorlevel%
0
```

But if I execute it directly...
```shell
> python -c "import sys; sys.exit(1)"
> echo %errorlevel%
1
```

Is this the expected behavior?

**Comment by dimbleby** [comment] 2022-06-05 20:11
Works fine on Linux
```
$ poetry run python -c "import sys; sys.exit(13)"
$ echo $?
13
```

relevant code seems to be https://github.com/python-poetry/poetry/blob/865aa94dd3393076f790d3351f6ae18483673e38/src/poetry/utils/env.py#L1501-#L1511.

I don't have a suitable windows environment to test on but I can tweak the code to force it through the `Popen` branch anyway, at which point I see two things:

- this code seems to have been broken by #3339, I think it has to go `cmd = list_to_shell_command(command)` if it's going to set `shell=True`, and then run `cmd`
  - else I just get a python interpreter when running `poetry run python -c "import sys; sys.exit(13)"` ...
  - @kevincon is that right?

- but that bug isn't in 1.2.0b1 so you won't see it, and after tweaking it manually I still get the expected return code when going through that branch on Linux

So I dunno, some sort of windows-only thing maybe?

**Comment by kevincon** [comment] 2022-06-05 20:39
@dimbleby thanks for your analysis! I’m not sure I understand the issue with #3339 since https://stackoverflow.com/a/1253161 suggests that passing a command as a list and setting shell=True on Windows should already convert the sequence to a string, but if it’s causing problems then feel free to revert it. It took over 1.5 years for #3339 to be reviewed and merged, so I won’t be working on that particular issue anymore.

**Comment by dimbleby** [comment] 2022-06-05 20:42
I don't have a windows environment to test in: perhaps this is fine on Windows.

I guess if it's broken then someone who does use windows will notice soon enough...

**Comment by radoering** [comment] 2022-06-06 08:23
I can't reproduce the issue in cmd on Windows with either 1.2.0b1 or master. 🤷

**Comment by cwichel** [comment] 2022-06-06 19:38
I've performed more testing on my side and I've found that the error appears depending on the install mode of poetry...

1. If I install the last version of poetry (1.2.0b1) using pip (`python -m pip install poetry==1.2.0b1`) the return code is incorrect (same test as in the example).  
2. If I install the last version of poetry (1.2.0b1) using the recommended mode (`curl -sSL https://install.pyt...`) the return code is correct.

**Comment by neersighted** [comment] 2022-06-09 16:38
> I've performed more testing on my side and I've found that the error appears depending on the install mode of poetry...
> 
>     1. If I install the last version of poetry (1.2.0b1) using pip (`python -m pip install poetry==1.2.0b1`) the return code is incorrect (same test as in the example).
> 
>     2. If I install the last version of poetry (1.2.0b1) using the recommended mode (`curl -sSL https://install.pyt...`) the return code is correct.

Please try again on `b2` -- the issue likely is because when installing with `pip` you're pulling in a stable (instead of pre-release) `poetry-core`.

**Comment by cwichel** [comment] 2022-06-10 03:43
Tested doing the following: 

1. Created a conda environment for python 3.7:
   ```
   > conda create -n py37 python=3.7.11 -y
   > activate py37 
   ```
2. Installed poetry 1.2.0b2:
   ```
   > pip install poetry==1.2.0b2
   ```
3. Running test: 
   ```
   > poetry run python -c "import sys; sys.exit(1)"
   > echo %errorlevel%
   1 
   ```
Everything seems to be working OK now 😄

**Closed** 2022-06-10 14:46 UTC
Labels: Bug, Triage
