### ISSUE TITLE
--find-links equivalent

### ISSUE THREAD

**Issue by severinsimmler** [python-poetry/poetry#1391] opened 2019-09-19 17:55 UTC
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

Using:
- Python 3.7.3
- Poetry 1.0.0b1

## Feature Request
Because the CPU version of PyTorch is not on PyPI, they recommend installing it this way:
```
pip install torch==1.2.0+cpu --find-links https://download.pytorch.org/whl/torch_stable.html
```
However, there is no way to do this with Poetry?

Pointing directly to the wheel:

```
poetry add https://download.pytorch.org/whl/cpu/torch-1.2.0%2Bcpu-cp36-cp36m-manylinux1_x86_64.whl
```

results in 

```
Updating dependencies
Resolving dependencies... (2.0s)


Package operations: 1 install, 0 updates, 0 removals

  - Installing torch (1.2.0+cpu https://download.pytorch.org/whl/cpu/torch-1.2.0%2Bcpu-cp36-cp36m-manylinux1_x86_64.whl)

[EnvCommandError]
Command ['/home/simmler/.cache/pypoetry/virtualenvs/epss-WeFenOJ_-py3.7/bin/python', '-m', 'pip', 'install', '--no-deps', 'torch==1.2.0+cpu'] errored with the following return code 1, and output: 
Collecting torch==1.2.0+cpu
  Could not find a version that satisfies the requirement torch==1.2.0+cpu (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2, 0.4.1, 0.4.1.post2, 1.0.0, 1.0.1, 1.0.1.post2, 1.1.0, 1.2.0)
No matching distribution found for torch==1.2.0+cpu
```

And adding `https://download.pytorch.org/whl/torch_stable.html` as a repository to the `pyproject.toml` does not work, because it (the PyTorch wheel index page) is not PEP conform.

**Comment by cc-a** [comment] 2019-10-20 20:58
Hi. I was thinking of having a go at this for Hacktoberfest.

The approach I was thinking of:
- Implement a variation of the LegacyRepository class
- Extend the expected fields for the source toml section to add a flag that specifies this type of simple html repository
- Implement the relevant logic in poetry.py to determine the correct repository class to use

Sound about right?

**Comment by severinsimmler** [comment] 2019-10-23 13:38
Sounds like a plan :+1:

**Comment by woodlandhunter** [comment] 2019-10-25 01:37
@cc-a a `--find-links` that is equivalent to `pip`'s would also accept file paths (a directory). See pip docs [here](https://pip.pypa.io/en/stable/user_guide/#installing-from-local-packages). We could really use this. It's also mentioned in these issues:

#558 
#1289 

Your comment doesn't mention this scenario, would `--find-links=DIR` be covered by what you are working on?

**Comment by cc-a** [comment] 2019-10-25 11:30
I'll have a crack at it, probably in a second PR. In principle the same logic should be required just working with file paths instead of urls.

**Comment by golyalpha** [comment] 2019-12-22 11:29
Right now the workaround is defining remote file dependencies (in pytorch's case, platform specific).
This works for me on the current release:
```
poetry add https://download.pytorch.org/whl/cu101/torch-1.3.1-cp37-cp37m-win_amd64.whl --platform win32
```

Ideally, you would do this for every platform.

**Comment by germn** [comment] 2020-01-11 00:06
After installing torch with

    poetry add https://download.pytorch.org/whl/cu101/torch-1.3.1-cp37-cp37m-win_amd64.whl

each time I add any package poetry does following:

    - Updating torch (1.3.1 -> 1.3.1 https://download.pytorch.org/whl/cu101/torch-1.3.1-cp37-cp37m-win_amd64.whl)

It doesn't break anything, but takes some time.

Anyone knows a way to avoid "updating"?

**Comment by golyalpha** [comment] 2020-01-11 10:31
Not really, but you could probably limit the impact by using a local cache (like devpi) @germn

**Comment by allen-chin** [comment] 2020-02-04 01:16
@germn Something like below should work fine for your case.
`pyspark = {file = "pyspark-3.0.0.dev0.tar.gz"}`

**Comment by golyalpha** [comment] 2020-02-04 07:33
@allen-chin The sideeffect of that is continual reinstallations of the package. Just because the package is local, doesn't mean it Poetry won't reinstall it.

**Comment by cpbotha** [comment] 2020-03-17 15:31
I created a valid simple index that can be used with index-url and as a `tool.poetry.source` for all of the pytorch.org official packages. You can find the new index here: https://vxlabs.com/pypi/

I massaged the official PyTorch find-urls file to look more like a PEP 503 compatible simple index, but it's still pointing to all of the official packages at pytorch.org.

It's currently working like a charm in my poetry setup.

**Comment by aviramha** [comment] 2020-05-26 14:42
@cpbotha Plan on adding 1.5.0 soon?
BTW Any news on this issue?

**Comment by cpbotha** [comment] 2020-05-27 08:22
Currently swamped, have not had time to get back to this and probably won't for the coming weeks. 

There's also the issue on pytorch's side to make available the right sort of index for their packages, but no-one has had  time yet to dive in.

**Comment by timorkal** [comment] 2020-06-23 11:41
@cpbotha great job, but I have an issue when I am using your source with poetry when trying to lock.
pyproject.toml:
torch = "1.3.1+cpu"
torchvision = "0.4.2+cpu"

[SolverProblemError]
Because torchvision (0.4.2+cpu) depends on torch (1.3.1)
 and package depends on torch (1.3.1+cpu), torchvision is forbidden.
So, because package on torchvision (0.4.2+cpu), version solving failed.

**Comment by lironmo** [comment] 2020-06-28 08:04
same issue here.

**Comment by daniel-j-h** [comment] 2020-07-06 14:35
The same is true for the latest stable pytorch and torchvision packages.

The officially recommended way is

    pip install torch==1.5.1+cpu torchvision==0.6.1+cpu -f https://download.pytorch.org/whl/torch_stable.html

but without an equivalent to the `-f` option in poetry we can only add the wheels manually.

But adding the wheels manually fails because the solver thinks `(1.5.1)` != `(1.5.1+cpu url)`


```bash
$ poetry add --platform linux https://download.pytorch.org/whl/cpu/torchvision-0.6.1%2Bcpu-cp38-cp38-linux_x86_64.whl https://download.pytorch.org/whl/cpu/torch-1.5.1%2Bcpu-cp38-cp38-linux_x86_64.whl
Skipping virtualenv creation, as specified in config file.

Updating dependencies
Resolving dependencies... (36.4s)

[SolverProblemError]
Because myproject depends on torchvision (0.6.1+cpu url) which depends on torch (1.5.1), torch is required.
So, because myproject depends on torch (1.5.1+cpu url), version solving failed.
```

Should we split this into a new issue separate from the `-f` issue, though?

And adding here, what's the recommended way to install pytorch and torchvision with poetry now? If it's not possible (other than going through some 3rd party index as described above) that would be quite unfortunate.

**Comment by severinsimmler** [comment] 2020-07-06 15:00
Most of us only have this problem because of PyTorch, right? To be honest, since I opened this issue I no longer see the problem here with Poetry, but with PyTorch. Why the hell isn't a big project like PyTorch published on a PEP-conform index? I opened an issue (https://github.com/pytorch/pytorch/issues/26340) some time ago -- so far without any concrete reaction.

I actually like the strict policy of Poetry. PEP exists for a reason.

**Comment by kousu** [comment] 2020-08-15 02:03
@severinsimmler I'm having the same issue (https://github.com/neuropoly/spinalcordtoolbox/issues/1526#issuecomment-674330466). Thanks a lot for trying to get the ball rolling with pytorch!

Poetry should stick close to the core pypa specs, and they want to kill `--find-links` and `dependency_links` in favour of https://www.python.org/dev/peps/pep-0508/#environment-markers (https://github.com/pypa/pip/issues/6162, https://github.com/pypa/pip/issues/4187). But PEP 508's URL mode doesn't cover wheels with compiled platform-specific versions :/ so we're stuck from both sides.

But if pytorch got themselves together and published to pypi this would be a non-issue.

**Comment by Jefffish09** [comment] 2020-09-11 04:06
Same problem.
I tried to install pytorch and torchvision with local .whl files via these command:
```
poetry add ./torch-1.6.0+cpu-cp38-cp38-linux_x86_64.whl
poetry add ./torchvision-0.7.0+cpu-cp38-cp38-linux_x86_64.whl
```

When I install pytorch, it was successful.
But when install torchvision,it showed below:
```
[SolverProblemError]
Because torchvision (0.7.0+cpu) depends on torch (1.6.0) and machinelearning depends on torch (1.6.0+cpu /torch-1.6.0+cpu-cp38-cp38-linux_x86_64.whl), torchvision is forbidden. So, because machinelearning depends on torchvision (0.7.0+cpu /torchvision-0.7.0+cpu-cp38-cp38-linux_x86_64.whl), version solving failed.
```
How can I solve this?

**Comment by Korijn** [comment] 2020-09-12 09:21
> The same is true for the latest stable pytorch and torchvision packages.
> 
> The officially recommended way is
> 
> ```
> pip install torch==1.5.1+cpu torchvision==0.6.1+cpu -f https://download.pytorch.org/whl/torch_stable.html
> ```
> 
> but without an equivalent to the `-f` option in poetry we can only add the wheels manually.
> 
> But adding the wheels manually fails because the solver thinks `(1.5.1)` != `(1.5.1+cpu url)`
> 
> ```shell
> $ poetry add --platform linux https://download.pytorch.org/whl/cpu/torchvision-0.6.1%2Bcpu-cp38-cp38-linux_x86_64.whl https://download.pytorch.org/whl/cpu/torch-1.5.1%2Bcpu-cp38-cp38-linux_x86_64.whl
> Skipping virtualenv creation, as specified in config file.
> 
> Updating dependencies
> Resolving dependencies... (36.4s)
> 
> [SolverProblemError]
> Because myproject depends on torchvision (0.6.1+cpu url) which depends on torch (1.5.1), torch is required.
> So, because myproject depends on torch (1.5.1+cpu url), version solving failed.
> ```
> 
> Should we split this into a new issue separate from the `-f` issue, though?
> 
> And adding here, what's the recommended way to install pytorch and torchvision with poetry now? If it's not possible (other than going through some 3rd party index as described above) that would be quite unfortunate.

See https://github.com/python-poetry/poetry/issues/2543

**Comment by golyalpha** [comment] 2020-09-16 16:18
@Korijn The pytorch team is packaging their modules properly, and they publish what they can on PyPI. The issue is, that PyPI (understandably) doesn't provide them with enough storage space to upload *all* versions of their module, and so they had to resort to publishing them themselves.

The unfortunate truth is, that hosting an html file with links is easier than an actual package index, and the PyTorch team should not be forced to host their own package index, even if only for their own packages, if PyPI simply refuses to support them - that is a dangerous precedent to be set, regardless of who is the maintainer of the affected package.

**Comment by Korijn** [comment] 2020-09-16 16:32
> @Korijn The pytorch team is packaging their modules properly, and they publish what they can on PyPI. The issue is, that PyPI (understandably) doesn't provide them with enough storage space to upload _all_ versions of their module, and so they had to resort to publishing them themselves.
> 
> The unfortunate truth is, that hosting an html file with links is easier than an actual package index, and the PyTorch team should not be forced to host their own package index, even if only for their own packages, if PyPI simply refuses to support them - that is a dangerous precedent to be set, regardless of who is the maintainer of the affected package.

Fair enough, I have not digged deep enough to uncover this root cause. Apologies for my tone.

I do think that it's odd that hosting your own index is apparently too hard for such a project. Aren't there tons of such tools available to do that?

**Comment by golyalpha** [comment] 2020-09-19 09:36
@Korijn I was saying that hosting an index is harder than hosting a static HTML file. Not in terms of setting it up (though it could be potentially harder to set up a package index than a static file host), but in terms of actually running it (expense, etc.)

**Comment by Korijn** [comment] 2020-09-19 10:12
> @Korijn I was saying that hosting an index is harder than hosting a static HTML file. Not in terms of setting it up (though it could be potentially harder to set up a package index than a static file host), but in terms of actually running it (expense, etc.)

Yes, well, I guess I was also not clear enough. One can also host a static HTML site that meets the [PEP 503 format](https://www.python.org/dev/peps/pep-0503/). That also allows it to be included as an index in project.toml.

**Comment by golyalpha** [comment] 2020-09-19 10:18
Well, if the guys at PyTorch manage to figure it out, that's good. Poetry still probably should support the feature from pip.

**Comment by RafalSkolasinski** [comment] 2020-09-20 14:27
Hey guys, I read this thread (and the https://github.com/pytorch/pytorch/issues/26340) and I just to make sure I didn't miss any workaround - do I understand it right that currently there is no way of including cpu version of torch into poetry pyproject.toml?

**Comment by Korijn** [comment] 2020-09-20 15:46
> Hey guys, I read this thread (and the [pytorch/pytorch#26340](https://github.com/pytorch/pytorch/issues/26340)) and I just to make sure I didn't miss any workaround - do I understand it right that currently there is no way of including cpu version of torch into poetry's pyproject.toml?

If it's _just_ torch (and not also vision), you can if you set up a PEP 503 compatible index with the package on it. There's a public one hacked together by @cpbotha you can use.

**Comment by sinoroc** [comment] 2020-11-17 13:00
I will add this as a potential workaround:
* https://github.com/uranusjr/simpleindex/issues/2

It does not seem to be a valid workaround, yet. It might be that there is an [issue with _URL redirections_ in _poetry_](https://github.com/python-poetry/poetry/pull/3198), so that the workaround fails for now.

**Comment by espdev** [comment] 2020-11-21 16:27
Any news on [the PR](https://github.com/python-poetry/poetry/pull/1511)?

For example, I need to use numpy+mkl on Windows 10 2004 Update because of this [issue](https://github.com/numpy/numpy/issues/16744). I can download whl from [gohlke web page](https://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy) only manually. And it would be nice to use `--find-links` and the local wheelhouse directory for searching wheel-packages instead of remote wheelhouse:

Something like this:

```
[tool.poetry.dependencies]
python = "^3.7"
numpy = { version = "^1.19.4+mkl", markers = "sys_platform == 'win32'" }
pandas = "^1.1.4"

[[tool.poetry.source]]
name = "numpy"
url = "wheels/"  # relative path to local directory with wheel files
find_links = true
```

**Comment by timothyjlaurent** [comment] 2021-02-03 03:45
@Korijn's solution is good but it has become outdated. 
https://eternalphane.github.io/pytorch-pypi/ seems to be up to date though.

**Comment by jhrmnn** [comment] 2021-05-21 10:46
Just linking to a related issue: #2613

**Comment by Nathan-Furnal** [comment] 2021-12-18 15:16
Hi! Is there any news on this issue?

**Comment by Sbozzolo** [comment] 2022-02-22 16:15
I stumbled upon this issue because vtk does not provide wheels for Python 3.10, but unofficial ones exist: https://github.com/pyvista/pyvista/discussions/2064

**Comment by ColdTeapot273K** [comment] 2022-05-03 19:54
Same problem when trying to install [JAX](https://github.com/google/jax) via 
```bash
pip install --upgrade "jax[cuda]" -f https://storage.googleapis.com/jax-releases/jax_releases.html  # Note: wheels only available on linux.

```

Currently I've resorted to:
```bash
poetry run pip install --upgrade "jax[cuda]" -f https://storage.googleapis.com/jax-releases/jax_releases.html    
```

Which effectively excludes JAX and its deps from tracking (i.e. they're not in poetry.lock)
Which in turn results in overwriting them with poetry-accessible dependencies once i try to install something that depends on them, i.e.:
```bash
> poetry add flax
...
Updating jaxlib (0.3.7+cuda11.cudnn82 -> 0.3.7) # "jax[cuda]" install gets overwritten effectively into "jax[cpu]"
...
Installing flax (0.4.1)
```

**Comment by mkniewallner** [comment] 2022-06-17 19:55
Closing, since it is now implemented in the next release of Poetry, 1.2, but if you still encounter any issue, feel free to reopen.

**Closed by mkniewallner** 2022-06-17 19:55 UTC
Labels: Feature, Awaiting Reponse

**Comment by mboisson** [comment] 2023-06-28 20:07
--find-links accepts a directory path, not a single-page index. A single-page index supposes running a web server. This is not equivalent.

**Comment by rashidnhm** [comment] 2023-11-08 19:46
We are running in an environment (out of control), where the packages are spread across different local directories. Pip was configured with --find-links to search across all the directories when installing a package, however, it does not seem like poetry is able to do the same.
