### ISSUE TITLE
Automatically installing beta releases

### ISSUE THREAD

**Issue by romanzdk** [python-poetry/poetry#8845] opened 2024-01-04 08:43 UTC
- **Poetry version**: 1.7.1
- **Python version**: 3.10.13
- **OS version and name**: Debian GNU/Linux 12 (bookworm)
- **pyproject.toml**: 
```toml
...
[tool.poetry.dependencies]
python = "^3.10"
safety = "^2.3.5"
...
```

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a [recommended method](https://python-poetry.org/docs/#installation).
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
The latest stable version of safety on pypi is 2.3.5, however with `^2.3.5` poetry still installs `2.4.0b2` which is not desired.

**Comment by dimbleby** [comment] 2024-01-04 12:20
does not reproduce, please either provide a way to reproduce or close this

**Comment by abn** [comment] 2024-03-02 09:34
Closing as no response from the author for couple of months now. 

And given this cannot be reproduced with information provided, please raise a new issue with relevant details if the issue is still a concern.

**Closed by abn** 2024-03-02 09:34 UTC
Labels: kind/bug, status/waiting-on-response, status/needs-reproduction
