### ISSUE TITLE
Dependencies in group.dev.dependencies are removed

### ISSUE THREAD

**Issue by Spenhouet** [python-poetry/poetry#4769] opened 2021-11-15 19:34 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 20.04.3 LTS
- **Poetry version**: 1.2.0a2
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: [](https://gist.github.com/Spenhouet/c049651e53250455aad361b8e9aa68c8)

## Issue

When I install dev dependencies via VSCodes UI (dialog asking if I want to install a linter) or via `poetry add yapf --group dev` these dependencies will get installed to `[tool.poetry.group.dev.dependencies]` but these seem to be ignored. They are removed again everytime and therefore linting, ... does not work.
Only dev dependencies in `[tool.poetry.dev-dependencies]` are actually installed.

**Comment by finswimmer** [comment] 2021-11-16 05:42
Hello @Spenhouet,

it's not obvious to me how to reproduce. What do you mean by "They are removed again everytime "? When they get removed? Please show your `pyproject.toml` before and after running `poetry add`. What is the console output?

fin swimmer

**Comment by finswimmer** [comment] 2021-12-17 08:19
I'm closing this because we haven't receive no more information for a long time now.

Feel free to leave a comment if you disagree.

**Closed by finswimmer** 2021-12-17 08:19 UTC
Labels: Bug, Triage, Awaiting Reponse
