### ISSUE TITLE
poetry run causes [FileNotFoundError] with some scripts

### ISSUE THREAD

**Issue by huwper** [python-poetry/poetry#2481] opened 2020-06-02 09:38 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10 Enterprise
- **Poetry version**: Poetry version 1.0.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/huwper/efb95344f986939bf4fd717fbeb64a91

## Issue

Using poetry run to run scripts fails on some scripts. I think this is probably in cases where the script has no file extension. The linked pyproject.toml installs scons into the virtual environment. Scons  comes with a script called `scons` which is installed in the `Scripts` directory. The following error occurs when running the script:

```
c:\Projects\personal\poetry-scons-issue>poetry run scons

[FileNotFoundError]
[WinError 2] The system cannot find the file specified
```

Running `poetry venv info` to get path/to/venv and running scons with the explicit path works fine

```
> path\to\venv\Scripts\scons

scons: *** No SConstruct file found.
......
```

scons also comes with a script called `scons.bat` which does the same thing. `poetry run scons.bat` does work

**Comment by jonapich** [comment] 2020-11-10 19:30
Same problem here, slightly different setup:

- Project B defines a script called `genall`
- Project A has a `path` dependency to Project B
- I can run `poetry run genall` in Project B
- I cannot in project A (FileNotFoundError)
- In Project A's virtual env, in the Scripts folder, there are 2 files: `genall` and a `genall.cmd`

**Comment by jonapich** [comment] 2020-11-10 19:49
I tried a workaround, but it didn't work. The result is weird so I'm sharing it:

- Added a `poetry.scripts` section to Project A, a copy of the one in Project B
- Recreated the virtual environment from scratch
- Tried to launch `poetry run genall` from Project A again:

```
PS C:\...> poetry run genall

  FileNotFoundError

  [WinError 2] The system cannot find the file specified

  at ~\AppData\Local\Programs\Python\Python38\lib\subprocess.py:1307 in _execute_child
      1303│             sys.audit("subprocess.Popen", executable, args, cwd, env)
      1304│
      1305│             # Start the process
      1306│             try:
    → 1307│                 hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
      1308│                                          # no special security
      1309│                                          None, None,
      1310│                                          int(not close_fds),
      1311│                                          creationflags,


```

**Comment by finswimmer** [comment] 2020-11-13 05:50
@jonapich can you please share your `pyproject.toml` files and the project structure? This would help a lot for finding out what's going on. Thanks a lot!

fin swimmer

**Comment by huwper** [comment] 2020-11-18 13:07
My issue seems to be because poetry searches for .exe files, whereas windows can happily execute anything with an extension from PATHEXT, here was my hacky workaround. 

https://github.com/python-poetry/poetry/compare/master...huwper:master

**Comment by sinoroc** [comment] 2020-11-18 13:34
@huwper Looks like a good find.

_[Aside: Why does poetry put itself in the way here? Why does poetry need to check that the (executable) file exists, or whatever it is that it does there?]_

**Comment by sinoroc** [comment] 2020-11-21 07:30
What looks like a related PR has been opened here: https://github.com/python-poetry/poetry/pull/3395

**Comment by kevincon** [comment] 2020-11-22 00:12
I think this is also a duplicate of #3265 which I have this PR up to fix: #3339

**Comment by sinoroc** [comment] 2020-11-22 10:48
This looks like the oldest report of the issue. So maybe close the other ones and let's keep the discussion going here.

@kevincon @huwper @andschwa Do you agree these are the same issue or are closely related enough issues? Can you collaborate on a fix? Maybe start by testing each other's pull requests to see if they are also fixing your own use case, and review each other's code.

**Comment by andschwa** [comment] 2020-11-24 02:39
@sinoroc Yes, I think these are all the same issue. I have a question: what's then intention behind `env.py`'s `_bin(bin)` method? I _inferred_ that it's to check Poetry's virtualenv _first_ (that's what the code sure is doing by looking at `self._bin_dir / bin` first, and only falling back to `bin` if nothing was found in `self._bin_dir`). If this is indeed the case, that lends credence to my recommendation I made here: https://github.com/python-poetry/poetry/pull/3395#issuecomment-732546336

@kevincon @huwper Can you both take a look and confirm? I definitely borrowed from both your PR's and am happy to go change the authorship. In fact, let me go do that! This was definitely a joint effort.

**Closed** 2022-06-04 07:06 UTC
Labels: Bug, Good First Issue, Triage
