### ISSUE TITLE
- [extras.pipfile_deprecated_finder.2] 'pip-shims<=0.3.4' does not match '^[a-zA-Z-_.0-9]+$'

### ISSUE THREAD

**Issue by AtitBimali** [python-poetry/poetry#7426] opened 2023-01-28 17:28 UTC
- [extras.pipfile_deprecated_finder.2] 'pip-shims<=0.3.4' does not match '^[a-zA-Z-_.0-9]+$'

pre-commit log : https://pastebin.com/9mtszQdP

**Comment by dimbleby** [comment] 2023-01-28 18:26
You've failed to follow the issue template, which makes it hard to help you.

But I expect something is wrong in your pyproject.toml, the error message is telling you where the error is, there is no poetry bug

**Comment by dimbleby** [comment] 2023-01-28 20:41
I guess this was a duplicate of https://github.com/PyCQA/isort/issues/2077 (which, I see, you duplicated again at https://github.com/PyCQA/isort/issues/2079)

**Comment by neersighted** [comment] 2023-01-28 21:28
Closing as this is an external issue, it appears that isort has a misspecified extra that was not detected until poetry#7226 was solved.

**Closed by neersighted** 2023-01-28 21:28 UTC
Labels: kind/bug, status/triage

**Comment by MyLinhRP** [comment] 2023-02-01 09:42
you can run 

pip install poetry -U

and try again

**Comment by javiermarcon** [comment] 2023-09-29 13:43
pre-commit autoupdate solved the problem
