### ISSUE TITLE
Standard project structure not specified or not easily findable

### ISSUE THREAD

**Issue by sandrinr** [python-poetry/poetry#2252] opened 2020-04-01 09:27 UTC
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

When Poetry is unable to determine the packages of the current project (folder). It prints an error such as:
```
[ModuleOrPackageNotFound]
No file/folder found for package <package>
```

When a user then tries to find something about this error on the web he will find some closed issues talking about the `packages` portion of the `pyproject.toml`. There and in some other locations (e.g. GitHub) you can find "If your project structure differs from the standard one supported by poetry...". However, it is not defined (or will not pop up in search results) defined, as far as I can see, what exactly this standard structure might be.

By looking at https://python-poetry.org/docs/basic-usage/ one might guess what it could be.

**Comment by GabrielSimonetto** [comment] 2020-10-17 18:18
Could you tell us what an example of this error would be? By looking on the website it seems to me it's somehow defined for most cases

```
poetry-demo
├── pyproject.toml
├── README.rst
├── poetry_demo
│   └── __init__.py
└── tests
    ├── __init__.py
    └── test_poetry_demo.py
```

By searching [issues with this error](https://github.com/python-poetry/poetry/issues?q=is%3Aissue+ModuleOrPackageNotFound), it seems to me there is no single answer as to how to define this structure, since most issues have been solved by some ad hoc knowledge

**Comment by GabrielSimonetto** [comment] 2020-10-17 18:18
@python-poetry/triage

**Comment by abn** [comment] 2020-10-17 19:58
The standard structure being referred to is the structure where the project's root package is in the same directory as the `pyproject.toml` file (project root).

By default, if [`tool.poetry.packages`](https://python-poetry.org/docs/pyproject/#packages) is not defined, poetry will attempt to look for [`module_name(tool.poetry.name)`](https://python-poetry.org/docs/pyproject/#name). If this is not found the error is raised. 

This typically happens when `poetry init` was used to create the `pyproject.toml` (or it was created manually) and the package name does not match expected derived package name from project name; or the existing project uses `src` layout without specifying `packages`.

**Comment by finswimmer** [comment] 2020-10-18 06:19
I guess @GabrielSimonetto's main point is, that it is not stated clearly in the docs  how poetry detects the package and this should be improved. PR is always welcome :)

**Comment by HallerPatrick** [comment] 2020-10-25 19:23
Made a pull request, which should provide sufficient information in the docs

**Comment by woolinsilver-kainos** [comment] 2020-11-11 14:15
This stuff is non-obvious and very confusing IMHO.
Poetry should concern itself with managing _projects_, not _packages_.

The name of the directory containing `pyproject.toml` should (reasonably) be the _project_ name.
The directory name should not influence Poetry.

The field `tool.poetry.name` has no clearly defined purpose.
It **should** be the name of the project: it's in a file which describes the attributes of the project, and it's consumed by a tool which builds projects.
However...

There is some bizarre assumption that it is also the name of the root _package_.
When running `poetry init`, it asks for the "`Package name`", and pre-populates with the parent directory name.
This is extremely confusing.
Projects and packages have different naming conventions in Python, and must be allowed to diverge.

There are multiple occasions where poetry takes `tool.poetry.name` and apparently **transforms** it (!?), e.g. 
- transforming underscores to hyphens, when creating virtual environments,
- transforming hyphens to underscores, when trying to guess the root package.

If you run `python build`, you get one tarball artifact with hyphens, and a separate wheel artifact with underscores... god only knows what's going on there, or why.

It's not clear why Poetry even cares about packages at all.
Compare with Maven, which works very well:
- `pom.xml` completely describes the project
- source code (for arbitrary Java packages) is found under `src/main` and `src/test`
Maven manages projects, Java manages packages.
No confusion, no guesswork.
 
I thought the point of Poetry was to fix the horrible mess of Python packaging, but all that's happened is we now have yet another packaging tool, which has introduced yet more confusion and mess.

**Comment by finswimmer** [comment] 2020-11-11 17:17
Hello @woolinsilver-kainos,

> Poetry should concern itself with managing projects, not packages.

the aim of poetry is to manage python packaging projects.

> The name of the directory containing pyproject.toml should (reasonably) be the project name.

It is, so what's your point here?

> The directory name should not influence Poetry.

About which directory you are talking exactly?

> It should be the name of the project: it's in a file which describes the attributes of the project, and it's consumed by a tool which builds projects.

That's exactly how it works.

> When running poetry init, it asks for the "Package name", and pre-populates with the parent directory name.

The aim of poetry is to manage python packaging projects. So it's correct that the project has the same name as the package and therefor the project folder has the same name as the project's name.

> Projects and packages have different naming conventions in Python, and must be allowed to diverge.

IMO we should talk about three different things here: The name of the project itself, the name of the python package you want to build within this project and the folder name that holds the package code.

It is recommended to have only one package per project, so we can assume project name == package name. You can have multiple packages per project with poetry as well via the [packages](https://python-poetry.org/docs/pyproject/#packages) keyword. But this is out of scope of the `poetry new` command and you have to do it manually.

Let's come to the folder name that holds the package code itself. In python, the names in your import statements cannot contain a hyphen. That's why folder, that contain the package code, uses underscores instead. On the other hand it's a convention that the package name itself uses hyphens instead of underscores. poetry respects that when autogenerate the folders with a `poetry new`.

> transforming underscores to hyphens, when creating virtual environments,

Ok, something that is discussible.

> transforming hyphens to underscores, when trying to guess the root package.

See above.

> If you run python build, you get one tarball artifact with hyphens, and a separate wheel artifact with underscores... god only knows what's going on there, or why.

Theres a different for sdist and wheel packages. There is no PEP for sdist. So the package name is used in the filename however the package is called. For wheel PEP 491 exists. And this PEP defines that ["Each component of the filename is escaped by replacing runs of non-alphanumeric characters with an underscore _"](https://www.python.org/dev/peps/pep-0491/#escaping-and-unicode)

> It's not clear why Poetry even cares about packages at all.

That's the reason why poetry exists.

fin swimmer

**Comment by egnor** [comment] 2020-12-21 17:45
For a project like this, clear documentation is almost as important as working functionality. Documentation that says "If your project structure differs from the standard one supported by poetry" without ever once explaining the "standard one supported by poetry" seems like clearly buggy documentation. (Very much understood that bugs and work need prioritizing and not everything can be fixed right away, but the first step is for us all to realize that this is a bug as serious as a code bug.)

I feel like there used to be a page explaining the project layouts supported by Poetry. Am I imagining things?

My current understanding is:

 * A single Poetry _project_ (pyproject.toml file) describes ONE _package manager package_ (file to upload to pypi, etc), which may contain one or more _Python packages_ (importable directories of code). If you want to build more than one _package manager package_ as part of a project, you will need multiple pyproject.toml files, which need to be in different directories.
 * By default, Poetry assumes that one _package manager package_ contains one _Python package_ (and possibly subpackages) with the same name as the package manager package, as is conventional but not universal. (There's some name mangling that happens here. I agree that is Not Cool especially if undocumented.)
 * For such conventional packages, Poetry uses default algorithms to try to autodetect where the Python package's code lives (in package_name/..., or src/package_name/..., or ???)
 * When the assumption above is not true, the tool.poetry.packages value in pyproject.yaml describes where Python files live and how they should be arranged inside the package manager package, thus defining the Python package(s) assembled there.
 * In any case, "poetry install" will effectively assemble the package manager package (as guessed or described explicitly) and install it in the virtualenv. (No actual package file is created; the source files are linked into the virtualenv in "editable mode", so edits in the source tree take immediate effect.)

In my humble opinion, this all makes reasonable sense, but is very badly underdocumented, leading to confusion and anger:

 * The relationship between package manager packages, Python packages, and Python modules is never made clear; the word "package" is often used in an ambiguous and confusing way.
 * The default algorithms used to guess and detect how source files are laid out are completely undescribed. The impact of the "--src" flag to "poetry new" is underdescribed. The related choices made in "poetry init" are underdescribed.
 * The exact specification and semantics of tool.poetry.packages value is undescribed. A couple examples are given but it is not clear exactly what the full range is and what effect it has.

I'm heartened that @HallerPatrick has started a PR, though it only takes a little nibble at this issue and also seems stalled.

**Comment by sinoroc** [comment] 2020-12-21 17:50
***Aside***:
In case that helps anyone, I try to gather general Python packaging terms (not _poetry_-specific) here: https://sinoroc.gitlab.io/kb/python/packaging.html

**Comment by egnor** [comment] 2020-12-21 17:51
@sinoroc - thank you! Edited my comment above to conform to that terminology ("distribution package" and "import package", etc).

**Comment by sinoroc** [comment] 2020-12-21 17:57
Some more bits that are general to the whole Python packaging ecosystem (which is mostly under ***loose*** control of the _PyPA_ group) are defined here: https://packaging.python.org/specifications/

Indeed it might be difficult to see where the line is between things that are general (_PyPA_) standards and the things that are unique to _poetry_.

**Comment by philippefutureboy** [comment] 2021-01-13 20:00
Hey there!

As someone from the JS ecosystem who is looking for a proper dependency management tool, I must concur with the comments brought by @woolinsilver-kainos and @egnor.

Python seems to be a decade behind when it comes to dependency management & project management, and I hoped to find something reasonable in either Pipenv or poetry.

To my dismay, Pipenv seems to be dying and poetry enforces undocumented file structure, which makes it a questionable migration target from a complex project using classic requirements.txt + setup.py.

So I must concur, either the documentation should be clear about the author(s)' intention to make this dependency management tool a package-only dependency management tool or it should support both projects and packages.
Once again, as someone coming from the JS ecosystem, I really don't understand how the most popular language on the web hasn't figure its dependency management in a sane way yet (especially since the language is older than JS).

Thanks!
Cheers,
Philippe

**Comment by dimaqq** [comment] 2021-01-21 09:15
As a practical/actionable item, would it be all right to include @GabrielSimonetto 's project structure outline somewhere in the poetry docs?
(I guess there should be a section for "new Python project with poetry" as opposed to "migrating legacy Python project to poetry", but I can't seem to find those_

> ```
> poetry-demo
> ├── pyproject.toml
> ├── README.rst
> ├── poetry_demo
> │   └── __init__.py
> └── tests
>     ├── __init__.py
>     └── test_poetry_demo.py
> ```

Something very similar is stated in: https://hackersandslackers.com/python-poetry-package-manager/

**Comment by aantn** [comment] 2021-07-06 12:55
As a user who loves poetry but is often confused by the docs, I totally agree with the above comments.

**Comment by nothead31** [comment] 2021-07-22 18:00
@egnor 's comment above is on point with the issue at hand, and gives a good explanation of what is wrong. What I think should be done to fix the documentation is to include a section within the ['Basic Usage'](https://python-poetry.org/docs/basic-usage/) section that explicitly outlines the intended folder structure for the package, even if that is redundant with other documentation. 

This means briefly explaining the distinction between package vs. project, breaking down where *exactly* key files should be in relation to eachother (ie, "your entry point should be in a package folder directly underneath where pyproject.toml is located"), and more clearly reference the documentation in itself (ie, the "Basic Usage" chapter mentions pyproject.toml, but it is not a link, leaving the user to navigate through documentation manually. This is bad practice.) Furthermore, within the [pyproject.toml](https://python-poetry.org/docs/pyproject/).

The reason for the redundancy and clarifications is that the tone of the documentation assumes a certain degree of pre-existing knowledge of python packaging that just doesn't exist in the community. As others have stated, packaging in python is notoriously obtuse, poorly-documented, and complex, and the PEPs themselves don't provide enough documentation to either establish best practice or even a competent baseline understanding of the process. In addition to that, documentation that assumes advanced prior knowledge is just plain bad documentation.

This aspect of documentation shows an area where it just is not explicit enough and not every user of poetry has the time to investigate the source files to find a solution to what should be a simple problem.

In my personal experience, I cannot get my program to run because I keep getting `ModuleNotFoundError` which is directly caused by me not being able to figure out how exactly Poetry wants tool.poetry.packages and tool.poetry.scripts to be formatted. Yes, the syntax is there, but there is no documentation in **any** resource, poetry or Python itself which explains "tool.poetry.packages expects your entry point to be in this particular folder relative to pyproject.toml" or "tool.poetry.scripts looks through the listed packages in this manner to find the entry point you declared".

Finally, there is one more addition that could improve this problem: `poetry check` could be improved by testing the declared scripts entry point for ModuleNotFoundError, and return a warning that the entry point may not work.

**Comment by sonotley** [comment] 2021-09-23 13:03
Agree that @egnor is on point, a very useful reply summarising both the issue(s) and the current behaviour. I'd be happy to work on the docs, but I don't know the behaviour well enough to document it (chicken and egg!). 

I totally agree making the docs clearer would alleviate a lot of this, but perhaps Poetry is simply trying to be too clever in some cases. Do we really need it to guess the project structure from the name? Perhaps this is convenient, but it is also opaque. 

As a minimum I'd suggest that the results of the guesswork are written to the pyproject.toml file in the [packages](https://python-poetry.org/docs/pyproject/#packages) section, then it would be transparent and editable. It would also mean this section of pyproject.toml could be mandatory which could be helpful for other tools that need to know what packages are part of the project.

**Comment by AdamJel** [comment] 2021-09-24 11:55
I absolutely agree with @sonotley @nothead31 @egnor that documentation needs to be worked on. I will not repeat great arguments already mentioned here, but I will provide a few examples, where the documentation is indeed plain bad.

#### difference between dependencies and dev.dependencies
[here in documentation](https://python-poetry.org/docs/pyproject#dependencies-and-dev-dependencies) is section with name "dependencies and dev-dependencies". One would (I did) expect this section to provide some information about the difference between dependencies and dev dependencies. Yet, it only talks abou repository source and that it may be other then pypi. For me, this is totally unrelated information to the heading.

#### list object in toml
In the same section, there is a code example on how to add repository source. The code is this:
```
[[tool.poetry.source]]
...
```
While the line is in double brackets, I did not notice it and wrote it with just single ones like this:
```
[tool.poetry.source]
```
which resulted in error. Nowhere in the documentation is described, what and why is the proper structure of toml file. Usage of double `[[` and `]]` is just confusing (and inconsistent with the rest of toml file (this may be the only line with double brackets)).

#### undocumented tool.poetry.packages
Searching the documentation for `tool.poetry.packages` returns nothing. The documentation does not mention this at all. It does however mention the other option how to include packages [here](https://python-poetry.org/docs/pyproject/#packages). So, there are 2 ways how to mention packages:
```
[tool.poetry]
# ...
packages = [
    { include = "my_package" },
    { include = "my_other_package", format = "sdist" },
]
```

and
```
[[tool.poetry.packages]]
include = "druhypackage"
```
And notice, that it once again has to be in double brackets.

But the second option is not mentioned at all. And the first option is totally inconsistend with the rest of the documentation. E.g. scripts are described like this (why not in double brackets??): 
```
[tool.poetry.scripts]
poetry = 'poetry.console:run'
```

Also, what about trailing commas in python project/package?
```
packages = [
    { include = "my_package" },
    { include = "my_other_package", format = "sdist" },
]
```

#### brackets inconsistency
So, when I will define both, scripts and packages, the toml file will look like this:
```
[[tool.poetry.packages]]
...

but
[tool.poetry.scripts]
```
Inconsisten. It may be correct, but I lack the explonation why.

#### scripts
This [section](https://python-poetry.org/docs/pyproject/#scripts) describes how scripts work. Badly. I dont understand this section at all. In sentence "This section describes the scripts or executables that will be installed", what does "will be installed" mean? Will they be added to PATH, or what?

Then it continues "script installed which will execute `console.run`". I have two problems here. How am I supposed to know, that `run` has to be a function in package here? This is very undescribed here and only googling helped me understand this problem. Second: it speaks about `console.run`, while code is `console:run` (`.` vs. `:`). That is even more confusing. 

How to do I specify a different then root location of scripts? Does the `.` separates folders from root dir? Or how does this work at all?

#### quotes inconsistency
I dont like the fact, that single quotes and double quotes are mixed:
```
[[tool.poetry.source]]
name = 'private'

but 
[tool.poetry]
name = "awesome"
```

### project vs. package
I noticed in this thread that project and package may/should or may not/should not be the same thing. 
- It should be clearly explained in the documentation, what is expected use of the tool. I mean, what if I want more packages in my project? Should I not use poetry at all? Or what should I do? In my understanding, it is possible with specifying tool.poetry.packages, but it should be documented better.
- I agree with @sonotley and The Zen of Python, that this behaviour should be explicit not implicit => if I do not specify the tool.poetry.packages, I may freely work, but when I build, only the package with the same name as project is build (vilation of zen: explicit is better then implicit and no error should pass silently).

#### if tool.poetry.packages: poetry build is weird
Lets stars with `poetry new --name projectname --src projectroot`
It creates this folder structure:
```
projectroot/
|-- src/
    |-- projectname/
        |-- __init__.py
|-- tests/
    ...
|-- pyproject.toml
|-- README.rst
```

When I build now, everything is fine.
Now, I want to add some other package into src, so that:
```
|-- src/
    |-- projectname/
        |-- __init__.py
    |-- secondpackage/
        |-- __init__.py
        ...
```

When I build now, the secondpackage is not build. This is pseudo-fine. There could be at least a warning message from poetry that there are other packages in the root or root/src folder, that where not build. But OK. Lets add the package to tool.poetry.packages:
```
pyproject.toml/
---
[[tool.poetry.packages]]
include = "src/secondpackage"
```

Then, when you build the secondpackage is build as expected. BUT the main package `projectname` is NOT. It was silently excluded from build. This is even worse vilation, since now, without any warning msg, the main package is not included. So when I include the second package, I must also include the main package. And again, this is not mentioned anywhere. So again: Errors should never pass silently.

But the nightmare continues. I cannot add second `include` statement into `[[tool.poetry.packages]]` as it accepts only one line with `include`. So lets change to the:
```
# Good:
[[tool.poetry.packages]]
include = "src/druhypackage"

# Error:
[[tool.poetry.packages]]
include = "src/projectname"
include = "src/druhypackage"

# Lets use:
[tool.poetry]
...
packages = [
    {include = "src/projectname"},
    {include = "src/druhypackage"},
]
```

Now, it finally builds both packages.

Also, you do have to specify, that the package is in the `src` directory. I would expect this could be ommited, since I already told poetry that this is project with `src` folder in the begging. But ok. What is worse, is the fact that I must use unix path delimiter `/` and must not use windows path delimiter `\` and that it is not mentioned in the documentation.

Also, when building just the first package `projectname`. The wheel folder strucure is such: that the package is in root folder. But when the `secondpackage` was added to build process, they are both in src/.. folder in wheel. So the wheel folder structure changes. Again, silently.

### Conclusion
To conclude, let me quote The Zen of Python:
"Explicit is better than implicit."
"Readability counts."
"In the face of ambiguity, refuse the temptation to guess." (Do not force users to guess)

Except for all of that, poetry is a great tool and thank you all who help this effort.

**Comment by finswimmer** [comment] 2021-09-24 12:14
Hello @sandrinr,

I have the improvement of the documentation on my Todo list for some time now. Hopefully I find enough time for it in the next weeks. Most of the improvements will cover the point, that the current documentation presumes that people have knowledge about how python packaging and setting up python project works. poetry isn't doing any special things here, but the introductions to these topics are missing, making in hard to understand some points to newcomers in this field.

Regarding your confusions about the syntax in the `pyproject.toml`: The syntax isn't an invention by poetry. It's a standardized format. You can read more about it here: https://toml.io/en/

fin swimmer

**Closed** 2021-11-14 12:53 UTC
Labels: Documentation, Good First Issue

**Comment by nickbreid** [comment] 2022-07-08 14:51
These were helpful comments from everyone in this thread. I know it's been idle for a while, but I found this thread for the first time today because of the same reason described earlier; namely, this sentence in the docs:

> If your project structure differs from the standard one supported by poetry...

This sentence is seemingly still not accompanied by a good example of the the standard project structure.

In my case, I had no introduction to poetry and took over a rewrite of a poetry-using app that had a structure like this:

```
rather-long-app-name
├── pyproject.toml
├── rather_long_app_name
│   └── __init__.py
│   └── a.py
│   └── b.py
```

I understand this to be the standard structure. However, everyone on this newly formed team, none of whom are poetry users, instinctively said: "Obviously we should rename the `rather_long_app_name` directory to `src` so we can stop typing this long name in so many imports." I'm not saying that's the _right_ mode of thinking -- it's just our two cents.

Anyway, if anyone else had that same thought and comes across this post, you can use this structure by doing what people recommended above in your `pyproject.toml` file:

```toml
[tool.poetry]
name = "rather-long-app-name"
packages = [
    { include = "src" }
]
```
