### ISSUE TITLE
Mypy with in-project virtualenv misses type errors on full path to file

### ISSUE THREAD

**Issue by Doekeb** [python-poetry/poetry#7026] opened 2022-11-14 05:17 UTC
## Prerequisites

- **Poetry version**: 1.2.2
- **Python version**: 3.10.7
- **OS version and name**: Manjaro Linux (rolling release)
- **pyproject.toml**: https://gist.github.com/Doekeb/587f55d167c48654b279fde4e7334efb
- **Full MWE**: [Here](https://github.com/Doekeb/poetry-mypy-demo)

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
Under specific, but not-so-rare conditions, mypy mistakenly reports that there are no issues in the source file.

#### From Scratch: 
1. Create a new poetry project with `poetry new`.
2. `poetry config virtualenvs.in-project true --local`.
3. Create a simple `main.py` file inside the package with type annotations and an obvious violation.
4. `poetry install`.
5. Verify that `poetry run mypy poetry_mypy_demo/main.py` correctly produces a type error.
6. Either `poetry run mypy /full/path/to/package/main.py` or `poetry shell` then `mypy /full/path/to/package/main.py`.

#### From MWE:
1. Clone the MWE https://github.com/Doekeb/poetry-mypy-demo.
2. Note, crucially, the setting `virtualenvs.in-project = true` as defined in `poetry.toml`.
3. Note, also crucially, that `poetry_mypy_demo/main.py` has an obvious type violation.
4. `poetry install`.
5. Verify that `poetry run mypy poetry_mypy_demo/main.py` correctly produces a type error.
6. Either `poetry run mypy /full/path/to/directory/poetry_mypy_demo/main.py` or `poetry shell` then `mypy /full/path/to/directory/poetry_mypy_demo/main.py`.

#### Expected Behavior:
Mypy produces the same type error as in step 5.

#### Actual Behavior:
Mypy finishes successfully without producing any type errors with the message `Success: no issues found in 1 source file`.

## Notes
- There is no bug if step 2 is omitted. In this case, mypy correctly produces a type error when using either the relative or absolute path.
- There is no bug if mypy is installed into an old-school virtual environment (`pyenv` + `virtualenv` + `pip`). This is the main reason that I suspect this is an issue with poetry and not with mypy.
- While the conditions to reproduce this bug are very specific, this situation arises in a very typical workflow: when using VSCode, it is convenient to have virtual environments in-project since they are more easily discovered by the editor. From there, when using mypy as a linter, VSCode calls mypy in the virtual environment on the full path to the file rather than the relative path, and therefore all the conditions to reproduce the bug are present so no linting occurs even with obvious type errors.

## Output of `mypy -vvv ...`
After `poetry shell`...
- After `rm -r .mypy_cache`: output of `mypy -vvv /full/path/to/directory/poetry_mypy_demo/main.py`: https://gist.github.com/Doekeb/9063526e8dce99e5e089ef8f06655a5c
- After `rm -r .mypy_cache`: output of `mypy -vvv poetry_mypy_demo/main.py`: https://gist.github.com/Doekeb/b3e8d112e531cdf3d82237e568d1c30b

**Comment by neersighted** [comment] 2022-11-14 05:25
Duplicate of a mypy issue: https://github.com/python/mypy/issues/14042

Reproduces without Poetry in the loop; simply `poetry install` then `source .venv/bin/activate`; the same symptoms will be exhibited.

**Closed by neersighted** 2022-11-14 05:25 UTC
Labels: kind/bug, status/triage
