### ISSUE TITLE
keyrings.alt.Windows used unter linux if python 3 used

### ISSUE THREAD

**Issue by jedie** [python-poetry/poetry#1968] opened 2020-02-01 21:14 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **Ubuntu 18.04** 
- **Poetry v1.0.3** 

## Issue

I like to start poerty directly with Python v3, so i change the shebang in **~/.poetry/bin/poetry** to:

`#!/usr/bin/env python3`

But then i get a very strange traceback while `poetry publish`:

```
Error initializing plugin EntryPoint(name='Windows (alt)', value='keyrings.alt.Windows', group='keyring.backends').
Traceback (most recent call last):
  File "/home/jens/.poetry/lib/poetry/_vendor/py3.6/keyring/backend.py", line 203, in _load_plugins
    init_func = ep.load()
  File "/home/jens/.poetry/lib/poetry/_vendor/py3.6/importlib_metadata/__init__.py", line 95, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/keyrings/alt/Windows.py", line 9, in <module>
    from . import file_base
  File "/usr/lib/python3/dist-packages/keyrings/alt/file_base.py", line 13, in <module>
    from keyring.util.escape import escape as escape_for_ini
ModuleNotFoundError: No module named 'keyring.util.escape'
Error initializing plugin EntryPoint(name='file', value='keyrings.alt.file', group='keyring.backends').
Traceback (most recent call last):
  File "/home/jens/.poetry/lib/poetry/_vendor/py3.6/keyring/backend.py", line 203, in _load_plugins
    init_func = ep.load()
  File "/home/jens/.poetry/lib/poetry/_vendor/py3.6/importlib_metadata/__init__.py", line 95, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/keyrings/alt/file.py", line 11, in <module>
    from keyring.util.escape import escape as escape_for_ini
ModuleNotFoundError: No module named 'keyring.util.escape'
Error initializing plugin EntryPoint(name='pyfs', value='keyrings.alt.pyfs', group='keyring.backends').
Traceback (most recent call last):
  File "/home/jens/.poetry/lib/poetry/_vendor/py3.6/keyring/backend.py", line 203, in _load_plugins
    init_func = ep.load()
  File "/home/jens/.poetry/lib/poetry/_vendor/py3.6/importlib_metadata/__init__.py", line 95, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/keyrings/alt/pyfs.py", line 8, in <module>
    from keyring.util.escape import escape as escape_for_ini
ModuleNotFoundError: No module named 'keyring.util.escape'
```

**Comment by zeezdev** [comment] 2020-03-11 12:33
There is the similar problem in dbxfs: https://github.com/rianhunter/dbxfs/issues/14

This issue may be resolved with the upgrade of `keyrings.alt`: `pip3 install --upgrade keyrings.alt`

**Comment by jedie** [comment] 2020-03-18 09:06
> pip3 install --upgrade keyrings.alt

Yes, it helps to remove `ModuleNotFoundError: No module named 'keyring.util.escape'`
But it's only a work-a-round for a bug in poetry.

**Comment by dazza-codes** [comment] 2021-02-10 20:36
Similar error on linux where an OSX keyring plugin raises an error:

```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"

$ python --version
Python 3.7.9

$ poetry --version
Poetry version 1.1.4

$ poetry publish --build --dry-run
There are 2 files ready for publishing. Build anyway? (yes/no) [no] yes
Building py-dev-deps (0.2.0)
  - Building sdist
  - Built py-dev-deps-0.2.0.tar.gz
  - Building wheel
  - Built py_dev_deps-0.2.0-py3-none-any.whl

Error initializing plugin EntryPoint(name='macOS', value='keyring.backends.macOS', group='keyring.backends').
Traceback (most recent call last):
  File "/home/joe/.poetry/lib/poetry/_vendor/py3.7/keyring/backend.py", line 198, in _load_plugins
    init_func = ep.load()
  File "/home/joe/.poetry/lib/poetry/_vendor/py3.7/importlib_metadata/__init__.py", line 105, in load
    module = import_module(match.group('module'))
  File "/opt/conda/envs/py-dev-deps/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'keyring.backends.macOS'

```

**Comment by abn** [comment] 2024-03-02 13:08
> I like to start poerty directly with Python v3, so i change the shebang in ~/.poetry/bin/poetry to:
> 
> #!/usr/bin/env python3

This will not work since you basically are asking poetry to execute under an environment that it was not installed into. I'd suggest trying a new version of poetry installed using a method mentioned at https://python-poetry.org/docs/#installation.

This is also likely issues with keyring not functioning correctly under a non-interactive environment. There are improvements to that part of the code in upcoming releases. #8623 #9065

Meanwhile if keyring issues persist use temporarily.

```sh
export PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring
```

If the issue is different to existing ones, please file a new issue with information on how best we could reliably reproduce it.

**Closed by abn** 2024-03-02 13:08 UTC
Labels: kind/bug
