### ISSUE TITLE
Poetry does not include Pip in lockfile when specified as explicit dependency

### ISSUE THREAD

**Issue by enpaul** [python-poetry/poetry#1818] opened 2020-01-02 22:03 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Fedora 31: `5.3.16-300.fc31.x86_64 x86_64 GNU/Linux`
- **Poetry version**: `1.0.0`
- **Pyproject gist**: https://gist.github.com/enpaul/8d792cae5df181c1c77678b20516e5c5

## Issue

Poetry does not include pip or its dependencies in the lockfile when pip is explicitly specified as a dependency of my project. While pip is in fact installed to Poetry's virtualenv (confirmed using `poetry run which pip` and `poetry run pip --version`) it is not included in the Poetry lockfile, even though the `pyproject.toml` specifies `pip = "^19.3.1"` in the `[tool.poetry.dependencies]` section (see linked pyproject gist).

Admittedly this is an edge case, but still something I encountered.

### Expected behaviour:

Poetry includes pip and its dependencies in the lockfile when pip is specified as a project dependency in `pyproject.toml`. This would make it accessible via `poetry show` and `poetry export`.

### Actual behaviour:

Poetry does not include pip or its dependencies in the lockfile, regardless of whether pip is specified as a dependency or not. Poetry reports that pip is not installed when running `poetry show` or `poetry export`.

### Steps to repro:
1. Download gist file
```
curl -o pyproject.toml https://gist.githubusercontent.com/enpaul/8d792cae5df181c1c77678b20516e5c5/raw/aeb150a03d07d6a3def7d1f7db35985dfacd55ae/poetry-pip-lock-reproducer.toml
```
2. Install and lock the project
```
poetry install
```
3. Inspect dependencies and lockfile
```
poetry show pip  # raises ValueError, for no package `pip`
cat poetry.lock  # shows no dependencies
```

Thank you for all your work on Poetry! Let me know if I can provide any more information.

**Comment by finswimmer** [comment] 2020-01-03 07:46
Hello @enpaul ,

this is a duplicate of #1584. (https://github.com/python-poetry/poetry/issues/1584#issuecomment-566023407).

So I will close this here. Feel free to leave a comment if you disagree.

fin swimmer

**Closed by finswimmer** 2020-01-03 07:46 UTC
Labels: Bug

**Comment by enpaul** [comment] 2020-01-03 13:55
@finswimmer Yep, sorry about that!
