### ISSUE TITLE
Poetry failed to add a package with BadZipFile error 

### ISSUE THREAD

**Issue by Maybbe** [python-poetry/poetry#3763] opened 2021-03-09 09:08 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **Debian GNU/Linux 10 (buster)**: 
- **Poetry version 1.1.4**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue

I try to add a package with `poetry add jqdatasdk` but it failed with an error message: 
`Skipping virtualenv creation, as specified in config file.
Using version ^1.8.8 for jqdatasdk

Updating dependencies
Resolving dependencies... (8.4s)

  BadZipFile

  File is not a zip file

  at /usr/local/lib/python3.9/zipfile.py:1324 in _RealGetContents
      1320│             endrec = _EndRecData(fp)
      1321│         except OSError:
      1322│             raise BadZipFile("File is not a zip file")
      1323│         if not endrec:
    → 1324│             raise BadZipFile("File is not a zip file")
      1325│         if self.debug > 1:
      1326│             print(endrec)
      1327│         size_cd = endrec[_ECD_SIZE]             # bytes in central directory
      1328│         offset_cd = endrec[_ECD_OFFSET]         # offset of central directory`

**The strange thing is I can install the package with `pip install jqdatasdk` command.**

**Comment by binary-signal** [comment] 2021-03-10 08:25
I had a similar problem a few days ago with poetry, the idea behind the issue is that poetry is having its own private cache of packages, and for some strange reason that cached package is corrupted and that's why you get the error. One solution would be to empty your poetry cache and try again to install the package

clear poetry caches with 

```shell
poetry cache clear pypi --all
```

Assuming pypi as your package repo

**Comment by sinoroc** [comment] 2021-03-28 11:10
Yes, you probably have a corrupted file in your cache. Either try to identify which one precisely, maybe the verbose output `poetry add -vvv jqdatasdk` can help with that. Or clear the whole cache as mentioned in the previous message.

**Comment by finswimmer** [comment] 2021-04-05 06:51
Hello @Maybbe,

could you solve this issue by clearing the cache as described by @binary-signal ?

fin swimmer

**Comment by papb** [comment] 2021-07-02 05:52
Hello @finswimmer and everyone else, I am facing a similar situation. In the presence of a `poetry.lock` file, which includes checksums, couldn't poetry automatically realize that the cached file is corrupted and download a new version?

**Comment by binary-signal** [comment] 2021-08-06 19:53
at the moment poetry doesn't support detecting corrupted downloads, errors shouldn't pass unnoticed pythonic maybe decision idk.

**Comment by finswimmer** [comment] 2022-01-21 14:03
Because we haven't receive more information I assume the original issue is solved. So I'm closing this. Feel free to leave a comment if you disagree.

**Closed by finswimmer** 2022-01-21 14:03 UTC
Labels: Bug, Triage, Awaiting Reponse
