### ISSUE TITLE
Could not find version error when no credentials are set

### ISSUE THREAD

**Issue by fdragovic** [python-poetry/poetry#4134] opened 2021-06-03 09:55 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: OSX 11.4, python:3.8-buster docker image
- **Poetry version**: 1.1.6 (also downgraded to 1.0.9, 1.0.5, still the same error)

## Issue
when you set your private repo url via toml and/or config, and don't set up credentials (via config or in the sources url) instead of getting an auth error you get a 'cannot resolve version' error (and the repo doesn't get looked up either, logs only show `PyPI: No packages found`), which made it really hard to diagnose the error as it seems the repository isn't added at all 😅

## Steps to Reproduce
* `poetry new test`
* add private repository in toml file
* poetry add private_package -> fails with `Could not find a matching version of package`
* add credentials via `poetry config` or in the url in the toml and it resolves again
* poetry config --unset the credentials and it stops looking in the repo

**Comment by dimbleby** [comment] 2022-10-29 12:07
401 and 403 responses are logged as authorization errors.  Either this wasn't true when the issue is raised, or your private repository is not returning an auth error.

Either way, this can be closed.

**Comment by neersighted** [comment] 2022-10-29 16:24
We used to not log a 401 error as an auth error; this has been fixed on the 1.2 branch.

**Closed by neersighted** 2022-10-29 16:24 UTC
Labels: area/ux, area/sources
