### ISSUE TITLE
`poetry show` and `poetry install` should throw an error when used with an unknown group name

### ISSUE THREAD

**Issue by pmav99** [python-poetry/poetry#4576] opened 2021-09-30 16:55 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

```
poetry debug info

Poetry
Version: 1.2.0a2
Python:  3.9.7

Virtualenv
Python:         3.8.12
Implementation: CPython
Path:           /tmp/aaa/.venv
Valid:          True

System
Platform: linux
OS:       posix
Python:   /usr
```

## Issue

Specifying an unknown group name on `poetry show` and `poetry install` (and possibly other commands that handle dependency groups) results in no error whatsoever. E.g.

```
poetry show --without gibberish && echo OK
poetry show --with gibberish && echo OK

poetry install --without gibberish && echo OK
poetry install --with gibberish && echo OK
```

IMHV, unknown group names, at least most of the time, imply typos and should result in an error.

The same happens e.g. in the `export` plugin, but I will open a separate issue there.

**Comment by ralbertazzi** [comment] 2023-05-20 09:39
Duplicate of https://github.com/python-poetry/poetry/issues/7303, which has been fixed

**Closed by ralbertazzi** 2023-05-20 09:39 UTC
Labels: area/cli, area/error-handling, area/ux
