### ISSUE TITLE
Problema with Pandas in circleci

### ISSUE THREAD

**Issue by Daiton** [python-poetry/poetry#4296] opened 2021-07-19 01:50 UTC
- [ ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: serverless image: ubuntu-2004:202008-01
- **Poetry version**: 1.1.7
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 
`[tool.poetry]
name = "pix-import-auto"
version = "0.1.0"
description = "Pix auto BU simplified import"
authors = ["Rogério Novo <rogerio.novo@yandeh.com.br>"]

[tool.poetry.dependencies]
python = "^3.7"
psycopg2-binary = "2.8.6"
SQLAlchemy = "1.4.17"
boto3 = "1.17.88"
pydantic = "1.8.2"
python-dotenv = "0.17.1"
openpyxl = "^3.0.7"
xlrd = "1.0.0"
pandas = "0.24.2"

[tool.poetry.dev-dependencies]
black = "21.5b2"
flake8 = "3.9.2"
mypy = "0.812"
pytest = "6.2.4"
pytest-cov = "2.12.1"
pylint = "2.8.3"
autopep8 = "^1.5.7"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
target-version = ['py37', 'py38']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist

  # The following are specific to Black, you probably don't want those.
  | blib2to3
  | tests/data
  | profiling
)/
'''

[tool.flake8]
max-line-length = 120
extend-ignore = "E203"`

## Issue
I have the above pyproject.toml that runs perfectly in the local environment. But inside circleci it crashes on the 'poetry install' command until circleci timeout. I realized that this started happening after it includes panda addiction.

**Comment by dimbleby** [comment] 2022-06-04 12:57
unactionable

**Comment by Secrus** [comment] 2022-06-04 13:59
Closing, as the issue is quite dated and doesn't provide enough information to reproduce.

**Closed by Secrus** 2022-06-04 13:59 UTC
Labels: Bug, Triage
