### ISSUE TITLE
Poetry update hangs when prompted for ssh key passphrase

### ISSUE THREAD

**Issue by danihodovic** [python-poetry/poetry#2825] opened 2020-08-17 21:01 UTC
Re-opening https://github.com/python-poetry/poetry/issues/446 which was automatically closed.

> I successfully added private git repository using poetry add --git ssh://git@gitlab_url/username/repository_name.git package_name. Then I ran poetry update, but it hanged forever on cloning repository (there: https://github.com/sdispater/poetry/blob/master/poetry/vcs/git.py#L99). The problem is that I have to authenticate using my ssh key for cloning repository, git asks for the passphrase, but I cannot enter it.

**Comment by gehring** [comment] 2020-08-20 03:24
I ran into a similar issue when authenticating with https, e.g., `poetry add git+https://github.com/username/my_private_repo.git`. Oddly enough, running it with `-vvv` allowed me to run it to completion but I had to type in my login info 4 different times!

I had to type it in 1) at the start, 2) while "resolving dependencies", 3) in between "writing lock file" and "Package operations: 1 install, [...]", and 4) at the very end after the final " - Installing my_private_package ..." message.

**Comment by Izoelektro** [comment] 2020-10-16 08:57
Confirming that this is still an issue as of Poetry version 1.1.3. 

It seems as if the poetry CLI/prompt overshadows the Git one - I am assuming this because for me the poetry prompt (without verbosity) keeps flashing and at times shows the Git prompt. I have even managed to make it work simply by guessing when the Git prompt appeared and typing in my username and passphrase multiple times.

This would explain the current issue (#446) as well as #863 (which was observed to be related already). Funnily enough, they have a similar issue over at [pipenv](https://github.com/pypa/pipenv/issues/3333). Seeing as the CL package used by poetry is built by hand as it is, I am guessing it should not be *that* hard to solve this (although I am far from capable of doing it). I see why it would not be of high priority to do so however.

**Comment by abn** [comment] 2020-10-16 10:55
It seems that it might be senisble to disable interactions for the git client and document that cases that need credentials should really use https://git-scm.com/docs/gitcredentials.

**Comment by danihodovic** [comment] 2020-10-16 14:27
@abn Can't you forward stdin / stdout between the git subprocess to the user process when the password prompt is triggered?

**Comment by abn** [comment] 2020-10-16 15:01
I suspect that will cause more problems than it solves. For example, when multiple operations happen in parallel. Better to keep this simple.

**Comment by danihodovic** [comment] 2020-10-16 16:12
Usually the ssh key is prompted for once and saved in the ssh-agent.

**Comment by abn** [comment] 2020-10-17 11:38
Yeah but the issue is when multiple processes request at the same time. I'm inclined to day that it's safer to document this and error out gracefully. Maybe even a detailed message on what to try.

**Comment by Izoelektro** [comment] 2020-10-19 07:06
From a user standpoint, git credentials do a fairly good job of solving it. Just documenting the issue would already help quite a lot in my opinion. Simply as an idea, would command-line options to provide credentials be a possible solution? That would likely cause some 'bloat' (verbosity) in the commands however.

**Comment by Mpreyzner** [comment] 2020-11-19 10:44
I have the same problem with resources from https not ssh. Exception with explanation why it failed would be sufficient for me.

**Comment by tector** [comment] 2021-01-29 15:55
This is a super annoying issue :-/
I have to type my SSH Passphrase at least 6 times on each install or update...

Any update on this?
I use the newest version of poetry.

**Comment by pietermarsman** [comment] 2021-03-03 08:24
Running `ssh-add` before poetry will unlock you ssh keys once. It will remember the identities and password until you close your terminal session.

**Comment by dimbleby** [comment] 2022-07-31 17:50
fixed at #5880 (and duplicated by #3222)

**Comment by hummus** [comment] 2022-10-21 16:16
> It seems that it might be senisble to disable interactions for the git client and document that cases that need credentials should really use https://git-scm.com/docs/gitcredentials.


(a) ssh passphrase prompting and (2) one-time, on-terminal http password prompting without requiring persistence do seem like desirable use-cases that are already supported by the underlying tools git/ssh and pip. the case I ran into was where i'm  on a foreign machine where it is undesirable to persist creds but I do want to install once from somewhere I have access.

would you still be open to a change which retains user/env-specified `GIT_TERMINAL_PROMPT` behavior? maybe something like
1) errors and does not block when not attached to a TTY (OR if poetry itself cannot prompt for some reason)
2) does block and prompt for passphrase when attached to a TTY (when underlying git client is prompting)

**Closed** 2023-02-01 11:59 UTC
Labels: kind/bug, status/triage
