### ISSUE TITLE
Error when using "develop = true" on non-Poetry project

### ISSUE THREAD

**Issue by brandon-leapyear** [python-poetry/poetry#5313] opened 2022-03-15 03:29 UTC
- [ ] ~I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.~
    - I'm looking at the source code on GitHub, and it should still be an issue in latest
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOS 10.15.7
- **Poetry version**: 1.1.12
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: ...

## Issue

In our monorepo, we're incrementally moving things over to Poetry, but we're still not finished. Right now, we have one project (e.g. `poetry-project`) that installs another project (e.g. `zz-other-project`) with `develop = true`. In `zz-other-project`, we have a `venv` directory. Running `poetry update` in `poetry-project` gives:
```
The dependency name for zz-other-project does not match the actual package's name: flake8-comprehensions
```
The problem is:
https://github.com/python-poetry/poetry/blob/6485bc23d6497c7731e0f1a635f960b33f2ae99e/src/poetry/inspection/info.py#L371-L384
where it finds `venv/lib/python3.7/site-packages/flake8-comprehensions.dist-info` before `zz-other-project.egg-info`

**Comment by finswimmer** [comment] 2022-03-15 05:42
Hello @brandon-leapyear,

this should be a duplicate of https://github.com/python-poetry/poetry/issues/5070.

fin swimmer

**Closed by finswimmer** 2022-03-15 05:42 UTC
Labels: Bug, Triage

**Comment by brandon-leapyear** [comment] 2022-03-15 05:52
I did see the other issue, and I did see it was the same root problem, but
I wasn't sure if Poetry wanted to treat that differently since that was a
matter of vendored packages while this is a matter of local projects. Maybe
the issue should be renamed to be more generally applicable?
