### ISSUE TITLE
Could not find a matching version of package typing-extensions. typing-extensions==3.10 version is not resolvable during manual add.

### ISSUE THREAD

**Issue by kbaikov** [python-poetry/poetry#5801] opened 2022-06-08 13:33 UTC
- [x ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [ x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Arch Linux
- **Poetry version**: 1.2.0b2
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/kbaikov/03bed5b79e951cebe123f612b621842c

## Issue

Exception during run: `poetry add typing-extensions==3.10 `
However pip resolves this correctly.
poetry need full version with additional zeros: `poetry add typing-extensions==3.10.0.0`

Probably not a bug since approx works fine: `poetry add typing-extensions~=3.10`
Feel free to close.

```bash
ValueError

  Could not find a matching version of package typing-extensions

  at ~/.local/lib/python3.10/site-packages/poetry/console/commands/init.py:406 in _find_best_version_for_package
      402│         )
      403│ 
      404│         if not package:
      405│             # TODO: find similar
    → 406│             raise ValueError(f"Could not find a matching version of package {name}")
      407│ 
      408│         return package.pretty_name, selector.find_recommended_require_version(package)
      409│ 
      410│     def _parse_requirements(self, requirements: list[str]) -> list[dict[str, Any]]:
```

**Comment by clintonroy** [comment] 2022-06-09 02:27
There is no 3.10 of typing-extensions, there is 3.10.0.0, so I think poetry is correct here, and pip is being a bit loose or helpful, depending on your point of view. I don't think there's a problem here.

**Comment by mkniewallner** [comment] 2022-06-25 15:06
Closing, since this is the expected behavior.

**Closed by mkniewallner** 2022-06-25 15:06 UTC
Labels: Bug, Triage
