### ISSUE TITLE
Getting wheeles error 

### ISSUE THREAD

**Issue by DrMartiner** [python-poetry/poetry#5083] opened 2022-01-22 12:16 UTC
```
poetry add django-object-tools
Using version ^2.0.0 for django-object-tools

Updating dependencies
Resolving dependencies... (0.1s)

RuntimeError

failed to build image pip because:
Traceback (most recent call last):
File "/Users/user/.pyenv/versions/3.9.0/envs/signals_back/lib/python3.9/site-packages/virtualenv/seed/embed/via_app_data/via_app_data.py", line 57, in _install
installer.install(creator.interpreter.version_info)
File "/Users/user/.pyenv/versions/3.9.0/envs/signals_back/lib/python3.9/site-packages/virtualenv/seed/embed/via_app_data/pip_install/base.py", line 35, in install
self._uninstall_previous_version()
File "/Users/user/.pyenv/versions/3.9.0/envs/signals_back/lib/python3.9/site-packages/virtualenv/seed/embed/via_app_data/pip_install/base.py", line 151, in _uninstall_previous_version
dist_name = self._dist_info.stem.split("-")[0]
File "/Users/user/.pyenv/versions/3.9.0/envs/signals_back/lib/python3.9/site-packages/virtualenv/seed/embed/via_app_data/pip_install/base.py", line 115, in _dist_info
raise RuntimeError(msg)  # pragma: no cover
RuntimeError: no .dist-info at /Users/user/Library/Application Support/virtualenv/wheel/3.9/image/1/CopyPipInstall/pip-21.3.1-py3-none-any, has pip


at ~/.pyenv/versions/3.9.0/envs/signals_back/lib/python3.9/site-packages/virtualenv/seed/embed/via_app_data/via_app_data.py:71 in run
67│                 messages = ["failed to build image {} because:".format(", ".join(exceptions.keys()))]
68│                 for value in exceptions.values():
69│                     exc_type, exc_value, exc_traceback = value
70│                     messages.append("".join(traceback.format_exception(exc_type, exc_value, exc_traceback)))
→  71│                 raise RuntimeError("\n".join(messages))
72│
73│     @contextmanager
74│     def _get_seed_wheels(self, creator):
75│         name_to_whl, lock, fail = {}, Lock(), {}
```

**Comment by finswimmer** [comment] 2022-01-30 19:40
Hello @DrMartiner,

unfortunately your post is missing essential information to give proper help. So if you're still interested in resolving your problem please tell us what OS you are using, how you've install poetry, which version you are using and anything else that can help us to reproduce your problem.

Thanks a lot.

fin swimmer

**Comment by finswimmer** [comment] 2022-04-29 20:50
Hey,

because you haven't add more information for a long time I guess this ticket is no longer relevant and we can close it. Feel free to leave a comment if you disagree.

fin swimmer

**Closed by finswimmer** 2022-04-29 20:50 UTC
Labels: Bug, Triage, Awaiting Reponse
