### ISSUE TITLE
If Python package is placed in non-root directory of Git repo -- how to `poetry add` it correctly?

### ISSUE THREAD

**Issue by Felix-neko** [python-poetry/poetry#5006] opened 2022-01-08 01:36 UTC
Hi folks! 

I want to add a fresh version of feast package from git (`#master` branch) via Poetry.

https://github.com/feast-dev/feast -- here is it, the python package is places in non-root directory: https://github.com/feast-dev/feast/tree/master/sdk/python

What should I do to `poetry add` it correctly as a dependency to my project?

Poetry docs don't tell anything about it...

**Comment by finswimmer** [comment] 2022-01-08 07:46
Hey,

this is currently not possible and a duplicate of #755.

fin swimmer

**Closed by finswimmer** 2022-01-08 07:46 UTC
Labels: Documentation, Triage
