### ISSUE TITLE
Allow specific source to only be used in resolving dependency when `source = "<source>"` is specified

### ISSUE THREAD

**Issue by chunleng** [python-poetry/poetry#7180] opened 2022-12-12 08:00 UTC
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request

As title, some sources are not meant to be lookup because they are used for specific purpose. For example, in pytorch-cpu, I get the following printed when running `poetry lock --no-update`.

```
Resolving dependencies... (881.4s)<c1>Source (pytorch-cpu):</c1> Authorization error accessing https://download.pytorch.org/whl/cpu/requests/
```

The above makes unnecessary requests and causes the dependency resolution to be slower than it needs to be.

If I may, I propose the following option for the source to be used only in the specified dependency

```
[[tool.poetry.source]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
specified_only = true
```

**Comment by neersighted** [comment] 2022-12-12 08:01
This is a duplicate of #6173. An issue being closed as a duplicate does not preclude it from being implemented, it only means that the linked issue is the place to discuss it. Please investigate the linked issue instead of continuing to open more issues. Thank you.

**Closed by neersighted** 2022-12-12 08:01 UTC
Labels: kind/feature, status/triage

**Comment by chunleng** [comment] 2022-12-12 08:18
@neersighted I don't get why this feature request is a duplicate of the mentioned ticket?

**Comment by chunleng** [comment] 2022-12-12 08:23
> This is a duplicate of #6173. An issue being closed as a duplicate does not preclude it from being implemented, it only means that the linked issue is the place to discuss it. Please investigate the linked issue instead of continuing to open more issues. Thank you.

Sorry, browser crashed and I didn't realize my previous request went through because of your fast reaction. Thank you for the quick response!
