### ISSUE TITLE
`poetry build` issue: Trailing newlines in tool.poetry.description lead to pip not installing dependencies

### ISSUE THREAD

**Issue by randallpittman** [python-poetry/poetry#4321] opened 2021-07-26 19:03 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Linux Mint 20.1
- **Poetry version**: 1.1.7
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/randallpittman/1fb8a187a79fe9bcc17cb4f845ff6d76

## Issue

In the above-linked Gist, the `tool.poetry.description` field is a triple-quoted string with a trailing newline. When poetry creates the METADATA file (for wheel) or PKG-INFO file (for sdist) that space makes it into those files and pip seems to stop when it comes to a blank line. This has the effect of none of the package dependencies getting installed.

**Comment by randallpittman** [comment] 2021-07-26 19:04
Example METADATA file with trailing newline in `tool.poetry.description`:

```text
Metadata-Version: 2.1
Name: pydantic-plus
Version: 1.1.2rc4
Summary: Pydantic BaseModel extended a bit:
  - PurePosixPath json encoding and validation
  - from_toml and from_tomls classmethods

Author: Randall Pittman
Author-email: redacted@example.com
Requires-Python: >=3.8,<4.0
Classifier: Programming Language :: Python :: 3
Classifier: Programming Language :: Python :: 3.8
Classifier: Programming Language :: Python :: 3.9
Requires-Dist: pydantic (>=1.8.1,<2.0.0)
Requires-Dist: rtoml (>=0.7.0,<0.8.0)
```

**Comment by randallpittman** [comment] 2021-07-26 19:14
I guess this is ultimately an RFC822 thing? Should all newlines be converted to `\n`?

**Comment by randallpittman** [comment] 2021-07-26 19:15
I also now realize that mutli-line description is probably not good practice.

**Comment by finswimmer** [comment] 2021-07-27 04:11
Hello @randallpittman,

thanks for reporting. This was done earlier as well.

Duplicate of https://github.com/python-poetry/poetry/issues/3610

fin swimmer

**Closed by finswimmer** 2021-07-27 04:11 UTC
Labels: Bug, Triage

**Comment by randallpittman** [comment] 2021-07-29 16:11
> Hello @randallpittman,
> 
> thanks for reporting. This was done earlier as well.
> 
> Duplicate of #3610

Whoops. Thanks.
