### ISSUE TITLE
Run a specific command after installation on a library 

### ISSUE THREAD

**Issue by MuhmdRaouf** [python-poetry/poetry#1578] opened 2019-11-13 10:14 UTC
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Feature Request

I was trying to install pre-commit library and I found out that every time I pass the project to a friend I need to tell him to run the command pre-commit install --hook-type={pre-commit,pre-push} so we can use the hooks, is that a way that I can make a post-install command so I make sure to run the hooks

**Comment by brno32** [comment] 2019-11-14 05:16
I agree this would be useful.

**Comment by whoizit** [comment] 2019-12-16 12:48
I need it after installation 'spacy' by official manual if i check any Model https://spacy.io/usage
`python -m spacy download en_core_web_sm`

**Comment by TheButlah** [comment] 2020-02-11 18:08
This is my exact use case. Maybe `tool.poetry.scripts` is related? https://github.com/python-poetry/poetry/issues/241

**Comment by talarari** [comment] 2021-02-24 10:44
same use case for me, anything that can be done here?

**Comment by a-recknagel** [comment] 2021-03-15 09:37
Isn't this a duplicate of https://github.com/python-poetry/poetry/issues/265? If that is the case, answer would unfortunately be "won't do"

**Comment by Abdullahabid3691** [comment] 2021-03-22 11:51
Maybe[ this answer ](https://stackoverflow.com/questions/61561366/can-you-download-nltk-data-through-poetry/66745383#66745383#answer-66745383)will be helpful.

**Comment by joaoe** [comment] 2022-10-14 22:45
> Isn't this a duplicate of #265? If that is the case, the answer would unfortunately be "won't do"

Not really. #265 is about extending poetry with custom code.

This issue is about running a post-install command hook, which I agree is a very valid use case for a development setup, e.g., setup external tools and other stuff after running `poetry install`.
In my case, I'd like to populate some links to external tools in the virtualenv bin folder or PATH variable. This post-install command would not be in any way added to a built wheel to run in some third party. It would be just something to run locally.

**Comment by finswimmer** [comment] 2022-10-20 14:59
There are no plans for a build-in functionality for this. But it should be possible to create a poetry plugin for it: https://python-poetry.org/docs/plugins/#event-handler

**Closed by finswimmer** 2022-10-20 14:59 UTC
Labels: kind/feature
