### ISSUE TITLE
Poetry now does not add the package.dependencies

### ISSUE THREAD

**Issue by martingaldeca** [python-poetry/poetry#7961] opened 2023-05-19 16:38 UTC
- **Poetry version**:1.5.0
- **Python version**: >3.10
- **OS version and name**: Ubuntu 22.04
- **pyproject.toml**: private

## Issue
I was using the poetry version 1.4.2, when adding a new package from a private pypi it adds also the package dependencies well as you can see here: (I remove the private values, but I promise that are the same for the other example)
![1 14 2](https://github.com/python-poetry/poetry/assets/36915710/94c76007-7475-4e1a-a84d-55cfc26a38aa)

When using poetry version 1.5.0, for the same package, poetry did not added the dependencies, also the description was not added and the python version not specified:
![1 15 0](https://github.com/python-poetry/poetry/assets/36915710/2c502799-c7e8-4fea-9725-4b4f11af75fb)

So in that case for us this is not a minor update, this is a major update as it is breaking some of our dependencies.

**Comment by dimbleby** [comment] 2023-05-19 16:50
I use private dependencies and repositories, and poetry 1.5.0 works fine

without a way to reproduce this there's not going to be very much that anyone can do.

**Comment by cquick01** [comment] 2023-05-19 17:07
Also seeing the same behavior on 1.5.0. We have several Python packages hosted in a private repo, and when trying to add them to a new project with `poetry add ...`, the package itself is installed but no dependencies are resolved. Note that the dependencies that are missing are just normal public PyPi packages.

I have my sources defined as follows, if it helps.

```yaml
[[tool.poetry.source]]
name = "private_pypi"
url = "https://pypi.domain.tld/simple/"
priority = "supplemental"

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"
```

**Comment by dimbleby** [comment] 2023-05-19 18:46
Works fine for me using `pypi-server` as my private repository:
```
$ tree ~/packages/
/home/dch/packages/
└── simple
    └── cq-test-poetry
        └── cq_test_poetry-0.1.0-py3-none-any.whl

2 directories, 1 file
```

```
$ pypi-server run --hash-algo sha256 -p 8080 ~/packages/
```

```toml
[tool.poetry.dependencies]
python = "^3.10"

[[tool.poetry.source]]
name = "private_pypi"
url = "http://localhost:8080/simple/"
priority = "supplemental"

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"
```
```
$ poetry --version
Poetry (version 1.5.0)

$ poetry add cq-test-poetry
Using version ^0.1.0 for cq-test-poetry

Updating dependencies
Resolving dependencies... (0.3s)

Package operations: 6 installs, 0 updates, 0 removals

  • Installing certifi (2023.5.7)
  • Installing charset-normalizer (3.1.0)
  • Installing idna (3.4)
  • Installing urllib3 (2.0.2)
  • Installing requests (2.30.0)
  • Installing cq-test-poetry (0.1.0)
```

**Comment by dimbleby** [comment] 2023-05-19 19:30
That also works just fine for me

**Comment by cquick01** [comment] 2023-05-19 20:05
So I tried to repro in docker, but was unable to. After messing with it a bit more, it appears that deleting `~/.cache/pypoetry` on my local machine gets it working again. Makes sense that it worked when in a 'clean' environment.

I have that cache directory backed up just in case. If there is any specific info that might be useful, I can look for it. I'd rather not just post the whole dir up somewhere because I don't know if any private info, like my company packages, are within.

It'd be good to avoid putting users into a weird state like this if poetry could detect and clean up the problematic cache. But for now this gets things working again.

Thanks!

**Comment by chrisgilmerproj** [comment] 2023-05-19 20:57
I was struggling with not getting the dependencies installed today when upgrading to Poetry 1.5.0 and python 3.10.11. The original `pyprojects.toml` file had only one source and it was my local devpi server that I had previously been using as a pull-through cache and private repository.

```toml
[tool.poetry.dependencies]
python = "^3.10"

[[tool.poetry.source]]
name = "private_pypi"
url = "http://localhost:8080/simple/"
priority = "primary"
```

However, when I modified it to include PyPI like this then the dependencies arrived:

```toml
[tool.poetry.dependencies]
python = "^3.10"

[[tool.poetry.source]]
name = "private_pypi"
url = "http://localhost:8080/simple/"
priority = "supplemental"

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"
```

This means that I'm no longer using my pull-through cache to get the set of packages. However, it works for now so I can move forward. Was there some change that causes this behavior? I'm thinking its related to this ticket too since the behavior seems similar.

**Comment by dimbleby** [comment] 2023-05-19 21:52
And is your case also resolved by clearing your poetry cache?

**Comment by psuet** [comment] 2023-05-22 15:28
I can also reproduce this or a similar problem.

When locking the following file 

```
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "testproject"
version = "0.0.1"
description = "Whatever"
authors = ["Hi"]
license = "IDK"
include = ["LICENSE"]

[[tool.poetry.source]]
name = "artifactory-3rdparty"
url = "https://our-domain.com/artifactory/api/pypi/default-pypi-3rdparty/simple"
priority="default"

[[tool.poetry.source]]
name = "artifactory"
url = "https://our-domain.com/artifactory/api/pypi/our-private-repository/simple"

[tool.poetry.dependencies]
python = "3.10.*"

[tool.poetry.group.dev.dependencies]
pytest = "^7.3.1"
```

and then executing ``poetry lock -vvv` we only get
```
Loading configuration file /home/paul/.config/pypoetry/config.toml
Loading configuration file /home/paul/.config/pypoetry/auth.toml
Adding repository artifactory-3rdparty (https://our-domain.com/artifactory/api/pypi/default-pypi-3rdparty/simple) and setting it as the default one
Adding repository artifactory (https://our-domain.com/artifactory/api/pypi/our-private-repository/simple) and setting it as primary
Deactivating the PyPI repository
Using virtualenv: /home/paul/git/image-updater/.venv
Updating dependencies
Resolving dependencies...
   1: fact: testproject is 0.0.1
   1: derived: testproject
   1: fact: testproject depends on pytest (^7.3.1)
   1: selecting testproject (0.0.1)
   1: derived: pytest (>=7.3.1,<8.0.0)
Multiple source configurations found for our-domain.com - artifactory-3rdparty, artifactory
[keyring.backend] Loading KWallet
[keyring.backend] Loading SecretService
[keyring.backend] Loading Windows
[keyring.backend] Loading chainer
[keyring.backend] Loading libsecret
[keyring.backend] Loading macOS
No suitable keyring backend found
No suitable keyring backends were found
Keyring is not available, credentials will be stored and retrieved from configuration files as plaintext.
Creating new session for our-domain.com
Multiple source configurations found for our-domain.com - artifactory-3rdparty, artifactory
[urllib3.connectionpool] Starting new HTTPS connection (1): our-domain.com:443
[urllib3.connectionpool] https://our-domain.com:443 "GET /artifactory/api/pypi/default-pypi-3rdparty/simple/pytest/ HTTP/1.1" 200 None
Source (artifactory-3rdparty): 1 packages found for pytest >=7.3.1,<8.0.0
Multiple source configurations found for our-domain.com - artifactory-3rdparty, artifactory
Creating new session for our-domain.com
Multiple source configurations found for our-domain.com - artifactory-3rdparty, artifactory
[urllib3.connectionpool] Starting new HTTPS connection (1): our-domain.com:443
[urllib3.connectionpool] https://our-domain.com:443 "GET /artifactory/api/pypi/our-private-repository/simple/pytest/ HTTP/1.1" 404 None
Source (artifactory): No packages found for pytest
Source (artifactory): 0 packages found for pytest >=7.3.1,<8.0.0
   1: selecting pytest (7.3.1)
   1: Version solving took 0.612 seconds.
   1: Tried 1 solutions.

Writing lock file
```
and the lock file

```
# This file is automatically @generated by Poetry 1.5.0 and should not be changed by hand.

[[package]]
name = "pytest"
version = "7.3.1"
description = ""
optional = false
python-versions = "*"
files = [
    {file = "pytest-7.3.1-py3-none-any.whl", hash = "sha256:3799fa815351fea3a5e96ac7e503a96fa51cc9942c3753cda7651b93c1cfa362"},
    {file = "pytest-7.3.1.tar.gz", hash = "sha256:434afafd78b1d78ed0addf160ad2b77a30d35d4bdf8af234fe621919d9ed15e3"},
]

[package.source]
type = "legacy"
url = "https://our-domain.com/artifactory/api/pypi/default-pypi-3rdparty/simple"
reference = "artifactory-3rdparty"

[metadata]
lock-version = "2.0"
python-versions = "*"
content-hash = "d87848352c72c891e28e016aa8c5df78d9a-MODIFIED-"
```

Somehow the metadata is not correctly extracted from the pytest dependency if retrieved from other sources. When using PyPi I cannot reproduce this problem. The problem is reproducible in our CI and logically removing `~/.cache/poetry` does not have any effect.

**Comment by dimbleby** [comment] 2023-05-22 15:34
We're back to: please provide a way to reproduce.

(So far the only reproducer that we've seen is resolved by clearing the cache)

**Comment by cquick01** [comment] 2023-05-22 19:27
I'm sort of able to reproduce this again, this time in docker. The entirety of `~/.cache` is completely empty, however the dependencies are only found with `--no-cache` or when pointing to a local `.whl` file.

Fails to find deps:

```
➜  ~/test git:(main) ✗ docker run -it poetry-docker
root@4e0af102c3fb:/opt# ls ~/.cache/
pip
root@4e0af102c3fb:/opt# rm -rf ~/.cache/pip
root@4e0af102c3fb:/opt# ls -la ~/.cache/
total 16
drwxr-xr-x 1 root root 4096 May 22 18:19 .
drwx------ 1 root root 4096 May 22 17:38 ..
root@4e0af102c3fb:/opt# poetry shell
Creating virtualenv opt-y8366zdl-py3.11 in /root/.cache/pypoetry/virtualenvs
Spawning shell within /root/.cache/pypoetry/virtualenvs/opt-y8366zdl-py3.11
root@4e0af102c3fb:/opt# . /root/.cache/pypoetry/virtualenvs/opt-y8366zdl-py3.11/bin/activate
(opt-py3.11) root@4e0af102c3fb:/opt# poetry add cq-test-poetry
Using version ^0.1.0 for cq-test-poetry

Updating dependencies
Resolving dependencies... (0.1s)

Package operations: 1 install, 0 updates, 0 removals

  • Installing cq-test-poetry (0.1.0)

Writing lock file

```

Finds deps with `--no-cache`

```
➜  ~/test git:(main) ✗ docker run -it poetry-docker
root@05a04d106afa:/opt# ls ~/.cache/
pip
root@05a04d106afa:/opt# rm -rf ~/.cache/pip
root@05a04d106afa:/opt# ls -la ~/.cache/
total 16
drwxr-xr-x 1 root root 4096 May 22 18:20 .
drwx------ 1 root root 4096 May 22 17:38 ..
root@05a04d106afa:/opt# poetry shell
Creating virtualenv opt-y8366zdl-py3.11 in /root/.cache/pypoetry/virtualenvs
Spawning shell within /root/.cache/pypoetry/virtualenvs/opt-y8366zdl-py3.11
root@05a04d106afa:/opt# . /root/.cache/pypoetry/virtualenvs/opt-y8366zdl-py3.11/bin/activate
(opt-py3.11) root@05a04d106afa:/opt# poetry add --no-cache cq-test-poetry
Using version ^0.1.0 for cq-test-poetry

Updating dependencies
Resolving dependencies... Downloading https://files.pythonhosted.org/packages/fc/34/3030de6f1370931b9dbb4dad48f6ab1015ab1d32447850b9fc94e60097be/idna-3.4-pyResolving dependencies... (0.7s)

Package operations: 6 installs, 0 updates, 0 removals

  • Installing certifi (2023.5.7)
  • Installing charset-normalizer (3.1.0)
  • Installing idna (3.4)
  • Installing urllib3 (2.0.2)
  • Installing requests (2.31.0)
  • Installing cq-test-poetry (0.1.0)

Writing lock file
```

Installing from `.whl` finds deps:

```
➜  ~/test git:(main) ✗ docker run -it poetry-docker
root@53a33d15cfc7:/opt# ls ~/.cache
pip
root@53a33d15cfc7:/opt# rm -rf ~/.cache/pip/
root@53a33d15cfc7:/opt# ls -la ~/.cache
total 16
drwxr-xr-x 1 root root 4096 May 22 18:21 .
drwx------ 1 root root 4096 May 22 17:38 ..
root@53a33d15cfc7:/opt# poetry shell
Creating virtualenv opt-y8366zdl-py3.11 in /root/.cache/pypoetry/virtualenvs
Spawning shell within /root/.cache/pypoetry/virtualenvs/opt-y8366zdl-py3.11
root@53a33d15cfc7:/opt# . /root/.cache/pypoetry/virtualenvs/opt-y8366zdl-py3.11/bin/activate
(opt-py3.11) root@53a33d15cfc7:/opt# poetry add ./cq_test_poetry-0.1.0-py3-none-any.whl

Updating dependencies
Resolving dependencies... (0.7s)

Package operations: 6 installs, 0 updates, 0 removals

  • Installing certifi (2023.5.7)
  • Installing charset-normalizer (3.1.0)
  • Installing idna (3.4)
  • Installing urllib3 (2.0.2)
  • Installing requests (2.31.0)
  • Installing cq-test-poetry (0.1.0 /opt/cq_test_poetry-0.1.0-py3-none-any.whl)

Writing lock file
```

I've updated https://github.com/cquick01/cq-test-poetry with a Dockerfile, hopefully others can reproduce too now...

**Comment by dimbleby** [comment] 2023-05-22 20:50
@cquick01 once again this works just fine for me.

you keep using `https://pypi.domain.tld/simple` as if that should work for the rest of us but so far as I can see it is just something you have made up?  So I again set up `python -m http.server 8080` on the host, invoked docker with `--add-host=host.docker.internal:host-gateway`, and switched in `url = http://host.docker.internal:8080/simple/`

Then, as before, `poetry add cq-test-poetry` installs both that package and all dependencies.

**Comment by cquick01** [comment] 2023-05-22 21:37
Our real pypi server is not accessible from the outside world.

Here, I've setup a VPS with an nginx server hosting the package at http://ec2-18-219-190-206.us-east-2.compute.amazonaws.com/simple/

And trying to install `cq-test-poetry` from within that instance, with source set to localhost, still fails the same way.

```
ubuntu@ip-172-31-20-126:~/test$ cat pyproject.toml
[tool.poetry]
name = "test"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"

[[tool.poetry.source]]
name = "private_pypi"
url = "http://localhost/simple/"
priority = "supplemental"

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
ubuntu@ip-172-31-20-126:~/test$ poetry add cq-test-poetry
Creating virtualenv test-QNrpxocX-py3.10 in /home/ubuntu/.cache/pypoetry/virtualenvs
Using version ^0.1.0 for cq-test-poetry

Updating dependencies
Resolving dependencies... (0.2s)

Package operations: 1 install, 0 updates, 0 removals

  • Installing cq-test-poetry (0.1.0)

Writing lock file
```

And `--no-cache` works again

```
ubuntu@ip-172-31-20-126:~/test$ poetry remove cq-test-poetry
Updating dependencies
Resolving dependencies... (0.1s)

Package operations: 0 installs, 0 updates, 1 removal

  • Removing cq-test-poetry (0.1.0)

Writing lock file
ubuntu@ip-172-31-20-126:~/test$ poetry add --no-cache cq-test-poetry
Using version ^0.1.0 for cq-test-poetry

Updating dependencies
Resolving dependencies... (0.5s)

Package operations: 6 installs, 0 updates, 0 removals

  • Installing certifi (2023.5.7)
  • Installing charset-normalizer (3.1.0)
  • Installing idna (3.4)
  • Installing urllib3 (2.0.2)
  • Installing requests (2.31.0)
  • Installing cq-test-poetry (0.1.0)

Writing lock file
```

Can you send me a public key and I'll just give you access to the instance?

**Comment by chrisgilmerproj** [comment] 2023-05-22 21:39
> And is your case also resolved by clearing your poetry cache?

I apologize that this took me a while to get back to and reproduce related to my bug report above. I did in fact find that clearing my entire poetry cache did the trick. There did not appear to be another way for it to work with my devpi service as the `primary` other than that.  I used the poetry command itself to clear for me (where `private_repo` is a made up cache):

```
poetry clear cache private_repo --all
```

Just to be sure this worked I did this for several repos I'm in the process of upgrading and was able to reproduce that clearing the cache works for them as well. I was upgrading from 1.3.2 to 1.5.0 in case other folks are curious..

Thanks again for the hard work you put into this repository and issues like this. I know its not always great dealing with user reports.

**Comment by chriskuehl** [comment] 2023-05-22 21:59
We are also running an issue that looks like this with our internal registry and Poetry 1.5. I think I've narrowed it down to some kind of issue with response caching, because if we disable [Etags](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag) on our PyPI registry, the issues go away.

It's been tricky to reproduce this but I've managed to create two small publicly accessible reproduction indexes which have `boto3==1.26.137` and its dependencies. These are identical except that one serves Etags and one does not (one has `etag off;` in the nginx config):

* https://ckuehl.me/tmp/poetry-7961/simple/
* https://ckuehl.me/tmp/poetry-7961/simple-no-etags/

Here is a test `pyproject.toml` I am using:

```toml
[tool.poetry]
name = "test-project"
version = "0.0.0"
authors = []
description = ""

[tool.poetry.dependencies]
python = "^3.11"
boto3 = "1.26.137"

[[tool.poetry.source]]
name = "my-pypi"
url = "https://ckuehl.me/tmp/poetry-7961/simple"
# Switch to this URL to test without etags:
# url = "https://ckuehl.me/tmp/poetry-7961/simple-no-etags"
priority = "default"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

When installing from the first repo, only `boto3` is locked (none of its dependencies are). With the second repo, dependencies are also locked as expected.

## Output with the first registry (Etags enabled)

```
$ venv/bin/poetry --version                                       
Poetry (version 1.5.0)

$ rm -rf poetry.lock ~/.cache/pypoetry && venv/bin/poetry lock -vv
Creating virtualenv test-project-ovAjWgsE-py3.11 in /home/ckuehl/.cache/pypoetry/virtualenvs
Using virtualenv: /home/ckuehl/.cache/pypoetry/virtualenvs/test-project-ovAjWgsE-py3.11
Updating dependencies
Resolving dependencies...
   1: fact: test-project is 0.0.0
   1: derived: test-project
   1: fact: test-project depends on boto3 (1.26.137)
   1: selecting test-project (0.0.0)
   1: derived: boto3 (==1.26.137)
   1: selecting boto3 (1.26.137)
   1: Version solving took 0.486 seconds.
   1: Tried 1 solutions.

Writing lock file

$ venv/bin/poetry show                                            
boto3 1.26.137 
```


## Output with the second registry (Etags disabled)

```
$ venv/bin/poetry --version                              
Poetry (version 1.5.0)

$ rm -rf poetry.lock ~/.cache/pypoetry && venv/bin/poetry lock -vv
Creating virtualenv test-project-ovAjWgsE-py3.11 in /home/ckuehl/.cache/pypoetry/virtualenvs
Using virtualenv: /home/ckuehl/.cache/pypoetry/virtualenvs/test-project-ovAjWgsE-py3.11
Updating dependencies
Resolving dependencies...
   1: fact: test-project is 0.0.0
   1: derived: test-project
   1: fact: test-project depends on boto3 (1.26.137)
   1: selecting test-project (0.0.0)
   1: derived: boto3 (==1.26.137)
   1: fact: boto3 (1.26.137) depends on botocore (>=1.29.137,<1.30.0)
   1: fact: boto3 (1.26.137) depends on jmespath (>=0.7.1,<2.0.0)
   1: fact: boto3 (1.26.137) depends on s3transfer (>=0.6.0,<0.7.0)
   1: selecting boto3 (1.26.137)
   1: derived: s3transfer (>=0.6.0,<0.7.0)
   1: derived: jmespath (>=0.7.1,<2.0.0)
   1: derived: botocore (>=1.29.137,<1.30.0)
   1: fact: s3transfer (0.6.1) depends on botocore (>=1.12.36,<2.0a.0)
   1: selecting s3transfer (0.6.1)
   1: selecting jmespath (1.0.1)
   1: fact: botocore (1.29.137) depends on jmespath (>=0.7.1,<2.0.0)
   1: fact: botocore (1.29.137) depends on python-dateutil (>=2.1,<3.0.0)
   1: fact: botocore (1.29.137) depends on urllib3 (>=1.25.4,<1.27)
   1: selecting botocore (1.29.137)
   1: derived: urllib3 (>=1.25.4,<1.27)
   1: derived: python-dateutil (>=2.1,<3.0.0)
   1: selecting urllib3 (1.26.15)
   1: fact: python-dateutil (2.8.2) depends on six (>=1.5)
   1: selecting python-dateutil (2.8.2)
   1: derived: six (>=1.5)
   1: selecting six (1.16.0)
   1: Version solving took 6.119 seconds.
   1: Tried 1 solutions.

Writing lock file

$ venv/bin/poetry show
boto3           1.26.137 The AWS SDK for Python
botocore        1.29.137 Low-level, data-driven core of boto 3.
jmespath        1.0.1    JSON Matching Expressions
python-dateutil 2.8.2    Extensions to the standard Python datetime module
s3transfer      0.6.1    An Amazon S3 Transfer Manager
six             1.16.0   Python 2 and 3 compatibility utilities
urllib3         1.26.15  HTTP library with thread-safe connection pooling, file post, and more.
```

I'm still trying to figure out exactly what happens; the problem may not be Etags themselves but just that they enable the caching logic which causes the issue. I'm continuing to look into this but since there has been a lot of searching for reproductions I figured I would post this sooner rather than later.

**Comment by dimbleby** [comment] 2023-05-22 22:28
@ralbertazzi looks like this was introduced at https://github.com/python-poetry/poetry/pull/7916

I think the problem is that the the cached file returned by `get_cached_file_for_url` is not the cached wheel, it's the cached http response (with the wheel still somewhere inside it)

**Comment by chriskuehl** [comment] 2023-05-22 22:30
@dimbleby I just came to the same conclusion. Here's a (very rough/awkward, probably not what we want to merge) patch which fixes it for me:

```diff
diff --git a/src/poetry/repositories/http_repository.py b/src/poetry/repositories/http_repository.py
index ae96481a..88977d69 100644
--- a/src/poetry/repositories/http_repository.py
+++ b/src/poetry/repositories/http_repository.py
@@ -78,7 +78,14 @@ class HTTPRepository(CachedRepository):
     def _cached_or_downloaded_file(self, link: Link) -> Iterator[Path]:
         filepath = self._authenticator.get_cached_file_for_url(link.url)
         if filepath:
-            yield filepath
+            import os
+            from cachecontrol.serialize import Serializer
+            serializer = Serializer()
+            with temporary_directory() as temp_dir:
+                path = os.path.join(temp_dir, "wheel.whl")
+                with open(path, "wb") as f:
+                    f.write(serializer.loads(None, open(filepath, "rb").read()).data)
+                yield path
         else:
             self._log(f"Downloading: {link.url}", level="debug")
             with temporary_directory() as temp_dir:
```

Even though this is not a good patch, maybe other people experiencing this could also test it to verify if it's the same root cause for all these repos?

**Comment by cquick01** [comment] 2023-05-22 22:32
Can confirm disabling etags in nginx.conf fixes it for me. I'll try testing with that patch. Thanks guys!

**Comment by kis87988** [comment] 2023-05-23 06:27
Not sure this is relate to a bug under https://github.com/ionrock/cachecontrol/issues/292 or not

**Comment by dimbleby** [comment] 2023-05-23 08:54
I don't think #7619 made a lot of sense.  As this MR shows, the file that is being inspected is an internal implementation detail for cachecontrol.

The suggested patch above, deserializing the file, is presumably doing only what cachecontrol would have done all along.  If poetry repeats a GET that cachecontrol has already seen, cachecontrol can take care of that.

@ralbertazzi

**Comment by ralbertazzi** [comment] 2023-05-23 10:40
I'll check myself but it seems like the best solution is to revert the change. @dimbleby do you have suggestions on how to best deal with the buffer size when the file is already cached locally? We use a `chunk_size: int = 1024` that works well when the package needs to be fetched from the internet, but it's terribly inefficient when the file is already cached locally (a good chunk size in that case would be at least 10x)

**Comment by dimbleby** [comment] 2023-05-23 10:48
in the long run I think the right fix is probably not to use cachecontrol at all for package distributions - we have an `ArtifactCache` as used by the `Chef`, we should find a way to share that for all artifact downloads.  Then there's no ndeed for the additional cache in cachecontrol.

I don't know any particularly good reason for the chunk size to be so small even when downloading from the internet, though I don't know whether this is a change that would be accepted in - I assume - an upcoming patch release.

**Closed** 2023-05-24 16:25 UTC
Labels: kind/bug, area/deps
