### ISSUE TITLE
Poetry resolves argparse as deps with python 3.7

### ISSUE THREAD

**Issue by ClementWalter** [python-poetry/poetry#3906] opened 2021-04-09 17:12 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: 
- **Poetry version**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue

So the problem comes from the argparse lib that has been integrated into python since python >= 3.2 (see [argparse pypi page](https://pypi.org/project/argparse/)).

When poetry finds a package that depends on argparse, even though the pyproject states python>=3.2 (python 3.7 in my example), it adds argparse==1.4 to the requirements.

This creates a conflict. See this MWE:

```
[tool.poetry]
name = "tmp_project"
version = "0.1.0"
description = ""
authors = ["Clement Walter <clement0walter@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7.1"
pytest = "^6.2.3"
nnunet = "^1.6.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

Poetry resolves that argparse is required because nnunet > batchgenerators > unittest2 > argparse
It then installs argparse==1.4 which is not necessary because python=3.7 and not compatible, for instance, with pytest 6.2.3

Running `pytest` works because of the order of the paths in `sys.path` but enforcing the `site-packages` path to be the first one creates a crash. See logs on my computer:

```
 (tmp) > pytest
==================================================== test session starts ====================================================
platform darwin -- Python 3.7.9, pytest-6.2.3, py-1.10.0, pluggy-0.13.1
rootdir: /Users/clementwalter/Documents/tmp_project
collected 0 items

=================================================== no tests ran in 0.00s ===================================================
 ✘ > PYTHONPATH=/Users/clementwalter/.pyenv/versions/tmp/lib/python3.7/site-packages pytest
Traceback (most recent call last):
  File "/Users/clementwalter/.pyenv/versions/tmp/bin/pytest", line 8, in <module>
    sys.exit(console_main())
  File "/Users/clementwalter/.pyenv/versions/tmp/lib/python3.7/site-packages/_pytest/config/__init__.py", line 185, in console_main
    code = main()
  File "/Users/clementwalter/.pyenv/versions/tmp/lib/python3.7/site-packages/_pytest/config/__init__.py", line 143, in main
    config = _prepareconfig(args, plugins)
  File "/Users/clementwalter/.pyenv/versions/tmp/lib/python3.7/site-packages/_pytest/config/__init__.py", line 319, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File "/Users/clementwalter/.pyenv/versions/tmp/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/clementwalter/.pyenv/versions/tmp/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/clementwalter/.pyenv/versions/tmp/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/Users/clementwalter/.pyenv/versions/tmp/lib/python3.7/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/Users/clementwalter/.pyenv/versions/tmp/lib/python3.7/site-packages/_pytest/helpconfig.py", line 100, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File "/Users/clementwalter/.pyenv/versions/tmp/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/clementwalter/.pyenv/versions/tmp/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/clementwalter/.pyenv/versions/tmp/lib/python3.7/site-packages/_pytest/config/__init__.py", line 1003, in pytest_cmdline_parse
    self.parse(args)
  File "/Users/clementwalter/.pyenv/versions/tmp/lib/python3.7/site-packages/_pytest/config/__init__.py", line 1283, in parse
    self._preparse(args, addopts=addopts)
  File "/Users/clementwalter/.pyenv/versions/tmp/lib/python3.7/site-packages/_pytest/config/__init__.py", line 1157, in _preparse
    self._initini(args)
  File "/Users/clementwalter/.pyenv/versions/tmp/lib/python3.7/site-packages/_pytest/config/__init__.py", line 1074, in _initini
    args, namespace=copy.copy(self.option)
  File "/Users/clementwalter/.pyenv/versions/tmp/lib/python3.7/site-packages/_pytest/config/argparsing.py", line 155, in parse_known_and_unknown_args
    optparser = self._getparser()
  File "/Users/clementwalter/.pyenv/versions/tmp/lib/python3.7/site-packages/_pytest/config/argparsing.py", line 113, in _getparser
    optparser = MyOptionParser(self, self.extra_info, prog=self.prog)
  File "/Users/clementwalter/.pyenv/versions/tmp/lib/python3.7/site-packages/_pytest/config/argparsing.py", line 387, in __init__
    allow_abbrev=False,
TypeError: __init__() got an unexpected keyword argument 'allow_abbrev'
```

**Comment by abn** [comment] 2021-04-09 17:32
@ClementWalter this seems to me like an issue of incorrect metadata.

```console
$ curl -sL https://pypi.org/pypi/batchgenerators/json | jq '.info.requires_dist'
[
  "pillow (>=7.1.2)",
  "numpy (>=1.10.2)",
  "scipy",
  "scikit-image",
  "scikit-learn",
  "future",
  "unittest2",
  "threadpoolctl"
]
$ curl -sL https://pypi.org/pypi/unittest2/json | jq '.info.requires_dist'
null
```

In this case `batchgenerators` specifies `unittest2` as a dependency without any `python_version` markers. Since `unittest2` does not declare the `requires_dist` field, poetry falls back to metadata from wheel and/or sdist. And if you look at `unittest2` wheel metadata, you will see that `argparse` is declared again as a dependency without any python version constraints.

```
Metadata-Version: 2.0
Name: unittest2
Version: 1.1.0
Summary: The new features in unittest backported to Python 2.4+.
Home-page: http://pypi.python.org/pypi/unittest2
Author: Robert Collins
Author-email: rbtcollins@hp.com
License: UNKNOWN
Keywords: unittest,testing,tests
Platform: UNKNOWN
Classifier: Development Status :: 4 - Beta
Classifier: Environment :: Console
Classifier: Intended Audience :: Developers
Classifier: License :: OSI Approved :: BSD License
Classifier: Programming Language :: Python
Classifier: Programming Language :: Python :: 2.4
Classifier: Programming Language :: Python :: 2.5
Classifier: Programming Language :: Python :: 2.6
Classifier: Programming Language :: Python :: 2.7
Classifier: Operating System :: OS Independent
Classifier: Topic :: Software Development :: Libraries
Classifier: Topic :: Software Development :: Libraries :: Python Modules
Classifier: Topic :: Software Development :: Testing
Requires-Dist: argparse
Requires-Dist: six (>=1.4)
Requires-Dist: traceback2
```

**Comment by abn** [comment] 2021-04-09 17:37
Further, the metadata for `argparse` does not list python version constraints.

```console
$ curl -sL https://pypi.org/pypi/argparse/json | jq '.info.requires_python'
null
```

The wheel metadata also fails to state the `Requires-Python` metadata.

```
Metadata-Version: 2.0
Name: argparse
Version: 1.4.0
Summary: Python command-line parsing library
Home-page: https://github.com/ThomasWaldmann/argparse/
Author: Thomas Waldmann
Author-email: tw@waldmann-edv.de
License: Python Software Foundation License
Keywords: argparse command line parser parsing
Platform: any
Classifier: Development Status :: 5 - Production/Stable
Classifier: Environment :: Console
Classifier: Intended Audience :: Developers
Classifier: License :: OSI Approved :: Python Software Foundation License
Classifier: Operating System :: OS Independent
Classifier: Programming Language :: Python
Classifier: Programming Language :: Python :: 2
Classifier: Programming Language :: Python :: 3
Classifier: Programming Language :: Python :: 2.3
Classifier: Programming Language :: Python :: 2.4
Classifier: Programming Language :: Python :: 2.5
Classifier: Programming Language :: Python :: 2.6
Classifier: Programming Language :: Python :: 2.7
Classifier: Programming Language :: Python :: 3.0
Classifier: Programming Language :: Python :: 3.1
Classifier: Programming Language :: Python :: 3.2
Classifier: Programming Language :: Python :: 3.3
Classifier: Programming Language :: Python :: 3.4
Classifier: Topic :: Software Development
```

**Comment by abn** [comment] 2021-04-09 17:39
Closing this as the issue is invalid metadata in the dependencies.

**Closed** 2021-04-09 17:38 UTC
Labels: Invalid Dependency Metadata
