### ISSUE TITLE
`poetry update` uses `secondary` repo for all dependencies listed in `pyproject.toml`

### ISSUE THREAD

**Issue by diegoquintanav** [python-poetry/poetry#5538] opened 2022-05-04 13:59 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: docker container `python:3.9`
- **Poetry version**: 1.1.13
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: <https://gist.github.com/diegoquintanav/df62503eebb058818554eb768bf93f5c>

## Issue

- I install my project inside a docker container
- everything works fine: pipy dependencies are installed from pipy, my custom pipy dependency is installed from source
- I  access to the container shell
- run `poetry update`
- I get an error:
```python
401 Client Error: Unauthorized for url: https://pypi.myrepo.org/simple/pytest/
```
Poetry is looking for `pytest` in `myrepo` although it did not did so when doing `install`. What am I doing wrong?

Note that the URL of `pypi.myrepo.org` is masked and I can't provide credentials for obvious reasons.

**Comment by abn** [comment] 2022-05-04 16:54
This is a duplicate of #4704 for an explanation of what is happening see https://github.com/python-poetry/poetry/issues/4704#issuecomment-1111380597.

**Closed by abn** 2022-05-04 16:54 UTC
Labels: Bug, Triage
