### ISSUE TITLE
poetry selects wrong python version when markers present

### ISSUE THREAD

**Issue by maciejskorski** [python-poetry/poetry#4959] opened 2021-12-31 11:29 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: linux + Python 3.8.10
- **Poetry version**: 1.2.0a2 (recent master)

## Issue
Multiple constraints on python version fail when combined with valid markers.

This does work fine
```
# selecting 1.3.1 matching the system
[tool.poetry.dependencies]
python = "~3.8"
pandas = [
    {version="1.3.2",python='~3.9'},
    {version="1.3.1",python='~3.8'},
]
```
but not this
```
# selecting incompatible 1.3.2 and ignoring 1.3.1 - error
[tool.poetry.dependencies]
python = "~3.8"
pandas = [
    {version="1.3.2",python='~3.9',markers="sys_platform=='linux'"},
    {version="1.3.1",python='~3.8'},
]
```
when I move everything to markers it works fine again

```
# selecting 1.3.1 - fine!
[tool.poetry.dependencies]
python = "~3.8"
pandas = [
    {version="1.3.2",markers="python_version=='3.9' and sys_platform=='linux'"},
    {version="1.3.1",markers="python_version=='3.8'"},
]
```

**Comment by radoering** [comment] 2021-12-31 14:05
Probably duplicate of #3444

**Comment by maciejskorski** [comment] 2022-01-01 15:12
Related to #3444 but highlights bit different issues.  The logs show that `poetry` this these are different packages.
```
  • Installing pandas (1.3.1)
  • Installing pandas (1.3.2)
 ```

**Closed** 2022-04-26 21:33 UTC
Labels: Bug, Triage
