### ISSUE TITLE
(🐞) poetry only ever validates the python version when adding a new env, not with any other commands

### ISSUE THREAD

**Issue by KotlinIsland** [python-poetry/poetry#5230] opened 2022-02-24 04:05 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10
- **Poetry version**: Poetry version 1.1.13
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 
```toml
[tool.poetry.dependencies]
python = "^3.11"
```
## Issue

```
>poetry env list
untitled-HfdF1kCl-py3.10
untitled-HfdF1kCl-py3.11 (Activated)

>poetry env use python3.10
Using virtualenv: C:\Users\amongus\AppData\Local\pypoetry\Cache\virtualenvs\untitled-HfdF1kCl-py3.10

>poetry env list   
untitled-HfdF1kCl-py3.10 (Activated)
untitled-HfdF1kCl-py3.11

>poetry install
Installing dependencies from lock file

>poetry check
All set!

>poetry env remove python3.10
Deleted virtualenv: C:\Users\amongus\AppData\Local\pypoetry\Cache\virtualenvs\untitled-HfdF1kCl-py3.10

>poetry env use python3.10

  NoCompatiblePythonVersionFound

  The specified Python version (3.10.2) is not supported by the project (^3.11).
  Please choose a compatible version or loosen the python constraint specified in the pyproject.toml file.

  at ~\AppData\Roaming\pypoetry\venv\Lib\site-packages\poetry\utils\env.py:708 in create_venv
       704│             # If an executable has been specified, we stop there
       705│             # and notify the user of the incompatibility.
       706│             # Otherwise, we try to find a compatible Python version.
       707│             if executable:
    →  708│                 raise NoCompatiblePythonVersionFound(
       709│                     self._poetry.package.python_versions, python_patch
       710│                 )
       711│
       712│             io.write_line(
```

I would expect all of these commands (except the remove) to show errors (or warnings, if only listing envs)

**Comment by finswimmer** [comment] 2022-02-24 10:37
Hey @KotlinIsland,

this is a duplicate of https://github.com/python-poetry/poetry/issues/3426.

fin swimmer

**Closed by finswimmer** 2022-02-24 10:37 UTC
Labels: Bug, Triage
