### ISSUE TITLE
Missing wheel when poetry lock --no-update is run on macos

### ISSUE THREAD

**Issue by sileht** [python-poetry/poetry#7125] opened 2022-11-30 16:05 UTC
- **Poetry version**: 1.2.2
- **Python version**: seen at least in 3.10.8 and 3.11
- **OS version and name**: MacOS 13.0.1 on arm m1
- **pyproject.toml**: https://gist.github.com/sileht/a80dbab1fbffc20095da1bae77bad425

- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

On a project where the lock file is up to date.

When we run `poetry lock --no-update` in a ubuntu 20.04 amd64, nothing is updated.

But when we run it on MacOS, we see some unexpected changes (see below), some required wheels are missing.

```
$ poetry lock --no-update
$ git diff
diff --git a/poetry.lock b/poetry.lock
index 12d818279..b14ace9d4 100644
--- a/poetry.lock
+++ b/poetry.lock
@@ -2067,7 +2067,7 @@ tokenize-rt = ">=2.1"

 [metadata]
 lock-version = "1.1"
-python-versions = "~3.11"
+python-versions = ">=3.11,<4.0"
 content-hash = "1347bfabb59dab124409181672415383dbb893453a61785d268f00a09174571c"

 [metadata.files]
@@ -3212,13 +3212,6 @@ pyyaml = [
     {file = "PyYAML-6.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl", hash = "sha256:f84fbc98b019fef2ee9a1cb3ce93e3187a6df0b2538a651bfb890254ba9f90b5"},
     {file = "PyYAML-6.0-cp310-cp310-win32.whl", hash = "sha256:2cd5df3de48857ed0544b34e2d40e9fac445930039f3cfe4bcc592a1f836d513"},
     {file = "PyYAML-6.0-cp310-cp310-win_amd64.whl", hash = "sha256:daf496c58a8c52083df09b80c860005194014c3698698d1a57cbcfa182142a3a"},
-    {file = "PyYAML-6.0-cp311-cp311-macosx_10_9_x86_64.whl", hash = "sha256:d4b0ba9512519522b118090257be113b9468d804b19d63c71dbcf4a48fa32358"},
-    {file = "PyYAML-6.0-cp311-cp311-macosx_11_0_arm64.whl", hash = "sha256:81957921f441d50af23654aa6c5e5eaf9b06aba7f0a19c18a538dc7ef291c5a1"},
-    {file = "PyYAML-6.0-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl", hash = "sha256:afa17f5bc4d1b10afd4466fd3a44dc0e245382deca5b3c353d8b757f9e3ecb8d"},
-    {file = "PyYAML-6.0-cp311-cp311-manylinux_2_17_s390x.manylinux2014_s390x.whl", hash = "sha256:dbad0e9d368bb989f4515da330b88a057617d16b6a8245084f1b05400f24609f"},
-    {file = "PyYAML-6.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl", hash = "sha256:432557aa2c09802be39460360ddffd48156e30721f5e8d917f01d31694216782"},
-    {file = "PyYAML-6.0-cp311-cp311-win32.whl", hash = "sha256:bfaef573a63ba8923503d27530362590ff4f576c626d86a9fed95822a8255fd7"},
-    {file = "PyYAML-6.0-cp311-cp311-win_amd64.whl", hash = "sha256:01b45c0191e6d66c470b6cf1b9531a771a83c1c4208272ead47a3ae4f2f603bf"},
     {file = "PyYAML-6.0-cp36-cp36m-macosx_10_9_x86_64.whl", hash = "sha256:897b80890765f037df3403d22bab41627ca8811ae55e9a722fd0392850ec4d86"},
     {file = "PyYAML-6.0-cp36-cp36m-manylinux_2_17_aarch64.manylinux2014_aarch64.whl", hash = "sha256:50602afada6d6cbfad699b0c7bb50d5ccffa7e46a3d738092afddc1f9758427f"},
     {file = "PyYAML-6.0-cp36-cp36m-manylinux_2_17_s390x.manylinux2014_s390x.whl", hash = "sha256:48c346915c114f5fdb3ead70312bd042a953a8ce5c7106d5bfb1a5254e47da92"},
@@ -3804,7 +3797,6 @@ xmltodict = [
     {file = "xmltodict-0.13.0.tar.gz", hash = "sha256:341595a488e3e01a85a9d8911d8912fd922ede5fecc4dce437eb4b6c8d037e56"},
 ]
 yamllint = [
-    {file = "yamllint-1.28.0-py2.py3-none-any.whl", hash = "sha256:89bb5b5ac33b1ade059743cf227de73daa34d5e5a474b06a5e17fc16583b0cf2"},
     {file = "yamllint-1.28.0.tar.gz", hash = "sha256:9e3d8ddd16d0583214c5fdffe806c9344086721f107435f68bad990e5a88826b"},
 ]
 yarl = [
```

`-vvv` logs: https://gist.github.com/sileht/e67e8e310da04fafd3f81115cdb588e4

**Comment by sileht** [comment] 2022-11-30 16:13
Seems to work correctly on MacOS 12.6.

**Comment by sileht** [comment] 2022-11-30 17:03
I just clean up the cache, and indeed it solves the issues for me.

This thing is that a package like PyYAML does not release a new version to support the new Python versions. They only build new wheels.

So for each python release, I will get the issue again and again. I'm pretty sure I'm not alone.

For PyYAML, they are a funny side effect, not really a poetry issue, but if people just copy/paste the doc:

```
try:
    from yaml import CLoader as Loader, CDumper as Dumper
except ImportError:
    from yaml import Loader, Dumper
```

They will get the slow implementation of PyYAML, when the poetry cache is outdated.

I wonder if something could be done to automatically detected the missing files.

I should be able to propose a PR if this is a good idea. And if I have a bit of guidance about where I should look in the codebase.

**Comment by neersighted** [comment] 2022-11-30 17:30
Right now the baby and the bathwater go together; we'd need separate logic to check for new files from the current caching, which lumps everything together. That might be a better direction to take in the long run as package metadata is expensive and checking for files is cheap; but it will be rather invasive.

The code in question lives in the `Repository` class/subclasses. I'm going to close this as not a bug, but feel free to open an issue for the above proposed refactor if you are interested/can't find a duplicate.

**Closed by neersighted** 2022-11-30 17:30 UTC
Labels: kind/bug, status/triage
