### ISSUE TITLE
Poetry failed after upgrade to Ubuntu 19.04

### ISSUE THREAD

**Issue by mbello** [python-poetry/poetry#1071] opened 2019-05-02 20:20 UTC
- [x ] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [ x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- Ubuntu 19.04
- 1.0.0.a2

## Issue
After upgrading from Ubuntu 18.10 to 19.04 (which also upgrade python from 3.6.6 to 3.7.3, running poetry would result in the following error:
```
[ValueError]
No JSON object could be decoded

```
Also, the projects I had opened on PyCharms (all of them use poetry with .venv folder) were giving "The SDK seems invalid" virtualenv errors. There was something wrong with the .venv folder that was also triping PyCharm.

I managed to fix it by luck running the command below from inside the project directory:
`poetry use env /usr/bin/python3`

I am reporting it here because I thing poetry should be able to better handle this situation.

**Comment by Imaclean74** [comment] 2019-05-03 03:41
this may be a duplicate of #654. Could you try running :

```bash
.venv/bin/python
```
And see if it gives an error.  In my case site_packages wasn't being populated correctly - which left the venv and python inside it - unusable. This might also explain your pycharm errors.

This is the error I get 
```
Could not find platform independent libraries <prefix>

Could not find platform dependent libraries <exec_prefix>

Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]

Fatal Python error: initfsencoding: Unable to get the locale encoding

ModuleNotFoundError: No module named 'encodings'
```

**Comment by mbello** [comment] 2019-05-03 19:02
> this may be a duplicate of #654. Could you try running :
> 
> ```shell
> .venv/bin/python
> ```

Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007f9e55d9d740 (most recent call first):
Aborted (core dumped)

Same thing with .venv/bin/python3.

Also ran `poetry update -vvv`

[ValueError]
No JSON object could be decoded

Traceback (most recent call last):
  File "/home/mbello/.poetry/lib/poetry/_vendor/py2.7/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/home/mbello/.poetry/lib/poetry/_vendor/py2.7/clikit/api/command/command.py", line 112, in handle
    status_code = self._do_handle(args, io)
  File "/home/mbello/.poetry/lib/poetry/_vendor/py2.7/clikit/api/command/command.py", line 152, in _do_handle
    self._dispatcher.dispatch(ConsoleEvents.PRE_HANDLE.value, event)
  File "/home/mbello/.poetry/lib/poetry/_vendor/py2.7/clikit/api/event/event_dispatcher.py", line 22, in dispatch
    self._do_dispatch(listeners, event_name, event)
  File "/home/mbello/.poetry/lib/poetry/_vendor/py2.7/clikit/api/event/event_dispatcher.py", line 89, in _do_dispatch
    listener(event, event_name, self)
  File "/home/mbello/.poetry/lib/poetry/console/config/application_config.py", line 76, in set_env
    '.'.join(str(v) for v in current_env.version_info[:3])
  File "/home/mbello/.poetry/lib/poetry/utils/env.py", line 577, in version_info
    return tuple(self.marker_env['version_info'])
  File "/home/mbello/.poetry/lib/poetry/utils/env.py", line 593, in marker_env
    self._marker_env = self.get_marker_env()
  File "/home/mbello/.poetry/lib/poetry/utils/env.py", line 783, in get_marker_env
    return json.loads(output)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError('No JSON object could be decoded')

Then on this project I ran `poetry env use /usr/bin/python3` and everything works again.

**Comment by Imaclean74** [comment] 2019-05-04 01:29
Thanks, @mbello . So definitely the same issue. PR #1069 *should* resolve it. Thanks to @sdispater's quick merge - 0.12.15 should have the fix. You'll need to delete the venv and re run the poetry command.
There is another issue - which is that the invalid venv errors are masked by the JSON error. I'm making a PR for that now.

**Comment by funkyfuture** [comment] 2019-06-21 10:54
@mbello is this issue resolved with newer releases and can thus be closed?

**Comment by kierun** [comment] 2019-10-28 12:32
I get the same error with `1.0.0b3`, installed via pip on Python 2.7.

```
$ poetry install -vvv --ansi
Using virtualenv: /home/rprs/.cache/pypoetry/virtualenvs/devtree-WCzw6nhT-py2.7
Installing dependencies from lock file

[ValueError]
No JSON object could be decoded

Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/rprs/.local/bin/poetry", line 8, in <module>
    sys.exit(main())
  File "/home/rprs/.local/lib/python2.7/site-packages/poetry/console/__init__.py", line 5, in main
    return Application().run()
  File "/home/rprs/.local/lib/python2.7/site-packages/clikit/console_application.py", line 139, in run
    trace.render(io, simple=isinstance(e, CliKitException))
  File "/home/rprs/.local/lib/python2.7/site-packages/clikit/ui/components/exception_trace.py", line 57, in render
    self._render_traceback(io, tb)
  File "/home/rprs/.local/lib/python2.7/site-packages/clikit/ui/components/exception_trace.py", line 67, in _render_traceback
    io.write_line("".join(traceback.format_list(frames)))
  File "/usr/lib64/python2.7/traceback.py", line 39, in format_list
    item = '  File "%s", line %d, in %s\n' % (filename,lineno,name)
TypeError: %d format: a number is required, not str
```

**Comment by kierun** [comment] 2019-10-28 14:45
My problem was unrelated. Since I was running this in a basic docker container, my `locals` were incorrectly set so I was getting an extra warning in front of some commands: `warning: setlocale: LC_ALL: cannot change locale (en_GB.UTF-8)`. These are clearly not JSON!

While it is an edge case, a more helpful error message might be in order. Or even printing the erroneous JSON in debug mode or something like that.

**Closed** 2020-05-03 18:30 UTC
