### ISSUE TITLE
Error adding a git dependency : parsing the package version?

### ISSUE THREAD

**Issue by alexander-belikov** [python-poetry/poetry#4723] opened 2021-11-08 23:16 UTC
- [ x ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [ x ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ x ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- OS : **Linux Mint 20.2**
- Poetry version : **1.2.0a2**
- pyenv version:  **2.2.0**

## Issue

Adding a git dependency terminates in an error after either `poetry add git+ssh://git@github.com/path/repo.git` or manually modifying `pyproject.toml` and running `poetry update`, see the error message below. I've tried everything possible, like tweaking the version of the git package or trying different python or poetry versions. Have anyone encountered something like this?

```shell
   4  ~/.local/lib/python3.8/site-packages/poetry/installation/pip_installer.py:266 in install_git
       264│         pkg.develop = package.develop
       265│ 
     → 266│         self.install_directory(pkg)
       267│ 

   3  ~/.local/lib/python3.8/site-packages/poetry/installation/pip_installer.py:204 in install_directory
       202│             # so we need to check the version of pip to know
       203│             # if we can rely on the build system
     → 204│             legacy_pip = self._env.pip_version < self._env.pip_version.__class__(
       205│                 19, 0, 0
       206│             )

   2  <string>:10 in __init__

   1  ~/.local/lib/python3.8/site-packages/poetry/core/version/pep440/version.py:44 in __post_init__
        42│         # we do this here to handle both None and tomlkit string values
        43│         object.__setattr__(
     →  44│             self, "text", self.to_string() if not self.text else str(self.text)
        45│         )
        46│ 

  AttributeError

  'int' object has no attribute 'to_string'

  at ~/.local/lib/python3.8/site-packages/poetry/core/version/pep440/version.py:113 in to_string
      109│         version_string = dash.join(
      110│             filter(
      111│                 bool,
      112│                 [
    → 113│                     self.release.to_string(),
      114│                     self.pre.to_string(short) if self.pre else self.pre,
      115│                     self.post.to_string(short) if self.post else self.post,
      116│                     self.dev.to_string(short) if self.dev else self.dev,
      117│                 ],
```

**Comment by alexander-belikov** [comment] 2021-11-12 10:18
To be able to work I have currently 
1. cloned the remote github repo
2. included `setup.py`  
3. use good old `python setup.py develop`

That defeats the purpose of using poetry...

**Comment by finswimmer** [comment] 2021-11-12 13:08
Hello @alexander-belikov,

can you please show at least the `pyproject.toml` of your current project and the project you are trying to add as a dependency?

At best, you create a minimal, public available project to reproduce your problem.

fin swimmer

**Comment by alexander-belikov** [comment] 2021-11-12 14:42
Hello @finswimmer , 

thank you!

Here I've created two dummy packages: [](url)

[poetry_check_a](https://github.com/alexander-belikov/poetry_check_a) and [poetry_check_b](https://github.com/alexander-belikov/poetry_check_b). Upon `poetry update` `poetry_check_b` should fetch and install `poetry_check_a`. The stack trace is in the [poetry_check_b/README.md](https://github.com/alexander-belikov/poetry_check_b/blob/main/README.md).

Best,
Alexander

**Comment by finswimmer** [comment] 2021-11-12 16:59
Hallo @alexander-belikov,

thanks for providing a minimal example :+1: 

For me the error message is different:

```
$ poetry install
Installing dependencies from lock file

Package operations: 1 install, 0 updates, 0 removals

  • Installing poetry-check-a (1.0.1 c26bc6f): Failed

  ModuleOrPackageNotFound

  No file/folder found for package poetry-check-a

  at ~/.local/share/pypoetry/venv/lib/python3.9/site-packages/poetry/core/masonry/utils/module.py:67 in __init__
       63│                             "from": str(src.relative_to(self._path)),
       64│                         }
       65│                     ]
       66│                 else:
    →  67│                     raise ModuleOrPackageNotFound(
       68│                         "No file/folder found for package {}".format(name)
       69│                     )
       70│ 
       71│         for package in packages:
```

same on `poetry update`.


poetry is correct here by saying `ModuleOrPackageNotFound`. `poetry-check-a` doesn't contain any package data. You need a `poetry_check_a` folder in the root folder of that project, which contains at least one python file, e.g. `__init__.py`.

fin swimmer

**Comment by alexander-belikov** [comment] 2021-11-12 17:12
Hi @finswimmer , what version of poetry are you using? I'm on `1.2.0a2` .
I've updated both repos `poetry-check-a` and `poetry-check-b` with a `poetry-check-a/__init__py` and `poetry-check-b/__init__py`. How far are you able to proceed now?

Best, Alexander

**Comment by finswimmer** [comment] 2021-11-12 19:21
This works now with no problems:

```
$ poetry install
Installing dependencies from lock file

Package operations: 1 install, 0 updates, 0 removals

  • Installing poetry-check-a (1.0.1 aeb4411)

Installing the current project: poetry_check_b (0.2.0)

$ poetry install
Installing dependencies from lock file

Package operations: 1 install, 0 updates, 0 removals

  • Installing poetry-check-a (1.0.1 aeb4411)

Installing the current project: poetry_check_b (0.2.0)
```

Poetry version is

```
poetry --version
Poetry (version 1.2.0a2)
```

**Comment by finswimmer** [comment] 2021-12-17 08:18
I'm closing this because we haven't receive no more information for a long time now.

Feel free to leave a comment if you disagree.

**Closed by finswimmer** 2021-12-17 08:18 UTC
Labels: Bug, Triage, Awaiting Reponse

**Comment by jylind** [comment] 2022-01-10 12:46
Hello,
I’m getting the same attribute error as explained in the initial issue. Both, with code in the provided repos and with my own code.

It turns out (at least for me) that the cause is related to experimental feature or, in fact, not using it.

So, when experimental.new-installer is used it seems to works and when experimental feature is set to false it fails like this:

```
D:\Temp\poetry_fail\poetry_check_b-main>poetry install
Installing dependencies from lock file

Package operations: 1 install, 0 updates, 0 removals

  - Installing poetry-check-a (1.0.1 aeb4411)

  AttributeError

  'int' object has no attribute 'to_string'

  at D:\Program Files\poetry\venv\lib\site-packages\poetry\core\version\pep440\version.py:113 in to_string
      109│         version_string = dash.join(
      110│             filter(
      111│                 bool,
      112│                 [
    → 113│                     self.release.to_string(),
      114│                     self.pre.to_string(short) if self.pre else self.pre,
      115│                     self.post.to_string(short) if self.post else self.post,
      116│                     self.dev.to_string(short) if self.dev else self.dev,
      117│                 ],

```

PS. I did have some cache related problems with the experimental.new-installer, so I could not use it.

**Comment by alecgunny** [comment] 2022-03-02 20:32
I've encountered this same issue when trying to use the `Installer` directly in the manner outlined in #1053. The issue seems to be [here](https://github.com/python-poetry/poetry/blob/16c26106bfe157472974b4e8013a0ec9cb1babc4/src/poetry/installation/pip_installer.py#L208-L210)
```python
            legacy_pip = self._env.pip_version < self._env.pip_version.__class__(
                19, 0, 0
            )
```
which attempts to initialize the `Version` object directly from `int`s, rather than using the `Version.from_parts` class method. I think this should be solved by just changing this line to

```python
            legacy_pip = self._env.pip_version < self._env.pip_version.__class__.from_parts(
                19, 0, 0
            )
```

Happy to open a PR to fix this, but might take me a bit longer to contribute tests.

**Comment by Ierezell** [comment] 2022-04-08 16:14
I have the same problem as described above : 

```
  AttributeError

  'int' object has no attribute 'to_string'

  at ~/.local/share/pypoetry/venv/lib/python3.8/site-packages/poetry/core/version/pep440/version.py:122 in to_string
      118│         version_string = dash.join(
      119│             filter(
      120│                 bool,
      121│                 [
    → 122│                     self.release.to_string(),
      123│                     self.pre.to_string(short) if self.pre else self.pre,
      124│                     self.post.to_string(short) if self.post else self.post,
      125│                     self.dev.to_string(short) if self.dev else self.dev,
      126│                 ],
```

That is also coming from the config

```
experimental.new-installer = false # => Raise this error 
experimental.new-installer = true # => Work fine
```

Have a great day

**Comment by coderanger** [comment] 2022-04-30 23:57
Can confirm the combo of `mypackage = { path = "../mypackage/", develop = true }` where `mypackage` is using Poetry too and the new-installer is disabled results in a 100% crash.
