### ISSUE TITLE
Git Dependency Resolution Failure

### ISSUE THREAD

**Issue by petervaro** [python-poetry/poetry#3740] opened 2021-02-27 13:43 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Arch Linux (latest)
- **Poetry version**: `1.1.4`
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: _see below_

## Issue

Let's assume I have an empty dummy project, that defines the following dependency:

```toml
[tool.poetry.dependencies.poetry-semver]
git = "git@github.com:python-poetry/semver.git"
rev = "906a0e1"
```

And then I run:

```bash
$ poetry install --no-root
Updating dependencies
Resolving dependencies... (1.6s)

Writing lock file

Package operations: 1 install, 0 updates, 0 removals

  • Installing poetry-semver (0.1.0 906a0e1)
```

It installs correctly, as expected.  Now I change the `rev` to a different one:

```toml
[tool.poetry.dependencies.poetry-semver]
git = "git@github.com:python-poetry/semver.git"
rev = "906a0e1"
```

And then I run the following:

```bash
$ poetry update
Updating dependencies
Resolving dependencies... (1.7s)

Writing lock file

No dependencies to install or update
```

Or even if I run:

```bash
$ poetry update poetry-semver
Updating dependencies
Resolving dependencies... (1.7s)

No dependencies to install or update
```

Or even if I run:

```bash
$ poetry install --no-root --extras private-dependencies
Installing dependencies from lock file

No dependencies to install or update
```

As you can see, I'm just unable to make `poetry` update that package.  The lock-file is updated properly when I change the `rev` value, every time.  Despite all my efforts, even trying to force-run `poetry lock` I just wasn't able to make this work.

## Potential Root Cause of the Problem

I tried to debug it myself but then I gave up on this for a myriad of reasons, but mainly to keep my sanity intact.  However this is what I found out:

- In `poetry/puzzle/solver.py:Solver.solve` Poetry never steps into the first branch of the following `if` statement:
  ```python
  if pkg.source_type == "git" and package.source_type == "git":
      # ...
  ```
  That's because `pkg.source_type` is not `"git"` albeit `package.source_type` is.
- This happens because in `poetry/repositories/installed_repositories.py:InstalledRepository.load` when Poetry relies on `importlib.metadata.distribution` to determine the version the `Distribution.metadata['version']` will return `0.1.0` instead of any kind of Git information.  Maybe this is the expected behaviour, I'm not familiar with the `importlib.metadata` module's functionality.  However, that version information is then passed down to the `poetry/core/packages.py:Package`, hence the `package` at this point does not contain the `source_type` information.
- Even if the previous point is not the actual problem (which I assume it is not based on the lines following) then further below in this method the `poetry/respositories/installed_repositories.py:InstalledRepository.get_package_paths` returns an empty `set`, thus the previously mentioned `load` method never steps into the `if paths:` branch and does not test the package with the  `cls.is_vcs_package` and therefore does not modify the package details with the `cls.set_package_vcs_properties`.

In light of the above, I don't even have the foggiest how this was ever working / tested.

**Comment by amanda-wee** [comment] 2021-03-08 02:05
This is a duplicate of: https://github.com/python-poetry/poetry/issues/2921

**Closed** 2021-04-05 06:53 UTC
Labels: Duplicate
