### ISSUE TITLE
poetry show -t --no-dev should exclude all dependencies of any dev-dep

### ISSUE THREAD

**Issue by dazza-codes** [python-poetry/poetry#3448] opened 2020-12-04 03:06 UTC
Try

```
poetry init  # etc etc
poetry add -D py-dev-deps
poetry show -t --no-dev
```

It shows all the dependencies of the `py-dev-deps` package, which itself is a dev-dep.  The `--no-dev` flag should traverse the dep-tree of any dev-dep to exclude the entire tree.  It might only include dependencies that are in the project deps (i.e. some intersection of the project deps and anything deep in a dev-dep tree, e.g. some very common libs are likely to be both project deps and somewhere in the dep-tree of the dev-deps).

**Comment by glencairn** [comment] 2020-12-09 16:06
Hey @dazza-codes, this looks like a duplicate of #3295 and it appears that this behavior was fixed by #3296, the fix just hasn't made it's way into the wild yet. Unless you disagree, I think this issue can be closed.

**Comment by blueyed** [comment] 2021-05-03 14:18
I can confirm that https://github.com/python-poetry/poetry/pull/3296 fixes this, but has not been released yet.

**Comment by blueyed** [comment] 2021-05-03 14:22
Backported for 1.1 already in https://github.com/python-poetry/poetry/commit/7a0fdf9964a95b0812c01811c1a974dafab218e1 (will be in 1.1.7 then likely).

**Closed** 2021-05-08 16:41 UTC
Labels: Bug, Triage
