### ISSUE TITLE
Installing poetry succeeds but gives a ...

### ISSUE THREAD

**Issue by ghost** [python-poetry/poetry#1130] opened 2019-05-28 02:41 UTC
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
-[x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: <!-Ubuntu 18.10 -->
- **Poetry version**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 
 
---------------------------------------------------------------------------

## Issue

Both https://poetry.eustace.io/docs/#installation & https://github.com/sdispater/poetry#installation
contain -
```
curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
```

**Comment by snow8gaia** [comment] 2019-05-28 03:02
<details>

<summary> 
1
  </summary>

<p>

```bash
poetry version -vvv

[ImportError]     
No module named pkg_resources  
                                 
Exception trace:
 /home/qren/.poetry/lib/poetry/_vendor/py2.7/cleo/application.py in run() at line 94
   status_code = self.do_run(input_, output_)
 /home/qren/.poetry/lib/poetry/console/application.py in do_run() at line 88
   return super(Application, self).do_run(i, o)
 /home/qren/.poetry/lib/poetry/_vendor/py2.7/cleo/application.py in do_run() at line 197
   status_code = command.run(input_, output_)
 /home/qren/.poetry/lib/poetry/console/commands/command.py in run() at line 77
   return super(BaseCommand, self).run(i, o)
 /home/qren/.poetry/lib/poetry/_vendor/py2.7/cleo/commands/base_command.py in run() at line 146
   status_code = self.execute(input_, output_)
 /home/qren/.poetry/lib/poetry/_vendor/py2.7/cleo/commands/command.py in execute() at line 107
   return self.handle()
 /home/qren/.poetry/lib/poetry/console/commands/version.py in handle() at line 35
   version = self.increment_version(self.poetry.package.pretty_version, version)
 /home/qren/.poetry/lib/poetry/console/commands/command.py in poetry() at line 62
   return self.get_application().poetry
 /home/qren/.poetry/lib/poetry/console/application.py in poetry() at line 55
   from poetry.poetry import Poetry
 /home/qren/.poetry/lib/poetry/poetry.py in <module>() at line 11
   from .json import validate_object
 /home/qren/.poetry/lib/poetry/json/__init__.py in <module>() at line 4
   import jsonschema
 /home/qren/.poetry/lib/poetry/_vendor/py2.7/jsonschema/__init__.py in <module>() at line 32
   from pkg_resources import get_distribution

version [<version>]


```
</p>
</details>


<details>

<summary> 2</summary>

<p>

```bash
poetry update -vvv

[ImportError]     
No module named pkg_resources  
                                 
Exception trace:
 /home/qren/.poetry/lib/poetry/_vendor/py2.7/cleo/application.py in run() at line 94
   status_code = self.do_run(input_, output_)
 /home/qren/.poetry/lib/poetry/console/application.py in do_run() at line 88
   return super(Application, self).do_run(i, o)
 /home/qren/.poetry/lib/poetry/_vendor/py2.7/cleo/application.py in do_run() at line 197
   status_code = command.run(input_, output_)
 /home/qren/.poetry/lib/poetry/console/commands/command.py in run() at line 77
   return super(BaseCommand, self).run(i, o)
 /home/qren/.poetry/lib/poetry/_vendor/py2.7/cleo/commands/base_command.py in run() at line 136
   self.initialize(input_, output_)
 /home/qren/.poetry/lib/poetry/console/commands/env_command.py in initialize() at line 18
   current_env = Env.get(self.poetry.file.parent)
 /home/qren/.poetry/lib/poetry/console/commands/command.py in poetry() at line 62
   return self.get_application().poetry
 /home/qren/.poetry/lib/poetry/console/application.py in poetry() at line 55
   from poetry.poetry import Poetry
 /home/qren/.poetry/lib/poetry/poetry.py in <module>() at line 11
   from .json import validate_object
 /home/qren/.poetry/lib/poetry/json/__init__.py in <module>() at line 4
   import jsonschema
 /home/qren/.poetry/lib/poetry/_vendor/py2.7/jsonschema/__init__.py in <module>() at line 32
   from pkg_resources import get_distribution

update [--no-dev] [--dry-run] [--lock] [--] [<packages>]...
```
</p>
</details>


<details>

<summary>3</summary>

<p>

```bash
poetry update werzkeug -vvv 
                                 
[ImportError]     
No module named pkg_resources  
                                 
Exception trace:
 /home/qren/.poetry/lib/poetry/_vendor/py2.7/cleo/application.py in run() at line 94
   status_code = self.do_run(input_, output_)
 /home/qren/.poetry/lib/poetry/console/application.py in do_run() at line 88
   return super(Application, self).do_run(i, o)
 /home/qren/.poetry/lib/poetry/_vendor/py2.7/cleo/application.py in do_run() at line 197
   status_code = command.run(input_, output_)
 /home/qren/.poetry/lib/poetry/console/commands/command.py in run() at line 77
   return super(BaseCommand, self).run(i, o)
 /home/qren/.poetry/lib/poetry/_vendor/py2.7/cleo/commands/base_command.py in run() at line 136
   self.initialize(input_, output_)
 /home/qren/.poetry/lib/poetry/console/commands/env_command.py in initialize() at line 18
   current_env = Env.get(self.poetry.file.parent)
 /home/qren/.poetry/lib/poetry/console/commands/command.py in poetry() at line 62
   return self.get_application().poetry
 /home/qren/.poetry/lib/poetry/console/application.py in poetry() at line 55
   from poetry.poetry import Poetry
 /home/qren/.poetry/lib/poetry/poetry.py in <module>() at line 11
   from .json import validate_object
 /home/qren/.poetry/lib/poetry/json/__init__.py in <module>() at line 4
   import jsonschema
 /home/qren/.poetry/lib/poetry/_vendor/py2.7/jsonschema/__init__.py in <module>() at line 32
   from pkg_resources import get_distribution

update [--no-dev] [--dry-run] [--lock] [--] [<packages>]...

```
</p>
</details>

**Comment by snow8gaia** [comment] 2019-05-28 04:00
work->- 

- `$ poetry search requests` 
- `$ poetry init`

more info-
```
$ python -m pkg_resources
/usr/bin/python: No module named pkg_resources
```
----------
https://poetry.eustace.io/docs/#system-requirements are fulfilled. accounting for 1-5 & general chaos, this need to be updated->
[REadme.md file](https://github.com/sdispater/poetry/blob/master/README.md) & https://poetry.eustace.io/docs/#installation

missing link for `get-poetry.py`. no tab completion for bash & [powershell core](https://github.com/PowerShell/PowerShell/releases) by default.

----------
too much trouble for something that's for **helping newcomers**, reminds me of https://en.wikipedia.org/wiki/Propaganda#Advertising. postpone fixing https://github.com/sdispater/poetry/issues/991

**Comment by a-recknagel** [comment] 2019-06-03 14:15
I can reproduce the error in a container with the following commands:

```
~$ docker run -it ubuntu  # starts an Ubuntu 18.04.2 LTS image
/# apt update
/# apt install curl python
/# curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
/# source $HOME/.poetry/env
/# poetry debug:info -vvv
                                 
[ImportError]     
No module named pkg_resources  
                                 
Exception trace:
 /root/.poetry/lib/poetry/_vendor/py2.7/cleo/application.py in run() at line 94
   status_code = self.do_run(input_, output_)
 /root/.poetry/lib/poetry/console/application.py in do_run() at line 88
   return super(Application, self).do_run(i, o)
 /root/.poetry/lib/poetry/_vendor/py2.7/cleo/application.py in do_run() at line 197
   status_code = command.run(input_, output_)
 /root/.poetry/lib/poetry/console/commands/command.py in run() at line 77
   return super(BaseCommand, self).run(i, o)
 /root/.poetry/lib/poetry/_vendor/py2.7/cleo/commands/base_command.py in run() at line 146
   status_code = self.execute(input_, output_)
 /root/.poetry/lib/poetry/_vendor/py2.7/cleo/commands/command.py in execute() at line 107
   return self.handle()
 /root/.poetry/lib/poetry/console/commands/debug/info.py in handle() at line 17
   poetry = self.poetry
 /root/.poetry/lib/poetry/console/commands/command.py in poetry() at line 62
   return self.get_application().poetry
 /root/.poetry/lib/poetry/console/application.py in poetry() at line 55
   from poetry.poetry import Poetry
 /root/.poetry/lib/poetry/poetry.py in <module>() at line 11
   from .json import validate_object
 /root/.poetry/lib/poetry/json/__init__.py in <module>() at line 4
   import jsonschema
 /root/.poetry/lib/poetry/_vendor/py2.7/jsonschema/__init__.py in <module>() at line 32
   from pkg_resources import get_distribution

debug:info
```
Current workaround is to install it globally with pip instead.

**Comment by snow8gaia** [comment] 2019-06-12 15:20
in https://github.com/sdispater/poetry/blob/master/README.md#installation

solution
-----

This is the recommended way of installing poetry. 
```
pip install --user poetry
```

**Comment by snow8gaia** [comment] 2019-06-12 15:34
while using `poetry init` to reproduce https://github.com/sdispater/poetry/issues/991
```bash
Enter the version constraint to require (or leave blank to use the latest version): git = "https://github.com/pallets/werkzeug.git"

Search for a package: 

                                          
[ValueError]               
too many values to unpack (expected 2)  

```

**Comment by paranoidi** [comment] 2019-06-18 12:55
Installed poetry per up to date instructions with recommended method. Created a project and tried to build it. But looks like my poetry installation is broken:

```
[ImportError]     
No module named pkg_resources  
```

As installation is "isolated" by some non-standard magic, I can not even install setup tools to some virtualenv to address this issue. 

@snow8gaia how is that a solution? It's NOT recommended way per documentation!

**Comment by snow8gaia** [comment] 2019-06-19 17:05
## to @paranoidi 

<details>

<summary>click to expand </summary>

<p>

>But looks like my poetry installation is broken:

don't worry, it is the same on every fresh Ubuntu install. 

Linux distributions cut up software to annoy users (and package developers?). 
Maybe its their outlet for anger or frustration or sadistic tendencies ; a kind of entertainment ; or they want to promote Windows 10 for free.

-----

>how is that a solution? It's NOT recommended way per documentation!

I don't use `pip install --user`, never will. But for some reason, its on the README.md, so I thought rather than make a PR just ask and commented it.

read https://docs.pipenv.org/en/latest/install/#pragmatic-installation-of-pipenv , https://github.com/sdispater/poetry#installation, 
the above comments.

and by 
[issue/1130#issuecomment-501322508](https://github.com/sdispater/poetry/issues/1130#issuecomment-501322508)
I mean the change that needs to be made, not necessarily the best way to install poetry.

is this the documentation page you mention? just looked for it and saw it- https://github.com/sdispater/poetry/blob/master/docs/docs/index.md#alternative-installation-methods-not-recommended

----
>I can not even install setup tools to some virtualenv to address this issue.

what python program created the virtualenv? eg:-  virtualenv or venv

-------------
</p>
</details>



## to a-recknagel 

>Current workaround is to install it globally with pip instead.

so, `pip install poetry`?

**Comment by a-recknagel** [comment] 2019-06-19 17:47
@snow8gaia jep, it solves the problem in my setup ¯\\_(ツ)_/¯

**Comment by paranoidi** [comment] 2019-06-20 12:02
@snow8gaia I followed https://poetry.eustace.io/docs/#installation

This produces very confusingly broken installation on fresh installation due missing pip / setuptools (depending on distro). It's going to cause issues for many new users if handled as it currently is. There needs to be better error message than import error failure on "poetry build".

**Comment by finswimmer** [comment] 2020-05-03 18:05
Because there were no more comments to this issue for a very long time, I assume it is solved. So I will close it.

Feel free to leave a comment if someone disagree.

fin swimmer

**Closed by finswimmer** 2020-05-03 18:05 UTC
