### ISSUE TITLE
Every poetry command throws InvalidNumberError

### ISSUE THREAD

**Issue by cristianoperez** [python-poetry/poetry#2875] opened 2020-09-01 20:53 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: 10.15.6 (19G73) MacOS Catalina
- **Poetry version**: 1.1.0b2 but happens with any previous version

## Issue
Every time a try to execute any poetry command like `install` `build` `env info` `env list` poetry throws the following exception, already tried with python 3.7 and 3.8 

```
InvalidNumberError

  The invalid number at line 8 col 13

  at ~/.poetry/lib/poetry/_vendor/py3.8/tomlkit/parser.py:600 in _parse_value
       596│             item = self._parse_number(raw, trivia)
       597│             if item is not None:
       598│                 return item
       599│
    →  600│             raise self.parse_error(InvalidNumberError)
       601│         else:
       602│             raise self.parse_error(UnexpectedCharError, c)
       603│
       604│     def _parse_true(self):
```

**Comment by cristianoperez** [comment] 2020-09-01 21:39
After a few hours of investigation and debugging, I deleted `~/Library/Caches/pypoetry/virtualenvs` and everything starts to work again

**Comment by abn** [comment] 2020-09-02 00:15
This i beleive is a duplicate of #2849. Caused due to a corrupt `envs.toml` file in `~/.cache/pypoetry/virtualenvs`. In this case in `~/Library/Caches/pypoetry/virtualenvs`.

**Closed** 2020-09-02 00:17 UTC
Labels: Bug
