### ISSUE TITLE
SSLCertVereficationError when trying to install poetry using private repository

### ISSUE THREAD

**Issue by eresque** [python-poetry/poetry#6065] opened 2022-07-25 12:27 UTC
I know this there were a couple of issues on this problem but I can't see it being solved since in this issues there is no appropriate guide on how to fix it. So if you could help me with my issue I'll really appreciate that.
I use private repositiry:
`[[tool.poetry.source]]
name = "preprocess"
url = "https://.../pypi/python-remote/simple"
default = true`
And then using Docker to create a container I use this command:
`RUN source ./venv/bin/activate && poetry install --no-dev --no-root
`
But the ssl error pops out and I do not understand how to deal with it.

**Comment by dimbleby** [comment] 2022-07-25 14:20
duplicate #6052, #4016 (so far as anyone can tell)

I understand that those issues don't have answers in them; but I don't think that forking the conversation into multiple streams helps that.

**Comment by neersighted** [comment] 2022-07-25 14:22
Agreed, closing as dupe. This sounds like it might be more of a workflow/setup issue and not a bug, necessarily (though you have not included enough detail for me to be able to tell) -- please feel free to join Discord or start a Discussion to take advantage of some high signal to noise debugging help if you're not 100% sure this falls under an existing issue.

**Closed by neersighted** 2022-07-25 14:22 UTC
Labels: Bug, Triage
