### ISSUE TITLE
required extras cause dependency not to be installed

### ISSUE THREAD

**Issue by wakemaster39** [python-poetry/poetry#4721] opened 2021-11-08 19:52 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**:  macOS 11
- **Poetry version**:  1.2.0a2

## Issue

If all instances of a dependency requires extras, then the dependency is not being installed.

https://github.com/python-poetry/poetry/blob/5dcf24da04275425631c817419ad5cb17cbd0177/poetry/puzzle/solver.py#L156-L179

The continue on line 173 guarantees that this package never hits the add lines and won't be added.

**Comment by neersighted** [comment] 2021-11-11 14:52
Hi @wakemaster39! Thanks for opening an issue! It's pretty unclear what the expected behavior and the actual behavior is -- can you please clearly describe them both, as well as provide a `pyproject.toml` that reproduces the issue in a Gist?

**Comment by zdog234** [comment] 2021-11-14 12:54
I just ran into the same behavior.

It's showing up [with python3.10](https://gist.github.com/zdog234/7abfd318a762ab3a2dfeeb103fc55e6a) but isn't showing up [with python3.9](https://gist.github.com/zdog234/38255034458f18a569605352ebdb244f).

The expected behavior is that, when I run `poetry run pytest`, I should get an output saying "collected 0 items" and "no tests ran...". Instead, i get a `ModuleNotFoundError`:

```
...
File "/Users/zdufour/Github/poetry-issue/.venv/lib/python3.10/site-packages/pytest_cov/plugin.py", line 6, in <module>
    import coverage
ModuleNotFoundError: No module named 'coverage'
```

**Comment by k-sriram** [comment] 2021-11-28 00:39
I have had the same problem. It can even be recreated in a blank poetry project.

I am using `python 3.10` and `poetry 1.2.0a2`, on ubuntu-20.04 on WSL2

To recreate:

```sh
$ python -m venv deptest-venv
$ source deptest-venv/bin/activate
$ poetry new deptest
Created package deptest in deptest
$ cd deptest
$ poetry add "coverage[toml]"
Using version ^6.2 for coverage

Updating dependencies
Resolving dependencies... (0.8s)

Writing lock file

Package operations: 1 install, 0 updates, 0 removals

  • Installing tomli (1.2.2)
$ pip freeze
tomli==1.2.2
```
The expected behaviour here should be for poetry to install both `coverage` and `tomli`. As we can see `coverage` didn't get installed. It also gets added to  `pyproject.toml`/`poetry.lock` in such a manner that any subsequent invocation of `poetry add coverage` will also refuse to install `coverage` stating that it already exists. `poetry install` will also not install it in a fresh virtual environment. However `coverage` does get installed if it one doesn't provide the extras `toml` initially.

```sh
$ python -m venv deptest-venv
$ source deptest-venv/bin/activate
$ poetry new deptest
Created package deptest in deptest
$ cd deptest
$ poetry add coverage
Using version ^6.2 for coverage

Updating dependencies
Resolving dependencies... (0.1s)

Writing lock file

Package operations: 1 install, 0 updates, 0 removals

  • Installing coverage (6.2)
$ pip freeze
coverage==6.2
```

It might also be a specific case, since @wakemaster39 and me ran into this issue with the same repository. Coincidence? or is it because `pytest-cov` lists `coverage[toml]` in its `install-requires`.

For now I am using a workaround in which I explicitly state `coverage` (even though my project doesn't directly use it) as a dependency before `pytest-cov` in my `pyproject.toml`, and everything is working.

**Comment by finswimmer** [comment] 2022-04-29 20:49
Hello,

I'm not able reproduce this with Poetry 1.1.13 or 1.2.0b1. So I guess this is resolved in the meantime.

Feel free to leave a comment if you disagree.

fin swimmer

**Closed by finswimmer** 2022-04-29 20:49 UTC
Labels: Awaiting Reponse
