### ISSUE TITLE
Relative `cache-dir` breaks the new installer

### ISSUE THREAD

**Issue by matejcik** [python-poetry/poetry#3049] opened 2020-10-02 11:07 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Linux Mint 20, Python 3.8.2
- **Poetry version**: 1.1.0, master
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/matejcik/f7b0d6ca9bea9e6613f7a99433d7ad65

## Issue
When `cache-dir` is set to a relative path (in poetry.toml), bad things happen.

To reproduce:

1. place contents of above gist into a directory
2. `poetry install`
3. `rm -r .venv`
4. `poetry install` again

**Expected result:** this should work fine

**Actual result:** a spectacularly unhelpful stack trace with the following error: `ValueError: relative path can't be expressed as a file URI`

after modifying something or other, the actual stack trace shows up:
```
ValueError: relative path can't be expressed as a file URI
Traceback (most recent call last):
  File "/home/matejcik/.local/lib/python3.8/site-packages/poetry/installation/executor.py", line 180, in _execute_operation
    result = self._do_execute_operation(operation)
  File "/home/matejcik/.local/lib/python3.8/site-packages/poetry/installation/executor.py", line 255, in _do_execute_operation
    result = getattr(self, "_execute_{}".format(method))(operation)
  File "/home/matejcik/.local/lib/python3.8/site-packages/poetry/installation/executor.py", line 390, in _execute_install
    return self._install(operation)
  File "/home/matejcik/.local/lib/python3.8/site-packages/poetry/installation/executor.py", line 416, in _install
    archive = self._download(operation)
  File "/home/matejcik/.local/lib/python3.8/site-packages/poetry/installation/executor.py", line 559, in _download
    return self._download_link(operation, link)
  File "/home/matejcik/.local/lib/python3.8/site-packages/poetry/installation/executor.py", line 564, in _download_link
    archive = self._chef.get_cached_archive_for_link(link)
  File "/home/matejcik/.local/lib/python3.8/site-packages/poetry/installation/chef.py", line 49, in get_cached_archive_for_link
    archives = self.get_cached_archives_for_link(link)
  File "/home/matejcik/.local/lib/python3.8/site-packages/poetry/installation/chef.py", line 84, in get_cached_archives_for_link
    links.append(Link(archive.as_uri()))
```

Far as I could tell, `archive` above is a relative path starting with `.cache`, which can't be converted to an URI.

After changing the line in `chef.py` to:
```
links.append(Link(archive.resolve().as_uri())
```
the issue goes away. I'm not sure if that is even the right place to fix it, but if yes, I'll send a PR.

**Comment by abn** [comment] 2020-10-02 16:41
That should fix the specific issue. 

An additional fix may be to resolve the cache-dir value when it is loaded in. However, not sure if there would be any unintentional side-effects in doing so.

**Comment by ericriff** [comment] 2020-10-08 18:41
Just came across this myself, on poetry version `1.1.2`, but only if I'm using `python 3.7`. With `3.6` and `3.5` it works as expected.

**Comment by ericriff** [comment] 2020-10-09 14:51
Are you guys going to open a PR for this?
I don't know how the internals of Poetry work, but if it is just that line I don't mind changing it. 
I would hate to steal the credit, but it blocking some of my work since I can't move past python 3.6 if I'm using relative paths on the cache.

By the way, I'm using the relative paths as a workaround to `in-project` only allowing you to have ONE environment per project. I just moved the whole cache inside my project  (since we need it to be self contained) and now I can have all the environments I want (I only care about different python versions) inside my project folder. 
I'm not sure if there is a better way to do this.

**Comment by rvorias** [comment] 2021-01-12 13:00
I accidentally removed the `_build/` contents. After restoring them, poetry couldn't be installed due to this error.

Solved it by removing `_build/` and `.venv/` and ran `poetry install` which uses the `.lock`. Seems to be fixed now.

**Comment by prusnak** [comment] 2021-01-14 16:57
I was just with the same issue today

**Comment by pawamoy** [comment] 2021-03-12 21:39
Same thing in CI when setting cache directory with a relative path: https://github.com/pawamoy/duty/runs/2098788727?check_suite_focus=true

**Comment by ericriff** [comment] 2021-03-12 21:41
I would love to have a way to make it relative to `pyproject.yoml`.

**Comment by pawamoy** [comment] 2021-03-12 21:43
Here's how I worked around this in CI:

```yaml
env:
  # To fix an error running Poetry on Windows
  # (https://github.com/python-poetry/poetry/issues/2629),
  # we set Poetry's cache directory to .poetry_cache in the current directory.
  # It makes it easier to later remove the virtualenv when it's broken.
  # Absolute path is necessary to avoid this issue:
  # https://github.com/python-poetry/poetry/issues/3049
  POETRY_CACHE_DIR: ${{ github.workspace }}/.poetry_cache
```

**Comment by finswimmer** [comment] 2023-04-29 15:03
Closing this, because I cannot reproduce this anymore.

Feel free to leave a comment if you disagree.

**Closed by finswimmer** 2023-04-29 15:03 UTC
Labels: kind/bug, status/triage
