### ISSUE TITLE
Installing local file dependencies fail in spite of file existing

### ISSUE THREAD

**Issue by navyamehta** [python-poetry/poetry#3625] opened 2021-01-31 16:35 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 18.04.5 LTS
- **Poetry version**: 1.1.4
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/navyamehta/228b80fa5f11000b5616dd522c73a74b.js"

## Issue

I download the TensorRT-7.2.2.3.Ubuntu-18.04.x86_64-gnu.cuda-11.1.cudnn8.0.tar.gz file from NVIDIA and put it in the same folder as pyproject.toml. My virtualenv is 20.4.1 and install-metadata is 3.4.0. However, I get the following error on poetry install --no-dev
`
TypeError

  expected string or bytes-like object

  at /opt/conda/lib/python3.8/site-packages/poetry/core/utils/helpers.py:24 in canonicalize_name
       20│ _canonicalize_regex = re.compile("[-_]+")
       21│ 
       22│ 
       23│ def canonicalize_name(name):  # type: (str) -> str
    →  24│     return _canonicalize_regex.sub("-", name).lower()
       25│ 
       26│ 
       27│ def module_name(name):  # type: (str) -> str
       28│     return canonicalize_name(name).replace(".", "_").replace("-", "_")
`
Any help would be appreciated!

**Comment by mxab** [comment] 2021-02-02 17:51
We're also facing this issue on some machines
pyhton 3.8.6 (pyenv) / wsl1 / ubuntu / poetry 1.1.3 (as 1.1.4 has an issue when resolving with private repos)

**Comment by sinoroc** [comment] 2021-02-02 21:44
There was a case with similar symptoms here: https://github.com/python-poetry/poetry/issues/3628
Maybe the root cause is also similar in your case... might also be a false lead.

**Comment by abn** [comment] 2022-05-19 11:43
Closing as a duplicate of #3628 as it has more information.

**Closed by abn** 2022-05-19 11:43 UTC
Labels: Bug, Triage
