### ISSUE TITLE
Why can I not execute migrations with Django in poetry venv?

### ISSUE THREAD

**Issue by fkromer** [python-poetry/poetry#3788] opened 2021-03-16 09:33 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10 Pro + WSL2 + Ubuntu 20.04
- **Poetry version**: 1.1.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue

I've setup a `virtualenv` using `poerty==1.1.5` for a Django project in WSL2-Ubuntu. When I try to execute a database migration with `Django=3.0.4` I get the following error:

```
(.venv) florian@DESKTOP-G3G6E71-wsl:~/gitlab/mvp-edge-backend/backend$ python manage.py makemigrations
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/florian/gitlab/mvp-edge-backend/backend/.venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/florian/gitlab/mvp-edge-backend/backend/.venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/florian/gitlab/mvp-edge-backend/backend/.venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 244, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/home/florian/gitlab/mvp-edge-backend/backend/.venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 37, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/florian/gitlab/mvp-edge-backend/backend/.venv/lib/python3.8/site-packages/django/core/management/commands/makemigrations.py", line 11, in <module>
    from django.db.migrations import Migration
  File "/home/florian/gitlab/mvp-edge-backend/backend/.venv/lib/python3.8/site-packages/django/db/migrations/__init__.py", line 1, in <module>
    from .migration import Migration, swappable_dependency  # NOQA
ModuleNotFoundError: No module named 'django.db.migrations.migration'
```

I've recreated the `venv` several times like suggested in other related questions. However I get always this same error. The package seems to be installed in the `venv` properly:

```
(.venv) florian@DESKTOP-G3G6E71-wsl:~/gitlab/mvp-edge-backend/backend$ python manage.py --version
3.0.4
(.venv) florian@DESKTOP-G3G6E71-wsl:~/gitlab/mvp-edge-backend/backend$ pip freeze | grep Django
Django @ file:///home/florian/.cache/pypoetry/artifacts/01/7f/3b/9b972acb56bdd4b4d20a000d9f9be5cf8daf08fcf50e75003371ff0cb7/Django-3.0.4-py3-none-any.whl
(.venv) florian@DESKTOP-G3G6E71-wsl:~/gitlab/mvp-edge-backend/backend$ poetry show django
name         : django
version      : 3.0.4
description  : A high-level Python Web framework that encourages rapid development and clean, pragmatic design.

dependencies
 - asgiref >=3.2,<4.0
 - pytz *
 - sqlparse >=0.2.2
```

In the Python system installation there is no package installed which could potentially conflict with the `venv`:

    florian@DESKTOP-G3G6E71-wsl:~/gitlab/mvp-edge-backend/backend$ pip show django
    WARNING: Package(s) not found: django

Why is it not possible to execute a database migration with a `poetry` managed venv?

Sidenote: I recreated the `venv` with plain [stdlib `venv`](https://docs.python.org/3/library/venv.html) and was able to run migrations without trouble.

**Comment by stephsamson** [comment] 2021-03-28 13:40
Can you dump the results of `poetry env info` here?

**Comment by mkniewallner** [comment] 2022-06-16 22:58
Since we didn't hear back from you and the issue is a bit old, I'm gonna close this, but if you still encounter the problem, feel free to reopen and share more details on your setup to help us reproduce.

**Closed by mkniewallner** 2022-06-16 22:58 UTC
Labels: Bug, Triage
