### ISSUE TITLE
Obsolete, "about to be removed" package path causes "does not exist" error

### ISSUE THREAD

**Issue by mitchhentges** [python-poetry/poetry#5541] opened 2022-05-04 17:55 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Fedora 35
- **Poetry version**: `poetry==1.2.0b1` or (`poetry==edabfce155c5c5445371115d5a83b792b0dc0de2` and `poetry-core==722d439e383d6691116bb2d99857a7e1f9b830f7`)
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: [https://gist.github.com/mitchhentges/910d013f8f261605f6dd4abd73983836](https://gist.github.com/mitchhentges/910d013f8f261605f6dd4abd73983836)

## Issue

1. Have a path-based dependency (e.g. `bonk = { path = "../python-setup.py/", develop = true }`
2. `poetry lock --no-update`
3. Remove the path-based dependency from `pyproject.toml`, **remove the associated files (`python-setup.py/`) at the same time**
4. `poetry lock --no-update`

```
(env) ~/d/poetry-example % python -m poetry -vvv lock --no-update
Using virtualenv: /home/mitch/work/env
Resolving dependencies...

  Stack trace:

  13  ~/work/env/lib64/python3.10/site-packages/cleo/application.py:330 in run
       328│ 
       329│             try:
     → 330│                 exit_code = self._run(io)
       331│             except Exception as e:
       332│                 if not self._catch_exceptions:

  12  ~/dev/poetry/src/poetry/console/application.py:174 in _run
       172│         self._load_plugins(io)
       173│ 
     → 174│         return super()._run(io)
       175│ 
       176│     def _configure_io(self, io: IO) -> None:

  11  ~/work/env/lib64/python3.10/site-packages/cleo/application.py:425 in _run
       423│                 io.set_input(ArgvInput(argv))
       424│ 
     → 425│         exit_code = self._run_command(command, io)
       426│         self._running_command = None
       427│ 

  10  ~/work/env/lib64/python3.10/site-packages/cleo/application.py:467 in _run_command
       465│ 
       466│         if error is not None:
     → 467│             raise error
       468│ 
       469│         return event.exit_code

   9  ~/work/env/lib64/python3.10/site-packages/cleo/application.py:451 in _run_command
       449│ 
       450│             if event.command_should_run():
     → 451│                 exit_code = command.run(io)
       452│             else:
       453│                 exit_code = ConsoleCommandEvent.RETURN_CODE_DISABLED

   8  ~/work/env/lib64/python3.10/site-packages/cleo/commands/base_command.py:118 in run
       116│         io.input.validate()
       117│ 
     → 118│         status_code = self.execute(io)
       119│ 
       120│         if status_code is None:

   7  ~/work/env/lib64/python3.10/site-packages/cleo/commands/command.py:85 in execute
        83│ 
        84│         try:
     →  85│             return self.handle()
        86│         except KeyboardInterrupt:
        87│             return 1

   6  ~/dev/poetry/src/poetry/console/commands/lock.py:55 in handle
        53│         self._installer.lock(update=not self.option("no-update"))
        54│ 
     →  55│         return self._installer.run()
        56│ 

   5  ~/dev/poetry/src/poetry/installation/installer.py:98 in run
        96│         # Check if refresh
        97│         if not self._update and self._lock and self._locker.is_locked():
     →  98│             return self._do_refresh()
        99│ 
       100│         # Force update if there is no lock file present

   4  ~/dev/poetry/src/poetry/installation/installer.py:204 in _do_refresh
       202│             source_root=self._env.path.joinpath("src")
       203│         ):
     → 204│             ops = solver.solve(use_latest=[]).calculate_operations()
       205│ 
       206│         local_repo = Repository()

   3  ~/dev/poetry/src/poetry/puzzle/solver.py:79 in solve
        77│         with self._provider.progress():
        78│             start = time.time()
     →  79│             packages, depths = self._solve(use_latest=use_latest)
        80│             end = time.time()
        81│ 

   2  ~/dev/poetry/src/poetry/puzzle/solver.py:139 in _solve
       137│         for package in self._locked.packages:
       138│             locked[package.name].append(
     → 139│                 DependencyPackage(package.to_dependency(), package)
       140│             )
       141│         for dependency_packages in locked.values():

   1  ~/dev/poetry-core/src/poetry/core/packages/package.py:462 in to_dependency
       460│ 
       461│         if self.source_type == "directory":
     → 462│             dep = DirectoryDependency(
       463│                 self._name,
       464│                 Path(self._source_url),

  ValueError

  Directory /home/mitch/dev/python-setup.py does not exist

  at ~/dev/poetry-core/src/poetry/core/packages/directory_dependency.py:42 in __init__
       38│         self._develop = develop
       39│         self._supports_poetry = False
       40│ 
       41│         if not self._full_path.exists():
    →  42│             raise ValueError(f"Directory {self._path} does not exist")
       43│ 
       44│         if self._full_path.is_file():
       45│             raise ValueError(f"{self._path} is a file, expected a directory")
       46│ 
```

**Comment by finswimmer** [comment] 2024-10-29 07:57
Duplicate of #9054

**Closed by finswimmer** 2024-10-29 07:57 UTC
Labels: kind/bug, status/triage
