### ISSUE TITLE
'poetry add wasmer' and 'show --outdated' hang forever on macOS

### ISSUE THREAD

**Issue by intgr** [python-poetry/poetry#3370] opened 2020-11-17 08:43 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

- **OS version and name**: macOS 10.15.7
- **Poetry version**: Poetry 1.1.4
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/intgr/767f32b18bd00164cceae9d02621af49
- Python 3.9.0

## Issue
On macOS this is how I could reproduce the hang:
* `poetry init -n`
* `poetry add wasmer`

Also, if I already have `wasmer` in my project dependencies, then `poetry show --outdated` hangs forever.

However, on Linux I could not reproduce the issue, so there seems to be something macOS specific.

This is different from the other hang I reported in #3200. In the case of #3200, the bug cannot be triggered via Poetry CLI and there's a simple workaround. In this case I'm using Poetry CLI as designed and I have not found any workarounds.

```
% poetry init -n
[...]
% time poetry add -vvv wasmer
Creating virtualenv test-y5X0okRo-py3.9 in /Users/marti.raudsepp/Library/Caches/pypoetry/virtualenvs
Using virtualenv: /Users/marti.raudsepp/Library/Caches/pypoetry/virtualenvs/test-y5X0okRo-py3.9
^Cpoetry add -vvv wasmer  0.92s user 3.63s system 0% cpu 12:56.92 total
```

**Comment by sinoroc** [comment] 2020-11-17 10:48
As a point of comparison, have you already tried with _pip_? If not, can you try? How does it behave?

**Comment by intgr** [comment] 2020-11-17 10:57
pip has no issue with it
```
% pip install wasmer
Collecting wasmer
  Downloading wasmer-0.4.1-py3-none-any.whl (1.3 kB)
Installing collected packages: wasmer
Successfully installed wasmer-0.4.1
```

**Comment by sinoroc** [comment] 2020-11-17 11:04
And this happens only with `poetry add wasmer`? If you add `wasmer` by hand to `pyproject.toml` then run `poetry update` or `poetry install`, are there issues as well?

**Comment by intgr** [comment] 2020-11-18 10:02
If I add it to `pyproject.toml` manually then poetry update/lock/install commands keep spinning at `Resolving dependencies... (56.1s)`. I tried specifying with version `"*"` as well as a few concrete version numbers.

**Comment by sinoroc** [comment] 2020-11-18 10:13
> If I add it to `pyproject.toml` manually then poetry update/lock/install commands keep spinning at `Resolving dependencies... (56.1s)`

Do you have the _verbose_ output (`-vvv`) of this? In case it might be helpful for the maintainers to try and debug this later.

**Comment by intgr** [comment] 2020-11-18 10:55
Ah indeed, `poetry add -vvv` did not give print extra information, but `poetry lock -vvv` outputs this:

```
[marti.raudsepp@Playtech-L2832]% poetry lock -vvv
Using virtualenv: /Users/marti.raudsepp/Library/Caches/pypoetry/virtualenvs/app-y5X0okRo-py3.9
Updating dependencies
Resolving dependencies...
   1: fact: app is 1.0.0
   1: derived: app
   1: fact: app depends on wasmer (*)
   1: selecting app (1.0.0)
   1: derived: wasmer (*)
^C   1: Version solving took 55.898 seconds.
   1: Tried 1 solutions.
```

**Comment by sinoroc** [comment] 2020-11-18 11:08
I do not know where to go from there. Some things to try:

* without the new installer: `poetry config experimental.new-installer false`
* with older _poetry_ (`1.0.*`)

**Comment by finswimmer** [comment] 2020-11-18 20:15
Hm, no problem here. `wasmer` gets installed immediately. :thinking:

**Comment by intgr** [comment] 2020-11-19 10:11
@finswimmer Did you test on macOS as well?

At one point resolving wasmer must have worked on my machine since I have a project using it. But I have no idea what changed since then.

I tried disabling new-installer and downgrading Poetry as suggested by @sinoroc.

I also tried downgrading to Python 3.8, that also did not fix the issue.

**Comment by sinoroc** [comment] 2020-11-19 11:17
Some other ideas to look into:

* Inspect the content of the `site-packages` directory for the current environment, in particular look for things like in this [comment in another ticket](https://github.com/python-poetry/poetry/issues/3378#issuecomment-729693838) and the `~asm` or `-asm` files or directories.
* Recreate the environment from scratch.
* Try different installation methods for _poetry_ itself. Which method have you used so far by the way, `get-poetry.py`, `pipx`, something else?

_[I hope I do not ask the same questions twice, questions whose answers you already gave, or questions whose answers are obvious, and so on.]_

**Comment by m0xb** [comment] 2021-11-06 19:46
This is an issue for me as well. I'm a new user, looking at switching from Pipenv to Poetry. I'm using Poetry 1.1.11 on macOS Big Sur (M1) and Python 3.9. Installed today with `curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -`

I've setup the demo with `poetry new poetry-demo`. Then, running `poetry add -vvv requests` hangs:
```
$ poetry add -vvv requests
Using virtualenv: /Users/immelol/Library/Caches/pypoetry/virtualenvs/poetry-demo-6vpDfws1-py3.9
^C
$
```

Similar to the above, `poetry remove -vvv sh` gives me more clues. "Resolving dependencies" is *extremely* slow. It's been running for 50+ minutes now and it looks like it's still running. From the verbose logs, looks like it's pulling information from PyPI, e.g. the last one is "PyPI: Getting info for pyparsing (2.4.7) from PyPI".

Installing with `pip` is no problem. So far, I've run into this with every package I've tried: `pex`, `requests`, and `sh`.

**Comment by bambu** [comment] 2021-12-10 23:26
I have this same problem. In my case `wasmer` works. However `capstone` does not. I was able to track the issue down to the creation of the session in `pypi_repository.py`.

Replacing:
```python
def session(self):
          return CacheControl(requests.session(), cache=self._cache_control_cache)
```

with

```python
def session(self):
          return requests.Session()
```
resolves the issue. 

No experience with what the `CacheControl` adapter may be doing to make the session fail intermittently.

**Comment by dimbleby** [comment] 2022-09-02 21:42
probably duplicate #6030 in which we learned that cachecontrol uses lockfiles and, presumably, if you hit Ctrl-C or similar at an unfortunate moment then that lockfile gets left lying around - at which point you are stuck until you remove it.

**Comment by neersighted** [comment] 2022-09-07 15:26
Closing as a duplicate for now as this is stale and there's no consistent reproduction.

**Closed by neersighted** 2022-09-07 15:26 UTC
Labels: kind/bug, status/triage
