### ISSUE TITLE
Be explicit about pyproject location

### ISSUE THREAD

**Issue by ericriff** [python-poetry/poetry#3123] opened 2020-10-07 15:25 UTC
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request
It would be very useful to be able to be explicit about the location of the `pyptoject` file when you invoke `poetry`. This allows you, for example, to invoke poetry from an arbitrary location. Or have multiple `pyproject`s for a given project, if that is what you need.
One of the main benefits would be to invoke poetry from **outside** the project folder. 

`pipenv` does something similar to this through the env variable `PIPENV_PIPFILE`.

Thanks,

Eric.

**Comment by ericriff** [comment] 2020-10-07 17:02
This will also allow us to create a `poetry-shebang` just like the one for `pipenv`, which makes the life of a dev using virtual environments 10 times easier.

https://github.com/laktak/pipenv-shebang/blob/master/bash/pipenv-shebang

**Comment by finswimmer** [comment] 2020-10-08 13:52
I guess this an accidentally made duplicate of #3122 :)

**Closed by finswimmer** 2020-10-08 13:52 UTC
Labels: Feature, Triage
