### ISSUE TITLE
Support constraining poetry version bounds in pyproject.toml

### ISSUE THREAD

**Issue by brandonchinn178** [python-poetry/poetry#6644] opened 2022-09-27 23:30 UTC
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request

It would be great to include the expected poetry version bounds in `pyproject.toml` like
```toml
[tool.poetry.meta]
requires_poetry = "^1.2"
```
Where running `poetry` in a project with an incompatible version of Poetry throws an error. We ran into issues where we upgraded our projects to Poetry 1.2, but a developer ran with Poetry 1.1 and had things silently fail.

**Comment by neersighted** [comment] 2022-09-27 23:46
This has been discussed multiple times, as a speculative `min_poetry_version` or similar, though a full constraint might be useful (but would be asymetric with how we put `python` in `dependencies` -- some bikeshedding is necessary here as design/ux will be important for this feature).

Without linking to a bunch of places, it's come up multiple time in Discussions, (private and public) Discord channels, and other issues; however, we have not had an issue to track it, so this might as well be the place.

It is worth noting that Poetry 1.1 does not fail silently; it fails loudly:

```
  RuntimeError

  The Poetry configuration is invalid:
    - Additional properties are not allowed ('group' was unexpected)
```

You could possible be referring to some other sort of incompatibility which is not graceful. We have taken steps to avoid those whenever we can (and have made changes to 1.2 to try and ease the transition), but by the nature of the long release cycle we are still discovering new sharp edges and trying to file them down. Feel free to start a discussion or similar if you are not sure what you are running into is a bug, docs issue, or just intended behavior.

**Comment by finswimmer** [comment] 2022-10-07 13:00
Duplicate of #3316

**Closed by finswimmer** 2022-10-07 13:00 UTC
Labels: kind/feature, area/pyproject
