### ISSUE TITLE
Poetry 1.2.0, dependencies with both version and path specifications

### ISSUE THREAD

**Issue by mindstorm38** [python-poetry/poetry#5546] opened 2022-05-05 16:02 UTC
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

I need some help with **Poetry 1.2.0b1**, not because it doesn't work, but because I don't understand why it works (compared to Poetry < 1.2).

I'm in a mono-repo architecture with one core module (portablemc v3.0.0) and many submodules, all depending on the core one. In each submodule, I used the following dependencies:
```toml
[tool.poetry.dependencies]
python = ">=3.6.2"
portablemc = "^3"
```

As expected, poetry fails to resolve portablemc version ^3 because it is not yet published, but this is the version I'm locally working on.

So I tried directory dependency:
```toml
[tool.poetry.dependencies]
python = ">=3.6.2"
portablemc = { path = "../core/", develop = false }
```

This worked! But not when building, the output version in METADATA file is a relative path, which is invalid when distributing the archive.

On my third attempt, I tried to mix this using dependency groups:
```toml
[tool.poetry.dependencies]
python = ">=3.6.2"
portablemc = "^3"

[tool.poetry.group.dev.dependencies]
portablemc = { path = "../core/", develop = false }
```

I initially planned to use `poetry install --with/--without dev` but to my surprise it worked without such arguments! By working, I mean METADATA has the correct requirement `>=3,<4` and the `poetry install` successfully add the .pth redirection to site packages.

**EDIT0**: *Note that even with `poetry install --without dev` it works, this is weird because Poetry should ignore the path dependency, and so should be forced to search for an PyPI-available package (which is not available as described for the first code block).*

I also found that in the lock file, the dependency has a custom "directory source"
```toml
[[package]]
name = "portablemc"
version = "3.0.0"
description = "[...]"
category = "main"
optional = false
python-versions = ">=3.6"
develop = false

[package.source]
type = "directory"
url = "../core"
```

So my question is simple: is it expected to work like this? If yes, the documentation must be improved to explain why (if you explain here, I can edit the documentation myself).

**Comment by abn** [comment] 2022-05-10 10:34
@mindstorm38 this is expected. Poetry creates a single dependency graph for your project when you add the same dependency in multiple groups (previously just in dev).

So when you perform `poetry lock` the lockfile is generated with the "globally" resolved dependency graph. This means poetry says Package A depends on Package B (^3) ad Package B (../core), and since `../core` is more constrained and assuming the path dependency's inspected version is within the range `^3`, poetry chooses the path dependency as the "locked" version.

The build step, ie. the step that creates your package artifacts, only assemble your files into a wheel and transpate the `main` group dependencys to PEP 508 representation for your MEATADATA file inside your wheel. Note that the lockfile is not used in this step nor is the "resolved" dependency graph. It is mearly a 1:1 translation of your `tool.poetry.dependency` section.

The install step, on the other hand, uses the lock fle. This means the path dependency is selected and installed.

Hope this clarifies why this happens. Would be happy to review relevant doc PRs.

**Comment by mindstorm38** [comment] 2022-05-10 10:53
Thank you for this clarification, I think you clearly explained all I needed. I'll work on a PR to include your comment in the document, which is really important imo.

**Comment by danielknell** [comment] 2022-05-27 18:06
as a really nasty workaround for anyone else finding themselves stuck here, the following gist seems to work in my 1.2.0b1 monorepo testing to generate pex files... 

https://gist.github.com/danielknell/7d1160d0fe41a3380182b235335a1b59

**Comment by danielknell** [comment] 2022-06-17 13:37
I wrote a poetry plugin to replace `FolderDependency` instances with regular `Dependency` instances, it reads the pyproject.toml of the dependency, gets the version number, prefixes with `^` and uses that in the wheels/sdists without having to touch pyproject.toml.

https://github.com/artisanofcode/poetry-stickywheel-plugin

**Comment by neersighted** [comment] 2022-10-04 08:06
Specialized duplicate of #1168.

**Closed by neersighted** 2022-10-04 08:06 UTC
Labels: status/duplicate
