### ISSUE TITLE
poetry init - Pressing ^C at "Enter package # to add ..." breaks tty

### ISSUE THREAD

**Issue by asottile** [python-poetry/poetry#2356] opened 2020-04-26 18:53 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).  **(it made no difference in the output)**

- **OS version and name**:  ubuntu 18.04
- **Poetry version**: 1.0.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: N/A

## Issue

```console
$ poetry init  -vvv

This command will guide you through creating your pyproject.toml config.

Package name [y]:  
Version [0.1.0]:  
Description []:  
Author [Anthony Sottile <asottile@umich.edu>, n to skip]:  
License []:  
Compatible Python versions [^3.6]:  

Would you like to define your main dependencies interactively? (yes/no) [yes] 
You can specify a package in the following forms:
  - A single name (requests)
  - A name and a constraint (requests ^2.23.0)
  - A git url (git+https://github.com/python-poetry/poetry.git)
  - A git url with a revision (git+https://github.com/python-poetry/poetry.git#develop)
  - A file path (../my-package/my-package.whl)
  - A directory (../my-package/)
  - An url (https://example.com/packages/my-package-0.1.0.tar.gz)

Search for package to add (or leave blank to continue): astpretty
Found 3 packages matching astpretty

Enter package # to add, or the complete package name if it is not listed: 
 [0] astpretty
 [1] asteria
 [2] moshmosh-base
 > (venv) asottile@nanobox:/tmp/y
$ I am typing at the terminal
(venv) asottile@nanobox:/tmp/y
$ but nothing is happening
(venv) asottile@nanobox:/tmp/y
$ eceho: command not found
(venv) asottile@nanobox:/tmp/y
$ here is me pressing enter
(venv) asottile@nanobox:/tmp/y
$ (venv) asottile@nanobox:/tmp/y
$ (venv) asottile@nanobox:/tmp/y
$ (venv) asottile@nanobox:/tmp/y
$ it only fixes itself after typing reset
(venv) asottile@nanobox:/tmp/y
```

(I was typing `echo ...` commands to produce those outputs)

the tty attributes (I believe noecho in this case?) should be reset on `^C` -- they currently are not

**Comment by finswimmer** [comment] 2022-10-21 09:46
Duplicate of #2067

**Closed by finswimmer** 2022-10-21 09:46 UTC
Labels: kind/bug, area/cli
