### ISSUE TITLE
'EmptyConstraint' object has no attribute 'allows'

### ISSUE THREAD

**Issue by asifali22** [python-poetry/poetry#4402] opened 2021-08-19 07:20 UTC
Everything was working fine until yesterday, I cleaned up my docker ending up removing all the images, etc. The project was building fine before clean up. Post clean up when I rebuilt the docker image, I started receiving the error:

```
 Writing lock file
#11 68.00
#11 68.00 [AttributeError]
#11 68.00 'EmptyConstraint' object has no attribute 'allows'
#11 68.00
#11 68.05 Traceback (most recent call last):
#11 68.05   File "/usr/local/lib/python3.8/site-packages/clikit/console_application.py", line 131, in run
#11 68.05     status_code = command.handle(parsed_args, io)
#11 68.05   File "/usr/local/lib/python3.8/site-packages/clikit/api/command/command.py", line 120, in handle
#11 68.05     status_code = self._do_handle(args, io)
#11 68.05   File "/usr/local/lib/python3.8/site-packages/clikit/api/command/command.py", line 171, in _do_handle
#11 68.05     return getattr(handler, handler_method)(args, io, self)
#11 68.05   File "/usr/local/lib/python3.8/site-packages/cleo/commands/command.py", line 92, in wrap_handle
#11 68.05     return self.handle()
#11 68.05   File "/usr/local/lib/python3.8/site-packages/poetry/console/commands/update.py", line 49, in handle
#11 68.05     return installer.run()
#11 68.05   File "/usr/local/lib/python3.8/site-packages/poetry/installation/installer.py", line 74, in run
#11 68.05     self._do_install(local_repo)
#11 68.05   File "/usr/local/lib/python3.8/site-packages/poetry/installation/installer.py", line 230, in _do_install
#11 68.05     self._filter_operations(ops, local_repo)
#11 68.05   File "/usr/local/lib/python3.8/site-packages/poetry/installation/installer.py", line 447, in _filter_operations
#11 68.05     ) or not self._env.is_valid_for_marker(package.marker):
#11 68.05   File "/usr/local/lib/python3.8/site-packages/poetry/utils/env.py", line 808, in is_valid_for_marker
#11 68.05     return marker.validate(self.marker_env)
#11 68.05   File "/usr/local/lib/python3.8/site-packages/poetry/version/markers.py", line 601, in validate
#11 68.05     if m.validate(environment):
#11 68.05   File "/usr/local/lib/python3.8/site-packages/poetry/version/markers.py", line 470, in validate
#11 68.05     if not m.validate(environment):
#11 68.05   File "/usr/local/lib/python3.8/site-packages/poetry/version/markers.py", line 361, in validate
#11 68.05     return self._constraint.allows(self._parser(environment[self._name]))
#11 68.05
```

Here's my `.toml` file:

```
[tool.poetry]
name = "myproject"
version = "0.1.0"
description = ""
authors = ["abc <abc@mail.in>"]

[tool.poetry.dependencies]
python = "^3.8"
python-dotenv = "^0.17.0"
numpy = ">=1.19.2"
pandas = "^1.2.4"
Flask = "^1.1.2"
Flask-SQLAlchemy = "^2.5.1"
Flask-Migrate = "^2.7.0"
newrelic = "^6.2.0"
python-jose = "^3.2.0"
Flask-JWT = "^0.3.2"
PyMySQL = "^1.0.2"
psycopg2 = "^2.8.6"
toolz = "^0.11.1"
sortedcontainers = "^2.3.0"
sqlalchemy-redshift = "^0.8.2"
boto3 = "^1.17.57"
joblib = "^1.0.1"
xgboost = "^1.4.2"
scikit-learn = "^0.24.2"
redis = "^3.5.3"
celery = {extras = ["redis"], version = "^5.1.0"}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

And here's my dockerfile:
```
FROM tiangolo/uwsgi-nginx-flask:python3.8

LABEL MAINTAINER="test@mail.in>"

ARG APP_DIR=/zest-srv
ARG SERVICE_NAME=service
ARG LOG_DIR_PATH=/var/log/uwsgi

WORKDIR $APP_DIR

RUN apt-get update \
     && apt-get install -y ca-certificates

ARG POETRY_VERSION=1.0.0

## Use this instead
# curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -

RUN pip install poetry==$POETRY_VERSION
RUN poetry --version
COPY poetry.lock pyproject.toml ${APP_DIR}/
RUN poetry update -vvv

# RUN mkdir ${APP_DIR}/lib
# COPY lib/transportstore-0.1.0-py3-none-any.whl ${APP_DIR}/lib/

RUN poetry config virtualenvs.create false \
    && poetry install --no-interaction --no-ansi

```

Here the debug logs: https://pastebin.com/sbiiDf8Z

**Comment by s3rius** [comment] 2021-08-19 07:42
I faced the same issue. My problem was that I was using SQLAlchemy with version "^1.4".
But yesterday SQLAlchemy released "1.4.23" with `platform_machine` constraint.

Here's the link: https://github.com/sqlalchemy/sqlalchemy/blob/4331c1902ae341158b597769f4e4991c0a7d5485/setup.cfg#L43.

My solution was to change SQLAlchemy dependency to:
```
SQLAlchemy = {version = ">=1.4,<1.4.23", extras = ["mypy"]}
```

**Comment by asifali22** [comment] 2021-08-19 07:55
> 
> 
> I faced the same issue. My problem was that I was using SQLAlchemy with version "^1.4".
> But yesterday SQLAlchemy released "1.4.23" with `platform_machine` constraint.
> 
> Here's the link: https://github.com/sqlalchemy/sqlalchemy/blob/4331c1902ae341158b597769f4e4991c0a7d5485/setup.cfg#L43.
> 
> My solution was to change SQLAlchemy dependency to:
> 
> ```
> SQLAlchemy = {version = ">=1.4,<1.4.23", extras = ["mypy"]}
> ```

Thanks this helped a lot. 

```
[tool.poetry.dependencies]
python = "^3.8"
python-dotenv = "^0.17.0"
numpy = ">=1.19.2"
pandas = "^1.2.4"
Flask = "^1.1.2"
Flask-SQLAlchemy = "^2.5.1"
Flask-Migrate = "^2.7.0"
python-jose = "^3.2.0"
Flask-JWT = "^0.3.2"
PyMySQL = "^1.0.2"
psycopg2 = "^2.8.6"
toolz = "^0.11.1"
SQLAlchemy = {version = "*", extras = ["mypy"]}
sortedcontainers = "^2.3.0"
sqlalchemy-redshift = "^0.8.2"
boto3 = "^1.17.57"
joblib = "^1.0.1"
xgboost = "^1.4.2"
scikit-learn = "^0.24.2"
redis = "^3.5.3"
celery = {extras = ["redis"], version = "^5.1.0"}
```

The above changes solved the issue for me. (Added SQLAlchemy)

**Comment by sdispater** [comment] 2021-08-19 08:10
Reopening since it should not crash like this when evaluating environment markers.

**Comment by pierresouchay** [comment] 2021-08-19 08:26
same issue here

**Comment by alonme** [comment] 2021-08-19 08:45
I think adding the offending package name to the error is crucial

**Comment by josef-polak-heu** [comment] 2021-08-19 09:06
Hi, i hot fixed this by adding:

```
def allows(self, other):  # type: ("ConstraintTypes") -> bool
    return True
```

to ./poetry/core/packages/constraints/empty_constraint.py

**Comment by trallnag** [comment] 2021-08-19 09:29
Same here

**Comment by trallnag** [comment] 2021-08-19 09:30
For me its sqlalchemy:

```
❯ poetry add sqlalchemy
Creating virtualenv test-CwXIzJDp-py3.9 in /home/jfn/.cache/pypoetry/virtualenvs
Using version ^1.4.23 for SQLAlchemy

Updating dependencies
Resolving dependencies... (0.5s)

Writing lock file

  AttributeError

  'EmptyConstraint' object has no attribute 'allows'

  at ~/.local/share/pypoetry/venv/lib/python3.9/site-packages/poetry/core/version/markers.py:291 in validate
      287│
      288│         if self._name not in environment:
      289│             return True
      290│
    → 291│         return self._constraint.allows(self._parser(environment[self._name]))
      292│
      293│     def without_extras(self):  # type: () -> MarkerTypes
      294│         return self.exclude("extra")
      295│
```

**Comment by ftheo** [comment] 2021-08-19 10:02
Same issue as well. Agree there should be more information on the error/offending package as it required digging into each dependency to identify the package causing the issue

**Comment by monkey0head** [comment] 2021-08-19 10:32
> Hi, i hot fixed this by adding method allows to EmptyConstraint class:
> 
> ```
> def allows(self, other):  # type: ("ConstraintTypes") -> bool
>     return True
> ```
> 
> to ./poetry/core/packages/constraints/empty_constraint.py

Thanks @josef-polak-heu! Perfectly solved the problem for me.

**Comment by lgeo3** [comment] 2021-08-19 10:39
In the sqlalchemy repo, one developer is saying that it could be due to poetry-core not able to parse correctly constraint like:

```
and platform_machine in "x86_64 X86_64 aarch64 AARCH64 ppc64le PPC64LE amd64 AMD64 win32 WIN32"
```

see comment here: 
https://github.com/sqlalchemy/sqlalchemy/issues/6136#issuecomment-901424041

if we look at parse_single_constraint (in poetry-core/core/package/constraints/__init__.py it seems that such kind of constraint is not handled by poetry and thus end as an EmptyConstraint

I am not sure that EmptyConstraint should provide a allows() that return True (maybee, but in my understanding, doing that will just hide the real problem here, that the constraint is not parsed correctly).

I am maybee completly wrong, so don't hesitate to tell me.

**Comment by kupuguy** [comment] 2021-08-19 12:02
I created an issue on sqlalchemy as I don't particularly care who is at fault, just want someone to fix it.
https://github.com/sqlalchemy/sqlalchemy/issues/6903

**Comment by sdispater** [comment] 2021-08-19 12:56
We have a fix ready on the `poetry-core` side.

We will make a new release of both `poetry-core` and `poetry` as soon as possible (either later today or tomorrow).

**Comment by sdispater** [comment] 2021-08-19 17:13
Release 1.1.8 – which hopefully fixes the issue – is out!

**Comment by Alesom** [comment] 2021-08-19 17:22
Version 1.1.8 fixed the issue for me! Thanks @sdispater!

**Comment by nacknime-official** [comment] 2021-08-19 17:24
Yes, it works, thank you!

> Release 1.1.8 – which hopefully fixes the issue – is out!

**Comment by chrisvdg** [comment] 2021-08-20 07:11
> Version 1.1.8 fixed the issue for me! Thanks @sdispater!

Also fixed for me!

**Comment by deanja** [comment] 2021-08-22 07:07
A big "thank you" to everyone involved in describing and resolving this issue. Tomorrow I'm due to release Python code to production **for the first time ever at our company**.    As a relative Python beginner this error had me despondent on Friday!   Sunday afternoon, the issue is already fixed and the fix released.  Just did a quick `poetry self update`  and I'm back on track.   I hope I can contribute to this project in future.    Thank you all!

**Comment by morne** [comment] 2021-08-22 14:03
After upgrading to 1.1.8 I still needed to patch the validate method in the markers module to check for an empty constraint to get it working.  As detailed in this pull request:
[pull request #194](https://github.com/python-poetry/poetry-core/pull/194)

**Closed** 2021-08-23 05:56 UTC
Labels: Bug, Triage

**Comment by dwyatte** [comment] 2021-08-24 16:40
> Version 1.1.8 fixed the issue for me! Thanks @sdispater!

Given https://github.com/python-poetry/poetry/issues/4429 and the fact that this error is in poetry-core, can one of the maintainers comment whether upgrading poetry-core>=1.0.4 is the better fix?
