### ISSUE TITLE
Poetry add takes forever

### ISSUE THREAD

**Issue by xtfocus** [python-poetry/poetry#8790] opened 2023-12-14 10:15 UTC
Hi,
I'm a Linux user, new to poetry. Installed Poetry (1.7.1) with
```bash
curl -sSL https://install.python-poetry.org | python3 -
```

then I created a virtual environtment with 
```bash
mkvirtualenv myenv -p  ~/.pyenv/versions/3.9.16/bin/python3.9
```
Then after `poetry init`, I got `pyproject.toml`:
```
[tool.poetry]
name = "faraday"
version = "0.1.0"
description = ""
authors = ["john <john.doe@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

1. When I do `poetry add` any packages, the command just hang for several minutes until I hit Ctrl C to kill it.

2. Poetry self update stuck on `Updating Poetry version ...` forever (10min until I turn it off).

Please tell me if you need any information to demystify this.

**Comment by dimbleby** [comment] 2023-12-14 10:41
obviously this doesn't happen for everyone else

unless you can provide a reproducible example it's unlikely that anyone but you can debug what's happening.

A dockerfile is a particularly convenient way of sharing such an example, ensuring that it really does reproduce not only on your machine

**Comment by clintonroy** [comment] 2023-12-14 21:59
As the bug template asks for, what happens when you add -vvv to the add command? Have you tried disabling the keyring? Possibly it's building a package, are there any processes kicked off?

**Comment by smurfix** [comment] 2023-12-16 02:22
Happens for me too.

`poetry install -vvv` does not enlighten.

In my case, the reason **is** in fact that it tries to access the keyring and doesn't get a DBus reply. I  found this by judicious use of `strace` and `pdb` since poetry doesn't tell us what it's doing. This should be fixed.

> Have you tried disabling the keyring?

Have you tried teaching poetry to tell us (a) that this might be necessary (b) how to do it? `poetry --help` or `poetry install --help` do not enlighten. I had to hack `poetry/utils/password_manager.py:PoetryKerring.is_available` to return `False` 

Adding a breakpoint to this classes' `_check` method in line 120 reveals that this method is hammered from multiple threads, which might be part of the problem.

Finally, (c), I have to admit that I fail to understand why poetry even tries to do any keyring operations when it clearly doesn't need to. And no in my case it's not building anything (and there is no reason why it should need any privileges even if it did), just pulling stuff from pypi and unpacking it into a venv; in fact, the aforementioned hack results in a perfectly working `poetry` installation.

**Comment by radoering** [comment] 2023-12-16 05:26
> Have you tried teaching poetry to tell us (a) that this might be necessary (b) how to do it? poetry --help or poetry install --help do not enlighten. I had to hack poetry/utils/password_manager.py:PoetryKerring.is_available to return False to get past this point.

IMO, this is too much of an edge case to put into `poetry --help` and maybe even `poetry install --help`. Maybe, it's something for the [FAQ](https://python-poetry.org/docs/faq/).

> Finally, (c), I have to admit that I fail to understand why poetry even tries to do any keyring operations when it clearly doesn't need to.

I'm not that deep into this keyring topic, but I suppose https://github.com/python-poetry/poetry/pull/7038#issuecomment-1315741622 might be a reason why we are trying to use keyring even if it's not necessary.

Nevertheless, closing as duplicate of #8623 or #8761.

**Closed by radoering** 2023-12-16 05:26 UTC
Labels: kind/bug, status/triage
