### ISSUE TITLE
Add a project setting to control if and where a project can be published

### ISSUE THREAD

**Issue by J-M0** [python-poetry/poetry#3692] opened 2021-02-13 16:15 UTC
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

I would like to propose that `poetry` have a project-level configuration option that would let you restrict which repositories a package gets published to or even prevent it from being published at all.

Rust's package manager `cargo` has a field in its `Cargo.toml` file that does just that. I think the behavior described here is exactly what `poetry` should adopt.

https://doc.rust-lang.org/cargo/reference/manifest.html#the-publish-field

I work on both public and private projects and this would be a nice addition for my peace of mind. I could make sure a private package doesn't accidentally get published to PyPI or even just prevent a package that is early in development from being published prematurely. It would also make publishing to private repositories easier as you would not need to specify the private repository with `poetry publish -r`.

**Comment by NickleDave** [comment] 2021-03-03 01:08
The way to do this is to include it in the "classifiers" section

```toml
[tool.poetry]
# ...
classifiers = [
    "Topic :: Software Development :: Build Tools",
    "Topic :: Software Development :: Libraries :: Python Modules"
]
```

You want to add
```
        "Private :: Do not Upload"
```
for your private projects

**Comment by NickleDave** [comment] 2021-03-03 01:11
AFAIK this is the "official Pythonic" way, see
https://github.com/pypa/packaging.python.org/issues/643

**Comment by J-M0** [comment] 2021-06-05 19:18
That's a good trick to know, thank you. I still think being able to specify a default repository to publish to would be useful and that enforcing not uploading a package would be better served at the tool level rather than having PyPI reject a package after upload.

**Comment by gh640** [comment] 2021-09-04 11:35
This might be same as #1537  .

**Comment by skewty** [comment] 2022-04-11 22:39
Is this supported now?  Its been over a year with no comments / updates.

**Comment by imochoa** [comment] 2022-08-29 08:43
> Is this supported now? Its been over a year with no comments / updates.

I think this doesn't actually depend on poetry. It's specified by PyPI already:
https://pypi.org/classifiers/

**Comment by finswimmer** [comment] 2024-10-30 07:55
Duplicate of #1537

**Closed by finswimmer** 2024-10-30 07:55 UTC
Labels: kind/feature, status/triage
