### ISSUE TITLE
Poetry init: 'utf-8' codec can't encode character '\udcc5' in position 23: surrogates not allowed

### ISSUE THREAD

**Issue by timthelion** [python-poetry/poetry#1955] opened 2020-01-29 11:29 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**:  Debian stretch
- **Poetry version**: 1.0.2
- **Terminal**: xfce4-terminal 0.8.3

## Issue

Poetry init crashes on saving if you type and then delete (using the backspace key) a Czech unicode character in any field. For example, here I have named the project `fč<backspace>f`.

````
$ poetry init -vvv

This command will guide you through creating your pyproject.toml config.

Package name [example]:  ff
Version [0.1.0]:  
Description []:  
Author [None, n to skip]:  no
License []:  
Compatible Python versions [^3.7]:  

Would you like to define your main dependencies interactively? (yes/no) [yes] no
Would you like to define your dev dependencies (require-dev) interactively (yes/no) [yes] no
Generated file

[tool.poetry]
name = "f�f"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"


Do you confirm generation? (yes/no) [yes] 

[UnicodeEncodeError]
'utf-8' codec can't encode character '\udcc5' in position 23: surrogates not allowed

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/usr/local/lib/python3.7/site-packages/clikit/api/command/command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "/usr/local/lib/python3.7/site-packages/clikit/api/command/command.py", line 171, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/usr/local/lib/python3.7/site-packages/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File "/usr/local/lib/python3.7/site-packages/poetry/console/commands/init.py", line 204, in handle
    f.write(content)
````

**Comment by mkniewallner** [comment] 2022-09-18 08:42
Cannot reproduce either.

Since we didn't hear back from the author, closing the issue. If you are still able to reproduce on newer versions, and believe that this is something related to Poetry, and not your terminal, feel free to reopen it.

**Closed by mkniewallner** 2022-09-18 08:42 UTC
Labels: kind/bug, area/cli

**Comment by black-snow** [comment] 2024-02-02 14:57
Just hit this with Poetry `1.7.1`, macOS `14.3`, Python `3.11.7`:
![screenshot](https://github.com/python-poetry/poetry/assets/579733/c180c7fa-a631-45a8-b929-e411bd225b24)
