### ISSUE TITLE
pre-commit fails when pyproject.toml is in subdirectory

### ISSUE THREAD

**Issue by wgiddens** [python-poetry/poetry#6259] opened 2022-08-29 02:37 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **Poetry version**: 1.2.0-rc2

## Issue

We are setting up the new pre-commit checks for our project. Our Python source code lives in a subfolder inside the main repo.  The full path to pyproject.toml is `<repo>/backend/src/pyproject.toml`.  The poetry checks fail because they can't find pyproject.toml in the root directory.  

The pre-commit project does not support changing the working directory for hooks and will not add support. See https://github.com/pre-commit/pre-commit/issues/1110#issuecomment-518939116

pre-commit hooks can be configured to pass a matching filename argument, but poetry does not have a way to operate on anything but the current working directory.

**Comment by finswimmer** [comment] 2022-10-07 10:23
Hey @wgiddens,

I'm closing this as a specialized duplicate of https://github.com/python-poetry/poetry/issues/2179. 

fin swimmer

**Closed by finswimmer** 2022-10-07 10:23 UTC
Labels: kind/feature
