### ISSUE TITLE
Error Creating New Poetry Environment

### ISSUE THREAD

**Issue by Arthur-Huan** [python-poetry/poetry#6551] opened 2022-09-17 20:09 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: <Ubuntu 22.04.1 LTS>
- **Poetry version**: <1.2.1>
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: <[!-- Gist Link Here --](https://gist.github.com/Arthur-Huan/2ae54253a676a80282b5bd368f03e4f7)>

## Issue

This is my first time using Poetry. When using PyCharm to configure a poetry interpreter, it says 
>Directory /home/arthur/.cache/pypoetry/virtualenvs/pyproject-bQEURbrH-py3.10/bin/python not found

When I try again to configure the interpreting using the environment that was created, it says Error Running Poetry. The command output is:

> Recreating virtualenv pyproject-bQEURbrH-py3.10 in /home/arthur/.cache/pypoetry/virtualenvs/pyproject-bQEURbrH-py3.10
> 
> The virtual environment found in /home/arthur/.cache/pypoetry/virtualenvs/pyproject-bQEURbrH-py3.10 seems to be broken.
> 
> Invalid PEP 440 version: '1.1build1'

I've seen the same error from the PyCharm forums, and applied the fix 

`sudo apt install python3-pip
pip3 install virtualenv`

Which didn't change anything. I've also tried installing python3-venv too.

**Comment by Secrus** [comment] 2022-09-17 20:37
could you try it from CLI? It should work fine. What you are describing seems to be a Pycharm bug, not a Poetry one.

**Comment by Arthur-Huan** [comment] 2022-09-17 21:05
> could you try it from CLI? It should work fine. What you are describing seems to be a Pycharm bug, not a Poetry one.

I did try creating an environment from the CLI, however the project doesn't have an interpreter, nor does it have a poetry.lock file.

**Comment by krageon** [comment] 2022-10-04 12:50
This consistently breaks because of ubuntu packaging: https://bugs.launchpad.net/ubuntu/+source/python-debian/+bug/1926870

This is shit, but it would be good if I could at least work around dist-packages having things poetry can't work with. As it stands I don't think I can solve it at all (e.g. I can't tell it to ignore those packages that don't work).

**Comment by neersighted** [comment] 2022-10-04 14:21
I think there are two things going on here -- Pycharm is trying to create a Poetry environment in an odd way that is affected by system packages, and failing.

@krageon, I suspect that instead you are hitting https://github.com/python-poetry/poetry/discussions/6623, especially if you have `virtualenvs.create false` or `virtualenvs.opts.system-site-packages true` set. In either of those cases this is not currently considered a Poetry bug, though I do have some ideas an interested contributor could pursue to try and avoid the pitfalls I originally described in that discussion.

In any case, barring a reproduction that doesn't involve PyCharm, I'm closing this for now -- if you can reproduce this occurring with a simple `poetry install` in a clean environment with default options set (e.g. in a Ubuntu 22.04 container), please open a new issue to track the PyCharm-free reproduction.

**Closed by neersighted** 2022-10-04 14:21 UTC
Labels: kind/bug, status/external-issue

**Comment by krageon** [comment] 2022-10-04 14:44
I have neither of those things set. I'll attempt to create a docker container that has this issue so you can see what goes wrong.

**Comment by krageon** [comment] 2022-10-04 15:04
I see it is this https://github.com/python-poetry/poetry/issues/4597#issuecomment-1233290435 this issue. The workaround there works as well.
