### ISSUE TITLE
Distinguish between libraries and applications

### ISSUE THREAD

**Issue by MartinThoma** [python-poetry/poetry#3334] opened 2020-11-06 23:29 UTC
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request
When you have a pure application, e.g. a package which is intended not to be imported by other packages, but only to be executed directly (e.g. CLI application, a web service, some GUI program), it would be nice to have reliable installations at the client.

For reliable installations, it is important that the dependencies (including transitive ones) are pinned. They are pinned in the poetry.lock file, but that file is not uploaded / used when a package built with poetry, uploaded to PyPI.org is installed via pip.

My suggestion is:

* Within `[tool.poetry]`, add `is-pure-application: true / false` or similar (never-included? no-library?)
* When this attribute is present and true, then poetry adds the transitive dependencies to the shipped `setup.py` file
* Then, when installed via `pipx`, one can be absolutely certain about what is installed and have way more control about the environment.

I'm uncertain, however, how to deal with the "normal" pip which does not create a virtual environment for such a package. That would be problematic.

**Comment by sinoroc** [comment] 2020-11-06 23:49
I get the general idea, but the suggested method does not make sense to me.

From my point of view, what would make more sense would be to instruct `poetry build` to write the pinned dependencies as `Requires-Dist` in the distributions.

This is typically the kind of things I would like to see implemented as a plugin, not necessarily part of _poetry_ proper. Because this seems like one nice way to shoot yourself in the foot, if you pin everything in the distributions without knowing what you are doing.

> I'm uncertain, however, how to deal with the "normal" pip which does not create a virtual environment for such a package. That would be problematic.

This does not seem feasible. I do not see what role _pip_ would play in that. I'd rather recommend another plugin that would output a _zipapp_ containing pinned dependencies.

**Comment by MartinThoma** [comment] 2020-11-07 00:12
> this seems like one nice way to shoot yourself in the foot

Yes, for sure 😁 👍

**Comment by MartinThoma** [comment] 2020-11-07 00:13
Could you please point me to documentation about how to create plugins for poetry?

**Comment by sinoroc** [comment] 2020-11-07 10:45
The plugin system is under development, scheduled for [version 1.2](https://github.com/python-poetry/poetry/projects/6):

* [_WIP - Plugin system (#1237)_](https://github.com/python-poetry/poetry/pull/1237)

**Comment by finswimmer** [comment] 2020-11-08 06:42
> From my point of view, what would make more sense would be to instruct poetry build to write the pinned dependencies as Requires-Dist in the distributions.

There is a feature request for this: https://github.com/python-poetry/poetry/issues/2778

But I'm with you @sinoroc  that this is a good way to shoot yourself in the foot :)

@MartinThoma: I will close your issue as a more or less duplicate of #2778. Feel free to leave a comment if you disagree with it.

**Closed by finswimmer** 2020-11-08 06:42 UTC
Labels: Feature, Triage

**Comment by sinoroc** [comment] 2020-12-01 08:16
@MartinThoma A PR has been filed: https://github.com/python-poetry/poetry/pull/3341. Would you mind giving it a try, giving feedback on it, reviewing the code? Whatever helps to get things moving...

**Comment by bneijt** [comment] 2021-05-01 18:50
I've written a small script to achieve an installation you mention, called poetry-lock-package. However, if you create a package like that, it will nolonger be able to share an environment with other programs, effectively requiring an isolated application environment (like docker, pyenv, etc.).

I have used this approach for deploying applications on Databricks as well and that works great, but you need to make sure you don't require stuff that Databricks secretly already has installed on the python path (like pyspark) or for which the environment brings in proprietary "enhanced" packages.

The poetry-lock-package script is crude, but effective. You can read more at https://bneijt.nl/pr/poetry-lock-package/
