### ISSUE TITLE
Poetery 1.1.9 hashing bug?

### ISSUE THREAD

**Issue by Casyfill** [python-poetry/poetry#4538] opened 2021-09-21 20:40 UTC
I have a dependency package pulled from artifactory, and the lock file has hashes for this specific package in md5 for some reason. However on `poetry install`, it seems to hash it to sha256 and hence fail to install with this issue:
```
Retrieved digest for link SE-8.4.282.tar.gz(sha256:4bbb76d0ad07f2a30eac0f4cfbc29d2516866351e55ca6600250cfde3697f0a8) not in poetry.lock metadata
```

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOS BigSur 11.5.2
- **Poetry version**: 1.1.9
- **Link of a [Gist](https://gist.github.com/Casyfill/76386baf743d9631ba115dc15ce86e32)

**Comment by colindean** [comment] 2021-09-21 20:53
I am seeing this, too, reported by a dev on my team. I'm still waiting to hear on the Poetry version in use but I'm guessing 1.1.9.

**Comment by colindean** [comment] 2021-09-21 20:53
This issue duplicates https://github.com/python-poetry/poetry/issues/4523.

**Comment by cbini** [comment] 2021-09-21 22:21
Think it still might be broken in 1.10? Getting the same error with `poetry add pandas`

**Comment by finswimmer** [comment] 2021-09-22 04:36
Ad @colindean said:

Duplicate of #4523

**Closed by finswimmer** 2021-09-22 04:36 UTC
Labels: Duplicate
