### ISSUE TITLE
'Unable to find a valid git executable' when running 'poetry new' command on Windows 10

### ISSUE THREAD

**Issue by knikolaeff** [python-poetry/poetry#5723] opened 2022-05-30 21:05 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10 Pro 21H2
- **Poetry version**: 1.1.13

## Issue
Hi! I was trying to create a new project, but got the following error:
```shell
D:\>poetry new django-app -vvv
Program Files\Git\cmd\git.exe

  Stack trace:

  6  ~\.poetry\lib\poetry\_vendor\py3.10\clikit\console_application.py:131 in run
      129│             parsed_args = resolved_command.args
      130│
    → 131│             status_code = command.handle(parsed_args, io)
      132│         except KeyboardInterrupt:
      133│             status_code = 1

  5  ~\.poetry\lib\poetry\_vendor\py3.10\clikit\api\command\command.py:120 in handle
      118│     def handle(self, args, io):  # type: (Args, IO) -> int
      119│         try:
    → 120│             status_code = self._do_handle(args, io)
      121│         except KeyboardInterrupt:
      122│             if io.is_debug():

  4  ~\.poetry\lib\poetry\_vendor\py3.10\clikit\api\command\command.py:171 in _do_handle
      169│         handler_method = self._config.handler_method
      170│
    → 171│         return getattr(handler, handler_method)(args, io, self)
      172│
      173│     def __repr__(self):  # type: () -> str

  3  ~\.poetry\lib\poetry\_vendor\py3.10\cleo\commands\command.py:92 in wrap_handle
       90│         self._command = command
       91│
    →  92│         return self.handle()
       93│
       94│     def handle(self):  # type: () -> Optional[int]

  2  ~\.poetry\lib\poetry\console\commands\new.py:49 in handle
      47│         readme_format = "rst"
      48│
    → 49│         config = GitConfig()
      50│         author = None
      51│         if config.get("user.name"):

  1  ~\.poetry\lib\poetry\_vendor\py3.10\poetry\core\vcs\git.py:207 in __init__
      205│             config_list = decode(
      206│                 subprocess.check_output(
    → 207│                     [executable(), "config", "-l"], stderr=subprocess.STDOUT
      208│                 )
      209│             )

  RuntimeError

  Unable to find a valid git executable

  at ~\.poetry\lib\poetry\_vendor\py3.10\poetry\core\vcs\git.py:189 in executable
      185│     else:
      186│         _executable = "git"
      187│
      188│     if _executable is None:
    → 189│         raise RuntimeError("Unable to find a valid git executable")
      190│
      191│     return _executable
      192│
      193│
```
I can easily find Git using the following command:
```shell
D:\>where git
D:\Program Files\Git\cmd\git.exe
```

I started to look through the source code and found this method:
![image](https://user-images.githubusercontent.com/80189148/171058062-787d3168-c4e3-4fe5-a787-a58906762a17.png)
The only way for me to fix the problem was commenting the 'if' statement made for Windows systems.
![image](https://user-images.githubusercontent.com/80189148/171058716-a7475313-bd42-4de7-89db-0cd55ddf3da9.png)

I suppose, something weird is happening with Windows-like paths, because some experiments with this method returned me the path of my Git executable, but without 'D:/' prefix. It worth mentioning that Poetry is installed on my C drive, while Git is installed on my D drive.

**Comment by abn** [comment] 2022-05-30 21:22
This should have been resolved by #5428. Please try poetry on master.

#### Install Poetry from VCS
```sh
pipx install --force --suffix=@git 'poetry @ git+https://github.com/python-poetry/poetry.git'
```

**Comment by knikolaeff** [comment] 2022-05-30 21:52
> This should have been resolved by #5428. Please try poetry on master.
> 
> #### Install Poetry from VCS
> ```shell
> pipx install --force --suffix=@git 'poetry @ git+https://github.com/python-poetry/poetry.git'
> ```

Hello and thanks for the quick response. I tried reinstalling Poetry with a regular pip, using both scripts from the official docs and now decided to try your command. Unfortunately, it throws an error.
```shell

D:\>pipx install --force --suffix=@git 'poetry @ git+https://github.com/python-poetry/poetry.git'
usage: pipx [-h] [--version] {install,inject,upgrade,upgrade-all,uninstall,uninstall-all,reinstall,reinstall-all,list,run,runpip,ensurepath,environment,completions} ...
pipx: error: unrecognized arguments: @ git+https://github.com/python-poetry/poetry.git'
```

**Comment by mkniewallner** [comment] 2022-06-16 21:04
> UPD: I have just tried to install Poetry right from this repo by cloning it and running the install-poetry script. After a succesful installation, the issue persists.

Are you sure that it picked up latest version of Poetry, and not a `1.1.x` leftover that you previously installed?
You should be able to validate that by running `poetry --version`.

If you do have latest version, do you have the exact same issue as you had, or is it a different one?

**Comment by simprecicchiani** [comment] 2022-07-25 09:47
I'm experiencing the same issue. First time installing poetry on the device (version `1.1.14`).

**Comment by simprecicchiani** [comment] 2022-07-25 10:15
> I'm experiencing the same issue. First time installing poetry on the device (version `1.1.14`).

I found a workaround using Git Bash instead of PS.

**Comment by finswimmer** [comment] 2022-10-05 15:32
Since Poetry 1.2 dulwich is used to interact with git. So I think we can close this issue.

**Closed by finswimmer** 2022-10-05 15:32 UTC
Labels: kind/bug, status/waiting-on-response, area/windows

**Comment by LexSong** [comment] 2022-12-13 04:25
The issue still exists with version 1.3.1, from the same source code above.
I don't think dulwich has anything with this issue.

```
  RuntimeError

  Unable to find a valid git executable

  at .local\pipx\venvs\poetry\lib\site-packages\poetry\core\vcs\git.py:182 in executable
      178│     else:
      179│         _executable = "git"
      180│
      181│     if _executable is None:
    → 182│         raise RuntimeError("Unable to find a valid git executable")
      183│
      184│     return _executable
      185│
      186│
```

**Comment by benjs** [comment] 2023-04-24 07:47
Hey, the issue still persists.

The problem is like stated above in the [following lines](https://github.com/python-poetry/poetry-core/blob/e81166e744fb3944ad4089cd526a73182e1d3483/src/poetry/core/vcs/git.py#L171-L177), in the successful try-case the `_executable` is not set:
```python
    if WINDOWS:
        # Finding git via where.exe
        where = "%WINDIR%\\System32\\where.exe"
        paths = subprocess.check_output(
            [where, "git"], shell=True, encoding="oem"
        ).split("\n")
        for path in paths:
            if not path:
                continue

            _path = Path(path.strip())
            try:
                _path.relative_to(Path.cwd())
               # PROBLEM HERE: _executable not set
            except ValueError:
                _executable = str(_path)

                break
```

I can submit a PR if you want to.

**Comment by jomaro110** [comment] 2023-06-27 18:05
Experiencing the same issue:
Unable to find a valid git executable

With Poetry version 1.5.1

**Comment by jomaro110** [comment] 2023-06-27 19:04
> 

And I have git installed and in the Path environment variables.

**Comment by jomaro110** [comment] 2023-06-27 19:12
Ok, the issue is I can't create new project in the C:\
But if I make new folder I can get it to work inside that folder, but not in the C:\ root.

**Comment by clintonroy** [comment] 2023-06-28 00:06
Please always give full error logs. It's clearly not the same issue as the one opened with a completely different version of poetry. If you don't give us the details we request, we can't do anything.

**Comment by LexSong** [comment] 2023-06-29 13:58
Here is the full log on my machine:

```
C:\Users\LexSong>poetry new test-project -vvv

  Stack trace:

  9  .local\pipx\venvs\poetry\Lib\site-packages\cleo\application.py:327 in run
      325│
      326│             try:
    → 327│                 exit_code = self._run(io)
      328│             except BrokenPipeError:
      329│                 # If we are piped to another process, it may close early and send a

  8  .local\pipx\venvs\poetry\Lib\site-packages\poetry\console\application.py:190 in _run
      188│         self._load_plugins(io)
      189│
    → 190│         exit_code: int = super()._run(io)
      191│         return exit_code
      192│

  7  .local\pipx\venvs\poetry\Lib\site-packages\cleo\application.py:431 in _run
      429│             io.input.interactive(interactive)
      430│
    → 431│         exit_code = self._run_command(command, io)
      432│         self._running_command = None
      433│

  6  .local\pipx\venvs\poetry\Lib\site-packages\cleo\application.py:473 in _run_command
      471│
      472│         if error is not None:
    → 473│             raise error
      474│
      475│         return terminate_event.exit_code

  5  .local\pipx\venvs\poetry\Lib\site-packages\cleo\application.py:457 in _run_command
      455│
      456│             if command_event.command_should_run():
    → 457│                 exit_code = command.run(io)
      458│             else:
      459│                 exit_code = ConsoleCommandEvent.RETURN_CODE_DISABLED

  4  .local\pipx\venvs\poetry\Lib\site-packages\cleo\commands\base_command.py:119 in run
      117│         io.input.validate()
      118│
    → 119│         status_code = self.execute(io)
      120│
      121│         if status_code is None:

  3  .local\pipx\venvs\poetry\Lib\site-packages\cleo\commands\command.py:62 in execute
       60│
       61│         try:
    →  62│             return self.handle()
       63│         except KeyboardInterrupt:
       64│             return 1

  2  .local\pipx\venvs\poetry\Lib\site-packages\poetry\console\commands\new.py:62 in handle
       60│         readme_format = self.option("readme") or "md"
       61│
    →  62│         config = GitConfig()
       63│         author = None
       64│         if config.get("user.name"):

  1  .local\pipx\venvs\poetry\Lib\site-packages\poetry\core\vcs\git.py:199 in __init__
      197│         try:
      198│             config_list = subprocess.check_output(
    → 199│                 [executable(), "config", "-l"], stderr=subprocess.STDOUT
      200│             ).decode()
      201│

  RuntimeError

  Unable to find a valid git executable

  at .local\pipx\venvs\poetry\Lib\site-packages\poetry\core\vcs\git.py:182 in executable
      178│     else:
      179│         _executable = "git"
      180│
      181│     if _executable is None:
    → 182│         raise RuntimeError("Unable to find a valid git executable")
      183│
      184│     return _executable
      185│
      186│
```

I think @benjs is on the right course here.

**Comment by PlkMarudny** [comment] 2023-08-09 07:41
```
PS C:\Users\XXX\Documents\python> poetry new whisper -vvv

  Stack trace:

  9  ~\AppData\Roaming\pypoetry\venv\Lib\site-packages\cleo\application.py:327 in run
      325│ 
      326│             try:
    → 327│                 exit_code = self._run(io)
      328│             except BrokenPipeError:
      329│                 # If we are piped to another process, it may close early and send a

  8  ~\AppData\Roaming\pypoetry\venv\Lib\site-packages\poetry\console\application.py:190 in _run
      188│         self._load_plugins(io)
      189│
    → 190│         exit_code: int = super()._run(io)
      191│         return exit_code
      192│ 

  7  ~\AppData\Roaming\pypoetry\venv\Lib\site-packages\cleo\application.py:431 in _run
      429│             io.input.interactive(interactive)
      430│ 
    → 431│         exit_code = self._run_command(command, io)
      432│         self._running_command = None
      433│

  6  ~\AppData\Roaming\pypoetry\venv\Lib\site-packages\cleo\application.py:473 in _run_command
      471│ 
      472│         if error is not None:
    → 473│             raise error
      474│
      475│         return terminate_event.exit_code

  5  ~\AppData\Roaming\pypoetry\venv\Lib\site-packages\cleo\application.py:457 in _run_command
      455│ 
      456│             if command_event.command_should_run():
    → 457│                 exit_code = command.run(io)
      458│             else:
      459│                 exit_code = ConsoleCommandEvent.RETURN_CODE_DISABLED

  4  ~\AppData\Roaming\pypoetry\venv\Lib\site-packages\cleo\commands\base_command.py:119 in run
      117│         io.input.validate()
      118│
    → 119│         status_code = self.execute(io)
      120│
      121│         if status_code is None:

  3  ~\AppData\Roaming\pypoetry\venv\Lib\site-packages\cleo\commands\command.py:62 in execute
       60│ 
       61│         try:
    →  62│             return self.handle()
       63│         except KeyboardInterrupt:
       64│             return 1

  2  ~\AppData\Roaming\pypoetry\venv\Lib\site-packages\poetry\console\commands\new.py:62 in handle
       60│         readme_format = self.option("readme") or "md"
       61│
    →  62│         config = GitConfig()
       63│         author = None
       64│         if config.get("user.name"):

  1  ~\AppData\Roaming\pypoetry\venv\Lib\site-packages\poetry\core\vcs\git.py:199 in __init__
      197│         try:
      198│             config_list = subprocess.check_output(
    → 199│                 [executable(), "config", "-l"], stderr=subprocess.STDOUT
      200│             ).decode()
      201│

  RuntimeError

  Unable to find a valid git executable

  at ~\AppData\Roaming\pypoetry\venv\Lib\site-packages\poetry\core\vcs\git.py:182 in executable
      178│     else:
      179│         _executable = "git"
      180│
      181│     if _executable is None:
    → 182│         raise RuntimeError("Unable to find a valid git executable")
      183│
      184│     return _executable
      185│
      186│
```

Poetry 1.5.1 on Windows,  git exists and available through $env:PATH

**Comment by knikolaeff** [comment] 2023-08-09 22:28
@benjs I believe, your PR will resolve the issue. Could you please submit it?
