### ISSUE TITLE
when "poetry install" installs the project’s package with a different version, the previous version should be removed

### ISSUE THREAD

**Issue by clo-vis** [python-poetry/poetry#4526] opened 2021-09-20 15:59 UTC
I have searched (A LOT) the issues, StackOverflow, and the docs before submitting this request.

## Feature Request
Initial pyproject.toml: 
```
[tool.poetry]
name = "example"
version = "0.1.0"
description = "Project description"
authors = ["Author1"]
...
```

The project has a script:
```
from importlib.metadata import metadata

if __name__ == '__main__':
    for key, value in metadata('example').items():
        print(f'{key}={value}')
```

By running the script (after poetry install), the output is as expected:

```
Metadata-Version=2.1
Name=example
Version=0.1.0
Summary=Project description
Author=Author1
...
```

Then pyproject.toml is updated:

```
[tool.poetry]
name = "example"
version = "0.1.1"
description = "Improved project description"
authors = ["Author1", "Author2"]
```
And poetry install is invoked again:

```
Installing dependencies from lock file
No dependencies to install or update


Installing the current project: example (0.1.1)
```

However, by running the script again, the metadata shown is the same of version 0.1.0.

Looking at the cache directory, I found both versions
```
…
20.09.2021  17:40    <DIR>          example-0.1.0.dist-info
20.09.2021  17:42    <DIR>          example-0.1.1.dist-info
20.09.2021  17:42                44 example.pth
…
```

So the feature request is "poetry install" should remove the previous metadata before installing the new one.

**Comment by finswimmer** [comment] 2021-09-20 17:49
Hello,

this is duplicate of:

* #2855
* #4498 

fin swimmer

**Closed by finswimmer** 2021-09-20 17:49 UTC
Labels: Feature, Triage
