### ISSUE TITLE
1.2.0 leaves leftover temporary files in /tmp after "poetry add", "poetry install" etc.; 1.1.15 does not do so.

### ISSUE THREAD

**Issue by glennmatthews** [python-poetry/poetry#6425] opened 2022-09-06 14:14 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Debian Bullseye (e.g., python:3.7-slim Docker image)
- **Poetry version**: 1.2.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: n/a

## Issue

Poetry 1.2.0 leaves files in `/tmp` after doing a `poetry add`, `poetry install`, or `poetry remove` command. Poetry 1.1.15 does not show this behavior. We noticed this due to an increase in our Docker image size after switching to 1.2.0 (yes, we should explicitly clean up `/tmp` or make it a tempfs, and we will probably do so for our project now, but this wasn't an issue with our builds under 1.1.15).

Easily reproduced on a clean system by installing either version of Poetry, then doing a `poetry init` (leaving all inputs as defaults except an arbitrary package name) and then adding any package, for example, `poetry add certifi` or `poetry add --dev isort`.

Under Poetry 1.2.0 it appears that one file gets left under /tmp for each Python package that poetry processes or installs. No such files are leftover when following the same steps with Poetry 1.1.15. The contents of each such file appear to be certificate related, e.g.:

```
root@9af68a6a70c6:/# head /tmp/tmpn0onvcob 

# Issuer: CN=GlobalSign Root CA O=GlobalSign nv-sa OU=Root CA
# Subject: CN=GlobalSign Root CA O=GlobalSign nv-sa OU=Root CA
# Label: "GlobalSign Root CA"
# Serial: 4835703278459707669005204
# MD5 Fingerprint: 3e:45:52:15:09:51:92:e1:b7:5d:37:9f:b1:87:29:8a
# SHA1 Fingerprint: b1:bc:96:8b:d4:f4:9d:62:2a:a8:9a:81:f2:15:01:52:a4:1d:82:9c
# SHA256 Fingerprint: eb:d4:10:40:e4:bb:3e:c7:42:c9:e3:81:d3:1e:f2:a4:1a:48:b6:68:5c:96:e7:ce:f3:c1:df:6c:d4:33:1c:99
-----BEGIN CERTIFICATE-----
MIIDdTCCAl2gAwIBAgILBAAAAAABFUtaw5QwDQYJKoZIhvcNAQEFBQAwVzELMAkG
```

**Comment by neersighted** [comment] 2022-09-06 15:08
I am unable to reproduce this on 1.2.0 -- could you please provide a detailed reproduction? Mine is below:

```
$ docker run --rm -it --entrypoint /bin/bash python:3.10
root@container:/ curl https://install.python-poetry.org | python3 -
root@container:/ git clone https://github.com/python-poetry/poetry && cd poetry
root@container:/ ~/.local/bin/poetry install
root@container:/ ls /tmp
[empty]
```

**Comment by glennmatthews** [comment] 2022-09-06 17:39
Interesting. I can't reproduce it with python 3.10 either. I can confirm that the issue is seen with 3.7, 3.8, and 3.9, for example:

```
$ docker run -it --entrypoint /bin/bash python:3.8
root@7ef6c2970605:/# curl https://install.python-poetry.org | python3 - --version 1.2.0
root@7ef6c2970605:/# ~/.local/bin/poetry init

This command will guide you through creating your pyproject.toml config.

Package name []:  mypkg
Version [0.1.0]:  
Description []:  
Author [None, n to skip]:  n
License []:  
Compatible Python versions [^3.8]:  

Would you like to define your main dependencies interactively? (yes/no) [yes] n
Would you like to define your development dependencies interactively? (yes/no) [yes] n
Generated file

[tool.poetry]
name = "mypkg"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


Do you confirm generation? (yes/no) [yes] y
root@7ef6c2970605:/# ls /tmp
tmp9f6c5ru4  tmpfxnqdptz
root@7ef6c2970605:/# ~/.local/bin/poetry add certifi
Creating virtualenv mypkg-il7asoJj-py3.8 in /root/.cache/pypoetry/virtualenvs
Using version ^2022.6.15 for certifi

Updating dependencies
Resolving dependencies... (0.3s)

Writing lock file

Package operations: 1 install, 0 updates, 0 removals

  • Installing certifi (2022.6.15)
root@7ef6c2970605:/# ls /tmp
tmp9f6c5ru4  tmpfxnqdptz  tmpti58ctxn
```

**Comment by dimbleby** [comment] 2022-09-06 18:55
These temporary files look like certificates.  I notice that there's one of them present in the image before you even do anything with it.

Then another is added by the act of installing poetry, and then more appear as packages are downloaded.

Not sure exactly what's happening but presumably this is the same as https://github.com/docker-library/python/issues/609 - which very likely puts it out of poetry's control.

**Comment by neersighted** [comment] 2022-09-06 19:43
I am going to close this for now as it looks like be interactions between certain versions of pip and Python... But if there is something concrete we can do about it from the Poetry end, please feel free to share it here/request we re-open this.

**Closed by neersighted** 2022-09-06 19:43 UTC
Labels: kind/bug, status/external-issue, version/1.2.0
