### ISSUE TITLE
CalledProcessError when adding git repositories

### ISSUE THREAD

**Issue by NeilGirdhar** [python-poetry/poetry#4194] opened 2021-06-22 00:35 UTC
For some reason, `poetry add git+https://github.com/deepmind/dm-haiku.git` now gives the error:
```
  Command '['git', '--git-dir', '/tmp/pypoetry-git-dm-haikufkv97ad7/.git', '--work-tree', '/tmp/pypoetry-git-dm-haikufkv97ad7', 'checkout', 'master']' returned non-zero exit status 1.
```

I discovered this because with my old dependency `dm-haiku = {git='https://github.com/deepmind/dm-haiku.git'}`, calling `poetry update` gives me:
```
Updating dependencies
Resolving dependencies... (0.8s)

  CalledProcessError

  Command '['git', '--git-dir', '/tmp/pypoetry-git-dm-haikurhz6cj20/.git', '--work-tree', '/tmp/pypoetry-git-dm-haikurhz6cj20', 'checkout', 'master']' returned non-zero exit status 1.

  at ~/.pyenv/versions/3.9.5/lib/python3.9/site-packages/poetry/utils/_compat.py:217 in run
      213│                 process.wait()
      214│                 raise
      215│             retcode = process.poll()
      216│             if check and retcode:
    → 217│                 raise CalledProcessError(
      218│                     retcode, process.args, output=stdout, stderr=stderr
      219│                 )
      220│         finally:
      221│             # None because our context manager __exit__ does not use them.
```

**Comment by finswimmer** [comment] 2021-06-23 18:51
Hello,

this is a duplicate of https://github.com/python-poetry/poetry/issues/3366

fin swimmer

**Closed by finswimmer** 2021-06-23 18:51 UTC
Labels: Bug, Triage
