### ISSUE TITLE
`poetry completions bash` generates invalid bash

### ISSUE THREAD

**Issue by paul-papacz** [python-poetry/poetry#6523] opened 2022-09-15 10:00 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 22.04
- **Poetry version**: 1.2.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: NOT RELEVANT

## Issue

After installing poetry via `curl -sSL https://install.python-poetry.org | python3 -` when running 

```none
$ poetry completions bash >> ~/.bash_completion
```
as mentioned in the [documentation](https://python-poetry.org/docs/#bash), and starting a new shell, the following error occurs:

```none
-bash: /home/username/.bash_completion: line 40: syntax error near unexpected token `clear'
-bash: /home/username/.bash_completion: line 40: `            (cache clear)'
```
Quicker way of reproducing:

```none
$ poetry completions bash | bash
bash: line 40: syntax error near unexpected token `clear'
bash: line 40: `            (cache clear)'
```

**Comment by Secrus** [comment] 2022-09-15 10:06
This is a duplicate of #4572. Fix was already applied upstream in Cleo, which handles generating completions, a new release of Cleo is coming soon. When Cleo is released, changes will be backported to the 1.2 branch and applied in the current master branch.

**Closed by Secrus** 2022-09-15 10:06 UTC
Labels: kind/bug, status/triage
