### ISSUE TITLE
Cannot install pyproject.toml packages as path dependencies

### ISSUE THREAD

**Issue by CLOVIS-AI** [python-poetry/poetry#5965] opened 2022-07-07 13:42 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: ArchLinux
- **Poetry version**: 1.1.13

## Issue

A Rust extension managed by [Maturin](https://github.com/PyO3/maturin) has a `pyproject.toml` file with `build-system.requires` properly set to compile and package the Rust code.

Installing such a package is as simple as `pip install <path-to-package>`.

When added as a path dependency in a Poetry project: `project = { path = "../project", develop = false }`, `poetry update` fails with:
`Directory /home/[REDACTED]/project does not seem to be a Python package`

`poetry/core/packages/directory_dependency.py:53` accepts dependencies that are either a Poetry `pyproject.toml`, or have a `setup.py` file. `pyproject.toml` is a standard Python packaging file, and Poetry should accept installing a non-Poetry project that uses this format.

**Comment by dimbleby** [comment] 2022-07-07 14:03
duplicate #5655, apparently fixed by https://github.com/python-poetry/poetry-core/pull/368

I've lost track of what's in the latest beta, you may need to wait for the next release to verify.

**Comment by finswimmer** [comment] 2022-07-08 04:20
Duplicate of #5655

**Closed by finswimmer** 2022-07-08 04:20 UTC
Labels: Bug, Triage

**Comment by CLOVIS-AI** [comment] 2022-07-09 10:55
Do you have an estimate of when that will be?

**Comment by Telofy** [comment] 2024-02-09 11:43
In case someone finds this searching for “does not seem to be a Python package”: The pyproject.toml of the dependency has to have a `build-system` section to be considered valid. E.g.:

```
[build-system]
requires = ["setuptools", "wheel"]
```

I'm guessing this is about to be fixed in the next release [through this commit](https://github.com/python-poetry/poetry-core/commit/fba71c11ce01100af82ed5b4ef73db2f2e35a2c0).
