### ISSUE TITLE
documentation hover menu sometimes bugs out

### ISSUE THREAD

**Issue by DetachHead** [python-poetry/poetry#4954] opened 2021-12-30 06:16 UTC
microsoft edge 96.0.1054.62
![asdf](https://user-images.githubusercontent.com/57028336/147726592-1a617f6a-99f1-486d-ba18-bb8a28ba185e.gif)

**Comment by finswimmer** [comment] 2022-07-29 11:14
The website has undergo several improvements since this was reported. I'm not able to reproduce this today. That's why I close it.

Feel free to leave a comment if you disagree.

fin swimmer

**Closed by finswimmer** 2022-07-29 11:14 UTC
Labels: Bug, Triage

**Comment by DetachHead** [comment] 2022-07-29 12:54
@finswimmer it's still happening for me. try moving your mouse real quickly on and off the documentation link, that seems to consistently reproduce the issue
