### ISSUE TITLE
`poetry lock [--regenerate]` unexpectedly uses a pre-release(/dev) version

### ISSUE THREAD

**Issue by bram-tv** [python-poetry/poetry#9759] opened 2024-10-12 13:13 UTC
### Description

When running `poetry lock` (or `poetry lock --regenerate`) poetry picks up a pre-release (in our cases a dev version) when this was not expected at all.

The case in which this happens also depends on the poetry version and in which order it processes the dependencies.
In our particular case it did not happen with poetry v1.5.1 but it did happen with poetry v1.6.0 and later versions. (Bisecting points to commit 36332d25a75ad157ca2d86ef6ffad5102d3bc84a for the change between v1.5.1 and v1.6.0)

With poetry versions (v1.6.1-v2.0.0.dev0.ca8917781) it happens when:
- package A exists and has the published versions: 2.0.0, 2.1.0, 2.2.0, 2.3.0
- package B exists and has:
  - v3.0.0 which depends on `A==2.0.0`
  - v3.0.1 which depends on `A==2.0.0`
  - v3.0.2.dev0 which depends on `A==^2.1.0`

When: pyproject contains:
```toml
[tool.poetry.dependencies]
package-b = "^3.0.0"
package-a = "^2.0.0"
```
Then: it is solved as:
- package-a = 2.3.0
- package-b = 3.0.2.dev0

When: pyproject contains:
```toml
[tool.poetry.dependencies]
package-b = "^3.0.1"
package-a = "^2.0.0"
```
Then: it is solved as:
- package-a = 2.0.0
- package-b = 3.0.1

In the case of `package-b = "^3.0.0"` what happens is that the solver:
- starts with `package-a = "^2.0.0"` 
  - it selects package-a == v2.3.0
    - it searches for a matching pacakge-b:
      - package-b v3.0.1 is not compatible
      - package-b v3.0.0 is not compatible
      - it then checks for pre-releases:
        - this finds v3.0.2.dev0 which is compatible and this is selected.

What we would have expected to happen:
- starts with `package-a = "^2.0.0"` 
  - it selects package-a == v2.3.0
    - it searches for a matching pacakge-b:
      - package-b v3.0.1 is not compatible
      - package-b v3.0.0 is not compatible
      - it then aborts and backtracks and picks a different version for package-a
  - it selects package-a == v2.2.0
    - (...)
  - (...)
  - it selects package-a == v2.0.0
    - it searches for a matching pacakge-b:
      - package-b v3.0.1 is compatible and selected

We would expect that it only ever considers the pre-releases if it fully ran out of options which is not yet the case in the above configuration since it can still backtrack and pick a different version for package-a.

### Unit-tests

Example unit tests:

<details>
  <summary>Code</summary>

```diff
diff --git a/tests/puzzle/test_solver.py b/tests/puzzle/test_solver.py
index 5c495579..ff74ffa9 100644
--- a/tests/puzzle/test_solver.py
+++ b/tests/puzzle/test_solver.py
@@ -4804,3 +4804,91 @@ def test_solver_resolves_duplicate_dependencies_with_restricted_extras(
             ]
         ),
     )
+
+
+@pytest.mark.parametrize("package_b_dependency", ["^3.0.0", "^3.0.1"])
+def test_solver_ignore_prerelease(
+    solver: Solver,
+    repo: Repository,
+    package: ProjectPackage,
+    package_b_dependency: str,
+) -> None:
+    package.add_dependency(Factory.create_dependency("A", "^2.0.0"))
+    package.add_dependency(Factory.create_dependency("B", package_b_dependency))
+
+    package_a0 = get_package("A", "2.0.0")
+    package_a1 = get_package("A", "2.1.0")
+    package_a2 = get_package("A", "2.2.0")
+    package_a3 = get_package("A", "2.3.0")
+
+    repo.add_package(package_a0)
+    repo.add_package(package_a1)
+    repo.add_package(package_a2)
+    repo.add_package(package_a3)
+
+    package_b0 = get_package("B", "3.0.0")
+    package_b0.add_dependency(get_dependency("A", "2.0.0"))
+    repo.add_package(package_b0)
+
+    package_b1 = get_package("B", "3.0.1")
+    package_b1.add_dependency(get_dependency("A", "2.0.0"))
+    repo.add_package(package_b1)
+
+    package_b2 = get_package("B", "3.0.2.dev0+aabbccdd")
+    package_b2.add_dependency(get_dependency("A", "^2.1.0"))
+    repo.add_package(package_b2)
+
+    transaction = solver.solve()
+    check_solver_result(
+        transaction,
+        (
+            [
+                {"job": "install", "package": package_a0},
+                {"job": "install", "package": package_b1},
+            ]
+        ),
+    )
+
+
+@pytest.mark.parametrize("package_d_dependency", ["^3.0.0", "^3.0.1", "^3.0.2"])
+def test_solver_ignore_prerelease_2(
+    solver: Solver,
+    repo: Repository,
+    package: ProjectPackage,
+    package_d_dependency: str,
+) -> None:
+    package.add_dependency(Factory.create_dependency("C", "^2.0.0"))
+    package.add_dependency(Factory.create_dependency("D", package_d_dependency))
+
+    package_c0 = get_package("C", "2.0.0")
+    package_c3 = get_package("C", "2.3.0")
+
+    repo.add_package(package_c0)
+    repo.add_package(package_c3)
+
+    package_d0 = get_package("D", "3.0.0")
+    package_d0.add_dependency(get_dependency("C", "2.0.0"))
+    repo.add_package(package_d0)
+
+    package_d1 = get_package("D", "3.0.1")
+    package_d1.add_dependency(get_dependency("C", "2.0.0"))
+    repo.add_package(package_d1)
+
+    package_d2 = get_package("D", "3.0.2")
+    package_d2.add_dependency(get_dependency("C", "2.0.0"))
+    repo.add_package(package_d2)
+
+    package_d3 = get_package("D", "3.0.3.dev0+aabbccdd")
+    package_d3.add_dependency(get_dependency("C", "^2.1.0"))
+    repo.add_package(package_d3)
+
+    transaction = solver.solve()
+    check_solver_result(
+        transaction,
+        (
+            [
+                {"job": "install", "package": package_c0},
+                {"job": "install", "package": package_d2},
+            ]
+        ),
+    )
```

</details>

In the unit tests:
- (case 1): test_solver_ignore_prerelease: works on v1.5.1, fails since v1.6.0
- (case 2): test_solver_ignore_prerelease_2: fails on v1.5.1, works since v1.6.0

### Related

- #8194 **might** be related issue
- Checking of pre-releases
  - #7978 
  - commit fd70f7e100c204ea2a99600c0d4a372735393c20  (included since v1.6.0)
  - commit 7ac6f374d7e56d74e8660fa50fe00ff69e022535 (backported and included in v1.5.1)
- Inverting depedency solving order:
  - #8256 
  - commit 36332d25a75ad157ca2d86ef6ffad5102d3bc84a (included since v1.6.0)

### Workarounds

For direct dependencies: pin a particular version
For non-direct dependencies: add the package that causes the pre-release/dev version to be used as direct dependency and pin its version.

### Poetry Version

Poetry (version 1.5.1) .. Poetry (version 2.0.0.dev0 -- commit ca8917781)

##### poerty v1.5.1: solver starts with package-b

```
Updating dependencies
Resolving dependencies...
   1: fact: example is 0.0.0
   1: derived: example
   1: fact: example depends on package-b (^3.0.0)
   1: fact: example depends on package-a (^2.0.0)
   1: selecting example (0.0.0)
   1: derived: package-a (>=2.0.0,<3.0.0)
   1: derived: package-b (>=3.0.0,<4.0.0)
   1: fact: package-b (3.0.1) depends on package-a (2.0.0)
   1: selecting package-b (3.0.1)
   1: derived: package-a (==2.0.0)
   1: selecting package-a (2.0.0)
   1: Version solving took 0.833 seconds.
   1: Tried 1 solutions.
```

##### poerty v1.6.0 (but same with v2.0.0.dev0):  solver starts with package-a

```
Updating dependencies
Resolving dependencies...
   1: fact: example is 0.0.0
   1: derived: example
   1: fact: example depends on package-b (^3.0.0)
   1: fact: example depends on package-a (^2.0.0)
   1: selecting example (0.0.0)
   1: derived: package-a (>=2.0.0,<3.0.0)
   1: derived: package-b (>=3.0.0,<4.0.0)
   1: selecting package-a (2.3.0)
   1: fact: package-b (3.0.1) depends on package-a (2.0.0)
   1: derived: not package-b (==3.0.1)
   1: fact: package-b (3.0.0) depends on package-a (2.0.0)
   1: derived: not package-b (==3.0.0)
   1: fact: package-b (3.0.2.dev0+aabbccdd) depends on package-a (>=2.1.0,<3.0.0)
   1: selecting package-b (3.0.2.dev0+aabbccdd)
   1: Version solving took 0.772 seconds.
   1: Tried 1 solutions.
```

##### poerty v1.5.1:  solver starts with package-c

```
Updating dependencies
Resolving dependencies...
   1: fact: example is 0.0.0
   1: derived: example
   1: fact: example depends on package-d (^3.0.0)
   1: fact: example depends on package-c (^2.0.0)
   1: selecting example (0.0.0)
   1: derived: package-c (>=2.0.0,<3.0.0)
   1: derived: package-d (>=3.0.0,<4.0.0)
   1: selecting package-c (2.3.0)
   1: fact: package-d (3.0.2) depends on package-c (2.0.0)
   1: derived: not package-d (==3.0.2)
   1: fact: package-d (3.0.1) depends on package-c (2.0.0)
   1: derived: not package-d (==3.0.1)
   1: fact: package-d (3.0.0) depends on package-c (2.0.0)
   1: derived: not package-d (==3.0.0)
   1: fact: package-d (3.0.3.dev0+aabbccdd) depends on package-c (>=2.1.0,<3.0.0)
   1: selecting package-d (3.0.3.dev0+aabbccdd)
```

##### poerty v1.6.0 (but same with v2.0.0.dev0):  solver starts with package-d

```
Updating dependencies
Resolving dependencies...
   1: fact: example is 0.0.0
   1: derived: example
   1: fact: example depends on package-d (^3.0.0)
   1: fact: example depends on package-c (^2.0.0)
   1: selecting example (0.0.0)
   1: derived: package-c (>=2.0.0,<3.0.0)
   1: derived: package-d (>=3.0.0,<4.0.0)
   1: fact: package-d (3.0.2) depends on package-c (2.0.0)
   1: selecting package-d (3.0.2)
   1: derived: package-c (==2.0.0)
   1: selecting package-c (2.0.0)
   1: Version solving took 0.660 seconds.
   1: Tried 1 solutions.
```

**Comment by dimbleby** [comment] 2024-10-12 15:14
Seems like a straight duplicate of #8194

**Closed as not planned** 2024-10-12 15:30 UTC
Labels: kind/bug, status/duplicate
