### ISSUE TITLE
How do I uninstall packages that have been removed from pyproject.toml?

### ISSUE THREAD

**Issue by rectalogic** [python-poetry/poetry#648] opened 2018-11-19 21:12 UTC
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Question

pipenv has `pipenv clean` which removes all packages that are no longer in Pipfile.lock from the virtualenv. What is the equivalent with poetry? The docs say there is no need for `pipenv sync` and `pipenv clean` due to the `remove` command https://github.com/sdispater/poetry#remove-command

But how does this work? I would need to run `poetry remove XXX` against all my virtualenvs - manually keeping track of all packages that have been removed and remembering to remove them myself?

Is there not any way to sync my poetry.lock to my virtualenv to ensure the virtualenv only has the packages specified in poetry.lock installed?

I have a virtualenv on each box I deploy to, and keep pyproject.toml and poetry.lock under source code control. I then want a way to ensure each of those virtualenvs only has the packages in poetry.lock installed.

**Comment by sdispater** [comment] 2018-11-19 21:14
I am not sure I understand. Why would your packages no longer be in `poetry.lock` but still in your virtualenv?

**Comment by rectalogic** [comment] 2018-11-19 21:15
Actually I just realized `poetry remove` won't even work.

Here I remove a package from en1 and then switch to env2 and attempt to remove it from there and it fails

```
(env1) ➜  poetrytest /Users/aw/Library/Python/2.7/bin/poetry remove boto3
Updating dependencies
Resolving dependencies... (0.1s)


Package operations: 0 installs, 0 updates, 9 removals

Writing lock file

  - Removing boto3 (1.9.47)
  - Removing botocore (1.12.47)
  - Removing docutils (0.14)
  - Removing futures (3.2.0)
  - Removing jmespath (0.9.3)
  - Removing python-dateutil (2.7.5)
  - Removing s3transfer (0.1.13)
  - Removing six (1.11.0)
  - Removing urllib3 (1.22)
(env1) ➜  poetrytest source env2/bin/activate
(env2) ➜  poetrytest /Users/aw/Library/Python/2.7/bin/poetry install
Installing dependencies from lock file

Nothing to install or update

(env2) ➜  poetrytest /Users/aw/Library/Python/2.7/bin/poetry remove boto3

[ValueError]
Package boto3 not found

remove [-D|--dev] [--dry-run] [--] <packages> (<packages>)...
```

**Comment by sdispater** [comment] 2018-11-19 21:15
Oh. I think I understand. You update the lock locally and then deploy. Is that right?

**Comment by rectalogic** [comment] 2018-11-19 21:16
> I am not sure I understand. Why would your packages no longer be in `poetry.lock` but still in your virtualenv?

Because I have many virtualenvs - one per EC2 instance. So I copy over my poetry.lock and want to sync each virtualenv using that poetry.lock, adding/upgrading/removing packages as needed to keep the virtualenv in sync (similar to how `pipenv sync && pipenv clean` would work.

**Comment by rickhutcheson** [comment] 2019-02-06 19:12
We have this problem using Poetry as well. One developer `poetry remove`s and deploys the new `poetry.lock`/`pyproject.toml`. The other devs pull the changes, but poetry install does not remove the old packages. Are there any plans to support this workflow?

**Comment by kevinkjt2000** [comment] 2019-03-04 15:15
The README mentions `clean` and `sync`, but these are not commands on version `0.12.11`.  I am also curious to know what steps to take to ensure that my local virtualenv matches `poetry.lock`.

**Comment by jobec** [comment] 2019-04-03 11:29
Same here.
would be great if packages not in poetry.lock were removed. Now there is a chance of such packages piling up and unexpectedly influencing your application (some packages look in specific locations for plugins and such).

Recreating a virtual environment each and every time is time consuming and unless it can happen automatically when checking out a branch, developers aren't going to do it.

**Comment by seansfkelley** [comment] 2019-04-13 01:14
Another use-case for this is CI build caching. If you remove dependency in a branch and the CI build for that branch pulls from a cache that still has that dependency, I definitely want it removed.

This is how Yarn works which is important because then `yarn install` means "make my build reproducible" rather than "make sure I have all the dependencies I need", which is not the same thing.

This ticket is in conflict with https://github.com/sdispater/poetry/issues/533 (though AFAICT Poetry indeed does not uninstall dependencies, so not sure what that ticket's about).

**Comment by jobec** [comment] 2019-04-13 15:59
It looks like if this line would loop over the installed packages, that it would result in obsolete packages to be cleaned up.

https://github.com/sdispater/poetry/blob/f2e2ed470ca1560111226b5f6f8f9dc4a28d319a/poetry/puzzle/solver.py#L96

I'm trying see what it does if I changed it, but I can't seem to get poetry running from it's own git repo inside PyCharm's debugger 🤔

**Comment by seansfkelley** [comment] 2019-04-13 16:50
@kevinkjt2000 AFAICT the only references to `clean` and `sync` in the README are talking about Pipenv commands, not Poetry. Also, `poetry debug:info` (0.12.x) will print out the virtualenv without you having to do weird things to find it.

**Comment by jobec** [comment] 2019-04-13 18:22
I did an attempts in pull request #1037 to remove obsolete packages when running `poetry install`.
Still a work in progress, but it looks like it's cleaning up obsolete packages (e.g. installed, but not in the list of resolved packages)

**Comment by pmav99** [comment] 2019-04-13 19:43
@jobec a couple of comments if you don't mind:
a) It is not clear to me if removing packages is a good default for poetry install
b) I am not a native speaker, but the term "obsolete" seems to be slightly misused in this context. Not sure what to propose though. Maybe "unspecified" packages?
c) This is a breaking change. Among other things, it would be making it impossible to implement something [like this](https://github.com/sdispater/poetry/issues/951#issuecomment-475156710). IMHV, removing packages should be either a separate subcommand or at the very least a `poetry install` flag.

**Comment by jobec** [comment] 2019-04-13 20:13
First of all, the PR is just a beginning. It's no where near finished nor fine tuned. And I'm open for all feedback.

* A) True, although I think people expect it to behave like that. I know I did. "Freezing dependencies" as in "THIS is how it should be". Anyway, I agree that changing current behavior might be a bridge to far.

* B) I'm also not a native speaker, but obsolete is the first thing that crossed my mind. I guess there are better synonyms: unknown, unlocked, unused, unspecified, rogue...

* C) The comment you point at is indeed a useful use-case. Combined with A) it might be a good reason *not* to make this behavior the default. Anyway, I think it's best to put it as a flag to `poetry install`. What about `--clean`. Matching with `git clean`

**Comment by seansfkelley** [comment] 2019-04-13 20:29
a) I assert that it is a good default, though that depends on if (per my [earlier comment](https://github.com/sdispater/poetry/issues/648#issuecomment-482763789)) you view "install" to mean "make my build reproducible" (as I do) rather than "make sure I have all the dependencies I need" (which is a good start, but incomplete).

Regarding point (c). From the [linked comment](https://github.com/sdispater/poetry/issues/951#issuecomment-475156710):

> You might still install a package with confliciting dependencies though. Perhaps it would make sense to have a special mode of poetry add that will resolve dependencies and install a package without adding it to pyproject.toml.

The semantics of this use case seem weird and difficult. If the "temporary" package has overlapping dependencies with non-temporary packages, what happens? Does it change the versions of the common dependencies? If so, does it update the lock file? Does it instead just fail outright? 

The OP on that issue says:

> Then there are tools that I use personnally to develop, but are not required to run tests. Examples are ipython, icecream, pdb++. Those are more personal preferencies that real requirements.

In node, the accepted solution for this use-case is either (1) install it globally since it's not relevant to the project at hand or (2) install it as part of the project because you use it to develop the project (and hence it is a dev dependency). It seems to me that trying to support a third, middle road is likely to cause more confusion than help.

**Comment by pmav99** [comment] 2019-04-13 21:04
@seansfkelley @jobec I, at the very least, hope that we can all agree that:
- "make my build reproducible"
- "make sure I have all the dependencies I need"

are both valid and discrete usecases :)

WRT to which one should be the default, I honestly don't have a strong opinion. I tend to prefer the latter option as the default one since it is more common for development + *it is* the current behaviour. Adding an extra flag and/or using an explicit subcommand on deployment scripts seems more natural.

@seansfkelley I transferred the discussion for installing packages without adding them to `pyproject.toml`  [here](https://github.com/sdispater/poetry/issues/951#issuecomment-482886431)

**Comment by pmav99** [comment] 2019-04-13 21:18
> I guess there are better synonyms: unknown, unlocked, unused, unspecified, rogue...
"orphan" is an option too

**Comment by drunkwcodes** [comment] 2019-04-13 22:12
`poetry autoremove`.

`clean` has different meaning in other package managers, which clear up cache packages not been installed yet.

**Comment by seansfkelley** [comment] 2019-04-14 17:40
`poetry autoremove` assumes you want a different command for this. What's the use-case for a separate command instead of changing the behavior of `install`? Would it make sense to use `autoremove` at any other time except immediately after `install`?

**Comment by jobec** [comment] 2019-04-14 18:21
I'd say: `poetry install --keep-untracked`

With a (new) default of removing untracked packages (e.g. not in poetry.lock), as I think the larger percentage of users expect it to work as such.

From the main website:

> Develop
> Poetry comes with all the tools you might need to manage your projects in **a deterministic way**. 

> Track
> Having an **insight of your project's dependencies** is just one command way.

**Comment by seansfkelley** [comment] 2019-04-14 18:31
Nice citation of the website! :) I also think "untracked" is a good word to describe these dependencies.

**Comment by pmav99** [comment] 2019-04-14 20:23
+1 for untracked.

Apart from that, I completely agree that having a way to have a "purged" virtualenv is really important. That being said though, I also think that not purging the virtualenv while developing can also be useful. 

The reason I don't really like changing the defaults is that I prefer adding a flag on a deployment script rather than having to add a cli flag when using poetry interactively (i.e. while developing)

**Comment by drunkwcodes** [comment] 2019-04-14 21:21
Why? What we are talking about is removing packages, not installing.
You will not install any untracked packages anyway.

**Comment by pmav99** [comment] 2019-04-14 21:27
@drunkwcodes this discussion is related to #951

**Comment by drunkwcodes** [comment] 2019-04-14 21:35
I won't look at that for a while...

There are many ways to install untracked packages, not just with `poetry install --strange-option`.
Having a `poetry autoremove` command to remove universally untracked packages is a proper thing to do.

**Comment by seansfkelley** [comment] 2019-04-14 22:39
> Having a `poetry autoremove` command to remove universally untracked packages is a proper thing to do.

Well, this is the point under discussion. I think there is value in increasing the scope of `install` to handle this case as well (though I disagree with @pmav99 over whether it's a flag or not), specifically, because then install can become a one-stop shop to put your dependencies in the right state without having to juggle multiple commands. One extra command wouldn't be a huge burden for those of us having this discussion here, but keeping this behavior localized to `install` instead means that (1) it's more discoverable, (2) it's more correct by default and (3) Poetry doesn't bloat.

That said, in writing this comment I did discover a couple of interesting related commands in other tools:

- [`npm ci`](https://docs.npmjs.com/cli/ci.html) is a variant of `npm install` specifically designed to be stricter for a CI environment, noting that it "...can help catch errors or inconsistencies caused by the incrementally-installed local environments of most npm users."
- [`yarn prune`](https://yarnpkg.com/en/docs/cli/prune) and [`yarn dedupe`](https://yarnpkg.com/en/docs/cli/dedupe) are specifically called out as not necessary due to the behavior of `yarn install`.
- [`yarn check --verify-tree`](https://yarnpkg.com/en/docs/cli/check) is designed to check what's on disk against what's in the lock file. (Though it should be noted that as a heavy Yarn user for years, I never knew this command existed until now because `yarn install` is already so dependably predictable.)
- [`cargo fetch`](https://doc.rust-lang.org/cargo/commands/cargo-fetch.html) is designed exclusively to populate Cargo's dependency cache, which is the closest it has to `poetry install` because Cargo prefers to think about `run` and `build`, which _as a prerequisite_  ensure that your dependencies are in the right state. (So, Cargo thinks about this whole problem slightly differently than Poetry or npm/Yarn in that it doesn't generally think about a separate dependency-installation command; `fetch` is described as a convenience if you're going off-network.)

My preferred style here is Yarn's, which has to tolerate users installing extra stuff (like npm) but by default tries to assert total control over `node_modules`. It should be noted that the analogy isn't perfect due to the way node handles conflicting versions (via duplication), which allows it to sidestep some complexity that Poetry has to handle.

**Comment by drunkwcodes** [comment] 2019-04-14 22:52
It's absolutly doable.
What we need is to figure out all kinds of installations which can be with poetry projects at the same time.

And doing it professionally and better than a brutal virtualenv restart is the only concern.

**Comment by jacebrowning** [comment] 2019-04-14 23:03
@drunkwcodes In my opinion, this comment does not add anything of value to this discussion. Please refrain from providing your commentary unless it has not already been presented in the various open issues on this project.

**Comment by jobec** [comment] 2019-04-15 17:08
Who actually has the final say in this?
@sdispater ?

**Comment by pmav99** [comment] 2019-04-15 17:20
@seansfkelley thank you for the thorough comparison)

> (2) it's more correct by default 

Care to elaborate? It kind of feels like "correctness" in this context is rather subjective than objective.

**Comment by seansfkelley** [comment] 2019-04-15 17:57
Point (2) above was referring only to the comparison of having the behavior in `install` versus a new command, not about whether `install` should be remove-by-default or keep-by-default. With that in mind, what I meant by "more correct by default" is that baking this behavior into `install` means that the default action (`poetry install`) will be opinionated about what it means to be correct and which mode is preferred, rather than having a pair of related commands and letting you figure it out. Poetry is an opinionated tool, and I think that should extend to this as well.

Note also I said "_more_ correct", because as we have determined we don't agree about which should be the default but I think we agree that it would be preferable to keep it in `install`, whatever it is...?

**Comment by kylebebak** [comment] 2019-10-03 23:24
Running `poetry remove pkg` fails, if `pkg` is in `poetry.lock` but not in `pyproject.toml`.

This is really surprising behavior, given that `poetry update pkg` works just fine.

`poetry remove pkg` should remove `pkg` from `poetry.lock`, even if it's not in `pyproject.toml` -- after all, this is exactly how `poetry update pkg` works.


```
➜  cloud-django git:(328/branch) ✗ poetry remove django-stubs

[ValueError]
Package django-stubs not found
```

-----

```
➜  cloud-django git:(328/branch) ✗ poetry update django-stubs
Updating dependencies
Resolving dependencies... (0.5s)

Writing lock file


Package operations: 0 installs, 0 updates, 2 removals

  - Removing dataclasses (0.6)
  - Removing django-stubs (0.12.0)
➜  cloud-django git:(328/inspection_event_publishing) ✗
```


Or with an image:

![Screen Shot 2019-10-03 at 6 19 38 PM](https://user-images.githubusercontent.com/1524088/66170701-e5255000-e60a-11e9-8ccf-bffcc7086b60.png)

**Comment by Trim21** [comment] 2019-10-19 18:32
Maybe add a command `poetry ci` like `npm ci`🤔. 
Not charging default behavior and don't need to run command like `auto remove/clean` after `install`.

(And much shorter than `poetry install`

**Comment by ayroblu** [comment] 2020-03-04 17:26
Just wondering if this is moving anywhere? It looks like there was a good proposal:
`poetry install --keep-untracked`
Not sure if just not enough resources to action this?

To clarify the use case if it's not obvious, if you collaborate with anyone, including CI or have multiple machines, you probably add and remove dependencies organically, it makes no sense to keep removed ones around, especially if they interact with other tools

**Comment by jobec** [comment] 2020-03-04 17:41
I had a PR partially implementing this. But is has been closed in the meanwhile.

Also, without a go or direction from a maintainer, there's not much fun in working on it of it won't be merged.

**Comment by finswimmer** [comment] 2020-03-04 17:54
Hello @jobec,

I guess I closed your PR as this has the status WIP for a very long time and you didn't react on the stale bot message. So I thought you didn't work anymore on it.

I found this feature very useful and appreciate your contribution. So please go on! :+1: 

fin swimmer

**Comment by jobec** [comment] 2020-03-04 18:02
Still the question remains:

Maintainers, what direction to go in? Remove obsolete/stale/untracked/... packages by default, or keep them.

**Comment by finswimmer** [comment] 2020-03-04 18:51
At the end @sdispater has to decide, because it's a new feature.

I support the version to remove untracked packages by default and have the `--keep-untracked` parameter for those who really need it (I read some of the arguments why people would do this, but still doesn't understand why ...).

**Comment by PetterS** [comment] 2020-03-11 08:20
This is very important and I don't know of any way to do this.

Say several developers work on a project. One performs an update which removes a package from the pyproject and lock files. How will the other developers ever remove this package?

Pipenv, for all of its flaws, at least has `pipenv clean`.

**Comment by PetterS** [comment] 2020-03-17 13:37
@sdispater did you have any input on finswimmers suggestion of `--keep-untracked` above? I am happy to finish my PR if this is what we want. Having a way of cleaning out unused dependencies is crucial to us.

**Comment by sdispater** [comment] 2020-03-18 09:27
Unfortunately, we can't make this the default behavior since it's a breaking change in my opinion. 

We should add an option that requires opt-in like `--remove-untracked`.

**Comment by PetterS** [comment] 2020-03-18 09:56
Sure! I'll modify my PR, then?

We could add a configuration file that sets the default behavior, no problem.

**Comment by PetterS** [comment] 2020-03-20 10:18
@sdispater @finswimmer 
Please let me know if there is anything I should do with my PR at this point.

**Comment by stephsamson** [comment] 2020-05-01 17:07
#2172 fixes this issue and should be available in the next release.

**Closed by stephsamson** 2020-05-01 17:07 UTC
Labels: Feature

**Comment by earshinov** [comment] 2020-05-24 21:22
@stephsamson , is there any date for the next release? We are waiting for this feature.

**Comment by dash-samuel** [comment] 2020-09-22 12:19
> Running `poetry remove pkg` fails, if `pkg` is in `poetry.lock` but not in `pyproject.toml`.
> 
> This is really surprising behavior, given that `poetry update pkg` works just fine.
> 
> `poetry remove pkg` should remove `pkg` from `poetry.lock`, even if it's not in `pyproject.toml` -- after all, this is exactly how `poetry update pkg` works.
> 
> ```
> ➜  cloud-django git:(328/branch) ✗ poetry remove django-stubs
> 
> [ValueError]
> Package django-stubs not found
> ```
> 
> ```
> ➜  cloud-django git:(328/branch) ✗ poetry update django-stubs
> Updating dependencies
> Resolving dependencies... (0.5s)
> 
> Writing lock file
> 
> 
> Package operations: 0 installs, 0 updates, 2 removals
> 
>   - Removing dataclasses (0.6)
>   - Removing django-stubs (0.12.0)
> ➜  cloud-django git:(328/inspection_event_publishing) ✗
> ```
> 
> Or with an image:
> 
> ![Screen Shot 2019-10-03 at 6 19 38 PM](https://user-images.githubusercontent.com/1524088/66170701-e5255000-e60a-11e9-8ccf-bffcc7086b60.png)

I am running into the exact same problem.

**Comment by Aiky30** [comment] 2023-03-09 16:52
Is this closed without a solution? Seems a little overkill to have to destroy my venv to bring my venv back in check with a projects packages. Teams do remove packages ....

**Comment by trim21** [comment] 2023-03-09 16:53
> Is this closed without a solution? Seems a little overkill to have to destroy my venv to bring my venv back in check with a projects packages. Teams do remove packages ....

In newer poetry you can run `poetry install --sync` and it will keep env synced with pyproject.toml

**Comment by Aiky30** [comment] 2023-03-09 16:55
Awesome thanks @trim21 , I didn't see this option in `poetry list`. Should help anyone falling into this thread in the future.
