### ISSUE TITLE
Modules not found when running python scripts in shell context after package installation

### ISSUE THREAD

**Issue by Residu** [python-poetry/poetry#4100] opened 2021-05-25 07:11 UTC
Hi everyone, i'm facing an issue with my Poetry environment.

- [x]  I am on the latest Poetry version.
- [x]  I have searched the issues of this repo and believe that this is not a duplicate.
- [x]  If an exception occurs when executing a command, I executed it again in debug mode (-vvv option).

I installed Poetry according to the recommended instructions.
My machine is running macOS BigSur 11.3.1 and Python 3.8 .

My problem is the following: i cloned a repo which delivers a toml file. In the repo folder, i run a `poetry shell` command, the prompt indicates that no virtual env exists, it automatically create a new one. 
Then i run the `poetry install` command, everything is ok. I check if my dependencies are currently installed using `poetry show <my-package>`, seems good.
Then `python` `import 'django'` returns `No module named 'django'`.

I checked multiple times, i am running python in my virtualenv, packages look to be installed.
Using pip instead of poetry install works.

**Comment by finswimmer** [comment] 2021-06-23 19:07
Hello @Residu,

could you show which commands you execute in which order and what the output of the commands are? Unfortunately I'm not able to reproduce your issue.

fin swimmer

**Comment by finswimmer** [comment] 2021-12-17 08:04
I'm closing this because we haven't receive nor more information for a long time now.

**Closed by finswimmer** 2021-12-17 08:04 UTC
Labels: Awaiting Reponse
