### ISSUE TITLE
Poetry add private github repository with ssh using --group flag

### ISSUE THREAD

**Issue by vinicius-oa** [python-poetry/poetry#8365] opened 2023-08-24 20:38 UTC
- **Poetry version**: 1.5.1
- **Python version**: 3.11.4
- **OS version and name**: Linux Xubuntu 22.04
- **pyproject.toml**: 

- [ ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

It seems that poetry is unable to specify a group for some github repository installation. I've tried:

`poetry add --group=github git+ssh://git@github.com/repo/repo.git`

Poetry has installed it correctly, but it didn't create the group `github` in pyproject.toml

[Edit - 27/08/23]
I've tested with the latest poetry's version (1.6.1), still not working.

**Comment by dimbleby** [comment] 2023-08-24 21:20
works fine for me, cannot reproduce

you've checked the box declaring that you're using the latest stable poetry, but you've also said poetry 1.5.1.  Which is it?

**Comment by dimbleby** [comment] 2023-08-24 22:20
well this works fine at both versions so it doesn't really matter.

not sure what you've done wrong: but try again, then close this out.  Thanks!

**Comment by vinicius-oa** [comment] 2023-08-24 22:22
> well this works fine at both versions so it doesn't really matter.
> 
> not sure what you've done wrong: but try again, then close this out. Thanks!

Thanks, could you try once again but: `git+ssh://git@github.com/repo/repo.git#someotherbranch`

**Comment by dimbleby** [comment] 2023-08-24 22:26
this is a nonsensical way of debugging a non-existent problem.

please do your own testing!

**Comment by abn** [comment] 2024-02-29 16:13
Closing as it looks like this is a non-issue on 1.81. If this is in fact still an issue, please raise a new issue with clearer details and a reproducer for the latest Poetry version.

**Closed by abn** 2024-02-29 16:13 UTC
Labels: kind/bug, status/triage
