### ISSUE TITLE
Case sensitivity of project names when publishing to PyPI

### ISSUE THREAD

**Issue by robertmartin8** [python-poetry/poetry#1202] opened 2019-06-29 05:46 UTC
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

- **Poetry version**:  0.12.16

## Issue

I'm trying to migrate my project from `setup.py` etc to `poetry`, and it has mostly been very straightforward. 

My (very minor) issue is that the `name` field does not appear to preserve its case when publishing. 

```
[tool.poetry]
name = "PyPortfolioOpt"
version = "0.3.2"
...
```

Becomes:

![pyp](https://user-images.githubusercontent.com/11792905/60380205-16263f80-9a74-11e9-8e2e-d0dbfece805f.png)

With `setup.py`, the case sensitivity is preserved on PyPI.

I know that there is no real difference which is why this is a minor issue, but stylistically it's a tiny thing that I prefer about `setup.py`.

**Comment by justinmayer** [comment] 2019-11-13 13:52
@robertmartin8: Could you try using the latest Poetry 1.0 beta (e.g., by passing `--preview` to the `get-poetry.py` install script) and confirm that the issue you reported persists?

**Comment by robertmartin8** [comment] 2019-12-12 11:45
@justinmayer 

I just pushed an update to my package. As far as I can see, **the issue still persists**.

```
> poetry --version
Poetry version 1.0.0b9
```

```
> poetry build

Building PyPortfolioOpt (0.5.0)
 - Building sdist
 - Built PyPortfolioOpt-0.5.0.tar.gz

 - Building wheel
 - Built PyPortfolioOpt-0.5.0-py3-none-any.whl
```

```
> poetry publish

Publishing PyPortfolioOpt (0.5.0) to PyPI
Username: ***********
Password: 
 - Uploading PyPortfolioOpt-0.5.0-py3-none-any.whl 100%
 - Uploading PyPortfolioOpt-0.5.0.tar.gz 100%
```

![Screenshot 2019-12-12 at 11 44 10](https://user-images.githubusercontent.com/11792905/70709480-dfb44800-1cd4-11ea-9427-ffae93632fc9.png)

**Comment by justinmayer** [comment] 2019-12-14 18:43
Poetry v1.0.0 was just released, so I'd try again with that version. I imagine the issue is unresolved, but it'd be better to know that for certain.

**Comment by robertmartin8** [comment] 2019-12-19 04:37
@justinmayer I've just tried with v1.0.0 – it's still unresolved.

**Comment by neersighted** [comment] 2022-10-05 16:22
@dimbleby will python-poetry/poetry-core#484 affect this?

**Comment by dimbleby** [comment] 2022-10-05 16:35
No, as I said there, that MR leaves poetry continuing to normalize project names at upload.

Unless and until pypa decide what the standards should actually be, and pypi do something about https://github.com/pypi/warehouse/issues/10030, it will remain impossible to do both of (i) publish with a pretty project name and (ii) normalize sdist and wheel names.

https://github.com/python-poetry/poetry-core/pull/484 continues in the direction of favouring normalization.

**Comment by neersighted** [comment] 2022-10-05 16:49
Ah, makes sense -- we're trading capitalized names versus not being able to upload an entire category of otherwise valid package. Given the acceptance of [PEP 625](https://peps.python.org/pep-0625/) and our move to canonicalize names, I'm going to close this as wontfix. It could eventually be addressed by amendments to the PEPs/changes in PyPI widening the list of acceptable names.

**Closed by neersighted** 2022-10-05 16:49 UTC
Labels: area/publishing

**Comment by dimbleby** [comment] 2022-10-05 16:50
yeah - again reiterating what I said in the other one - if and when that pypi issue is fixed, it's trivial for poetry to start publishing with pretty names.  But we shouldn't do that while it doesn't work!
