### ISSUE TITLE
Poetry 1.2.0a2 - discrepancy in lockfile generation (compared to 1.1.x)

### ISSUE THREAD

**Issue by orlevii** [python-poetry/poetry#4384] opened 2021-08-14 18:26 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOS BigSur 11.4
- **Poetry version**: 1.2.0a2

## Issue

For some reason poetry 1.2.0a2 is generating a different lockfile then 1.1.x:
Let's take for for example this `pyproject.toml`:
```toml
[tool.poetry]
name = "setuptools_bug"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "~3.7.1"
google-cloud-core = "^1.7.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```
When using poetry 1.1.x - the lockfile looks fine.
But when using poetry 1.2.0a2 - for some reason "setuptools" is added as a dependency.

Also, the content hash comes out different:
<img width="1169" alt="image" src="https://user-images.githubusercontent.com/13447456/129456811-430c40bb-fb82-4370-aa31-30e2e190e1fd.png">

Added the 2 lockfiles here:
**1.1.7:**
https://gist.github.com/orlevii/b56528719277c54492b44515b2efa22c#file-1-1-7-lockfile

**1.2.0a2:**
https://gist.github.com/orlevii/b56528719277c54492b44515b2efa22c#file-1-2-0a2-lockfile

**Comment by orlevii** [comment] 2021-08-16 19:27
I've looked deeply at the changes and I think this change is related:
https://github.com/python-poetry/poetry/pull/2826/files#diff-4b39a635ef4f2ecc56c75890e6c1c22ec80d3db3385974d7937b295cad7eded1R57

**Comment by martinxsliu** [comment] 2021-08-23 16:56
Related: https://github.com/python-poetry/poetry/issues/4242

**Comment by apollo13** [comment] 2021-08-30 20:02
Hi @orlevii, this is not a bug. `google-api-core` which your `google-cloud-core` depends on has a direct dependency on `setuptools`:
```
google-cloud-core 1.7.2 Google Cloud API client core library
├── google-api-core >=1.21.0,<2.0.0dev
│   ├── google-auth >=1.25.0,<2.0dev 
│   │   ├── cachetools >=2.0.0,<5.0 
│   │   ├── pyasn1-modules >=0.2.1 
│   │   │   └── pyasn1 >=0.4.6,<0.5.0 
│   │   ├── rsa >=3.1.4,<5 
│   │   │   └── pyasn1 >=0.1.3 (circular dependency aborted here)
│   │   ├── setuptools >=40.3.0 
│   │   └── six >=1.9.0 
│   ├── googleapis-common-protos >=1.6.0,<2.0dev 
│   │   └── protobuf >=3.12.0 
│   │       └── six >=1.9 (circular dependency aborted here)
│   ├── packaging >=14.3 
│   │   └── pyparsing >=2.0.2 
│   ├── protobuf >=3.12.0 (circular dependency aborted here)
│   ├── pytz * 
│   ├── requests >=2.18.0,<3.0.0dev 
│   │   ├── certifi >=2017.4.17 
│   │   ├── charset-normalizer >=2.0.0,<2.1.0 
│   │   ├── idna >=2.5,<4 
│   │   └── urllib3 >=1.21.1,<1.27 
│   ├── setuptools >=40.3.0 (circular dependency aborted here)
│   └── six >=1.13.0 (circular dependency aborted here)
├── google-auth >=1.24.0,<2.0dev
│   ├── cachetools >=2.0.0,<5.0 
│   ├── pyasn1-modules >=0.2.1 
│   │   └── pyasn1 >=0.4.6,<0.5.0 
│   ├── rsa >=3.1.4,<5 
│   │   └── pyasn1 >=0.1.3 (circular dependency aborted here)
│   ├── setuptools >=40.3.0 
│   └── six >=1.9.0 
└── six >=1.12.0
```
and 
https://github.com/googleapis/python-api-core/blob/1db493cafff62e3a9f0b2d8ddf3071199db1af7e/setup.py#L36

As such it is expected to find `setuptools` in the lockfile. The actual bug was that 1.1 did not include it (you already linked the correct PR that fixed said bug). If you agree please close this ticket.

**Closed** 2021-09-12 12:10 UTC
Labels: Bug, Triage
