### ISSUE TITLE
"TypeError unhashable type: 'Table'" when 

### ISSUE THREAD

**Issue by cmcconomyfwig** [python-poetry/poetry#8153] opened 2023-07-04 14:18 UTC
- **Poetry version**: 1.5.1
- **Python version**: 3.11.4
- **OS version and name**: MacOS 13.4
- **pyproject.toml**: (created a default toml with `poetry init`)

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
I have attempted to install poetry with:
`brew install poetry` (arm64 version)
`brew install poetry` (rosetta emulated x86_64 version)
`curl | python3` (default install instructions from poetry web docs)

In all these cases, when I create a default toml using `poetry init` (which is a pre-requisite for `poetry debug info`), running debug info yields the following error:

```
Poetry

unhashable type: 'Table'
```

Running with full verbosity, I find:

```
Poetry
Loading configuration file /Users/cmcconomyfwig/Library/Application Support/pypoetry/config.toml
Loading configuration file /Users/cmcconomyfwig/Library/Application Support/pypoetry/auth.toml

  Stack trace:

  17  ~/Library/Application Support/pypoetry/venv/lib/python3.11/site-packages/cleo/application.py:327 in run
       325│ 
       326│             try:
     → 327│                 exit_code = self._run(io)
       328│             except BrokenPipeError:
       329│                 # If we are piped to another process, it may close early and send a

  16  ~/Library/Application Support/pypoetry/venv/lib/python3.11/site-packages/poetry/console/application.py:190 in _run
       188│         self._load_plugins(io)
       189│ 
     → 190│         exit_code: int = super()._run(io)
       191│         return exit_code
       192│ 

  15  ~/Library/Application Support/pypoetry/venv/lib/python3.11/site-packages/cleo/application.py:431 in _run
       429│             io.input.interactive(interactive)
       430│ 
     → 431│         exit_code = self._run_command(command, io)
       432│         self._running_command = None
       433│ 

  14  ~/Library/Application Support/pypoetry/venv/lib/python3.11/site-packages/cleo/application.py:473 in _run_command
       471│ 
       472│         if error is not None:
     → 473│             raise error
       474│ 
       475│         return terminate_event.exit_code

  13  ~/Library/Application Support/pypoetry/venv/lib/python3.11/site-packages/cleo/application.py:457 in _run_command
       455│ 
       456│             if command_event.command_should_run():
     → 457│                 exit_code = command.run(io)
       458│             else:
       459│                 exit_code = ConsoleCommandEvent.RETURN_CODE_DISABLED

  12  ~/Library/Application Support/pypoetry/venv/lib/python3.11/site-packages/cleo/commands/base_command.py:119 in run
       117│         io.input.validate()
       118│ 
     → 119│         status_code = self.execute(io)
       120│ 
       121│         if status_code is None:

  11  ~/Library/Application Support/pypoetry/venv/lib/python3.11/site-packages/cleo/commands/command.py:62 in execute
        60│ 
        61│         try:
     →  62│             return self.handle()
        63│         except KeyboardInterrupt:
        64│             return 1

  10  ~/Library/Application Support/pypoetry/venv/lib/python3.11/site-packages/poetry/console/commands/debug/info.py:20 in handle
        18│             "\n".join(
        19│                 [
     →  20│                     f"Version: {self.poetry.VERSION}",
        21│                     f"Python:  {poetry_python_version}",
        22│                 ]

   9  ~/Library/Application Support/pypoetry/venv/lib/python3.11/site-packages/poetry/console/commands/command.py:23 in poetry
        21│     def poetry(self) -> Poetry:
        22│         if self._poetry is None:
     →  23│             return self.get_application().poetry
        24│ 
        25│         return self._poetry

   8  ~/Library/Application Support/pypoetry/venv/lib/python3.11/site-packages/poetry/console/application.py:129 in poetry
       127│             project_path = self._io.input.option("directory")
       128│ 
     → 129│         self._poetry = Factory().create_poetry(
       130│             cwd=project_path,
       131│             io=self._io,

   7  ~/Library/Application Support/pypoetry/venv/lib/python3.11/site-packages/poetry/factory.py:95 in create_poetry
        93│ 
        94│         poetry.set_pool(
     →  95│             self.create_pool(
        96│                 config,
        97│                 poetry.local_config.get("source", []),

   6  ~/Library/Application Support/pypoetry/venv/lib/python3.11/site-packages/poetry/factory.py:203 in create_pool
       201│ 
       202│                 pool.add_repository(
     → 203│                     PyPiRepository(disable_cache=disable_cache), priority=pypi_priority
       204│                 )
       205│ 

   5  ~/Library/Application Support/pypoetry/venv/lib/python3.11/site-packages/poetry/repositories/pypi_repository.py:43 in __init__
        41│         fallback: bool = True,
        42│     ) -> None:
     →  43│         super().__init__(
        44│             "PyPI", url.rstrip("/") + "/simple/", disable_cache=disable_cache
        45│         )

   4  ~/Library/Application Support/pypoetry/venv/lib/python3.11/site-packages/poetry/repositories/http_repository.py:55 in __init__
        53│             disable_cache=disable_cache,
        54│         )
     →  55│         self._authenticator.add_repository(name, url)
        56│         self.get_page = functools.lru_cache(maxsize=None)(self._get_page)
        57│ 

   3  ~/Library/Application Support/pypoetry/venv/lib/python3.11/site-packages/poetry/utils/authenticator.py:411 in add_repository
       409│ 
       410│     def add_repository(self, name: str, url: str) -> None:
     → 411│         self.configured_repositories[name] = AuthenticatorRepositoryConfig(name, url)
       412│         self.reset_credentials_cache()
       413│ 

   2  ~/Library/Application Support/pypoetry/venv/lib/python3.11/site-packages/poetry/utils/authenticator.py:401 in configured_repositories
       399│                 url = self._config.get(f"repositories.{repository_name}.url")
       400│                 self._configured_repositories[repository_name] = (
     → 401│                     AuthenticatorRepositoryConfig(repository_name, url)
       402│                 )
       403│ 

   1  <string>:5 in __init__

  TypeError

  unhashable type: 'Table'

  at ~/Library/Application Support/pypoetry/venv/lib/python3.11/site-packages/poetry/utils/authenticator.py:93 in __post_init__
       89│     netloc: str = dataclasses.field(init=False)
       90│     path: str = dataclasses.field(init=False)
       91│ 
       92│     def __post_init__(self) -> None:
    →  93│         parsed_url = urllib.parse.urlsplit(self.url)
       94│         self.netloc = parsed_url.netloc
       95│         self.path = parsed_url.path
       96│ 
       97│     def certs(self, config: Config) -> RepositoryCertificateConfig:
```

When looking into my `/Users/cmcconomyfwig/Library/Application Support/pypoetry/auth.toml`

I found some traces of previous test entries:
```
[http-basic.azure-private]
username = "fwig-pypi"

[http-basic.azure_devops]
username = "fwig_pypi"
```

Similar with contents of `/Users/cmcconomyfwig/Library/Application Support/pypoetry/config.toml`:

```
[virtualenvs]
in-project = true
prefer-active-python = true

[repositories.azure_devops.url]
url = "https://<redacted>"
```

# Root Cause
This last file's "repositories" entry is causing this issue; it was added using the command,
`poetry config repositories.azure_devops.url https://<redacted>`

When I remove that section in the config, it works as expected.

**Comment by dimbleby** [comment] 2023-07-04 14:23
approximately duplicate #7123: "azure_devops.url" is not a good name for a repository

**Comment by dimbleby** [comment] 2023-07-04 14:35
the problem isn't the underscore, it's the dot

**Comment by dimbleby** [comment] 2023-07-04 14:43
you have the power to close this, I don't.  IMO it's adequately covered by #7123 so you should feel free to do so

**Closed** 2023-07-04 14:44 UTC
Labels: kind/bug, status/triage

**Comment by Daniel-Khodabakhsh** [comment] 2023-11-16 03:46
> ... not sure where I picked up the idea that I should include a `.url` suffix.

Because the documentation says so:
https://python-poetry.org/docs/configuration/#repositoriesnameurl
![image](https://github.com/python-poetry/poetry/assets/9839187/84d63db3-1065-4334-81ed-bbf060952f4f)

If you were to `poetry config repositories.<name> <url>` instead, and if you `poetry config --list` afterwards, the `repositories.<name>` magically becomes `repositories.<name>.url` (where `<name>` is `artifactory` below):
![image](https://github.com/python-poetry/poetry/assets/9839187/b6f9f1f3-a247-40f5-827b-a32a12601810)

Seems related to this open ticket: #2204 where they mention the code that automatically truncates and/or adds the `.url` to the configuration name.
