### ISSUE TITLE
optional `path` for git repository specification

### ISSUE THREAD

**Issue by dmvianna** [python-poetry/poetry#5144] opened 2022-02-03 03:58 UTC
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request
`pyproject.toml`
```toml
example = { git = "https://github.com/example/example.git", branch = "main", path="./python" }
```
Some multi-language projects have python modules that are not in the root of the repository. Currently **poetry** cannot find these. I propose you add a `path` keyword to the git specification so that a package can identify which directory within a repository has the desired module.

**Comment by finswimmer** [comment] 2022-02-04 20:20
Hello @dmvianna,

this is duplicate of https://github.com/python-poetry/poetry/issues/755.

fin swimmer

**Closed by finswimmer** 2022-02-04 20:20 UTC
Labels: Feature, Triage
