### ISSUE TITLE
Poetry should use the locally-installed version when it matches the requirement

### ISSUE THREAD

**Issue by abompard** [python-poetry/poetry#5324] opened 2022-03-16 14:22 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Fedora 35
- **Poetry version**: 1.1.13
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/abompard/d6bea4157194c3d3d48bb992e2cdba76

## Issue

If I have a dependency already installed that fits the requirement in `pyproject.toml`, Poetry will go to PyPI anyway and select what it finds there. I think it should use the already installed version.

Here's my situation: I'm depending on [libcomps](https://pypi.org/project/libcomps/) and I have a locally installed version that's newer than what's on PyPI. The reason for that is that the upstream project has either lagged behind when publishing version to PyPI, or prefers distributing the code using the distribution's packages, or both reasons, or yet another. In any case I have `0.1.18` installed locally while PyPI has `0.1.15`.

If I set my `pyproject.toml` to depend on `0.1.18`, poetry will still not accept my locally installed package and output this:
```
Updating dependencies
Resolving dependencies... (0.1s)

  SolverProblemError

  Because poetry-test depends on libcomps (>=0.1.18) which doesn't match any versions, version solving failed.

  at venv/lib64/python3.10/site-packages/poetry/puzzle/solver.py:241 in _solve
      237│             packages = result.packages
      238│         except OverrideNeeded as e:
      239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
      240│         except SolveFailure as e:
    → 241│             raise SolverProblemError(e)
      242│ 
      243│         results = dict(
      244│             depth_first_search(
      245│                 PackageNode(self._package, packages), aggregate_package_nodes
```

This is the output with `-vvv`: https://gist.github.com/abompard/6efee0ad1f97d7310beba2257d46dbf5

But I do have a compatible `libcomps` installed:
```
$ ./venv/bin/pip freeze | grep libcomps
libcomps==0.1.18
```

By looking at the code I realized that in `installation.installer.Installer._do_install()`, the PyPI check is done before the local installed packages are even looked at. No release on PyPI match my dependency, thus the solver errors out with a `SolveFailure`.

Since my locally installed package matches the requirement, I think it should be accepted regardless of what's available on PyPI, at least for the `install` command.

**Comment by finswimmer** [comment] 2022-09-07 09:42
Duplicate of #2861

**Closed by finswimmer** 2022-09-07 09:42 UTC
Labels: kind/bug, status/triage
