### ISSUE TITLE
Poetry not using the correct python version

### ISSUE THREAD

**Issue by shanewazabbas** [python-poetry/poetry#7075] opened 2022-11-22 19:34 UTC
```
> poetry shell
The currently activated Python version 3.9.14 is not supported by the project (>=3.10.1,<3.11).
Trying to find and use a compatible version. 
Using python3 (3.10.7)
Skipping virtualenv creation, as specified in config file.
Spawning shell within /Users/shaneabbas/.pyenv/versions/3.9.14
```

It says using 3.10.7 but the last line says otherwise. 
If I do poetry install, it chooses to still use 3.9.14

Keep in mind that I'm using pyenv and local `.python-version` file
```
> python --version
Python 3.10.7
```

```
> cat .python-version 
3.10.7
```

```
> poetry env info

Virtualenv
Python:         3.9.14
Implementation: CPython
Path:           NA
Executable:     NA

System
Platform:   darwin
OS:         posix
Python:     3.9.14
Path:       /Users/shaneabbas/.pyenv/versions/3.9.14
Executable: /Users/shaneabbas/.pyenv/versions/3.9.14/bin/python3.9
```

There is nothing crazy going on here on my end. How are we not able to handle just having the current python version be respected for poetry? I'm on a mac

**Comment by shanewazabbas** [comment] 2022-11-22 19:53
Also this doesn't work:
```
> poetry env use $(pyenv which python3.10) -vvv
Loading configuration file /Users/shaneabbas/Library/Preferences/pypoetry/config.toml
Loading configuration file /Users/XXX/poetry.toml
Skipping virtualenv creation, as specified in config file.
Using virtualenv: /Users/shaneabbas/.pyenv/versions/3.9.14
```

This is rather frustrating...

**Comment by clintonroy** [comment] 2022-11-22 20:08
I really don't understand what pyenv is, I've never used it, and thus I'm not well placed to try to help here.

Buuuut, if poetry isn't making the virtual environment, that means the user is, and  that means it's on you?

**Comment by shanewazabbas** [comment] 2022-11-22 20:11
> I really don't understand what pyenv is

Then look it up...
There's even documentation about pyenv from poetry: https://python-poetry.org/docs/managing-environments/#switching-between-environments

**Comment by shanewazabbas** [comment] 2022-11-22 20:16
I have and it still doesn't work...

**Comment by shanewazabbas** [comment] 2022-11-22 20:25
Even then the original output I posted is clearly a bug. It shouldn't be saying it's using python3 (3.10.7) when it actually isn't.
```
> poetry shell
The currently activated Python version 3.9.14 is not supported by the project (>=3.10.1,<3.11).
Trying to find and use a compatible version. 
Using python3 (3.10.7)
Skipping virtualenv creation, as specified in config file.
Spawning shell within /Users/shaneabbas/.pyenv/versions/3.9.14
```

Not to mention that message also contradicts `poetry env info` as well.

**Comment by dimbleby** [comment] 2022-11-22 20:51
bugs notwithstanding, I wonder what you are trying to achieve here?  You say you have configured poetry to prefer the active python, we can see you have configured poetry not to create a virtual environment - what _are_ you hoping that `poetry env` or `poetry shell` will do?

If you want the python that's active and not a new virtual environment... just do nothing?

**Comment by shanewazabbas** [comment] 2022-11-22 21:06
> If you want the python that's active and not a new virtual environment... just do nothing?

You understand that poetry install doesn't just magically work right? It has to install the packages somewhere? Where do you think it will do that?

If it installs the packages in python3.9 and I'm using python 3.10, how do you suppose this will work?

**Comment by dimbleby** [comment] 2022-11-22 21:08
where do _you_ think it will do that?  You have configured poetry not to create a virtual environment

> Skipping virtualenv creation, as specified in config file.

Again: what are you expecting to happen?

**Comment by shanewazabbas** [comment] 2022-11-22 21:08
Reread everything I posted. I cannot make it any more clear...

**Comment by finswimmer** [comment] 2022-11-23 08:03
Hey @shanewazabbas,

for further debugging please provide the output of `poetry config --list`.

From what I can see until now:

"The currently activated Python version 3.9.14 is not supported by the project (>=3.10.1,<3.11)." indicated that you haven't set `virtualenvs.prefer-active-python` to `true`.

"Skipping virtualenv creation, as specified in config file." means you have set `virtualenvs.create` to `false`. This disable venv creation by poetry at all. Also a `poetry env use` will not create a venv for you.

A wrong output of `poetry env info` is possible to due a bug, which is fixed in master by https://github.com/python-poetry/poetry/pull/6986

fin swimmer

**Comment by castagninojose** [comment] 2022-11-24 16:20
Are there any plans to make this config the default?

It seems to me that having poetry use the installation version instead of the currently activated makes one of poetry's most important features kinda useless.

**Comment by finswimmer** [comment] 2022-11-24 17:05
> Are there any plans to make this config the default?

We discuss this from time to time, but haven't made a final decision. It's still experimental and in the last couple of weeks some edge case bugs were discovered.

> It seems to me that having poetry use the installation version instead of the currently activated makes one of poetry's most important features kinda useless.

There are at least two groups of users.

One that are using tools like `pyenv`. Those get used to this behavior and loved it. But actually the feature was never introduced with intend. It was a side effect how Poetry was installed with the old `get-poetry.py` script.

The other group are users that don't use `pyenv` and are not aware of such tools. They were always surprised and disappointed about this behavior. Because there systems default `python` linked to `python2`, but they wanted to use `python3` and installed Poetry through it and expected that Poetry will than pick `python3` by default.

So we have to decide from which group we prefer criticism ;)

fin swimmer

PS: I will mark your and my comment as off topic, to keep the focus on the issue here.

**Comment by matthewhughes934** [comment] 2022-11-25 11:59
@shanewazabbas out of curiosity which interpreter is `poetry` being run with, i.e. what's the shebang at the top of `poetry`? You should be able to get this with `head "$(which poetry)"`

**Comment by doolio** [comment] 2022-12-06 10:12
@shanewazabbas I believe we are suffering the same or similar issue. See discussion #6978.

**Comment by garrettargenna** [comment] 2023-03-16 17:58
I’m having a similar issue where I have a terminal opened in a directory that contains a pyproject.toml with python pinned to python 3.10.8 and a .python-version file also set to 3.10.8. If I run
‘python —version’
I get 3.10.8.
But if I run
‘poetry env info’
It lists the system version at 3.10.10 which is the pyenv global version I used when installing poetry.. fine everything should still work because I have ‘virtualenvs.prefer-active-python’ set to true.
But when I run 
‘poetry update’
I get the following error:
"The currently activated Python version 3.10.10 is not supported by the project (3.10.8).
Trying to find and use a compatible version."

**Comment by dnabb** [comment] 2023-03-19 15:34
Similar issue (using pyenv-win) where poetry seems to ignore `virtualenvs.prefer-active-python = true` and tries to use system python instead:


From a new shell in the project directory:  

`pyenv which python`
*C:\Users\mysuer\.pyenv\pyenv-win\versions\3.9.13\python.exe*

`poetry --version`
*Poetry (version 1.4.0)*

`poetry config --list`

```text
...only showing the virtualenvs settings
virtualenvs.create = true
virtualenvs.in-project = false
virtualenvs.options.always-copy = false
virtualenvs.options.no-pip = false
virtualenvs.options.no-setuptools = false
virtualenvs.options.system-site-packages = false
virtualenvs.path = "{cache-dir}\\virtualenvs"
virtualenvs.prefer-active-python = true
virtualenvs.prompt = "{project_name}-py{python_version}
...
```

Now, let's try to acivate another python version:

`pyenv shell 3.10.6`
`pyenv which python`
*C:\Users\myuser\.pyenv\pyenv-win\versions\3.10.6\python.exe*

Looking good. Now, let's start poetry:

`poetry shell`
*The currently activated Python version 3.9.13 is not supported by the project (^3.10.6).
Trying to find and use a compatible version.

[WinError 2] The system cannot find the file specified*

**Comment by pelayogmp** [comment] 2023-03-29 20:28
Same problem here, using poetry 1.4.1 on windows

Global python version is 3.11.2 used to install poetry:

```shell
λ pyenv global
3.11.2
λ python --version
Python 3.11.2
```

Test project requires python 3.10.10, and `poetry install`  fails:

```
 cd $HOME/git/test_project
λ pyenv local
3.10.10
λ python --version
Python 3.10.10
λ poetry install
The currently activated Python version 3.11.2 is not supported by the project (>=3.10,<3.11).
Trying to find and use a compatible version.

[WinError 193] %1 no es una aplicación Win32 válida
```

However using `poetry env use <full_path_to_python_shim>` worked for me:

```shell
poetry env use  %HOME%\.pyenv\pyenv-win\shims\python.bat
Creating virtualenv test-project in ...\test_project\.venv 
Using virtualenv: ...\test_project\.venv

λ poetry shell
Spawning shell within ...\test_project\.venv 

(test-project-py3.10) ...\tutor_nicegui>python --version
Python 3.10.10
```

IMHO [the documentation about pyenv](https://python-poetry.org/docs/managing-environments/) should be clarified.

**Comment by xyxel** [comment] 2023-04-04 16:11
I have the same issue. Looks like the reason is commit: https://github.com/python-poetry/poetry/pull/7471
If add "shell=True" to subprocess.check_output of _full_python_path method, everything works fine.

**Comment by dimbleby** [comment] 2023-04-04 16:43
A problem reported in November 2022 is certainly not caused by a commit made in February 2023

**Comment by xyxel** [comment] 2023-04-05 08:47
Yes, you are right, I'm not sure about the original issue. But "shell=True" can help people who left three last messages.
 On Windows pyenv uses batch files for python management. In particularly,  python.bat file. If you execute subprocess with shell=False, Popen doesn't use python.bat, but use python.exe that is used for poetry execution.
 
Please look at example:

`>>> subprocess.call("python")
Python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()
0
>>> subprocess.call("python.bat")
Python 3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()
0
>>> subprocess.call("python", shell=True) 
Python 3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.`

Thank you.

**Comment by dimbleby** [comment] 2023-04-05 14:34
well let's try to keep separate issues separate - please raise new issues for new problems.

(perhaps we want a `shutil.which("python")` round about https://github.com/python-poetry/poetry/blob/161b19cb4e4686fc5a0a7925001534a87f6c4052/src/poetry/utils/env.py#L545, feel free to experiment and open an MR)

**Comment by finswimmer** [comment] 2024-03-11 20:13
Hello @shanewazabbas,

you haven't come back to this issue for a long while. So I assume this is solved in the meantime and I can close this ticket.

Feel free to leave a comment if you disagree.

fin swimmer

**Closed by finswimmer** 2024-03-11 20:13 UTC
Labels: kind/bug, status/triage, status/waiting-on-response
