### ISSUE TITLE
`install-poetry.py` incorrectly reports Poetry is already installed, but legacy installer works

### ISSUE THREAD

**Issue by EFulmer** [python-poetry/poetry#5112] opened 2022-01-27 01:09 UTC
Hi there! Bug report below:

- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
    - Not applicable, my bug appears when I am trying to install Poetry.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).
    - I'm not running into any exceptions. 

- **OS version and name**: macOS Mojave 10.14.6
- **Poetry version**: N/A, trying to install it
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: N/A

## Issue
I am trying to install Poetry fresh onto a computer. Following [the official instructions](https://python-poetry.org/docs/master/#installing-with-the-official-installer), here's my output:

```
$ curl -ksSL https://install.python-poetry.org | python3 -  # -k because without it a certificate expiry error shows up
Retrieving Poetry metadata

The latest version (1.1.12) is already installed.
# sanity checks
$ ls ~/.local/bin
ls: /Users/eric/.local/bin: No such file or directory
$ ls ~/.poetry
ls: /Users/eric/.poetry: No such file or directory
$ python3 --version
Python 3.9.7
$ which poetry
poetry not found
```

I don't have any guesses as to why this is, I would assume the certificate problem isn't relevant here and `-k` should bypass it.

**But**, the old installer works fine:

```
$ curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
Retrieving Poetry metadata

This installer is deprecated. Poetry versions installed using this script will not be able to use 'self update' command to upgrade to 1.2.0a1 or later.
# Welcome to Poetry!

This will download and install the latest version of Poetry,
a dependency and package manager for Python.

It will add the `poetry` command to Poetry's bin directory, located at:

$HOME/.poetry/bin

This path will then be added to your `PATH` environment variable by
modifying the profile files located at:

$HOME/.profile
$HOME/.zshrc
$HOME/.bash_profile

You can uninstall at any time by executing this script with the --uninstall option,
and these changes will be reverted.

Installing version: 1.1.12
  - Downloading poetry-1.1.12-darwin.tar.gz (51.00MB)

Poetry (1.1.12) is installed now. Great!

To get started you need Poetry's bin directory ($HOME/.poetry/bin) in your `PATH`
environment variable. Next time you log in this will be done
automatically.

To configure your current shell run `source $HOME/.poetry/env`
```

Any help would be appreciated. 🙂

**Comment by finswimmer** [comment] 2022-01-28 08:18
Hey @EFulmer,

this is a more or less duplicate of https://github.com/python-poetry/poetry/issues/4705.

fin swimmer

**Closed by finswimmer** 2022-01-28 08:18 UTC
Labels: Bug, Triage
