### ISSUE TITLE
[1.0.0b4] poetry run fails with FileNotFoundError

### ISSUE THREAD

**Issue by MrGreenTea** [python-poetry/poetry#1567] opened 2019-11-11 09:27 UTC
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option). `poetry run -vvv` does not change anything about the output

- **OS version and name**: Linux x86_64 (Elementary OS)
- **Poetry version**: 1.0.0b4
- **Link of a [Gist](https://gist.github.com/MrGreenTea/3d9c1e9e9f55d4822f3ae732647ccb96) with the contents of your pyproject.toml file**: [Link](https://gist.github.com/MrGreenTea/3d9c1e9e9f55d4822f3ae732647ccb96) (generated with `poetry new`)

## Issue
Running `poetry run` without additional argument fails with 
```
[FileNotFoundError]
[Errno 2] No such file or directory
```

Executing `poetry run pip list` for example works fine. It's just with either no argument or when the first argument is not found as an executable.

**Comment by hoefling** [comment] 2019-11-11 15:00
Me also getting this error with the `1.0.0b4`. Using double dashes is broken in the latest beta, e.g. `poetry run -- pytest -svx --lf` ends with the `FileNotFoundError` message.

**Comment by janw** [comment] 2019-12-02 15:26
For me the inverse is true now.

```
poetry run pytest
```

runs just fine, while

```
poetry run -- pytest
```

gives me the FileNotFoundError.

**Comment by taketarouex** [comment] 2020-01-01 14:45
I also getting this error after renaming the parent dir.
And it resolved by removing .venv dir and `poetry install`

**Comment by JavierL1** [comment] 2020-01-20 13:02
> I also getting this error after renaming the parent dir.
> And it resolved by removing .venv dir and `poetry install`

Can you give a little bit more feedback on how did you resolve the issue? You removed the `poetry install` command from execution?

**Comment by taketarouex** [comment] 2020-01-20 13:32
I'm sorry. I was mistaken.
I intended to say that I removed .venv dir, after that I executed `poetry install` and I resolved it

**Comment by JavierL1** [comment] 2020-01-20 17:41
I just solved my problem. I used for reference this issue python-poetry/poetry#1198. 
In my case, I have a project that uses a CLI interface implemented with [click](https://click.palletsprojects.com/en/7.x/). So in order to run a command using poetry, first I had to register the group of commands as a poetry script, just like it's described [here](https://stackoverflow.com/questions/55063392/poetry-manage-python-package-cli).
I hope it helps you!

**Comment by kiudee** [comment] 2020-08-03 12:43
Same problem here using `1.0.10` on Ubuntu 20.04.
```
poetry run --help
```
results in
```
[FileNotFoundError]
[Errno 2] No such file or directory
```
while `poetry run python` or `poetry run pip` works.

**Comment by dector** [comment] 2020-08-17 14:28
I have this issue too.

<details><summary><code>$ cat /etc/os-release</code></summary>
<pre>
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
</pre>
</details>

<details><summary><code>$ poetry --version</code></summary>
<pre>
Poetry version 1.0.10
</pre>
</details>

## This doesn't work:

<details><summary><code>$ poetry run "echo hello"</code></summary>
<pre>
Poetry version [OSError]
[Errno 2] No such file or directory
</pre>
</details>

<details><summary><code>$ poetry run --help</code></summary>
<pre>
Poetry version [OSError]
[Errno 2] No such file or directory
</pre>
</details>

## This works:

<details><summary><code>$ poetry run echo hello</code></summary>
<pre>
hello
</pre>
</details>

**Comment by technillogue** [comment] 2020-12-25 21:45
it would be awfully nice if poetry told you to run `poetry install` or something instead of just FileNotFoundError

**Comment by mattwelke** [comment] 2021-01-12 18:51
I'm getting this error even after I run `poetry install`.

Steps to reproduce:

- Create new Poetry project with `poetry init`.
- Create file `app.py` with contents `print('hello')`.
- Run `poetry run app.py`.

Something I notice is that poetry can't run my program but using python directly can:

```
poetry run app.py 

  FileNotFoundError

  [Errno 2] No such file or directory

  at ~/.pyenv/versions/3.9.1/lib/python3.9/os.py:607 in _execvpe
       603│         path_list = map(fsencode, path_list)
       604│     for dir in path_list:
       605│         fullname = path.join(dir, file)
       606│         try:
    →  607│             exec_func(fullname, *argrest)
       608│         except (FileNotFoundError, NotADirectoryError) as e:
       609│             last_exc = e
       610│         except OSError as e:
       611│             last_exc = e
```

```
python app.py 
hello
```

**Comment by rourich** [comment] 2021-02-05 09:56
> Me also getting this error with the `1.0.0b4`. Using double dashes is broken in the latest beta, e.g. `poetry run -- pytest -svx --lf` ends with the `FileNotFoundError` message.

were you able to circumvent this problem?

**Comment by KevinCooper** [comment] 2021-02-15 07:13
I am also getting this issue.  Unfortunately, I'm not sure the exact steps my project took to start getting to this error.

```
shell$ poetry version

  FileNotFoundError

  [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/usr/local/lib/python3.8/dist-packages/clikit/api/command/command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "/usr/local/lib/python3.8/dist-packages/clikit/api/command/command.py", line 171, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/usr/local/lib/python3.8/dist-packages/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File "/usr/local/lib/python3.8/dist-packages/poetry/console/commands/version.py", line 68, in handle
    self.poetry.package.name, self.poetry.package.pretty_version
  File "/usr/local/lib/python3.8/dist-packages/poetry/console/commands/command.py", line 10, in poetry
    return self.application.poetry
  File "/usr/local/lib/python3.8/dist-packages/poetry/console/application.py", line 69, in poetry
    self._poetry = Factory().create_poetry(Path.cwd())
  File "/usr/lib/python3.8/pathlib.py", line 1092, in cwd
    return cls(os.getcwd())
FileNotFoundError: [Errno 2] No such file or directory
```

**Comment by Nathaniel-Rink** [comment] 2021-03-02 18:27
> 
> EDIT:
> 
> Oh wait, I'm just stupid. I misunderstood how to use the `poetry run` command. Checking the docs helped me:
> 
> ```
> poetry run python app.py
> hello
> ```

This was immensely helpful. I'd misread the instructions too

**Comment by joker234** [comment] 2021-03-16 19:26
I have a similar error:
```bash
$ poetry run --no-ansi echo "hello"

  FileNotFoundError

  [Errno 2] No such file or directory

  at /usr/local/lib/python3.8/os.py:601 in _execvpe
       597│         path_list = map(fsencode, path_list)
       598│     for dir in path_list:
       599│         fullname = path.join(dir, file)
       600│         try:
    →  601│             exec_func(fullname, *argrest)
       602│         except (FileNotFoundError, NotADirectoryError) as e:
       603│             last_exc = e
       604│         except OSError as e:
       605│             last_exc = e
```
or
```bash
$ poetry --no-ansi run echo "hello"
USAGE
  poetry help [<command1>] ... [<commandN>]

ARGUMENTS
  <command>              The command name

GLOBAL OPTIONS
  -h (--help)            Display this help message
  -q (--quiet)           Do not output any message
  -v (--verbose)         Increase the verbosity of messages: "-v" for normal output, "-vv" for more verbose output and "-vvv" for debug
  -V (--version)         Display this application version
  --ansi                 Force ANSI output
  --no-ansi              Disable ANSI output
  -n (--no-interaction)  Do not ask any interactive question
```
vs.
```bash
$ poetry run echo "hello"
hello
```

According to the help, I can use `--no-ansi` and `--no-interaction` with every poetry command. Where am I supposed to put them? The help isn't clear on that terms.
```bash
$ poetry help run
USAGE
  poetry run <args1> ... [<argsN>]

ARGUMENTS
  <args>                 The command and arguments/options to run.

GLOBAL OPTIONS
  -h (--help)            Display this help message
  -q (--quiet)           Do not output any message
  -v (--verbose)         Increase the verbosity of messages: "-v" for normal output, "-vv" for more verbose output and "-vvv" for debug
  -V (--version)         Display this application version
  --ansi                 Force ANSI output
  --no-ansi              Disable ANSI output
  -n (--no-interaction)  Do not ask any interactive question
```

**Comment by NelsonAPenn** [comment] 2021-07-21 20:35
I get this error if I haven't properly added / installed a package within poetry. But the error is especially baffling in my case, because the directory it is trying to read from shouldn't be python related at all:

Below is some slightly censored output (just the file path censored) for if I run `poetry run pytest` without having first installed / added `pytest`.
```
poetry run pytest

  FileNotFoundError

  [Errno 2] No such file or directory: b'/path/to/my/godot/installation/godot-3.2.3/pytest'

  at /usr/lib/python3.8/os.py:601 in _execvpe
       597│         path_list = map(fsencode, path_list)
       598│     for dir in path_list:
       599│         fullname = path.join(dir, file)
       600│         try:
    →  601│             exec_func(fullname, *argrest)
       602│         except (FileNotFoundError, NotADirectoryError) as e:
       603│             last_exc = e
       604│         except OSError as e:
       605│             last_exc = e

```

I have no idea why poetry wants to look in the folder in which I installed godot, but it does, every time. Similarly:

```
 poetry run "the answer to life, the universe and everything"

  FileNotFoundError

  [Errno 2] No such file or directory: b'/path/to/my/godot/installation/godot-3.2.3/the answer to life, the universe and everything'

  at /usr/lib/python3.8/os.py:601 in _execvpe
       597│         path_list = map(fsencode, path_list)
       598│     for dir in path_list:
       599│         fullname = path.join(dir, file)
       600│         try:
    →  601│             exec_func(fullname, *argrest)
       602│         except (FileNotFoundError, NotADirectoryError) as e:
       603│             last_exc = e
       604│         except OSError as e:
       605│             last_exc = e

```

System: ubuntu 20.04
Poetry version: 1.1.6

**Comment by gstravinskaite** [comment] 2021-09-24 08:47
I have the same issue as above, it tries to look to the Golang binaries to run Python program.

**Comment by comalice** [comment] 2022-01-26 19:32
I have this same issue but it is looking for Perl binaries...

```bash
root@alatham <path to poetry project> (<virtualenv-name>) # poetry run

  FileNotFoundError

  [Errno 2] No such file or directory: b'/usr/bin/core_perl/run'

  at /usr/lib/python3.10/os.py:607 in _execvpe
       603│         path_list = map(fsencode, path_list)
       604│     for dir in path_list:
       605│         fullname = path.join(dir, file)
       606│         try:
    →  607│             exec_func(fullname, *argrest)
       608│         except (FileNotFoundError, NotADirectoryError) as e:
       609│             last_exc = e
       610│         except OSError as e:
       611│             last_exc = e
```

Note that I'm running from WSL2 on Arch Linux.

**Comment by elyobo** [comment] 2022-02-04 09:22
Had the same problem, `poetry install` resolved it (even though nothing had changed :man_shrugging:)

**Comment by NelsonAPenn** [comment] 2022-02-20 23:53
In terms of the error message, it is raised during the call to `os.execvpe`. The reason the directory in the message is so weird in every case is because it is always the last path in the system path.

I think that the output of `poetry run <command>` could be much improved if it were to produce the same output that would appear if you ran `poetry shell` followed by `<command>` in the subshell. Running a nonexist command within `poetry shell` returns (on Ubuntu 20.04)
```

Command 'aoeu' not found, did you mean:

  command 'aoeui' from deb aoeui (1.7+20160302.git4e5dee9-2)

Try: sudo apt install <deb name>

```
which is kind of result you'd expect in this situation. I've looked into this a little and am not sure on the implementation details, but will create a PR if I come up with something I'm satisfied with.

**Comment by branchvincent** [comment] 2022-02-27 06:10
Some of the UX issues around `run` have already been fixed on `master`:

```console
$ poetry --version
Poetry (version 1.2.0a2)
$ poetry run

Not enough arguments (missing: "args")
$ poetry run --help

Description:
  Runs a command in the appropriate environment.
...
```

 I've filed #5243 to address the remaining cryptic `FileNotFoundError` when an executable isn't found

**Closed** 2022-02-27 07:31 UTC
Labels: Bug, CLI, Error Handling

**Comment by pkoch** [comment] 2022-03-18 19:29
Just got bit by this. In my case, I'd forgotten to run `poetry install` before `poetry run pytest`.

**Comment by 1player** [comment] 2022-07-06 14:15
Still having this issue in version 1.1.3

```
% poetry -V
Poetry version 1.1.13
% poetry run

  FileNotFoundError

  [Errno 2] No such file or directory: b'/usr/bin/core_perl/run'

  at /usr/lib/python3.10/os.py:607 in _execvpe
       603│         path_list = map(fsencode, path_list)
       604│     for dir in path_list:
       605│         fullname = path.join(dir, file)
       606│         try:
    →  607│             exec_func(fullname, *argrest)
       608│         except (FileNotFoundError, NotADirectoryError) as e:
       609│             last_exc = e
       610│         except OSError as e:
       611│             last_exc = e
```

**Comment by 1player** [comment] 2022-07-06 16:22
I literally just created a new repo with `poetry init` and ran `poetry run`. Running on Arch Linux.

**Comment by pkoch** [comment] 2022-07-06 16:46
Indeed. Here's how I repro'ed it:

```bash
cat <<EOF > Dockerfile
FROM archlinux

RUN pacman -Syyu --noconfirm python \
&& mkdir /code \
&& cd /code \
&& (curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -) \
&& echo "source /root/.poetry/env" > /root/.profile \
&& . /root/.profile \
&& poetry init -n
EOF

docker run -it --rm $(docker build -q .) bash -c ". /root/.profile && cd code && poetry run"
```

**Comment by dimbleby** [comment] 2022-07-06 17:36
On more recent versions of poetry you will see this:
```
$ poetry run

Not enough arguments (missing: "args")
```
which is a more helpful error message

**Comment by pkoch** [comment] 2022-07-06 17:47
@dimbleby Can you name what version that starts happening? I've repo'ed @1player's problem with Poetry version 1.1.13.

**Comment by dimbleby** [comment] 2022-07-06 17:54
no, I don't know where this changed.  Try with the latest beta 1.2.0b2.

**Comment by pkoch** [comment] 2022-07-06 18:00
Using `curl -sSL https://install.python-poetry.org | python3 - --version "1.2.0b2"`, I do see that new error. 👌

**Comment by NourKired** [comment] 2022-08-19 08:07
you have to add on you're pyproject.toml, this script:
**example:**
[tool.poetry.scripts]
converter-image-text = "converter_image_text.main:cli"
