### ISSUE TITLE
Poetry install threading issue on Docker build

### ISSUE THREAD

**Issue by JeremyCraigMartinez** [python-poetry/poetry#8860] opened 2024-01-09 16:55 UTC
- **Poetry version**: 1.7.1
- **Python version**: 3.11
- **OS version and name**: [python:3.11-slim](https://hub.docker.com/_/python/)
- **pyproject.toml**: <below>

```[tool.poetry]
name = "./api"
version = "0.1.0"
description = ""
authors = ["Jeremy Martinez <jeremy.martinez@avalara.com>"]
readme = "README.md"
packages = [
    { include = "app" },
]

[tool.poetry.dependencies]
python = "^3.11"
uvicorn = "^0.23.2"
langserve = {extras = ["server"], version = ">=0.0.30"}
pydantic = "<2"
openai = "^1.6.1"
python-dotenv = "^1.0.0"
boto3 = "^1.34.14"


[tool.poetry.group.dev.dependencies]
langchain-cli = ">=0.0.15"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a [recommended method](https://python-poetry.org/docs/#installation).
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

Running `poetry install --no-interaction --no-ansi --no-root -vvv` in Dockerfile in an environment I do not have access to (company-wide gitlab CI/CD platform).

It is my understanding that, according to my config, I should not be experiencing parallel install issues. 

Poetry config below:

```
cache-dir = "/root/.cache/pypoetry"
experimental.system-git-client = false
installer.max-workers = null
installer.modern-installation = false # fails when set to true, too
installer.no-binary = null
installer.parallel = false # fails when set to true, too
virtualenvs.create = false
virtualenvs.in-project = null
virtualenvs.options.always-copy = false
virtualenvs.options.no-pip = false
virtualenvs.options.no-setuptools = false
virtualenvs.options.system-site-packages = false
virtualenvs.path = "{cache-dir}/virtualenvs"  # /root/.cache/pypoetry/virtualenvs
virtualenvs.prefer-active-python = false
virtualenvs.prompt = "{project_name}-py{python_version}"
warnings.export = true
```

Verbose install output:

```
  Stack trace:
  14  /usr/local/lib/python3.11/site-packages/cleo/application.py:327 in run
       325│ 
       326│             try:
     → 327│                 exit_code = self._run(io)
       328│             except BrokenPipeError:
       329│                 # If we are piped to another process, it may close early and send a
  13  /usr/local/lib/python3.11/site-packages/poetry/console/application.py:190 in _run
       188│         self._load_plugins(io)
       189│ 
     → 190│         exit_code: int = super()._run(io)
       191│         return exit_code
       192│ 
  12  /usr/local/lib/python3.11/site-packages/cleo/application.py:431 in _run
       429│             io.input.interactive(interactive)
       430│ 
     → 431│         exit_code = self._run_command(command, io)
       432│         self._running_command = None
       433│ 
  11  /usr/local/lib/python3.11/site-packages/cleo/application.py:473 in _run_command
       471│ 
       472│         if error is not None:
     → 473│             raise error
       474│ 
       475│         return terminate_event.exit_code
  10  /usr/local/lib/python3.11/site-packages/cleo/application.py:457 in _run_command
       455│ 
       456│             if command_event.command_should_run():
     → 457│                 exit_code = command.run(io)
       458│             else:
       459│                 exit_code = ConsoleCommandEvent.RETURN_CODE_DISABLED
   9  /usr/local/lib/python3.11/site-packages/cleo/commands/base_command.py:117 in run
       115│         io.input.validate()
       116│ 
     → 117│         return self.execute(io) or 0
       118│ 
       119│     def merge_application_definition(self, merge_args: bool = True) -> None:
   8  /usr/local/lib/python3.11/site-packages/cleo/commands/command.py:61 in execute
        59│ 
        60│         try:
     →  61│             return self.handle()
        62│         except KeyboardInterrupt:
        63│             return 1
   7  /usr/local/lib/python3.11/site-packages/poetry/console/commands/install.py:150 in handle
       148│         self.installer.verbose(self.io.is_verbose())
       149│ 
     → 150│         return_code = self.installer.run()
       151│ 
       152│         if return_code != 0:
   6  /usr/local/lib/python3.11/site-packages/poetry/installation/installer.py:104 in run
       102│             self.verbose(True)
       103│ 
     → 104│         return self._do_install()
       105│ 
       106│     def dry_run(self, dry_run: bool = True) -> Installer:
   5  /usr/local/lib/python3.11/site-packages/poetry/installation/installer.py:341 in _do_install
       339│ 
       340│         # Execute operations
     → 341│         status = self._execute(ops)
       342│ 
       343│         if status == 0 and self._update:
   4  /usr/local/lib/python3.11/site-packages/poetry/installation/installer.py:358 in _execute
       356│ 
       357│     def _execute(self, operations: list[Operation]) -> int:
     → 358│         return self._executor.execute(operations)
       359│ 
       360│     def _populate_lockfile_repo(
   3  /usr/local/lib/python3.11/site-packages/poetry/installation/executor.py:192 in execute
       190│                     continue
       191│ 
     → 192│                 tasks.append(self._executor.submit(self._execute_operation, operation))
       193│ 
       194│             try:
   2  /usr/local/lib/python3.11/concurrent/futures/thread.py:176 in submit
       174│ 
       175│             self._work_queue.put(w)
     → 176│             self._adjust_thread_count()
       177│             return f
       178│     submit.__doc__ = _base.Executor.submit.__doc__
   1  /usr/local/lib/python3.11/concurrent/futures/thread.py:199 in _adjust_thread_count
       197│                                        self._initializer,
       198│                                        self._initargs))
     → 199│             t.start()
       200│             self._threads.add(t)
       201│             _threads_queues[t] = self._work_queue
  RuntimeError
  can't start new thread
  at /usr/local/lib/python3.11/threading.py:964 in start
       960│ 
       961│         with _active_limbo_lock:
       962│             _limbo[self] = self
       963│         try:
    →  964│             _start_new_thread(self._bootstrap, ())
       965│         except Exception:
       966│             with _active_limbo_lock:
       967│                 del _limbo[self]
       968│             raise
```

**Comment by dimbleby** [comment] 2024-01-09 18:09
this isn't going to be a poetry bug, but a problem with the docker container or environment or something.  stackoverflow has lots of suggestions

**Comment by JeremyCraigMartinez** [comment] 2024-01-10 06:36
@dimbleby would you mind pointing one out? A common solution I have found (and applied in the past) is the `--progress-bar false` flag on `pip install`. However, this is not an option on `poetry install`

**Comment by dimbleby** [comment] 2024-01-10 20:24
No.  I am sure your browser and search engine work as well as mine do.  

What matters _here_ is that poetry making use of threads is not a bug: you will need to figure out why it is that your environment does not allow a new thread to be created.

**Comment by abn** [comment] 2024-03-02 22:42
Kagi says https://stackoverflow.com/a/70093119

I'm going to close this as this is not a poetry bug but rather an environment permission/limit issue.

**Closed by abn** 2024-03-02 22:42 UTC
Labels: kind/bug, status/triage
