### ISSUE TITLE
 Poetry Malfunction

### ISSUE THREAD

**Issue by fkatibi** [python-poetry/poetry#6806] opened 2022-10-15 06:49 UTC
poetry
dyld: Library not loaded: /usr/local/Cellar/python@3.10/3.10.6_2/Frameworks/Python.framework/Versions/3.10/Python
  Referenced from: /Users/funmi/Library/Application Support/pypoetry/venv/bin/python
  Reason: image not found
zsh: abort      poetry

**Comment by dimbleby** [comment] 2022-10-15 08:27
Clearly poetry is not universally broken.  You forgot to provide any useful details about what is different on your system or how you got into this state.

**Comment by angeliney** [comment] 2022-10-18 02:57
I'm having this problem as well with macOS Monterey 12.6 after doing a brew update

**Comment by neersighted** [comment] 2022-10-18 02:59
Looks like https://github.com/python-poetry/install.python-poetry.org/issues/71, closing as duplicate given no reproduction details from anybody in this issue.

**Closed by neersighted** 2022-10-18 02:59 UTC
Labels: status/waiting-on-response
