### ISSUE TITLE
1.0.0b4 attempts to install local project as part of "poetry install".

### ISSUE THREAD

**Issue by MaineTim** [python-poetry/poetry#1561] opened 2019-11-09 11:44 UTC
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- Linux Mint 19.2 Python 3.8.0 
- 1.0.0b4 
- https://gist.github.com/MaineTim/aceb037b44cff276d9b6f44a710bb560  

## Issue

As a part of installing dependencies for a project as specified in pyproject.toml, poetry atttempts to install the project itself, failing with an EnvCommandError. 

```
(venv) tim@helios:/data/Projects/Local/Python/tc_py$ poetry install
Updating dependencies
Resolving dependencies... (0.2s)

Writing lock file


Package operations: 23 installs, 0 updates, 0 removals

  - Installing pyparsing (2.4.4)
  - Installing six (1.13.0)
  - Installing appdirs (1.4.3)
  - Installing atomicwrites (1.3.0)
  - Installing attrs (19.3.0)
  - Installing click (7.0)
  - Installing entrypoints (0.3)
  - Installing mccabe (0.6.1)
  - Installing more-itertools (7.2.0)
  - Installing packaging (19.2)
  - Installing pathspec (0.6.0)
  - Installing pluggy (0.13.0)
  - Installing py (1.8.0)
  - Installing pycodestyle (2.5.0)
  - Installing pyflakes (2.1.1)
  - Installing regex (2019.11.1)
  - Installing toml (0.10.0)
  - Installing typed-ast (1.4.0)
  - Installing wcwidth (0.1.7)
  - Installing black (19.10b0)
  - Installing flake8 (3.7.9)
  - Installing profilehooks (1.11.0)
  - Installing pytest (5.2.2)
  - Installing tc_py (0.1.0)

[EnvCommandError]
Command ['/data/Projects/Local/Python/tc_py/venv/bin/python', '-m', 'pip', 'install', '-e', '/data/Projects/Local/Python/tc_py'] errored with the following return code 1, and output:
Obtaining file:///data/Projects/Local/Python/tc_py
ERROR: Files/directories not found in /data/Projects/Local/Python/tc_py
WARNING: You are using pip version 19.2.3, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```
Second attempt with debug:
```
(venv) tim@helios:/data/Projects/Local/Python/tc_py$ poetry install -vvv
Using virtualenv: /data/Projects/Local/Python/tc_py/venv
Installing dependencies from lock file

Nothing to install or update

  - Skipping pyparsing (2.4.4) Already installed
  - Skipping six (1.13.0) Already installed
  - Skipping appdirs (1.4.3) Already installed
  - Skipping atomicwrites (1.3.0) Already installed
  - Skipping attrs (19.3.0) Already installed
  - Skipping click (7.0) Already installed
  - Skipping colorama (0.4.1) Not needed for the current environment
  - Skipping entrypoints (0.3) Already installed
  - Skipping mccabe (0.6.1) Already installed
  - Skipping more-itertools (7.2.0) Already installed
  - Skipping packaging (19.2) Already installed
  - Skipping pathspec (0.6.0) Already installed
  - Skipping pluggy (0.13.0) Already installed
  - Skipping py (1.8.0) Already installed
  - Skipping pycodestyle (2.5.0) Already installed
  - Skipping pyflakes (2.1.1) Already installed
  - Skipping regex (2019.11.1) Already installed
  - Skipping toml (0.10.0) Already installed
  - Skipping typed-ast (1.4.0) Already installed
  - Skipping wcwidth (0.1.7) Already installed
  - Skipping black (19.10b0) Already installed
  - Skipping flake8 (3.7.9) Already installed
  - Skipping profilehooks (1.11.0) Already installed
  - Skipping pytest (5.2.2) Already installed
  - Installing tc_py (0.1.0)

[EnvCommandError]
Command ['/data/Projects/Local/Python/tc_py/venv/bin/python', '-m', 'pip', 'install', '-e', '/data/Projects/Local/Python/tc_py'] errored with the following return code 1, and output:
Obtaining file:///data/Projects/Local/Python/tc_py
ERROR: Files/directories not found in /data/Projects/Local/Python/tc_py
WARNING: You are using pip version 19.2.3, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


Traceback (most recent call last):
  File "/home/tim/.poetry/lib/poetry/_vendor/py3.8/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/home/tim/.poetry/lib/poetry/_vendor/py3.8/clikit/api/command/command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "/home/tim/.poetry/lib/poetry/_vendor/py3.8/clikit/api/command/command.py", line 171, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/home/tim/.poetry/lib/poetry/_vendor/py3.8/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File "/home/tim/.poetry/lib/poetry/console/commands/install.py", line 88, in handle
    builder.build()
  File "/home/tim/.poetry/lib/poetry/masonry/builders/editable.py", line 17, in build
    return self._setup_build()
  File "/home/tim/.poetry/lib/poetry/masonry/builders/editable.py", line 41, in _setup_build
    self._env.run(
  File "/home/tim/.poetry/lib/poetry/utils/env.py", line 1009, in run
    return super(VirtualEnv, self).run(bin, *args, **kwargs)
  File "/home/tim/.poetry/lib/poetry/utils/env.py", line 823, in run
    raise EnvCommandError(e, input=input_)
```

**Comment by stevegore** [comment] 2019-11-11 00:20
Try using `--no-root`

**Comment by pcattori** [comment] 2019-11-12 03:14
there are 2 issues here:
1) How to avoid installing the local project, which is covered in #800 (and as mentioned, can be done via `--no`root`)
2) If I *do* want to install the local project, then how do I get around this `EnvCommandError`?

I am looking for an answer to (2)^

---

Doing the local proj installation manually works just fine:

```sh
python -m pip install -e /Users/pedro/workspace/static-dura
Obtaining file:///Users/pedro/workspace/static-dura
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Installing collected packages: static-dura
  Running setup.py develop for static-dura
Successfully installed static-dura
```

but as it's being done by `poetry` it fails:

```sh
Command ['/Users/pedro/Library/Caches/pypoetry/virtualenvs/static-dura-CCRtcgPC-py3.8/bin/python', '-m', 'pip', 'install', '-e', '/Users/pedro/workspace/static-dura'] errored with the following return code 1, and output: 
Obtaining file:///Users/pedro/workspace/static-dura
ERROR: Files/directories not found in /Users/pedro/workspace/static-dura/
```

---

- MacOS 10.15.1
- Python 3.8.0
- Poetry 1.0.0b4

**Comment by finswimmer** [comment] 2020-02-06 19:38
Hello @pcattori ,

it looks like this was a problem on your machine, because installing the project itself during `poetry install` is the default, that should work.

If you haven't come back until now, I guess you've solved this and I close this issue.

Feel free to leave a comment if you disagree.

fin swimmer

**Closed by finswimmer** 2020-02-06 19:38 UTC
Labels: Bug

**Comment by pcattori** [comment] 2020-02-06 20:18
I'm using v1.0.2 now and haven't run into this problem since. Seems fixed (or at least unreproducible for me). Thanks! 🙌
