### ISSUE TITLE
Unexpectedly verbose "poetry run" failure

### ISSUE THREAD

**Issue by dimaqq** [python-poetry/poetry#3541] opened 2021-01-06 01:05 UTC
This is the error I get when I try to run e.g. `mypy` in project that doesn't have `mypy` dep.
(Same for `poetry run some_typo` as well)

```py
> poetry run mypy

  FileNotFoundError

  [Errno 2] No such file or directory

  at /usr/local/bin/../../../Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/os.py:601 in _execvpe
       597│         path_list = map(fsencode, path_list)
       598│     for dir in path_list:
       599│         fullname = path.join(dir, file)
       600│         try:
    →  601│             exec_func(fullname, *argrest)
       602│         except (FileNotFoundError, NotADirectoryError) as e:
       603│             last_exc = e
       604│         except OSError as e:
       605│             last_exc = e
```
(displayed colorised)

While it's pretty, I guess displaying the exception call site is redundant, as well as not actually helpful.

Version info `Poetry version 1.1.4`, venv with `Python 3.9.1`

**Comment by sinoroc** [comment] 2021-01-06 10:43
Should have been filed as a feature request maybe? I see it as a request to improve the UX (fair enough), not as a bug.

It is true that in general the UX regarding failures could be improved. There is not always need to show a stack trace, for example in that case `FileNotFoundError` could have been enough.

_[Aside: I am still not sure why poetry tries to check for the existence of the `mypy` binary, why isn't it delegated to the OS, or shell or whatever?]_

**Comment by branchvincent** [comment] 2022-02-27 06:29
Hi, thanks for reporting. I agree this should be improved and am working on a fix. I'm going to mark this as a duplicate of #1567, feel free to follow along there

**Closed by branchvincent** 2022-02-27 06:29 UTC
Labels: Bug, Triage
