### ISSUE TITLE
Add `subdirectory` to poetry VCS configs

### ISSUE THREAD

**Issue by rickmark** [python-poetry/poetry#5272] opened 2022-03-03 21:21 UTC
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request
Some projects (e.g. `unicorn-engine/unicorn`) place python projects into subdirectories as they support bindings in multiple languages.  Today we cannot add this as a Git VCS url to a project because `setup.py` is not at the root but instead at a path of `bindings/python/setup.py` relative to the VCS root.

Also, the error messages for the above are non-intuitive.  VCS poetry projects should check for `setup.py` or `pyproject.toml` and provide helpful messages that they could not be found in the the VCS root.

We should be mindful that we *do not* want to check out the subdirectory from VCS as a _treeish_ as many will do `..` navigation to shared resources.  (Again, Unicorn as an example)

**Comment by finswimmer** [comment] 2022-03-04 07:12
Hello @rickmark,

this is a duplicate of https://github.com/python-poetry/poetry/issues/755.

fin swimmer

**Closed by finswimmer** 2022-03-04 07:12 UTC
Labels: Feature, Triage
