### ISSUE TITLE
Poetry 1.0.0b4 breaks with Python 2.7.

### ISSUE THREAD

**Issue by KelSolaar** [python-poetry/poetry#1559] opened 2019-11-09 01:06 UTC
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 10.14.6 
- **Poetry version**: 1.0.0b4
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://github.com/colour-science/colour-demosaicing/blob/053eb2b31bcfa2a2a09545a2e866cddde9a6aea7/pyproject.toml 

## Issue

All my builds started to break today with 1.0.0b4 and it turns out that there are issues with Python 2.7:

```bash
(colour-demosaicing-JqjoDa6b-py2.7) Kali:colour-demosaicing kelsolaar$ poetry install -vvv
Using virtualenv: /Users/kelsolaar/Library/Caches/pypoetry/virtualenvs/colour-demosaicing-JqjoDa6b-py2.7
Updating dependencies
Resolving dependencies...
   1: fact: colour-demosaicing is 0.1.5
   1: derived: colour-demosaicing
   ...
   0: Complete version solving took 17.056 seconds for 2 branches
   0: Resolved for branches: (>=2.7,<2.8), (>=3.5,<4.0)

Writing lock file

[InvalidRequirement]
Invalid requirement, parse error at "'and () o'"

Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/kelsolaar/.poetry/bin/poetry", line 14, in <module>
    main()
  File "/Users/kelsolaar/.poetry/lib/poetry/console/__init__.py", line 5, in main
    return Application().run()
  File "/Users/kelsolaar/.poetry/lib/poetry/_vendor/py2.7/clikit/console_application.py", line 139, in run
    trace.render(io, simple=isinstance(e, CliKitException))
  File "/Users/kelsolaar/.poetry/lib/poetry/_vendor/py2.7/clikit/ui/components/exception_trace.py", line 57, in render
    self._render_traceback(io, tb)
  File "/Users/kelsolaar/.poetry/lib/poetry/_vendor/py2.7/clikit/ui/components/exception_trace.py", line 67, in _render_traceback
    io.write_line("".join(traceback.format_list(frames)))
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/traceback.py", line 39, in format_list
    item = '  File "%s", line %d, in %s\n' % (filename,lineno,name)
TypeError: %d format: a number is required, not str
(colour-demosaicing-JqjoDa6b-py2.7) Kali:colour-demosaicing kelsolaar$ poetry install -vv
Using virtualenv: /Users/kelsolaar/Library/Caches/pypoetry/virtualenvs/colour-demosaicing-JqjoDa6b-py2.7
Installing dependencies from lock file

[ParseException]
Expected stringEnd, found u'a'  (at char 24), (line:1, col:25)

Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/kelsolaar/.poetry/bin/poetry", line 14, in <module>
    main()
  File "/Users/kelsolaar/.poetry/lib/poetry/console/__init__.py", line 5, in main
    return Application().run()
  File "/Users/kelsolaar/.poetry/lib/poetry/_vendor/py2.7/clikit/console_application.py", line 139, in run
    trace.render(io, simple=isinstance(e, CliKitException))
  File "/Users/kelsolaar/.poetry/lib/poetry/_vendor/py2.7/clikit/ui/components/exception_trace.py", line 57, in render
    self._render_traceback(io, tb)
  File "/Users/kelsolaar/.poetry/lib/poetry/_vendor/py2.7/clikit/ui/components/exception_trace.py", line 67, in _render_traceback
    io.write_line("".join(traceback.format_list(frames)))
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/traceback.py", line 39, in format_list
    item = '  File "%s", line %d, in %s\n' % (filename,lineno,name)
TypeError: %d format: a number is required, not str
```

My `poetry.lock` file is here: https://filebin.net/gprt82f9bw1b3cyh

**Comment by finswimmer** [comment] 2020-02-02 19:20
Hello @KelSolaar,

I'm not able to reproduce your issue with poetry 1.0.3. Instead I'm having the problem as in #1963.

I will close this one, because it looks like the original issue has been solved in the meantime. If you disagree just leave a comment.

fin swimmer

**Closed by finswimmer** 2020-02-02 19:20 UTC
Labels: Bug
