### ISSUE TITLE
pip install throws ValueError when installing a package built with poetry

### ISSUE THREAD

**Issue by orlevii** [python-poetry/poetry#3419] opened 2020-11-25 16:56 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOS (Catalina)
- **Poetry version**: 1.1.4

## Issue

I'm experimenting with monorepos, and I want to manage multiple packages under the same git repository.
Because of that, I want all of them to have the same dev-dependencies. so I decided to add another package for the common stuff.

This is my `pyproject.toml`:

```toml
[tool.poetry]
name = "data-tracker"
version = "0.1.0a"
description = ""
authors = ["Or Levi <orlevi128@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6.1"
pandas = { version = "1.*", optional = true }

[tool.poetry.dev-dependencies]
common-dev = { path = "../common-dev", develop = true }

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```
As you can see, `common-dev` is a path dependency under the `dev-dependencies` section.

I want to install this package with pip, so I built it using `poetry build` command, nothing special here.

I tried installing the `.whl` file - everything works as expected

But when I tried installing the `tar.gz` I get the following message:

```
Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    Complete output from command /Users/or.levi/temp/poetry_bug/venv/bin/python3 /Users/or.levi/temp/poetry_bug/venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/fg/0l5kn8yx7z39kpcj9ryh08wm0000gn/T/tmpojun4eav:
    Traceback (most recent call last):
      File "/Users/or.levi/temp/poetry_bug/venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
        main()
      File "/Users/or.levi/temp/poetry_bug/venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/Users/or.levi/temp/poetry_bug/venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 69, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/private/var/folders/fg/0l5kn8yx7z39kpcj9ryh08wm0000gn/T/pip-build-env-ok89w91y/overlay/lib/python3.7/site-packages/poetry/core/masonry/api.py", line 34, in prepare_metadata_for_build_wheel
        poetry = Factory().create_poetry(Path(".").resolve())
      File "/private/var/folders/fg/0l5kn8yx7z39kpcj9ryh08wm0000gn/T/pip-build-env-ok89w91y/overlay/lib/python3.7/site-packages/poetry/core/factory.py", line 111, in create_poetry
        name, constraint, category="dev", root_dir=package.root_dir
      File "/private/var/folders/fg/0l5kn8yx7z39kpcj9ryh08wm0000gn/T/pip-build-env-ok89w91y/overlay/lib/python3.7/site-packages/poetry/core/factory.py", line 249, in create_dependency
        extras=constraint.get("extras", []),
      File "/private/var/folders/fg/0l5kn8yx7z39kpcj9ryh08wm0000gn/T/pip-build-env-ok89w91y/overlay/lib/python3.7/site-packages/poetry/core/packages/directory_dependency.py", line 36, in __init__
        raise ValueError("Directory {} does not exist".format(self._path))
    ValueError: Directory ../common-dev does not exist
```

Looks like poetry tries to resolve `common-dev` even though it's a dev-dependency.

(This error also occurs when trying to install from path)

**Comment by sinoroc** [comment] 2020-11-25 17:16
Sounds like https://github.com/python-poetry/poetry/issues/2174 to me. The potential fix https://github.com/python-poetry/poetry-core/pull/101 has been merged in _poetry-core_'s `master` branch. If you agree that it indeed might be the same root cause, would you mind trying the fix?

**Comment by orlevii** [comment] 2020-11-25 18:09
@sinoroc 
Thanks, it looks related.

How do I test this fix?

**Comment by sinoroc** [comment] 2020-11-25 18:56
> How do I test this fix?

I am not sure. Maybe in the `pyproject.toml`:

```
[build-system]
requires = ["poetry_core @ git+https://github.com/python-poetry/poetry.git"]
build-backend = "poetry.core.masonry.api"
```

**Comment by orlevii** [comment] 2020-11-25 19:30
@sinoroc 
Your suggestion works! 🎉 

So just need to wait for the next`poetry-core` version release.

**Comment by sinoroc** [comment] 2020-11-25 19:55
> Your suggestion works! tada
Great!

> So just need to wait for the next `poetry-core` version release.

You could comment on the PR and lobby for a new release of _poetry-core_. There were a couple of interesting fixes since _v1.0.0_.

**Comment by sinoroc** [comment] 2020-11-25 22:28
@orlevii Should we close this ticket as a duplicate of #2174 then?

**Closed** 2020-11-26 11:53 UTC
Labels: Bug, Triage
