### ISSUE TITLE
Poetry add git+ does not respect git repos default branch. Assumes master is default branch.

### ISSUE THREAD

**Issue by avnes** [python-poetry/poetry#4167] opened 2021-06-10 12:37 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS Big Sur 11.4. Darwin Kernel Version 20.5.0
- **Poetry version**: 1.1.6
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: N/A

## Issue
According to the https://python-poetry.org/docs/cli/ you can use `poetry add` with a git repo. I know it is possible to specify a branch or a tag in the call, but I had assumed that would not be needed if the default branch was something other than master. 

```
poetry add git+https://github.com/avnes/python-template-project.git


CalledProcessError

  Command '['git', '--git-dir', '/var/folders/x8/yxw7dnh10z57gqjpzr4bm55m0000gn/T/pypoetry-git-python-template-projecavjjt1j2/.git', '--work-tree', '/var/folders/x8/yxw7dnh10z57gqjpzr4bm55m0000gn/T/pypoetry-git-python-template-projecavjjt1j2', 'checkout', 'master']' returned non-zero exit status 1.

  at ~/.poetry/lib/poetry/utils/_compat.py:217 in run
      213│                 process.wait()
      214│                 raise
      215│             retcode = process.poll()
      216│             if check and retcode:
    → 217│                 raise CalledProcessError(
      218│                     retcode, process.args, output=stdout, stderr=stderr
      219│                 )
      220│         finally:
      221│             # None because our context manager __exit__ does not use them.
```

### Steps to reproduce:

1. poetry add git+https://github.com/avnes/python-template-project.git (will fail becase the default branch is main instead of master)
2. poetry add git+https://github.com/avnes/python-template-project.git#main works fine. So minor issue, but a bit annoying.

**Comment by kyleflan** [comment] 2021-06-18 21:41
The workaround above is fine for a single dependency, but in the event where a dependency itself has a dependency on a project in e.g. GitHub, there's not a straightforward solution to specify the branch for the sub-dependency. 

In my situation, the sub-dependency has the dependency defined in setup.py so I would have to modify that project's setup.py to use poetry.

Attempting to specify and install the dependencies separately, e.g define the sub-dependency first in pyproject.toml, install, then define the dependency in pyproject.toml fails with the following:

```
  SolverProblemError

  Because car (rev master) depends on engine (branch master)
   and poetry-demo depends on engine (branch main), car is forbidden.
  So, because poetry-demo depends on car (branch master), version solving failed.
```

**Comment by finswimmer** [comment] 2021-06-23 18:50
Hello,

this is a duplicate of https://github.com/python-poetry/poetry/issues/3366

fin swimmer

**Closed by finswimmer** 2021-06-23 18:50 UTC
Labels: Bug, Triage
