### ISSUE TITLE
poetry install uses an old pip version

### ISSUE THREAD

**Issue by tsvikas** [python-poetry/poetry#1661] opened 2019-12-02 14:36 UTC
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: ubuntu 19.04
- **Poetry version**: 0.12.17
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 
`poetry init --name foo --dependency tensorflow:==2.1.0rc0 --no-interaction && poetry install -vvv`

## Issue
It seems that `poetry install` creates an venv using python venv module. This module creates an environment with a pretty old pip version. The old pip version have some issues -- for example, it does not recognize `manylinux2010` packages at all.

This can lead to problems: a user can try to run a `poetry install` using a toml/lock files that was created in another computer. If, on the other computer, a user manually upgraded pip in the poetry venv, it will not be documented anywhere, leading to an inconsistent behavior (success at one case, fail on another), and hard to debug errors.
See that command above for an example.

Furthermore, no manual override exists (i.e. `poetry install --upgrade-pip-first`)

some valid solutions might be:

* always upgrade pip to most recent version, before any install/upgrade (but it means that future pip versions that breaks som API used by poetry will be problematic)
* always upgrade pip to a specific version, before any install/upgrade (but it means that users cannot use different pip versions, if they are needed for some reason)
* log the venv's pip version to the `poetry.lock` file, and ensure that this version is installed before any install/upgrade

**Comment by aloisklink** [comment] 2019-12-04 11:42
This sounds like a duplicate of issue #732, but that issue has a name that doesn't explain what the issue is, so I understand not being able to find it in a search.

#740 is trying to fix this, but there doesn't seem be any progress on that front. I think an ideal solution would be to specify the `pip` version in the `pyproject.toml`, but I've heard that isn't safe, since `pip` updates could change `pip`'s API and break poetry.

**Comment by tsvikas** [comment] 2019-12-11 16:42
Thanks, it does seems like a non-trivial issue!
I looked at #732 and #740, do we need to continue there?

To clarify, what i'm saying is that:

not allowing users to update pip for their created poetry-venvs will
* prevent users from installing some packages (i.e. tensorflow2) because they are uninstallable with old pip versions
* use less secure pip versions

however, allowing users to update pip manually will:
* create hard to debug problems, where `poetry install` fails for no clear reason

(N.B.: setting pip as dependency does not work at all - poetry just ignores it)

I believe **all of those issues are problematic to poetry mission** - so maybe let's try to brainstorm ideas that can overcome them, without "allowing it to be manipulated as a dependency [that] can lead to undesirable side effects"

**Comment by tsvikas** [comment] 2019-12-11 16:46
The fastest solution that comes to my mind is: 
find a version of pip that is:
* good, stable, secure
* can install all the problematic packages
* with the 'correct' API

and verify in poetry code that the venv is updated to this version before each poetry action (or, at least, after creation and before first package install)

**Comment by finswimmer** [comment] 2020-02-06 19:51
Closing this in favor of the discussion in #732.

Thanks a lot for your input!

fin swimmer

**Closed by finswimmer** 2020-02-06 19:51 UTC
Labels: Bug
