### ISSUE TITLE
poetry run does not support --src or other project structures

### ISSUE THREAD

**Issue by cpterry** [python-poetry/poetry#6029] opened 2022-07-18 15:07 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10
- **Poetry version**: 1.1.13
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/cpterry/0061b55fd13a16430c9250c4dd7ee05b

## Issue

`poetry run` does not support the structure of  `poetry new --src` or other project structures. It does not check the `packages` values. You can work around the issue by adding `src` but then installing the script after running `poetry build` will fail looking for the missing `src` folder.

So this works for `poetry build` but not `poetry run`:

```toml
packages = [
    { include = "example", from = "src" }
]

[tool.poetry.scripts]
myapp = "example:hello"
```

This works for `poetry run` but not `poetry build`:

```toml
packages = [
    { include = "example", from = "src" }
]

[tool.poetry.scripts]
myapp = "src.example:hello"
```

**Comment by cpterry** [comment] 2022-07-18 19:52
If I run `poetry install` with `myapp = "example:hello"` then running `poetry run myapp` will work.

But if set with `myapp = "src.example:hello"` it will without having to run `poetry install`. So what exactly does `poetry run` do? I mean for the installed case `poetry run myapp` it's calling the executable just the same as `poetry run python`. But if it's not installed then is `poetry` doing something else to handle  `myapp = "src.example:hello"` or is there something else going on?

**Comment by cpterry** [comment] 2022-07-18 20:18
I found the applicable code in [application.py](https://github.com/python-poetry/poetry/blob/master/src/poetry/console/application.py) and [run.py](https://github.com/python-poetry/poetry/blob/master/src/poetry/console/commands/run.py).

For `poetry run myapp` it first checks if myapp is one of the scripts. If so, it calls `self.run_script`. If not, it calls `self.env.execute`.

`run_script` includes code check `if self._module.is_in_src()` to add `src` to `sys.path`. This looks like it should handle this case and `poetry run` shouldn't require `poetry install` when using a `src` folder.

If there's something wrong in my setup that causes `self._module.is_in_src` to unexpectedly return `False`, that would cause the problem I'm seeing.

**Comment by cpterry** [comment] 2022-07-18 20:47
Over in `poetry-core`, [module](https://github.com/python-poetry/poetry-core/blob/main/src/poetry/core/masonry/utils/module.py) the `_in_src` is initialized as `False` and never set to `True` anywhere in the repo. So that's the root cause.

**Comment by finswimmer** [comment] 2022-07-20 16:06
Can you please prepare an example repo, that one can checkout and reproduce your problem?

I'm still unable to reproduce your problem (or I misunderstood it?). Poetry itself is using src layout as well without any problems.

**Comment by cpterry** [comment] 2022-07-20 17:56
I've prepared an [example repo](https://github.com/cpterry/poetry_run_src). Thank you for your attention to this.

**Comment by dimbleby** [comment] 2022-10-30 20:04
```
[tool.poetry.scripts]
myapp = "src.example:hello"
```
is wrong, `myapp = "example:hello"` is correct.

So far as I can see `module.is_in_src()` always returns `False`, I find no mechanism to make it do anything else.  So that looks completely pointless.

However in general you shouldn't expect to be able to run a script that's defined by your project without first installing your project (eg none of the dependencies will yet be available).  So I'm not seeing any supported use case that is actually broken.

ie this

> But if set with myapp = "src.example:hello" it will without having to run poetry install. 

was just lucky.

**Comment by finswimmer** [comment] 2023-01-20 07:53
Hello @cpterry,

you haven't come back to this issue for a long while. So I assume this is solved in the meantime and I can close this ticket.

Feel free to leave a comment if you disagree.

fin swimmer

**Closed by finswimmer** 2023-01-20 07:53 UTC
Labels: kind/bug, status/triage, status/waiting-on-response
