### ISSUE TITLE
 poetry lock --check does not reflect directory packages changes

### ISSUE THREAD

**Issue by coffinmatician** [python-poetry/poetry#7209] opened 2022-12-16 22:48 UTC
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request
`poetry lock --check` falsely succeeds if `path` dependencies change when it should fail. This is a similar issue to https://github.com/python-poetry/poetry/issues/3783. I'm not sure if the fix involves changing how the `metadata.content-hash` in poetry.lock is calculated to include `path` dependencies, or if it is preferable to instead check if the solution is valid against the current set of version requirements, and to ignore, or remove the `metadata.content-hash`. I may be willing to help out if I could receive guidance on the desired kind of change.

**Comment by radoering** [comment] 2022-12-17 05:31
I think this is out of scope because `poetry lock --check` only checks if poetry.lock has been created from the current pyproject.toml. Extending `poetry lock --check` will make it significantly slower and quite similar to `poetry lock --no-update`. If you want to detect changes of path dependencies, you'll have to run `poetry lock --no-update` and check if the lock file changed.

**Comment by radoering** [comment] 2022-12-17 08:11
If I remember correctly, the `content-hash` only considers the content of pyproject.toml at the moment. That includes all types of dependencies. If I understand correctly, in your case the line in the pyproject.toml referring to a directory dependency does not change but some content of the referenced directory (the pyproject.toml file?). By the way, a directory dependency does not necessarily have a pyproject.toml file.

**Comment by neersighted** [comment] 2022-12-19 14:23
I'm closing this as the current behavior is by design, and there is no way to make it work as you want as gathering metadata is an inherently expensive operation.

**Closed by neersighted** 2022-12-19 14:23 UTC
Labels: kind/feature, status/triage
