### ISSUE TITLE
consider retrying 500 errors on poetry install

### ISSUE THREAD

**Issue by novas0x2a** [python-poetry/poetry#7679] opened 2023-03-18 18:58 UTC
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request

It's certainly perfectly normal to avoid retrying http 500s, but on the modern internet 500s tend to be extremely transient, so I was wondering if you'd consider permitting 500s to retry. It looks like, currently, the [uploader retries](https://github.com/python-poetry/poetry/blob/cbfdc628df931bafb3f4c042f6d560df124d7ad6/src/poetry/publishing/uploader.py#L71) 500--503, and the [authenticator retries](https://github.com/python-poetry/poetry/blob/cbfdc628df931bafb3f4c042f6d560df124d7ad6/src/poetry/utils/authenticator.py#L262) 502--504. Was this difference intentional?

There is actually a PR that aligns them, though it hasn't seen much attention, I think: https://github.com/python-poetry/poetry/pull/7072

**Comment by dimbleby** [comment] 2023-03-18 19:05
this is a duplicate of #7072, as you have pointed out yourself. 

(I would agree that the backlog of PRs not getting attention is a sad thing: but I don't expect that duplicating PRs with issues will help)

**Comment by novas0x2a** [comment] 2023-03-18 19:09
Yeah, sorry, a lot of projects won't look at PRs unless there's an associated issue, wasn't sure if that was the case here.

**Comment by nejch** [comment] 2023-03-28 08:01
Hey folks, I'm the author of that PR. I'll try to get to a windows machine so I can reproduce the Windows CI failures (or maybe rebasing will help already). 

Maybe once the CI is green, it'll get more attention from maintainers. I'd be keen to get that merged of course as well :)

**Closed** 2023-04-04 08:29 UTC
Labels: kind/feature, status/triage
