### ISSUE TITLE
Cannot install package from git on Windows if repository contains symlinks

### ISSUE THREAD

**Issue by bruchar1** [python-poetry/poetry#7798] opened 2023-04-14 12:55 UTC
`poetry add git+https://github.com/mesonbuild/meson.git` does not work on Windows, because it tries to create a symlink.

However, I can git clone this repository with no problems, and I can install it with pip with no problems (`pip install git+https://github.com/mesonbuild/meson.git`).

This was reported in #6246. However, I do think this is a poetry bug, since pip can manage it with no problems.

**Comment by dimbleby** [comment] 2023-04-14 13:03
you didn't provide output, so no-one can see what the problem is.

If this is truly a duplicate of #6246 then it can be closed for the same reasons that one is closed, TLDR being that if a fix can be made it must be made in dulwich so please raise the issue there.

**Comment by bruchar1** [comment] 2023-04-14 13:07
> λ poetry add git+https://github.com/mesonbuild/meson.git
> Creating virtualenv mt-fT1b7t6V-py3.10 in C:\Users\charles.brunet\AppData\Local\pypoetry\Cache\virtualenvs
> 
> [WinError 1314] Le client ne dispose pas d’un privilège nécessaire: '../Cellar/boost/0.3.0/include/boost' -> 'C:\\Users\\charles.brunet\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\mt-fT1b7t6V-py3.10\\src\\meson\\test cases\\frameworks\\35 boost symlinks\\boost\\include\\boost'

The message is in French, but it means: "Client has no required privileges".

This has nothing to do with dulwich, it is simply a different example of the same symptoms.
It cannot be solved in meson repo, because those symlinks are needed for testing.

**Comment by dimbleby** [comment] 2023-04-14 13:10
> It cannot be solved in meson repo

no-one suggested that.

dulwich is poetry's default git client. If you provided output with `-vvv` as the issue template asks, I expect you would see that this failure is raised from that library.

**Comment by clintonroy** [comment] 2023-04-14 13:10
I'm not a windows person, but i think regular users can't make symlinks on windows, hence the permissions error. What does the git checkout do? make the symlink? resolve it? elide it?

**Comment by bruchar1** [comment] 2023-04-14 13:20
Sorry for the confusion. I didn't realized what dulwich was...

Yes, symlinks on Windows require elevated privileges.

git writes a text file containing the path pointed by the symlink.

**Comment by jelmer** [comment] 2023-04-27 14:36
This should be resolved by https://github.com/jelmer/dulwich/pull/1171

**Comment by abn** [comment] 2024-11-16 00:33
This should be resolved now as the dulwich version has been updated.

**Closed by abn** 2024-11-16 00:33 UTC
Labels: kind/bug, status/triage, area/windows, area/vcs
