### ISSUE TITLE
`setuptool_scm` is being accessed

### ISSUE THREAD

**Issue by jjfantini** [python-poetry/poetry#8476] opened 2023-09-27 16:05 UTC
- **Poetry version**: 
- **Python version**: 
- **OS version and name**: 
- **pyproject.toml**: 

- [x ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

=================== DEBUG INFO ===============
Poetry
Version: 1.6.1
Python:  3.10.8

Virtualenv
Python:         3.10.8
Implementation: CPython
Path:           C:\Users\jjfan\PYTHON-PKG_WD\humbl-data\obb
Executable:     C:\Users\jjfan\PYTHON-PKG_WD\humbl-data\obb\python.exe
Valid:          True

System
Platform:   win32
OS:         nt
Python:     3.10.8
Path:       C:\Users\jjfan\PYTHON-PKG_WD\humbl-data\obb
Executable: C:\Users\jjfan\PYTHON-PKG_WD\humbl-data\obb\python.exe
======================== ===================

I am running into an error where setuptools_scm is saying that it doesn't have any settings specified in the `pyproject.toml` file. I am not using `setuptools` but I am using poetry. 

I have done a fresh install of my conda environment to make sure there are no conflicts, but as soon as I write poetry on the CLI, this error comes back up. I am not sure where it is coming from, this should not be the case. 

![poetry_error](https://github.com/python-poetry/poetry/assets/63276164/84565dc6-5ca0-4701-8e83-83d4b5c1c17a)

**Comment by dimbleby** [comment] 2023-09-27 17:12
poetry doesn't have anything to do with setuptools_scm: I very much doubt that this is a poetry bug.

please provide a way to reproduce.

**Comment by jjfantini** [comment] 2023-09-27 17:41
looking into it...

**Comment by thomasSve** [comment] 2023-09-28 12:47
I'm having the same issue, looks like a new release of setuptools_scm had a bug in it: https://github.com/pypa/setuptools_scm/issues/938

**Comment by jjfantini** [comment] 2023-09-28 16:03
Yeah, poetry still works flawlessly, but when I run `poetry` for some reason setuptools is being called, did you fix by just downgrading? @thomasSve

**Comment by thomasSve** [comment] 2023-09-28 16:20
I uninstalled `matplotlib` which I believe has `setuptools_scm` as a dependency. Not having `setuptools_scm` installed fixed it for me

**Comment by Secrus** [comment] 2023-09-29 08:52
Poetry doesn't have `setuptools_scm` anywhere in it's dependency tree and your investigation pointed out that it's an external issue. Closing.

**Closed by Secrus** 2023-09-29 08:52 UTC
Labels: kind/bug, status/triage
