### ISSUE TITLE
Poetry changes sys.argv[0]?

### ISSUE THREAD

**Issue by probablykasper** [python-poetry/poetry#480] opened 2018-10-07 15:46 UTC
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Question

Hi. For the help menus in my CLI scripts, I like to print usage instructions like this:
```
print("Usage:")
print("    "+sys.argv[0]+" <command> [options]")
```
But Poetry seems to change sys.argv[0] to the full path of the script, instead of keeping what the user actually typed in. Why? Is there any way around this?

**Comment by SpectralKH** [comment] 2018-10-07 20:36
@fridex That doesn't really fix the problem. If the user did type in the full path with that code, he would only get the basename.

**Comment by fridex** [comment] 2018-10-07 20:39
Ah, OK. You want to replicate the whole invocation. That makes sense :+1:

**Comment by SpectralKH** [comment] 2018-10-07 20:40
@fridex Correct :)

**Comment by chdsbd** [comment] 2019-11-13 19:50
This is still an issue. I think it relates to #965.

**Comment by finswimmer** [comment] 2022-07-01 18:57
Duplicate of https://github.com/python-poetry/poetry/issues/965

**Closed by finswimmer** 2022-07-01 18:57 UTC
Labels: CLI
