### ISSUE TITLE
Cannot install ccxt

### ISSUE THREAD

**Issue by miracle2k** [python-poetry/poetry#435] opened 2018-09-14 23:30 UTC
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**:  MacOS
- **Poetry version**: Poetry 0.11.5

## Issue

```
$ poetry -vvvv add ccxt
Creating virtualenv test2-py3.7 in /Users/michael/Library/Caches/pypoetry/virtualenvs
Using virtualenv: /Users/michael/Library/Caches/pypoetry/virtualenvs/test2-py3.7
PyPI: 4099 packages found for ccxt *
Using version ^1.17 for ccxt

Updating dependencies
Resolving dependencies...
   1: fact: test2 is 0.1.0
   1: derived: test2
   1: fact: test2 depends on ccxt (^1.17)
   1: fact: test2 depends on pytest (^3.0)
   1: selecting test2 (0.1.0)
   1: derived: pytest (^3.0)
   1: derived: ccxt (^1.17)
PyPI: 37 packages found for pytest >=3.0,<4.0
PyPI: 286 packages found for ccxt >=1.17,<2.0
   1: fact: ccxt (1.17.293) depends on web3 (4.4.1)
   1: fact: ccxt (1.17.293) depends on yarl (1.1.0)
   1: fact: ccxt (1.17.293) depends on aiodns (1.1.1)
   1: fact: ccxt (1.17.293) depends on aiohttp (>=3.0.1)
   1: fact: ccxt (1.17.293) depends on requests (>=2.18.4)
   1: fact: ccxt (1.17.293) depends on certifi (>=2018.1.18)
   1: selecting ccxt (1.17.293)
   1: derived: certifi (>=2018.1.18)
   1: derived: requests (>=2.18.4)
   1: derived: aiohttp (>=3.0.1)
   1: derived: aiodns (1.1.1)
   1: derived: yarl (1.1.0)
   1: derived: web3 (4.4.1)
PyPI: No release information found for certifi-0, skipping
PyPI: 4 packages found for certifi >=2018.1.18
PyPI: No release information found for requests-0.0.1, skipping
PyPI: No release information found for requests-0.12.01, skipping
PyPI: No release information found for requests-2.15.0, skipping
PyPI: 3 packages found for requests >=2.18.4
PyPI: 29 packages found for aiohttp >=3.0.1
PyPI: 1 packages found for aiodns 1.1.1
PyPI: No release information found for yarl-0.5.0b0, skipping
PyPI: No release information found for yarl-0.5.0b1, skipping
PyPI: 1 packages found for yarl 1.1.0
PyPI: No release information found for web3-0.1.0, skipping
PyPI: 1 packages found for web3 4.4.1
   1: fact: aiodns (1.1.1) depends on pycares (>=1.0.0)
   1: fact: aiodns (1.1.1) depends on trollius (*)
   1: fact: aiodns (1.1.1) depends on asyncio (*)
   1: selecting aiodns (1.1.1)
   1: derived: asyncio (*)
   1: derived: trollius (*)
   1: derived: pycares (>=1.0.0)
PyPI: 7 packages found for asyncio *
PyPI: 18 packages found for trollius *
PyPI: 7 packages found for pycares >=1.0.0
   1: fact: yarl (1.1.0) depends on multidict (>=4.0)
   1: fact: yarl (1.1.0) depends on idna (>=2.0)
   1: selecting yarl (1.1.0)
   1: derived: idna (>=2.0)
   1: derived: multidict (>=4.0)
PyPI: No release information found for idna-0.1, skipping
PyPI: 8 packages found for idna >=2.0
PyPI: No release information found for multidict-0.0.1, skipping
PyPI: 48 packages found for multidict >=4.0
   1: fact: web3 (4.4.1) depends on eth-abi (>=1.1.1,<2)
   1: fact: web3 (4.4.1) depends on eth-account (>=0.2.1,<0.3.0)
   1: fact: web3 (4.4.1) depends on eth-utils (>=1.0.1,<2.0.0)
   1: fact: web3 (4.4.1) depends on hexbytes (>=0.1.0,<1.0.0)
   1: fact: web3 (4.4.1) depends on lru-dict (>=1.1.6,<2.0.0)
   1: fact: web3 (4.4.1) depends on eth-hash (*)
   1: fact: web3 (4.4.1) depends on requests (>=2.16.0,<3.0.0)
   1: fact: web3 (4.4.1) depends on websockets (>=5.0.1,<6.0.0)
   1: fact: web3 (4.4.1) depends on cytoolz (>=0.9.0,<1.0.0)
   1: fact: web3 (4.4.1) depends on toolz (>=0.9.0,<1.0.0)
   1: fact: web3 (4.4.1) depends on pypiwin32 (>=223)
   1: selecting web3 (4.4.1)
   1: derived: pypiwin32 (>=223)
   1: derived: toolz (>=0.9.0,<1.0.0)
   1: derived: cytoolz (>=0.9.0,<1.0.0)
   1: derived: websockets (>=5.0.1,<6.0.0)
   1: derived: requests (>=2.16.0,<3.0.0)
   1: derived: eth-hash (*)
   1: derived: lru-dict (>=1.1.6,<2.0.0)
   1: derived: hexbytes (>=0.1.0,<1.0.0)
   1: derived: eth-utils (>=1.0.1,<2.0.0)
   1: derived: eth-account (>=0.2.1,<0.3.0)
   1: derived: eth-abi (>=1.1.1,<2)
PyPI: No release information found for requests-0.0.1, skipping
PyPI: No release information found for requests-0.12.01, skipping
PyPI: No release information found for requests-2.15.0, skipping
PyPI: 3 packages found for requests >=2.18.4,<3.0.0
PyPI: 1 packages found for pypiwin32 >=223
PyPI: 1 packages found for toolz >=0.9.0,<1.0.0
PyPI: No release information found for cytoolz-0.5.3, skipping
PyPI: 2 packages found for cytoolz >=0.9.0,<1.0.0
PyPI: No release information found for websockets-0.1, skipping
PyPI: 1 packages found for websockets >=5.0.1,<6.0.0
PyPI: 9 packages found for eth-hash *
PyPI: 1 packages found for lru-dict >=1.1.6,<2.0.0
PyPI: 1 packages found for hexbytes >=0.1.0,<1.0.0
PyPI: 7 packages found for eth-utils >=1.0.1,<2.0.0
PyPI: 3 packages found for eth-account >=0.2.1,<0.3.0
PyPI: 5 packages found for eth-abi >=1.1.1,<2
   1: fact: pypiwin32 (223) depends on pywin32 (>=223)
   1: selecting pypiwin32 (223)
   1: derived: pywin32 (>=223)
PyPI: No release information found for pywin32-210, skipping
PyPI: No release information found for pywin32-214, skipping
PyPI: 1 packages found for pywin32 >=223
   1: selecting toolz (0.9.0)
   1: selecting websockets (5.0.1)
   1: selecting lru-dict (1.1.6)
   1: fact: hexbytes (0.1.0) depends on eth-utils (>=1.0.1,<2.0.0)
   1: selecting hexbytes (0.1.0)
   1: selecting pywin32 (223)
   1: fact: cytoolz (0.9.0.1) depends on toolz (>=0.8.0)
   1: selecting cytoolz (0.9.0.1)
   1: fact: requests (2.19.1) depends on certifi (>=2017.4.17)
   1: fact: requests (2.19.1) depends on urllib3 (>=1.21.1,<1.24)
   1: fact: requests (2.19.1) depends on idna (>=2.5,<2.8)
   1: fact: requests (2.19.1) depends on chardet (>=3.0.2,<3.1.0)
   1: selecting requests (2.19.1)
   1: derived: chardet (>=3.0.2,<3.1.0)
   1: derived: idna (>=2.5,<2.8)
   1: derived: urllib3 (>=1.21.1,<1.24)
PyPI: No release information found for idna-0.1, skipping
PyPI: 3 packages found for idna >=2.5,<2.8
PyPI: 3 packages found for chardet >=3.0.2,<3.1.0
PyPI: No release information found for urllib3-0.3, skipping
PyPI: No release information found for urllib3-0.3.1, skipping
PyPI: No release information found for urllib3-0.4.0, skipping
PyPI: No release information found for urllib3-0.4.1, skipping
PyPI: 3 packages found for urllib3 >=1.21.1,<1.24
   1: selecting idna (2.7)
   1: fact: eth-account (0.2.3) depends on attrdict (>=2.0.0,<3)
   1: fact: eth-account (0.2.3) depends on eth-keyfile (>=0.5.0,<0.6.0)
   1: fact: eth-account (0.2.3) depends on eth-keys (>=0.2.0b3,<0.3.0)
   1: fact: eth-account (0.2.3) depends on eth-utils (>=1.0.2,<2)
   1: fact: eth-account (0.2.3) depends on hexbytes (>=0.1.0,<1)
   1: fact: eth-account (0.2.3) depends on eth-rlp (>=0.1.2,<1)
   1: selecting eth-account (0.2.3)
   1: derived: eth-rlp (>=0.1.2,<1)
   1: derived: eth-utils (>=1.0.2,<2)
   1: derived: eth-keys (>=0.2.0b3,<0.3.0)
   1: derived: eth-keyfile (>=0.5.0,<0.6.0)
   1: derived: attrdict (>=2.0.0,<3)
PyPI: 6 packages found for eth-utils >=1.0.2,<2.0.0
PyPI: 1 packages found for eth-rlp >=0.1.2,<1
PyPI: 1 packages found for eth-keys >=0.2.0b3,<0.3.0
PyPI: 2 packages found for eth-keyfile >=0.5.0,<0.6.0
PyPI: 1 packages found for attrdict >=2.0.0,<3
   1: fact: eth-rlp (0.1.2) depends on eth-utils (>=1.0.1,<2)
   1: fact: eth-rlp (0.1.2) depends on hexbytes (>=0.1.0,<1)
   1: fact: eth-rlp (0.1.2) depends on rlp (>=0.6.0,<2)
   1: selecting eth-rlp (0.1.2)
   1: derived: rlp (>=0.6.0,<2)
PyPI: 10 packages found for rlp >=0.6.0,<2
   1: fact: eth-keys (0.2.0b3) depends on eth-utils (>=1.0.0-beta.2,<2.0.0)
   1: fact: eth-keys (0.2.0b3) depends on cytoolz (>=0.9.0,<1.0.0)
   1: selecting eth-keys (0.2.0b3)
   1: fact: attrdict (2.0.0) depends on six (*)
   1: selecting attrdict (2.0.0)
   1: derived: six (*)
PyPI: 23 packages found for six *
   1: fact: eth-keyfile (0.5.1) depends on eth-utils (>=1.0.0-beta.1,<2.0.0)
   1: fact: eth-keyfile (0.5.1) depends on eth-keys (>=0.1.0-beta.4,<1.0.0)
   1: fact: eth-keyfile (0.5.1) depends on cytoolz (>=0.9.0,<1.0.0)
   1: fact: eth-keyfile (0.5.1) depends on pycryptodome (>=3.4.7,<4.0.0)
   1: selecting eth-keyfile (0.5.1)
   1: derived: pycryptodome (>=3.4.7,<4.0.0)
PyPI: 12 packages found for pycryptodome >=3.4.7,<4.0.0
   1: selecting chardet (3.0.4)
   1: selecting urllib3 (1.23)
   1: selecting certifi (2018.8.24)
   1: fact: eth-abi (1.2.0) depends on parsimonious (0.8.0)
   1: fact: eth-abi (1.2.0) depends on eth-typing (<=2)
   1: fact: eth-abi (1.2.0) depends on eth-utils (>=1.2.0,<2.0.0)
   1: selecting eth-abi (1.2.0)
   1: derived: eth-utils (>=1.2.0,<2.0.0)
   1: derived: eth-typing (<=2)
   1: derived: parsimonious (0.8.0)
PyPI: 2 packages found for eth-utils >=1.2.0,<2.0.0
PyPI: 7 packages found for eth-typing <=2
PyPI: 1 packages found for parsimonious 0.8.0
   1: fact: parsimonious (0.8.0) depends on six (>=1.9.0)
   1: selecting parsimonious (0.8.0)
   1: derived: six (>=1.9.0)
PyPI: 3 packages found for six >=1.9.0
   1: fact: eth-utils (1.2.1) depends on toolz (>0.8.2,<1)
   1: fact: eth-utils (1.2.1) depends on cytoolz (>=0.8.2,<1.0.0)
   1: fact: eth-utils (1.2.1) depends on eth-typing (>=1.3.0,<2.0.0)
   1: fact: eth-utils (1.2.1) depends on eth-hash (>=0.1.0,<1.0.0)
   1: selecting eth-utils (1.2.1)
   1: derived: eth-hash (>=0.1.0,<1.0.0)
   1: derived: eth-typing (>=1.3.0,<2.0.0)
PyPI: 6 packages found for eth-hash >=0.1.0,<1.0.0
PyPI: 1 packages found for eth-typing >=1.3.0,<2.0.0
   1: selecting eth-typing (1.3.0)
   1: selecting six (1.11.0)
   1: selecting eth-hash (0.2.0)
   1: selecting asyncio (3.4.3)
   1: selecting pycares (2.3.0)
   1: fact: rlp (1.0.2) depends on eth-utils (>=1.0.2,<2)
   1: selecting rlp (1.0.2)
   1: selecting pycryptodome (3.6.6)
   1: fact: trollius (2.2) depends on six (*)
   1: fact: trollius (2.2) depends on futures (*)
   1: selecting trollius (2.2)
   1: derived: futures (*)
PyPI: 21 packages found for futures *
   1: selecting futures (3.2.0)
   1: fact: aiohttp (3.4.4) depends on idna-ssl (>=1.0)
   1: fact: aiohttp (3.4.4) depends on yarl (>=1.0,<2.0)
   1: fact: aiohttp (3.4.4) depends on async-timeout (>=3.0,<4.0)
   1: fact: aiohttp (3.4.4) depends on multidict (>=4.0,<5.0)
   1: fact: aiohttp (3.4.4) depends on chardet (>=2.0,<4.0)
   1: fact: aiohttp (3.4.4) depends on attrs (>=17.3.0)
   1: selecting aiohttp (3.4.4)
   1: derived: attrs (>=17.3.0)
   1: derived: multidict (>=4.0,<5.0)
   1: derived: async-timeout (>=3.0,<4.0)
   1: derived: idna-ssl (>=1.0)
PyPI: No release information found for multidict-0.0.1, skipping
PyPI: 48 packages found for multidict >=4.0,<5.0
PyPI: 4 packages found for attrs >=17.3.0
PyPI: 1 packages found for async-timeout >=3.0,<4.0
PyPI: 3 packages found for idna-ssl >=1.0
   1: selecting async-timeout (3.0.0)
   1: fact: idna-ssl (1.1.0) depends on idna (>=2.0)
   1: selecting idna-ssl (1.1.0)
   1: selecting attrs (18.2.0)
   1: fact: pytest (3.8.0) depends on colorama (*)
   1: fact: pytest (3.8.0) depends on pathlib2 (>=2.2.0)
   1: fact: pytest (3.8.0) depends on funcsigs (*)
   1: fact: pytest (3.8.0) depends on pluggy (>=0.7)
   1: fact: pytest (3.8.0) depends on atomicwrites (>=1.0)
   1: fact: pytest (3.8.0) depends on more-itertools (>=4.0.0)
   1: fact: pytest (3.8.0) depends on attrs (>=17.4.0)
   1: fact: pytest (3.8.0) depends on six (>=1.10.0)
   1: fact: pytest (3.8.0) depends on py (>=1.5.0)
   1: selecting pytest (3.8.0)
   1: derived: py (>=1.5.0)
   1: derived: more-itertools (>=4.0.0)
   1: derived: atomicwrites (>=1.0)
   1: derived: pluggy (>=0.7)
   1: derived: funcsigs (*)
   1: derived: pathlib2 (>=2.2.0)
   1: derived: colorama (*)
PyPI: No release information found for py-0.8.0-alpha2, skipping
PyPI: No release information found for py-0.9.0, skipping
PyPI: No release information found for py-1.4.32.dev1, skipping
PyPI: 5 packages found for py >=1.5.0
PyPI: 5 packages found for more-itertools >=4.0.0
PyPI: 5 packages found for atomicwrites >=1.0
PyPI: 1 packages found for pluggy >=0.7
PyPI: 7 packages found for funcsigs *
PyPI: 4 packages found for pathlib2 >=2.2.0
PyPI: 37 packages found for colorama *
   1: selecting pluggy (0.7.1)
   1: fact: pathlib2 (2.3.2) depends on scandir (*)
   1: fact: pathlib2 (2.3.2) depends on six (*)
   1: selecting pathlib2 (2.3.2)
   1: derived: scandir (*)
PyPI: 15 packages found for scandir *
   1: selecting py (1.6.0)
   1: fact: more-itertools (4.3.0) depends on six (>=1.0.0,<2.0.0)
   1: selecting more-itertools (4.3.0)
   1: selecting atomicwrites (1.2.1)
   1: fact: funcsigs (1.0.2) depends on ordereddict (*)
   1: selecting funcsigs (1.0.2)
   1: derived: ordereddict (*)
PyPI: 2 packages found for ordereddict *
   1: selecting ordereddict (1.1)
   1: selecting scandir (1.9.0)
   1: selecting colorama (0.3.9)
   1: selecting multidict (4.4.0)
   1: Version solving took 1.547 seconds.
   1: Tried 1 solutions.

[ValueError]
Could not parse version constraint: <empty>

Exception trace:
 /Users/michael/.pyenv/versions/3.7.0/lib/python3.7/site-packages/poetry/_vendor/cleo/application.py in run() at line 94
   status_code = self.do_run(input_, output_)
 /Users/michael/.pyenv/versions/3.7.0/lib/python3.7/site-packages/poetry/console/application.py in do_run() at line 88
   return super(Application, self).do_run(i, o)
 /Users/michael/.pyenv/versions/3.7.0/lib/python3.7/site-packages/poetry/_vendor/cleo/application.py in do_run() at line 197
   status_code = command.run(input_, output_)
 /Users/michael/.pyenv/versions/3.7.0/lib/python3.7/site-packages/poetry/console/commands/command.py in run() at line 77
   return super(BaseCommand, self).run(i, o)
 /Users/michael/.pyenv/versions/3.7.0/lib/python3.7/site-packages/poetry/_vendor/cleo/commands/base_command.py in run() at line 146
   status_code = self.execute(input_, output_)
 /Users/michael/.pyenv/versions/3.7.0/lib/python3.7/site-packages/poetry/_vendor/cleo/commands/command.py in execute() at line 107
   return self.handle()
 /Users/michael/.pyenv/versions/3.7.0/lib/python3.7/site-packages/poetry/console/commands/add.py in handle() at line 139
   status = installer.run()
 /Users/michael/.pyenv/versions/3.7.0/lib/python3.7/site-packages/poetry/installation/installer.py in run() at line 76
   self._do_install(local_repo)
 /Users/michael/.pyenv/versions/3.7.0/lib/python3.7/site-packages/poetry/installation/installer.py in _do_install() at line 158
   ops = solver.solve(use_latest=self._whitelist)
 /Users/michael/.pyenv/versions/3.7.0/lib/python3.7/site-packages/poetry/puzzle/solver.py in solve() at line 31
   packages, depths = self._solve(use_latest=use_latest)
 /Users/michael/.pyenv/versions/3.7.0/lib/python3.7/site-packages/poetry/puzzle/solver.py in _solve() at line 132
   graph = self._build_graph(self._package, packages)
 /Users/michael/.pyenv/versions/3.7.0/lib/python3.7/site-packages/poetry/puzzle/solver.py in _build_graph() at line 233
   pkg, packages, graph, dependency, dep or dependency
 /Users/michael/.pyenv/versions/3.7.0/lib/python3.7/site-packages/poetry/puzzle/solver.py in _build_graph() at line 233
   pkg, packages, graph, dependency, dep or dependency
 /Users/michael/.pyenv/versions/3.7.0/lib/python3.7/site-packages/poetry/puzzle/solver.py in _build_graph() at line 233
   pkg, packages, graph, dependency, dep or dependency
 /Users/michael/.pyenv/versions/3.7.0/lib/python3.7/site-packages/poetry/puzzle/solver.py in _build_graph() at line 233
   pkg, packages, graph, dependency, dep or dependency
 /Users/michael/.pyenv/versions/3.7.0/lib/python3.7/site-packages/poetry/puzzle/solver.py in _build_graph() at line 168
   parse_constraint(previous["python_version"]).intersect(
 /Users/michael/.pyenv/versions/3.7.0/lib/python3.7/site-packages/poetry/semver/__init__.py in parse_constraint() at line 31
   constraint_objects.append(parse_single_constraint(and_constraints[0]))
 /Users/michael/.pyenv/versions/3.7.0/lib/python3.7/site-packages/poetry/semver/__init__.py in parse_single_constraint() at line 145
   raise ValueError("Could not parse version constraint: {}".format(constraint))

add [-D|--dev] [--git GIT] [--path PATH] [-E|--extras EXTRAS] [--optional] [--python PYTHON] [--platform PLATFORM] [--allow-prereleases] [--dry-run] [--] <name> (<name>)...
```

**Comment by sbdchd** [comment] 2019-02-07 03:33
I had a similar issue that was fixed by specifying a python version in my `pyproject.toml`.

```
poetry --version 
Poetry 0.11.0
```

**Comment by kierun** [comment] 2019-10-17 13:46
[This could be linked as well.](https://github.com/sdispater/poetry/issues/1475)

I tried setting a python version but it did not help.

**Comment by finswimmer** [comment] 2020-02-02 17:10
Hello,

I cannot reproduce it with poetry 1.0.3. So I will close this. Feel free to leave any comment if you disagree.

fin swimmer

**Closed by finswimmer** 2020-02-02 17:10 UTC
