### ISSUE TITLE
Local user configuration for dependencies

### ISSUE THREAD

**Issue by Leon0402** [python-poetry/poetry#7007] opened 2022-11-11 10:49 UTC
Hi, 

for development I sometimes need to to changes for the dependencies. For instance: 
- Change versions
- Change paths
- Use a local version of a package
... 

One example might be that I need a specific torch package:
```
torch = { path = "./packages/torch-1.12.0+cu116-cp38-cp38-linux_x86_64.whl" } 
```

It would be great if I could have a local file, which I can ignore in my gitignore, where I can override dependencies for my local machine. For instance the normal project would just have: 

````
torch = "^1.12.0"
````

which work most of the time. But if need for reasons another version (different os, different availability of hardware, performance reasons, personal preference) a local version I could just overwrite this without changing it in the file. I know there are "markers", which partially solve the problem. But in my experience it's not always worth it  or possible to specify all possibilities with complex markers.

**Comment by neersighted** [comment] 2022-11-11 17:04
Split duplicate of #1168 and #6409 -- I can tell you with confidence that we will not support any project files augmenting pyproject.toml, and that the format will stay declarative. Either issue has discussion of the direct problem you are trying to solve, as well as speculation on a design to realize them (though, no one is working on an implementation afaik).

**Closed by neersighted** 2022-11-11 17:04 UTC
Labels: kind/feature, status/triage
