### ISSUE TITLE
install-poetry.py breaks global installs

### ISSUE THREAD

**Issue by martinxsliu** [python-poetry/poetry#4279] opened 2021-07-13 02:38 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: linux debian slim
- **Poetry version**: 1.1.7
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: n/a

## Issue

Using the old `get-poetry.py` installer script to install Poetry, I can install projects globally by setting `poetry config virtualenvs.create false` (e.g. see https://github.com/python-poetry/poetry/issues/243). This is useful for installing projects in a Docker container.

Using the new `install-poetry.py` installer, it looks like the script creates a virtualenv at `${XDG_DATA_HOME}/pypoetry/venv` (`~/.local/share/pypoetry/venv` by default) inside of which Poetry is installed. Based on my understanding, this also means that projects will be installed within this venv instead of globally. I'm not sure if I'm missing something, but how can we do a global install with the new installer?

**Comment by martinxsliu** [comment] 2021-07-13 19:25
This is the same problem as https://github.com/python-poetry/poetry/issues/4187.

Feel free to close as duplicate, but I'm keeping it open for now as this issue is about global installs vs strictly about `virtualenvs.create` which may or may not be working as intended depending on how you look at it.

**Comment by finswimmer** [comment] 2021-07-14 17:20
Yes, this should be a duplicate of  #4187.

**Closed by finswimmer** 2021-07-14 17:20 UTC
Labels: Bug, Triage
