### ISSUE TITLE
Add section to Dependency Specification detailing `@` at notation

### ISSUE THREAD

**Issue by ucodery** [python-poetry/poetry#4539] opened 2021-09-21 23:23 UTC
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue
There exists not definition of what `@` does, either on its own, or in combination with other constraint symbols. As this has no meaning defined in PEP-440, a section describing the expected behavior and mapping it to more verbose constraints would be helpful.

`poetry add --help` mentions this as a possible constraint with this one line
>     - A name and a constraint (requests@^2.23.0)
but otherwise there is no mention that `@` is valid, or in what combinations.

I will note `@local` is mentioned in contributing documentation and seems mostly self-explanatory.

**Comment by finswimmer** [comment] 2021-12-28 06:57
Duplicate of https://github.com/python-poetry/poetry/issues/3142

**Closed by finswimmer** 2021-12-28 06:57 UTC
Labels: Documentation, Triage
