### ISSUE TITLE
`poetry env use ...` doesn't work

### ISSUE THREAD

**Issue by simonrouse9461** [python-poetry/poetry#4530] opened 2021-09-21 00:37 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Red Hat Enterprise Linux Server 7.9 (Maipo)
- **Poetry version**: 1.1.8
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue

According to the documentation, if `python` is in my `$PATH`, I can use `poetry env use python` to switch to the environment associated with that python executable. However, it only gives me an error:
```python
$ which python
~/.conda/envs/deepgd/bin/python
$ poetry env use python -vvv
Skipping virtualenv creation, as specified in config file.

  Stack trace:

  6  ~/.conda/envs/deepgd/lib/python3.9/site-packages/clikit/console_application.py:131 in run
      129│             parsed_args = resolved_command.args
      130│ 
    → 131│             status_code = command.handle(parsed_args, io)
      132│         except KeyboardInterrupt:
      133│             status_code = 1

  5  ~/.conda/envs/deepgd/lib/python3.9/site-packages/clikit/api/command/command.py:120 in handle
      118│     def handle(self, args, io):  # type: (Args, IO) -> int
      119│         try:
    → 120│             status_code = self._do_handle(args, io)
      121│         except KeyboardInterrupt:
      122│             if io.is_debug():

  4  ~/.conda/envs/deepgd/lib/python3.9/site-packages/clikit/api/command/command.py:171 in _do_handle
      169│         handler_method = self._config.handler_method
      170│ 
    → 171│         return getattr(handler, handler_method)(args, io, self)
      172│ 
      173│     def __repr__(self):  # type: () -> str

  3  ~/.conda/envs/deepgd/lib/python3.9/site-packages/cleo/commands/command.py:92 in wrap_handle
       90│         self._command = command
       91│ 
    →  92│         return self.handle()
       93│ 
       94│     def handle(self):  # type: () -> Optional[int]

  2  ~/.conda/envs/deepgd/lib/python3.9/site-packages/poetry/console/commands/env/use.py:23 in handle
      21│             return
      22│ 
    → 23│         env = manager.activate(self.argument("python"), self._io)
      24│ 
      25│         self.line("Using virtualenv: {}".format(env.path))

  1  ~/.conda/envs/deepgd/lib/python3.9/site-packages/poetry/utils/env.py:405 in activate
       403│         # Activate
       404│         envs[base_env_name] = {"minor": minor, "patch": patch}
    →  405│         envs_file.write(envs)
       406│ 
       407│         return self.get(reload=True)

  FileNotFoundError

  [Errno 2] No such file or directory: '~/.cache/pypoetry/virtualenvs/envs.toml'

  at ~/.conda/envs/deepgd/lib/python3.9/site-packages/tomlkit/toml_file.py:23 in write
      19│         with io.open(self._path, encoding="utf-8") as f:
      20│             return loads(f.read())
      21│ 
      22│     def write(self, data):  # type: (TOMLDocument) -> None
    → 23│         with io.open(self._path, "w", encoding="utf-8") as f:
      24│             f.write(data.as_string())
      25│ 
```

**Comment by finswimmer** [comment] 2021-09-21 18:30
Hello @simonrouse9461,

can you please tell us how you installed poetry? I can't reproduce it until now.

Also note that setting `virtualenvs.create` to `false` (your output has the message "Skipping virtualenv creation, as specified in config file.") and using `poetry env use` doesn't make sense. Because `poetry env use` tells poetry which python interpreter should be used to create a venv.

fin swimmer

**Comment by simonrouse9461** [comment] 2021-09-21 18:52
> can you please tell us how you installed poetry?

I installed poetry through conda.

> Because poetry env use tells poetry which python interpreter should be used to create a venv.

I think my understanding of `python env use` is wrong. I thought it means "using the virtual environment associated with the given python executable".

By the way, how do I select which existing virtual environment to use? My current situation is, the system allocates a virtual environment for me after login, I need to use some executables inside that virtual environment. Additionally, for my project, I need to activate a conda environment, and I want to use poetry within my own conda environment. However, poetry ignores the conda environment as long as it sees the virtual environment. Is there a way I can tell poetry which environment to use?

**Comment by finswimmer** [comment] 2021-09-22 17:58
> I think my understanding of python env use is wrong. I thought it means "using the virtual environment associated with the given python executable".

My explanation was not complete here. It also means "using the virtual environment associated with the given python executable". But only if this venv was created by poetry itself and is therefore located under whatever is set in the `virtualenvs.path` config.

> By the way, how do I select which existing virtual environment to use?
If you mean a venv, that was not created by poetry, you have to activate the env by your self. This can be also a conda environment. poetry will detect that a venv is activated and will not try to create a new one (only exception: you are in the `base` conda environment)

**Comment by simonrouse9461** [comment] 2021-09-22 19:05
@finswimmer Thanks for you answer!
My problem is that if a venv and a conda env are both activated, then poetry will always choose venv over conda env. Is there a way to force poetry to use a certain environment under this circumstance?

**Comment by finswimmer** [comment] 2021-09-22 19:19
> Is there a way to force poetry to use a certain environment under this circumstance?

No, this is not possible. Why do you want to do this? Just activate only one isolated environment (conda or virtualenv) at a time. Mixing isolated envs seems very error-prone to me.

**Comment by simonrouse9461** [comment] 2021-09-22 22:17
> Mixing isolated envs seems very error-prone to me

Ok, I see. I think you are right. I can probably find a workaround.

However, I found `poetry env use system` also doesn't work. Here's what I tried:
```
$ poetry env info
Virtualenv
Python:         3.9.7
Implementation: CPython
Path:           NA

System
Platform: darwin
OS:       posix
Python:   /usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9
$ poetry env use system 
$ poetry add numpy 
Creating virtualenv deepgd-vKPGfjo2-py3.9 in /Users/chuhan/Library/Caches/pypoetry/virtualenvs
Using version ^1.21.2 for numpy
...
```

It is still creating a new venv even if I say `poetry env use system`.

**Comment by neersighted** [comment] 2022-09-05 17:33
@liudonghua123 When Poetry says it is using an environment, that means it is being used for Poetry commands (e.g. `poetry install`, `poetry shell`, `poetry update`). Poetry cannot activate the virtual environment in your shell as a process cannot directly manipulate the state of its parent.

If you want the env to be active, you can run `poetry shell` and you'll get a subshell in the virtual environment.

It seems like we might want to change the terminology used by `poetry env list` as active has a specific meaning in Python and others might be confused like you.

Finally, I'm closing this issue as it was originally a question/support issue and I believe it to be resolved (`poetry env use system` has no meaning, one must either activate another virtual environment or set `virtualenvs.create false` to turn off Poetry's virtual environment support).

**Closed by neersighted** 2022-09-05 17:33 UTC
Labels: kind/bug, status/triage
