### ISSUE TITLE
poetry add command doesn't have help

### ISSUE THREAD

**Issue by MadWombat** [python-poetry/poetry#1920] opened 2020-01-20 17:36 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: OS X Sierra
- **Poetry version**: 1.0.2

## Issue

If I run poetry without any arguments, I get a help screen with a list of commands. If I run poetry with a command and `--help` flag, like `poetry show --help` I get a help screen for that command. This does not seem to be the case for `add` command. Running `poetry add --help` results in an error message `Not enough arguments (missing: "name").` and that is it. Would be nice to have a help screen for add command.

**Comment by sdispater** [comment] 2020-01-20 22:13
Duplicate of #1625 and fixed in #1910

**Closed by sdispater** 2020-01-20 22:13 UTC
Labels: Bug
