### ISSUE TITLE
Poetry fails to run pip which picks `user` option from user config

### ISSUE THREAD

**Issue by sergei-dyshel** [python-poetry/poetry#6521] opened 2022-09-15 07:10 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**:  MacOS Big Sur 11.6
- **Poetry version**: 1.2.0 (installed with Homebrew)
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://github.com/sergei-dyshel/itunes-tag-sync/blob/master/pyproject.toml

## Issue
I have pip configured to install to user directory:
```
# pip.conf
[global]
user = yes
```

When I install project with poetry I get the following error:
```
# poetry install
  Command ['/Users/sergei/Library/Caches/pypoetry/virtualenvs/itunes-tag-sync-_c69w8Vl-py3.10/bin/python', '/usr/local/Cellar/poetry/1.2.0_1/libexec/lib/python3.10/site-packages/virtualenv/seed/wheels/embed/pip-22.2.2-py3-none-any.whl/pip', 'install', '--disable-pip-version-check', '--prefix', '/Users/sergei/Library/Caches/pypoetry/virtualenvs/itunes-tag-sync-_c69w8Vl-py3.10', '--no-deps', '/Users/sergei/Library/Caches/pypoetry/artifacts/e1/09/c0/6a6df3ef412eb19fcda1b353ea54e3b48f9c518348fadd0967a962cbb6/pyparsing-3.0.9-py3-none-any.whl'] errored with the following return code 1, and output:
  ERROR: Can not combine '--user' and '--prefix' as they imply different installation locations
```

So it looks like Poetry is picking `user` option from the config and it conflicts with the option passed on command line.

## Expected behaviour
Poetry ignores user config or at least potentially conflicting parts of it (e.g. `user` option).

## Workaround
Use env variable to override `user` during Poetry run.
```
PIP_USER=0 poetry install
```

**Comment by dimbleby** [comment] 2022-09-15 10:41
duplicate #1214

**Comment by sergei-dyshel** [comment] 2022-09-15 20:00
@dimbleby 
I think you misunderstood the issue here and there's not duplicate here.

#1214 is talking about making Poetry into a global (or rather user-specific) package manager that installs packages to user directory.

This issue is talking about a *BUG* that poetry fails to install because of conflicting user configuration. Please correct me if I'm wrong.

**Comment by neersighted** [comment] 2022-09-15 20:02
Not really -- ultimately the request is to interoperate with `pip --user` or similar. Pip is an implementation detail of Poetry and anything you do to try and perturb Poetry's usage of pip may cause breakage (arguable we should be using `pip --isolated`) -- but a request for Poetry to respect pip's user mode is a duplicate of #1214.

**Comment by dimbleby** [comment] 2022-09-15 20:09
fwiw I agree after all that this is not quite the same as #1214.  

This one is sort of saying that there was a loophole all along that the #1214-wanters could have used, and asking that loophole to be closed.  

If poetry ever reaches the ponit where it doesn't shell out to pip at all then this all becomes moot.

Meanwhile, as you say, it probably ought to go `--isolated` when it does call pip, and it seems legit to have an issue tracking that.

**Comment by neersighted** [comment] 2022-09-15 20:10
Ah, after re-reading the original issue I see the distinction now -- this is a user's configuration of a different/external tool breaking Poetry.

**Comment by dimbleby** [comment] 2022-09-15 20:20
`--isolated` should be a trivial addition to https://github.com/python-poetry/poetry/blob/cc3f99425206aa2507af6779b1943cfa751206cc/src/poetry/utils/pip.py#L28 if anyone care to make an MR

**Comment by neersighted** [comment] 2022-09-15 20:22
Already baking locally 😄

**Closed** 2022-09-15 20:50 UTC
Labels: kind/bug, area/installer, version/1.2.0

**Comment by sergei-dyshel** [comment] 2022-09-15 21:44
Thanks for understanding and quick patching ;)

Just one nitpick about `avoid bad local config` - there's nothing wrong or bad if user configures pip to install packages to user directory when he does `pip install ...` in terminal. On the other side, Poetry uses pip as internal implementation detail, in a way that is unrelated to the former flow. So something like `to avoid conflict with user config` would be more appropriate.

**Comment by neersighted** [comment] 2022-09-15 21:51
What I really mean is 'bad' from Poetry's perspective -- fair enough 😅
