### ISSUE TITLE
Multiple constraints for dependencies does not work with URL

### ISSUE THREAD

**Issue by eterna2** [python-poetry/poetry#2193] opened 2020-03-18 03:29 UTC
- [ x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [ x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10
- **Poetry version**: 1.0.2

## Issue
pytorch in pypi only support linux and darwin. So the only way to properly install pytorch is via their download page. However, I need to declare dependency for different os (i.e. linux and win32)

Based on the documentation, for multiple constraints I can do it like this:
```
[tool.poetry.dependencies]
foo = [
    {version = "<=1.9", python = "^2.7"},
    {version = "^2.0", python = "^3.4"}
]
```
However, when I tried to do the same using URL endpoint
```
torch = [
    { url = "https://download.pytorch.org/whl/cpu/torch-1.4.0%2Bcpu-cp37-cp37m-linux_x86_64.whl", markers = "python_version == '3.7' and sys_platform == 'linux'"},
    { url = "https://download.pytorch.org/whl/cpu/torch-1.4.0%2Bcpu-cp37-cp37m-win_amd64.whl", markers = "python_version == '3.7' and sys_platform == 'win32'"}
]
```
I got this error. 
```
The Poetry configuration is invalid:
  - [dependencies.torch] [{'url': 'https://download.pytorch.org/whl/cpu/torch-1.4.0%2Bcpu-cp37-cp37m-linux_x86_64.whl', 'markers': "python_version == '3.7' and sys_platform == 'linux'"}, {'url': 'https://download.pytorch.org/whl/cpu/torch-1.4.0%2Bcpu-cp37-cp37m-win_amd64.whl', 'markers': "python_version == '3.7' and sys_platform == 'win32'"}] is not valid under any of the given schemas
```

Is there any way to get this to work?

**Comment by abn** [comment] 2020-03-19 00:20
This is a duplicate of the issue identified in https://github.com/python-poetry/poetry/issues/2138#issuecomment-596250583

**Closed** 2020-04-05 16:41 UTC
Labels: Bug, Duplicate
