### ISSUE TITLE
Poetry does not show required login when resolving depedencies

### ISSUE THREAD

**Issue by MartinThoma** [python-poetry/poetry#2272] opened 2020-04-06 09:20 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version: 1.0.5
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 18.04
- **Poetry version**: 1.0.5

## Issue

When I executed `poetry install --extras all`, I've seen `Resolving dependencies...` + the seconds counting up for over 2000s. Twice. I thought it was [poetry being slow at resolving](https://github.com/python-poetry/poetry/issues/2094#issuecomment-609648194), but when I added `-vvv`, I could see `Username for 'https://gitlab.mycompany.com':`. So the reason why it was blocked is that it was waiting for authentication, but I as a user could not see that. With `-vvv` I could enter my credentials. This should not require `-vvv`

**Comment by m1nde** [comment] 2020-05-08 10:49
This happens when you have a misconfigured `~/.pip/pip.conf` file.

**Comment by MartinThoma** [comment] 2020-05-09 07:17
@m1nde I don't have this file at all. I don't even have the `.pip` directory

**Comment by MartinThoma** [comment] 2020-07-06 04:01
I have `Poetry version 1.0.9` now. Also happens with `poetry add`

**Comment by felixpatzelt** [comment] 2020-11-05 10:12
I had the same issue and for me it was caused by having a `~/.pip/pip.conf` like @m1nde reported.

**Comment by atemate** [comment] 2023-01-03 03:07
+1 to this issue: poetry hangs silently on every resolving dependency command if it can't access private pypi repo, and it's not obvious for the users that they need to clean their pip.conf

**Comment by neersighted** [comment] 2023-01-03 03:38
This issue was actually solved in #6531 and #6724 -- Poetry is also decreasing usage of Pip to avoid the pitfalls of depending on Pip for core functionality when the Pip version is uncontrolled/based on the environment being managed.

**Closed by neersighted** 2023-01-03 03:38 UTC
Labels: kind/bug, status/triage, area/ux
