### ISSUE TITLE
Poetry takes very much time to lock on a specific set of dependencies

### ISSUE THREAD

**Issue by KristobalJunta** [python-poetry/poetry#2137] opened 2020-03-06 10:13 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 19.10
- **Poetry version**: 1.0.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/KristobalJunta/90ec92274a286d7a0f5f366a4ee451c4

## Issue

While this is not technically a bug, this situation is affecting user experience quite much. With the set of dependencies provided in the linked pyproject file, Poetry takes too long to resolve and generate a lock file. About 1.5 hrs on my machine (quad-core @ 3.7 GHz, so not quite low-end), to be specific.

I have tested this with pip and pipenv, and the latter generates lock in about 17s.

I wonder, if something can be done to improve dependency resolution in such cases, as pipenv test shows that it's totally possible. _Though, usually pipenv takes more time to lock & install for me than Poetry._

**Comment by dimbleby** [comment] 2022-04-18 11:51
I don't know whether this was true two years ago, but today it takes poetry a long time to work its way back through awscli versions and find one that's compatible with python 3.5.

This is somewhat improved by #5335, but really in such cases the pragmatic thing to do is to put an upper bound on awscli (or use a more recent python) so that poetry doesn't have to check all of the hundreds of later versions.

- with `python = "^3.6"` this pyproject.toml solves more or less immediately

- sticking with python 3.5 but adding extra constraints to help poetry never choose packages that require python >=3.6 is less effective than I had hoped - but in combination with #4695 it does solve quickly

**Comment by mkniewallner** [comment] 2022-07-10 16:15
Since Python 3.5 is considered end of life since almost 2 years, and there are actionable solutions to make the resolver faster here (setting a lower bound for `awscli`, or using more recent Python versions), going to close this issue, because there's not that much things that Poetry can do given how the resolver works.

**Closed by mkniewallner** 2022-07-10 16:15 UTC
Labels: Resolver

**Comment by mm-matthias** [comment] 2022-07-12 14:56
Probably a duplicate of https://github.com/python-poetry/poetry/issues/5896 .
