### ISSUE TITLE
poetry show --why doesn't display the why part in GitLab CICD job

### ISSUE THREAD

**Issue by eiriklid** [python-poetry/poetry#8907] opened 2024-01-25 10:38 UTC
- **Poetry version**: 1.7.1
- **Python version**: 3.10.13
- **OS version and name**: Fedora 38
- **pyproject.toml**: https://gist.github.com/eiriklid/c90df956b39baf186e190205f1aa11c2

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a [recommended method](https://python-poetry.org/docs/#installation).
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

When running `poetry show --why` locally the dependency that added the package is displayed.
However when running in GitLab CICD, the dependencies is not displayed.
Running the same image/container on my laptop `poetry show --why` the dependency that added the package is displayed.

So it is only on GitLab the error occur.

Has anyone encountered the same or a similar problem?

Gitlab: 
![image](https://github.com/python-poetry/poetry/assets/14213127/81232509-f8e5-4bc0-9670-e4395b187b3b)

Locally:
![image](https://github.com/python-poetry/poetry/assets/14213127/a5196b03-17ec-4e8c-a957-6f3e947d213f)

**Comment by dimbleby** [comment] 2024-01-25 12:43
probably it's just about the terminal width

**Comment by radoering** [comment] 2024-02-04 12:13
Probably a duplicate of #2880

**Closed by radoering** 2024-02-04 12:13 UTC
Labels: kind/bug, area/cli, status/duplicate, area/ux
