### ISSUE TITLE
Poetry 1.1.0 erroneously warns about out of sync poetry.lock and pyproject.toml

### ISSUE THREAD

**Issue by TimOrme** [python-poetry/poetry#3092] opened 2020-10-06 00:53 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Debian Buster
- **Poetry version**: 1.1.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/TimOrme/f12d1cf9d89d262be03570bd040843c9

## Issue

When running the export command in poetry 1.1.0, it raises a warning stating:

```
Warning: The lock file is not up to date with the latest changes in pyproject.toml. You may be getting outdated dependencies. Run update to update them.
```

However, this doesn't seem to be the case, and the same files work fine in poetry 1.0.9, which raises no warning.

This also creates an issue in some automation with export, as were running a command like this:

```
poetry export -f requirements.txt > requirements.txt
```

And because the warning is on stdout, it is added to the requirements file, which then causes breakage on pip commands trying to parse that requirements file.

The warning being written to stdout is less of an issue, but would also be nice if export was guaranteed to have clean output.

Thanks!

**Comment by finswimmer** [comment] 2020-10-06 04:42
Hello @TimOrme,

whenever you see such warning, you should run `poetry lock` to make sure, your `poetry lock` is up to date. Also please update to poetry 1.1.1 Unfortunately there were some bugs in the 1.1.0 release around locking and exporting. 

fin swimmer

**Comment by TimOrme** [comment] 2020-10-06 06:16
Running `poetry lock` seems to have no effect unfortunately.  I also see the same issue in 1.1.1 as well.

**Comment by TimOrme** [comment] 2020-10-06 06:20
Here's the console output:

```
root@ac2833088cb1:/pip-packages# poetry --version
Poetry version 1.1.1
root@ac2833088cb1:/pip-packages# poetry export -f requirements.txt | head
Warning: The lock file is not up to date with the latest changes in pyproject.toml. You may be getting outdated dependencies. Run update to update them.
```

Interestingly, I only see this happen in the docker container with debian jesse.  I don't see the same issue occur on my mac.  It's unclear if thats strictly an OS issue or other dependency in the environment.

**Comment by inactivist** [comment] 2020-11-22 13:32
> Interestingly, I only see this happen in the docker container with debian jesse. I don't see the same issue occur on my mac. It's unclear if thats strictly an OS issue or other dependency in the environment.

Can you provide a simple Dockerfile that reproduces the issue?

**Comment by finswimmer** [comment] 2021-12-29 19:38
Closing this because we haven't received more information for a long time.

Feel free to leave a comment if you disagree.

**Closed by finswimmer** 2021-12-29 19:38 UTC
Labels: Bug, Triage
