### ISSUE TITLE
Embed resource files in final package at a given location

### ISSUE THREAD

**Issue by kasteph** [python-poetry/poetry#2267] opened 2020-04-05 11:50 UTC
**From  @theunkn0wn1** 

The feature I would like to see out of this is to be able to embed resource files into the wheel (and subsequently the installed package) at an arbitrary location.

For instance, in my project i would like to embed the `pyproject.toml` into the installed sources so the library may access this resource at runtime. I wish to do this to access the version string contained in the `pyproject.toml`. 
Presently, even if the `tool.poetry.include` directive is used the file does not end up in the installation directory and is consequently not usable to the installed application.

My application has the structure
```
/
/pyproject.toml
/src/...
/test/...
```
What I would like to do is copy, at build time, `/pyproject.toml` to `/src/pyproject.toml` so it may be included in the wheel and usable a resource via `importlib.resources`.
```py
import importlib.resources as resources
import toml
import src  # root application package (renames are planned)
package_meta = toml.loads(resources.read_text(src, "pyproject.toml"))
src.__version__ = package_meta['tool']['poetry']['version']

_Originally posted by @theunkn0wn1 in https://github.com/python-poetry/core/pull/6#issuecomment-608017525_

**Comment by finswimmer** [comment] 2020-04-05 17:40
Hello @theunkn0wn1,

maybe there is a use case for your feature request. But the one you are showing isn't.

The correct way to get access to the metadata of a package during runtime is to use [importlib.metadata](https://docs.python.org/3/library/importlib.metadata.html) (or [importlib_metadata](https://pypi.org/project/importlib-metadata/) for python <3.8)

```
import importlib.metadata

__version__ = importlib.metadata.version("mypackage")
```

So could you imagine other use cases?

fin swimmer

**Comment by dmyersturnbull** [comment] 2020-05-01 04:11
@finswimmer @stephsamson Is there no current way to include resource files that are not in a package?

I'd like to include a changelog.md so it can be summarized when the package runs.

This is a more obscure use case, but I also have a self-hosting code that needs to store its own config setup, including its own pyproject.toml.

**Comment by dclong** [comment] 2020-08-18 15:35
What about including a JAR file?

**Comment by ToddG** [comment] 2021-01-08 21:51
What about including a schema.json to be used by jsonschema? Sure, as a work-around, I can embed the schema into a string... But what if I want to include image resources in my package? etc..

**Comment by sinoroc** [comment] 2021-01-08 22:40
Resource files (in short: file that is not a Python file) that you wish to install and access at run time ***has to be part of a package***. It can then be accessed with [_`importlib.resources`_ from Python's standard library](https://docs.python.org/3/library/importlib.html#module-importlib.resources). There are many examples around...

**Comment by gitonthescene** [comment] 2021-02-13 23:55
Just to be explicit about this.  When I changed my access to a file from using `open().read()` to using `importlib.resources.read_text()` running `poetry build` did package the file into the built wheel.

**Comment by sinoroc** [comment] 2021-02-14 08:25
I think this thread sums up the full situation about including and/or excluding things of the sdist and/or wheel: https://github.com/python-poetry/poetry/issues/3380

**Comment by zoj613** [comment] 2021-02-28 18:07
I would love this feature. I have a package with a C extension where I would like to the copy the folder of header files inside the wheel and sdist during build time. Currently I have no way of doing this. I don't want to keep the header files in the python package folder since they don't belong there.

**Comment by theunkn0wn1** [comment] 2021-03-01 03:36
> I would love this feature. I have a package with a C extension where I would like to the copy the folder of header files inside the wheel and sdist during build time. Currently I have no way of doing this. I don't want to keep the header files in the python package folder since they don't belong there.

Funnily enough that was my initial inpetus to request this feature: compiled modules.

I have two projects which have generated files, which I do not wish to place in-line with the non-generated sources as they don't belong there. 
`importlib.resources` helps in places where we have static files embedded into the wheel which are not generated at build time, or manually generated before building the wheel. They do not resolve the problem of embedding resources into the wheel that are not present within the package's filesystem to begin with.

**Comment by finswimmer** [comment] 2022-11-27 20:08
Closing this as a duplicate of #4583

**Closed by finswimmer** 2022-11-27 20:08 UTC
Labels: area/build-system, kind/feature, area/core, status/triage
