### ISSUE TITLE
Add Poetry Version to Metadata in Poetry.lock

### ISSUE THREAD

**Issue by jhamet93** [python-poetry/poetry#9238] opened 2024-03-25 17:58 UTC
### Issue Kind

Brand new capability

### Description

To ensure compatibility, I would like to understand which version of the `poetry` CLI is compatible with a given `pyproject.toml` which produced a `poetry.lock`.

Recently, this [issue](https://github.com/python-poetry/poetry/issues/9042) broke CI/CD pipelines for certain projects where the Poetry version that ended up being installed was `1.8` but the projects themselves were not updated to support that version. Thus, it would be a nice bonus if I could predetermine a compatible version of Poetry and install that version to manage a given Poetry project.

I do understand there are better solutions that can be implemented internally (e.g. only support a single Poetry version across all projects) but given the scale of the company (number of projects + developers),  I figured it is worth reaching out here about this particular request.

### Impact

When sharing projects, to ensure the same version of Poetry is used across users/CI/etc.

### Workarounds

Could parse the first line of the `poetry.lock` file but that seems a brittle approach.

**Comment by dimbleby** [comment] 2024-03-26 20:58
writing a poetry version number into poetry.lock should not help your pipelines.  Pipelines should be pinning the versions of tools such as poetry - not automatically taking the latest, but also not automatically taking whatever version the most recent committer used.

if you want to know what version of poetry produced a lockfile so that you as a developer can install a matching poetry - then reading the first line of `poetry.lock` seems just fine to me.

**Comment by radoering** [comment] 2024-03-27 06:20
We deliberately decided against adding the poetry version to the metadata. See #7339 for details.

Apart from your proposed solution, your use case reads more or less like a duplicate of #3316.

**Closed by radoering** 2024-03-27 06:20 UTC
Labels: kind/feature, status/triage
