### ISSUE TITLE
 assert by_ref[ref] is not None with crypto==1.4.1

### ISSUE THREAD

**Issue by rrauenza** [python-poetry/poetry#6111] opened 2022-08-03 18:30 UTC
- [ x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Centos7
- **Poetry version**: 1.1.14
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: started with fresh init

## Issue

```
(venv) <centos7:/tmp>$ ./venv/bin/poetry add -vv crypto==1.4.1
Using virtualenv: /tmp/venv

Updating dependencies
Resolving dependencies...
   1: fact: tmp is 0.1.0
   1: derived: tmp
   1: fact: tmp depends on crypto (1.4.1)
   1: selecting tmp (0.1.0)
   1: derived: crypto (==1.4.1)
   1: fact: crypto (1.4.1) depends on Naked (*)
   1: fact: crypto (1.4.1) depends on shellescape (*)
   1: selecting crypto (1.4.1)
   1: derived: shellescape
   1: derived: Naked
   1: selecting shellescape (3.8.1)
   1: Version solving took 0.299 seconds.
   1: Tried 1 solutions.

  Stack trace:

  14  venv/lib64/python3.8/site-packages/clikit/console_application.py:131 in run
      status_code = command.handle(parsed_args, io)

  13  venv/lib64/python3.8/site-packages/clikit/api/command/command.py:120 in handle
      status_code = self._do_handle(args, io)

  12  venv/lib64/python3.8/site-packages/clikit/api/command/command.py:171 in _do_handle
      return getattr(handler, handler_method)(args, io, self)

  11  venv/lib64/python3.8/site-packages/cleo/commands/command.py:92 in wrap_handle
      return self.handle()

  10  venv/lib64/python3.8/site-packages/poetry/console/commands/add.py:173 in handle
      status = self._installer.run()

   9  venv/lib64/python3.8/site-packages/poetry/installation/installer.py:103 in run
      return self._do_install(local_repo)

   8  venv/lib64/python3.8/site-packages/poetry/installation/installer.py:235 in _do_install
      ops = solver.solve(use_latest=self._whitelist)

   7  venv/lib64/python3.8/site-packages/poetry/puzzle/solver.py:65 in solve
      packages, depths = self._solve(use_latest=use_latest)

   6  venv/lib64/python3.8/site-packages/poetry/puzzle/solver.py:233 in _solve
      result = resolve_version(

   5  venv/lib64/python3.8/site-packages/poetry/mixology/__init__.py:7 in resolve_version
      return solver.solve()

   4  venv/lib64/python3.8/site-packages/poetry/mixology/version_solver.py:84 in solve
      next = self._choose_package_version()

   3  venv/lib64/python3.8/site-packages/poetry/mixology/version_solver.py:403 in _choose_package_version
      for incompatibility in self._provider.incompatibilities_for(version):

   2  venv/lib64/python3.8/site-packages/poetry/puzzle/provider.py:410 in incompatibilities_for
      return [

   1  venv/lib64/python3.8/site-packages/poetry/puzzle/provider.py:411 in <listcomp>
      Incompatibility(

  AssertionError

  

  at venv/lib64/python3.8/site-packages/poetry/mixology/incompatibility.py:60 in __init__
       56│                     # intersection, they're mutually exclusive, making this incompatibility
       57│                     # irrelevant, since we already know that mutually exclusive version
       58│                     # ranges are incompatible. We should never derive an irrelevant
       59│                     # incompatibility.
    →  60│                     assert by_ref[ref] is not None
       61│                 else:
       62│                     by_ref[ref] = term
       63│ 
       64│             new_terms = []
(venv) <centos7:/tmp>$ ./venv/bin/poetry -V
Poetry version 1.1.14
(venv) <centos7:/tmp>$ 
```

**Comment by dimbleby** [comment] 2022-08-03 19:02
the real problem is `Naked`, and this is a duplicate of #1985

**Closed** 2022-08-04 21:09 UTC
Labels: Upstream Issue
