### ISSUE TITLE
poetry 1.1.x causes SSLCertVerificationError when installing packages from private repo

### ISSUE THREAD

**Issue by zyxue** [python-poetry/poetry#3110] opened 2020-10-06 22:50 UTC
I have a poetry project, configured with a private pypi repo, that used to work well, but after upgrading poetry to 1.1.x (tried 1.1.0 to 1.1.2), it causes error like

```
#16 26.50 Retrying HTTP request in 0.5 seconds.
#16 27.13 Retrying HTTP request in 1.0 seconds.
#16 28.25 Retrying HTTP request in 1.5 seconds.
#16 29.87 Retrying HTTP request in 2.0 seconds.
#16 32.00 Retrying HTTP request in 2.5 seconds.
#16 34.71 
#16 34.71   SSLError
#16 34.71 
#16 34.71   HTTPSConnectionPool(host='<PRIVATE-REPO-HOST>)', port=443): Max retries exceeded with url: <URL-to-myapp-0.1.3-py3-none-any.whl (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1124)')))
#16 34.71 
#16 34.71   at /usr/local/lib/python3.8/site-packages/requests/adapters.py:514 in send
#16 34.76       510│                 raise ProxyError(e, request=request)
#16 34.76       511│ 
#16 34.76       512│             if isinstance(e.reason, _SSLError):
#16 34.76       513│                 # This branch is for urllib3 v1.22 and later.
#16 34.76     → 514│                 raise SSLError(e, request=request)
#16 34.76       515│ 
#16 34.76       516│             raise ConnectionError(e, request=request)
#16 34.76       517│ 
#16 34.76       518│         except ClosedPoolError as e:
#16 34.76 
#16 ERROR: executor failed running [/bin/sh -c poetry install --no-dev]: runc did not terminate sucessfully
```

when downloading packages that are only available in the private repo.

When I downgrade poetry to 1.0.10, it then works fine.

**Comment by abn** [comment] 2020-10-07 00:16
@zyxue can you try setting [`REQUESTS_CA_BUNDLE`](https://requests.readthedocs.io/en/master/user/advanced/)?

**Comment by neilpanchal** [comment] 2020-10-07 22:31
Is it possible to ignore SSL certs in poetry? We have an internal private pypi repository hosted without SSL certs.

**Comment by zyxue** [comment] 2020-10-08 05:39
> @zyxue can you try setting [`REQUESTS_CA_BUNDLE`](https://requests.readthedocs.io/en/master/user/advanced/)?

tried `REQUESTS_CA_BUNDLE=/app/certs.pem `

but it doesn't seem to be working, still the same error.

**Comment by zyxue** [comment] 2020-10-08 05:42
@abn could you please point me to the place in the code how certs file is used differently between poetry 1.0.x and 1.1.x?

**Comment by absassi** [comment] 2020-10-20 09:45
I also have the same problem. The funny thing is that when doing `poetry add my-private-package` it is able to find the latest version of that package and resolve its dependencies (so `certificates.my-private-repo.cert` config is used there), but then fails when trying to actually install it.

Setting `REQUESTS_CA_BUNDLE` (or `CURL_CA_BUNDLE`, as requests check for them both) fixes it for me.

**Comment by zyxue** [comment] 2020-10-24 02:44
> The funny thing is that when doing poetry add my-private-package it is able to find the latest version of that package and resolve its dependencies (so certificates.my-private-repo.cert config is used there), but then fails when trying to actually install it.
@absassi , I'm seeing the same behavior. the version is resolved, but it can't install.

Do I understand correctly that you set `certificates.my-private-repo.cert` and `REQUESTS_CA_BUNDLE` to the same value (i.e. path to a `pem` file) and then it works?

**Comment by irremotus** [comment] 2020-10-28 04:17
I am seeing the same issue, and can confirm that `certificates.my-private-repo.cert` and REQUESTS_CA_BUNDLE are set to the same value.

**Comment by zyxue** [comment] 2020-10-28 05:07
@irremotus , do you mean it's still not working for you even with "certificates.my-private-repo.cert and REQUESTS_CA_BUNDLE are set to the same value"?

It's not working for me.

**Comment by absassi** [comment] 2020-10-28 13:06
To make it clear: I've set both `certificates.my-private-repo.cert` and `REQUESTS_CA_BUNDLE` and _it works for me_ (it should probably work too by setting only `REQUESTS_CA_BUNDLE`, but I haven't checked).

**Comment by irremotus** [comment] 2020-10-28 13:09
@zyxue When I set REQUESTS_CA_BUNDLE, both dependency resolution and package installation work.  When I set certificates.my-private-repo.cert (and not REQUESTS_CA_BUNDLE), dependency resolution works, but package installation fails, as @absassi mentioned.  This worked in previous versions (e.g. 1.0.0), but is failing in recent versions (e.g. 1.1.[1-4]).

**Comment by zyxue** [comment] 2020-10-28 23:50
I haven't had a problem with before poetry 1.1.0. Currently, I explicitly set the poetry version to avoid break with `python -m pip install poetry==1.0.10`, but still curious why this is happening.

I tried with poetry 1.1.4 again, here is what I experienced:

| poetry   config   certificates.<repo> .cert | set REQUESTS_CA_BUNDLE | note                                                                                         |
|---------------------------------------------|------------------------|----------------------------------------------------------------------------------------------|
| yes                                         | yes                    | get [SSL: CERTIFICATE_VERIFY_FAILED]  before dependency resolution                           |
| yes                                         | no                     | dependency resolution succeeds, but get [SSL: CERTIFICATE_VERIFY_FAILED] during installation |
| no                                          | yes                    | get [SSL: CERTIFICATE_VERIFY_FAILED] before dependency resolution                            |
| no                                          | no                     | get [SSL: CERTIFICATE_VERIFY_FAILED] before dependency resolution

**Comment by absassi** [comment] 2020-10-30 08:33
@zyxue, since dependency resolution only works when you have the file in Poetry config and the variable is unset, it means that whatever you are setting in the variable is causing the validation to fail (the variable takes precedence over the configuration). Please double check the path for any typos or maybe wrong use of quotes.

**Comment by zyxue** [comment] 2020-10-30 19:46
what I have done is basically
```
poetry config certificates.mypypi.cert /app/cacerts.pem
export REQUESTS_CA_BUNDLE=/app/cacerts.pem
```
am I missing something?

**Comment by absassi** [comment] 2020-11-03 16:42
@zyxue that looks correct to me. Are you using a private repo _in addition_ to PyPI (i.e. no `default = true` in the source in pyproject.toml)? If so, do you have public CA certificates in this bundle or only the private CAs? The only thing I could think of is that Poetry is trying to get packages from both sources and your bundle have only the certificate for the private one, so when you set the variable, it works for the private repo, but starts to fail when accessing pypi.org.

**Comment by zyxue** [comment] 2020-11-10 17:27
>Are you using a private repo in addition to PyPI (i.e. no default = true in the source in pyproject.toml)?

No, I'm not using `default=true`.

> If so, do you have public CA certificates in this bundle or only the private CAs? 

From your reasoning, I feel I'm only having private CAs. (I'm not too familiar with how CA works, and the difference between public and private)

After adding `default=true`, I'm seeing error like

```
#17 14.97   • Installing pygments (2.6.1)
#17 14.97   • Installing rsa (4.6)
#17 14.97   • Updating urllib3 (1.25.11 -> 1.25.10)
#17 16.19 
#17 16.19   RuntimeError
#17 16.19 
#17 16.19   Unable to find installation candidates for nest-asyncio (1.4.0)
#17 16.19 
#17 16.19   at /usr/local/lib/python3.8/site-packages/poetry/installation/chooser.py:72 in choose_for
#17 16.22        68│ 
#17 16.22        69│             links.append(link)
#17 16.22        70│ 
#17 16.22        71│         if not links:
#17 16.22     →  72│             raise RuntimeError(
#17 16.22        73│                 "Unable to find installation candidates for {}".format(package)
#17 16.22        74│             )
#17 16.22        75│ 
#17 16.22        76│         # Get the best link
#17 16.22 
#17 16.22 
#17 16.22   RuntimeError
#17 16.22 
#17 16.22   Unable to find installation candidates for pygments (2.6.1)
#17 16.22 
#17 16.22   at /usr/local/lib/python3.8/site-packages/poetry/installation/chooser.py:72 in choose_for
#17 16.24        68│ 
#17 16.24        69│             links.append(link)
#17 16.24        70│ 
#17 16.24        71│         if not links:
#17 16.24     →  72│             raise RuntimeError(
#17 16.24        73│                 "Unable to find installation candidates for {}".format(package)
#17 16.24        74│             )
#17 16.24        75│ 
#17 16.24        76│         # Get the best link
#17 16.24 
#17 16.24 
#17 16.24   RuntimeError
```

It's kind of confusing why the behavior changed from poetry 1.0.x?

**Comment by absassi** [comment] 2020-11-19 15:51
@zyxue, I think we found the problem then (because I can't think of anything else). so what happens is that you need to use the private source only for private packages, and you still need PyPI for public packages. So, if you use `default=true`, it doesn't work, because it stops looking for packages in PyPI and if you don't use it, then it looks into both repositories, but you don't have a CA bundle that can validate both servers.

I think there's three ways you can fix this:

* Download the open source wheels you need from PyPI and upload them to your private repository. Or configure your private repository to also mirror PyPI, if it has this feature (I know Artifactory can do that).
* Include the CAs required to validate PyPI servers in your bundle. If you are on Linux, you can just `cat` the system certificates and your bundle together into a single file. If you are on Windows, then you can use the Mozilla CA bundle (you can download a copy from [curl website](https://curl.haxx.se/docs/caextract.html)), as Windows doesn't have any bundle in that format that you can use directly.
* Downgrade to Poetry 1.0.10 or 1.0.9, if possible.

As for why this changed, this is simply a bug, as far as I can tell, and hopefully will be fixed soon.

**Comment by zyxue** [comment] 2020-11-19 16:31
Thank you for the detailed explanation, @absassi ! 

Regarding the first solution, based on the log in my last comment, do you have any insight on why it does not have trouble till updating urllib3. In other words, it seems fine downloading pygments and rsa, which I thought are also from the public PyPI?

**Comment by absassi** [comment] 2020-11-25 14:07
@zyxue, I can't say for sure. Maybe they are locally cached and urllib3 is not, or maybe you have pygments and rsa in your private repo?

**Comment by zyxue** [comment] 2020-11-25 19:35
@absassi, thank you for your reply! I see, I'll stick to Poetry 1.0.10 till this issue is fixed.

**Comment by gazpachoking** [comment] 2022-07-21 19:50
This is still an issue on 1.2.0b3

**Comment by neersighted** [comment] 2022-10-11 12:11
The last set of steps listed by @wjhrdy are correct for a private repo with a self-signed certificate, and should work properly on 1.2.x. If you're still running into issues using them, please open a new issue with a detailed reproduction.

If you're trying to replace the certificate for PyPI/files.pythonhosted.org, you'll want to see #1012 -- in short, `REQUESTS_CA_BUNDLE` works but is not the most ergonomic experience. If you're trying to replace PyPI with another URL/index globally (and are unwilling to set a custom source with `default = true`), that is tracked at #1632.

**Closed by neersighted** 2022-10-11 12:11 UTC
Labels: kind/bug, status/triage, area/repo
