### ISSUE TITLE
.bash_profile is not sourced when running shell / commands on MacOS

### ISSUE THREAD

**Issue by erny** [python-poetry/poetry#4180] opened 2021-06-14 09:39 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOS Mojave 10.14.6
- **Poetry version**: 1.1.6
- [Link to pyproject.toml Gist](https://gist.github.com/erny/1599224404436c6740a256329b6c3701)
- Bash: GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18)

## Issue

.bash_profile is not sourced on MacOS when running `poetry shell` or `poetry run ...`.  MacOS seems to not use `~/.bashrc` by default.

Should this be implemented ? If not, this could be documented.

The easy workaround is to create a `~/.bashrc` which sources `.bash_profile`.

It seems that the ~/.poetry/lib/poetry/_vendor/py*/pexpect/bashrc.sh does not source it.

Thanks for this great piece of software. Best regards.

**Comment by neersighted** [comment] 2022-09-05 14:50
This is not a bug -- this is the documented behavior of bash in non-login mode. Closing as not an issue, the linked issue mentions a feature request for `poetry shell -l` which may be worth following up on.

**Closed by neersighted** 2022-09-05 14:50 UTC
Labels: kind/question, status/external-issue
