### ISSUE TITLE
POETRY_HTTP_BASIC_ environment variables are ignored for private repositories

### ISSUE THREAD

**Issue by willemt** [python-poetry/poetry#2988] opened 2020-09-28 09:49 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: travis-ci-sardonyx-xenial (happening in CI)
- **Poetry version**: 1.1.0rc1
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: N/A

## Issue

Poetry 1.1.0rc1 is ignoring POETRY_HTTP_BASIC_XXX_PASSWORD and POETRY_HTTP_BASIC_XXX_USERNAME

I'm getting HTTP 401 when running `poetry install`.

Works fine on 1.0.10.

```
  HTTPError

  401 Client Error: Unauthorized for url: https://xxxxxxx.execute-api.ap-northeast-1.amazonaws.com/dev/packages/xxx-0.1.61-py3-none-any.whl

  at ~/virtualenv/python3.7.1/lib/python3.7/site-packages/requests/models.py:941 in raise_for_status
      937│         elif 500 <= self.status_code < 600:
      938│             http_error_msg = u'%s Server Error: %s for url: %s' % (self.status_code, reason, self.url)
      939│
      940│         if http_error_msg:
    → 941│             raise HTTPError(http_error_msg, response=self)
      942│
      943│     def close(self):
      944│
      945│         called the underlying ``raw`` object must not be accessed again.
```

Stack trace (apologies for the artefacts in the left column):
```

  8  ~/virtualenv/python3.7.1/lib/python3.7/site-packages/poetry/installation/executor.py:179 in _execute_operation
      177â”‚ 
      178â”‚             try:
    â†’ 179â”‚                 result = self._do_execute_operation(operation)
      180â”‚             except EnvCommandError as e:
      181â”‚                 if e.e.returncode == -2:

  7  ~/virtualenv/python3.7.1/lib/python3.7/site-packages/poetry/installation/executor.py:253 in _do_execute_operation
      251â”‚             return 0
      252â”‚ 
    â†’ 253â”‚         result = getattr(self, "_execute_{}".format(method))(operation)
      254â”‚ 
      255â”‚         if result != 0:

  6  ~/virtualenv/python3.7.1/lib/python3.7/site-packages/poetry/installation/executor.py:388 in _execute_install
      386â”‚ 
      387â”‚     def _execute_install(self, operation):  # type: (Install) -> None
    â†’ 388â”‚         return self._install(operation)
      389â”‚ 
      390â”‚     def _execute_update(self, operation):  # type: (Update) -> None

  5  ~/virtualenv/python3.7.1/lib/python3.7/site-packages/poetry/installation/executor.py:414 in _install
      412â”‚             archive = self._download_link(operation, Link(package.source_url))
      413â”‚         else:
    â†’ 414â”‚             archive = self._download(operation)
      415â”‚ 
      416â”‚         operation_message = self.get_operation_message(operation)

  4  ~/virtualenv/python3.7.1/lib/python3.7/site-packages/poetry/installation/executor.py:568 in _download
      566â”‚         link = self._chooser.choose_for(operation.package)
      567â”‚ 
    â†’ 568â”‚         return self._download_link(operation, link)
      569â”‚ 
      570â”‚     def _download_link(self, operation, link):

  3  ~/virtualenv/python3.7.1/lib/python3.7/site-packages/poetry/installation/executor.py:577 in _download_link
      575â”‚             # No cached distributions was found, so we download and prepare it
      576â”‚             try:
    â†’ 577â”‚                 archive = self._download_archive(operation, link)
      578â”‚             except BaseException:
      579â”‚                 cache_directory = self._chef.get_cache_directory_for_link(link)

  2  ~/virtualenv/python3.7.1/lib/python3.7/site-packages/poetry/installation/executor.py:604 in _download_archive
      602â”‚     def _download_archive(self, operation, link):  # type: (Operation, Link) -> Path
      603â”‚         response = self._authenticator.request(
    â†’ 604â”‚             "get", link.url, stream=True, io=self._sections.get(id(operation), self._io)
      605â”‚         )
      606â”‚         wheel_size = response.headers.get("content-length")

  1  ~/virtualenv/python3.7.1/lib/python3.7/site-packages/poetry/installation/authenticator.py:80 in request
       78â”‚             else:
       79â”‚                 if resp.status_code not in [502, 503, 504] or is_last_attempt:
    â†’  80â”‚                     resp.raise_for_status()
       81â”‚                     return resp
       82â”‚ 

  HTTPError

  401 Client Error: Unauthorized for url: https://xxx.execute-api.ap-northeast-1.amazonaws.com/dev/packages/xxx-0.1.61-py3-none-any.whl

  at ~/virtualenv/python3.7.1/lib/python3.7/site-packages/requests/models.py:941 in raise_for_status
      937â”‚         elif 500 <= self.status_code < 600:
      938â”‚             http_error_msg = u'%s Server Error: %s for url: %s' % (self.status_code, reason, self.url)
      939â”‚ 
      940â”‚         if http_error_msg:
    â†’ 941â”‚             raise HTTPError(http_error_msg, response=self)
      942â”‚ 
      943â”‚     def close(self):
      944â”‚         
      945â”‚         called the underlying ``raw`` object must not be accessed again.
```

**Comment by abn** [comment] 2020-09-28 12:39
Duplicate of #2799

**Closed** 2020-09-29 01:22 UTC
Labels: Bug, Triage
