### ISSUE TITLE
Optional path dependency cause poetry update to fail when the path is missing

### ISSUE THREAD

**Issue by dg10a** [python-poetry/poetry#2091] opened 2020-02-26 21:38 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Arch Linux 5.5.4-arch1-1 
- **Poetry version**: 1.0.3

## Issue

After modifying the `pyproject.toml` file to include an optional path dependency, `poetry update` fails with the following error:

```
[ValueError]
Directory <Some path that doesn't exist on filesystem> does not exist
```

I would expect `poetry` to ignore the missing directory as the dependency is optional.

Might be related to https://github.com/python-poetry/poetry/issues/668

**Comment by AlexJoz** [comment] 2020-08-12 08:20
yep, agree, would be very helpful to fix

**Comment by abn** [comment] 2020-08-12 08:42
The issue with this is that when doing update or generating lock file all dependencies, including optional ones are required in order get a correct dependency tree. Avoiding this when resolving dependencies, could lead to other issues. It might be better to fail here. If a lock file already exists and the dependency is not activated (via extra etc.), this should not fail.

Re-using the existing package information from the lock file should mitigate this issue. We could, if data is available, treat this as a warning instead of an error.

**Comment by charlax** [comment] 2021-09-10 14:28
I think you get the same error if you want to move a path dependency. Let's it was under `/foo` and move it + change `pyproject.toml` to point to `/bar`, `poetry update` will still fail with `ValueError: Directory /foo does not exist` (I'll try to reproduce later).

**Comment by finswimmer** [comment] 2022-10-07 12:58
Duplicate of #668

**Closed by finswimmer** 2022-10-07 12:58 UTC
Labels: kind/bug
