### ISSUE TITLE
git dependencies are not cached

### ISSUE THREAD

**Issue by blaggacao** [python-poetry/poetry#1698] opened 2019-12-10 00:14 UTC
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

- **Poetry version**: Poetry 0.12.17
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/blaggacao/34765d9ce6d0783297952f1802b69c45

## Issue

I checked the code and it seems the temp dir for git dependency installs are not cached. This is a bug-like behaviour for a 1.5 GB repository like https://github.com/odoo/odoo

**Comment by blaggacao** [comment] 2019-12-10 00:34
Specifically:
https://github.com/sdispater/poetry/blob/e01564775bf58b3f11a5aa67841e9b4cb79de176/poetry/installation/pip_installer.py#L231-L232

And:
https://github.com/sdispater/poetry/blob/e01564775bf58b3f11a5aa67841e9b4cb79de176/poetry/installation/pip_installer.py#L231-L232

**Comment by blaggacao** [comment] 2019-12-10 00:36
Maybe this issue can serve as an opportunity to streamline `poetry.vcs.git` with `pygit2` `libgit` bindings...

**Comment by ubmarco** [comment] 2020-03-10 14:20
I also observed that a dependency given as
```
[tool.poetry.dependencies]
python = "^3.6"
click = "^7"
PyYAML = "*"
pdfplumber = { git = "https://github.com/jsvine/pdfplumber.git", rev = "df00787" }
```
will be cloned every time I do a `poetry install`, even if `.venv/src/pdfplumber` already contains the Git checkout with the right commit ID. I see no reason why an update is needed.
This prevents running tests when machines are offline.

**Comment by ldhieu** [comment] 2020-06-04 12:40
Having issues with this as well.

Does anyone have a temporary/quick fix for this ? Running poetry add with odoo in the pyproject file takes 20-30 mins everytime

**Comment by kshcherban** [comment] 2020-10-14 15:30
> Having issues with this as well.
> 
> Does anyone have a temporary/quick fix for this ? Running poetry add with odoo in the pyproject file takes 20-30 mins everytime

Just use odoo as a submodule in your git repo and change dependency from `git` to `path`.

**Comment by dimbleby** [comment] 2022-10-11 11:25
#6131 should have avoided cloning when nothing has changed

**Comment by abn** [comment] 2024-11-16 00:26
This issue does not exist in Poetry 1.8.4 as the clone is reused if nothing has changed.

If the the issue still exists, or can be reproduced please create a new issue linking to this one as the codebase has changed significantly since this issue was raised.

**Closed by abn** 2024-11-16 00:26 UTC
Labels: kind/enhancement, area/vcs, area/sources
