### ISSUE TITLE
"poetry install" when everything is already installed is very slow

### ISSUE THREAD

**Issue by boxed** [python-poetry/poetry#980] opened 2019-03-22 12:43 UTC
- [X ] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [X ] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.

- **OS version and name**: macOS Mojave 10.14.3
- **Poetry version**: 0.12.11

## Issue
Did this:

```
poetry new foo
cd foo
poetry install
```

so far it's fine, but if I do `poetry install`, it says there is nothing to do but it still takes 7 seconds. I was looking into poetry because I was frustrated with pip being slow when it did nothing, but it seem poetry is even slower :(

**Comment by drunkwcodes** [comment] 2019-03-22 13:22
How long does it take by `pip` and the acceptable overhead when you don't want `poetry` serving more than that?

**Comment by pmav99** [comment] 2019-03-22 13:29
If memory serves, poetry asks PyPi for metadata. If the metadata are not available, then poetry downloads the package from PyPi to check it out. That's what takes time.

**Comment by boxed** [comment] 2019-03-22 14:31
pip is dog slow in general. Try doing "pip --version"!

Going out on the network when the package is already installed seems pretty silly.

**Comment by drunkwcodes** [comment] 2019-03-22 14:46
@boxed It is another issue. 
i
Please close this and reproduce the silliness in your another issue.

**Comment by boxed** [comment] 2019-03-22 14:52
@drunkwcodes sorry, I didn't understand what you just said. Why would I close this ticket when it's still a real thing?

**Comment by drunkwcodes** [comment] 2019-03-22 14:55
@boxed No it's not.

**Comment by boxed** [comment] 2019-03-22 16:14
Why not? Am I having hallucinations or what are you saying?

**Comment by drunkwcodes** [comment] 2019-03-22 16:28
Wait a minute... let me sign up a PayPal account to continue this conversation...
It takes time for a reason, not like the lacking-infomation nonsense.

**Comment by hangtwenty** [comment] 2019-03-28 18:33
Let’s stop the snarkiness @drunkwcodes, it helps nothing.

@boxed It would be good to have instructions for reproducing - can you share a snapshot of your reqs/pyproject.toml, pip and poetry versions, and output of your issues (max verbose ideally)

**Comment by boxed** [comment] 2019-03-28 19:08
Just try installing any package you already have installed. Now, I am aware the reason it's slow is because it just calls pip which is slow. It's not poetrys fault, but it does mean it's just as bad as pip at something pip is very bad at.

**Comment by drunkwcodes** [comment] 2019-03-28 19:21
Wrong guy was mentioned,  @hangtwenty.

**Comment by exhuma** [comment] 2019-09-06 07:16
I can't reproduce this issue. First install is ~23s, subsequent installs are ~3s (using poetry 0.12.16 and pip 19.2.3)

## Console output:

```
┌─[9:11:46] malbert@BBS-nexus
└─~/work/tmp/pspeed› time poetry install
Creating virtualenv pspeed-py3.5 in /home/users/malbert/.cache/pypoetry/virtualenvs
Updating dependencies
Resolving dependencies... (1.9s)

Writing lock file


Package operations: 9 installs, 0 updates, 0 removals

  - Installing markupsafe (1.1.1)
  - Installing click (7.0)
  - Installing itsdangerous (1.1.0)
  - Installing jinja2 (2.10.1)
  - Installing werkzeug (0.15.6)
  - Installing flask (1.1.1)
  - Installing marshmallow (3.0.3)
  - Installing msgpack (0.6.1)
  - Installing pyyaml (5.1.2)
poetry install  16.94s user 1.43s system 77% cpu 23.711 total
┌─[9:12:11] malbert@BBS-nexus
└─~/work/tmp/pspeed› time poetry install
Installing dependencies from lock file

Nothing to install or update

poetry install  2.24s user 0.21s system 80% cpu 3.052 total
┌─[9:12:17] malbert@BBS-nexus
└─~/work/tmp/pspeed› time poetry install
Installing dependencies from lock file

Nothing to install or update

poetry install  2.08s user 0.18s system 88% cpu 2.545 total
┌─[9:12:22] malbert@BBS-nexus
└─~/work/tmp/pspeed›
```

## pyproject.toml

```
[tool.poetry]
name = "pspeed"
version = "0.1.0"
description = ""
license = "MIT"

[tool.poetry.dependencies]
python = "^3.5"
flask = "^1.1"
pyyaml = "^5.1"
msgpack = "^0.6.1"
marshmallow = "^3.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```

**Comment by boxed** [comment] 2019-09-06 10:32
3 seconds counts. It should really be >100ms, ideally >10

**Comment by boxed** [comment] 2019-11-13 13:21
It is still relevant.

**Comment by HodeiG** [comment] 2020-07-05 07:53
I am seeing the same issue:

```bash
$ mkdir /tmp/my_test_project
$ cd /tmp/my_test_project
$ poetry -V
Poetry version 1.0.9
$ poetry init
$ time poetry add bokeh
Using version ^2.1.1 for bokeh

Updating dependencies
Resolving dependencies... (0.2s)

Writing lock file


Package operations: 0 installs, 12 updates, 0 removals

  - Updating markupsafe (1.1.1 /home/hodei/.cache/pypoetry/virtualenvs/my-test-package-itypr2X_-py3.7/lib/python3.7/site-packages -> 1.1.1)
  - Updating pyparsing (2.4.7 /home/hodei/.cache/pypoetry/virtualenvs/my-test-package-itypr2X_-py3.7/lib/python3.7/site-packages -> 2.4.7)
  - Updating six (1.15.0 /home/hodei/.cache/pypoetry/virtualenvs/my-test-package-itypr2X_-py3.7/lib/python3.7/site-packages -> 1.15.0)
  - Updating jinja2 (2.11.2 /home/hodei/.cache/pypoetry/virtualenvs/my-test-package-itypr2X_-py3.7/lib/python3.7/site-packages -> 2.11.2)
  - Updating numpy (1.19.0 /home/hodei/.cache/pypoetry/virtualenvs/my-test-package-itypr2X_-py3.7/lib/python3.7/site-packages -> 1.19.0)
  - Updating packaging (20.4 /home/hodei/.cache/pypoetry/virtualenvs/my-test-package-itypr2X_-py3.7/lib/python3.7/site-packages -> 20.4)
  - Updating pillow (7.2.0 /home/hodei/.cache/pypoetry/virtualenvs/my-test-package-itypr2X_-py3.7/lib/python3.7/site-packages -> 7.2.0)
  - Updating python-dateutil (2.8.1 /home/hodei/.cache/pypoetry/virtualenvs/my-test-package-itypr2X_-py3.7/lib/python3.7/site-packages -> 2.8.1)
  - Updating pyyaml (5.3.1 /home/hodei/.cache/pypoetry/virtualenvs/my-test-package-itypr2X_-py3.7/lib/python3.7/site-packages -> 5.3.1)
  - Updating tornado (6.0.4 /home/hodei/.cache/pypoetry/virtualenvs/my-test-package-itypr2X_-py3.7/lib/python3.7/site-packages -> 6.0.4)
  - Updating typing-extensions (3.7.4.2 /home/hodei/.cache/pypoetry/virtualenvs/my-test-package-itypr2X_-py3.7/lib/python3.7/site-packages -> 3.7.4.2)
  - Updating bokeh (2.1.1 /home/hodei/.cache/pypoetry/virtualenvs/my-test-package-itypr2X_-py3.7/lib/python3.7/site-packages -> 2.1.1)

real    0m22.064s
user    0m18.580s
sys     0m2.052s

$ time poetry install
Installing dependencies from lock file


Package operations: 0 installs, 12 updates, 0 removals

  - Updating markupsafe (1.1.1 /home/hodei/.cache/pypoetry/virtualenvs/my-test-package-itypr2X_-py3.7/lib
  - Updating pyparsing (2.4.7 /home/hodei/.cache/pypoetry/virtualenvs/my-test-package-itypr2X_-py3.7/lib/
  - Updating six (1.15.0 /home/hodei/.cache/pypoetry/virtualenvs/my-test-package-itypr2X_-py3.7/lib/pytho
  - Updating jinja2 (2.11.2 /home/hodei/.cache/pypoetry/virtualenvs/my-test-package-itypr2X_-py3.7/lib/py
  - Updating numpy (1.19.0 /home/hodei/.cache/pypoetry/virtualenvs/my-test-package-itypr2X_-py3.7/lib/pyt
  - Updating packaging (20.4 /home/hodei/.cache/pypoetry/virtualenvs/my-test-package-itypr2X_-py3.7/lib/p
  - Updating pillow (7.2.0 /home/hodei/.cache/pypoetry/virtualenvs/my-test-package-itypr2X_-py3.7/lib/pyt
  - Updating python-dateutil (2.8.1 /home/hodei/.cache/pypoetry/virtualenvs/my-test-package-itypr2X_-py3.
  - Updating pyyaml (5.3.1 /home/hodei/.cache/pypoetry/virtualenvs/my-test-package-itypr2X_-py3.7/lib/pyt
  - Updating tornado (6.0.4 /home/hodei/.cache/pypoetry/virtualenvs/my-test-package-itypr2X_-py3.7/lib/py
  - Updating typing-extensions (3.7.4.2 /home/hodei/.cache/pypoetry/virtualenvs/my-test-package-itypr2X_-
  - Updating bokeh (2.1.1 /home/hodei/.cache/pypoetry/virtualenvs/my-test-package-itypr2X_-py3.7/lib/pyth

real    0m21.447s
user    0m18.436s
sys     0m2.076s

$ time poetry install
Installing dependencies from lock file


Package operations: 0 installs, 12 updates, 0 removals

  - Updating markupsafe (1.1.1 /home/hodei/.cache/pypoetry/virtualenvs/my-test-package-itypr2X_-py3.7/lib/python3.7/site-packages -> 1.1.1)
  - Updating pyparsing (2.4.7 /home/hodei/.cache/pypoetry/virtualenvs/my-test-package-itypr2X_-py3.7/lib/python3.7/site-packages -> 2.4.7)
  - Updating six (1.15.0 /home/hodei/.cache/pypoetry/virtualenvs/my-test-package-itypr2X_-py3.7/lib/python3.7/site-packages -> 1.15.0)
  - Updating jinja2 (2.11.2 /home/hodei/.cache/pypoetry/virtualenvs/my-test-package-itypr2X_-py3.7/lib/python3.7/site-packages -> 2.11.2)
  - Updating numpy (1.19.0 /home/hodei/.cache/pypoetry/virtualenvs/my-test-package-itypr2X_-py3.7/lib/python3.7/site-packages -> 1.19.0)
  - Updating packaging (20.4 /home/hodei/.cache/pypoetry/virtualenvs/my-test-package-itypr2X_-py3.7/lib/python3.7/site-packages -> 20.4)
  - Updating pillow (7.2.0 /home/hodei/.cache/pypoetry/virtualenvs/my-test-package-itypr2X_-py3.7/lib/python3.7/site-packages -> 7.2.0)
  - Updating python-dateutil (2.8.1 /home/hodei/.cache/pypoetry/virtualenvs/my-test-package-itypr2X_-py3.7/lib/python3.7/site-packages -> 2.8.1)
  - Updating pyyaml (5.3.1 /home/hodei/.cache/pypoetry/virtualenvs/my-test-package-itypr2X_-py3.7/lib/python3.7/site-packages -> 5.3.1)
  - Updating tornado (6.0.4 /home/hodei/.cache/pypoetry/virtualenvs/my-test-package-itypr2X_-py3.7/lib/python3.7/site-packages -> 6.0.4)
  - Updating typing-extensions (3.7.4.2 /home/hodei/.cache/pypoetry/virtualenvs/my-test-package-itypr2X_-py3.7/lib/python3.7/site-packages -> 3.7.4.2)
  - Updating bokeh (2.1.1 /home/hodei/.cache/pypoetry/virtualenvs/my-test-package-itypr2X_-py3.7/lib/python3.7/site-packages -> 2.1.1)

real    0m21.831s
user    0m18.680s
sys     0m2.112s

```

**Closed** 2020-11-06 20:57 UTC
