### ISSUE TITLE
dependencies of local dependencies are not installed

### ISSUE THREAD

**Issue by GerevSec** [python-poetry/poetry#5300] opened 2022-03-11 10:02 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- Windows 11 WSL2 ubuntu 20.04 python 3.10
- master (6485bc23d6497c7731e0f1a635f960b33f2ae99e)
- [pyproject.toml](https://gist.github.com/GerevSec/b3f66a0051ab532f5d8334aa456378ba)

## Issue
Hey guys,

After using the current master branch in order to access the 1.2 preview features, I notice that when **installing** a package (in this case, "X") using a local package "pylib", the dependencies of the local package are not installed.
In this case, pylib uses grpcio-tools (with protobuf) to create some python grpc files that use **google.protobuf**.
X uses pylib, so it needs grpcio-tools/protobuf installed.
however, installing X after a fresh clone does not install protobuf or grpcio-tools.

How do you suggest to proceed?

Cheers,
Ayal

**Comment by GerevSec** [comment] 2022-03-11 10:04
Actually, any time a new venv is created (after every restart/whatever) there's a need to install the 2 packages separately. What do you suggest?

**Comment by GerevSec** [comment] 2022-03-11 10:11
Expanding on this - 

Even installing both packages separately doesn't solve the issue.
Each package receives a separate venv, meaning that package X's venv never has grpcio-tools/protobuf packages needed to run pylib's code.

Thoughts?

**Comment by abn** [comment] 2022-03-11 13:15
@GerevSec can you try the following from outside the project virtual environment?

```sh
pip install build
python -c "import build.util; print(build.util.project_wheel_metadata('../../libraries/python/pylib'))"
```

This should show the wheel metadata generated for the project `pylib`. You can grep for `Requires-Dist` to filter for the relevant bits.

Additionally, using `poetry show --tree` should list the dependencies as identified by Poetry. It would also be useful if you can provide the output of `poetry lock -vvv` should also provide more insight on what is going on.

**Comment by GerevSec** [comment] 2022-03-12 16:45
Hey @abn, Thanks for the response. 

So running it outside of the venv, I'm getting an error with the venv - 
`python -c "import build.util; print(build.util.project_wheel_metadata('../../libraries/python/pylib'))"

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/gerev/.local/lib/python3.10/site-packages/build/util.py", line 52, in project_wheel_metadata
    with build.env.IsolatedEnvBuilder() as env:
  File "/home/gerev/.local/lib/python3.10/site-packages/build/env.py", line 104, in __enter__
    executable, scripts_dir = _create_isolated_env_venv(self._path)
  File "/home/gerev/.local/lib/python3.10/site-packages/build/env.py", line 258, in _create_isolated_env_venv
    executable, script_dir, purelib = _find_executable_and_scripts(path)
  File "/home/gerev/.local/lib/python3.10/site-packages/build/env.py", line 303, in _find_executable_and_scripts
    raise RuntimeError(f'Virtual environment creation failed, executable {executable} missing')
RuntimeError: Virtual environment creation failed, executable /tmp/build-env-8qe2u2wg/local/bin/python missing`

am I missing something here?

**Comment by abn** [comment] 2022-03-22 21:57
Hmm, unsure. Looks like the issue is that the `build` package is unable to create the isolatd build environment. I suspect the issue is https://github.com/pypa/build/issues/433. 

See also https://github.com/pypa/virtualenv/issues/2319#issuecomment-1072412075.

**Comment by abn** [comment] 2022-03-22 21:58
This might warrant some additional investigation.

**Comment by finswimmer** [comment] 2022-10-22 15:49
Hello @GerevSec,

you haven't come back to this issue for a long while. So I assume this is solved in the meantime and I can close this ticket.

Feel free to leave a comment if you disagree.

fin swimmer

**Closed by finswimmer** 2022-10-22 15:49 UTC
Labels: kind/bug, status/triage

**Comment by after-ephemera** [comment] 2023-04-05 20:24
I ran into this issue recently and resolved it by removing the `develop = true` flag for my local dependency.
