### ISSUE TITLE
Poetry init not working when path contains certain characters

### ISSUE THREAD

**Issue by PabloRuizCuevas** [python-poetry/poetry#6848] opened 2022-10-20 12:28 UTC
- **1.2.2**: 
- **3.8-2.10**: 
- **Windows 10**: 
- **None**: 

- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
`poetry init --vvv` or in general any poetry command don't work and raise this error:
`Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)`

The only clue I have with this issue is that the username and therefore the path contains a special character "è" 
such as :`"C:\Users\MyUsèrWithRareCharactèr\Project`

And if the path is written somewhere and parsed maybe gives an error like in this SO [issue:](https://stackoverflow.com/questions/13156395/python-load-json-file-with-utf-8-bom-header)

On the other hand the --vvv didn't help to solve it as it logs the same with or without --vvv so it may be a very early problem during execution.

Any idea, besides creating a new user?

**Comment by Azleur** [comment] 2023-02-03 19:48
I ran into a similar issue with a username containing an ampersand (&). Windows 10, Python 3.10, Poetry 1.2.1.

In my case, the Python executable is in a "safe" directory, but Poetry failed when trying to access cached data due to the ampersand.  I could partially solve the issue by setting the cache-dir to a path without special characters, but Poetry still fails if it needs to invoke a compiler (same underlying reason: ampersand in a path that is not quoted).

The feeling I get as an external observer is that Poetry doesn't quote path strings when calling system commands, and that the issue would be solved if it did.

**Comment by Azleur** [comment] 2023-02-03 20:40
[poetry-test.zip](https://github.com/python-poetry/poetry/files/10582612/poetry-test.zip)

I managed to reproduce the bug in a minimal setting. All you need is a cache-dir with an ampersand.

**Comment by Azleur** [comment] 2023-02-04 20:18
I believe the problem can be fixed by modifying `poetry.utils._compat.list_to_shell_command()`. I tried the following version locally and it seemed to work:

```python
def list_to_shell_command(cmd: list[str]) -> str:
    def should_escape(token: str) -> bool:
        should_escape = any(char in token for char in { " ", "/", "\\" })
        is_escaped = token[0] in  { "'", '"' }
        return should_escape and not is_escaped

    return " ".join(
        f'"{token}"' if should_escape(token) else token
        for token in cmd
    )
```

**Closed** 2023-02-18 12:04 UTC
Labels: kind/bug, status/triage
