### ISSUE TITLE
support for non-python extensions

### ISSUE THREAD

**Issue by etijskens** [python-poetry/poetry#1351] opened 2019-09-04 07:02 UTC
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Question

Hi, thanks for poetry!
My Python projects for HPC/scientific computing rely heavily on extension modules, written in C++ using pybind11, or Fortran using f2py. The building process is currently organised with CMake (to great satisfaction). Could anyone give me some information about how I can make use of Poetry to package such projects and deploy them to PyPI?
if possible I'd appreciated being pointed to the relevant poetry files to try and understand how the machinery works :)
many thanks in advance.

**Comment by dmontagu** [comment] 2019-09-04 07:18
I am currently using poetry to build multiple projects using cython and pybind11 extensions.

* As described in https://github.com/sdispater/poetry/issues/11 you'll need to add
    ```toml
    [tool.poetry]
    build = "build.py"
    ```
    to the pyproject.toml
* [This gist](https://gist.github.com/dmontagu/b91d5fd5319ae6fe004ecd28771d985e) includes the contents of the `build.py` file (referenced in the previous bullet) that I use with one of my projects containing *both* cython and pybind11 extensions (the extension names/paths have been changed).

I haven't deployed any packages to PyPI, but I do use `poetry build` to generate a platform-specific wheel and source distribution; presumably this is ready for publishing.

You may want/need to fiddle with the `packages` and/or `exclude` keys in the `[tool.poetry]` section of the pyproject.toml to build a source distribution / wheel with the right contents. (E.g., if using pybind11 as a git submodule, you'd probably want to exclude its `.git` folder.)

**Comment by slurps-mad-rips** [comment] 2019-12-08 00:30
It would be nice if something akin to setup.cfg/setup.py's approach for `console_scripts` could be specified under the `[tool.poetry]` table. Right now I just write a script that just imports a module with a function from a dev dependency named `build` and nothing else (i.e., `from developement_dependency.module import build`). It'd be neat if I could just do `development_dependency.module_name:function` or something to that effect. Then full packages could be used instead of per-project files.

**Comment by dimbleby** [comment] 2024-03-10 12:25
later duplicated by #2740 but that one has more useful discussion in it so suggest closing this one out

**Comment by finswimmer** [comment] 2024-10-30 13:37
Duplicate of #2740

**Closed by finswimmer** 2024-10-30 13:37 UTC
Labels: kind/feature
