### ISSUE TITLE
How to implement custom build?

### ISSUE THREAD

**Issue by brandon-leapyear** [python-poetry/poetry#5483] opened 2022-04-22 20:50 UTC
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue
Does poetry use the `[build-system]` section in `pyproject.toml`? I see it parsed in [`PyProjectTOML`](https://github.com/python-poetry/poetry-core/blob/e251faaebfa92d401d28c9e72f69bcd756147db4/src/poetry/core/pyproject/toml.py#L42-L60), but I don't see anything in `poetry` or `poetry-core` using that property.

I do see `tool.poetry.build`, which _is_ used in `WheelBuilder`, but it isn't documented:
* https://github.com/python-poetry/poetry/blob/b753aaf4c3c08ef0e54941a6616fe318fdf4f6e4/tests/fixtures/extended_project_without_setup/pyproject.toml#L23-L25
* https://python-poetry.org/docs/pyproject/

Ideally, I would want to be able to run `poetry build -f wheel` using a custom `build.py` backend (that does some actions before calling the usual build in `poetry-core`) with some version of:
```toml
# pyproject.toml
[build-system]
backend-path = ["."]
build-backend = "build"
```

If poetry doesn't use `[build-system]`, why not? What should be used instead? Is `tool.poetry.build` the way to define a custom build? If so, why isn't it documented?

Related issues:
* https://github.com/python-poetry/poetry/issues/1332
    * Since this issue is closed, does that mean poetry does support building wheels with C extensions? Are the [docs here](https://python-poetry.org/docs/cli/#build) outdated, saying only pure python wheels are supported?
* https://github.com/python-poetry/poetry/issues/2789

**Comment by Secrus** [comment] 2022-04-23 11:51
There are plans to add support for different build backends, but for now, there is no stable or documented API for that. You can try looking at [Pendulum](https://github.com/sdispater/pendulum), it uses some hacks and `build.py` script to build C extensions.

**Comment by abn** [comment] 2022-05-15 00:39
This is a duplicate of #2740 #5539. Also see #5401.

I suspect you are not really looking for "build-system". This section is not directly used by Poetry. It is used by PEP 517 front ends like pypa/build or pip.

**Closed** 2022-05-15 00:39 UTC
Labels: Documentation
