### ISSUE TITLE
Poetry 1.1.12 installed without error but command producing cleo module name not found error

### ISSUE THREAD

**Issue by marindrag** [python-poetry/poetry#4886] opened 2021-12-11 22:39 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10
- **Poetry version**: 1.1.12
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: None

## Issue
I installed poetry 1.1.12 on Windows 10 following the recommendation on official site, restarted terminal and run the poetry command.
Now I get the following error. This was not happening when I was installing 1.1.11 on Windows 10 last time.
![image](https://user-images.githubusercontent.com/90330756/145693656-c1659bbf-734d-470d-821c-2dbac6987362.png)

**Comment by finswimmer** [comment] 2021-12-12 07:59
Hello @marindrag,

I thinks is a duplicate of https://github.com/python-poetry/poetry/issues/4846.

fin swimmer

**Closed by finswimmer** 2021-12-12 07:59 UTC
Labels: Bug, Triage
