### ISSUE TITLE
`poetry update` repeatedly reinstalls dependencies

### ISSUE THREAD

**Issue by AnOctopus** [python-poetry/poetry#4669] opened 2021-10-22 19:38 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Arch Linux
- **Poetry version**: 1.1.11
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: [here](https://gist.github.com/AnOctopus/f24b3df653af8eb9b5b2ea892736b46f)

## Issue
Similar to
- https://github.com/python-poetry/poetry/issues/4385
- https://github.com/python-poetry/poetry/issues/4358
except their circumstances do not appear to apply.

When I change a dependency (or a new version is released for one), `poetry update` says it is updating the versions, as expected. But if I run `poetry update` again, it will once again output that it is updating from the old version to the new one. `poetry show $PACKAGE` indicates the newer version is installed.

Probably related, if I undo a change to `pyproject.toml` that prompted the update, `poetry update` indicates there are no dependencies to update, but `poetry show $PACKAGE` indicates it is correctly downgraded. This makes me think `poetry update` isn't getting an updated view of what packages are installed.

With the provided gist, I can trigger this behavior by changing the version for `keras` to `"*"` and back, for example.

Project configuration/setup info (in case it is relevant):
I have `virtualenvs.in-project` enabled in my global config. I create my local venv by installing specific python versions with `pyenv` and then setting it for poetry with `poetry env use $PATH_TO_PYENV_PYTHON_BINARY`. Poetry is provided by my OS package manager rather than through the installer script.

**Comment by logan-bobo** [comment] 2022-10-31 20:05
HI, @AnOctopus it looks as if this issue has been fixed in a later version of `poetry` I have tested this on `1.2.2`, and the issue is resolved. Updating to the latest version should fix this :raised_hands:

**Closed by logan-bobo** 2022-10-31 20:05 UTC
Labels: kind/bug, status/triage
