### ISSUE TITLE
poetry self update fails on MacOS for 1.2.0

### ISSUE THREAD

**Issue by fsherratt** [python-poetry/poetry#6296] opened 2022-08-31 15:49 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOS 12.5.1
- **Poetry version**: 1.1.15 -> 1.2.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: N/A

## Issue

Updating poetry from `1.1.15` to `1.2.0` on MacOS Monterey fails with
```
Could not find poetry-1.2.0-darwin.sha256sum file
```
I assuming this is just because the relevant files have not yet been build yet but just want to flag this here.

**Comment by finswimmer** [comment] 2022-08-31 15:52
Duplicate of https://github.com/python-poetry/poetry/issues/6269

**Closed by finswimmer** 2022-08-31 15:52 UTC
Labels: Bug, Triage

**Comment by fsherratt** [comment] 2022-08-31 16:05
https://github.com/python-poetry/poetry/issues/6269 has the solution thanks

Running the following commands got me up to the latest version
```
curl https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py > get-poetry.py

python get-poetry.py --uninstall

curl -sSL https://install.python-poetry.org | python3 -
```
