### ISSUE TITLE
`--remove-untracked` does not remove old versions of root package

### ISSUE THREAD

**Issue by kkirsche** [python-poetry/poetry#5204] opened 2022-02-16 19:14 UTC
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: `macOS Catalina 10.15.7 (19H1715)`
- **Poetry version**: `Poetry version 1.1.13`
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://github.com/kkirsche/poetry-remove-untracked
    - This is a full repo with a `before` and `after` tag with reproduction steps in the `README.md`

## Issue
I expect the `--remove-untracked` flag to remove versions of the root package that no longer match the pyproject.toml file.

By not removing these files, if the project uses `importlib.metadata.version`, this will return an incorrect version number even though the pip installation is aware that a later version is the newest.

**Comment by jclerman** [comment] 2022-02-16 22:26
I encountered this exact issue earlier this week. Not clear if the described effect on `importlib_metadata` (or `importlib.metadata`, depending on the Python version) should also be considered a bug in that library - but regardless, making `--remove--untracked` behave as requested would make its results more deterministic, which is a Good Thing.

**Comment by kkirsche** [comment] 2022-02-17 01:44
> I encountered this exact issue earlier this week. Not clear if the described effect on `importlib_metadata` (or `importlib.metadata`, depending on the Python version) should also be considered a bug in that library - but regardless, making `--remove--untracked` behave as requested would make its results more deterministic, which is a Good Thing.

I’ve filed https://bugs.python.org/issue46774 To understand if they consider this a bug in the upstream Python language.

**Comment by finswimmer** [comment] 2022-02-22 14:33
Hello,

this is a duplicate of https://github.com/python-poetry/poetry/issues/3289, which is already solved by https://github.com/python-poetry/poetry/pull/3900

fin swimmer

**Closed by finswimmer** 2022-02-22 14:33 UTC
Labels: Bug, Triage

**Comment by kkirsche** [comment] 2022-02-22 15:18
When will this be in the released poetry version if it was already solved?

**Comment by jaraco** [comment] 2022-03-13 18:36
Looks like it's included with 1.2.0a1 and later.

**Comment by AlexAurand** [comment] 2022-03-31 16:33
@jaraco Is there a tentative release date for poetry 1.2?

**Comment by jaraco** [comment] 2022-03-31 23:17
I don't maintain this project; I hope someone else knows.

**Comment by AlexAurand** [comment] 2022-04-06 17:40
@finswimmer Is there a tentative release date for poetry 1.2?
