### ISSUE TITLE
Support poetry venvs per python full version

### ISSUE THREAD

**Issue by johnklehm** [python-poetry/poetry#2884] opened 2020-09-04 20:27 UTC
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

As far as I can tell poetry current allows a venv per python major version, e.g. py3.7, py3.8.  I'm hoping for a little tighter control when testing between minor python versions and would like the option to have the venv created per python minor version.

E.g.
```
$ rg 'python = ' pyproject.toml
14:python = "3.7.7"
```
```
$ poetry env use $(pyenv prefix 3.7.7)/bin/python
Creating virtualenv myproject-nkpQrFJt-py3.7 in /home/john/.cache/pypoetry/virtualenvs
Using virtualenv: /home/john/.cache/pypoetry/virtualenvs/myproject-nkpQrFJt-py3.7
```
```
$ sed -i 's/python = "3.7.7"/python = "3.7.9"/' pyproject.toml
```

```
$ poetry env use $(pyenv prefix 3.7.9)/bin/python
Recreating virtualenv myproject-nkpQrFJt-py3.7 in /home/john/.cache/pypoetry/virtualenvs/myproject-nkpQrFJt-py3.7
Using virtualenv: /home/john/.cache/pypoetry/virtualenvs/myproject-nkpQrFJt-py3.7
```
```
$ poetry env list                                                                                                                                                                                    
myproject-nkpQrFJt-py3.7 (Activated)
```

With this request I'm hoping the env use 3.7.9 variant would create a second venv dedicated to that python minor version instead of squashing the existing 3.7.7 venv...e.g. there would now be two items listed from `poetry env list`

**Comment by finswimmer** [comment] 2022-10-05 12:22
Duplicate of https://github.com/python-poetry/poetry/issues/2619

**Closed by finswimmer** 2022-10-05 12:22 UTC
Labels: kind/feature, status/triage
