### ISSUE TITLE
poetry export generates wrong boolean restrictions 

### ISSUE THREAD

**Issue by MichaelAquilina** [python-poetry/poetry#2623] opened 2020-07-03 09:58 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- ~[ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).~ Not an exception

- **OS version and name**: Linux OpenSUSE tumbleweed (Occurs on Mac and other Linux distros too though)
- **Poetry version**: 1.0.9
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/MichaelAquilina/7a18dbc33a14ca42d8028ebac41b9af2

Because the contents of the pyproject.toml at each point probably is important, I've also created a public repo with a commit showing the dependency addition at each stage: https://github.com/MichaelAquilina/poetry-export-test

## Issue

Running export with the pyproject.toml provided in the gist link above generates boolean restrictions on packages that do not make sense. These boolean conditions also seem to change depending on what dependencies have been added.

The best way to show the issue is to start off with an empty poetry project

1) `poetry init` use all the defaults but choose not to add dependencies iteractively
2) `poetry add ipdb`
3) run `poetry export --without-hashes --format requirements.txt` and notice the line for `pexpect` shows

```
pexpect==4.8.0; python_version >= "3.4" and sys_platform != "win32"
```

This is perfectly reasonable and makes sense as a requirement.

4) `poetry add ipython`
5) run `poetry export --without-hashes --format requirements.txt` and notice the line for `pexpect` shows

```
pexpect==4.8.0; python_version >= "3.4" and sys_platform != "win32" or sys_platform != "win32"
```

Notice that this boolean condition doesn't make sense. All it boils down to is `sys_platform != "win32". The python version has suddenly been ignored

Also notice that the `ptyprocess` line shows

```
ptyprocess==0.6.0; python_version >= "3.4" and sys_platform != "win32"
```

I'm noting this because this will change considerably with the next steps

6) `poetry add hypothesis`
7) run `poetry export --without-hashes --format requirements.txt` and notice the line for `ptyprocess` has become this massive requirement that also doesnt make sense

```
ptyprocess==0.6.0; python_version >= "3.4" and sys_platform != "win32" or sys_platform != "win32" or python_version >= "3.4" and sys_platform != "win32" and (python_version >= "3.4" and sys_platform != "win32" or sys_platform != "win32")
```

**Comment by MichaelAquilina** [comment] 2020-07-12 16:16
Been trying to do a bit of digging to see if I can find open a PR to fix this issue. Till now I've managed to figure out that the problem is not the export command, but seems to be something to do with the way the packages are stored in `poetry.lock`.

Here is the entry of `ptyprocess` in `poetry.lock` at the end:

```toml
[[package]]
category = "main"
description = "Run a subprocess in a pseudo terminal"
marker = "python_version >= \"3.4\" and sys_platform != \"win32\" or sys_platform != \"win32\" or python_version >= \"3.4\" and sys_platform != \"win32\" and (python_version >= \"3.4\" and sys_platform != \"win32\" or sys_platform != \"win32\")"
name = "ptyprocess"
optional = false
python-versions = "*"
version = "0.6.0"`
```

**Comment by eblume** [comment] 2020-07-20 20:46
Thank you @MichaelAquilina , we've just noticed this same behavior with `ptyprocess`. I am not sure how we got there, but our lockfile presently has the following:

```
[[package]]
category = "dev"
description = "Run a subprocess in a pseudo terminal"
marker = "python_version >= \"3.4\" and sys_platform != \"win32\" or sys_platform != \"win32\""
name = "ptyprocess"
optional = false
python-versions = "*"
version = "0.6.0"
```

From that state, if I run `poetry update ptyprocess`, I get this diff:

```
diff --git a/poetry.lock b/poetry.lock
index 9567512bca..32247d9934 100644
--- a/poetry.lock
+++ b/poetry.lock
@@ -1210,7 +1210,7 @@ version = "2.8.5"
 [[package]]
 category = "dev"
 description = "Run a subprocess in a pseudo terminal"
-marker = "python_version >= \"3.4\" and sys_platform != \"win32\" or sys_platform != \"win32\""
+marker = "python_version >= \"3.4\" and sys_platform != \"win32\" or sys_platform != \"win32\" or python_version >= \"3.4\" and sys_platform != \"win32\" and (python_version >= \"3.4\" and sys_platform != \"win32\" or sys_platform != \"win32\")"
 name = "ptyprocess"
 optional = false
 python-versions = "*"
@@ -1282,7 +1282,6 @@ version = "2.6.0"
 [[package]]
 category = "main"
 description = "C parser in Python"
-marker = "platform_python_implementation == \"CPython\" and sys_platform == \"win32\""
 name = "pycparser"
 optional = false
 python-versions = ">=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*"
```

Note that there is a second marker change in `pycparser` which gets dropped, I can't tell if this is a relevant issue. Also, to reiterate your observation, `ptyprocess` is a dependency of `pexpect` which is a dependency of `ipython`. ipython does not expose any marker in my lockfile, so I don't think it's simply an issue of root-level ("parent") packages exporting their markers to their children, which was my first thought.

I will attempt to create a test for this case to see if we can move a fix forward. This isn't necessarily blocking for us, but it has caused some concern, especially since the marker does seem to be droping the `python_version` platform due to broken marker logic.

**Comment by eblume** [comment] 2020-07-20 20:48
Adding for emphasis to the above: my reproduction above is purely from running `poetry update ptyprocess`, so I don't think this issue is tied to any one command.

**Comment by MichaelAquilina** [comment] 2020-10-05 11:01
FWIW this may have been fixed in poetry 1.1.1 @sdispater

**Comment by finswimmer** [comment] 2020-10-05 18:52
Thanks for your response @MichaelAquilina. So I'm closing this. If someone disagree, just leave a comment.

**Closed by finswimmer** 2020-10-05 18:52 UTC
Labels: Bug, Triage

**Comment by fish-face** [comment] 2021-07-23 11:05
I am experiencing something like this by adding the dependencies `bcrypt` and `gevent`. It looks like `gevent` only needs `cffi` on the `win32` platform, whilst `bcrypt` always needs it. But the exported requirements file contains the line:

```
cffi==1.14.6; platform_python_implementation == "CPython" and sys_platform == "win32" and (python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.5.0") and python_version >= "3.6" \
```

Notice two things: the python version conditions amount to just saying ">= 3.6" and the platform requirement applies to everything, whereas since `bcrypt` needs it also on other platforms, this should not be present.
