### ISSUE TITLE
poetry install partially broken after introducing --isolated

### ISSUE THREAD

**Issue by moltob** [python-poetry/poetry#7182] opened 2022-12-12 14:31 UTC
https://github.com/python-poetry/poetry/pull/6531 added the `--isolated` flag to the pip invocation. This seems to be breaking installation in certain situations.

Our analysis suggests this is the reason:

* Poetry 1.3 started passing `--isolated` to pip.
* The new switch results in ignoring all user configurations, like a `PIP_INDEX_URL` or a user-local `pip.conf` file.
* Since poetry is not passing the configured index to pip (related to https://github.com/python-poetry/poetry/issues/3249?), pip is now called without any index configuration.
* pip wants to build the wheel for the installed package.
* Packages may have additional `setup_requires` dependencies needed for building them.
* pip tries downloading those. Since there is no index config, pip attempts to use the default, PyPI.
* On machines with without internet access (like enterprise build machines), this fails.

Workaround: Create a non-user configuration, e.g. in `/etc/pip.conf`.

In a way the new switch stopped shadowing the issue that the index config is not passed to pip, that's why this is surfacing now.

I'd appreciate some feedback how the developer team sees that issue.

**Comment by neersighted** [comment] 2022-12-12 14:37
This is indeed a duplicate of #3249. As you have noted, if you really want to perturb the behavior of pip as used by Poetry, one must alter the system config. This is because many users configure pip in ways incompatible with Poetry, use of `--isolated` breaks fewer people.

Our long term plan is #6205. Please direct any more discussion to #3249.

**Closed by neersighted** 2022-12-12 14:37 UTC
