### ISSUE TITLE
Allow optional compilation of C extensions

### ISSUE THREAD

**Issue by teknico** [python-poetry/poetry#2330] opened 2020-04-20 21:28 UTC
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

This issue is prompted by a [suggestion](https://github.com/python-poetry/poetry/issues/11#issuecomment-612249998):

> I'd recommend creating a new issue detailing shortcomings of the current implementations with as much details as possible please.

## Feature Request

This is in reference to issue #11. The [tinydecred](https://github.com/decred/tinydecred/) project uses Poetry, and we're trying to add a Cython-generated extension to speed up the code in one of the Python files, using the undocumented feature mentioned in issue #11.

Here's the `build.py` file we're using:

```python
try:
    from Cython.Build import cythonize
except ImportError:
    def build(setup_kwargs):
        pass
else:
    def build(setup_kwargs):
        setup_kwargs.update(
            {"ext_modules": cythonize(["decred/crypto/secp256k1/field.py"])}
        )
```

A problem we have is that we'd like to ignore the error that happens if the developer does not have a C compiler installed and they execute the `poetry install` command ([example](https://github.com/decred/tinydecred/pull/160#issuecomment-616649340)).

(Ignoring such errors is the correct behavior in this case because the C extension is generated by Cython from a Python file and a matching `.pxd` file. If the compiled dynamic library is not there, the interpreter will just use the Python file.)

Thanks.

**Comment by abn** [comment] 2020-04-20 23:27
If this is the desired behaviour, wouldn't it be cleaner and more explicit to wrap the build step in a try catch within the `build.py`?

**Comment by teknico** [comment] 2020-04-20 23:33
Indeed, and that's what we [ended up doing](https://github.com/decred/tinydecred/blob/62326dce4211bbc340196b4c7cfb17d2795b7b4d/decred/build.py).

Still a workaround though, so we'll be happy to eventually see official support of non-Python extensions in Poetry.

**Comment by abn** [comment] 2020-04-20 23:47
Fair enough. Within the frame of current implementation, I'd consider that the solution for now.

That said, we should consider this if we end up further integrating support for C extensions.

**Comment by Secrus** [comment] 2023-06-05 16:28
Closing as duplicate of #1351

**Closed by Secrus** 2023-06-05 16:28 UTC
Labels: kind/feature
