### ISSUE TITLE
poetry and pyenv don't work well together

### ISSUE THREAD

**Issue by MrGreenTea** [python-poetry/poetry#172] opened 2018-06-01 13:08 UTC
I am using pyenv to manage my python versions and virtualenvs. This seems to cause some problems with poetry. 

```bash
>> which python
~/.pyenv/shims/python
>> which pip
~/.pyenv/shims/pip
>> poetry run which python
~/.cache/pypoetry/virtualenvs/XXXXX-py3.6/bin/python
>> poetry run which pip
~/.pyenv/shims/pip
```

This seems to cause the issue, that packages are installed in to the python version set by pyenv, but the python interpreter is used from the poetry virtualenv. This is no problem, when I activate the virtualenv first and then run `poetry install` 
But if I want to rely on poetry's automatic virtualenv management, this doesn't work anymore.

If you need more info I'll gladly provide it.

Thanks for your great work and tool, it's a real pleasure to work with :)

**Comment by tkossak** [comment] 2018-06-07 12:51
Would like to use it with pyenv too. For me it doesn't install in pyenv python:

```
> mkdir /tmp/2                                                                                                                                    
> cd /tmp/2                                                                                                                                       
> pyenv shell 3.6.5                                                                                                                     
> pyenv version                                                                                                                         
3.6.5 (set by PYENV_VERSION environment variable)

> pyenv which python                                                                                                                    
/home/kossak/.pyenv/versions/3.6.5/bin/python

> python -VV                                                                                                                            
Python 3.6.5 (default, Apr 25 2018, 13:20:33) 
[GCC 5.4.0 20160609]

> pip -V                                                                                                                                
pip 9.0.3 from /home/kossak/.pyenv/versions/3.6.5/lib/python3.6/site-packages (python 3.6)

> wget https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py                                                          
--2018-06-07 14:47:40--  https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.112.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.112.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9670 (9,4K) [text/plain]
Saving to: ‘get-poetry.py’

get-poetry.py                           100%[=============================================================================>]   9,44K  --.-KB/s    in 0s      

2018-06-07 14:47:41 (37,0 MB/s) - ‘get-poetry.py’ saved [9670/9670]


> python get-poetry.py                                                                                                                  
Retrieving metadata

Installing version: 0.10.3
  - Getting dependencies
  - Vendorizing dependencies
  - Installing poetry

poetry (0.10.3) successfully installed!

> poetry new test                                                                                                                       
poetry: command not found

> pip freeze | grep poetry                                                                                                        127  
You are using pip version 9.0.3, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
poetry==0.10.3

> which poetry                                                                                                                          
>

```

**Comment by ariebovenberg** [comment] 2018-06-29 18:11
I've had this same issue. For me, it only works if I tell `pyenv` to use the `system` python version:

```fish
curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | env PYENV_VERSION=system python
```

Installed this way, the `poetry` command is available everywhere. @tkossak does this work for you?

**Comment by jacebrowning** [comment] 2018-06-29 19:07
That worked for me. We should probably put this in the docs as it shouldn't hurt anyone **not** using `pyenv`.

**Comment by hwine** [comment] 2018-06-30 00:38
@MrGreenTea fwiw, I found a workaround. _(It may also identify the possible code issue.)_ I noticed that ``poetry install`` _was_ working -- it just installed the packages into the python's environment, instead of into the virtual environment poetry had just created.

First, I used [``pipsi``](https://pypi.org/project/pipsi/) to install python tools I want globally accessible -- I find it avoids a lot of the problems that arise with complex pyenv setups.

Second, prior to running ``poetry install``, I manually activated poetry's virtual environment before running the command (I also pushed into a sub-shell to minimize side effects):
```sh
$ bash
$ . ~/.local/venvs/poetry/bin/activate
$ which python pip
/home/hwine/.local/venvs/poetry/bin/python
/home/hwine/.local/venvs/poetry/bin/pip
$ poetry install
Updating dependencies
Resolving dependencies... (0.8s)


Package operations: 6 installs, 0 updates, 0 removals

Writing lock file

  - Installing pygments (2.2.0)
  - Installing urwid (2.0.1)
  - Installing agithub (2.1)
  - Installing pudb (2018.1)
  - Installing pyyaml (3.12)
  - Installing tinydb (3.9.0.post1)
$ exit
```
You'll notice that there's now a "compatible" pip as the default.

I haven't done it yet, but I suspect I can create a shell function to combine these steps (except, of course, for ``poetry run``). (If so, I'll update this.)

**Comment by tkossak** [comment] 2018-06-30 09:36
I tried installing it using pipsi and it seems it is installed correctly.
```
> pipsi install poetry
Running virtualenv with interpreter /home/kossak/.local/venvs/pipsi/bin/python
Using base prefix '/home/kossak/.pyenv/versions/3.6.5'
New python executable in /home/kossak/.local/venvs/poetry/bin/python
Installing setuptools, pip, wheel...done.
Collecting poetry
  Using cached https://files.pythonhosted.org/packages/06/fe/b496c2f37e0571b5893b0f561aa596636879aafdcbcf8baa29ac13643903/poetry-0.11.1-py2.py3-none-any.whl
Collecting cleo<0.7.0,>=0.6.7 (from poetry)
  Using cached https://files.pythonhosted.org/packages/a7/b9/270301a3a87587f09bc3985973f2e362ffa45fa5fcd5128501516b2f5e31/cleo-0.6.8-py2.py3-none-any.whl
Collecting cachy<0.3,>=0.2 (from poetry)
  Using cached https://files.pythonhosted.org/packages/26/37/8ce3e7b330078b6797a34e79a80a8ad6935e404a3b903765417182c9ce19/cachy-0.2.0-py2.py3-none-any.whl
Collecting html5lib<2.0,>=1.0 (from poetry)
  Using cached https://files.pythonhosted.org/packages/a5/62/bbd2be0e7943ec8504b517e62bab011b4946e1258842bc159e5dfde15b96/html5lib-1.0.1-py2.py3-none-any.whl
Collecting shellingham<2.0,>=1.1 (from poetry)
  Using cached https://files.pythonhosted.org/packages/21/a5/5b13e906824294d1a5f3cc91ed5789f7871f8e277f24830c2dd0c54a150e/shellingham-1.1.0-py2.py3-none-any.whl
Collecting requests-toolbelt<0.9.0,>=0.8.0 (from poetry)
  Using cached https://files.pythonhosted.org/packages/97/8a/d710f792d6f6ecc089c5e55b66e66c3f2f35516a1ede5a8f54c13350ffb0/requests_toolbelt-0.8.0-py2.py3-none-any.whl
Collecting pkginfo<2.0,>=1.4 (from poetry)
  Using cached https://files.pythonhosted.org/packages/a3/fe/f32a48d48f40a7209be9825fba2566cab92364787cf37de2e08300dd6ce7/pkginfo-1.4.2-py2.py3-none-any.whl
Collecting requests<3.0,>=2.18 (from poetry)
  Using cached https://files.pythonhosted.org/packages/65/47/7e02164a2a3db50ed6d8a6ab1d6d60b69c4c3fdf57a284257925dfc12bda/requests-2.19.1-py2.py3-none-any.whl
Collecting pytoml<0.2.0,>=0.1.16 (from poetry)
  Using cached https://files.pythonhosted.org/packages/71/a2/a5c13282c081624703aa43b22530a4c928839c25b96aa7466e5d127c9dd9/pytoml-0.1.18.tar.gz
Collecting pyrsistent<0.15.0,>=0.14.2 (from poetry)
  Using cached https://files.pythonhosted.org/packages/a0/e0/72d0a6bd199505d26011a4f22857553fd6e86b9d93374aca0e56ffcc2a1b/pyrsistent-0.14.3.tar.gz
Collecting cachecontrol[filecache]<0.13.0,>=0.12.4 (from poetry)
  Using cached https://files.pythonhosted.org/packages/5e/f0/2c193ed1f17c97ae539da7e1c2d48b80d8cccb1917163b26a91ca4355aa6/CacheControl-0.12.5.tar.gz
Collecting pyparsing<3.0,>=2.2 (from poetry)
  Using cached https://files.pythonhosted.org/packages/6a/8a/718fd7d3458f9fab8e67186b00abdd345b639976bc7fb3ae722e1b026a50/pyparsing-2.2.0-py2.py3-none-any.whl
Collecting jsonschema<3.0,>=2.6 (from poetry)
  Using cached https://files.pythonhosted.org/packages/77/de/47e35a97b2b05c2fadbec67d44cfcdcd09b8086951b331d82de90d2912da/jsonschema-2.6.0-py2.py3-none-any.whl
Collecting pylev<2.0,>=1.3 (from cleo<0.7.0,>=0.6.7->poetry)
  Using cached https://files.pythonhosted.org/packages/40/1c/7dff1d242bf1e19f9c6202f0ba4e6fd18cc7ecb8bc85b17b2d16c806e228/pylev-1.3.0-py2.py3-none-any.whl
Collecting pastel<0.2.0,>=0.1.0 (from cleo<0.7.0,>=0.6.7->poetry)
  Using cached https://files.pythonhosted.org/packages/9b/7e/7d701686013c0d7dae62e0977467232a6adc2e562c23878eb3cd4f97d02e/pastel-0.1.0-py3-none-any.whl
Collecting six>=1.9 (from html5lib<2.0,>=1.0->poetry)
  Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting webencodings (from html5lib<2.0,>=1.0->poetry)
  Using cached https://files.pythonhosted.org/packages/f4/24/2a3e3df732393fed8b3ebf2ec078f05546de641fe1b667ee316ec1dcf3b7/webencodings-0.5.1-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests<3.0,>=2.18->poetry)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests<3.0,>=2.18->poetry)
  Using cached https://files.pythonhosted.org/packages/7c/e6/92ad559b7192d846975fc916b65f667c7b8c3a32bea7372340bfe9a15fa5/certifi-2018.4.16-py2.py3-none-any.whl
Collecting urllib3<1.24,>=1.21.1 (from requests<3.0,>=2.18->poetry)
  Using cached https://files.pythonhosted.org/packages/bd/c9/6fdd990019071a4a32a5e7cb78a1d92c53851ef4f56f62a3486e6a7d8ffb/urllib3-1.23-py2.py3-none-any.whl
Collecting idna<2.8,>=2.5 (from requests<3.0,>=2.18->poetry)
  Using cached https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl
Collecting msgpack (from cachecontrol[filecache]<0.13.0,>=0.12.4->poetry)
  Using cached https://files.pythonhosted.org/packages/22/4e/dcf124fd97e5f5611123d6ad9f40ffd6eb979d1efdc1049e28a795672fcd/msgpack-0.5.6-cp36-cp36m-manylinux1_x86_64.whl
Collecting lockfile>=0.9 (from cachecontrol[filecache]<0.13.0,>=0.12.4->poetry)
  Using cached https://files.pythonhosted.org/packages/c8/22/9460e311f340cb62d26a38c419b1381b8593b0bb6b5d1f056938b086d362/lockfile-0.12.2-py2.py3-none-any.whl
Building wheels for collected packages: pytoml, pyrsistent, cachecontrol
  Running setup.py bdist_wheel for pytoml ... done
  Stored in directory: /home/kossak/.cache/pip/wheels/22/39/f8/40b79ff765ccf2ca4d221f5f109e8f5926fef7a06653623f1c
  Running setup.py bdist_wheel for pyrsistent ... done
  Stored in directory: /home/kossak/.cache/pip/wheels/2e/03/95/ba4b9035e3d69c56695ef5f9ab4ea59ccc20aff4dce8856839
  Running setup.py bdist_wheel for cachecontrol ... done
  Stored in directory: /home/kossak/.cache/pip/wheels/36/bd/5f/dbbee4f2d51f97ecd12a363f870361179cb1fd4bc1174ea08a
Successfully built pytoml pyrsistent cachecontrol
Installing collected packages: pylev, pastel, cleo, cachy, six, webencodings, html5lib, shellingham, chardet, certifi, urllib3, idna, requests, requests-toolbelt, pkginfo, pytoml, pyrsistent, msgpack, lockfile, cachecontrol, pyparsing, jsonschema, poetry
Successfully installed cachecontrol-0.12.5 cachy-0.2.0 certifi-2018.4.16 chardet-3.0.4 cleo-0.6.8 html5lib-1.0.1 idna-2.7 jsonschema-2.6.0 lockfile-0.12.2 msgpack-0.5.6 pastel-0.1.0 pkginfo-1.4.2 poetry-0.11.1 pylev-1.3.0 pyparsing-2.2.0 pyrsistent-0.14.3 pytoml-0.1.18 requests-2.19.1 requests-toolbelt-0.8.0 shellingham-1.1.0 six-1.11.0 urllib3-1.23 webencodings-0.5.1
  Linked script /home/kossak/.local/bin/poetry
Done.

> which poetry
/home/kossak/.local/bin/poetry

> poetry --version
Poetry 0.11.1
```

I will test further to see if it also works correctly.

**Comment by ariebovenberg** [comment] 2018-06-30 09:38
@tkossak I guess `pipsi` is the way to go then.

I think the `pyenv` approach worked for me because the `system` python is actually the one installed with `homebrew`, which doesn't require root priviledges.

**Comment by tkossak** [comment] 2018-06-30 09:57
But something doesn't look good - it's the same case as in first post in this thread:
```
> poetry new .
Created package 1 in .

> poetry run which python
Creating virtualenv 1-py3.6 in /home/kossak/.cache/pypoetry/virtualenvs
/home/kossak/.cache/pypoetry/virtualenvs/1-py3.6/bin/python

> poetry run which pip
/home/kossak/.pyenv/shims/pip
```

`python` points to virtualenv python, but `pip` points to pyenv shim. Shouldn't `pip` point to virtualenv too?

**Comment by cauebs** [comment] 2018-06-30 16:01
If you're using pipsi to install poetry, make sure you're using the latest version available, from the git repository, because the one on PyPI is about three years old.

`pip install -U --user git+https://github.com/mitsuhiko/pipsi/`

The old version always uses virtualenv, even if you're on Python 3, and that messes the venv module up.

**Comment by sdispater** [comment] 2018-06-30 17:12
I am currently using `pyenv` on MacOS and I don't have any problem making it working.

I didn't do anything special, I only have this on my `.zshrc`:

```zsh
# pyenv
export PYENV_ROOT=/usr/local/var/pyenv

if [[ -z "$VIRTUAL_ENV" ]]; then
    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"
fi
```

**Comment by tkossak** [comment] 2018-07-09 14:08
@cauebs Thank you. I installed development version of pipsi and then used it to install poetry from pip. The first signs are good:

```
> pipsi --version
pipsi, version 0.10.dev0, python /home/kossak/.pyenv/versions/3.6.5/bin/python3.6
> poetry --version
Poetry 0.11.2
> poetry new .
Created package 1 in .
> poetry run which python
Creating virtualenv 1-py3.6 in /home/kossak/.cache/pypoetry/virtualenvs
/home/kossak/.cache/pypoetry/virtualenvs/1-py3.6/bin/python
> poetry run which pip
/home/kossak/.cache/pypoetry/virtualenvs/1-py3.6/bin/pip
```

**Comment by tkossak** [comment] 2018-07-12 12:55
And I even managed to get it to work with pyenv but i'm not sure how :). Maybe because I reinstalled pyenv and this time set different python as my "system" one (different than anaconda).

**Comment by nchammas** [comment] 2018-08-02 02:46
FYI: I reported a similar issue in #354 and provided some steps to reproduce it. Basically, Poetry hiccups when the Python version it's running under differs from the Python version currently active in the environment.

**Comment by nackjicholson** [comment] 2018-10-17 18:35
I use `pyenv` and I am getting inconsistent behavior between `poetry run` and `poetry shell`.

```
nackjicholson@Williams-MacBook-Pro-7> which python
/Users/nackjicholson/.pyenv/shims/python
nackjicholson@Williams-MacBook-Pro-7> python --version
Python 3.6.6
nackjicholson@Williams-MacBook-Pro-7> poetry run python --version
Python 3.6.6
nackjicholson@Williams-MacBook-Pro-7> poetry run which python
/Users/nackjicholson/Library/Caches/pypoetry/virtualenvs/source-data-service-py3.6/bin/python
nackjicholson@Williams-MacBook-Pro-7> poetry run which pip
/Users/nackjicholson/Library/Caches/pypoetry/virtualenvs/source-data-service-py3.6/bin/pip
nackjicholson@Williams-MacBook-Pro-7> poetry shell
Spawning shell within /Users/nackjicholson/Library/Caches/pypoetry/virtualenvs/source-data-service-py3.6
nackjicholson@Williams-MacBook-Pro-7> which pip
/Users/nackjicholson/.pyenv/shims/pip
nackjicholson@Williams-MacBook-Pro-7> which python
/Users/nackjicholson/.pyenv/shims/python
nackjicholson@Williams-MacBook-Pro-7>
```

**Comment by anpr** [comment] 2019-04-29 09:02
Just to give my feedback here, I'm new to poetry and encountered issues when using pyenv and poetry together. Basically, it installed packages to a newly created virtualenv directory that was then nowhere to be found, poetry shell didn't work, etc.

I installed poetry using `curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python`. My python used there is python 3.7.1 from ~/.pyenv/shims/python. Then I went to my code repository, activated my pyenv virtualenv, executed `poetry install` and had the problems mentioned above.

I'm just commenting here, because I believe there is some underlying issue here that's not fixed.

**Comment by LuRsT** [comment] 2019-05-19 20:08
Extra feedback on this issue, I'm new to both `pyenv` and `poetry`, here are the steps to reproduce my environment.

```
$ pyenv local 2.7.16
$ which python
/home/lurst/.pyenv/shims/python
$ poetry shell
Spawning shell within ...
$ which python
/home/lurst/.pyenv/shims/python
$ ⏎  ( Ctrl+D to exit shell)
$ poetry run which python
/home/lurst/.cache/pypoetry/virtualenvs/myproject/bin/python
```

**Comment by tkossak** [comment] 2019-08-21 07:52
If people are still having issues with pyenv I suggest switching from pyenv to [asdf](https://github.com/asdf-vm/asdf). It can manage versions of not only python and for me works perfectly fine with poetry.

**Comment by mnrce** [comment] 2019-09-21 16:32
> If people are still having issues with pyenv I suggest switching from pyenv to [asdf](https://github.com/asdf-vm/asdf). It can manage versions of not only python and for me works perfectly fine with poetry.

I switched to `asdf` and still having the same issue as https://github.com/sdispater/poetry/issues/172#issuecomment-493787520

**Comment by tkossak** [comment] 2019-09-23 07:53
I meant it works in reference to the original problem OP had (see first post). Poetry and asdf works this way:
```
$ which python
/home/kossak/.asdf/shims/python
$ which pip
/home/kossak/.asdf/shims/pip
$ poetry run which python
/home/kossak/.cache/pypoetry/virtualenvs/kossak-search-py3.7/bin/python
$ poetry run which pip
/home/kossak/.cache/pypoetry/virtualenvs/kossak-search-py3.7/bin/pip
```

Alongside with all `poetry install` / `poetry add` commands.

As for `poetry shell` - it also doesn't work for me (but I don't use it actually in my workflow, so I didn't even notice it).

**Comment by ntrepid8** [comment] 2019-10-09 14:21
I encountered this issue when using the `get-poetry.py` installer, but when I just use `pip install poetry` from my `pyenv global` environment, everything seems to work fine.

**Comment by ClaytonJY** [comment] 2019-10-28 21:25
I would _love_ to see a system-level poetry installation detect and use `pyenv` automatically. To me, the only things `Pipenv` is still superior at is installation & venv management: if you have `pyenv` configured, even a `pipx`-installed `pipenv` will "do the right thing" via `pipenv install --python 3.7`, while for `poetry` I can only use the curl installation method, and I still have to resort to tricks like `pyenv local 3.7.4 && poetry env use $(pyenv which python)` in order to use python 3.7.

**Comment by kierun** [comment] 2019-10-29 07:54
I use `pyenv` and `pyenv virtualenv` which alongside `poetry` have been good. More integration would be nice but I wonder if it is not an edge case.

**Comment by AdamGold** [comment] 2019-11-06 18:45
I have been having trouble with using `poetry` with versions that are not my global `pyenv` version. To get around this, I use `python3.6 -m venv venv` and then use poetry as simply a package manager and not a virtualenv. For my global Python, which is `3.8`, I use `poetry` as usual.

**Comment by pochemuto** [comment] 2019-12-05 16:21
`poetry shell` spawns a new shell adding a new folder to PATH env variable. But new shell also loads all rc scripts like .bash_profile. That file likely has pyenv initialization line
`eval "$(pyenv init -)"` that overrides venv python

Avoiding initializing pyenv within spawned shell works for me.

```bash
if [ -z "$PYENV_INITIALIZED" ]; then
   eval "$(pyenv init -)"
   export PYENV_INITIALIZED=1
fi
```

**Comment by abratnap** [comment] 2020-01-24 16:53
Deleting `.python-version` on every other base directory than project works.. 

`/Users/abc/based-dir/project-dir/` 

Then I deleted the `/Users/abc/.python-version` and `/Users/abc/based-dir/.python-version`
Just kept ``/Users/abc/based-dir/project-dir/.python-version`

**Comment by finswimmer** [comment] 2020-02-06 17:36
The original issue seems to be solved in the meantime. So I will close this.

**Closed by finswimmer** 2020-02-06 17:36 UTC
Labels: Bug
