### ISSUE TITLE
Installing dependency from downloaded wheel ignores platform specifier

### ISSUE THREAD

**Issue by Interpause** [python-poetry/poetry#5644] opened 2022-05-19 07:36 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Gentoo Linux
- **Poetry version**: 1.2.0b1

## Issue

When installing dependency from a local wheel, the platform specifier is ignored.

```toml
netifaces = { path = "netifaces-0.11.0-cp39-cp39-win_amd64.whl", platform = "win32" }
```

Poetry attempts to install `netifaces` from the win32 wheel, which fails because the installation is on Linux. I made sure to run `poetry lock --no-update` beforehand.

**Comment by abn** [comment] 2022-05-19 11:57
I am unable to reproduce this issue. Unsure if this has something to do with the python installation on Gentoo?

```sh
podman run --rm -i --entrypoint bash docker.io/python:3.8 <<EOF
set -xe
python -m pip install --disable-pip-version-check -q --pre poetry
poetry new foobar
pushd foobar
wget https://files.pythonhosted.org/packages/d7/6c/d24d9973e385fde1440f6bb83b481ac8d1627902021c6b405f9da3951348/netifaces-0.11.0-cp38-cp38-win_amd64.whl
poetry add --platform=win32 ./netifaces-0.11.0-cp38-cp38-win_amd64.whl
poetry install -vvv
EOF
```

<details>
<summary><b>console output:</b></summary>
<p>

```console
+ python -m pip install --disable-pip-version-check -q --pre poetry
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
+ poetry new foobar
Created package foobar in foobar
+ pushd foobar
/foobar /
+ wget https://files.pythonhosted.org/packages/d7/6c/d24d9973e385fde1440f6bb83b481ac8d1627902021c6b405f9da3951348/netifaces-0.11.0-cp38-cp38-win_amd64.whl
--2022-05-19 11:55:18--  https://files.pythonhosted.org/packages/d7/6c/d24d9973e385fde1440f6bb83b481ac8d1627902021c6b405f9da3951348/netifaces-0.11.0-cp38-cp38-win_amd64.whl
Resolving files.pythonhosted.org (files.pythonhosted.org)... 151.101.1.63, 151.101.65.63, 151.101.129.63, ...
Connecting to files.pythonhosted.org (files.pythonhosted.org)|151.101.1.63|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 16449 (16K) [application/octet-stream]
Saving to: ‘netifaces-0.11.0-cp38-cp38-win_amd64.whl’

     0K .......... ......                                     100% 6.28M=0.002s

2022-05-19 11:55:18 (6.28 MB/s) - ‘netifaces-0.11.0-cp38-cp38-win_amd64.whl’ saved [16449/16449]

+ poetry add --platform=win32 ./netifaces-0.11.0-cp38-cp38-win_amd64.whl
Creating virtualenv foobar-lWDpn5M1-py3.8 in /root/.cache/pypoetry/virtualenvs

Updating dependencies
Resolving dependencies...

Writing lock file
+ poetry install -vvv
Using virtualenv: /root/.cache/pypoetry/virtualenvs/foobar-lWDpn5M1-py3.8
Installing dependencies from lock file

Finding the necessary packages for the current system

Installing the current project: foobar (0.1.0)
  - Building package foobar in editable mode
  - Adding foobar.pth to /root/.cache/pypoetry/virtualenvs/foobar-lWDpn5M1-py3.8/lib/python3.8/site-packages for /foobar
  - Adding the foobar-0.1.0.dist-info directory to /root/.cache/pypoetry/virtualenvs/foobar-lWDpn5M1-py3.8/lib/python3.8/site-packages
```

</p>
</details>

**Comment by Interpause** [comment] 2022-05-22 07:53
![Screenshot_20220522_155041](https://user-images.githubusercontent.com/42513874/169684659-3dfe1004-598c-47da-81f2-f3ce149f89f5.png)

Above is the reproduction of my issue. Based on how it skipped `rich` but did not skip `netifaces`, it suggests the `platform` option is ignored when the wheel path is specified.

**Comment by neersighted** [comment] 2022-10-04 07:13
Does not reproduce for me on 1.2.1 either -- closing for now.

**Closed by neersighted** 2022-10-04 07:13 UTC
Labels: kind/bug, area/installer, status/needs-reproduction
