### ISSUE TITLE
Add awareness of pip installed packages

### ISSUE THREAD

**Issue by ketozhang** [python-poetry/poetry#3006] opened 2020-09-30 19:25 UTC
Poetry is not aware of accidental/purposeful use of `pip` to install packages

```
$ poetry init
$ poetry add tqdm
$ poetry shell
$ pip install numpy # e.g., user did this accidentally 
```

**Actual**
```
$ poetry lock && poetry install
$ poetry show
tqdm 4.50.0 Fast, Extensible Progress Meter
```

**Expected**
```
$ poetry lock && poetry install
$ poetry show
tqdm 4.50.0 Fast, Extensible Progress Meter
numpy 1.19.2 NumPy is the fundamental package for array computing with Python.
```

I understand this is very difficult to support currently and the current design recommends user to avoid `pip` in favor of installing via `poetry`. However, in peculiar cases (e.g., syntax conventions), sometimes install via poetry is not possible/easy and pip is preferred to be used.

**Comment by malcolmgreaves** [comment] 2020-10-01 00:40
This is actually expected behavior: nothing is wrong here.

Your project will be installed in an isolated virutalenv. When you do `pip install numpy`, that installs it to the system-wide environment -- **not** the project environment.

You don't want to have your project dependencies intermingled with your system, or other project, dependencies. This is a core design feature of poetry and it won't be changed.

**Comment by ketozhang** [comment] 2020-10-01 02:31
My apologies, I forgot to mention the pip install is ran inside the virtual env. Will edit the example.

**Comment by n8sty** [comment] 2020-10-02 02:11
I think the suggested behavior would actually add a fair bit of difficulty to working on a poetry managed project. Sometimes I'll `pip install ipython` into a poetry managed virtual environment because I want to use a fancier REPL or pip install a dependency to play with some additional functionality that I may or may not want added to as a project dependency. If each of these actions automagically added a dependency, I'd have to remember to revert `pyproject.toml` and `poetry.lock`. I like the current behavior because it's explicit. When I add a new dependency I `poetry add`, and that's it. I think this proposal might lead to a fair bit of commit reverts because dependencies were erroneously added.

**Comment by ketozhang** [comment] 2020-10-02 02:18
Good point @n8sty, it looks like what I'm really looking for is to be able to undo a pip install operation without needing to know its name similar to pipenv's has the clean command. Unfortunately `poetry install` is not able to restore the environment.

**Comment by finswimmer** [comment] 2020-10-02 04:40
> It looks like what I'm really looking for is to be able to undo pip install operation(s) without needing to know its name similar to pipenv's clean command.

`$ poetry install --remove-untracked` ?

**Comment by malcolmgreaves** [comment] 2020-10-02 16:21
@ketozhang My apologies -- I totally did not see the `poetry shell` and completely misunderstood!

**Comment by ketozhang** [comment] 2020-10-02 16:24
No worries, as I've edited that in after your comment so your confusion was my fault

**Comment by ketozhang** [comment] 2020-10-07 07:38
> `$ poetry install --remove-untracked` ?

@finswimmer 
Thanks! I've missed this having outdated poetry. Is it possible to make this behavior the default when running bare `poetry install`? My expectation is always "Python environment should always match the environment specification file". I wonder if this is a golden rule for poetry?

**Comment by finswimmer** [comment] 2020-10-07 09:49
> Is it possible to make this behavior the default when running bare poetry install (maybe alias it to poetry [clean|sync]?

There is already a feature request for this: https://github.com/python-poetry/poetry/issues/2370 We haven't finally discussed it until now.

**Comment by phiresky** [comment] 2021-01-31 02:41
In my opinion it would be best if pip would be aliased to something that just errors with "use poetry add to install packages". If I'm working together with others not familiar with poetry, they will inevitably use pip install and then wonder why the tool I've upsold them so greatly loses all of the dependency they add.

**Comment by finswimmer** [comment] 2021-12-29 19:34
The original issue seems to solved by `poetry install --remove-untracked` (or `poetry install --sync` from 1.2.0 on).

**Closed by finswimmer** 2021-12-29 19:34 UTC
Labels: Feature, Triage
