### ISSUE TITLE
Fail to run `poetry add` via ssh

### ISSUE THREAD

**Issue by y-marui** [python-poetry/poetry#7400] opened 2023-01-24 04:02 UTC
- **Poetry version**: 1.3.2
- **Python version**: 3.11.1
- **OS version and name**: Host Widows 11 22H2, Client macOS 13.1（22C65）
- **pyproject.toml**: https://gist.github.com/y-marui/0159a3119455119b14b498fd7307e6a7#file-pyproject-toml

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
I hosted Windows 11 on my Parallels Desktop.
`ssh` itself is working and I successed to run `poetry init`.
However, I failed to run `poetry add numpy` (`poetry add autopep8` and `poetry add pre-commit` also resulted in the same error).

```
> poetry add numpy -vvv
Loading configuration file C:\Users\username\AppData\Roaming\pypoetry\config.toml
Creating virtualenv test in C:\Users\username\src\github.com\y-marui\test\.venv
Using virtualenv: C:\Users\username\src\github.com\y-marui\test\.venv

  Stack trace:

  4  ~\.pyenv\pyenv-win\versions\3.11.1\Lib\site-packages\win32ctypes\pywin32\pywintypes.py:35 in pywin32error
       33│ def pywin32error():
       34│     try:
    →  35│         yield
       36│     except WindowsError as exception:
       37│         raise error(exception.winerror, exception.function, exception.strerror)

  3  ~\.pyenv\pyenv-win\versions\3.11.1\Lib\site-packages\win32ctypes\pywin32\win32cred.py:66 in CredRead
       64│         if _backend == 'cffi':
       65│             ppcreds = _authentication.PPCREDENTIAL()
    →  66│             _authentication._CredRead(TargetName, Type, flag, ppcreds)
       67│             pcreds = _common.dereference(ppcreds)
       68│         else:

  2  ~\.pyenv\pyenv-win\versions\3.11.1\Lib\site-packages\win32ctypes\core\cffi\_authentication.py:145 in _CredRead
      143│ def _CredRead(TargetName, Type, Flags, ppCredential):
      144│     target = make_unicode(TargetName)
    → 145│     value = check_zero(
      146│         dlls.advapi32.CredReadW(target, Type, Flags, ppCredential),
      147│         u'CredRead')

  1  ~\.pyenv\pyenv-win\versions\3.11.1\Lib\site-packages\win32ctypes\core\cffi\_util.py:81 in __call__
       79│     def __call__(self, value, function_name=''):
       80│         if value == self._check:
    →  81│             self._raise_error(function_name)
       82│         else:
       83│             return value

  OSError

  [WinError 1312] 指定されたログオン セッションは存在しません。そのセッションは既に終了している可能性があります。

  at ~\.pyenv\pyenv-win\versions\3.11.1\Lib\site-packages\win32ctypes\core\cffi\_util.py:92 in _raise_error
       88│         exception.errno = ffi.errno
       89│         exception.winerror = code
       90│         exception.strerror = message
       91│         exception.function = function_name
    →  92│         raise exception
       93│
       94│
       95│ check_null = ErrorWhen(ffi.NULL)
       96│ check_zero = ErrorWhen(0)

The following error occurred when trying to handle this error:


  Stack trace:

  30  ~\.pyenv\pyenv-win\versions\3.11.1\Lib\site-packages\cleo\application.py:327 in run
       325│
       326│             try:
     → 327│                 exit_code = self._run(io)
       328│             except BrokenPipeError:
       329│                 # If we are piped to another process, it may close early and send a

  29  ~\.pyenv\pyenv-win\versions\3.11.1\Lib\site-packages\poetry\console\application.py:190 in _run
       188│         self._load_plugins(io)
       189│
     → 190│         exit_code: int = super()._run(io)
       191│         return exit_code
       192│

  28  ~\.pyenv\pyenv-win\versions\3.11.1\Lib\site-packages\cleo\application.py:431 in _run
       429│             io.input.interactive(interactive)
       430│
     → 431│         exit_code = self._run_command(command, io)
       432│         self._running_command = None
       433│

  27  ~\.pyenv\pyenv-win\versions\3.11.1\Lib\site-packages\cleo\application.py:473 in _run_command
       471│
       472│         if error is not None:
     → 473│             raise error
       474│
       475│         return terminate_event.exit_code

  26  ~\.pyenv\pyenv-win\versions\3.11.1\Lib\site-packages\cleo\application.py:457 in _run_command
       455│
       456│             if command_event.command_should_run():
     → 457│                 exit_code = command.run(io)
       458│             else:
       459│                 exit_code = ConsoleCommandEvent.RETURN_CODE_DISABLED

  25  ~\.pyenv\pyenv-win\versions\3.11.1\Lib\site-packages\cleo\commands\base_command.py:119 in run
       117│         io.input.validate()
       118│
     → 119│         status_code = self.execute(io)
       120│
       121│         if status_code is None:

  24  ~\.pyenv\pyenv-win\versions\3.11.1\Lib\site-packages\cleo\commands\command.py:62 in execute
        60│
        61│         try:
     →  62│             return self.handle()
        63│         except KeyboardInterrupt:
        64│             return 1

  23  ~\.pyenv\pyenv-win\versions\3.11.1\Lib\site-packages\poetry\console\commands\add.py:158 in handle
       156│             return 0
       157│
     → 158│         requirements = self._determine_requirements(
       159│             packages,
       160│             allow_prereleases=self.option("allow-prereleases"),

  22  ~\.pyenv\pyenv-win\versions\3.11.1\Lib\site-packages\poetry\console\commands\init.py:373 in _determine_requirements
       371│             elif "version" not in requirement:
       372│                 # determine the best version automatically
     → 373│                 name, version = self._find_best_version_for_package(
       374│                     requirement["name"],
       375│                     allow_prereleases=allow_prereleases,

  21  ~\.pyenv\pyenv-win\versions\3.11.1\Lib\site-packages\poetry\console\commands\init.py:408 in _find_best_version_for_package
       406│
       407│         selector = VersionSelector(self._get_pool())
     → 408│         package = selector.find_best_candidate(
       409│             name, required_version, allow_prereleases=allow_prereleases, source=source
       410│         )

  20  ~\.pyenv\pyenv-win\versions\3.11.1\Lib\site-packages\poetry\version\version_selector.py:39 in find_best_candidate
        37│             },
        38│         )
     →  39│         candidates = self._pool.find_packages(dependency)
        40│         only_prereleases = all(c.version.is_unstable() for c in candidates)
        41│

  19  ~\.pyenv\pyenv-win\versions\3.11.1\Lib\site-packages\poetry\repositories\repository_pool.py:136 in find_packages
       134│         packages: list[Package] = []
       135│         for repo in self.repositories:
     → 136│             packages += repo.find_packages(dependency)
       137│         return packages
       138│

  18  ~\.pyenv\pyenv-win\versions\3.11.1\Lib\site-packages\poetry\repositories\repository.py:42 in find_packages
        40│         ignored_pre_release_packages = []
        41│
     →  42│         for package in self._find_packages(dependency.name, constraint):
        43│             if package.yanked and not isinstance(constraint, Version):
        44│                 # PEP 592: yanked files are always ignored, unless they are the only

  17  ~\.pyenv\pyenv-win\versions\3.11.1\Lib\site-packages\poetry\repositories\pypi_repository.py:112 in _find_packages
       110│         """
       111│         try:
     → 112│             json_page = self.get_page(name)
       113│         except PackageNotFound:
       114│             self._log(f"No packages found for {name}", level="debug")

  16  ~\.pyenv\pyenv-win\versions\3.11.1\Lib\site-packages\poetry\repositories\pypi_repository.py:215 in _get_page
       213│     def _get_page(self, name: NormalizedName) -> SimpleJsonPage:
       214│         source = self._base_url + f"simple/{name}/"
     → 215│         info = self.get_package_info(name)
       216│         return SimpleJsonPage(source, info)
       217│

  15  ~\.pyenv\pyenv-win\versions\3.11.1\Lib\site-packages\poetry\repositories\pypi_repository.py:103 in get_package_info
       101│         or retrieved from the remote server.
       102│         """
     → 103│         return self._get_package_info(name)
       104│
       105│     def _find_packages(

  14  ~\.pyenv\pyenv-win\versions\3.11.1\Lib\site-packages\poetry\repositories\pypi_repository.py:127 in _get_package_info
       125│     def _get_package_info(self, name: str) -> dict[str, Any]:
       126│         headers = {"Accept": "application/vnd.pypi.simple.v1+json"}
     → 127│         info = self._get(f"simple/{name}/", headers=headers)
       128│         if info is None:
       129│             raise PackageNotFound(f"Package [{name}] not found.")

  13  ~\.pyenv\pyenv-win\versions\3.11.1\Lib\site-packages\poetry\repositories\pypi_repository.py:222 in _get
       220│     ) -> dict[str, Any] | None:
       221│         try:
     → 222│             json_response = self.session.get(
       223│                 self._base_url + endpoint,
       224│                 raise_for_status=False,

  12  ~\.pyenv\pyenv-win\versions\3.11.1\Lib\site-packages\poetry\utils\authenticator.py:278 in get
       276│
       277│     def get(self, url: str, **kwargs: Any) -> requests.Response:
     → 278│         return self.request("get", url, **kwargs)
       279│
       280│     def post(self, url: str, **kwargs: Any) -> requests.Response:

  11  ~\.pyenv\pyenv-win\versions\3.11.1\Lib\site-packages\poetry\utils\authenticator.py:219 in request
       217│         headers = kwargs.get("headers")
       218│         request = requests.Request(method, url, headers=headers)
     → 219│         credential = self.get_credentials_for_url(url)
       220│
       221│         if credential.username is not None or credential.password is not None:

  10  ~\.pyenv\pyenv-win\versions\3.11.1\Lib\site-packages\poetry\utils\authenticator.py:342 in get_credentials_for_url
       340│                 # no credentials were provided in the url, try finding the
       341│                 # best repository configuration
     → 342│                 self._credentials[url] = self._get_credentials_for_url(url)
       343│             else:
       344│                 # Split from the right because that's how urllib.parse.urlsplit()

   9  ~\.pyenv\pyenv-win\versions\3.11.1\Lib\site-packages\poetry\utils\authenticator.py:303 in _get_credentials_for_url
       301│
       302│         credential = (
     → 303│             self._get_credentials_for_repository(repository=repository)
       304│             if repository is not None
       305│             else HTTPAuthCredential()

   8  ~\.pyenv\pyenv-win\versions\3.11.1\Lib\site-packages\poetry\utils\authenticator.py:291 in _get_credentials_for_repository
       289│
       290│         if key not in self._credentials:
     → 291│             self._credentials[key] = repository.get_http_credentials(
       292│                 password_manager=self._password_manager, username=username
       293│             )

   7  ~\.pyenv\pyenv-win\versions\3.11.1\Lib\site-packages\poetry\utils\authenticator.py:112 in get_http_credentials
       110│         if credential.password is None:
       111│             # fallback to url and netloc based keyring entries
     → 112│             credential = password_manager.keyring.get_credential(
       113│                 self.url, self.netloc, username=credential.username
       114│             )

   6  ~\.pyenv\pyenv-win\versions\3.11.1\Lib\site-packages\poetry\utils\password_manager.py:51 in get_credential
        49│
        50│         for name in names:
     →  51│             credential = keyring.get_credential(name, username)
        52│             if credential:
        53│                 return HTTPAuthCredential(

   5  ~\.pyenv\pyenv-win\versions\3.11.1\Lib\site-packages\keyring\core.py:72 in get_credential
        70│ ) -> typing.Optional[credentials.Credential]:
        71│     """Get a Credential for the specified service."""
     →  72│     return get_keyring().get_credential(service_name, username)
        73│
        74│

   4  ~\.pyenv\pyenv-win\versions\3.11.1\Lib\site-packages\keyring\backends\Windows.py:167 in get_credential
       165│         # get any first password under the service name
       166│         if not res:
     → 167│             res = self._get_password(service)
       168│             if not res:
       169│                 return None

   3  ~\.pyenv\pyenv-win\versions\3.11.1\Lib\site-packages\keyring\backends\Windows.py:108 in _get_password
       106│     def _get_password(self, target):
       107│         try:
     → 108│             res = win32cred.CredRead(
       109│                 Type=win32cred.CRED_TYPE_GENERIC, TargetName=target
       110│             )

   2  ~\.pyenv\pyenv-win\versions\3.11.1\Lib\site-packages\win32ctypes\pywin32\win32cred.py:63 in CredRead
        61│
        62│     flag = 0
     →  63│     with _pywin32error():
        64│         if _backend == 'cffi':
        65│             ppcreds = _authentication.PPCREDENTIAL()

   1  ~\.pyenv\pyenv-win\versions\3.11.1\Lib\contextlib.py:155 in __exit__
       153│                 value = typ()
       154│             try:
     → 155│                 self.gen.throw(typ, value, traceback)
       156│             except StopIteration as exc:
       157│                 # Suppress StopIteration *unless* it's the same exception that

  error

  (1312, 'CredRead', '指定されたログオン セッションは存在しません。そのセッションは既に終了している可能性があります。')

  at ~\.pyenv\pyenv-win\versions\3.11.1\Lib\site-packages\win32ctypes\pywin32\pywintypes.py:37 in pywin32error
       33│ def pywin32error():
       34│     try:
       35│         yield
       36│     except WindowsError as exception:
    →  37│         raise error(exception.winerror, exception.function, exception.strerror)
       38│
```

**Comment by neersighted** [comment] 2023-01-24 05:31
More-or-less a duplicate of #1917, but in an edge case where the current session is not connected to the Windows Credential service. The workaround is the same -- disable the keyring backend. Note that you will not have any access to credentials stored in WinCred by design of Windows itself.

**Closed by neersighted** 2023-01-24 05:31 UTC
Labels: kind/bug, status/triage
