### ISSUE TITLE
(🐞) Glitch when poetry tries to find a different version of python for the project

### ISSUE THREAD

**Issue by KotlinIsland** [python-poetry/poetry#7090] opened 2022-11-24 06:02 UTC
- **Poetry version**:  1.2.2
- **Python version**:  3.11
- **OS version and name**:  Windows 10
- **pyproject.toml**: 
```toml
[tool.poetry]
name = "poetry-test"
version = "0.1.0"
description = ""
authors = [""]

[tool.poetry.dependencies]
python = "~3.10"
```

- [🚀] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [🚀] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [🚀] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [🚀] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

```
👉 poetry install
The currently activated Python version 3.11.0 is not supported by the project (~3.10).
Trying to find and use a compatible version.
Using python3.10 (3.10.8)
Creating virtualenv poetry-test-RGMhFuFN-py3.10 in C:\Users\AMONGUS\AppData\Local\pypoetry\Cache\virtualenvs

[WinError 2] The system cannot find the file specified: 'C:/Users/AMONGUS/projects/poetry-test/python3.10'    
```

**Comment by neersighted** [comment] 2022-11-24 06:07
This is well-known, though I can't find the original issue to duplicate right now. This is because Poetry currently naively tries to find Python version X.Y by executing `pythonX.Y`; this works on Unix as the convention there is to install a versioned Python executable (and symlink `python`/`python3` to your preferred version), but fails on Windows.

We can use the `py.exe` wrapper, or pythonfinder, or similar; one of these options is needed to resolve this. Please let me know if you can find the duplicate, as this topic has already been discussed at length several times.

**Comment by KotlinIsland** [comment] 2022-11-24 06:33
What's strange here though is that it correctly found the installed python 3.10.8. And strangely it tried to execute the python exe in the current directory

`~\projects\poetry-test\python.3.10`

**Comment by KotlinIsland** [comment] 2022-11-24 06:41
related to #3520

**Comment by neersighted** [comment] 2022-11-24 10:29
Aha, this is a duplicate of #2117 -- there's no explicit `env use` here, but the code path is the same for `env use` or auto-selection of a compatible Python (once the version has been determined).

**Closed by neersighted** 2022-11-24 10:29 UTC
Labels: kind/bug, status/triage
