### ISSUE TITLE
Adding a transitive path dependency throws exception

### ISSUE THREAD

**Issue by roxchkplusony** [python-poetry/poetry#3203] opened 2020-10-14 14:34 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS Catalina 10.15.7 (19H2)
- **Poetry version**: 1.1.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/roxchkplusony/3c0349e6d15fa601672c6e570ae3d477

## Issue
1. `mkdir poetry-test-proj && cd poetry-test-proj`
2. `poetry new commons && poetry new lib && poetry new svc`
3. `cd lib && poetry add ../commons && cd ..`
4. `cd svc && poetry add ../lib && cd ..` 

Exception log:
```
  • Installing lib (0.1.0 /Users/victor/poetry-demo/lib): Pending...
  • Installing lib (0.1.0 /Users/victor/poetry-demo/lib): Building...
  • Installing lib (0.1.0 /Users/victor/poetry-demo/lib): Failed

  EnvCommandError

  Command ['/Users/victor/Library/Caches/pypoetry/virtualenvs/svc-3tVC9GWN-py3.8/bin/pip', 'install', '--no-deps', '-U', '/Users/victor/poetry-demo/lib'] errored with the following return code 1, and output: 
  Looking in indexes: https://artifactory.int.datarobot.com/artifactory/api/pypi/python-all/simple
  Processing /Users/victor/poetry-demo/lib
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
      Preparing wheel metadata: started
      Preparing wheel metadata: finished with status 'error'
      ERROR: Command errored out with exit status 1:
       command: /Users/victor/Library/Caches/pypoetry/virtualenvs/svc-3tVC9GWN-py3.8/bin/python /Users/victor/Library/Caches/pypoetry/virtualenvs/svc-3tVC9GWN-py3.8/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/vg/4y775k9j7y559wds0_xvyh2w0000gq/T/tmp8a0susmn
           cwd: /private/var/folders/vg/4y775k9j7y559wds0_xvyh2w0000gq/T/pip-req-build-7c127cdv
      Complete output (16 lines):
      Traceback (most recent call last):
        File "/Users/victor/Library/Caches/pypoetry/virtualenvs/svc-3tVC9GWN-py3.8/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
          main()
        File "/Users/victor/Library/Caches/pypoetry/virtualenvs/svc-3tVC9GWN-py3.8/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/victor/Library/Caches/pypoetry/virtualenvs/svc-3tVC9GWN-py3.8/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 133, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/private/var/folders/vg/4y775k9j7y559wds0_xvyh2w0000gq/T/pip-build-env-_w7lokmp/overlay/lib/python3.8/site-packages/poetry/core/masonry/api.py", line 34, in prepare_metadata_for_build_wheel
          poetry = Factory().create_poetry(Path(".").resolve())
        File "/private/var/folders/vg/4y775k9j7y559wds0_xvyh2w0000gq/T/pip-build-env-_w7lokmp/overlay/lib/python3.8/site-packages/poetry/core/factory.py", line 91, in create_poetry
          self.create_dependency(name, constraint, root_dir=package.root_dir)
        File "/private/var/folders/vg/4y775k9j7y559wds0_xvyh2w0000gq/T/pip-build-env-_w7lokmp/overlay/lib/python3.8/site-packages/poetry/core/factory.py", line 242, in create_dependency
          dependency = DirectoryDependency(
        File "/private/var/folders/vg/4y775k9j7y559wds0_xvyh2w0000gq/T/pip-build-env-_w7lokmp/overlay/lib/python3.8/site-packages/poetry/core/packages/directory_dependency.py", line 36, in __init__
          raise ValueError("Directory {} does not exist".format(self._path))
      ValueError: Directory ../commons does not exist
      ----------------------------------------
  ERROR: Command errored out with exit status 1: /Users/victor/Library/Caches/pypoetry/virtualenvs/svc-3tVC9GWN-py3.8/bin/python /Users/victor/Library/Caches/pypoetry/virtualenvs/svc-3tVC9GWN-py3.8/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/vg/4y775k9j7y559wds0_xvyh2w0000gq/T/tmp8a0susmn Check the logs for full command output.
  

  at ~/.poetry/lib/poetry/utils/env.py:948 in _run
       944│                 output = subprocess.check_output(
       945│                     cmd, stderr=subprocess.STDOUT, **kwargs
       946│                 )
       947│         except CalledProcessError as e:
    →  948│             raise EnvCommandError(e, input=input_)
       949│ 
       950│         return decode(output)
       951│ 
       952│     def execute(self, bin, *args, **kwargs):

  • Installing pytest (5.4.3): Pending...
  • Installing pytest (5.4.3): Skipped for the following reason: Already installed

Failed to add packages, reverting the pyproject.toml file to its original content.
```

The situation is made better if the path dependency has develop=true, but as a related troubledness I do not understand how to make a path dependency in development but a package dependency in the sdist. I think that's a question asked multiple times and multiple ways elsewhere (principally: #1168, #2270).

**Comment by abn** [comment] 2020-10-14 16:57
@roxchkplusony this is expected behaviour as path dependencies are not included in the sdist of your first level dependency and an isolated build will fail because it is being built in a temporary directory. The exception is raised because the "../commons" directory is not longer in the expected location.

You could include the directory as part of your sdist. However, this will have to be in your project root.

```toml
include = [
    { path = "lib", format = "sdist" },
]
```

It is not clear what you mean by "make a path dependency in development but a package dependency in the sdist". I am assuming whatn you mean is that you want package `A` to depend on package `B`. However, when developing (locally), you want `B` to be `../some/path/to/B`.

For your use case, as you have identified, this is a duplicate of the broader conversation in #2270.

**Comment by sinoroc** [comment] 2020-10-22 21:18
@roxchkplusony Do we have a satisfying solution for this use case?

**Comment by roxchkplusony** [comment] 2020-10-23 04:12
Yes, I think we can close this for now.

**Comment by sinoroc** [comment] 2020-10-26 11:14
@roxchkplusony If you have the possibility, please close the ticket (I can not do it), this will make it easier for maintainers to keep an overview of what needs to be worked on. It can always be reopened later.

**Closed** 2020-10-30 05:29 UTC
Labels: Bug, Triage
