### ISSUE TITLE
Poetry blocks on "Pending..." during installation

### ISSUE THREAD

**Issue by AleCandido** [python-poetry/poetry#6050] opened 2022-07-22 07:53 UTC
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Often (in practice always) it happens that during `poetry install` some packages are blocked on `Pending...` for a long time. I guess it should be related to the requests to PyPI or something like.

In practice, the fastest way to install an environment is to run `poetry install`, wait for as long as there still packages installing, and when you're left with only `Pending...` packages, kill it and rerun.
I guess there should be a more proper way to obtain this without killing Poetry over and over...

**Comment by dimbleby** [comment] 2022-07-22 11:31
plausibly #6030, especially if you are in the habit of killing poetry while it is doing things.  Clear your cache.

**Comment by AleCandido** [comment] 2022-07-22 14:24
If I have to clear my cache every time the installation speed will decrease even more.

The problem is observed even on a fresh installation. And in any case, it's only a matter of speed: if I wait long enough, a single `poetry install` will eventually work. But if I kill it while doing things and rerun, then it will finish earlier.

**Comment by dimbleby** [comment] 2022-07-22 14:35
It's not clear what anyone should do about this: you've provided no way to reproduce your problem, and you don't want to try the thing that has a good chance of fixing it.

What action are you asking for?

**Comment by AleCandido** [comment] 2022-07-22 15:13
> (Clarification: the suggestion was not that you clear your cache every time, but that you clear it once to fix the problem)

I'm just telling you that I already did, on 3 different computers. Even reinstalling system from scratch. Simply it didn't change the behavior.

Way to reproduce:

1. run `poetry install` in one shell
2. in another shell run `poetry install` for as long as there are some `Installing...` packages; as soon as there are no one any longer, but only `Pending...`, kill it and rerun; repeat for as many times as needed

I'm saying that in case 2. it is sometimes finishing earlier (quite a lot), and I observed with many different lock files. I sum this on many other Poetry performance issues (already reported in other issues, check [here](https://github.com/python-poetry/poetry/issues/4924#issuecomment-1046290020) for a list), and this takes a lot of time to perform every day operations.

I'm not saying I'm observing it always, but it is simply happening over and over. If you wish next time it will happen I can upload also the corresponding lock file.

However, I am just reporting a feedback. If you don't care, no need to reply :)

**Comment by dimbleby** [comment] 2022-07-22 15:20
parallel poetry operations makes it sound ever more likely that this is related to #6030, in which a `.lock` file gets stuck in the cache, preventing poetry from proceeding.

However a repro that involves parallel installations and deliberate killing of processes isn't very interesting, the answer to that is simply: don't do that.

If you have a pyproject.toml which, on its own with no funny business as above, causes poetry to get stuck: then please share it.

**Comment by AleCandido** [comment] 2022-07-22 15:23
It doesn't get stuck, it's simply slower. Killing is the workaround to speed up, not the problem (that is speed without killing).

**Comment by dimbleby** [comment] 2022-07-22 15:26
If you have a pyproject.toml which, on its own with no funny business as above, causes poetry to get ~stuck~ slower: then please share it.

**Comment by AleCandido** [comment] 2022-07-22 15:40
This one ([pyproject.tar.gz](https://github.com/python-poetry/poetry/files/9169021/pyproject.tar.gz)) for example was causing the problem this morning.

But right now it's not a problem, at least on 2 machines for which it was. Without clearing any cache in the meanwhile.

That's why I believe it depends in the way Poetry reacts to the server response (or the network status, I'm on a different one right now). Unfortunately, server and network status are out of my scope, so if it happens again, I can notify again, but without any clean way to reproduce it.

I know it is hard to debug something that is not deterministically reproducible, that's why I said it was a feedback, and I classified as "Feature Request" rather than a bug. But the only other alternative was to provide no feedback, and drop Poetry if the things will repeat to frequently.

**Comment by dimbleby** [comment] 2022-07-22 15:48
Your server and network status are out of this project's scope as well...

Appreciate you taking the time to come here and report a problem; but right now it's hard to see how anyone can do anything with this.  

If you're able to clarify a concrete way in which poetry can be improved then by all means please update.  Else I suspect this is likely to sit here unloved until someone eventually does a sweep and closes it down.

**Comment by dimbleby** [comment] 2022-07-22 16:01
(conceivably helped by #5881, though this is plainly speculation.  You haven't said what poetry version you're using, but the latest beta is worth a try)

**Comment by skorokithakis** [comment] 2022-09-27 10:28
I am affected by this as well, and the problem started when I added a secondary index to my config. There's now this very odd behaviour where Poetry stops on one package, I kill it (ctrl-c), then run it again, goes past that package, freezes on the next one, kill, that one works, freezes on the next one, etc.

I think this has something to do with the secondary index code, but `-vvv` doesn't really say anything more than "Pending...". @AleCandido, do you have a secondary index as well?

**Comment by skorokithakis** [comment] 2022-09-27 11:21
I debugged this deep in the bowels of Poetry for the past hour, and it seems to be that PyPI simply hangs.

This hangs as well:

```
wget "https://files.pythonhosted.org/packages/3a/7d/9f8ac1b1b76f2f1538b5650f0b5636bae082724b1e06939a3a9d38e1380e/ipykernel-5.5.3-py3-none-any.whl#sha256=21abd584543759e49010975a4621603b3cf871b1039cb3879a14094717692614"
```

**Comment by skorokithakis** [comment] 2022-09-27 11:24
Yep:

```
*   Trying 2a04:4e42:400::319:443...
* Immediate connect fail for 2a04:4e42:400::319: Network is unreachable
*   Trying 2a04:4e42::319:443...
* Immediate connect fail for 2a04:4e42::319: Network is unreachable
*   Trying 2a04:4e42:600::319:443...
* Immediate connect fail for 2a04:4e42:600::319: Network is unreachable
*   Trying 2a04:4e42:200::319:443...
* Immediate connect fail for 2a04:4e42:200::319: Network is unreachable
```

So this wasn't a Poetry issue for me.

**Comment by neersighted** [comment] 2022-09-27 13:41
Closing this for now as the only instances reported are because of transient network conditions. Killing Poetry may result in a corrupt cache that gets things stuck further -- however, fixes for this are in 1.3 already.

**Closed by neersighted** 2022-09-27 13:41 UTC
Labels: kind/feature, status/triage

**Comment by Omegastick** [comment] 2023-01-19 11:58
I have this issue. It seems to occur after Poetry receives a `304` response from PyPI:
```
[urllib3.connectionpool] https://pypi.org:443 "GET /pypi/cachetools/5.2.1/json HTTP/1.1" 304 0
```

Clearing Poetry's cache presumably changes something about the request being sent and makes PyPI return `200`, then the package installs correctly.

**Comment by alpha-beta-soup** [comment] 2023-04-26 01:17
For what it's worth, I had this issue in Ubuntu 22.04 and a `poetry -vvv install` revealed that it was an issue with my keyring. Getting Python to ignore the keyring with `export PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring` (from this [SO Q&A](https://stackoverflow.com/questions/61947044/keyring-warning-when-running-pip-list-o)) solved my immediate installation issues.

**Comment by lephuongbg** [comment] 2023-05-05 11:06
Hitting the same issue with @Omegastick, poetry stucks on 304 response from PyPI. After clearing cache, poetry can install things normally again.
