### ISSUE TITLE
Inconsistent packaging between sdist and whl when source folder is called 'src' and additional directory is 'include'd

### ISSUE THREAD

**Issue by danieleades** [python-poetry/poetry#3673] opened 2021-02-10 11:56 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option). **NA**

- **ubuntu 20.04**: 
- **Poetry 1.1.4**: 

## Issue

Poetry seems to be producing sdist and `.whl` packages which are inconsistent, when the source directory is called `src`, and directories are explicitly included

steps to reproduce-

1. create a new package, with a `src/` directory - `poetry new my-cool-package --src`
2. have a directory in the `src/` folder which is ignored by a `.gitignore` file, but explicitly included in the `pyproject.toml` file
```toml
[tool.poetry]
include = "src/ignored-directory/*"
```
2. build the package `poetry build`
3. create another dummy package and add the first as a local dependency using either the .whl or the tarball

you can then observe that when depending on the tarball, the contents of the src directory are installed properly in the virtualenv in a folder named after the package, and containing all the files.

When depending on the *wheel* the explicitly included directory is installed under `src/<package-name>/` instead of `<package-name>/` (the rest of the files are installed in `<package-name>/`.

**Comment by danieleades** [comment] 2021-02-10 13:35
or, to put it another way- the files which are explicitly included maintain their relative paths in the wheel, instead of being transformed to account for the fact that the package is nested under a `src/` folder

**Comment by danieleades** [comment] 2021-02-10 13:38
as a workaround, it works if you change to the convention of storing source files under `<package-name>` instead of `src/<package-name>`

**Comment by finswimmer** [comment] 2021-02-11 16:53
Thank for reporting @danieleades. I can confirm it.

The issue is, that the included files a placed under a folder called `src/<package-name>` at the toplevel of the wheel file instead of `<package-name> just like the other files, which is obviously not correct.

fin swimmer

**Comment by finswimmer** [comment] 2021-02-11 17:31
Ok, this seems to be already fixed in poetry-core 1.0.2. So when you installing poetry via `pip` or `pipx` and try again it should work.

**Comment by danieleades** [comment] 2021-02-11 18:04
> Ok, this seems to be already fixed in poetry-core 1.0.2. So when you installing poetry via `pip` or `pipx` and try again it should work.

Is this not updated with `poetry self update`?

**Comment by finswimmer** [comment] 2021-02-13 08:18
`poetry self update` updates poetry if it was installed with  the installer script and if the version of poetry itself has changed.

In this case, the version of poetry hasn't change. Only one of it's dependencies (`poetry-core`), so it not gets updated. Also when you are using the installer script, the dependencies are pinned to a specific version. So I guess also a reinstall via the installer script will not work.

poetry 1.1.5 is near ;)

**Comment by nourwolf** [comment] 2021-02-15 16:15
@finswimmer Thanks for confirming that reinstalling Poetry using the script won't update `poetry-core` as I was just going to open an issue for that.

Our team currently uses the script and thus we are not able to update poetry-core to 1.0.2 which solved some dependency resolution issues related to RC versions.

Any suggestion on how to pin both Poetry and Poetry-Core versions? I understood that using pip is discouraged as it pins Poetry to the Python interpreter used for the installation.

**Closed** 2021-12-30 08:01 UTC
Labels: Bug, Triage
