### ISSUE TITLE
Unable to install llama-cpp-python with poetry

### ISSUE THREAD

**Issue by PierreCarceller** [python-poetry/poetry#9656] opened 2024-08-29 11:07 UTC
### Issue Kind

Brand new capability

### Description

Based on the llama-cpp-python installation documentation, if we want to install the lib with CUDA support (for example) we have 2 options : 

Pass a CMAKE env var : 
```bash
CMAKE_ARGS="-DGGML_CUDA=on" pip install llama-cpp-python
```

Or use the `--config-settings` argument of pip like this : 
```bash
pip install llama-cpp-python --config-settings cmake.args="-DGGML_CUDA=on"
```

As far as I know, it's not possible to do something equivalent with poetry because :

-  It's not possible to pass env var to poetry 
- Poetry has no equivalent to `--config-settings`

I saw that there had already been conversations on similar subject [here](https://github.com/python-poetry/poetry/issues/9323) but they date from a while and maybe things have changed in the meantime?

I understand that **pip** and **poetry** are two different projects with different objectives, but it would be really useful (from my point of view) to be able to handle this kind of installation. 

### Impact

As I see it, llama-cpp-python will become an important lib in the python ecosystem (it probably already is to some extent).

In addition, llama-cpp-python is not the only one to use the `--config-settings` functionality for installation.  

That's why I think it would be interesting to be able to allow a fluid installation with poetry.

### Workarounds

There is a workaround as explained [here](https://stackoverflow.com/questions/77534091/how-can-i-install-llama-cpp-python-with-cublas-using-poetry)

``` bash
poetry run pip install llama-cpp-python --upgrade --force-reinstall --no-cache-dir
```

But it's not very practical because it breaks the poetry workflow.

**Comment by dimbleby** [comment] 2024-08-29 12:01
> It's not possible to pass env var to poetry

but the conclusion in #9323 was that environment variables _are_ passed through and so this already worked?

request for config-settings duplicates #8909, https://github.com/python-poetry/poetry-core/pull/715

**Comment by dimbleby** [comment] 2024-08-29 16:07
as in #9323 I retried it myself and it is clear from the error messages that the environment variable is indeed passed to the build

also as in #9323 you perhaps have an already-built wheel in your cache

**Comment by PierreCarceller** [comment] 2024-08-30 07:31
"perhaps have an already-built wheel in your cache" -> I thought that if I reset the environment and set the "--no-cache" flag, this wouldn't happen. Can you tell me more ?

I will test it with docker to be sure and post my results here in the next few days

**Comment by dimbleby** [comment] 2024-08-30 07:35
`--no-cache` does not affect the artifact cache. 

This is now just a straight duplicate of #9323

**Closed** 2024-09-15 14:10 UTC
Labels: kind/feature, status/triage
