### ISSUE TITLE
multiple package versions locked

### ISSUE THREAD

**Issue by chargr** [python-poetry/poetry#7399] opened 2023-01-23 23:02 UTC
- **Poetry version**: 1.3.2 (verified issue exists in 1.2.2 as well)
- **Python version**: 3.8.16/3.9.16
- **OS version and name**: CentOS 6
- **pyproject.toml**: reproduce with one package in fresh project `poetry add statsmodels`

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
This appears to be an issue resulting from the platform specific scipy restrictions within statsmodels.
passing --platform does not trickle down to the dependency markers
selecting scipy 1.8.x should be valid for all platforms, but ideally we can select 1.10 on linux.
the scipy packages themselves within the lock are not restricted to a platform.

multiple scipy versions selected
```
poetry add --platform linux -vvv --lock statsmodels
```

I see this in the output:
```
   0: Duplicate dependencies for scipy
   0: Different requirements found for scipy (>=1.3) with markers (python_version > "3.9" or platform_system != "Windows" or platform_machine != "x86") and python_version < "3.12" and scipy (>=1.3,<1.9) with markers python_version == "3.9" and platform_system == "Windows" and platform_machine == "x86".
```

```
$ cat poetry.lock | grep 'name = "scipy' -A2
name = "scipy"
version = "1.8.1"
description = "SciPy: Scientific Library for Python"
--
name = "scipy"
version = "1.10.0"
description = "Fundamental algorithms for scientific computing in Python"
```

This results in an error when trying to export to a requirements.txt
```
poetry export --without-hashes -f requirements.txt

Dependency walk failed at scipy (>=1.3,<1.9)
```

this also results in multiple scipy versions selected
```
poetry add --platform linux -vvv --lock hpbandster
```

this package will result in multiple statmodels
```
poetry add --platform linux -vvv --lock pyod
```

```
$ cat poetry.lock | grep 'name = "statsmodels' -A2
name = "statsmodels"
version = "0.13.2"
description = "Statistical computations and models for Python"
--
name = "statsmodels"
version = "0.13.3"
description = "Statistical computations and models for Python"
--
name = "statsmodels"
version = "0.13.4"
description = "Statistical computations and models for Python"
--
name = "statsmodels"
version = "0.13.5"
description = "Statistical computations and models for Python"
[0]
```

**Comment by dimbleby** [comment] 2023-01-24 00:03
poetry builds cross-platform lockfiles and it is completely normal for different versions of the same package to appear.

**Comment by dimbleby** [comment] 2023-01-24 00:08
and the poetry export failure should be a duplicate of https://github.com/python-poetry/poetry-plugin-export/issues/163

so there's nothing left here.

**Comment by chargr** [comment] 2023-01-24 01:27
my expectation that was the poetry.lock would not have ambiguous version information.
dependencies have markers, why dont the main package entries?

i am parsing poetry data for my own (unique?) use case.  it seems then that the consumer should start with the pyproject.toml and evaluate markers for packages and then look those up in the poetry.lock and then uses the latest valid version listed.

i think i can work with this... i may have had the wrong approach...

thanks.

**Comment by neersighted** [comment] 2023-01-24 01:32
The lock file is not self-descriptive, and never has been. #1301 is the feature request for a self-descriptive format.

**Closed by neersighted** 2023-01-24 01:32 UTC
Labels: kind/bug, status/triage
