### ISSUE TITLE
Check path to the python file in tool.poetry.scripts

### ISSUE THREAD

**Issue by RalfKow** [python-poetry/poetry#7655] opened 2023-03-16 07:28 UTC
## Feature Request
Would it somehow be possible to check whether the string is valid defined in the pyproject.toml f.e
[tool.poetry.scripts]
extract-day-ahead-prices="raw_sampleapp.feeds.extract_day_ahead_prices:cli"

**Comment by dimbleby** [comment] 2023-03-16 16:55
there's currently no mechanism in poetry to introspect the source code of the project being managed, adding this function seems unlikely to happen.

**Comment by finswimmer** [comment] 2024-10-30 20:58
Duplicate of #3333

**Closed by finswimmer** 2024-10-30 20:58 UTC
Labels: kind/feature, status/triage, area/scripts
