### ISSUE TITLE
pip install -t equivalent 

### ISSUE THREAD

**Issue by jasonkuhrt** [python-poetry/poetry#1174] opened 2019-06-18 14:31 UTC
When working with serverless, (but surely other contexts too), we run a script essentially like so:

```
#!/usr/bin/env bash
set -e

export PIP_EXTRA_INDEX_URL=https://pypi.fury.io/${GEMFURY_TOKEN}/foobar
poetry export --format requirements.txt --without-hashes
poetry run pip install -r requirements.txt . --target package
rm requirements.txt

cd package
find . -name "*.pyc" -delete
zip -9 -r ../package.zip .
cd ..
rm -fr package

npx sls deploy
```

It would be great if poetry had the ability to output packages itself so that we could e.g.:

```
poetry install --target package
zip -9 -r package.zip package
npx sls deploy
rm package.zip
```

I couldn't find a pre-existing issue for this but also finding it surprising this issue wouldn't have come up yet. So maybe my title phrasing is off or this is already possible?

**Comment by brno32** [comment] 2019-06-27 02:45
You want it to output just a single package, or is `package` the target destination like it is with `pip -t`?

**Comment by jasonkuhrt** [comment] 2019-06-27 13:07
@brno32 I guess was thinking it to work like `pip -t`. But, it would be cool if poetry can go further on the dx here.

**Comment by brno32** [comment] 2019-06-28 04:33
https://github.com/brno32/poetry/tree/brno32-issue/1174

Is my implementation useful for you? Would make a PR but I'm stuck on the test I'm trying to write

**Comment by jasonkuhrt** [comment] 2019-06-28 13:00
@brno32 yeah maybe, would have to try it; Seems right!

**Comment by brno32** [comment] 2019-06-28 14:52
Cool. Let me know how it works if you do. I'll try and make a PR this weekend

**Comment by finswimmer** [comment] 2021-12-29 17:39
Duplicate of https://github.com/python-poetry/poetry/issues/1937

**Closed by finswimmer** 2021-12-29 17:39 UTC
Labels: Feature
