### ISSUE TITLE
poetry run gives a cryptic FileNotFoundError if the command does not exist

### ISSUE THREAD

**Issue by SeriousBug** [python-poetry/poetry#3883] opened 2021-04-06 21:53 UTC
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Consider the following run:

```
$ poetry run does-not-exist

  FileNotFoundError

  [Errno 2] No such file or directory

  at /usr/lib/python3.9/os.py:607 in _execvpe
       603│         path_list = map(fsencode, path_list)
       604│     for dir in path_list:
       605│         fullname = path.join(dir, file)
       606│         try:
    →  607│             exec_func(fullname, *argrest)
       608│         except (FileNotFoundError, NotADirectoryError) as e:
       609│             last_exc = e
       610│         except OSError as e:
       611│             last_exc = e
```

This is confusing to look at. It would make sense to provide an actual error message if a package is missing. Something like the following would be much better:

```
$ poetry run does-not-exist

Error: Command does-not-exist doesn't exist. Please check that it is installed, and that the command name is spelled correctly.
```

**Comment by dimaqq** [comment] 2021-07-21 05:40
The label should be `bug` or `cleanup` or maybe `improvement`. Not a `feature` 🤔

**Comment by pbsds** [comment] 2022-02-17 10:11
Related: #4963

**Comment by branchvincent** [comment] 2022-02-27 06:36
Appreciate the report! There are quite a few issues around this so I'm going to mark it as a duplicate of #1567, but note I'm currently working on a fix

**Closed by branchvincent** 2022-02-27 06:36 UTC
Labels: Feature, Triage
