### ISSUE TITLE
1.1.3 poetry export command result in Maximum recursion depth exceeded

### ISSUE THREAD

**Issue by SakornW** [python-poetry/poetry#3266] opened 2020-10-22 03:53 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10, Can be also reproduce using docker image: python:3.7-alpine
- **Poetry version**: 1.1.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml and poetry.lock file**: https://gist.github.com/SakornW/35ac772b85cb8435e2209b97a348fb04
- **Stack trace**: https://gist.github.com/SakornW/8ff428039e7c05ed3010ddea609a0e1b 

## Issue
- Using the pyproject.toml and poetry.lock file, `poetry export -vvv` got stuck and end up with `Maximum recursion depth exceeded` error. (The same occur with `poetry export --without-hashes -f requirements.txt > requirements.txt` command)
- Delete poetry.lock file and re-lock the poetry.lock file doesn't improve the situation.
- `poetry install` doesn't have this issue.

## workaround
- downgrade to poetry 1.1.2

**Comment by abn** [comment] 2020-10-22 06:38
Duplicate of #3213

**Closed** 2020-10-22 06:38 UTC
Labels: Duplicate
