### ISSUE TITLE
PEP 440 Check Failed when using poetry config virtualenvs.create false

### ISSUE THREAD

**Issue by yaq-cc** [python-poetry/poetry#5976] opened 2022-07-08 15:08 UTC
Hi team,

I'm trying to use Poetry within a Docker container that's using ubuntu:focal as the base image.  In the container, I can install poetry without a hitch but stopping poetry from using a virtual environment with `poetry config virtualenvs.create false` causes a PEP 440 warning.

Here's the Dockerfile:

```docker
FROM    ubuntu:focal AS base
ENV     DEBIAN_FRONTEND=noninteractive \
        PYTHONUNBUFFERED=true \
        PATH=/root/.local/bin:${PATH}
WORKDIR /src
RUN     apt update && \
        apt upgrade -y && \
        apt install -y software-properties-common python3-pip python3-venv curl && \
        add-apt-repository -y ppa:ubuntugis/ppa && \
        apt update && \
        apt install -y gdal-bin libgdal-dev && \
        curl -sSL https://install.python-poetry.org | python3 - --preview

FROM    base
ADD     . ./
RUN     poetry config virtualenvs.create false && \
        poetry install --only main
WORKDIR /src/service
CMD     uvicorn --host 0.0.0.0 --port $PORT main:app
```

Everything works in the base image; The moment I try to install my deps, I get a PEP 440 issue that I can't seem to troubleshoot at all.

**Comment by dimbleby** [comment] 2022-07-08 15:19
You forgot to say what the error you are hitting actually is.  

And also to provide the things that get copied into your docker image that are presumably needed to reproduce this.

**Comment by finswimmer** [comment] 2022-07-16 09:35
Hello @yaq-cc,

I guess this is a duplicate of https://github.com/python-poetry/poetry/issues/6013. See my comment there.

Feel free to leave a comment if you disagree.

fin swimmer

**Closed by finswimmer** 2022-07-16 09:35 UTC
