### ISSUE TITLE
Poetry no module name found

### ISSUE THREAD

**Issue by differentMonster** [python-poetry/poetry#2470] opened 2020-05-28 09:56 UTC
I am having a error after installing poetry

ModuleNotFoundError: No module named 'cores

and i out put the  "`which - a poetry`
```

/root/.local/bin/poetry
/root/.local/bin/poetry
```
how do i fix this no module problem ?

**Comment by finswimmer** [comment] 2020-06-01 06:15
Hello @differentMonster,

could you please explain how you have installed poetry?

fin swimmer

**Comment by finswimmer** [comment] 2021-12-22 07:13
Hello,

I'm closing this because we haven't received any response for a long time now and guess the issue issue is solved. Feel free to leave a comment if you disagree.

fin swimmer

**Closed by finswimmer** 2021-12-22 07:13 UTC
Labels: Bug, Triage
