### ISSUE TITLE
poetry can't find the right installation candidate of tensorflow with python 3.9

### ISSUE THREAD

**Issue by kretes** [python-poetry/poetry#4605] opened 2021-10-06 16:33 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Docker. Host & image run ubuntu 20.04
- **Poetry version**: 1.1.11
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/kretes/3e82c4fced9e39bf93ab89ba18f21b6a

## Issue
Having an example toml with just:
```
python = "~3.9"
tensorflow = "*"
h5py = "*"
scikit-learn = "*"
```
makes poetry select tensorflow down to 2.0.2, for which it eventually fails with `  Unable to find installation candidates for tensorflow (2.0.2)
` 
due to the fact there is no wheel for it for python 3.9 - https://pypi.org/project/tensorflow/2.0.2/#files 

If I specify a version constraint for tensorflow e.g. `>2.5` - it finds other combination of dependencies' versions and it works.

The gist contains a dockerfile and a pyproject.toml and a log when I try to build the image.

**Comment by dimbleby** [comment] 2022-06-04 12:40
If the latest versions of everything are not compatible with one another, then of course poetry must choose to hold some things down-level.

If you care about which things are at the latest version , then providing a version constraint is the right answer.

tensorflow 2.0.2 gives no restriction on `requires_python` in its metadata; there's not much poetry can do about it if tensorflow publishes no 3.9-installable package.

Not a bug.

**Comment by Tlaloc-Es** [comment] 2023-04-01 15:34
Try with this `python = ">=3.10, <3.12"`

**Comment by SergeyHein** [comment] 2024-01-31 19:21
I'm experiencing same issue with python 3.11 under docker & WSL 2

```bash
(test-py3.11) root@a634e1891f96:/data/test# python --version
Python 3.11.6
(test-py3.11) root@a634e1891f96:/data/test# pip list
Package    Version
---------- -------
pip        23.3.2
setuptools 69.0.2
(test-py3.11) root@a634e1891f96:/data/test# cat pyproject.toml 
[tool.poetry]
name = "test"
version = "0.1.0"
description = "test"
authors = ["test"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.11"




[tool.poetry.group.dev.dependencies]
black = "^23.10.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
(test-py3.11) root@a634e1891f96:/data/test# poetry add tensorflow
Using version ^2.15.0.post1 for tensorflow

Updating dependencies
Resolving dependencies... (1.3s)

Because no versions of tensorflow match >2.15.0.post1,<3.0.0
 and tensorflow (2.15.0.post1) depends on tensorflow-intel (2.15.0.post1), tensorflow (>=2.15.0.post1,<3.0.0) requires tensorflow-intel (2.15.0.post1).
So, because no versions of tensorflow-intel match 2.15.0.post1
 and test depends on tensorflow (^2.15.0.post1), version solving failed.
 
 ```

**Comment by dimbleby** [comment] 2024-01-31 20:15
that's not the same thing, though this _also_ is not poetry's fault.

what you are seeing is a duplicate of 2.15.0.post1

both are issues with tensorflow and not with poetry

**Closed** 2024-02-04 12:19 UTC
Labels: kind/bug, status/duplicate, status/external-issue

**Comment by ArturHatoka** [comment] 2024-02-20 22:06
@dimbleby @radoering why close issue??

please release fix for tensorflow bug...
