### ISSUE TITLE
it should say "Downgrading" instead of "Updating" when downgrading dependencies

### ISSUE THREAD

**Issue by DetachHead** [python-poetry/poetry#5352] opened 2022-03-24 06:56 UTC
```
> poetry install
Installing dependencies from lock file

Package operations: 0 installs, 2 updates, 0 removals

  • Updating robotframework (5.0 -> 5.0rc2)
  • Updating robotframework-tidy (2.0b1 -> 1.6.2)
```

**Comment by finswimmer** [comment] 2022-03-24 07:11
Hello @DetachHead,

this is a duplicate of https://github.com/python-poetry/poetry/issues/1394.

fin swimmer.

**Closed by finswimmer** 2022-03-24 07:11 UTC
Labels: Feature, Triage
