### ISSUE TITLE
Unable to install sentence-transformers

### ISSUE THREAD

**Issue by rjalexa** [python-poetry/poetry#8075] opened 2023-06-07 11:21 UTC
- **Poetry version**: Poetry (version 1.5.0)
- **Python version**: Python:  3.11.3 (but python --version from the command line gives 3.10.9)
- **OS version and name**:macOS 13.4
- **pyproject.toml**: [(https://gist.github.com/rjalexa/05a0a9846a25627e8315bb7e01f18ca4)]

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
poetry add sentence-trasfomers  -> Could not find a matching version of package sentence-trasformers
while the same from PyPI is installed without problems via pip. https://pypi.org/project/sentence-transformers/

**Comment by ralbertazzi** [comment] 2023-06-07 11:32
I can't reproduce it. This is what happens on the latest Poetry starting from your pyproject.toml

```
❯ poetry add sentence-transformers
The currently activated Python version 3.9.11 is not supported by the project (^3.10).
Trying to find and use a compatible version.
Using python3.11 (3.11.2)
Creating virtualenv bertopictest in /Users/ra/projects/poetry-8075/.venv
Using version ^2.2.2 for sentence-transformers

Updating dependencies
Resolving dependencies... Downloading https://files.pythonhosted.org/packages/44/e5/4fea13230bcebf24b28c0efd774a2dd65a0937a2d39e94a4503438b078ed/PyYAML-6.0-cp310-cp310
Resolving dependencies... Downloading https://files.pythonhosted.org/packages/09/7f/dd8cae1ed66d43bdff9e0d250b806d2217a9c18177f4f65cc3e4bc907308/sentencepiece-0.1.99-c
Resolving dependencies... Downloading https://files.pythonhosted.org/packages/09/7f/dd8cae1ed66d43bdff9e0d250b806d2217a9c18177f4f65cc3e4bc907308/sentencepiece-0.1.99-c
Resolving dependencies... Downloading https://files.pythonhosted.org/packages/91/d4/3b4c8e5a30604df4c7518c562d4bf0502f2fa29221459226e140cf846512/joblib-1.2.0-py3-none-
Resolving dependencies... Downloading https://files.pythonhosted.org/packages/f3/23/7cc851bae09cf4db90d42a701dfe525780883ada86bece45e3da7a07e76b/numpy-1.24.3-cp310-cp3
Resolving dependencies... Downloading https://files.pythonhosted.org/packages/f3/23/7cc851bae09cf4db90d42a701dfe525780883ada86bece45e3da7a07e76b/numpy-1.24.3-cp310-cp3
Resolving dependencies... Downloading https://files.pythonhosted.org/packages/f3/23/7cc851bae09cf4db90d42a701dfe525780883ada86bece45e3da7a07e76b/numpy-1.24.3-cp310-cp3
Resolving dependencies... Downloading https://files.pythonhosted.org/packages/f3/23/7cc851bae09cf4db90d42a701dfe525780883ada86bece45e3da7a07e76b/numpy-1.24.3-cp310-cp3
Resolving dependencies... Downloading https://files.pythonhosted.org/packages/f3/23/7cc851bae09cf4db90d42a701dfe525780883ada86bece45e3da7a07e76b/numpy-1.24.3-cp310-cp3
Resolving dependencies... Downloading https://files.pythonhosted.org/packages/f3/23/7cc851bae09cf4db90d42a701dfe525780883ada86bece45e3da7a07e76b/numpy-1.24.3-cp310-cp3
Resolving dependencies... Downloading https://files.pythonhosted.org/packages/f3/23/7cc851bae09cf4db90d42a701dfe525780883ada86bece45e3da7a07e76b/numpy-1.24.3-cp310-cp3
Resolving dependencies... Downloading https://files.pythonhosted.org/packages/f3/23/7cc851bae09cf4db90d42a701dfe525780883ada86bece45e3da7a07e76b/numpy-1.24.3-cp310-cp3
Resolving dependencies... Downloading https://files.pythonhosted.org/packages/f3/23/7cc851bae09cf4db90d42a701dfe525780883ada86bece45e3da7a07e76b/numpy-1.24.3-cp310-cp3
Resolving dependencies... Downloading https://files.pythonhosted.org/packages/f3/23/7cc851bae09cf4db90d42a701dfe525780883ada86bece45e3da7a07e76b/numpy-1.24.3-cp310-cp3
Resolving dependencies... Downloading https://files.pythonhosted.org/packages/f3/23/7cc851bae09cf4db90d42a701dfe525780883ada86bece45e3da7a07e76b/numpy-1.24.3-cp310-cp3
Resolving dependencies... Downloading https://files.pythonhosted.org/packages/f3/23/7cc851bae09cf4db90d42a701dfe525780883ada86bece45e3da7a07e76b/numpy-1.24.3-cp310-cp3
Resolving dependencies... Downloading https://files.pythonhosted.org/packages/f3/23/7cc851bae09cf4db90d42a701dfe525780883ada86bece45e3da7a07e76b/numpy-1.24.3-cp310-cp3
Resolving dependencies... Downloading https://files.pythonhosted.org/packages/f3/23/7cc851bae09cf4db90d42a701dfe525780883ada86bece45e3da7a07e76b/numpy-1.24.3-cp310-cp3
Resolving dependencies... Downloading https://files.pythonhosted.org/packages/f3/23/7cc851bae09cf4db90d42a701dfe525780883ada86bece45e3da7a07e76b/numpy-1.24.3-cp310-cp3
Resolving dependencies... Downloading https://files.pythonhosted.org/packages/f3/23/7cc851bae09cf4db90d42a701dfe525780883ada86bece45e3da7a07e76b/numpy-1.24.3-cp310-cp3
Resolving dependencies... (7.1s)

Package operations: 32 installs, 0 updates, 0 removals

  • Installing certifi (2023.5.7)
  • Installing charset-normalizer (3.1.0)
  • Installing idna (3.4)
  • Installing markupsafe (2.1.3)
  • Installing mpmath (1.3.0)
  • Installing urllib3 (2.0.3)
  • Installing filelock (3.12.0)
  • Installing fsspec (2023.5.0)
  • Installing jinja2 (3.1.2)
  • Installing networkx (3.1)
  • Installing numpy (1.24.3)
  • Installing packaging (23.1)
  • Installing pyyaml (6.0)
  • Installing requests (2.31.0)
  • Installing sympy (1.12)
  • Installing tqdm (4.65.0)
  • Installing typing-extensions (4.6.3)
  • Installing click (8.1.3)
  • Installing huggingface-hub (0.15.1)
  • Installing joblib (1.2.0)
  • Installing pillow (9.5.0)
  • Installing regex (2023.6.3)
  • Installing scipy (1.9.3)
  • Installing threadpoolctl (3.1.0)
  • Installing tokenizers (0.13.3)
  • Installing torch (2.0.1)
  • Installing nltk (3.8.1)
  • Installing scikit-learn (1.2.2)
  • Installing sentencepiece (0.1.99)
  • Installing torchvision (0.15.2)
  • Installing transformers (4.29.2)
  • Installing sentence-transformers (2.2.2)

Writing lock file
```

> I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.

You marked this as true but is false, since 1.5.0 is not the latest version. Please upgrade to 1.5.1 and see if this fixes the issue.

> If an exception occurs when executing a command, I executed it again in debug mode (-vvv option) and have included the output below.

You marked this as true but you didn't share any verbose output.

**Comment by dimbleby** [comment] 2023-06-07 11:39
> poetry add sentence-trasfomers -> Could not find a matching version of package sentence-trasformers

is it possible that you simply typed this wrong?  There should be an 'n' in 'transformers'...

**Closed** 2023-06-07 12:48 UTC
Labels: kind/bug, status/triage
