### ISSUE TITLE
Poetry isn't using the POETRY_PYPI_TOKEN_PYPI variable when publishing

### ISSUE THREAD

**Issue by arnavb** [python-poetry/poetry#2801] opened 2020-08-12 02:17 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOS 10.15.5 Catalina 
- **Poetry version**: 1.0.10 
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**:  [Gist](https://gist.github.com/arnavb/543b8c61d6dee05dea01e6484b142e7d) 

## Issue

I was trying to deploy the latest version of my package, [pypokedex](https://github.com/arnavb/pypokedex) to PyPI, using [Travis CI](https://travis-ci.com/github/arnavb/pypokedex/jobs/371045831) (the link is to my build log). I'm using the following deploy config from `.travis.yml`

```yaml
    ...
    - stage: deploy
      python: "3.6"
      script: skip
      deploy:
        provider: script
        script: ./deploy.sh
        on:
          tags: true
        skip_cleanup: true
    ...
```

and:

<details>
<summary><code>deploy.sh</code></summary>

```bash
#!/usr/bin/env bash

if ! poetry build; then
  echo "Failed to build pypokedex. Rerun 'poetry build'. Aborting."
  exit 1
fi

echo "Built pypokedex in dist folder"

# Requires rename utility with perl replace support
if ! rename 's/py3/py36/' dist/pypokedex-1.5.0-py3-none-any.whl; then
  echo "Unable to rename built wheel. Aborting."
  exit 1
fi

echo "Renamed wheel"

if ! poetry publish; then
  echo "Failed to publish pypokedex. Rerun 'poetry publish'. Aborting."
  exit 1
fi

echo "Successfully published package to PyPI"
exit 0
```

</details>

Notably, for my Travis build, I have set the variable `POETRY_PYPI_TOKEN_PYPI` to an API token from `pypi.org`. However, as seen from the build output, which is

```
Publishing pypokedex (1.5.0) to PyPI
No suitable keyring backends were found
Using a plaintext file to store and retrieve credentials
Username: 
```

Poetry is ignoring the presence of this environment variable and asking for my username and password. [The documentation](https://python-poetry.org/docs/repositories/#configuring-credentials) states that I should be able to publish with just the token set. I initially thought that I needed my username as well, but according [PyPI documentation](https://pypi.org/help/#apitoken) it isn't necessary.  I can produce the same behavior locally if I just set the token to an environment variable (and not a username password combo) before running `poetry publish`.

**Comment by abn** [comment] 2020-08-12 07:55
@arnavb you can, as a workaround, do something like this.

```yaml
      script:	
        - poetry config http-basic.pypi "__token__" "${POETRY_PYPI_TOKEN_PYPI}"	
        - poetry publish --build
```

This is a duplicate of #2210

**Closed** 2020-08-12 08:36 UTC
Labels: Duplicate

**Comment by arnavb** [comment] 2020-08-12 23:01
@abn Oh I saw that issue, I thought it only applied to non-PyPI repositories but I was mistaken. Thanks for the quick response!
