### ISSUE TITLE
Enforcing python compatibility does not appear to be well documented

### ISSUE THREAD

**Issue by couling** [python-poetry/poetry#5821] opened 2022-06-09 22:41 UTC
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue
Some logic that apparently [isn't a bug](https://github.com/python-poetry/poetry/issues/5798) could be better documented.

I'm struggling to find any documentation about the origin of this error.

```
  SolverProblemError

  The current project's Python requirement (>=3.8,<4.0) is not compatible with some of the required packages Python requirement:
    - scipy requires Python >=3.8,<3.11, so it will not be satisfied for Python >=3.11,<4.0
```

It seems to be reasoning about versions of python that don't yet exist (`>=3.11,<4.0`) and I suspect this logic is really specific to the `python` dependency.

If I had to guess, I would assume **Poetry is unable to install other versions of python that the one installed on the system, and it's trying to ensure the lock file will be compatible with other systems (as long as they meet the project's python requirement).**

The only documentation I've found on the topic is [here](https://python-poetry.org/docs/pyproject/#dependencies-and-dev-dependencies) where it says

> Be aware that declaring the python version for which your package is compatible is mandatory

## Requests

 - Could some explanation of this behaviour be added to the documentation (if it's really missing) 
 - Could it be linked from the above passage, to give some explanation of why specifying `pthon` is "compatible mandatory".  
 - Could it be referenced or placed on [this page](https://python-poetry.org/docs/dependency-specification/).

Rejecting a package for reasons of non-existent python versions is really really unusual.  It deserves to be documented.

**Comment by Secrus** [comment] 2022-06-09 22:48
Caret (`^`) operator is documented on the exact page you linked. Don't really understand what you expect to be added.

**Comment by couling** [comment] 2022-06-09 23:01
> **Rejecting a package for reasons of non-existent python versions is really really unusual. It deserves to be documented.**

@Secrus I'm re-reading and re-reading but I see nothing about the `^` operator having an effect based on non-existent / unreleased python versions.  I only see that something like `^3.8` expands to `>=3.8,<4.0`.  That's a completely different topic to the one I'm discussing here.

Kindly read more carefully, because on both my original bug report and this documentation request you have incorrectly assumed I don't understand that `^3.8` infers `<4.0`.  That has never been the issue.  The problem I've faced is that poetry is raising an error based on hypothetical versions of python that don't exist.

**Comment by sihrc** [comment] 2022-06-09 23:23
@couling  I've read this in other issues, but for the Python dependency the entire range of python versions supplied must be compatible with your packages.

Because your specification includes 3.11 - 4.0 and scipy only includes up to 3.11 that is a conflict

**Comment by abn** [comment] 2022-06-09 23:24
@couling see https://python-poetry.org/docs/master/faq/#why-is-poetry-telling-me-that-the-current-projects-python-requirement-is-not-compatible-with-one-or-more-packages-python-requirements 

A few things to take into consideration about the scenario you are encountering.

1. The error is about dependency resolution and not installation of a dependency.
2. Poetry generates a global lock file.
3. Poetry by design ensures that the dependencies you have specified works across all the python versions you have declared your project will work with.
4. The reference to `3.11` comes from `scipy`'s metadata `>=3.8,<3.11`.

```console
$ curl -sL https://pypi.org/pypi/scipy/json | jq -r '.info.requires_python'
>=3.8,<3.11
```

Because of (4), Poetry cannot ensure (3) and hence raises the error in question. 

> It seems to be reasoning about versions of python that don't yet exist 

Yes it is, this is because `scipy` says it works only for versions `>=3.8,<3.11`. But your project claims it works for `>=3.8,<4.0`. Poetry does not try to determine if a dependency or python version is released or unreleased.

**Comment by couling** [comment] 2022-06-09 23:28
@abn Thanks a lot.  That's pretty much what I figured after spending hours and hours trawling documentation.  No I didn't find the FAQ.

I think my request for cross-references in the documentation stands.  It feels as though this should have been easier to find, and hints like others raising similar issues suggests the same.

**Comment by couling** [comment] 2022-06-09 23:30
I'll also formulate a feature-request.  Not sure what to request at this second, maybe an off-switch for this behaviour, maybe something different.

The problems with it go beyond simple trip hazard.

**Comment by abn** [comment] 2022-06-09 23:39
> I think my request for cross-references in the documentation stands. It feels as though this should have been easier to find, and hints like others raising similar issues suggests the same.

We will be closing this issue as there is no real action here at present. That said, if you think there is a change to documentation that would benifit the community, feel free to raise a PR. We are happy to review it.

> others raising similar issues suggests the same

While there are a few issues on similar topics, this is in the grand scheme of things only an extremely small portion. And among them, more likely than not it is because folks coming from no dependency resolution environments.

> I'll also formulate a feature-request. Not sure what to request at this second, maybe an off-switch for this behaviour, maybe something different.

I can tell you now that this wont be something we will add an "off-switch" for. Assuming you are talking about python dependency constraints being enforced based on available metadata. Bear in mind that Poetry has been developed over years, and this behaviour is intentional.

**Closed by abn** 2022-06-09 23:39 UTC
Labels: Documentation, Triage
