### ISSUE TITLE
Poetry missing py10 vendor in 1.1.12

### ISSUE THREAD

**Issue by TomasMadeja** [python-poetry/poetry#4876] opened 2021-12-09 13:54 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Win 10 10.0.19042
- **Poetry version**: 1.1.12
- **Python version**: 3.10.1

## Issue
 
Poetry 1.1.12 fails for me with python 10. Looking into the _vendor folder, the py10 folder is missing. It is missing in the downloaded tar.gz files from releases on git as well (1.1.11 has them).

Running any poetry command gives me `ModuleNotFoundError: No module named 'poetry.core'`.

**Comment by kkirsche** [comment] 2021-12-09 15:43
I'm using Python 3.10 and haven't experienced this behavior with poetry. Can you share more information about how poetry is installed and whatnot to see if there is a way I could replicate this?

**Comment by finswimmer** [comment] 2021-12-09 16:00
Hey,

this is a duplicate of: https://github.com/python-poetry/poetry/issues/4846

fin swimmer

**Closed as completed by finswimmer** 2021-12-09 16:00 UTC
Labels: kind/bug
