### ISSUE TITLE
Poetry show and update

### ISSUE THREAD

**Issue by peach-lasagna** [python-poetry/poetry#2845] opened 2020-08-22 08:53 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10
- **Poetry version**: 1.0.10
- **Link of a [Gist](https://gist.github.com/peach-lasagna/274939af019f6c72806cc37099fddb76) with the contents of your pyproject.toml file**

## Issue

Continuation of #2735.
I tried do 
```sh
$poetry update
```
in/out venv and catch RecursionError (from pyparsing)
[All Traceback ](https://gist.github.com/peach-lasagna/c19c398831d93d1332198d0c488d94ab)

__poetry show__  not working too ([Traceback](https://gist.github.com/peach-lasagna/3e81e5e4a7bc64185d26fce7603ea708))

**Comment by finswimmer** [comment] 2020-08-24 04:36
Hello @peach-lasagna,

could you please try out the latest preview release? With this I'm not able to reproduce your problem.

fin swimmer

**Comment by g4b1nagy** [comment] 2020-11-09 21:27
This has been fixed in the `1.1.X` branch of `Poetry`. So every version starting from `1.1.0` (Oct 1, 2020) should work just fine.
Note that:
> lock files generated with this release are not compatible with previous releases of Poetry.

**Closed** 2020-11-10 04:53 UTC
Labels: Bug, Triage
