### ISSUE TITLE
AssertionError in `poetry add URL` 

### ISSUE THREAD

**Issue by aalok-sathe** [python-poetry/poetry#5249] opened 2022-02-28 20:22 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 20.04 LTS
- **Poetry version**: 1.1.12
- **Contents of your pyproject.toml file**: 
    ```
     $ cat pyproject.toml 
      [tool.poetry]
      name = "cdr"
      version = "0.0.1"
      description = ""
      authors = ["Your Name <you@example.com>"]
      license = "None"
      
      [tool.poetry.dependencies]
      python = "^3.9"
      
      [tool.poetry.dev-dependencies]
      
      [build-system]
      requires = ["poetry-core>=1.0.0"]
      build-backend = "poetry.core.masonry.api"
    ```

## Issue

Unable to add a dependency using the command: `poetry add https://github.com/coryshain/cdr/archive/refs/tags/v0.5.3.tar.gz`.
I get an `AssertionError`

<pre> λ poetry add https://github.com/coryshain/cdr/archive/refs/tags/v0.5.3.tar.gz -vvv
Using virtualenv: <font color="#4E9A06">/home/aalok/.cache/pypoetry/virtualenvs/cdr-IZ5BapSB-py3.9</font>

<font color="#3465A4">Updating dependencies</font>
Resolving dependencies...
<font color="#8D8F8A">   1: </font><font color="#3465A4">fact</font>: <font color="#06989A">cdr</font> is <b>0.0.1</b>
<font color="#8D8F8A">   1: </font><font color="#3465A4">derived</font>: <font color="#06989A">cdr</font>
<font color="#8D8F8A">   1: Version solving took 0.282 seconds.</font>
<font color="#8D8F8A">   1: Tried 1 solutions.</font>

  <font color="#C4A000">Stack trace</font>:

  <font color="#C4A000">13</font>  <b>~/.poetry/lib/poetry/_vendor/py3.9/clikit/console_application.py</b>:<b>131</b> in <font color="#06989A">run</font>
       129│             parsed_args = resolved_command.args
       130│ 
     <font color="#EF2929"><b>→</b></font> <b>131</b><font color="#8D8F8A">│             status_code = command.handle(parsed_args, io)</font>
       132│         <font color="#AD7FA8"><b>except </b></font><b>KeyboardInterrupt</b><font color="#8D8F8A">:</font>
       133│             status_code = <font color="#729FCF"><b>1</b></font>

  <font color="#C4A000">12</font>  <b>~/.poetry/lib/poetry/_vendor/py3.9/clikit/api/command/command.py</b>:<b>120</b> in <font color="#06989A">handle</font>
       118│     <font color="#AD7FA8"><b>def </b></font>handle(<b>self</b><font color="#8D8F8A">, args, io):  </font><font color="#8D8F8A"><i># type: (Args, IO) -&gt; int</i></font>
       119│         <font color="#AD7FA8"><b>try</b></font><font color="#8D8F8A">:</font>
     <font color="#EF2929"><b>→</b></font> <b>120</b><font color="#8D8F8A">│             status_code = </font><b>self</b><font color="#8D8F8A">._do_handle(args, io)</font>
       121│         <font color="#AD7FA8"><b>except </b></font><b>KeyboardInterrupt</b><font color="#8D8F8A">:</font>
       122│             <font color="#AD7FA8"><b>if </b></font>io.is_debug():

  <font color="#C4A000">11</font>  <b>~/.poetry/lib/poetry/_vendor/py3.9/clikit/api/command/command.py</b>:<b>171</b> in <font color="#06989A">_do_handle</font>
       169│         handler_method = <b>self</b><font color="#8D8F8A">._config.handler_method</font>
       170│ 
     <font color="#EF2929"><b>→</b></font> <b>171</b><font color="#8D8F8A">│         </font><font color="#AD7FA8"><b>return </b></font><b>getattr</b><font color="#8D8F8A">(handler, handler_method)(args, io, </font><b>self</b><font color="#8D8F8A">)</font>
       172│ 
       173│     <font color="#AD7FA8"><b>def </b></font>__repr__(<b>self</b><font color="#8D8F8A">):  </font><font color="#8D8F8A"><i># type: () -&gt; str</i></font>

  <font color="#C4A000">10</font>  <b>~/.poetry/lib/poetry/_vendor/py3.9/cleo/commands/command.py</b>:<b>92</b> in <font color="#06989A">wrap_handle</font>
        90│         <b>self</b><font color="#8D8F8A">._command = command</font>
        91│ 
     <font color="#EF2929"><b>→</b></font> <b> 92</b><font color="#8D8F8A">│         </font><font color="#AD7FA8"><b>return </b></font><b>self</b><font color="#8D8F8A">.handle()</font>
        93│ 
        94│     <font color="#AD7FA8"><b>def </b></font>handle(<b>self</b><font color="#8D8F8A">):  </font><font color="#8D8F8A"><i># type: () -&gt; Optional[int]</i></font>

  <font color="#C4A000"> 9</font>  <b>~/.poetry/lib/poetry/console/commands/add.py</b>:<b>173</b> in <font color="#06989A">handle</font>
       171│             <b>self</b><font color="#8D8F8A">._installer.whitelist([r[</font><font color="#FCE94F"><b>&quot;name&quot;</b></font><font color="#8D8F8A">] </font><font color="#AD7FA8"><b>for </b></font>r <font color="#AD7FA8"><b>in </b></font>requirements])
       172│ 
     <font color="#EF2929"><b>→</b></font> <b>173</b><font color="#8D8F8A">│             status = </font><b>self</b><font color="#8D8F8A">._installer.run()</font>
       174│         <font color="#AD7FA8"><b>except </b></font><b>BaseException</b><font color="#8D8F8A">:</font>
       175│             <font color="#8D8F8A"><i># Using BaseException here as some exceptions, eg: KeyboardInterrupt, do not inherit from Exception</i></font>

  <font color="#C4A000"> 8</font>  <b>~/.poetry/lib/poetry/installation/installer.py</b>:<b>103</b> in <font color="#06989A">run</font>
       101│         local_repo = Repository()
       102│ 
     <font color="#EF2929"><b>→</b></font> <b>103</b><font color="#8D8F8A">│         </font><font color="#AD7FA8"><b>return </b></font><b>self</b><font color="#8D8F8A">._do_install(local_repo)</font>
       104│ 
       105│     <font color="#AD7FA8"><b>def </b></font>dry_run(<b>self</b><font color="#8D8F8A">, dry_run=</font><font color="#AD7FA8"><b>True</b></font><font color="#8D8F8A">):  </font><font color="#8D8F8A"><i># type: (bool) -&gt; Installer</i></font>

  <font color="#C4A000"> 7</font>  <b>~/.poetry/lib/poetry/installation/installer.py</b>:<b>235</b> in <font color="#06989A">_do_install</font>
       233│             )
       234│ 
     <font color="#EF2929"><b>→</b></font> <b>235</b><font color="#8D8F8A">│             ops = solver.solve(use_latest=</font><b>self</b><font color="#8D8F8A">._whitelist)</font>
       236│         <font color="#AD7FA8"><b>else</b></font><font color="#8D8F8A">:</font>
       237│             <b>self</b><font color="#8D8F8A">._io.write_line(</font><font color="#FCE94F"><b>&quot;Installing dependencies from lock file&quot;</b></font><font color="#8D8F8A">)</font>

  <font color="#C4A000"> 6</font>  <b>~/.poetry/lib/poetry/puzzle/solver.py</b>:<b>65</b> in <font color="#06989A">solve</font>
        63│         <font color="#AD7FA8"><b>with </b></font><b>self</b><font color="#8D8F8A">._provider.progress():</font>
        64│             start = time.time()
     <font color="#EF2929"><b>→</b></font> <b> 65</b><font color="#8D8F8A">│             packages, depths = </font><b>self</b><font color="#8D8F8A">._solve(use_latest=use_latest)</font>
        66│             end = time.time()
        67│ 

  <font color="#C4A000"> 5</font>  <b>~/.poetry/lib/poetry/puzzle/solver.py</b>:<b>233</b> in <font color="#06989A">_solve</font>
       231│ 
       232│         <font color="#AD7FA8"><b>try</b></font><font color="#8D8F8A">:</font>
     <font color="#EF2929"><b>→</b></font> <b>233</b><font color="#8D8F8A">│             result = resolve_version(</font>
       234│                 <b>self</b><font color="#8D8F8A">._package, </font><b>self</b><font color="#8D8F8A">._provider, locked=locked, use_latest=use_latest</font>
       235│             )

  <font color="#C4A000"> 4</font>  <b>~/.poetry/lib/poetry/mixology/__init__.py</b>:<b>7</b> in <font color="#06989A">resolve_version</font>
       5│     solver = VersionSolver(root, provider, locked=locked, use_latest=use_latest)
       6│ 
     <font color="#EF2929"><b>→</b></font> <b>7</b><font color="#8D8F8A">│     </font><font color="#AD7FA8"><b>return </b></font>solver.solve()
       8│ 

  <font color="#C4A000"> 3</font>  <b>~/.poetry/lib/poetry/mixology/version_solver.py</b>:<b>84</b> in <font color="#06989A">solve</font>
        82│             <font color="#AD7FA8"><b>while </b></font><b>next </b><font color="#AD7FA8"><b>is not None</b></font><font color="#8D8F8A">:</font>
        83│                 <b>self</b><font color="#8D8F8A">._propagate(</font><b>next</b><font color="#8D8F8A">)</font>
     <font color="#EF2929"><b>→</b></font> <b> 84</b><font color="#8D8F8A">│                 </font><b>next </b><font color="#8D8F8A">= </font><b>self</b><font color="#8D8F8A">._choose_package_version()</font>
        85│ 
        86│             <font color="#AD7FA8"><b>return </b></font><b>self</b><font color="#8D8F8A">._result()</font>

  <font color="#C4A000"> 2</font>  <b>~/.poetry/lib/poetry/mixology/version_solver.py</b>:<b>404</b> in <font color="#06989A">_choose_package_version</font>
       402│         conflict = <font color="#AD7FA8"><b>False</b></font>
       403│ <font color="#AD7FA8"><b>        for </b></font>incompatibility <font color="#AD7FA8"><b>in </b></font><b>self</b><font color="#8D8F8A">._provider.incompatibilities_for(version):</font>
     <font color="#EF2929"><b>→</b></font> <b>404</b><font color="#8D8F8A">│             </font><b>self</b><font color="#8D8F8A">._add_incompatibility(incompatibility)</font>
       405│ 
       406│             <font color="#8D8F8A"><i># If an incompatibility is already satisfied, then selecting version</i></font>

  <font color="#C4A000"> 1</font>  <b>~/.poetry/lib/poetry/mixology/version_solver.py</b>:<b>445</b> in <font color="#06989A">_add_incompatibility</font>
       443│ 
       444│     <font color="#AD7FA8"><b>def </b></font>_add_incompatibility(<b>self</b><font color="#8D8F8A">, incompatibility):  </font><font color="#8D8F8A"><i># type: (Incompatibility) -&gt; None</i></font>
     <font color="#EF2929"><b>→</b></font> <b>445</b><font color="#8D8F8A">│         </font><b>self</b><font color="#8D8F8A">._log(</font><font color="#FCE94F"><b>&quot;fact: {}&quot;</b></font><font color="#8D8F8A">.</font><b>format</b><font color="#8D8F8A">(incompatibility))</font>
       446│ 
       447│         <font color="#AD7FA8"><b>for </b></font>term <font color="#AD7FA8"><b>in </b></font>incompatibility.terms:

  <font color="#EF2929"><b>AssertionError</b></font>

  

  at <font color="#4E9A06">~/.poetry/lib/poetry/mixology/incompatibility.py</font>:<b>111</b> in <font color="#06989A">__str__</font>
      107│         )
      108│ 
      109│     <font color="#AD7FA8"><b>def </b></font>__str__(<b>self</b><font color="#8D8F8A">):</font>
      110│         <font color="#AD7FA8"><b>if </b></font><b>isinstance</b><font color="#8D8F8A">(</font><b>self</b><font color="#8D8F8A">._cause, DependencyCause):</font>
    <font color="#EF2929"><b>→</b></font> <b>111</b><font color="#8D8F8A">│             </font><font color="#AD7FA8"><b>assert </b></font><b>len</b><font color="#8D8F8A">(</font><b>self</b><font color="#8D8F8A">._terms) == </font><font color="#729FCF"><b>2</b></font>
      112│ 
      113│             depender = <b>self</b><font color="#8D8F8A">._terms[</font><font color="#729FCF"><b>0</b></font><font color="#8D8F8A">]</font>
      114│             dependee = <b>self</b><font color="#8D8F8A">._terms[</font><font color="#729FCF"><b>1</b></font><font color="#8D8F8A">]</font>
      115│             <font color="#AD7FA8"><b>assert </b></font>depender.is_positive()</pre>

**Comment by finswimmer** [comment] 2022-04-29 19:53
Hey, 

problem here is that you are trying to add a dependency with the same name as the project. So this is duplicate of https://github.com/python-poetry/poetry/issues/1985.

fin swimmer

**Closed by finswimmer** 2022-04-29 19:53 UTC
Labels: Bug, Triage
