### ISSUE TITLE
Can't use newrelic

### ISSUE THREAD

**Issue by Exspiravit** [python-poetry/poetry#1844] opened 2020-01-08 03:36 UTC
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **18.04.3 Ubuntu LTS**: 
- **1.0.0**: 
- **Its not necesary **: 

## Issue

Hello community, I like to collaborate at least in this way, I found that by adding newrelic, (poetry add newrelic), it generates the following in my pyproject.toml (newrelic = "^ 5.4.1"), however it does not let me use newrelic -admin, this causes that the services of newrelic cannot be lifted, the solution that I found was to install it by means of pip inside poetry, something like (poetry run pip install newrelic), but it does not seem to me that it is the best way to do it.

the issue line in my logs:
sh[32174]: /bin/sh: 1: /home/admin/web/test.quimder.com/backend/.venv/bin/newrelic-admin: not found

**Comment by finswimmer** [comment] 2020-01-08 05:48
Hello @Exspiravit,

unfortunately I'm  not able to reproduce this. After adding newrelic to the project by `poetry add newrelic` I can run it either with `poetry run newrelic-admin help` or activate the venv with `poetry shell` and run `newrelic-admin help`.

**Comment by finswimmer** [comment] 2021-12-22 05:17
Hello,

I'm closing this because we haven't received any response for a long time now and guess the issue issue is solved. Feel free to leave a comment if you disagree.

fin swimmer

**Closed by finswimmer** 2021-12-22 05:17 UTC
Labels: Bug
