### ISSUE TITLE
Version is not changed in pyproject.toml

### ISSUE THREAD

**Issue by ktsibikov** [python-poetry/poetry#1696] opened 2019-12-09 18:46 UTC
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS Mojave
- **Poetry version**: Poetry 1.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/ktsibikov/c047dec8000bbf622162ebcad0230c54

## Issue
Steps to reproduce:
1. Add source section in `pyproject.toml`
2. Patch package version executing command `poetry version patch`

Expected behavior: version in `pyproject.toml` was updated.
Actual behavior: version in `pyproject.toml` was not updated.

**Comment by finswimmer** [comment] 2019-12-09 19:31
Hello @ktsibikov ,

could you please test it with the latest preview? Notice that syntax has changed their. `poetry version` will just show the current version. You has to define what part of the version should be bump, e.g. `poetry version patch`.

fin swimmer

**Comment by ktsibikov** [comment] 2019-12-10 05:16
Tried with the `1.0.0b9` preview. After executing `poetry version patch` version in `pyproject.toml` still was not changed.

**Comment by finswimmer** [comment] 2019-12-10 05:25
Hm, I tried it with the `pyproject.toml` you've linked with no problems. (I received a deprecation warning: The "black" dependency specifies the "allows-prereleases" property, which is deprecated. Use "allow-prereleases" instead.)

How have you installed `poetry`? Have you closed and reopened the file afterwards, to make sure you see the latest content?

**Comment by ktsibikov** [comment] 2019-12-13 09:07
Hi @finswimmer ! 
Installation `curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python`
So, I installed version `1.0.0` and the result the same: in the terminal I see `Bumping version from 0.1.0 to 0.1.1`,  but in `pyproject.toml` the version was not changed.

> Have you closed and reopened the file afterwards, to make sure you see the latest content?
Yes, I did

**Comment by ktsibikov** [comment] 2020-01-08 19:08
The same behavior is on 1.0.0 version
`predicates on  master [!] via predicates-h1BsK1i7-py3.6 via 🐍 3.6.2 
➜ poetry --version
Poetry version 1.0.0

predicates on  master [!] via predicates-h1BsK1i7-py3.6 via 🐍 3.6.2 
➜ poetry version
predicates 0.1.0

predicates on  master [!] via predicates-h1BsK1i7-py3.6 via 🐍 3.6.2 
➜ poetry version patch
Bumping version from 0.1.0 to 0.1.1

predicates on  master [!] via predicates-h1BsK1i7-py3.6 via 🐍 3.6.2 
➜ poetry version
predicates 0.1.0`

**Comment by cfarrend** [comment] 2020-02-21 01:18
We are experiencing the same issue, it does not happen all the time however. We have currently reproduced the issue by going to the commit that fails in our GitHub Actions build but are still investigating. It seems that when the problem is present, you can't update to _any_ version

When I mean it does not happen all the time, we could have a version `5.0.0` and update to `5.0.1dev1`, `5.0.1dev2`, `5.0.1dev3` but then fail on `5.0.1dev4`. Usually after a new release we don't run into the issue for a little while but appears again

**Comment by etijskens** [comment] 2020-02-21 08:48
I am not sure wether this is helpful or not - just hoping to save you some time.
Some time ago I had similar issues. It turned out that when the entries in the pyproject.toml file are not in correct order or grouped together, version bumping fails without error. Details in https://github.com/python-poetry/poetry/issues/1182
Kindest regards,

Dr [Engel]bert Tijskens - HPC Analyst/Consultant
Flemish Supercomputer Center
University of Antwerp / Computational mathematics
++32 3 265 3879, ++32 494 664408

On 21 Feb 2020, at 02:18, Christopher Farrenden <notifications@github.com<mailto:notifications@github.com>> wrote:


We are experiencing the same issue, it does not happen all the time however. We have currently reproduced the issue by going to the commit that fails in our GitHub Actions build but are still investigating. It seems that when the problem is present, you can't update to any version

When I mean it does not happen all the time, we could have a version 5.0.0 and update to 5.0.1dev1, 5.0.1dev2, 5.0.1dev3 but then fail on 5.0.1dev4. Usually after a new release we don't run into the issue for a little while but appears again

**Comment by estyxx** [comment] 2020-02-28 15:13
I think the problem is somewhere inside these [lines](https://github.com/python-poetry/poetry/blob/c9fb348e16ed6e7f6570770dfe42c71038961938/poetry/console/commands/version.py#L55), sometimes the version is not updated correctly in the file content (that is a tomlkit.toml_document.TOMLDocument object). But I didn't understand why... 

In my case, this is my [configuration](https://gist.github.com/estyxx/ca81901f57daae6d90875c48f88233c8) where poetry can't update the version correctly. 
I have the isort configuration inside, if I remove it, the poetry is able to update correctly the version in pyproject.toml file...

**Comment by sdispater** [comment] 2020-02-28 15:37
This has been fixed in tomlkit (see https://github.com/sdispater/tomlkit/pull/68).

I will make a new release of tomlkit today along with a new release of Poetry.

**Closed** 2020-03-03 18:03 UTC
Labels: Bug
