### ISSUE TITLE
Handle multiple dependency specification sources

### ISSUE THREAD

**Issue by CommonCrisis** [python-poetry/poetry#1547] opened 2019-11-06 10:56 UTC
Hi,

is there a way to handle dependencies from different sources. I have a repo let's call it _app-lib_ that is used in other repos as submodule. 
If I change some dependencies in _app-lib_, I have to adjust the pyproject.toml files in all other repos.
There should be a way to tell poetry to merge the dependencies in the _app-lib_ pyproject.toml file  and the ones in the root repo.
Or is there another way this can be handled?

Thanks

**Comment by huangxiaohen2738** [comment] 2020-07-12 04:43
so,  supported?

**Comment by finswimmer** [comment] 2020-07-14 08:26
Hello,

can you please add more information about what this feature should do? Until now it's unclear to me.

fin swimmer

**Comment by huangxiaohen2738** [comment] 2020-07-14 08:43
Thanks for your reply.
Some lib in open pypi source, some lib in private source.
And `pipenv` support it.

**Comment by Eduard-gan** [comment] 2020-08-06 13:45
Hi, first of all i want to apologize in advance for my english :D

The author asks actually different question as to me. The problem is not in *sources of actual binary data of the different the packages*.

Say we're in microservices environment. We trying to not duplicate our code and have some common code in separate repository that has its dependencies(for example i need aiohttp for this code to work) and this is defined in pyproject.toml in this "common" repository. 

The problem comes when we start a new microservice in separate repo. We link as submodule the "common" repo(it has its own pyproject.toml) an then we make another pyproject.toml specific to this microservice.

Stupid solution is when a build step begins install everything in one virtualenv inside docker cotainer in two steps
RUN cd /app/common && poetry install && cd /app
RUN poetry install --no-dev

But it's obviously doesn't work if you have cross dependencies between two .lock files ant it leads us to unmanaged updates of packages.

How can we use solver of poetry to make it install packages in one context but from multiple files(not necessarily pyproject.toml files). Different files are crucial here because they come from different repos from different teams.

**Comment by abn** [comment] 2020-08-06 14:41
@CommonCrisis @Eduard-gan the solution proposed in #2270 might address the scenarios you are referring to. However, note that this intended for mono-repo cases. Which might be better suited for the cases described above. If not, please do let us know what the gap is.

@CommonCrisis in your case, it might also be prudent to consider that it might be better to better to build wheels (optionally publish them to a private index) and install them within a container using `pip`, and [with it's new resolver](https://pip.pypa.io/en/stable/user_guide/#changes-to-the-pip-dependency-resolver-in-20-2-2020), `pip` should handle the versions correctly since the wheels contain accurate metadata thanks to poetry ;).

@huangxiaohen2738 I think you are looking for a different feature from the one the OP is referring to. Poetry allows the use of multiple repositories as described [here](https://python-poetry.org/docs/repositories/#install-dependencies-from-a-private-repository). You can specify the use of a defined source in a dependency as `name = { version = "^1.0", source = "private-pypi"}`.

**Comment by neersighted** [comment] 2022-10-04 05:03
Closing in favor of #2270 -- this issue is unclear overall (every comment is talking about something different), but the closest thing to the original issue body is better support for monorepo scenarios.

**Closed by neersighted** 2022-10-04 05:03 UTC
Labels: kind/feature
