### ISSUE TITLE
Poetry not honouring (deprecated) dependencies with tornado 5.1.1

### ISSUE THREAD

**Issue by matejsp** [python-poetry/poetry#7534] opened 2023-02-19 06:56 UTC
- **Poetry version**: 1.3.2
- **Python version**: 3.8.16
- **OS version and name**: macOS 13.1
- **pyproject.toml**: tornado = "==5.1.1"

- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
We tried to migrate to poetry from pipenv and what we encountered is that one library incorrectly detects transient depedencies.

python = "~3.8"
tornado = "==5.1.1"

We are running on python 3.8 and according to tornado setup.py
https://github.com/tornadoweb/tornado/blob/v5.1.1/setup.py
```
if setuptools is not None:
    # If setuptools is not available, you're on your own for dependencies.
    install_requires = []
    if sys.version_info < (3, 2):
        install_requires.append('futures')
    if sys.version_info < (3, 4):
        install_requires.append('singledispatch')
    if sys.version_info < (3, 5):
        install_requires.append('backports_abc>=0.4')
    kwargs['install_requires'] = install_requires

    python_requires = '>= 2.7, !=3.0.*, !=3.1.*, !=3.2.*, != 3.3.*'
    kwargs['python_requires'] = python_requires
```

However poetry somehow detects these now useless dependencies and adds them to lock file.

```
[[package]]
name = "tornado"
version = "5.1.1"
description = "Tornado is a Python web framework and asynchronous networking library, originally developed at FriendFeed."
category = "main"
optional = false
python-versions = ">= 2.7, !=3.0.*, !=3.1.*, !=3.2.*, != 3.3.*"
files = [
    {file = "tornado-5.1.1-cp27-cp27mu-linux_x86_64.whl", hash = "sha256:2f9eee81441b9fa299e2e66c3f1e70e1fef16ec964554471acb4d14105f78910"},
    {file = "tornado-5.1.1-cp310-cp310-linux_aarch64.whl", hash = "sha256:018d68631a563cec7d2aa50da609c69aa5e7594b17a82e6e7c9abd15ef976f6e"},
    {file = "tornado-5.1.1-cp310-cp310-linux_x86_64.whl", hash = "sha256:ca191033930d8c3e76f557b99c6a7146eaef7655e93ea828efe5416985bc9edc"},
    {file = "tornado-5.1.1-cp310-cp310-macosx_12_0_arm64.whl", hash = "sha256:cd8f42c513259ecaccafe0084c3d3287b38579c825f82ff5d6b9b2a01b1f64dc"},
    {file = "tornado-5.1.1-cp310-cp310-macosx_12_0_x86_64.whl", hash = "sha256:37d4acf210a79d388c70aabb2b8c4feea207e606af2cda22925a65efb3cf1f88"},
    {file = "tornado-5.1.1-cp311-cp311-macosx_12_0_arm64.whl", hash = "sha256:f418053f68235080609b27fdc4bee9cce36e326e94cfaae8e2cebd2059173019"},
    {file = "tornado-5.1.1-cp36-cp36m-linux_x86_64.whl", hash = "sha256:3fb6816ae1958f70d5bfa50e65ff5071f8f47e7989b0c2e5872614c1cdbd61ec"},
    {file = "tornado-5.1.1-cp37-cp37m-linux_x86_64.whl", hash = "sha256:7423f105906cebe1911c43419af276568d77164bb2366a93fd153d06cd636b0e"},
    {file = "tornado-5.1.1-cp38-cp38-linux_aarch64.whl", hash = "sha256:444bbb1a83ab40d454ccfe6f810502a2cd504ef28a0edf0e216c549105957435"},
    {file = "tornado-5.1.1-cp38-cp38-linux_x86_64.whl", hash = "sha256:305debc7c83df7b668f288e4d3e363ae59c7c0ba1458caab05e4ed4f4c0dd24d"},
    {file = "tornado-5.1.1-cp38-cp38-macosx_12_0_arm64.whl", hash = "sha256:554ed63b5e8cdeb6b67e8190757c576c4bc598d60fa6750722349c8267161b8c"},
    {file = "tornado-5.1.1-cp38-cp38-macosx_12_0_x86_64.whl", hash = "sha256:798d88ed386659784d9289ea8b11e2491fb7aac2ca792d387f6ce700ee803a74"},
    {file = "tornado-5.1.1-cp39-cp39-linux_aarch64.whl", hash = "sha256:2a68c209fa98eb1f389516b25487d03ccab6a94fb2e96204a18b584b4874a4a9"},
    {file = "tornado-5.1.1-cp39-cp39-linux_x86_64.whl", hash = "sha256:17c8d1aa6f3a167cd1d13f67aed56145d19625e4a06f38d2673185fa12aa7dfa"},
    {file = "tornado-5.1.1-cp39-cp39-macosx_12_0_arm64.whl", hash = "sha256:8c4e63c04f836690890ff217ab29264d77a34ffa056e8c9681cfe074b0d89201"},
    {file = "tornado-5.1.1-cp39-cp39-macosx_12_0_x86_64.whl", hash = "sha256:49a046295a44f1b0f0f17609071c371613899cda7ef3a4fdb72d533f153d0788"},
    {file = "tornado-5.1.1.tar.gz", hash = "sha256:4e5158d97583502a7e2739951553cbd88a72076f152b4b11b64b9a10c4c49409"},
]

[package.dependencies]
backports-abc = ">=0.4"
futures = "*"
singledispatch = "*"
```

We are unable to upgrade tornado at the moment.

**Comment by dimbleby** [comment] 2023-02-19 11:10
poetry will not execute setup.py, pep508 markers are the way to express conditional dependencies.

tornado hasn't done this for several years.  You say you can't upgrade: but if this is a problem for you, that's the way to solve it.

**Comment by matejsp** [comment] 2023-02-19 11:33
I see. Thanks for the anwser. But if setup.py is not executed where does it get dependencies from?

If it is from METADATA inside each wheel. Yes 2.7 has those 3 dependencies listed and other wheels don't.
Perhaps this bug should be that poetry should exclude (download, caching and checking) wheels that are not related to current setup. Mind I have python = "~3.8" so all unrelated wheels should be ignored in the process. It would be better more correct and even faster poetry :)

METADATA from 2.7 wheel
```
Metadata-Version: 2.1
Name: tornado
Version: 5.1.1
Summary: Tornado is a Python web framework and asynchronous networking library, originally developed at FriendFeed.
Home-page: http://www.tornadoweb.org/
Author: Facebook
Author-email: python-tornado@googlegroups.com
License: http://www.apache.org/licenses/LICENSE-2.0
Platform: UNKNOWN
Classifier: License :: OSI Approved :: Apache Software License
Classifier: Programming Language :: Python :: 2
Classifier: Programming Language :: Python :: 2.7
Classifier: Programming Language :: Python :: 3
Classifier: Programming Language :: Python :: 3.4
Classifier: Programming Language :: Python :: 3.5
Classifier: Programming Language :: Python :: 3.6
Classifier: Programming Language :: Python :: 3.7
Classifier: Programming Language :: Python :: Implementation :: CPython
Classifier: Programming Language :: Python :: Implementation :: PyPy
Requires-Python: >= 2.7, !=3.0.*, !=3.1.*, !=3.2.*, != 3.3.*
Requires-Dist: futures
Requires-Dist: singledispatch
Requires-Dist: backports-abc (>=0.4)
```

**Comment by dimbleby** [comment] 2023-02-19 11:51
poetry builds cross-platform solutions and therefore the platform that you happen to be locking on ismore or less irrelevant. 

To achieve this in a performant way, poetry assumes that the metadata does not vary between the wheels of a package.  Again, pep508 markers are the way to make this true.

still not a bug!

**Comment by matejsp** [comment] 2023-02-19 12:25
Yes I agree, it's not a bug. You can close it.

OTOH If the specified Python version is not supported by the project (like ^3.8 in my case) I don't need to have lock file cluttered with wheels and its hashes that will never be needed. Why waste speed and resources?

**Comment by dimbleby** [comment] 2023-02-19 12:33
non-varying metadata is a poetry assumption.  It's not required to be true, but poetry's success is a demonstration that it's nearly always true.  (Though, as you have discovered, that wouldn't have been a good assumption back in 2018 when tornado 5.1 was released...)

I don't have the power to close this issue.  You do.

**Closed** 2023-02-19 12:46 UTC
Labels: kind/bug, status/triage

**Comment by radoering** [comment] 2023-02-19 15:00
> Mind I have python = "~3.8" so all unrelated wheels should be ignored anyway in the process, since they are useless. It would be better more correct and even faster poetry :)

Just as a side note: I agree that it makes sense to ignore wheels that are not compatible with the project's python constraint. They will never be used so I don't think it adds any value to have them in the lock file. If I remember correctly, recently, there was an example in the chat where a wheel that would never be used due to the project's python constraint was downloaded only to calculate its hash for the lock file. In this case, ignoring the wheel could be a massive performance improvement (at least with a cold cache). However, I don't know how difficult it is to ignore such wheels. I haven't had the time to check this in detail yet. There might be some sharp edges. PRs are definitively welcome.
