### ISSUE TITLE
Poetry exports incorrect requirements for transitive dependencies, breaks installation with hashes

### ISSUE THREAD

**Issue by mathrick** [python-poetry/poetry#4719] opened 2021-11-06 06:26 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 20.04, CPython 3.8.5
- **Poetry version**: 1.1.11
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/mathrick/ad6b1be5be5e124b3ce1bddbeef24bac

## Issue

This seems related to #3363, but I don't believe it's a duplicate, and I haven't seen this mentioned elsewhere.

When exporting `requirements.txt`, poetry will add incorrect implementation markers to the output, which in some cases can result in invalid requirement files when used with hashes:

```
Collecting cffi>=1.0.0
ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    cffi>=1.0.0 from https://devpi.cerebras.aws/root/pypi/%2Bf/57e/9ac9ccc3101fa/cffi-1.15.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl#sha256=57e9ac9ccc3101fac9d6014fba037473e4358ef4e89f8e181f8951a2c0162024 (from argon2-cffi==21.1.0->-r /tmp/reqs.txt (line 16))
```

This happens because in the generated `requirements.txt`, the section for `cffi` is as follows:
```
cffi==1.15.0; implementation_name == "pypy" and python_version >= "3.6" \
    --hash=sha256:c2502a1a03b6312837279c8c1bd3ebedf6c12c4228ddbad40912d671ccc8a962 \
    --hash=sha256:23cfe892bd5dd8941608f93348c0737e369e51c100d03718f108bf1add7bd6d0 \
[...]
    --hash=sha256:920f0d66a896c2d99f0adbb391f990a84091179542c205fa53ce5787aff87954
```

Notice the `implementation_name == "pypy"` marker, even though the implementation used is CPython.

**Comment by dimbleby** [comment] 2021-11-06 14:27
recent master gives
```
cffi==1.15.0; implementation_name == "pypy" and python_version >= "3.7" and python_full_version >= "3.6.1" or python_version >= "3.6"
``` 
which seems satisfactory

**Comment by mathrick** [comment] 2021-11-22 00:44
Any ETA for when that could make its way into a release?

**Comment by DMRobertson** [comment] 2022-03-08 19:41
I think I might have come across this on poetry `1.1.12`. With the following pyproject.toml:

```toml
[tool.poetry]
name = "foo"
version = "1.2.3"
description = "foo"
authors = ["foo"]

[tool.poetry.dependencies]
python = "^3.7"

signedjson = "1.1.1"
matrix-common = "1.1.0"

[tool.poetry.dev-dependencies]
flake8 = "4.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

If I run `poetry export`, the generated requirements stipulate that `importlib-metadata` is only required for Python 3.7:

```
$ poetry lock && poetry export | grep ^importlib-metadata -A 3
importlib-metadata==4.11.2; python_version < "3.8" and python_version >= "3.7" \
    --hash=sha256:d16e8c1deb60de41b8e8ed21c1a7b947b0bc62fab7e1d470bcdf331cea2e67\
    --hash=sha256:b36ffa925fe3139b2f6ff11d6925ffd4fa7bc47870165e3ac260ac7b4f91e6ac
```

However, [signedjson 1.1.1 requires importlib_metadata unconditionally](https://github.com/matrix-org/python-signedjson/blob/b4fc77d6e6a9f23defb02335d9b6189c82f6f3ba/setup.py#L44). Somehow, combining this with the other two requirements and exporting from the results makes this only required on Python 3.7.

Quoting from the lockfile:

```
[[package]]
  name = "flake8"
  version = "4.0.1"
  ...
   
  [package.dependencies]
  importlib-metadata = {version = "<4.3", markers = "python_version < \"3.8\""}
  ...

  [[package]]
  name = "matrix-common"
  version = "1.1.0"  ...
   
  [package.dependencies]
  importlib-metadata = {version = ">=1.4", markers = "python_version < \"3.8\""}
```

**Comment by DMRobertson** [comment] 2022-03-08 19:47
Using the same pyproject.toml and poetry@b06658f9a730b4d28b4b517d7f5c982514e524df I now get

```
$ poetry lock && poetry export | \grep ^importlib-metadata -A 3
Updating dependencies
Resolving dependencies... (0.2s)
importlib-metadata==4.2.0 ; python_version >= "3.6" \
    --hash=sha256:057e92c15bc8d9e8109738a48db0ccb31b4d9d5cfbee5a8670879a30be66304b \
    --hash=sha256:b7e52a1f8dec14a75ea73e0891f3060099ca1d8e6a462a4dff11c3e119ea1b31
matrix-common==1.1.0 \
```

which seems sensible to me.

**Comment by dimbleby** [comment] 2022-05-11 14:43
Having said which, this example actually exposes https://github.com/python-poetry/poetry/issues/5593, so thanks for that!

**Comment by shaib** [comment] 2022-05-11 15:13
(was going to point out that all the relevant data is in `poetry.lock` by the time we export, but you seem to already have the root cause, which is great!)

**Comment by dimbleby** [comment] 2022-05-15 11:40
anyway both the original issue and the new example are fixed on master, so probably this should be closed

**Closed** 2022-05-15 13:02 UTC
Labels: Bug, Triage
