### ISSUE TITLE
poetry tries to (re-)install package although same version is available in site-packages

### ISSUE THREAD

**Issue by marekro** [python-poetry/poetry#7234] opened 2022-12-22 14:44 UTC
I am using a system-wide Python 3.10 installation with up-to-date pip, setuptools and poetry, which also includes a few packages that require binaries being built during installation, example: netifaces. Version 0.11.0 is installed in /opt/python-3.10.9/lib/python3.10/site-packages/
I have a poetry.toml with:
```
[virtualenvs.options]
system-site-packages = true
```
Now when running "poetry install" (poetry version 1.3.1), I see this message:
> Updating netifaces (0.11.0 /opt/python-3.10.9/lib/python3.10/site-packages -> 0.11.0): Installing...

This should not happen - why update the same version? In my case, this even fails fatally, because the environment (a Docker container) does not have a working gcc.
My expectation is that poetry will recognise the package version available in site-packages (as configured in poetry.toml) and skip any attempt to install the same version in the virtual env.

**Comment by neersighted** [comment] 2022-12-22 16:10
This is not, in fact, the same version -- there is a `direct_url.json` marker in that distribution that marks it as installed from a path and not an index. The path in the version number indicates this.

Additionally, please follow the issue template and the contribution guide when reporting issues in the future -- it really helps us address your issues faster.

**Comment by radoering** [comment] 2022-12-22 19:11
Might also be a duplicate of #6035 (and a bug, see https://github.com/python-poetry/poetry/issues/6035#issuecomment-1259761192)

**Closed** 2022-12-23 14:48 UTC
Labels: status/duplicate
