### ISSUE TITLE
Unable to find installation candidates for regex (2022.7.24)

### ISSUE THREAD

**Issue by ipmb** [python-poetry/poetry#6069] opened 2022-07-25 15:21 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **Ubuntu 20.04**: 
- **1.1.14 & 1.2.0b3**: 
- ```shell
    curl -sLo requirements.txt https://raw.githubusercontent.com/getsentry/sentry/a7057707ee086d9a587e1ea0ab08039a4d7566b5/requirements-base.txt
    poetry add $(sed -e 's/#.*//' -e '/^$$/ d' < requirements.txt)
    ```

## Issue
<!-- Now feel free to write your issue, but please be descriptive! Thanks again 🙌 ❤️ -->

It looks like one of the packages had a release issue https://github.com/mrabarnett/mrab-regex/issues/475

We are testing all the package managers against this requirements set and poetry was the only one that failed, https://github.com/lincolnloop/python-package-manager-shootout/actions/runs/2733333579 (click through to see verbose traceback). Not sure if this is a bug or a feature, but thought it was worth raising here.

**Comment by neersighted** [comment] 2022-07-25 15:37
Closing as a duplicate of #3543 -- the issue is pypi/warehouse#11949 and not something specific to regex.

**Closed by neersighted** 2022-07-25 15:37 UTC
Labels: Bug, Triage
