### ISSUE TITLE
Use the same naming pattern for sdist and wheel dist files

### ISSUE THREAD

**Issue by javiermatos** [python-poetry/poetry#2585] opened 2020-06-19 16:26 UTC
When building with `poetry build` I have noticed that the dist files created do not share the same naming pattern.

I have a package named `local-cache` and created dist files are the following:

1. local-cache-0.1.0.tar.gz
2. local_cache-0.1.0-py3-none-any.whl

First case uses dash, second uses underscore.

For wheel builder we have this:

```python
@property
def wheel_filename(self):  # type: () -> str
    return "{}-{}-{}.whl".format(
        escape_name(self._package.pretty_name),
        escape_version(self._meta.version),
        self.tag,
    )
```

But for sdist builder we have the following:

```python
target = target_dir / "{}-{}.tar.gz".format(
    self._package.pretty_name, self._meta.version
)
```

Would not it be better to use the same naming pattern in both cases?

**Comment by finswimmer** [comment] 2020-06-20 06:39
Hello @javiermatos,

my first thought was also that this behavior should be fixed. But it seems to work as intended. [PEP427](https://www.python.org/dev/peps/pep-0427/#file-name-convention) says this about the filename:

> Each component of the filename is escaped by replacing runs of non-alphanumeric characters with an underscore _:

I couldn't found something for sdist. So it is correct that the sdist filename contains `-` from the package name and in the wheel filename it get's replaced by `_`.

fin swimmer

**Closed by finswimmer** 2020-06-20 06:39 UTC
Labels: Feature, Triage

**Comment by javiermatos** [comment] 2020-06-20 13:16
Ok, thank you for the information :)
