### ISSUE TITLE
Poetry install dependencies/dev-dependencies from lock file

### ISSUE THREAD

**Issue by nathanrpage97** [python-poetry/poetry#3570] opened 2021-01-13 07:52 UTC
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Add the ability to run `poetry install {list-of-dependencies}` /  `poetry install --dev {list-of-dev-dependencies}`.

This will install these dependencies and their sub-dependencies from the lock file instead of installing all dependencies. This is useful in CI where not all dev-dependencies are needed for a job.

**Comment by sinoroc** [comment] 2021-01-14 18:01
Maybe look at the planned feature [_dependency groups_](https://github.com/python-poetry/poetry/issues/1644).

**Comment by nathanrpage97** [comment] 2021-01-14 19:30
I've seen that, but I still think that this is also useful to give the most fine grained control on dependency installation.

**Comment by finswimmer** [comment] 2022-03-26 19:52
Duplicate of #3033

**Closed by finswimmer** 2022-03-26 19:52 UTC
Labels: Feature, Triage
