### ISSUE TITLE
`get_ignored_files` may use wrong git working area

### ISSUE THREAD

**Issue by iarspider** [python-poetry/poetry#6242] opened 2022-08-26 08:34 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: CentOS 7
- **Poetry version**: 1.1.13
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://github.com/sdispater/tomlkit/blob/0.7.2/pyproject.toml

## Issue
When Poetry is looking for files to pack into wheel or tarball, one of the steps is to get excluded files from VCS. To do that, it first checks if the package's source dir was checked from git [`get_vcs`](https://github.com/python-poetry/poetry-core/blob/bb35db38597cdc4219a276e5be07f28d1a0a44d9/src/poetry/core/vcs/__init__.py#L11). However that check is not enough, since git (roughly speaking) will traverse up the directory tree looking for `.git` directory, which could happen to be completely unrelated to the package being built - in my case, it detects `.git` folder from [Spack](https://github.com/spack/spack.git) package manager while building `tomlkit`. Maybe poetry should check if the directory returned by `get_vcs` is the same as the one containing `pyproject.toml`?

**Comment by finswimmer** [comment] 2022-08-26 08:36
Duplicate of https://github.com/python-poetry/poetry/issues/5547

**Closed by finswimmer** 2022-08-26 08:36 UTC
Labels: Bug, Triage
