### ISSUE TITLE
`ModuleNotFoundError` using `from` in `packages`

### ISSUE THREAD

**Issue by nfantone** [python-poetry/poetry#8792] opened 2023-12-14 19:12 UTC
- **Poetry version**: `1.7.1`.
- **Python version**: `3.11.6`.
- **OS version and name**: macOS 14.1.2.

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a [recommended method](https://python-poetry.org/docs/#installation).
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

I'll admit, right off the bat, that I'm not sure what the expected behaviour here is or what exactly is causing my issues. This might not even be a `poetry` problem. So apologies up front if I'm off.

Regardless, here's what I see.

I have a project that I'm migrating from [a flat structure to a `src` layout](https://packaging.python.org/en/latest/discussions/src-layout-vs-flat-layout/). In its current state, it looks like this:

```
my-project/
├── project/
│   ├── __init__.py
│   ├── package/
│   │   ├── __init__.py
│   │   └── ...
│   └── module.py
├── tests/
│   ├── __init__.py
│   └─── package/
│        ├── __init__.py
│        └── test_package.py
├── plugins/
│   ├── __init__.py
│   └── commitizen.py
├── pyproject.toml
└── README.md
```

```toml
# pyproject.toml

[tool.poetry]
name = "my-project"
version = "0.1.0"
packages = [{ include = "project" }]

[tool.poetry.plugins."commitizen.plugin"]
# References plugins top level package
cz_jira_conventional = "plugins.commitizen:JiraConventionalCz"
```

This installs fine and allows me to execute binaries such as:

```sh
poetry run cz --help
poetry run pytest .
# etc.
```

However, after changing my layout to use `src/` and updating `pyproject.toml` `packages` accordingly, those commands above stop working, raising errors related to missing modules.

```
my-project/
├── src/
│   └── project/
│       ├── __init__.py
│       ├── package/
│       │   ├── __init__.py
│       │   └── ...
│       └── module.py
├── tests/
│   ├── __init__.py
│   └── package/
│       ├── __init__.py
│       └── test_package.py
├── plugins/
│   ├── __init__.py
│   └── commitizen.py
├── pyproject.toml
└── README.md
```

Note that only sources under `project` moved locations. Everything else, including `plugins/` and `tests/` stayed the same.

```toml
# pyproject.toml

[tool.poetry]
name = "my-project"
version = "0.1.0"
packages = [{ include = "project", from = "src" }]
```

`poetry install` runs successfully, but then results in:

```sh
poetry run cz --help
Traceback (most recent call last):
# ...
ModuleNotFoundError: No module named 'plugins'
```

```sh
poetry run pytest .
tests/test_package.py:5: in <module>
    from tests.factories import (
E   ModuleNotFoundError: No module named 'tests'
```

I found two ways to work around this:

1. Append `PYTHONPATH=.` to all `poetry run` commands (from project's root).
2. Add `{ include = "plugins" }, { include = "tests" }` to the `packages` in `pyproject.toml` (and re-run `poetry install`).

But none of them seem like things I should really be doing or caring about — I certainly didn't need to before.

Could you help me understand what exactly is going on? Am I misusing something?

**Comment by dimbleby** [comment] 2023-12-14 22:33
mixing src and not-src in the same project seems likely, at best, to be entering under-explored territory.  Probably dont do that.

**Comment by nfantone** [comment] 2023-12-14 23:24
What makes you say I'm "mixing `src` and not-`src`?

**Comment by dimbleby** [comment] 2023-12-14 23:28
> What makes you say I'm "mixing src and not-src"?

because you are?  you have both `/src/project` and `/plugins`

> Both of my layouts above [are widely used](https://browniebroke.com/blog/convert-existing-poetry-to-src-layout/), AFAIK

random blog post from two years ago showing something different from what you're doing is a strange citation for "widely used"!

**Comment by nfantone** [comment] 2023-12-14 23:38
Ok. Here you go:

* [Flask](https://github.com/pallets/flask)
* [`request`](https://github.com/psf/requests/)
* NASA [`fprime` repositories](https://github.com/nasa/fprime/)
* [Twisted](https://github.com/twisted/twisted).
* python.org [official packaging docs](https://packaging.python.org/en/latest/discussions/src-layout-vs-flat-layout/).
* [Cryptography](https://github.com/pyca/cryptography)


I could go on. Having python sources inside and outside `src` is pretty widely used.

**Comment by dimbleby** [comment] 2023-12-14 23:50
I dont know why you even care what other projects are doing - what _you_ are doing either works or it doesnt - but that is a very strange set of examples.  Admittedly I onlyl got half way down the list before getting bored, but those projects simply are not mixing src and non-src directories.

Anyway, I suggest you concentrate on what you are trying to do.

**Comment by nfantone** [comment] 2023-12-14 23:55
> I dont know why you even care what other projects are doing -

I don't. I posted examples of known sources using a `src` layout + sources outside it because you objected to it "not being used". That's it, really.

> Anyway, I suggest you concentrate on what you are trying to do.

Can I suggest we focus on the potential bug, instead? I still don't know what's causing my issue.

**Comment by dimbleby** [comment] 2023-12-14 23:56
Yes, using a src layout is fine - this project itself does that.  But I am guessing that your mixing of src (for "project") and not-src (for "plugins") is likely to expose you to potential confusion: and suggest dont do that.

**Comment by nfantone** [comment] 2023-12-14 23:58
As shown in my original post, `tests/` suffers from exactly the same. It doesn't work either. I don't think this is related to `plugins/` exclusively.

**Comment by dimbleby** [comment] 2023-12-14 23:59
tests is treated as a special case, so you are likely mistaken

**Comment by nfantone** [comment] 2023-12-15 00:00
I may be. Could you elaborate, please? How is it special?

**Comment by dimbleby** [comment] 2023-12-15 00:01
please either provide a reproducible example: or figure out for yourself how your project is different from a working example.  

you can use the poetry project as a sample working example that uses the src layout.

**Comment by nfantone** [comment] 2023-12-15 00:35
Sure. Managed to reproduce it using this very repo.

```sh
# Clone and install deps
git clone https://github.com/python-poetry/poetry.git
cd poetry
poetry install

# Install commitizen
poetry add commitizen --group dev

# Create plugins/ package
mkdir plugins
touch plugins/__init__.py
```

- Create the following module as `plugins/commitizen.py`

```python
# plugins/commitizen.py
from commitizen.cz.conventional_commits import ConventionalCommitsCz

class MyConventionalCz(ConventionalCommitsCz):
    pass
```

- Add the following section to `pyproject.toml`.

```toml
[tool.poetry.plugins."commitizen.plugin"]
cz_jira_conventional = "plugins.commitizen:MyConventionalCz"
```

- Install project.

```sh
poetry install
```

- Try to execute any `cz` command.


```sh
poetry run cz --help

Traceback (most recent call last):
# ...
ModuleNotFoundError: No module named 'plugins'
```

**Comment by dimbleby** [comment] 2023-12-15 08:14
Seems like you have lots of solutions

- consistent use of src, or of non-src layout
- per original report, explicit `include`

I don't think it's going to be worthwhile to put more effort into the - let's say unconventional - mixed layout

Please close

**Comment by nfantone** [comment] 2023-12-15 09:59
Supporting scripts designed for development, CI pipelines, or similar environments are commonly found in many projects. While you may perceive this as "unconventional," there are many examples of the opposite (some in previous responses).

Regarding the mention of "lots of solutions," your reference was limited to the two solutions already brought up in my original report.

While the explicit `include` addresses the issue, it deviates from the intended purpose of having a `src` layout, which is to segregate what users install from other project components. Ideally, anything outside of `src`, such as `plugins/`, should not be included in my virtual environment after running `poetry install`.

You made yourself clear and don't want to help out. That's all right. I appreciate the discussion.

**Comment by dimbleby** [comment] 2023-12-15 10:34
> Ideally, anything outside of src, such as plugins/, should not be included in my virtual environment after running poetry install.

well one of us is confused.  That's exactly what's happening, and what you are complaining about.

**Comment by nfantone** [comment] 2023-12-15 10:45
You're right. I'm confused about your passive aggressive tone. I opened a potential bug report, you asked for detailed steps to reproduce it. I provided them. Not sure what else you want from users like myself.

> That's exactly what's happening, and what you are complaining about.

I know. I don't _want_ this to happen for reasons stated above. It doesn't need to happen. I don't want my build scripts to end up in my package.

I can't make you be interested on this. It's fine if you aren't — just be mindful of other people's opinions. Some out there are different from yours.

**Comment by dimbleby** [comment] 2023-12-15 12:15
> Called me "confused".

this is a misreading of "one of us is confused".   Perhaps "at least one of us is confused" would have been more precise.

_I_ remain thoroughly confused.  It seems to me that you have raised an issue describing some behaviour that you presumably find undesirable; but then later described that exact behaviour as "ideal".  I have no idea what this conversation has been about!

**Comment by nfantone** [comment] 2023-12-15 21:40
> this is a misreading of "one of us is confused".

My bad, then. Apologies. I read that in a mocking voice, next to other remarks from before with similar tone.

> It seems to me that you have raised an issue describing some behaviour that you presumably find undesirable; but then later described that exact behaviour as "ideal".

I may have misspoken, but I believe I've never described the results I'm getting as "ideal". The opposite is true.

At the risk of repeating myself, let me try and clarify.

I want to port a project to use a `src` layout. Like most projects, I have:
  * Publishable/installable sources that are meant to be built, distributed and imported by others -> **these should live in a `src/` dir.**
  * Development/CI/testing/misc scripts and other executables. -> **these should not.**

I'm currently using a flat layout + `{ include = "project" }`.
  * No issues at all.
  * `poetry build` only adds `project` to wheel/sdist.
  * All root binaries and scripts execute as expected (i.e.: `poetry run ...`).

After migrating to `src` layout + `{ include = "project", from = "src" }`.
  * Binaries/scripts that import things from the root no longer work.
  * Can be worked around by either moving those scripts to `src/` or adding extra `include` items for each of the root sources. Neither of those are viable options:
    * `src/` _should not_ contain code that is not meant to be importable.
    * `poetry build` would add those unwanted sources to my wheel/sdist.

My expectations would be:

* **Have `src/` dir** alongside all my other root-level, dev-only, packages.
* `poetry build` outputs **only relevant packages** and modules.
* `poetry run ...` **keeps running binaries and entry points** the exact same way as it currently does with the flat layout.

Does this make more sense?

**Comment by dimbleby** [comment] 2023-12-15 23:05
well I had understood - misunderstood? - that you did want (say) `/plugins` to be part of your package but for some reason wanted some of your package in `src` layout and some not: so we certainly seem to have been at cross-purposes.

I think your expectations are just wrong.  If `plugins` is not part of your project then there is no reason to expect that installing your project should allow you to import from it.  It more-or-less irrelevant that you happen to have put something that is not your project near to something that is.

the oddity is that this works with the flat package layout; but that is really an accident.  If you look in your virtual environment you will find a `my-project.pth` or similar whose contents point either at the `src` directory or at the project root, depending which you have done.  The content of that file gets added to your `sys.path`, so when you have the flat layout you really only inadvertently pick up `plugins`: the `.pth` file is meant for `package` and `plugins` gets caught up with it.

ie behaviour here all seems correct

**Comment by dimbleby** [comment] 2023-12-15 23:09
indeed see the very last bullet at https://packaging.python.org/en/latest/discussions/src-layout-vs-flat-layout/, which explains that the behaviour you are seeing is not only intended but should be seen as an advantage of the src layout

> The src layout helps enforce that an [editable installation](https://setuptools.pypa.io/en/latest/userguide/development_mode.html) is only able to import files that were meant to be importable ...

**Comment by radoering** [comment] 2023-12-29 09:25
Importing from tests (inside of tests) works with src layout. Just take a look at poetry itself, e.g. https://github.com/python-poetry/poetry/blob/4177f62db413c4146e3e021b0f443a76aad38da8/tests/config/test_config.py#L15

If it doesn't work for you, I'd recommend looking for differences between your setup and poetry's own setup.

> Append PYTHONPATH=. to all poetry run commands (from project's root).

Normally, the current directory is automatically prepended to the path: https://docs.python.org/3/library/sys.html#sys.path
If you have deactivated this, you will of course have to take care of it yourself.

I'm closing this issue since it does not seem to be a Poetry issue but a general Python issue.

**Closed by radoering** 2023-12-29 09:25 UTC
Labels: kind/question
