### ISSUE TITLE
Equivalent of pip install --no-binary

### ISSUE THREAD

**Issue by spapanik** [python-poetry/poetry#365] opened 2018-08-01 21:22 UTC
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Question

How can I specify that I don't want the binary package to be installed, ie. the equivalent of pip install --no-binary?

**Comment by jambonrose** [comment] 2018-09-09 19:50
I would appreciate some clarity on this front as well. The currently recommended installation of `psycopg2` is:

```
python3 -m pip install psycopg2>=2.7,<2.8 --no-binary psycopg2
```

What is the right way to install `psycopg2` with Poetry?

Thanks!

**Comment by rectalogic** [comment] 2018-11-16 19:12
This seems to work:

`PIP_NO_BINARY="psycopg2" poetry install`

**Comment by RevolutionTech** [comment] 2019-03-25 19:59
Is there a solution with Poetry that involves a change to the `pyproject.toml` or something similar?

The team I work on is trying to install `psycopg2` with `--no-binary`, and although I appreciate that your solution works well @rectalogic, it would be ideal if the solution wasn't co-ordinating that all developers on the team add an environment variable whenever executing `poetry install` (or update their local `~./bashrc`, etc.).

**Comment by janw** [comment] 2019-10-02 20:28
I agree with @RevolutionTech that this should be an option for dependencies in `pyproject.toml`, a `no-binary` flag. If this is still something to be done, I'd be happy to come up with an implementation.

**Comment by RevolutionTech** [comment] 2019-10-03 05:50
In the interest of full transparency I should mention that this is no longer an urgent need for the team I work on since modern versions of `psycopg2` do not install the binary version by default anyways.

That said, I still think that this would be a really great feature, and I am sure there are other packages besides `psycopg2` where this presents a problem.

**Comment by b-long** [comment] 2019-12-27 03:32
Related / duplicate: https://github.com/python-poetry/poetry/issues/1316

**Comment by b-long** [comment] 2019-12-27 17:26
I ran into an issue with the `neuralcoref` library ([github](https://github.com/huggingface/neuralcoref), [pypi](https://pypi.org/project/neuralcoref/)) which was solved by changing my workflow to `PIP_NO_BINARY="neuralcoref" poetry install` .  

A few questions: 
1. Is this currently the best practice?
2. Is there any method of configuring this via pyproject.toml, poetry.lock, or poetry.toml ?
3. Are there any discussions in the Poetry namespace or https://github.com/pypa namespace to follow which might provide an answer to # 1 or # 2 ?

**Comment by spapanik** [comment] 2020-02-27 10:01
> Related / duplicate: #1316 ?

Yes, indeed

**Comment by jo7ueb** [comment] 2020-10-13 09:46
I'm watching this issue as `opencv-python` requires --no-binary option in my case.

**Comment by rendaw** [comment] 2020-10-19 02:30
This is not a duplicate of #1316 since _this_ issue, as an install override, doesn't drag in the question of config files/lock file specifications, platform string matching, etc.

Another example, `gevent==1.4.0` wheel doesn't work with new versions of Python 3.7 (Debian) due to binary incompatibility.  Installing from source works, but `PIP_NO_BINARY` or other environment variables don't work.  Manual fix is to `pip remove gevent` then install it manually with `--no-binary` after setting up the venv.

**Comment by rendaw** [comment] 2020-10-19 02:34
`PIP_NO_BINARY` environment variable no longer works since (1.10?) since file resolution is being resolved by Poetry itself no longer pip.

**Comment by adriantre** [comment] 2021-01-13 18:43
To install e.g. [rasterio](https://rasterio.readthedocs.io/en/latest/installation.html) without wheels for GDAL, we need to provide the `--no-binary` flag. Current workaround is:
```
poetry add rasterio
poetry run pip install --force-reinstall rasterio --no-binary rasterio
```
which feels like bad practice.

**Comment by simon-keith** [comment] 2021-01-21 13:55
We have a similar issue when installing geopandas with the pygeos backend, where we need to do :
`pip install pygeos geopandas --no-binary pygeos,shapely`

**Comment by kylebarron** [comment] 2021-01-21 18:10
Reinstalling with `pip --force-reinstall` after `poetry install` is an interesting workaround. It's probably ideal to grab the version from the Poetry lockfile so that you're installing the same package version:

```
poetry add rasterio
rasterio_version=$(poetry show rasterio | grep version | cut -d ':' -f 2)
poetry run pip install --force-reinstall rasterio=="$rasterio_version" --no-binary rasterio
```

**Comment by sallamander** [comment] 2021-02-11 15:41
Has anybody figured out how to get this into a `poetry.lock` and / or `pyproject.toml` file? The `--force-reinstall` works, but it'd be nice to be able to just do a `poetry install` from the toml or lock file and have that work. 

Are there any plans to support this in the future if it's not already supported in some way?

**Comment by flyte** [comment] 2021-03-01 11:04
None of these workarounds work when your project is published to PyPI and the user installs it with pip.

Our project is intended to run on small systems like Raspberry Pi, one of which (Zero W) is still being produced with a 32bit CPU. PyYAML doesn't include 32 bit binaries, so we need to make sure the source package is installed instead of the 64bit wheel.

Is there currently a workaround that will suit this use case? Changing the instructions from

```bash
pip install <project>
```

to

```bash
pip install --no-binary pyyaml pyyaml
pip install <project>
```

sucks.

**Comment by dazza-codes** [comment] 2021-03-06 21:02
One option to try is to take full advantage of the dependency analysis that poetry provides to manage compatible versions and then export the lock file to a requirements.txt file, e.g.

```
poetry export --without-hashes --format requirements.txt --output requirements.txt
# it can help to remove editable flags:
sed -i -e 's/^-e //g' requirements.txt
poetry run pip install --force-reinstall --no-binary pygeos,shapely,rasterio,pyproj
```

In this approach, poetry might not install anything, pip does it all.  In this approach, the env-var options should work when a build environment already provides shared libs that should be used for the python bindings.

**Closed** 2022-05-14 08:29 UTC
Labels: Configuration, Feature

**Comment by hhstore** [comment] 2023-03-07 03:12
# poetry config:

- https://python-poetry.org/blog/announcing-poetry-1.2.0/#opting-out-of-binary-distributions


```ruby

# Skip all binaries
$ poetry config --local installer.no-binary :all:

# Skip specific package binaries
$ poetry config --local installer.no-binary httpx,uvicorn

# Do not skip any binaries (default)
$ poetry config --local installer.no-binary :none:

```
