### ISSUE TITLE
Dataclasses solver failure with conditional python marker

### ISSUE THREAD

**Issue by mands** [python-poetry/poetry#2386] opened 2020-05-05 14:37 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- Linux (Fedora 32):
- **Poetry version**:
```bash
$ poetry debug info

Poetry
Version: 1.0.5
Python:  3.8.2

Virtualenv
Python:         3.8.2
Implementation: CPython
Path:           /home/projects/poetry-dataclasses/poetry-demo/.venv
Valid:          True

System
Platform: linux
OS:       posix
Python:   /usr
```
### pyproject.yaml

```yaml
[tool.poetry]
name = "poetry-demo"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.6.1"
dataclasses = {version = "^0.7", python = "~3.6.1"}
dacite = "^1.5.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```

## Issue
Following on from #1413, the solution there seems to suggest user python version markers to specify when to install a conditional dependencty - in my case the dataclasses-backport on python 3.6.*. However this seems to result in a `SolverProblemError` resolving in certain cases even with the python specifier as indicated in my `pyproject.yaml` above .

Things seem to work fine until I also install the addional library `dacite` (https://github.com/konradhalas/dacite) - which also has a dependency on dataclasses when using python 3.6. The `setup.py` for it is as follows,

```
    install_requires=['dataclasses;python_version<"3.7"'],
```

Once this library is also installed, adding any other packages to my project results in the aforementioned `SolverProblemError`, e.g.

```bash
$ poetry add arrow
Using version ^0.15.6 for arrow

Updating dependencies
Resolving dependencies... (0.0s)

[SolverProblemError]
The current project's Python requirement (^3.6.1) is not compatible with some of the required packages Python requirement:
  - dataclasses requires Python >=3.6, <3.7

Because dataclasses (0.7) requires Python >=3.6, <3.7
 and no versions of dataclasses match >0.7,<0.8, dataclasses is forbidden.
So, because poetry-demo depends on dataclasses (^0.7), version solving failed.
```

Commenting then uncommenting out either my use of `dataclasses` or `dacite` in my `pyproject.toml` to add additional libraries works, but it seems that both my projects and dacite's use of dataclasses with a conditional python marker conflict in poetry.

**Comment by tarkatronic** [comment] 2020-05-06 15:54
I just ran into what I believe is this same bug, and was able to reliably reproduce it from this example. First, a working dependency specification:

```toml
[tool.poetry.dev-dependencies]
black = {version = "19.10b0", allow-prereleases = true, python = "^3.6"}
```

All operations (lock, install, show, etc) work as expected with the above. When adding "markers", modifying it to the following:

```toml
[tool.poetry.dev-dependencies]
black = {version = "19.10b0", allow-prereleases = true, python = "^3.6", markers = "platform_python_implementation == 'CPython'"}
```

I get the following error:

```
$ poetry lock
Updating dependencies
Resolving dependencies... (0.1s)

[SolverProblemError]
The current project's Python requirement (^3.5) is not compatible with some of the required packages Python requirement:
  - black requires Python >=3.6

Because tartufo depends on black (19.10b0) which requires Python >=3.6, version solving failed.
```

**Comment by kakulukia** [comment] 2020-05-19 10:58
I think im also effected by the same error:

    [SolverProblemError]
    The current project's Python requirement (^3.8) is not compatible with some of the required packages Python requirement:
    - django-bulma requires Python >=3.6,<3.9

    Because no versions of django-bulma match >0.7.1,<0.8.0
    and django-bulma (0.7.1) requires Python >=3.6,<3.9, django-bulma is forbidden.
    So, because bulmatest depends on django-bulma (^0.7.1), version solving failed.

My Python version is within the set limits, but no accepted by poetry as a matching version. How can this be solved?

**Comment by P403n1x87** [comment] 2020-05-30 14:49
I think I have the same problem with Coverage.py

~~~ bash
Using python3 (3.6.9)
Updating dependencies
Resolving dependencies... (0.0s)

[SolverProblemError]
The current project's Python requirement (>=3.6) is not compatible with some of the required packages Python requirement:
  - coverage requires Python >=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, <4

Because no versions of coverage match >5.1
 and coverage (5.1) requires Python >=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, <4, coverage is forbidden.
So, because austin-python depends on coverage (>=5.1), version solving failed.
~~~

**Comment by pawamoy** [comment] 2020-06-07 20:21
I reproduced withi this very simple config:

```toml
[tool.poetry]
name = "hey"
version = "0.1.0"
description = ""
authors = ["Timothée Mazzucotelli <pawamoy@pm.me>"]

[tool.poetry.dependencies]
python = "^3.6"
dataclasses = { version = "^0.7", python = "<3.7" }

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```

```
[SolverProblemError]
The current project's Python requirement (^3.6) is not compatible with some of the required packages Python requirement:
  - dataclasses requires Python >=3.6, <3.7

Because no versions of dataclasses match >0.7,<0.8
 and dataclasses (0.7) requires Python >=3.6, <3.7, dataclasses is forbidden.
So, because hey depends on dataclasses (^0.7), version solving failed.
```

**Comment by kakulukia** [comment] 2020-06-07 20:34
I solved my problem by fixing the projects python version removing the ^
Because the upper Python version of the pack to be installed is limited and by default poetry projects use ^currentPythonVersion, poetry is creating this weird situation. @sdispater are you aware of this "bug"?

**Comment by pawamoy** [comment] 2020-06-07 20:36
You mean you changed `^3.6` into `>=3.6, <4.0`?

**Comment by kakulukia** [comment] 2020-06-07 20:38
Poetry could print a hint or offer to fix the project requirements with one of the available options that would allow to proceed.

**Comment by jcmuddle** [comment] 2020-06-09 13:00
I have a workaround by including a package that depends on dataclasses.

```
[tool.poetry]
name = "test_poetry"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.6.1"
dataclasses = { version = "^0.7", python = "^3.6.1, <3.7" }
dataclasses_json = "^0.4.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```

**Comment by jcmuddle** [comment] 2020-06-09 13:07
Now without the additional package, just drop the patch version for dataclases.
```
[tool.poetry]
name = "test_poetry"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.6.1"
dataclasses = { version = "^0.7", python = "^3.6.1, <3.7" }
dataclasses_json = "^0.4.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```

**Comment by kakulukia** [comment] 2020-06-09 13:10
@jcmuddle Try setting your python version to 3.6.1 instead of ^3.6.1 and report .. this also should work.

**Comment by jcmuddle** [comment] 2020-06-09 13:20
The following pyproject.toml does not install dataclasses:
```
[tool.poetry]
name = "test_poetry"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "3.6.1"
dataclasses = { version="^0.7", python="^3.6.1, <3.7" }


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```
Is this what you meant @kakulukia ?
Here is the output from `poetry update -vvv`
```
Using virtualenv: /home/jmuddle/.conda/envs/test
Updating dependencies
Resolving dependencies...
   1: fact: test-poetry is 0.1.0
   1: derived: test-poetry
   1: fact: test-poetry depends on dataclasses (^0.7)
   1: selecting test-poetry (0.1.0)
   1: derived: dataclasses (^0.7)
PyPI: 1 packages found for dataclasses >=0.7,<0.8
   1: selecting dataclasses (0.7)
   1: Version solving took 0.009 seconds.
   1: Tried 1 solutions.

```

**Comment by theodcr** [comment] 2020-07-06 11:29
Here is a more accurate way:
```
[tool.poetry.dependencies]
python = "^3.6.1 <3.7"
dataclasses = "^0.7"
```
It works and tells poetry exactly what we want: use Python 3.6 only.

**Comment by mands** [comment] 2020-07-09 19:38
As the original submitter, I can still reproduce this on the latest Poetry (1.0.9), when running `poetry add <anypackage>` within a Python 3.8 venv. 

For more context, I'm building an application that runs on any Python from >= 3.6.1, and < 4.0.0 that requires the `dataclasses` library. As `dataclasses` is only required when developing using / when a user is running on Python >= 3.6.1 and < 3.7.0, I've set a conditional marker - however I develop myself within a Python 3.8 venv. I don't believe that this is a user error, as I imagine Poetry supports such a configuration (Poetry's own `pyproject.toml` has a similar dataclasses constraint) so I'm not sure what's not working here.

The only way I can get it to work right now is by commenting the `dataclasses` package in my `pyproject.toml`, adding the additional package I want via `poetry add`, and then uncommenting `dataclasses` again.

My `pyproject.toml` is,

```toml
[tool.poetry.dependencies]
python = "^3.6.1"
dataclasses = {version = "0.7", python = "~3.6.1"}
```

The output from running `poetry add <anypackage> -vvv` is

```
   1: fact: dataclasses (0.7) requires Python >=3.6, <3.7
   1: conflict: dataclasses (0.7) requires Python >=3.6, <3.7
   1: ! dataclasses (0.7) is satisfied by dataclasses (0.7)
   1: ! which is caused by "datapane depends on dataclasses (0.7)"
   1: ! thus: version solving failed
   1: Version solving took 0.420 seconds.
   1: Tried 1 solutions.

[SolverProblemError]
The current project's Python requirement (^3.6.1) is not compatible with some of the required packages Python requirement:
  - dataclasses requires Python >=3.6, <3.7

Because datapane depends on dataclasses (0.7) which requires Python >=3.6, <3.7, version solving failed.
```

**Comment by boukeversteegh** [comment] 2020-07-12 10:01
Same problem @mands 

- Define a project that needs python `>=3.6` / `3.6.1` / `^3.6` / `^3.6.1`
- `poetry add dataclasses --python ">=3.6, <3.7"`
- installs fine
- then add any other package `poetry add --dev black`
- fails with  

```
   [SolverProblemError]
The current project's Python requirement (^3.6) is not compatible with some of the required packages Python requirement:
  - dataclasses requires Python >=3.6, <3.7

Because dataclasses (0.7) requires Python >=3.6, <3.7
 and no versions of dataclasses match >0.7,<0.8, dataclasses is forbidden.
So, because betterproto depends on dataclasses (^0.7), version solving failed.
```

**Comment by dazza-codes** [comment] 2020-07-25 03:15
Similar issue:

```text
[SolverProblemError]
Because {some-lib} ({some-ver}) depends on dataclasses (^0.6) which doesn't match any versions, {some-lib} is forbidden.
```

where `{some-lib}` uses a pyproject.toml with
```toml
[tool.poetry.dependencies]
python = ">=3.6.1, <3.9.0"  # see tox below too
dataclasses = {version = "^0.6", python = "^3.6.1, <3.7"}
```

So, what's up with `dataclasses (^0.6) which doesn't match any versions`?

**Comment by cgarciae** [comment] 2020-09-03 18:41
Having a lot of trouble with this. If a dependency itself depends on a restricted version of `dataclasses` you also get this error, even if you don't depend on `dataclasses` yourself.

**Comment by dekked** [comment] 2020-09-08 16:45
This happens when adding black `^20.8b1` to dev requirements.

Unfortunately, I have to install black separately because of this issue :(

**Comment by abn** [comment] 2020-09-08 19:38
Reproducible in `1.0.10`.

```console
$ poetry@1.0.10 add --dry-run arrow
Using version ^0.16.0 for arrow

Updating dependencies
Resolving dependencies... (0.0s)

[SolverProblemError]
The current project's Python requirement (^3.6.1) is not compatible with some of the required packages Python requirement:
  - dataclasses requires Python >=3.6, <3.7

Because dataclasses (0.7) requires Python >=3.6, <3.7
 and no versions of dataclasses match >0.7,<0.8, dataclasses is forbidden.
So, because poetry-demo depends on dataclasses (^0.7), version solving failed.
```

This should be fixed in `1.1.0b2`.

```console
$ poetry@1.1.0b2 add --dry-run arrow
Using version ^0.16.0 for arrow

Updating dependencies
Resolving dependencies... (0.1s)

Package operations: 0 installs, 0 updates, 0 removals, 5 skipped

  • Removing dataclasses (0.7): Skipped for the following reason: Not currently installed
  • Installing six (1.15.0): Skipped for the following reason: Already installed
  • Installing python-dateutil (2.8.1): Skipped for the following reason: Already installed
  • Installing arrow (0.16.0): Skipped for the following reason: Already installed
  • Installing dacite (1.5.1): Skipped for the following reason: Already installed
```

**Closed** 2020-09-08 19:39 UTC
Labels: Bug

**Comment by xylix** [comment] 2020-09-25 07:42
Had this bug with poetry 1.1.0b4. 

With this https://github.com/robocorp/rpaframework/blob/master/packages/main/pyproject.toml pyproject toml running any `poetry add` or `poetry remove` 

```
Using version ^0.782 for mypy

Updating dependencies
Resolving dependencies... (0.1s)

  SolverProblemError

  The current project's Python requirement (>=3.6,<4.0) is not compatible with some of the required packages Python requirement:
    - dataclasses requires Python >=3.6, <3.7, so it will not be satisfied for Python >=3.7,<4.0

  Because dataclasses (0.7) requires Python >=3.6, <3.7
   and no versions of dataclasses match >0.7,<0.8, dataclasses is forbidden.
  So, because rpaframework depends on dataclasses (^0.7), version solving failed.

  at ~/.poetry/lib/poetry/puzzle/solver.py:241 in _solve
      237│             packages = result.packages
      238│         except OverrideNeeded as e:
      239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
      240│         except SolveFailure as e:
    → 241│             raise SolverProblemError(e)
      242│
      243│         results = dict(
      244│             depth_first_search(
      245│                 PackageNode(self._package, packages), aggregate_package_nodes

  • Check your dependencies Python requirement: The Python requirement can be specified via the `python` or `markers` properties

    For dataclasses, a possible solution would be to set the `python` property to ">=3.6,<3.7"

    https://python-poetry.org/docs/dependency-specification/#python-restricted-dependencies,
    https://python-poetry.org/docs/dependency-specification/#using-environment-markers
```

Worked around the problem by manually modifying `pyproject.toml`.

**Comment by abn** [comment] 2020-09-25 08:39
@xylix see #2950
