### ISSUE TITLE
ModuleNotFoundError: No module named 'cleo.events' when installing with `pamac install python-poetry`

### ISSUE THREAD

**Issue by FilipeMarch** [python-poetry/poetry#6357] opened 2022-09-02 14:01 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
![image](https://user-images.githubusercontent.com/23220309/188158491-008a0ce6-0577-4b55-8894-efe17ee5e86b.png)
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Arch Linux 
- **Poetry version**: 1.2.0

## Issue
I have installed poetry with the command `pamac install python-poetry`. When I type `pip list` I see this:
![image](https://user-images.githubusercontent.com/23220309/188158491-008a0ce6-0577-4b55-8894-efe17ee5e86b.png)

When I open the terminal and type `poetry`, this error message appears:
```python
╰─λ poetry 
Traceback (most recent call last):
    File "/usr/bin/poetry", line 5, in <module>
        from poetry.console.application import main
    File "/usr/lib/python3.10/site-packages/poetry/console/application.py", line 13, in <module>
        from cleo.events.console_events import COMMAND
ModuleNotFoundError: No module named 'cleo.events'
```

I didn't find anything on Google related to this. I opened the `cleo` folder here and I don't see any file called `events`:
![image](https://user-images.githubusercontent.com/23220309/188161448-1eb24e26-3580-496f-8472-c8e14b27f0c2.png)

Well, I deleted the package with `pamac remove python-poetry` and typed `python -m pip install poetry`, and now it works.
Not sure if this is relevant or if here is the right to place to report this information, but the recommended way of installing packages using `pamac` does not work for poetry.

**Comment by dimbleby** [comment] 2022-09-02 14:06
what is pamac and who recommends it?  

Not this project I think, you'll want to take this up with pamac or with whoever told you to use it.

**Comment by Secrus** [comment] 2022-09-02 14:08
The Poetry team is not responsible for maintaining any other package type than Python Wheel so you should raise your issue with the maintainers of pamac package. Closing.

**Closed by Secrus** 2022-09-02 14:08 UTC
Labels: kind/bug, status/triage

**Comment by StarrFox** [comment] 2022-09-02 15:12
for anyone searching for this error:

this is caused by https://github.com/python-poetry/poetry/issues/6353 (pamac is a gui installer for arch)
