### ISSUE TITLE
Poetry pulls [SOME] private packages from public pypi

### ISSUE THREAD

**Issue by goaaron** [python-poetry/poetry#7672] opened 2023-03-18 00:18 UTC
- **Poetry version**: 1.40
- **Python version**:  3.9 (RUNNING INSIDE OF CONDA)
- **OS version and name**: CentOS Linux 8 (Core)
- **pyproject.toml (tool I want to use across my software)**: https://gist.github.com/goaaron/8c84dec52e698679454a68ba5f78ddb4

- **pyproject.toml (Package installing above tool)**: https://gist.github.com/goaaron/3fb1b4cbfd2c5d673d4b5a9219353551

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

Hi! I have a private pypi server I am hosting packages on. Some of my poetry packages depend on these and publish their distributable back to the repo.

I'm running into an issue where when I do `poetry add tool` from my private source, that some of it's private repo dependencies get sourced from **PUBLIC** pypi. 

For example above:
When I install the tool, `pkg`1 (one of it's dependencies) is correctly sourced from the private repository. But `db` is pulled from pypi!

I assumed that because it was sourcing some of the nested dependencies from the private repo that there may be some issue with cache, but....

I've done all manner of clearing caches, reinstalling poetry, and I can't stop this from occurring. Weirdly enough things work fine on my mac. 

Any clues on how to get past this?

**Comment by radoering** [comment] 2023-03-18 05:32
Since you set `secondary=false` for your private repo your private source should be preferred compared to PyPI. However, if there is a newer version on PyPI, this version may still be used. If you want to disable PyPI completely, set `default=true` for your private repo.

**Comment by ralbertazzi** [comment] 2023-06-01 14:49
Closing as duplicate of https://github.com/python-poetry/poetry/issues/7981, which was closed with no actionable.

In short: there's no way for Poetry to know by default that the dependencies of your private package **must** be fetched from the private repository. A few solutions to achieve this (it is all documented in https://python-poetry.org/docs/repositories/):
- Use `explicit` priority and specify transitive dependencies too in your pyproject.toml, with explicit source
- Or, make your private repository higher priority than PyPI. At that point Poetry will try to fetch packages from your private repository first, else fall back to pypi.

**Closed by ralbertazzi** 2023-06-01 14:49 UTC
Labels: kind/bug, status/triage
