### ISSUE TITLE
Incompatibility Pip 20.1, poetry and conda-smithy ?

### ISSUE THREAD

**Issue by albop** [python-poetry/poetry#2409] opened 2020-05-12 17:56 UTC
I'm not sure it's a conda , a pip or a poetry issue so I've opened an issue on  Unfortunately, I'm not able to replicate it outside of the docker environment used to build conda packages, which makes it hard to provide precise details. What I did is summarized in the conda-smith issue: https://github.com/conda-forge/conda-smithy/issues/1315 . For good measure I also opened an issue on pip https://github.com/pypa/pip/issues/8226 .

I ran into some issue when trying a conda package for a package managed with poetry. Said package is https://github.com/conda-forge/dolang-feedstock, but I had the same issue with other python packages.
It is strange since afaik all pip commands used in conda-forge should be compatible with pep517 / poetry.
Also, it used to work with pip==20.0.2 and a simple workaround is to freeze this version in the environment used to build the package.
Sorry for the complicated bug report and multiple issue filling. I'm not sure who should ultimately be responsible for this and I'm a bit out of my depth.

**Comment by Secrus** [comment] 2022-05-16 21:21
Without more details, this is impossible to be investigated in any way. I am closing this due to its age, but if you still experience this, please provide more details and reproduction steps in new issue.

**Closed by Secrus** 2022-05-16 21:21 UTC
Labels: Bug, Triage
