### ISSUE TITLE
Unable to install PyCuda even on a new project

### ISSUE THREAD

**Issue by namoshizun** [python-poetry/poetry#8830] opened 2023-12-29 02:40 UTC
- **Poetry version**: 1.7.1
- **Python version**: 3.8.10
- **OS version and name**: Ubuntu 20.04.5 LTS
- **pyproject.toml**:
```
[tool.poetry]
name = "temp-proj"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api
```

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a [recommended method](https://python-poetry.org/docs/#installation).
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

Hi, I tried to install Pycuda using `poetry add pycuda` but with no success. It complains OverrideNeeded and IncompatibleConstraintsError which made little sense to me.... 

```




Using version ^2023.1 for pycuda

Updating dependencies
Resolving dependencies... Downloading https://files.pythonhosted.org/packages/24/3b/11fe92d68c6a42468ddab0cf03f454419b0788fff4e91ba46b8bebafeffd/Mako-1.3.0-py3-none-anyResolving dependencies... Downloading https://files.pythonhosted.org/packages/24/3b/11fe92d68c6a42468ddab0cf03f454419b0788fff4e91ba46b8bebafeffd/Mako-1.3.0-py3-none-anyResolving dependencies... (4.5s)

Package operations: 7 installs, 0 updates, 0 removals

  • Installing markupsafe (2.1.3)
  • Installing platformdirs (4.1.0)
  • Installing typing-extensions (4.9.0)
  • Installing appdirs (1.4.4)
  • Installing mako (1.3.0)
  • Installing pytools (2023.1.1)
  • Installing pycuda (2023.1): Failed

  OverrideNeeded

  ({Package('oldest-supported-numpy', '2023.12.21'): {'numpy': <Dependency numpy (==1.22.2)>}}, {Package('oldest-supported-numpy', '2023.12.21'): {'numpy': <Dependency numpy (==1.21.0)>}}, {Package('oldest-supported-numpy', '2023.12.21'): {'numpy': <Dependency numpy (==1.19.3)>}}, {Package('oldest-supported-numpy', '2023.12.21'): {'numpy': <Dependency numpy (==1.25.0)>}}, {Package('oldest-supported-numpy', '2023.12.21'): {'numpy': <Dependency numpy (==1.23.3)>}}, {Package('oldest-supported-numpy', '2023.12.21'): {'numpy': <Dependency numpy (<empty>)>}})

  at ~/.local/share/pypoetry/venv/lib/python3.8/site-packages/poetry/puzzle/provider.py:660 in complete_package
      656│                     current_overrides.update({dependency_package: package_overrides})
      657│                     overrides.append(current_overrides)
      658│
      659│             if overrides:
    → 660│                 raise OverrideNeeded(*overrides)
      661│
      662│         # Modifying dependencies as needed
      663│         clean_dependencies = []
      664│         for dep in dependencies:

The following error occurred when trying to handle this error:


  OverrideNeeded

  {Package('oldest-supported-numpy', '2023.12.21'): {'numpy': <Dependency numpy (==1.22.2)>}, Package('oldest-supported-numpy', '2023.12.12'): {'numpy': <Dependency numpy (==1.22.2)>}}

  at ~/.local/share/pypoetry/venv/lib/python3.8/site-packages/poetry/puzzle/provider.py:660 in complete_package
      656│                     current_overrides.update({dependency_package: package_overrides})
      657│                     overrides.append(current_overrides)
      658│
      659│             if overrides:
    → 660│                 raise OverrideNeeded(*overrides)
      661│
      662│         # Modifying dependencies as needed
      663│         clean_dependencies = []
      664│         for dep in dependencies:

The following error occurred when trying to handle this error:


  OverrideNeeded

  {Package('oldest-supported-numpy', '2023.12.21'): {'numpy': <Dependency numpy (==1.22.2)>}, Package('oldest-supported-numpy', '2023.12.12'): {'numpy': <Dependency numpy (==1.22.2)>}, Package('oldest-supported-numpy', '2023.10.25'): {'numpy': <Dependency numpy (==1.22.2)>}}

  at ~/.local/share/pypoetry/venv/lib/python3.8/site-packages/poetry/puzzle/provider.py:660 in complete_package
      656│                     current_overrides.update({dependency_package: package_overrides})
      657│                     overrides.append(current_overrides)
      658│
      659│             if overrides:
    → 660│                 raise OverrideNeeded(*overrides)
      661│
      662│         # Modifying dependencies as needed
      663│         clean_dependencies = []
      664│         for dep in dependencies:

The following error occurred when trying to handle this error:


  OverrideNeeded

  {Package('oldest-supported-numpy', '2023.12.21'): {'numpy': <Dependency numpy (==1.22.2)>}, Package('oldest-supported-numpy', '2023.12.12'): {'numpy': <Dependency numpy (==1.22.2)>}, Package('oldest-supported-numpy', '2023.10.25'): {'numpy': <Dependency numpy (==1.22.2)>}, Package('oldest-supported-numpy', '2023.8.3'): {'numpy': <Dependency numpy (==1.22.2)>}}

  at ~/.local/share/pypoetry/venv/lib/python3.8/site-packages/poetry/puzzle/provider.py:660 in complete_package
      656│                     current_overrides.update({dependency_package: package_overrides})
      657│                     overrides.append(current_overrides)
      658│
      659│             if overrides:
    → 660│                 raise OverrideNeeded(*overrides)
      661│
      662│         # Modifying dependencies as needed
      663│         clean_dependencies = []
      664│         for dep in dependencies:

The following error occurred when trying to handle this error:


  IncompatibleConstraintsError

  Incompatible constraints in requirements of oldest-supported-numpy (2022.11.19):
  numpy (==1.22.2) ; platform_machine == "loongarch64" and python_version < "3.11"
  numpy (==1.23.3) ; python_version == "3.9" and platform_system == "OS400"
  numpy ; python_version >= "3.9" and platform_python_implementation == "PyPy"

  at ~/.local/share/pypoetry/venv/lib/python3.8/site-packages/poetry/puzzle/provider.py:920 in _resolve_overlapping_markers
      916│                     specific_source_dependency = dep
      917│                 constraint = constraint.intersect(dep.constraint)
      918│             if constraint.is_empty():
      919│                 # conflict in overlapping area
    → 920│                 raise IncompatibleConstraintsError(package, *used_dependencies)
      921│
      922│             if not any(uses):
      923│                 # This is an edge case where the dependency is not required
      924│                 # for the resulting marker. However, we have to consider it anyway

Cannot install pycuda.
```

**Comment by dimbleby** [comment] 2023-12-29 09:14
What version of numpy should poetry put into its solution when `python_version == "3.9" and platform_system == "OS400" and platform_machine == "loongarch64"`?

You will need to report this to oldest-supported-numpy

**Comment by radoering** [comment] 2023-12-29 13:20
> You will need to report this to oldest-supported-numpy

It's already fixed in later versions of oldest-supported-numpy.

I couldn't reproduce it at first (by locking the build requirements of pycuda) and wondered why we are trying an old version of oldest-supported-numpy.

On closer inspection, this is what happens:

Installing `build_system_requires` (i.e. `{'oldest-supported-numpy', 'setuptools', 'wheel'}`) in
https://github.com/python-poetry/poetry/blob/a1999816f4676db9f7f8715a184fe34754dac50a/src/poetry/installation/chef.py#L133 even succeeds.

Installing `build_system_requires` and `requires_for_build` (i.e. `{'setuptools', 'wheel', 'oldest-supported-numpy', 'numpy>=1.6'}`) in https://github.com/python-poetry/poetry/blob/a1999816f4676db9f7f8715a184fe34754dac50a/src/poetry/installation/chef.py#L140-L143 fails because due to the additional numpy constraint, numpy is resolved before oldest-supported-numpy, which apparently is not a good idea.

The additional numpy constraint probably comes from https://github.com/inducer/pycuda/blob/5cb2e1a32f330c2984e2c1bf0579022494381ef1/setup.py#L220-L222.
I wonder if this adds any value or if it could be removed.

What strikes me right now is that we abort dependency resolution as soon as we encounter a package with incompatible constraints. We could probably do better by ignoring these broken versions of the package. That way we could use an older version which might not be broken. However, that's probably not a common use case. In this specific case we might end up in the latest numpy and some ancient oldest-supported-numpy, which probably is not intended...

Another improvement that kind of works around this issue would be to solve build requirements during installation only for the current environment. However, we'd still end with an up-to-date numpy and an ancient oldest-supported-numpy...

**Comment by dimbleby** [comment] 2023-12-29 18:47
> The additional numpy constraint probably comes from https://github.com/inducer/pycuda/blob/5cb2e1a32f330c2984e2c1bf0579022494381ef1/setup.py#L220-L222.
I wonder if this adds any value or if it could be removed.

almost certainly accidentally left behind at https://github.com/inducer/pycuda/pull/274 - @namoshizun you should consider submitting a merge request to pycuda to remove this

**Comment by namoshizun** [comment] 2023-12-30 02:39
> > The additional numpy constraint probably comes from https://github.com/inducer/pycuda/blob/5cb2e1a32f330c2984e2c1bf0579022494381ef1/setup.py#L220-L222.
> > I wonder if this adds any value or if it could be removed.
> 
> almost certainly accidentally left behind at [inducer/pycuda#274](https://github.com/inducer/pycuda/pull/274) - @namoshizun you should consider submitting a merge request to pycuda to remove this

Hmmm I'm still a bit confused what needs to be fixed exactly... The pycuda#274 MR you referenced adds a pyproject.toml which selects the Numpy version based on the Python version. This setup has been superseded by simply installing `oldest-supported-numpy` (see PyCuda's current pyproject.toml), which is supposed to do a better job at installing the most compatible Numpy. From @radoering's finding, it is the additional `numpy>=1.6` in PyCuda's `setup.py` causing the resolution problem. Are you suggesting that `numpy>=1.6` should be removed?

**Comment by dimbleby** [comment] 2023-12-30 09:51
Yes

**Closed** 2024-01-01 02:23 UTC
Labels: kind/bug, status/triage
