### ISSUE TITLE
Optional dependencies incorrectly being exported w/ optional groups and extras

### ISSUE THREAD

**Issue by vwxyzjn** [python-poetry/poetry#7743] opened 2023-03-30 18:33 UTC
```
Poetry
Version: 1.4.1
Python:  3.9.5

Virtualenv
Python:         3.9.5
Implementation: CPython
Path:           /home/costa/.cache/pypoetry/virtualenvs/poetry14bug-7MQTjeBG-py3.9
Executable:     /home/costa/.cache/pypoetry/virtualenvs/poetry14bug-7MQTjeBG-py3.9/bin/python
Valid:          True

System
Platform:   linux
OS:         posix
Python:     3.9.5
Path:       /home/costa/.pyenv/versions/3.9.5
Executable: /home/costa/.pyenv/versions/3.9.5/bin/python3.9
```

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

During `poetry export`, extras and optional groups do not work properly with each other. While `poetry export` works properly with either optional groups or extras, if I don't use extras, my pypi build do not have extra dependencies. If I don't use dependency groups, when calling `poetry install -E "A B"` will remove extra dependency "C", unlike `poetry install --with`.

### ❌ Have both extras and groups
```
[tool.poetry]
name = "poetry14bug"
version = "0.1.0"
description = ""
authors = ["Costa Huang <costa.huang@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
numpy = {version = "^1.24.2", optional = true}
pandas = {version = "^1.5.3", optional = true}


[tool.poetry.group.A]
optional = true
[tool.poetry.group.A.dependencies]
numpy = "^1.24.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.extras]
As = ["numpy", "pandas"]
```

Note that `numpy` is an optional dependency. When running `poetry export --without-hashes -o d.txt --without=A` I get the following, which included the optional `numpy`.

```
numpy==1.24.2 ; python_version >= "3.9" and python_version < "4.0"
```

### ✅ Have only extras

```
[tool.poetry]
name = "poetry14bug"
version = "0.1.0"
description = ""
authors = ["Costa Huang <costa.huang@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
numpy = {version = "^1.24.2", optional = true}
pandas = {version = "^1.5.3", optional = true}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.extras]
As = ["numpy", "pandas"]
```

`poetry export --without-hashes -o d.txt ` follows expectation and exports an empty `requirements.txt`.

### ✅ Have only extra groups
```
[tool.poetry]
name = "poetry14bug"
version = "0.1.0"
description = ""
authors = ["Costa Huang <costa.huang@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.group.A]
optional = true
[tool.poetry.group.A.dependencies]
numpy = "^1.24.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

`poetry export --without-hashes -o d.txt ` follows expectation and exports an empty `requirements.txt`.

**Comment by dimbleby** [comment] 2023-03-30 19:31
this should be reported in https://github.com/python-poetry/poetry-plugin-export, not here

but no need to bother because it's a duplicate of https://github.com/python-poetry/poetry-plugin-export/issues/34, in particular https://github.com/python-poetry/poetry-plugin-export/issues/34#issuecomment-1140243586

please close

**Closed** 2023-03-30 19:52 UTC
Labels: kind/bug, status/triage
