### ISSUE TITLE
poetry add {private git repo} raise "unexpected http resp 503"

### ISSUE THREAD

**Issue by raisons** [python-poetry/poetry#8887] opened 2024-01-17 02:49 UTC
- **Poetry version**: 1.7.1
- **Python version**: 3.11
- **OS version and name**: macos 14.2.1
- **pyproject.toml**: 

- [ ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a [recommended method](https://python-poetry.org/docs/#installation).
- [ ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
When I enter the following command
```shell
poetry add git+http://{username}:{token}@{ip}/repo.git
```
output like this
```shell
unexpected http resp 503 for http://{username}/{token}@{ip}/repo.git/info/refs?service=git-upload-pack
```

I noticed that it replaces ":" to "/"

**Comment by dimbleby** [comment] 2024-01-17 07:56
503 is a server error, perhaps you should start at the server.

Highly unlikely that anyone can help if you do not provide a way to reproduce this.

**Comment by raisons** [comment] 2024-01-18 09:33
```python
from poetry.core.vcs.git import ParsedUrl

TEST_GIT_URLS = [
    "https://github.com/python-poetry/poetry.git",
    "git+https://github.com/python-poetry/poetry.git",
    "git+https://root:password@github.com/python-poetry/poetry.git"
]

for url in TEST_GIT_URLS:
    print(ParsedUrl.parse(url))
```

this code output:
```plaintext
https://github.com/python-poetry/poetry.git
https://github.com/python-poetry/poetry.git
https://root/password
```

My project must rely on a private repository. 
this is gitlab document: [https://docs.gitlab.com/ee/user/project/deploy_tokens/](https://docs.gitlab.com/ee/user/project/deploy_tokens/)

> There is no problem installing with pip

**Comment by abn** [comment] 2024-03-01 00:05
Duplicate of #7467 #4152 #2062

Poetry does not support username password in your vcs url at the moment, but you can configure them as an http basic credential. 

Doc: https://python-poetry.org/docs/dependency-specification/#git-dependencies

This might be supported in a future version with some heavy warnings as this is bad practice in most cases and often times a mistake.

**Closed by abn** 2024-03-01 00:05 UTC
Labels: kind/bug, status/triage
