### ISSUE TITLE
git repo with hypthens fails with error

### ISSUE THREAD

**Issue by michael-c-hoffman** [python-poetry/poetry#4678] opened 2021-10-27 15:59 UTC
- [ x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Fedora 34
- **Poetry version**: 1.1.5
- **Link of a [Gist](https://gist.github.com/michael-c-hoffman/34ded6f312419fda97254437c052380b)

## Issue
When adding a git repo that includes a hyphen in the org/path poetry fails to add with an error:
```
TypeError

  expected string or bytes-like object

  at ~/.local/lib/python3.9/site-packages/poetry/core/utils/helpers.py:27 in canonicalize_name
       23│ _canonicalize_regex = re.compile(r"[-_]+")
       24│ 
       25│ 
       26│ def canonicalize_name(name):  # type: (str) -> str
    →  27│     return _canonicalize_regex.sub("-", name).lower()
       28│ 
       29│ 
       30│ def module_name(name):  # type: (str) -> str
       31│     return canonicalize_name(name).replace(".", "_").replace("-", "_")
```

**Comment by gabrielbdsantos** [comment] 2021-11-02 22:47
I'm having the same issue on poetry 1.1.11.

`poetry add --help` gives `poetry add git+https://github.com/python-poetry/poetry.git` as an example, which is indeed a valid one. I have just tried it. However, when I try `poetry add git+https://github.com/tpaviot/pythonocc-core.git`, poetry throws that issue.

So, it seems that the problem is not with hyphens in general, but only in the package names, right?

**Comment by michael-c-hoffman** [comment] 2021-11-03 08:53
Correct

**Comment by michael-c-hoffman** [comment] 2021-11-10 14:03
yes I believe that is what is needed

**Comment by michael-c-hoffman** [comment] 2021-11-17 00:25
can this get merged into the next release?

**Comment by neersighted** [comment] 2021-11-17 02:02
> 
> 
> can this get merged into the next release?

Hi @michael-c-hoffman -- I'm not aware of any outstanding PRs with this fix. A PR with the fix and a regression test would be welcomed, and I'd love to be pointed to an already-extant one if I missed it.

**Comment by nathan-kairon** [comment] 2022-02-18 14:53
I got the same issue

**Comment by abn** [comment] 2022-05-11 00:41
I suspect the reported issue has been resolved with #5428 as the vay we create the directory was changed. This might also be a duplicate of #3392.

**Comment by neersighted** [comment] 2022-05-11 02:43
@skairunner Could you please test your failing repo against current master?

**Comment by skairunner** [comment] 2022-05-13 09:40
I am happy to confirm that `poetry@master` resolves this particular issue.

**Closed** 2022-05-13 11:40 UTC
Labels: Bug, Triage
