### ISSUE TITLE
"FileDependency.hash() takes 1 positional argument but 2 were given" error when running `poetry install`

### ISSUE THREAD

**Issue by DetachHead** [python-poetry/poetry#4923] opened 2021-12-21 14:00 UTC
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

windows 10
- **Poetry version**: 1.1.12
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://github.com/DetachHead/python-project/blob/master/pyproject.toml

## Issue
```
C:\Users\user\IdeaProjects\python-project>poetry install -vvv
Using virtualenv: C:\Users\user\IdeaProjects\python-project\.venv
Installing dependencies from lock file

Finding the necessary packages for the current system

Package operations: 28 installs, 0 updates, 0 removals

  • Installing colorama (0.4.4)
  • Installing lazy-object-proxy (1.7.1)
  • Installing pyparsing (3.0.6)
  • Installing wrapt (1.13.3)

  Stack trace:

  5  ~\.poetry\lib\poetry\installation\executor.py:203 in _execute_operation
      201│ 
      202│             try:
    → 203│                 result = self._do_execute_operation(operation)
      204│             except EnvCommandError as e:
      205│                 if e.e.returncode == -2:

  4  ~\.poetry\lib\poetry\installation\executor.py:277 in _do_execute_operation
      275│             return 0
      276│
    → 277│         result = getattr(self, "_execute_{}".format(method))(operation)
      278│
      279│         if result != 0:

  3  ~\.poetry\lib\poetry\installation\executor.py:412 in _execute_install
      410│ 
      411│     def _execute_install(self, operation):  # type: (Install) -> None
    → 412│         return self._install(operation)
      413│
      414│     def _execute_update(self, operation):  # type: (Update) -> None

  2  ~\.poetry\lib\poetry\installation\executor.py:438 in _install
      436│             archive = self._download_link(operation, Link(package.source_url))
      437│         else:
    → 438│             archive = self._download(operation)
      439│ 
      440│         operation_message = self.get_operation_message(operation)

  1  ~\.poetry\lib\poetry\installation\executor.py:586 in _download
      584│         link = self._chooser.choose_for(operation.package)
      585│
    → 586│         return self._download_link(operation, link)
      587│
      588│     def _download_link(self, operation, link):

  TypeError

  FileDependency.hash() takes 1 positional argument but 2 were given

  at ~\.poetry\lib\poetry\installation\executor.py:622 in _download_link
      618│             for hash_type in hash_types:
      619│                 archive_hashes.add(
      620│                     "{}:{}".format(
      621│                         hash_type,
    → 622│                         FileDependency(package.name, archive_path).hash(hash_type),
      623│                     )
      624│                 )
      625│
      626│             if archive_hashes.isdisjoint(hashes):


  Stack trace:

  5  ~\.poetry\lib\poetry\installation\executor.py:203 in _execute_operation
      201│
      202│             try:
    → 203│                 result = self._do_execute_operation(operation)
      204│             except EnvCommandError as e:
      205│                 if e.e.returncode == -2:

  4  ~\.poetry\lib\poetry\installation\executor.py:277 in _do_execute_operation
      275│             return 0
      276│
    → 277│         result = getattr(self, "_execute_{}".format(method))(operation)
      278│
      279│         if result != 0:

  3  ~\.poetry\lib\poetry\installation\executor.py:412 in _execute_install
      410│
      411│     def _execute_install(self, operation):  # type: (Install) -> None
    → 412│         return self._install(operation)
      413│
      414│     def _execute_update(self, operation):  # type: (Update) -> None

  2  ~\.poetry\lib\poetry\installation\executor.py:438 in _install
      436│             archive = self._download_link(operation, Link(package.source_url))
      437│         else:
    → 438│             archive = self._download(operation)
      439│
      440│         operation_message = self.get_operation_message(operation)

  1  ~\.poetry\lib\poetry\installation\executor.py:586 in _download
      584│         link = self._chooser.choose_for(operation.package)
      585│
    → 586│         return self._download_link(operation, link)
      587│
      588│     def _download_link(self, operation, link):

  TypeError

  FileDependency.hash() takes 1 positional argument but 2 were given

  at ~\.poetry\lib\poetry\installation\executor.py:622 in _download_link
      618│             for hash_type in hash_types:
      619│                 archive_hashes.add(
      620│                     "{}:{}".format(
      621│                         hash_type,
    → 622│                         FileDependency(package.name, archive_path).hash(hash_type),
      623│                     )
      624│                 )
      625│
      626│             if archive_hashes.isdisjoint(hashes):


  Stack trace:

  5  ~\.poetry\lib\poetry\installation\executor.py:203 in _execute_operation
      201│
      202│             try:
    → 203│                 result = self._do_execute_operation(operation)
      204│             except EnvCommandError as e:
      205│                 if e.e.returncode == -2:

  4  ~\.poetry\lib\poetry\installation\executor.py:277 in _do_execute_operation
      275│             return 0
      276│
    → 277│         result = getattr(self, "_execute_{}".format(method))(operation)
      278│
      279│         if result != 0:

  3  ~\.poetry\lib\poetry\installation\executor.py:412 in _execute_install
      410│
      411│     def _execute_install(self, operation):  # type: (Install) -> None
    → 412│         return self._install(operation)
      413│
      414│     def _execute_update(self, operation):  # type: (Update) -> None

  2  ~\.poetry\lib\poetry\installation\executor.py:438 in _install
      436│             archive = self._download_link(operation, Link(package.source_url))
      437│         else:
    → 438│             archive = self._download(operation)
      439│
      440│         operation_message = self.get_operation_message(operation)

  1  ~\.poetry\lib\poetry\installation\executor.py:586 in _download
      584│         link = self._chooser.choose_for(operation.package)
      585│
    → 586│         return self._download_link(operation, link)
      587│
      588│     def _download_link(self, operation, link):

  TypeError

  FileDependency.hash() takes 1 positional argument but 2 were given

  at ~\.poetry\lib\poetry\installation\executor.py:622 in _download_link
      618│             for hash_type in hash_types:
      619│                 archive_hashes.add(
      620│                     "{}:{}".format(
      621│                         hash_type,
    → 622│                         FileDependency(package.name, archive_path).hash(hash_type),
      623│                     )
      624│                 )
      625│
      626│             if archive_hashes.isdisjoint(hashes):


  Stack trace:

  5  ~\.poetry\lib\poetry\installation\executor.py:203 in _execute_operation
      201│
      202│             try:
    → 203│                 result = self._do_execute_operation(operation)
      204│             except EnvCommandError as e:
      205│                 if e.e.returncode == -2:

  4  ~\.poetry\lib\poetry\installation\executor.py:277 in _do_execute_operation
      275│             return 0
      276│
    → 277│         result = getattr(self, "_execute_{}".format(method))(operation)
      278│
      279│         if result != 0:

  3  ~\.poetry\lib\poetry\installation\executor.py:412 in _execute_install
      410│
      411│     def _execute_install(self, operation):  # type: (Install) -> None
    → 412│         return self._install(operation)
      413│
      414│     def _execute_update(self, operation):  # type: (Update) -> None

  2  ~\.poetry\lib\poetry\installation\executor.py:438 in _install
      436│             archive = self._download_link(operation, Link(package.source_url))
      437│         else:
    → 438│             archive = self._download(operation)
      439│
      440│         operation_message = self.get_operation_message(operation)

  1  ~\.poetry\lib\poetry\installation\executor.py:586 in _download
      584│         link = self._chooser.choose_for(operation.package)
      585│
    → 586│         return self._download_link(operation, link)
      587│
      588│     def _download_link(self, operation, link):

  TypeError

  FileDependency.hash() takes 1 positional argument but 2 were given

  at ~\.poetry\lib\poetry\installation\executor.py:622 in _download_link
      618│             for hash_type in hash_types:
      619│                 archive_hashes.add(
      620│                     "{}:{}".format(
      621│                         hash_type,
    → 622│                         FileDependency(package.name, archive_path).hash(hash_type),
      623│                     )
      624│                 )
      625│
      626│             if archive_hashes.isdisjoint(hashes):
```

**Comment by radoering** [comment] 2021-12-29 09:32
Can you check your poetry-core version? The hash method of FileDependency got an additional argument in poetry-core [1.0.6](https://github.com/python-poetry/poetry-core/blob/1.0.6/poetry/core/packages/file_dependency.py#L71) (compared to [1.0.5](https://github.com/python-poetry/poetry-core/blob/1.0.5/poetry/core/packages/file_dependency.py#L71)). Normally, when installing poetry 1.1.12, poetry-core ~1.0.7 should be installed (see [pyproject.toml of poetry](https://github.com/python-poetry/poetry/blob/1.1.12/pyproject.toml#L27)).

Besides, I can't access the linked pyproject.toml (404 Not Found).

**Comment by DetachHead** [comment] 2021-12-30 05:51
unfortunately i since completely deleted and reinstalled poetry using pipx following advice i got on #2449. it seems i don't even have poetry-core anymore but everything seems to be working fine now. from memory i might have had 1.0.0 but i'm not sure

that said, i think there are significant issues with the either the install script or the update command. it seems updating poetry can completely corrupt the install in multiple different ways, but i don't really know how to reproduce either this issue or the one in #2449

**Comment by clintonroy** [comment] 2021-12-30 06:02
(if you can't reproduce the issue, may as well close it)

**Closed** 2022-07-09 14:52 UTC
Labels: Bug, Triage
