### ISSUE TITLE
zsh completion for `poetry env` is missing sub-commands & options

### ISSUE THREAD

**Issue by juhoautio** [python-poetry/poetry#1855] opened 2020-01-09 16:19 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS Catalina 10.15.2
- **Poetry version**: 1.0.0
- **Link of a Gist with the contents of your pyproject.toml file**: N/A

## Issue

The `poetry completions zsh` output doesn't have anything for `poetry env`, just this:
```
            (env)
            opts+=()
            ;;
```

Help shows the sub-commands for `poetry env`:
```
❯ poetry env -h
USAGE
      poetry env
  or: poetry env info [-p]
  or: poetry env list [--full-path]
  or: poetry env remove <python>
  or: poetry env use <python>

COMMANDS
  info
    Displays information about the current environment.

    -p (--path)          Only display the environment's path.

  list
    Lists all virtualenvs associated with the current project.

    --full-path          Output the full paths of the virtualenvs.

  remove
    Removes a specific virtualenv associated with the project.

    <python>             The python executable to remove the virtualenv for.

  use
    Activates or creates a new virtualenv for the current project.

    <python>             The python executable to use.

GLOBAL OPTIONS
  -h (--help)            Display this help message
  -q (--quiet)           Do not output any message
  -v (--verbose)         Increase the verbosity of messages: "-v" for normal output, "-vv" for more verbose output and "-vvv" for debug
  -V (--version)         Display this application version
  --ansi                 Force ANSI output
  --no-ansi              Disable ANSI output
  -n (--no-interaction)  Do not ask any interactive question
```

Help is also available for sub-commands, for example:
```
❯ poetry env info -h
USAGE
  poetry env info [-p]

OPTIONS
  -p (--path)            Only display the environment's path.

GLOBAL OPTIONS
  -h (--help)            Display this help message
  -q (--quiet)           Do not output any message
  -v (--verbose)         Increase the verbosity of messages: "-v" for normal output, "-vv" for more verbose output and "-vvv" for debug
  -V (--version)         Display this application version
  --ansi                 Force ANSI output
  --no-ansi              Disable ANSI output
  -n (--no-interaction)  Do not ask any interactive question
```

Here's the full completions output:
```
❯ poetry completions zsh
#compdef poetry

_poetry_52efa89bd527c06c_complete()
{
    local state com cur

    cur=${words[${#words[@]}]}

    # lookup for command
    for word in ${words[@]:1}; do
        if [[ $word != -* ]]; then
            com=$word
            break
        fi
    done

    if [[ ${cur} == --* ]]; then
        state="option"
        opts=("--ansi:Force ANSI output" "--help:Display this help message" "--no-ansi:Disable ANSI output" "--no-interaction:Do not ask any interactive question" "--quiet:Do not output any message" "--verbose:Increase the verbosity of messages: \\\"-v\\\" for normal output, \\\"-vv\\\" for more verbose output and \\\"-vvv\\\" for debug" "--version:Display this application version")
    elif [[ $cur == $com ]]; then
        state="command"
        coms=("about:Shows information about Poetry." "add:Adds a new dependency to pyproject.toml." "build:Builds a package, as a tarball and a wheel by default." "cache:Interact with Poetry\'s cache" "check:Checks the validity of the pyproject.toml file." "config:Manages configuration settings." "debug:Debug various elements of Poetry." "env:Interact with Poetry\'s project environments." "export:Exports the lock file to alternative formats." "help:Display the manual of a command" "init:Creates a basic pyproject.toml file in the current directory." "install:Installs the project dependencies." "lock:Locks the project dependencies." "new:Creates a new Python project at <path\>." "publish:Publishes a package to a remote repository." "remove:Removes a package from the project dependencies." "run:Runs a command in the appropriate environment." "search:Searches for packages on remote repositories." "self:Interact with Poetry directly." "shell:Spawns a shell within the virtual environment." "show:Shows information about packages." "update:Update the dependencies as according to the pyproject.toml file." "version:Shows the version of the project or bumps it when a validbump rule is provided.")
    fi

    case $state in
        (command)
            _describe 'command' coms
        ;;
        (option)
            case "$com" in

            (about)
            opts+=()
            ;;

            (add)
            opts+=("--allow-prereleases:Accept prereleases." "--dev:Add as a development dependency." "--dry-run:Output the operations but do not execute anything \(implicitly enables --verbose\)." "--extras:Extras to activate for the dependency." "--optional:Add as an optional dependency." "--platform:Platforms for which the dependency must be installed." "--python:Python version for which the dependency must be installed.")
            ;;

            (build)
            opts+=("--format:Limit the format to either sdist or wheel.")
            ;;

            (cache)
            opts+=()
            ;;

            (check)
            opts+=()
            ;;

            (config)
            opts+=("--list:List configuration settings." "--local:Set/Get from the project\'s local configuration." "--unset:Unset configuration setting.")
            ;;

            (debug)
            opts+=()
            ;;

            (env)
            opts+=()
            ;;

            (export)
            opts+=("--dev:Include development dependencies." "--extras:Extra sets of dependencies to include." "--format:Format to export to." "--output:The name of the output file." "--with-credentials:Include credentials for extra indices." "--without-hashes:Exclude hashes from the exported file.")
            ;;

            (help)
            opts+=()
            ;;

            (init)
            opts+=("--author:Author name of the package." "--dependency:Package to require, with an optional version constraint, e.g. requests:\^2.10.0 or requests=2.11.1." "--description:Description of the package." "--dev-dependency:Package to require for development, with an optional version constraint, e.g. requests:\^2.10.0 or requests=2.11.1." "--license:License of the package." "--name:Name of the package.")
            ;;

            (install)
            opts+=("--dry-run:Output the operations but do not execute anything \(implicitly enables --verbose\)." "--extras:Extra sets of dependencies to install." "--no-dev:Do not install the development dependencies." "--no-root:Do not install the root package \(the current project\).")
            ;;

            (lock)
            opts+=()
            ;;

            (new)
            opts+=("--name:Set the resulting package name." "--src:Use the src layout for the project.")
            ;;

            (publish)
            opts+=("--build:Build the package before publishing." "--cert:Certificate authority to access the repository." "--client-cert:Client certificate to access the repository." "--password:The password to access the repository." "--repository:The repository to publish the package to." "--username:The username to access the repository.")
            ;;

            (remove)
            opts+=("--dev:Remove a package from the development dependencies." "--dry-run:Output the operations but do not execute anything \(implicitly enables --verbose\).")
            ;;

            (run)
            opts+=()
            ;;

            (search)
            opts+=()
            ;;

            (self)
            opts+=()
            ;;

            (shell)
            opts+=()
            ;;

            (show)
            opts+=("--all:Show all packages \(even those not compatible with current system\)." "--latest:Show the latest version." "--no-dev:Do not list the development dependencies." "--outdated:Show the latest version but only for packages that are outdated." "--tree:List the dependencies as a tree.")
            ;;

            (update)
            opts+=("--dry-run:Output the operations but do not execute anything \(implicitly enables --verbose\)." "--lock:Do not perform operations \(only update the lockfile\)." "--no-dev:Do not update the development dependencies.")
            ;;

            (version)
            opts+=()
            ;;

            esac

            _describe 'option' opts
        ;;
        *)
            # fallback to file completion
            _arguments '*:file:_files'
    esac
}

_poetry_52efa89bd527c06c_complete "$@"
compdef _poetry_52efa89bd527c06c_complete /Users/juhoautio/.pyenv/versions/3.7.5/bin/poetry
```

**Comment by nickolayl** [comment] 2020-05-23 21:02
For me either. macOS Catalina, zsh, Poetry 1.0.5

**Comment by mkniewallner** [comment] 2022-05-28 12:17
It looks like latest Poetry beta version (`1.2.0b1`) now shows all `env` sub-commands and their options:
```
            (env info)
            opts+=("--path:Only display the environment\'s path.")
            ;;

            (env list)
            opts+=("--full-path:Output the full paths of the virtualenvs.")
            ;;

            (env remove)
            opts+=("--all:Remove all managed virtual environments associated with the project.")
            ;;

            (env use)
            opts+=()
            ;;
```

Tested by doing:
```shell
curl -sSL https://install.python-poetry.org | python - --version 1.2.0b1
poetry completions zsh
```

Could you confirm if it solves the issue?

**Comment by abn** [comment] 2022-05-28 13:28
Related: https://github.com/python-poetry/cleo/issues/133

**Comment by juhoautio** [comment] 2022-05-30 18:20
Thanks for the update! I tested installing the completions with the command above and **I can see that the definitions for env subcommands appear**.

However, having the new output stored in my `/usr/local/share/zsh/site-functions/_poetry` **causes weird behavior**.

First of all, **it completes the sub-command with an additional slash**: `poetry env\ info` – which is not a valid command..

`poetry env` + tab adds the slash and shows the expected subcommands:
```
❯ poetry env\ 
env info    -- Displays information about the current environment.
env list    -- Lists all virtualenvs associated with the current project.
env remove  -- Remove virtual environments associated with the project.
env use     -- Activates or creates a new virtualenv for the current project.
```

Also, with this my zsh **is unable to autocomplete the option(s) for the subcommand**. I was trying `poetry env info --p` + tab, hoping to get `--path` completed but zsh just offers the global options of poetry:
```
❯ poetry env info --p
--help            -- Display help for the given command. When no command is given display help for the list command.
--no-interaction  -- Do not ask any interactive question.
--quiet           -- Do not output any message.
--version         -- Display this application version.
```

Is this working as expected for someone else on zsh? Sorry, if this is a user error. I'm not an expert in the internals of tab comp definitions.

**Comment by mkniewallner** [comment] 2022-05-31 21:28
> Is this working as expected for someone else on zsh? Sorry, if this is a user error. I'm not an expert in the internals of tab comp definitions.

Just installed zsh to test, and I do reproduce the issue you report.

Unfortunately I'm far from knowledgeable on zsh completions to know how to fix the generated completions.

Since the completions are generated by https://github.com/python-poetry/cleo, it may be best to report the issue here.

**Comment by juhoautio** [comment] 2022-06-01 08:32
> (Maybe) Related: [python-poetry/cleo#133](https://github.com/python-poetry/cleo/issues/133)

Could be. I wonder if bash and zsh completions are independent though. 

Seems like there's an issue also about entirely missing the sub-commands with zsh https://github.com/python-poetry/cleo/issues/84 – likely the issue is basically resolved because now the sub-commands are showing up. Even though it is still buggy.

> Since the completions are generated by https://github.com/python-poetry/cleo, it may be best to report the issue here.

I'll do that.

**Comment by Secrus** [comment] 2022-09-18 22:35
This issue is already tracked in Cleo repository (python-poetry/cleo#84). Closing this

**Closed by Secrus** 2022-09-18 22:35 UTC
Labels: kind/bug, area/cli, status/external-issue
