### ISSUE TITLE
incompatible with xattr v0.10.0

### ISSUE THREAD

**Issue by tjni** [python-poetry/poetry#6928] opened 2022-10-31 17:42 UTC
- **Poetry version**: 1.2.2
- **Python version**: 3.10
- **OS version and name**: macOS 12.6
- **pyproject.toml**: N/A

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

xattr [released v0.10.0](https://github.com/xattr/xattr/releases/tag/v0.10.0) recently, which is not sem-ver compatible with ^0.9.7 specified in pyproject.toml. The release notes suggest this is a safe update to make.

I don't anticipate this to be hard, but I haven't contributed before so I would need to find some time to learn how to do so. I will eventually get around to it if no one else finds this easy and quick enough to tackle.

**Comment by neersighted** [comment] 2022-10-31 17:44
Potential dupe of #6891 -- have not yet taken a close look, but the timing seems directly related.

**Comment by moonsikpark** [comment] 2022-11-11 02:09
#6891 is not a problem with the user's environment as suggested by the maintainer of xattr at xattr/xattr#108, it was in fact the problem of the package and was fixed by xattr/xattr#106.

Looking at the [changes in the version bump](https://github.com/xattr/xattr/compare/v0.9.9...v0.10.0), there does not seem to be any significant changes other than xattr/xattr#106. I will write a PR to bump the version in poetry.

**Closed** 2022-11-11 21:32 UTC
Labels: area/project/deps
