### ISSUE TITLE
Poetry 1.3 dies when run with a TTY reporting size 0/0

### ISSUE THREAD

**Issue by calebnorman** [python-poetry/poetry#7184] opened 2022-12-12 17:44 UTC
- **Poetry version**: 1.3.1
- **Python version**: 3.10
- **OS version and name**: Ubuntu 20.04
- **pyproject.toml**: [pyproject.toml](https://gist.github.com/calebnorman/2ea4019a6ab188bcd52236baf6315337)

- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
Running as part of a circle ci workflow. Steps below. The command `poetry install` identifies the `Package Operations` and then exits with code 1. (output below)
SSH into the box and running `poetry install` produces the normal expected behavior. 

### workflow steps
```
...
pyenv global 3.10.2
pip install poetry==1.2.2
export PATH="/home/circleci/.local/bin:$PATH"

poetry install -vvv
...
```

###Poetry Install Step
```
#!/bin/bash -eo pipefail
poetry install -vvv

Creating virtualenv fastapi-template-repository-3aSsmiER-py3.10 in /home/circleci/.cache/pypoetry/virtualenvs
Using virtualenv: /home/circleci/.cache/pypoetry/virtualenvs/fastapi-template-repository-3aSsmiER-py3.10
Installing dependencies from lock file

Finding the necessary packages for the current system

Package operations: 71 installs, 1 update, 0 removals


Exited with code exit status 1
```

**Comment by neersighted** [comment] 2022-12-12 18:03
A user on Discord has been debugging this as well, it appears to only happen in CircleCI when using the same base image. I've asked that user to post the debugging they've done here, but the basic thing we know right now is that Poetry is receiving a SIGINT right after printing the installer summary (determined via an strace).

**Comment by maurczz** [comment] 2022-12-12 18:09
Had the same issue this morning with eh latest `poetry`. Pinning back to `1.2.2` during the build solves the issue.

**Comment by TheKevJames** [comment] 2022-12-12 20:13
`strace --follow-forks` is interesting here as well: [failure output](https://circleci.com/api/v1.1/project/github/TheKevJames/experiments/697/output/111/0?file=true&allocation-id=639787ec88a18c242c9d3823-0-build%2FE838DEF) contrasted with [successful output](https://circleci.com/api/v1.1/project/github/TheKevJames/experiments/694/output/111/0?file=true&allocation-id=639787eb88a18c242c9d3812-0-build%2F6724D047).

Most notably in that, I see that the SIGINT is happening in both cases -- on further inspection, I think we may have been incorrect in our first read through @neersighted : I don't think this is poetry reporting a SIGINT, but rather us cleaning up our SIGINT handler as part of normal shutdown procedures. It looks like poetry is actually self-terminating in response to the forked process exiting (with exit code 0), I think??

**Comment by brandon-leapyear** [comment] 2022-12-12 20:30
I also see this happen in python versions 3.8 to 3.10, but it doesn't happen on 3.11 (both `cimg/python:3.x` and `python:3.x`). It also succeeds if you SSH in and manually run `poetry install`. I'm also unable to repro with Docker. Overall, very frustrating to debug 😢

**Comment by neersighted** [comment] 2022-12-12 20:51
Good job gathering those straces, it looks like what is happening is the worker is throwing an exception and we're swallowing it. This appears to be due to some issue getting Cleo's `ExceptionTrace` imported (maybe related to crashtest?):

https://github.com/python-poetry/poetry/blob/128c528f392cd79b3f19f0dbf09b6e4c74809e2a/src/poetry/installation/executor.py#L276-L297

I don't have more time to dig into this right now, but the exception handling here is plainly suspect (and we definitely should not be doing a conditional import in an exception handler).

**Comment by TheKevJames** [comment] 2022-12-12 21:24
Yup, definitely a Cleo issue:
```
Traceback (most recent call last):
  File "/root/.local/share/pypoetry/venv/lib/python3.10/site-packages/poetry/installation/executor.py", line 244, in _execute_operation
    self._sections[id(operation)].write_line(
  File "/root/.local/share/pypoetry/venv/lib/python3.10/site-packages/cleo/io/outputs/output.py", line 88, in write_line
    self.write(messages, new_line=True, verbosity=verbosity, type=type)
  File "/root/.local/share/pypoetry/venv/lib/python3.10/site-packages/cleo/io/outputs/output.py", line 109, in write
    self._write(message, new_line=new_line)
  File "/root/.local/share/pypoetry/venv/lib/python3.10/site-packages/cleo/io/outputs/section_output.py", line 83, in _write
    self.add_content(message)
  File "/root/.local/share/pypoetry/venv/lib/python3.10/site-packages/cleo/io/outputs/section_output.py", line 69, in add_content
    len(self.remove_format(line_content).replace("\t", "        "))
ZeroDivisionError: division by zero
```

**Comment by TheKevJames** [comment] 2022-12-12 21:25
https://github.com/python-poetry/cleo/blob/35896a0bc27e92f1d1f96d66facbf31531356ed7/src/cleo/io/outputs/section_output.py#L70

**Comment by neersighted** [comment] 2022-12-12 21:29
Ah, `_terminal` is the smoking gun. cc @Secrus

**Comment by TheKevJames** [comment] 2022-12-12 21:29
Ultimate cause is this PR: https://github.com/python-poetry/cleo/pull/175

Note that the stdlib method we're using acts differently in 3.11, which masks the issue: https://docs.python.org/3/library/shutil.html#shutil.get_terminal_size

**Comment by TheKevJames** [comment] 2022-12-12 21:29
Note also that the stdlib method falls back to using the terminal height/width values, which explains why the behaviour is different for interactive/non-interactive shells.

**Comment by TheKevJames** [comment] 2022-12-12 21:34
Confirming this by running the following on CircleCI, in otherwise equivalent jobs:
```
# python3.10
$ python3 -c 'import shutil; print(shutil.get_terminal_size())'
os.terminal_size(columns=0, lines=0)
# python3.11
$ python3 -c 'import shutil; print(shutil.get_terminal_size())'
os.terminal_size(columns=80, lines=24)
```

**Comment by neersighted** [comment] 2022-12-12 21:34
I think that makes Circle unique here is the fact it's not allocating a TTY, unlike most CI systems (which at this point, tend to provide full VT emulation so they can capture nice colorful/fancy logs). This should be possible to reproduce locally with `docker run` (without `-t`).

**Comment by TheKevJames** [comment] 2022-12-12 21:42
Yeah, it didn't even occur to me earlier on that this might be the case. Fancy logs generally show in CircleCI, so I made the erroneous assumption it was just via standard emulation.

Tossed up a quick fix PR [here](https://github.com/python-poetry/cleo/pull/298), though having someone with more Cleo-specific experience take a look would be fantastic.

I'd also note that it took patching poetry source code to discover this issue, given the cleo stuff was eating the trace. I wonder if there's a way we could at least fall back to not-so-fancy output in case of any errors?

**Comment by TheKevJames** [comment] 2022-12-12 21:48
You'd definitely have a better understanding than I on this! I was thinking potentially could be done fairly simply, though, eg. as a global try-except:
```python
except ...:
    try:
        # all the existing exception handler stuff, fancy formatting, whatever
    except Exception:
        traceback.print_exc()
```

**Comment by rlgomes** [comment] 2022-12-13 16:51
FYI a workaround is to run with `--no-ansi` as I stumbled upon this error and then while debugging used that option to clear up some of the output and things ran succesfully.

**Comment by qwertyuu** [comment] 2022-12-13 18:48
@rlgomes you've fixed our work deployment pipeline! Thanks. `--no-ansi` makes `poetry install` work as intended.

**Comment by jfroy** [comment] 2022-12-14 00:09
Just to add that install hangs on macOS 13.1 with Homebrew python 3.10.

**Comment by neersighted** [comment] 2022-12-14 01:33
That is unrelated to what is being discussed here, which is related to CircleCI reporting a TTY with dimensions 0/0.

**Comment by wadimiusz** [comment] 2022-12-14 12:06
Just confirming that I also faced this bug and that using `poetry install --no-ansi` did the trick.

**Comment by jaoxford** [comment] 2023-01-05 14:22
Same thing happens for us, when running `poetry install -vvv; echo $?` from CodeFresh. We get the following:
```python
Loading configuration file /codefresh/volume/yo-main-application/poetry.toml
Using virtualenv: /root/.venv
Installing dependencies from lock file

Finding the necessary packages for the current system

Package operations: 211 installs, 0 updates, 0 removals

1
```

1 being the exit code.

**Comment by neersighted** [comment] 2023-01-05 14:38
Is it the same thing? Please report your tty size; if it's not `0/0` it's #7148 instead, which we still don't understand the root cause of.

**Comment by jaoxford** [comment] 2023-01-05 14:44
`--no-ansi` solved our issue.

**Comment by FranzForstmayr** [comment] 2023-01-09 08:57
Finally more output:

```
Loading configuration file /home/rd-app-host/.config/pypoetry/config.toml
Loading configuration file /home/rd-app-host/.config/pypoetry/auth.toml
Adding repository gitlab (https://gitlab.hft.rosenberger.local/api/v4/groups/100/-/packages/pypi/simple) and setting it as secondary
Using virtualenv: /home/rd-app-host/apps/power-estimator-tool/.venv
Installing dependencies from lock file

Finding the necessary packages for the current system

Package operations: 41 installs, 0 updates, 0 removals, 62 skipped


  Stack trace:

  4  ~/.local/share/pypoetry/venv/lib/python3.9/site-packages/poetry/installation/executor.py:251 in _execute_operation
      249|                 if self._should_write_operation(operation):
      250|                     if not operation.skipped:
    > 251|                         self._io.write_line(

  Stack trace:

  4  ~/.local/share/pypoetry/venv/lib/python3.9/site-packages/poetry/installation/executor.py:251 in _execute_operation
      249|                 if self._should_write_operation(operation):
      250|                     if not operation.skipped:
    > 251|                         self._io.write_line(

  Stack trace:

  4  ~/.local/share/pypoetry/venv/lib/python3.9/site-packages/poetry/installation/executor.py:251 in _execute_operation
      249|                 if self._should_write_operation(operation):
      250|                     if not operation.skipped:
    > 251|                         self._io.write_line(

  Stack trace:

  4  ~/.local/share/pypoetry/venv/lib/python3.9/site-packages/poetry/installation/executor.py:251 in _execute_operation
      249|                 if self._should_write_operation(operation):
      250|                     if not operation.skipped:
    > 251|                         self._io.write_line(

  Stack trace:

  4  ~/.local/share/pypoetry/venv/lib/python3.9/site-packages/poetry/installation/executor.py:251 in _execute_operation
      249|                 if self._should_write_operation(operation):
      250|                     if not operation.skipped:
    > 251|                         self._io.write_line(

  Stack trace:

  4  ~/.local/share/pypoetry/venv/lib/python3.9/site-packages/poetry/installation/executor.py:251 in _execute_operation
      249|                 if self._should_write_operation(operation):
      250|                     if not operation.skipped:
    > 251|                         self._io.write_line(

  Stack trace:

  4  ~/.local/share/pypoetry/venv/lib/python3.9/site-packages/poetry/installation/executor.py:251 in _execute_operation
      249|                 if self._should_write_operation(operation):
      250|                     if not operation.skipped:
    > 251|                         self._io.write_line(
```

sorry for the delay, was not in the office for some days.

**Comment by yukw777** [comment] 2023-01-10 05:59
Happens to me when running poetry as a pre-commit local repo.

**Comment by dhart09** [comment] 2023-01-10 17:39
--no-ansi to the rescue, worked for us

**Comment by KhaledMohamedP** [comment] 2023-01-14 01:35
`--no-ansi` worked for me too. 

I'm testing a github action workflow and the poetry installation failed when this flag is not passed in. Surprisingly, it worked fine in github CI, but failed when testing this workflow locally using  [act](https://github.com/nektos/act). 

After hours of debugging `poetry install --no-ansi` ✅

**Comment by bnorick** [comment] 2023-02-08 08:24
FWIW, I ran into this issue when using `ray` which runs some setup commands. The resulting command looked like the following:
```sh
ssh -tt -i ~/ray_bootstrap_key.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ExitOnForwardFailure=yes -o ServerAliveInterval=5 -o ServerAliveCountMax=3 -o ControlMaster=auto -o ControlPath=/tmp/ray_ssh_X/Y/%C -o ControlPersist=10s -o ConnectTimeout=120s ubuntu@WORKER_IP 'bash --login -c -i '"'"'true && source ~/.bashrc && export OMP_NUM_THREADS=1 PYTHONWARNINGS=ignore && (export RAY_HEAD_IP=HEAD_IP; cd /tmp/library; POETRY_VIRTUALENVS_CREATE=0 /home/ubuntu/.local/bin/poetry install)'"'"
```

When executed by `ray`, it would fail. If I executed the same thing from a shell on the head node it would be successful.

`--no-ansi` resolved the issue.

**Comment by okasen** [comment] 2023-02-28 11:21
We've been experiencing this issue with poetry install and poetry update (and self update) on circleci. I just tested out a self update to use Poetry version 1.4, and it seems the issue still exists. (The release notes didn't indicate otherwise, but in case that confirmation is helpful)

**Comment by wlonkly** [comment] 2023-03-14 14:20
As a data point and for searchability, I encountered this with Poetry 1.4, but on Buildkite and not CircleCI. Same terminal issue there though:

```
[2023-03-14T14:18:32Z] poetry install --quiet' in python:3.8
[...]
[2023-03-14T14:18:52Z] os.terminal_size(columns=0, lines=0)
```

**Comment by TheKevJames** [comment] 2023-03-14 17:58
For current status, we've got a proposed fix [here from me](https://github.com/python-poetry/cleo/pull/298) that won't get accepted as per @neersighted 's comment and a better fix [here](https://github.com/python-poetry/cleo/pull/299) from the cleo maintainer @Secrus , that unfortunately doesn't yet solve the problem. As I understand, we're waiting on @Secrus to fix and then merge&release that PR.

Until then, all versions of Poetry v1.3+ on CircleCI and Buildkite (maybe others?) are broken for any commands not using the `--no-ansi` flag.

**Comment by Plozano94** [comment] 2023-05-19 08:03
Airflow with DockerOperator ando option 'tty=True' seems to fail also for the same reason

**Comment by navaati** [comment] 2023-05-19 19:20
Hello. This affects us within `docker build` for Docker versions 18.09.4 and 20.10.14 at least, which are pretty old versions but it could still affect a lot of people.

**Comment by TheKevJames** [comment] 2023-05-24 18:06
I think the current solution is to just make sure you always use `--no-ansi` everywhere you run poetry commands at this point, if those commands might be run in any of the several listed places folks have found 0/0 TTYs occur. So far, no working fix has been accepted for this issue, as far as I am aware.

**Closed** 2023-06-16 11:15 UTC
Labels: area/installer, status/external-issue, status/confirmed, version/1.3.1

**Comment by iainelder** [comment] 2023-06-21 08:16
@Secrus , you closed this as completed, but I'm still seeing the problem today.

`poetry install` fails with exit code 1 in [act](https://github.com/nektos/act) without the `--no-ansi` option set.

Versions:

* Poetry (version 1.5.1)
* act version 0.2.46

When can we expect to see this work without `--no-ansi`?

**Comment by eloquence** [comment] 2023-09-27 17:32
For anyone running into this bug in CircleCI, the issue appears to be in CircleCI itself (see comments here: https://github.com/python-poetry/cleo/pull/299#issuecomment-1349766335). I'm interpreting this to mean that we'll need to use `--no-ansi` in CircleCI, possibly indefinitely.
