### ISSUE TITLE
Unknown argument -, when spawning shell in a folder path where a ' - ' is present

### ISSUE THREAD

**Issue by MattiooFR** [python-poetry/poetry#7487] opened 2023-02-08 10:34 UTC
- **Poetry version**: 1.3.2
- **Python version**: 3.11.1
- **OS version and name**: macOS Ventura 13.2
- **pyproject.toml**: https://gist.github.com/MattiooFR/e2cfad3eb6879ce3c836717f41fcff20

- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
Using the local venv option, I have issue with the command `poetry shell` if my project folder is located in a path where there is a ' - ' in the path

```
brainsorting.dev on  src is 📦 v0.1.0 via 🐍 v3.11.1 took 2s
❯ poetry shell -vvv
Loading configuration file /Users/mattioo/Library/Preferences/pypoetry/config.toml
Using virtualenv: /Users/mattioo/Documents/2 - Areas/brainsorting.dev/.venv
Spawning shell within /Users/mattioo/Documents/2 - Areas/brainsorting.dev/.venv

brainsorting.dev on  src is 📦 v0.1.0 via 🐍 v3.11.1
❯ emulate bash -c '. '/Users/mattioo/Documents/2 - Areas/brainsorting.dev/.venv/
bin/activate''
emulate: unknown argument -
```

**Comment by dimbleby** [comment] 2023-02-08 11:21
looks like you've simply failed to quote the path?

**Comment by neersighted** [comment] 2023-02-08 18:45
`poetry shell` is failing to quote the path -- this is a duplicate of the current quoting issue, though I can't find it right now :laughing:

**Comment by dimbleby** [comment] 2023-02-08 18:46
I dont think it is - anyway the command that @MattiooFR pasted above is making a mess of the quoting.

(They seem to be trying to put a single-quoted path inside an already single-quoted string)

**Comment by neersighted** [comment] 2023-02-08 18:48
They didn't type that -- `poetry shell` did using `pexpect`.

**Comment by dimbleby** [comment] 2023-02-08 18:51
ack - in which case I agree that it's a bug, but I don't know the duplicate.  (In particular it's not the same as the one with all the `subprocess` calls, per #7471)

**Comment by neersighted** [comment] 2023-02-08 18:56
Duplicate #7244.

**Closed by neersighted** 2023-02-08 18:56 UTC
Labels: kind/bug, status/triage
