### ISSUE TITLE
Trouble upgrading from 3.7 to 3.8 in project

### ISSUE THREAD

**Issue by joshhejka** [python-poetry/poetry#2439] opened 2020-05-19 01:29 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 10.15.13
- **Poetry version**: Poetry 1.0.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/joshhejka/a20d4869865d80c1263f3c1ad0b5d27e

## Issue

My project was using Python 3.7 and I wanted to upgrade to Python 3.8. Using pyenv, I installed Python 3.8.2. I used `poetry env use 3.8` to create a new virtualenv called `pytchout-s_IzAqG2-py3.8`. However, `poetry env info` shows this:

```
Virtualenv
Python:         3.7.5
Implementation: CPython
Path:           /Users/joshhejka/Library/Caches/pypoetry/virtualenvs/pytchout-s_IzAqG2-py3.8
Valid:          True

System
Platform: darwin
OS:       posix
Python:   /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7
```

Even though the virtual environment was created with the path to Python 3.8, the version of Python inside the virtual environment is 3.7.5. Any tips on how to fix this? I have a feeling it might be a path issue, but I'm not sure. My path is:

```
/Users/joshhejka/.pyenv/shims:/Library/Frameworks/Python.framework/Versions/3.7/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/go/bin:/opt/X11/bin
```

so it doesn't look like Python 3.8 is on the path, but I thought pyenv takes care of that automatically.

**Comment by azdkj532** [comment] 2020-05-20 13:17
Did you set pyenv to 3.8 before using poetry ? `poetry env use` command also accepts a path pointing to python binary, for example `poetry env use ~/.pyenv/versions/3.8.1/bin/python`

**Comment by Secrus** [comment] 2022-05-16 21:41
The suggested solution should work. Closing, as the issue is not active anymore.

**Closed by Secrus** 2022-05-16 21:41 UTC
Labels: Bug, Triage
