### ISSUE TITLE
Installing poetry when a PyPi mirror is required fails

### ISSUE THREAD

**Issue by BenGale93** [python-poetry/poetry#4738] opened 2021-11-12 12:22 UTC
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

- **OS version and name**: WSL Ubuntu 20.04
- **Poetry version**: Master
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: N/A

## Issue

The latest version of install-poetry.py contains the following on 339-340

```python
def pip(self, *args, **kwargs) -> subprocess.CompletedProcess:
        return self.python("-m", "pip", "--isolated", *args, **kwargs)
```

Unfortunately the use of `--isolated` here results in those of us using a PyPi mirror getting hash errors like below.

Requirement already satisfied: pip in ~/.local/share/pypoetry/venv/lib/python3.9/site-packages (21.2.3)
Collecting pip
  Downloading pip-21.3.1-py3-none-any.whl (2.9 kB)
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    pip from https://files.pythonhosted.org/packages/a4/6d/6463d49a933f547439d6b5b98b46af8742cc03ae83543e4d7688c2420f8b/pip-21.3.1-py3-none-any.whl#sha256=deaf32dcd9ab821e359cd8330786bcd077604b5c5730c0b096eda46f95c24a2d:
        Expected sha256 deaf32dcd9ab821e359cd8330786bcd077604b5c5730c0b096eda46f95c24a2d
             Got        b53f57d75e73ed8af52fecb65ea6d47a317ab5d61c16dc32d945896adb5c5d4e

Removing the "--isolated" argument allows poetry to install packages from the mirror defined in pip.conf. Using the below command also works.

```bash
curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/07245670e9c3f5e9e27387609da3433de63028dc/install-poetry.py | python -
```

**Comment by neersighted** [comment] 2021-11-12 13:49
I think more instructions for reproduction are needed -- as best I can tell, you are able to install with a mirror configured just fine. What I suspect is happening is that you are unable to access PyPI on your local network without the mirror -- and so when `install-poetry.py` ignores the mirror because of the `--isolated` option, we see the hash failures.

More details would be great -- this is kind of an interesting edge case where the theoretical consistency benefits of `--isolated` might be biting us in another way.

**Comment by BenGale93** [comment] 2021-11-12 14:36
Hi @neersighted,

Unfortunately I'm not sure reproduction will be the easiest thing to do. I'm behind a corporate firewall which blocks access to PyPi, hence the PyPi mirror.

I ran the following command after installing Python 3.9.7 using pyenv:

```bash
curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -
```

The ouput is (removing personal path details):

```
Retrieving Poetry metadata

# Welcome to Poetry!

This will download and install the latest version of Poetry,
a dependency and package manager for Python.

It will add the `poetry` command to Poetry's bin directory, located at:

~/.local/bin

You can uninstall at any time by executing this script with the --uninstall option,
and these changes will be reverted.

Installing Poetry (1.1.11): An error occurred. Removing partial environment.
Poetry installation failed.
See ~/poetry-installer-error-s3ukees2.log for error logs.
```
And the log contains the error mentioned in my original post.

Let me know what other kinds of details you need.

**Comment by neersighted** [comment] 2021-11-12 14:47
Yeah, that's pretty much what I expected. I'm going to tag @abn in since he drove the addition of `--isolated`. The two possible solutions I see are removing it (I lean this way, thought it means allowing a broken PyPI config to affect the script), or adding a bailout e.g. `POETRY_PYPI_MIRROR` to allow configuring the script.

In the meantime, the `--git` and `--path` arguments give you two options to use a non-PyPI source. All the installer does is set up a venv with Poetry -- so you're also able to do that on your own if preferred as well.

**Comment by bmarroquin** [comment] 2022-01-31 00:10
@neersighted There is also a cert issues to consider. Would adding pass-through `--index-url` and `--cert` options be an acceptable way of handling this? I can work on this.

**Comment by Felix-neko** [comment] 2022-01-31 21:40
Really useful stuff. Will it be merged?

**Comment by neersighted** [comment] 2022-05-04 01:50
There's no code written for any of the discussed approaches yet -- honestly, since most implementations are trivial I'd suggest just creating a PR and discussing specific merits when we have code in front of us.

**Comment by dimbleby** [comment] 2022-07-02 13:27
duplicated by #5219, fixed at https://github.com/python-poetry/install.python-poetry.org/pull/17, this can be closed

**Closed** 2022-07-02 15:50 UTC
Labels: Bug, Installer
