### ISSUE TITLE
Add possibility to install dependencies to target directory. pip -t flag analogue

### ISSUE THREAD

**Issue by mvoitko** [python-poetry/poetry#1937] opened 2020-01-23 14:55 UTC
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request
Add possibility to install dependencies to target directory. pip -t flag analogue.

The proposed command example is

`poetry install -t ./vendor`

**Comment by finswimmer** [comment] 2020-01-24 05:00
Hey @mvoitko ,

could you please add a use case, where you think this feature would be useful?

fin swimmer

**Comment by RobbieClarken** [comment] 2020-04-11 11:27
> could you please add a use case, where you think this feature would be useful?

I'm interested in this feature to be able to download and build python packages as part of deploying to AWS Lambda. In order to deploy to Lambda you need to zip up your source code and dependencies and upload them to an S3 bucket. My build currently involves doing:

```bash
poetry export -f requirements.txt --without-hashes > requirements.txt
pip install -r requirements.txt -t ./bundle/
```

The `--without-hashes` is needed or I get an error when I `pip install`:

```
ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    setuptools>=39.2.0 from https://files.pythonhosted.org/packages/a0/df/635cdb901ee4a8a42ec68e480c49f85f4c59e8816effbf57d9e6ee8b3588/setuptools-46.1.3-py3-none-any.whl#sha256=4fe404eec2738c20ab5841fa2d791902d2a645f32318a7850ef26f8d7215a8ee (from cairocffi==1.1.0->-r requirements.txt (line 1))
```

It would be nice to be able to run something like:

```bash
poetry install -t ./bundle/
```

This would have the advantage of verifying hashes, simplifying the build and removing the direct dependency on `pip`.

**Comment by autoferrit** [comment] 2020-04-22 08:37
This could also help with caching dependencies in building containers as well I think. #1382

**Comment by beanaroo** [comment] 2020-07-11 05:37
We would also like to bundle an application for:

- AWS Lambda
- Docker Containers

It looks like there is an open Pull Request for this feature here: https://github.com/python-poetry/poetry/pull/799

**Comment by KentonParton** [comment] 2020-09-25 21:15
Similarly to @beanaroo, I too would like to be able to install packages to a specific directory for AWS Lambda deployments and Docker Containers. It would be awesome to have this added to Poetry.

**Comment by beanaroo** [comment] 2020-10-06 11:35
It appears the latest relevant PR is https://github.com/python-poetry/poetry/pull/2682

**Comment by Kaisbn** [comment] 2021-02-10 22:35
Any update on this issue?

The PR doesn't seem to be moving. As mentioned above, it would be nice to have this feature especially for Lambda deployments.

**Comment by invidian** [comment] 2021-03-07 10:41
It also seems some packages in Arch Linux like https://archlinux.org/packages/community/any/yubikey-manager/ started using `poetry` as build tool, which makes it difficult to upgrade with lack of ability to install project files into the target directory while building package.

**Comment by StampixSMO** [comment] 2021-03-22 11:18
Any update on the draft PR?

**Comment by RoelantStegmann** [comment] 2021-04-19 09:04
Any updates on this?

**Comment by nhuray** [comment] 2021-05-03 14:19
Clearly something helpful for bundling Lambda and containers. Any news ?

**Comment by ehiggs** [comment] 2021-05-04 13:30
A lot of people are explaining it's useful for bundling lambda and containers but it's possible poetry devs aren't familiar with why exactly that is.

Regarding containers, Docker has a concept of [a multi-stage build](https://docs.docker.com/develop/develop-images/multistage-build/). In a multistage build you can have a builder image and a live image in the same file. The builder image has compilers for cython and so on installed. The live one has none of these build dependencies installed and only has the resulting binaries.

So the motivating example for poetry is to install all the dependencies to a specific directory and then, copy the files from the build image into the live image. Without this feature, we need to do surgery on `/usr/local/lib` or we need to use a `venv`. A `venv` in a container is like a hat on a hat.

Thanks!

**Comment by tsz662** [comment] 2021-05-07 00:17
Any update on this? The below may be the simplest way to bundle an application with all dependencies into an AWS Lambda package but if poetry natively support an equivalent feature, that would be great.
```shell
$ poetry build --format wheel
$ pip install ./dist/foobar.whl -t ldist
$ cd ldist && zip lambda * -r
```

**Comment by AntoninGrele** [comment] 2021-06-06 21:07
I'd like to bring another user case. I have setup a git hook on post-merge to trigger a django server restart when code is merged to the repository's master branch. In the git hook, Things like django collectstatic and django migrate are run, so that new static files are collected, and new migrations are applied.

It would be useful to also be able to also automatically install new packages, and this requires targeting a different directory than the one the post-merge hook is on. I'd need to be able to install the new packages from `/home/username/...`.

**Comment by yogevyuval** [comment] 2021-07-01 08:57
Does anyone know what is the current status of this? It's the last item preventing many people from migrating to poetry

**Comment by Iain-S** [comment] 2021-09-28 10:48
This would also be useful for deployment as an Azure Function app.

**Comment by clintonroy** [comment] 2021-09-28 12:18
I'm not familiar with the target environments, but is using pip itself viable?
I can get pip install . -t /tmp/foobar installing everything to /tmp/foobar, in a pyproject.toml based project,
by leaning on the [build-system] stanza.

**Comment by sprckt** [comment] 2021-11-30 09:17
+1 For the Lambda use case

**Comment by Torwalt** [comment] 2021-12-01 15:29
Another solution that worked for me is installing the dependencies directly into the project. This will create a `.venv` folder which can be used to create a zip file.

```bash
 poetry config virtualenvs.create true
 poetry config virtualenvs.in-project true
 poetry install --no-dev
 # function handler file for AWS lambda
 cp lambda_function.py .venv/lib/python3.9/site-packages/
 cp -r ./YOUR_APPLICATION_ROOT .venv/lib/python3.9/site-packages/
 # set permissions so the aws runtime can execute the files
 find .venv/lib/python3.9/site-packages -type f -print0 | xargs -0 chmod 644
 find .venv/lib/python3.9/site-packages -type f -print0 | xargs -0 chmod 755
 cd .venv/lib/python3.9/site-packages/
 zip -q  -r lambda.zip ./*
```

**Comment by camfulton** [comment] 2022-01-31 17:53
+1

**Comment by Cajuteq** [comment] 2022-07-12 11:16
Hi, having followed this issue and other related (https://github.com/python-poetry/poetry/issues/1174), I've found that related pr (https://github.com/python-poetry/poetry/pull/799 and https://github.com/python-poetry/poetry/pull/2682) have been closed in favor of an official bundle plugin (https://github.com/python-poetry/poetry-plugin-bundle) 
I didn't tested it yet and don't known if it fixes all the problems raised in this issue but perhaps someone like @finswimmer or @sdispater could clarify and maybe close this issue.

**Comment by nitsujri** [comment] 2022-09-02 01:53
@Cajuteq thanks for linking the plugin bundle. Please forgive my lack of knowledge - pretty new to python.

It looks like it's designed to only work with virtual envs? Specifically there's no way to bundle directly into the root python environment? For deployment, I don't want to mess with venvs.

Based on this thread my current deployment is:

```dockerfile
RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -
RUN /root/.local/bin/poetry config virtualenvs.create false

# We copy just the requirements.txt first to leverage Docker cache
COPY poetry.lock pyproject.toml ./

# https://github.com/python-poetry/poetry/issues/1937
RUN /root/.local/bin/poetry export --format requirements.txt --without-hashes --output requirements.txt
RUN pip3 install -r requirements.txt --target "${LAMBDA_TASK_ROOT}"
```

Is using the plugin as simple as `poetry bundle venv ${LAMBDA_TASK_ROOT}` and I don't have to worry about venvs? Are venvs simply folders added to a scoped `$PATH` for easy searching or is there more that allows python to find packages?

**Comment by velovix** [comment] 2022-09-09 22:13
I maintain a plugin that adds Poetry support for a build tool used in the ROS community. It requires that Python dependencies be installed to a specific location. The bundle plugin ended up being a perfect solution to this problem, and I was able to replace my old `poetry export` + `pip install -r requirements.txt` workflow with it. Thanks!

@nitsujri Without getting too into how virtual environments work, you may be able to get away with setting the `PYTHONPATH` environment variable to point to the libraries in the virtual environment. So it would be something like:

```Dockerfile
RUN poetry bundle venv /my_project/my_venv
ENV PYTHONPATH="/my_project/my_venv/lib/python3.x/site-packages:${PYTHONPATH}"
```

That should allow you to use the libraries in the virtual environment without having to enter it. Let me know how it works for you.

**Comment by neersighted** [comment] 2022-10-09 16:41
Closing as out of scope for the main project / covered by the bundle plugin. `bundle` could easily be extended with a `prefix` type that simply installs to a prefix, `pip install -t` style.

**Closed by neersighted** 2022-10-09 16:41 UTC
Labels: kind/feature

**Comment by neersighted** [comment] 2022-11-23 18:40
See https://github.com/python-poetry/poetry-plugin-bundle -- this is out of scope for the core of Poetry, but would make sense as a FR on the plugin.

**Comment by cabney927** [comment] 2022-12-23 05:17
My use case is installing poetry dependencies in a python lambda container.

I agree being able to do `poetry install -t ./vendor` would be nice. I worked around this by installing poetry in my container and exporting the poetry dependencies to a requirements.txt file. Then installing the resulting requirements.txt to the target directory. Hope this helps.

e.g.
```
pip install --upgrade pip
pip install poetry
poetry export --without-hashes --format=requirements.txt > requirements-poetry.txt
pip install -r requirements-poetry.txt --target ./vendor --upgrade
```

**Comment by lunarmint** [comment] 2023-04-08 19:18
Any updates for this? +1 for the AWS lambda use case, would be so so nice to have.

**Comment by pievalentin** [comment] 2023-05-16 20:53
Same thing for Azure Function resulting to exit the poetry ecosystem

**Comment by svdev** [comment] 2023-08-11 18:09
This seems to work fine:

`
poetry config virtualenvs.path "/my-custom-root-path-for-virtual-envs/"
poetry install
source $(poetry env info --path)/bin/activate
python some-script.py
`

**Comment by jason-curtis** [comment] 2023-09-11 23:01
Can we [lock this conversation](https://github.blog/2014-06-09-locking-conversations/)?

The issue is closed as out of scope and there are perfectly good solutions above. The recent comments have all been "+1"s from folks who haven't bothered to read the thread.

For the record, the solutions include:

1. [using the bundle plugin](https://github.com/python-poetry/poetry/issues/1937#issuecomment-1242519454) and prepending to the `PYTHONPATH`
2. [exporting requirements from poetry](https://github.com/python-poetry/poetry/issues/1937#issuecomment-612398471)
3. [building a `.whl` with poetry](https://github.com/python-poetry/poetry/issues/1937#issuecomment-833964760)
4. [using the virtualenvs.project setting](https://github.com/python-poetry/poetry/issues/1937#issuecomment-983754739) to install to a known directory
5. I don't think anyone's mentioned it above, but in some cases you can also use the [`ENTRYPOINT` instruction](https://docs.docker.com/engine/reference/builder/#entrypoint) to run commands with `poetry run`. In one project I have a custom image built on `python:3.10-slim` with the entrypoint instruction: `ENTRYPOINT [ "poetry", "run", "python", "-m", "awslambdaric" ]` to run [AWS Lambda RIC](https://github.com/aws/aws-lambda-python-runtime-interface-client).
