### ISSUE TITLE
Allow to create empty python package

### ISSUE THREAD

**Issue by monim67-renforce** [python-poetry/poetry#6247] opened 2022-08-26 15:16 UTC
There is no way to create empty packages with poetry. If we set `tool.poetry.packages` to an empty array `[]`, pip install raises the following error:

```
      File "path/to/site-packages/poetry/core/masonry/utils/module.py", line 63, in __init__
        raise ModuleOrPackageNotFound(
    poetry.core.masonry.utils.module.ModuleOrPackageNotFound: No file/folder found for package poetry-dockerize
```

I understand this is a valid validation error, but there are cases where we need to install the package and dependencies separately, Dockerfiles. To leverage docker layer cache we generally install dependencies first and then install the project code in another command so that changes in project code does not require installing dependencies again.

Right now a simple workaround is to create a dummy python module (`my_project.py` if `tool.poetry.name = my-project`) to install dependencies.

```Dockerfile
FROM python:3.10-slim-buster

WORKDIR /app

# Install dependencies
COPY poetry.lock pyproject.toml ./
RUN touch my_project.py && pip install . && rm my_project.py

# Copy project code
COPY src src

CMD command1
```

If we could create empty packages like setuptools, then we could just set `tool.poetry.packages = []` instead of tricking poetry-core with a dummy python module.

**Comment by rrobby86** [comment] 2022-08-30 16:09
I'm also trying to install a project with `tool.poetry.packages = []` in development mode using `pip install -e .` resulting in the error described above.

Curiously, the `poetry install` command, from which I would expect the same error, seems to work correctly instead. If it is a validation error, I'd expect it to also appear with `poetry install`.

Still, I would like to be allowed to have an explicitly empty packages list even when installing with `pip`.

**Comment by onerandomusername** [comment] 2022-08-30 16:11
> I'm also trying to install a project with `tool.poetry.packages = []` in development mode using `pip install -e .` resulting in the error described above.
> 
> Curiously, the `poetry install` command, from which I would expect the same error, seems to work correctly instead. If it is a validation error, I'd expect it to also appear with `poetry install`.
> 
> Still, I would like to be allowed to have an explicitly empty packages list even when installing with `pip`.

But what is pip installing in that case? just the dependencies?

This smells a lot like an a-b problem, what is your end goal, what you are reaching to happen in the end?

**Comment by rrobby86** [comment] 2022-08-30 16:20
> But what is pip installing in that case? just the dependencies?

Yes

> This smells a lot like an a-b problem, what is your end goal, what you are reaching to happen in the end?

In my case I'm trying to setup a mono-repo with multiple subprojects and to create a "meta-project" which just includes them all as dependencies together with some useful dev-dependencies. I'm not sure it is the best possible approach, but in general I think there can be other use cases (like the one described by the OP) where declaring a "dependencies-only" package could be useful.

**Comment by HereticSK** [comment] 2022-08-30 17:37
> In my case I'm trying to setup a mono-repo with multiple subprojects and to create a "meta-project" which just includes them all as dependencies together with some useful dev-dependencies. I'm not sure it is the best possible approach, but in general I think there can be other use cases (like the one described by the OP) where declaring a "dependencies-only" package could be useful.


I guess a [namespace package](https://packaging.python.org/en/latest/guides/packaging-namespace-packages/) is suitable for this use case? According to python's official documentation:

> Namespace packages can be useful for a large collection of loosely-related packages (such as a large corpus of client libraries for multiple products from a single company).

**Comment by lieryan** [comment] 2022-09-09 12:19
Currently, my work around for this is to create another docker layer where I have full poetry just so I can do `poetry export` to create a requirements.txt. Not ideal but at least workable, though I wish there's a way to do this with just poetry-core and pip.

**Comment by neersighted** [comment] 2022-10-04 07:30
Mostly a specialized duplicate of #1132 with regard to the immediate ask of not requiring a valid package to use Poetry.

The Docker-specific stuff is better tracked elsewhere as a combination of best-practices patterns and possible features driven by the process of developing those best practices.

**Closed by neersighted** 2022-10-04 07:30 UTC
Labels: kind/feature, status/triage
