### ISSUE TITLE
poetry install throwing ssl error

### ISSUE THREAD

**Issue by SaiAnudeepK** [python-poetry/poetry#2518] opened 2020-06-08 07:37 UTC
This issue i am facing when i am using my project in jenkins

I had install poetry using pip
     pip install poetry

After installing poetry, I had entered the below command
    poetry install

then I get the below error
[SSLError]
HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /pypi/pytest/json (Caused by SSLError(SSLError("bad handshake: SysCallError(10060, 'WSAETIMEDOUT')")))

Below is the content of my pyproject.toml file
[tool.poetry]
name = "pyjama"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.23.0"
logzero = "^1.5.0"
debtcollector = "^2.0.1"
resteasy = "^3.1.1"
coverage = "^5.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

**Comment by SanketDG** [comment] 2020-06-08 13:37
Could you try doing `pip install pytest`? It should fail too, I can see your network not having the correct certificates.

**Comment by SaiAnudeepK** [comment] 2020-06-08 17:49
> Could you try doing `pip install pytest`? It should fail too, I can see your network not having the correct certificates.

Pip install pytest is working for me but when i add pytest as a dependency for poetry then it is failing
Yes it is the issue with certificates but i am not able to find where to provide certificates for poetry when it is trying to access pypi

**Comment by ian-flores** [comment] 2020-06-10 09:47
I'm having the same issue in MacOS as @SaiAnudeepK mentions.

**Comment by juliuskittler** [comment] 2021-06-30 18:21
I also had this issue with poetry 1.1.5. Switching back to poetry 1.1.4 solved it for me.

**Comment by ardila** [comment] 2021-08-12 17:43
I tried both of the fixes above and am still getting the same error

**Comment by mkniewallner** [comment] 2022-05-28 15:16
Does anyone of you still reproduce the issue on version [1.1.13](https://github.com/python-poetry/poetry/releases/tag/1.1.13) and/or [1.2.0b1](https://github.com/python-poetry/poetry/releases/tag/1.2.0b1)?

**Comment by matthewarmand** [comment] 2022-06-24 18:30
I just ran into this on 1.1.13. Here's debug output if it helps: https://pastebin.pl/view/dbaa460d

Running poetry 1.1.13 on python 3.8 inside Docker

**Comment by dimbleby** [comment] 2022-06-25 15:20
@matthewarmand that's not the same thing at all.

**Comment by matthewarmand** [comment] 2022-06-25 15:38
Woops, my mistake, I suppose I should have read the issue a bit more closely, but the `Max retries exceeded` failure to communicate with PyPi made me think it could be related. I was also confused how for me `poetry install` was working fine but `poetry add` was what was failing. (I know that doesn't match this issue either, but hey, reading comprehension :rofl: ).

At any rate mine looks to be a transient issue so apologies again and disregard

**Comment by djjudas21** [comment] 2022-08-02 15:12
Yes, I still see this on 1.1.13

```
[jgazeley@hephaestos artifact-backup]$ poetry install
Creating virtualenv kube-artifact-backup-CMVzlHXo-py3.10 in /home/jgazeley/.cache/pypoetry/virtualenvs
Updating dependencies
Resolving dependencies... (0.0s)

  SSLError

  HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /pypi/gnupg/json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))

  at /usr/lib/python3.10/site-packages/requests/adapters.py:517 in send
      513│                 raise ProxyError(e, request=request)
      514│ 
      515│             if isinstance(e.reason, _SSLError):
      516│                 # This branch is for urllib3 v1.22 and later.
    → 517│                 raise SSLError(e, request=request)
      518│ 
      519│             raise ConnectionError(e, request=request)
      520│ 
      521│         except ClosedPoolError as e
```

```
[jgazeley@hephaestos artifact-backup]$ poetry --version
Poetry version 1.1.13
```

**Comment by dimbleby** [comment] 2022-08-02 15:16
Also not the same thing, per reading the error message.

There are plenty of open duplicates that do talk about certificate verification, this is not one of them.

**Comment by dimbleby** [comment] 2022-10-23 15:52
probably not a poetry bug in the first place, no-one reports reproducing it recently, should likely close this

**Comment by neersighted** [comment] 2022-10-23 16:55
Agreed, there are no details here. This is likely a SSL-inspecting proxy or similar, which we currently have limited support for on a best-effort basis (due to having pip in the stack; once we move to an internal installer this will get a lot easier).

**Closed by neersighted** 2022-10-23 16:55 UTC
Labels: status/waiting-on-response
