### ISSUE TITLE
Dependency from git repo subfolder

### ISSUE THREAD

**Issue by DimaZhu** [python-poetry/poetry#4745] opened 2021-11-13 10:11 UTC
From doc:
I can specify dependency as follows:
requests = { git = "https://github.com/kennethreitz/requests.git", branch = "next" }

But in my repository there are several libraries in different folders, is there any way to install only one library?

- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

**Comment by jaens** [comment] 2021-11-22 12:52
One workaround is to add the repo as a git submodule and use a `lib = { path = "repo/subdir" }` directory dependency.

**Comment by finswimmer** [comment] 2022-01-08 07:46
Hey,

this is currently not possible and a duplicate of https://github.com/python-poetry/poetry/issues/755.

fin swimmer

**Closed by finswimmer** 2022-01-08 07:46 UTC
Labels: Question
