### ISSUE TITLE
Poetry does not install from wheels on macOS Big Sur

### ISSUE THREAD

**Issue by williammck** [python-poetry/poetry#3458] opened 2020-12-06 22:33 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS Big Sur 11.0.1 on Apple Silicon
- **Poetry version**: 1.1.4
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://github.com/crimsobot/crimsoBOT/blob/c00966011f5e829c097f0f1ce77e0b785d0d23ab/pyproject.toml

## Issue

When using Poetry on Big Sur, `poetry.installation.chooser.Chooser` is not recognizing available macOS wheels.
e.g. Poetry uses `cryptography-3.0.tar.gz` instead of `cryptography-3.0-cp27-cp27m-macosx_10_10_x86_64.whl`.

This has been fixed in https://github.com/pypa/packaging/pull/319 (v20.5 and above), however it appears that Poetry is using packaging v20.4.
I've tracked it down to https://github.com/python-poetry/poetry-core vendoring in packaging v20.4, as `poetry.utils.env.VirtualEnv.get_supported_tags` is using `~/.poetry/lib/poetry/_vendor/py3.8/poetry/core/_vendor/packaging/tags.py` as the script source on my machine.

I'm happy to put up a PR for this both here and in poetry-core, I just wasn't sure how to proceed with the vendoring there and how it ties back to here.

If there's any clarification I can provide, let me know :)

**Comment by donaldguy** [comment] 2020-12-07 04:43
For a sketchy workarount in the meantime

```bash
pip=$(which pip)
pushd $PWD
cd "$(dirname $(which poetry))/../lib/poetry/_vendor/"
cd "py$( python -V | grep -o '[23]\.[0-9]\+')"
cd poetry/core/_vendor
sed -i '' 's/packaging==20.4/packaging==20.5/' vendor.txt
$pip install -t $PWD --upgrade -r vendor.txt
unset pip
popd
```

**Comment by williammck** [comment] 2020-12-07 05:44
> For a sketchy workarount in the meantime

Feels weird but works (changed mine to install `packaging==20.7` since that's latest).
Also calling out that `virtualenv` still has wheels for pip 20.2.2 packaged with it, I needed to run `poetry run pip install -U pip` so that pip would install macOS wheels without erroring.

But with those two changes, seems like things are working... so one upstream dependency and then figuring out what all's in Poetry that needs changing.

**Comment by jeremad** [comment] 2020-12-15 15:30
The root bug is: https://github.com/pypa/packaging/pull/319
`packaging` must be updated to fix it!

**Comment by emanueljacob** [comment] 2021-01-02 19:36
I can confirm that the workaround by @donaldguy works well on MacOS 11.0 . I created a PR for that (in fact for packaging 20.8 not just 20.5), the tests have run successfully locally. Seems to be a small PR for me and therefore would be nice to see this reviewed and merged soon :)

**Comment by henryiii** [comment] 2021-01-05 15:05
The old version of packaging also means poetry can't install NumPy on Big Sur (Intel) with the last released version (the build fails since it's not getting a wheel). The lookup of version numbers was broken, I think, it doesn't look up the 11 correctly. For Big Sur Apple Silicon, you'll want https://github.com/pypa/packaging/pull/380 which has just landed and is not yet in a released version of packaging (or pip, obviously), as otherwise it still will not be able to pick up binary wheels.

**Comment by barentsen** [comment] 2021-01-08 01:45
Using poetry 1.1.4 with Python 3.8.6 (intel i386) on MacOS 11.1 (Big Sur), poetry also fails to install numpy for me with the following error:

```
numpy.distutils.system_info.NotFoundError: No lapack/blas resources found. Note: Accelerate is no longer supported.
```

As pointed out above, the problem is that poetry attempts to install packages from source rather than using the appropriate wheel, and the solution is to upgrade the version of `packaging` that is vendored with poetry.

## Solution

Inspired by https://github.com/python-poetry/poetry/issues/3458#issuecomment-739659452 above, the following steps resolve the issue for me by updating the version of packaging that is embedded within poetry.  These steps assume you already have poetry installed in your python environment:

```bash
git clone https://github.com/python-poetry/poetry-core.git
cd poetry-core
sed -i '' 's/packaging = "^20.1"/packaging = "^20.8"/g' vendors/pyproject.toml
python -m pip install vendoring
make vendor/sync
python -m pip install .
```

I'd open a PR for this, but I think I better leave it to a maintainer with a good understanding of these embedded dependencies?

**Comment by sinoroc** [comment] 2021-01-08 08:54
@barentsen As far as I understood, there is already a PR: https://github.com/python-poetry/poetry/pull/3530. If you get the chance, give it a try, leave some feedback, review the code.

**Comment by barentsen** [comment] 2021-01-08 16:57
@sinoroc Excellent point!  I forgot to mention: I evaluated PR #3530 and it did not appear to resolve the issue for me. I posted details here: https://github.com/python-poetry/poetry/pull/3530#issuecomment-756393563.

**Comment by sinoroc** [comment] 2021-01-08 17:22
@barentsen 
> Excellent point! I forgot to mention: I evaluated PR #3530 and it did _not_ appear to resolve the issue for me. I posted details here: [#3530 (comment)](https://github.com/python-poetry/poetry/pull/3530#issuecomment-756393563).

I see. My bad.

**Comment by henryiii** [comment] 2021-01-12 06:03
There should be a new release of packaging somewhat soon, and it will fix a bug that causes correctly named universal2 wheels to not be loaded on Apple Silicon, but it looks like it will also drop Python 2.7, 3.4, and 3.5 support, so it might be something to watch for, as I think Poetry partially supports 2.7 and fully supports 3.5, at least that was my impression. Not that I've tried that :). Going up to 20.8 would at least fix the issue for all macOS 11 users on Intel that can't get things like NumPy wheels with Poetry currently! See https://github.com/pypa/packaging/issues/385 and https://github.com/pypa/packaging/pull/376 .

**Comment by nilnullzip** [comment] 2021-01-23 22:34
Same issue on Intel silicon (16" 2019 MBP). Numpy and others don't download MacOS wheels and the attempted compile fails. My workaround is installing the package at the specified revision with pip and then running Poetry install/update succeeds. Make sure you also update pip if you see a message to that effect. I've had problems (not sure if related) if I don't.

**Comment by henryiii** [comment] 2021-01-23 22:54
It's the same issue if you use pip 20.2 (which tends to be default some places, like the CLT venv), it's due to old versions of packaging. Pip updated the vendored packaging in 20.3, and poetry needs to, too.

**Comment by williammck** [comment] 2021-01-23 22:59
I've fixed this locally for the time being by setting an alias for Poetry...
`alias poetry='env SYSTEM_VERSION_COMPAT=1 poetry'`

Setting `SYSTEM_VERSION_COMPAT=1` instructs macOS to return `10.16` for any system version lookups, which fixes the issues with older versions of https://github.com/pypa/packaging.

**Comment by damienrj** [comment] 2021-01-24 08:56
Nice, I will have to give this a try. I had been exporting to requirements.txt to get things to work for now.

**Closed** 2021-01-29 09:56 UTC
Labels: Bug, Triage

**Comment by damienrj** [comment] 2021-02-14 23:56
This solution worked better than most but fails with xgboost even with the new poetry core. I am sticking with converting to requirements.txt for now it seems.

**Comment by maxmorlocke** [comment] 2022-10-14 18:52
For those still encountering this and finding this lovely thread, I had success getting things installed with a M2 running Monterrey using:

```
brew install mupdf swig freetype
poetry add PyMuPDF
```

Installing mupdf alone didn't cover it all.
