### ISSUE TITLE
Poetry not respecting conditional dependencies

### ISSUE THREAD

**Issue by fferegrino** [python-poetry/poetry#5114] opened 2022-01-27 13:41 UTC
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS Catalina 10.15.7
- **Poetry version**: 1.1.12
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: [Gist](https://gist.github.com/fferegrino/71664686be3413ad7a256178819f2d55)

## Issue

Poetry downloads and installs Windows dependencies for a project, even when running on a Unix based system. For example, the package [docker](https://pypi.org/project/docker/) has a [dependency to pywin32](https://github.com/docker/docker-py/blob/master/setup.py#L19) when `:sys_platform == "win32"` however, Poetry ignores this and installs and locks the `pywin32` dependency.

This issue does not happen when using vanilla pip.

**Comment by clintonroy** [comment] 2022-01-28 02:32
I cannot reproduce this.

docker definitely depends on pywin32, and poetry records this in the poetry.lock file, but it does not install it on my linux system.

**Comment by dimbleby** [comment] 2022-05-15 12:17
looks like a misunderstanding, suggest close this.

**Closed** 2022-05-15 13:08 UTC
Labels: Bug, Triage
