### ISSUE TITLE
poetry commands stuck

### ISSUE THREAD

**Issue by agn-7** [python-poetry/poetry#8951] opened 2024-02-06 15:08 UTC
When I enter `poetry install` or `poetry update` or `poetry lock` it gets stuck:

```bash
$ poetry install

The currently activated Python version 3.10.12 is not supported by the project (^3.11).
Trying to find and use a compatible version. 
Using python3.11 (3.11.7)
Creating virtualenv ai3d-huZEbsel-py3.11 in /home/benyamin/.cache/pypoetry/virtualenvs
Updating dependencies
The authenticity of host 'https (185.38.110.118)' can't be established.
RSA key fingerprint is SHA256:OLu/gLhJqk/sFzryREsEYBZ7K2VN0ltqZK3wNP7q6fY.
This key is not known by any other names
Resolving dependencies... (350.6s)
```

pyproject.toml:

```
[tool.poetry]
name = "ai3d"
version = "0.1.0"
description = ""
authors = ["Benyamin <benyaminjmf@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.11"
pydantic = "^2.5.2"
uvicorn = "^0.24.0.post1"
alembic = "^1.12.1"
sqlalchemy = "1.4.27"
psycopg2-binary = "^2.9.9"
pydantic-settings = "^2.1.0"
pytz = "^2023.3.post1"
asyncpg = "^0.29.0"
gunicorn = "^21.2.0"
fastapi = "^0.109.2"
openai = "^1.6.1"
g4f = "^0.1.9.6"
google-generativeai = "^0.3.2"
python-jose = {extras = ["cryptography"], version = "^3.3.0"}
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
python-multipart = "^0.0.6"
asyncclick = "^8.1.3.4"
sqladmin = {git = "https://github.com/agn-7/sqladmin.git"}

[tool.poetry.group.dev.dependencies]
requests = "^2.31.0"
pytest = "7.4.2"
black = "^23.10.1"
pytest-cov = "^4.1.0"
pytest-asyncio = "^0.21.1"
aiosqlite = "^0.19.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

---
Versions:

 - _Poetry 1.7.1_
 - _Python 3.11_
 - _Ubuntu 22.04_

**Comment by Secrus** [comment] 2024-02-06 15:44
Please follow the issue template

**Comment by dimbleby** [comment] 2024-02-06 17:57
probably duplicate #8623 etc

**Comment by abn** [comment] 2024-02-29 13:39
This looks like an issue with ssh not trusting the host.

```
The authenticity of host 'https (185.38.110.118)' can't be established.
RSA key fingerprint is SHA256:OLu/gLhJqk/sFzryREsEYBZ7K2VN0ltqZK3wNP7q6fY.
This key is not known by any other names
```

Basically the terminal is waiting for you to say "yes". This is an environment issue rather than a poetry issue. Try trusting the host explicitly prior to using poetry install, or add the fingerprint to the known_hosts file if you really trust the host.

Since the provided pyproject cannot reproduce the issue, closing.

**Closed by abn** 2024-02-29 13:39 UTC
Labels: kind/bug, status/triage
