### ISSUE TITLE
Poetry v1.1.0. IndexError: list index out of range

### ISSUE THREAD

**Issue by andreevdanil** [python-poetry/poetry#3043] opened 2020-10-02 07:42 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **Ubuntu 18.04**;
- **Poetry 1.1.0**;

## Issue
Command `poetry export -f requirements.txt -o requirements.txt --without-hashes` ended with error:

```
  Stack trace:

  6  ~/.poetry/lib/poetry/_vendor/py3.8/clikit/console_application.py:131 in run
      129│             parsed_args = resolved_command.args
      130│ 
    → 131│             status_code = command.handle(parsed_args, io)
      132│         except KeyboardInterrupt:
      133│             status_code = 1

  5  ~/.poetry/lib/poetry/_vendor/py3.8/clikit/api/command/command.py:120 in handle
      118│     def handle(self, args, io):  # type: (Args, IO) -> int
      119│         try:
    → 120│             status_code = self._do_handle(args, io)
      121│         except KeyboardInterrupt:
      122│             if io.is_debug():

  4  ~/.poetry/lib/poetry/_vendor/py3.8/clikit/api/command/command.py:171 in _do_handle
      169│         handler_method = self._config.handler_method
      170│ 
    → 171│         return getattr(handler, handler_method)(args, io, self)
      172│ 
      173│     def __repr__(self):  # type: () -> str

  3  ~/.poetry/lib/poetry/_vendor/py3.8/cleo/commands/command.py:92 in wrap_handle
       90│         self._command = command
       91│ 
    →  92│         return self.handle()
       93│ 
       94│     def handle(self):  # type: () -> Optional[int]

  2  ~/.poetry/lib/poetry/console/commands/export.py:66 in handle
      64│ 
      65│         exporter = Exporter(self.poetry)
    → 66│         exporter.export(
      67│             fmt,
      68│             self.poetry.file.parent,

  1  ~/.poetry/lib/poetry/utils/exporter.py:37 in export
       35│             raise ValueError("Invalid export format: {}".format(fmt))
       36│ 
    →  37│         getattr(self, "_export_{}".format(fmt.replace(".", "_")))(
       38│             cwd,
       39│             output,

  IndexError

  list index out of range

  at ~/.poetry/lib/poetry/utils/exporter.py:76 in _export_requirements_txt
       72│             if not dev
       73│             else self._poetry.package.all_requires,
       74│             with_nested=True,
       75│         ):
    →  76│             package = repository.find_packages(dependency=dependency)[0]
       77│ 
       78│             # If a package is optional and we haven't opted in to it, continue
       79│             if package.optional and package.name not in extra_package_names:
       80│                 continue
```

This is my `pyproject.toml`:
```[tool.poetry]
name = "test"
version = "0.1.0"
authors = [
    "Test <test@test.ru>",
]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
aiodns = "^2.0.0"
aiohttp = "^3.6.2"
asyncpg = "^0.21"
attrs = "^20.2"
brotlipy = "^0.7"
cchardet = "^2.1"
environs = "^8.0"
gunicorn = "^20.0.4"
marshmallow = "^3.8"
uvloop = "^0.14"
yarl = "^1.6"
ujson = "^3.2"
alembic = "^1.4"
psycopg2-binary = "^2.8"
sqlalchemy = "^1.3"
docker = { version = "^4.3.0", optional = true }

[tool.poetry.dev-dependencies]
add-trailing-comma = "^2.0"
bandit = "^1.6"
cobertura_clover_transform = "^1.1"
coverage = "^5.3"
flake8 = "^3.8"
isort = "^4.3"
mypy = "^0.782"
pylint = "^2.6"
pytest = "^5.4"
unittest_xml_reporting = "^3.0.4"
yapf = "^0.30"

[tool.poetry.extras]
pytest-plugin = ["docker"]

[build-system]
requires = ["poetry>=1.0.5"]
build-backend = "poetry.masonry.api"
```

I suppose that it is the bug, because on previous version all was OK.

**Comment by abn** [comment] 2020-10-02 08:25
Duplicate of #3018.

**Closed** 2020-10-02 08:26 UTC
Labels: Bug, Duplicate
