### ISSUE TITLE
`poetry env` doesn't work on Windows after install-poetry.py

### ISSUE THREAD

**Issue by tom-bowles** [python-poetry/poetry#4615] opened 2021-10-08 08:09 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10
- **Poetry version**: 1.1.11
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: N/A

## Issue

After installing poetry, creating a fresh project and running `poetry env list` the following error occurs:

    EnvCommandError

    Command python -W ignore - errored with the following return code 1, and output:
    'python' is not recognized as an internal or external command,
    operable program or batch file.
    input was : import sys

    if hasattr(sys, "real_prefix"):
        print(sys.real_prefix)
    elif hasattr(sys, "base_prefix"):
        print(sys.base_prefix)
    else:
        print(sys.prefix)

    at c:\...\poetry\venv\lib\site-packages\poetry\utils\env.py:1183 in _run
        1179│                 output = subprocess.check_output(
        1180│                     cmd, stderr=subprocess.STDOUT, **kwargs
        1181│                 )
        1182│         except CalledProcessError as e:
      → 1183│             raise EnvCommandError(e, input=input_)
        1184│
        1185│         return decode(output)
        1186│
        1187│     def execute(self, bin, *args, **kwargs):

This appears to be due to the following at lines 1233-1236 in https://github.com/python-poetry/poetry/blob/1.1/poetry/utils/env.py:

                if not bin.endswith(".exe"):
                    bin_path = self._bin_dir / (bin + ".exe")
                else:
                    bin_path = self._path / bin

I believe in the first case self._path should be used instead of self._bin_dir.

This problem doesn't appear to happen (the function is never called) when poetry is installed with `get-poetry.py` instead of `install-poetry.py`. I don't know why that is, but it's a good workaround. I think the above code is wrong nonetheless.

**Comment by Luttik** [comment] 2021-10-18 13:57
@tom-bowles great research. Poetry 1.1.8 works for me too, the latest version still seems to be broken.

**Comment by zndr27** [comment] 2021-12-18 23:16
Any timeline on when this will be resolved?

**Comment by clintonroy** [comment] 2021-12-18 23:32
Have you tried installing poetry with pipx at all, does that get around this issue?

**Comment by shelper** [comment] 2022-04-09 02:30
> Have you tried installing poetry with pipx at all, does that get around this issue?

tried and the answer is no...

**Comment by neersighted** [comment] 2022-11-24 10:28
Closing as duplicate of #2117.

**Closed** 2022-11-24 10:28 UTC
Labels: kind/bug, status/triage
