### ISSUE TITLE
poetry update raise HTTPResponse.__init__() got an unexpected keyword argument 'strict'

### ISSUE THREAD

**Issue by jerzyk** [python-poetry/poetry#8029] opened 2023-05-28 20:34 UTC
- **Poetry version**: Poetry (version 1.5.0)
- **Python version**: Python 3.11.3
- **OS version and name**: macOS 13.4

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
poetry update is updating urllib3 library to a version >= 2.0.0, this cause that subsequent calls to poetry update ends with error from the title

workaround: pin urllib3 version directly:
urllib3 = "<2.0"

**Comment by ralbertazzi** [comment] 2023-05-28 20:37
Duplicate of https://github.com/python-poetry/poetry/issues/7936

**Closed** 2023-05-28 20:45 UTC
Labels: kind/bug, status/triage
