### ISSUE TITLE
export fails with "list index out of range"

### ISSUE THREAD

**Issue by moredatarequired** [python-poetry/poetry#3063] opened 2020-10-03 02:14 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 20.04.1 LTS (installed under WSL)
- **Poetry version**: 1.1.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://github.com/project-deepform/deepform/blob/9f8151ba3da99086e6bc98f9959981d6272a64d8/pyproject.toml

## Issue

After upgrading from 1.1.0rc1 to 1.1.0 I'm no longer able to run `poetry export -vvv --dev -f requirements.txt`; I now get an `IndexError` when it tries to run, which is causing our CI pipeline to fail on all runs. The ouput:
```
  Stack trace:

  6  ~/.poetry/lib/poetry/_vendor/py3.8/clikit/console_application.py:131 in run
      129│             parsed_args = resolved_command.args
      130│
    → 131│             status_code = command.handle(parsed_args, io)
      132│         except KeyboardInterrupt:
      133│             status_code = 1

  5  ~/.poetry/lib/poetry/_vendor/py3.8/clikit/api/command/command.py:120 in handle
      118│     def handle(self, args, io):  # type: (Args, IO) -> int
      119│         try:
    → 120│             status_code = self._do_handle(args, io)
      121│         except KeyboardInterrupt:
      122│             if io.is_debug():

  4  ~/.poetry/lib/poetry/_vendor/py3.8/clikit/api/command/command.py:171 in _do_handle
      169│         handler_method = self._config.handler_method
      170│
    → 171│         return getattr(handler, handler_method)(args, io, self)
      172│
      173│     def __repr__(self):  # type: () -> str

  3  ~/.poetry/lib/poetry/_vendor/py3.8/cleo/commands/command.py:92 in wrap_handle
       90│         self._command = command
       91│
    →  92│         return self.handle()
       93│
       94│     def handle(self):  # type: () -> Optional[int]

  2  ~/.poetry/lib/poetry/console/commands/export.py:66 in handle
      64│
      65│         exporter = Exporter(self.poetry)
    → 66│         exporter.export(
      67│             fmt,
      68│             self.poetry.file.parent,

  1  ~/.poetry/lib/poetry/utils/exporter.py:37 in export
       35│             raise ValueError("Invalid export format: {}".format(fmt))
       36│
    →  37│         getattr(self, "_export_{}".format(fmt.replace(".", "_")))(
       38│             cwd,
       39│             output,

  IndexError

  list index out of range

  at ~/.poetry/lib/poetry/utils/exporter.py:76 in _export_requirements_txt
       72│             if not dev
       73│             else self._poetry.package.all_requires,
       74│             with_nested=True,
       75│         ):
    →  76│             package = repository.find_packages(dependency=dependency)[0]
       77│
       78│             # If a package is optional and we haven't opted in to it, continue
       79│             if package.optional and package.name not in extra_package_names:
       80│                 continue
```
It looks like it's failing to find a dependency for one of my packages? I'm happy to work a little more on this, but in the meantime I wanted to raise it.

**Comment by abn** [comment] 2020-10-03 11:05
Duplicate of #3018

**Closed** 2020-10-03 11:05 UTC
Labels: Bug, Duplicate
