### ISSUE TITLE
"poetry install" into a specified directory

### ISSUE THREAD

**Issue by mludvig** [python-poetry/poetry#2003] opened 2020-02-08 05:00 UTC
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

When deploying code to AWS Lambda I often need to include some dependencies - `requests`, `pyyaml`, etc. 

It would be great if I could do `poetry install --dir {somewhere}/` and even better exclude some Lambda-provided dependencies like `--exclude boto3`. 

At the moment we've got a deployment script that builds the package wheel, then filters the unneeded dependencies and then installs it all into a specific directory with `pip install -e {somewhere}`. If `poetry` supported that out of the box that'd be great.

**Comment by beanaroo** [comment] 2020-07-11 05:35
We would also like to bundle an application for:

- AWS Lambda
- Docker Containers

It looks like there is an open Pull Request for this feature here: https://github.com/python-poetry/poetry/pull/799

**Comment by finswimmer** [comment] 2020-07-14 08:21
Duplicate of #1937

**Closed by finswimmer** 2020-07-14 08:21 UTC
Labels: Feature
