### ISSUE TITLE
Manually activated venv managed by poetry has missing packages shared with poetry (vendor/lib/pythonX.Y/site-packages not in path). 

### ISSUE THREAD

**Issue by DylanLukes** [python-poetry/poetry#1929] opened 2020-01-21 23:10 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS Mojave (10.14.6) 
- **Poetry version**: 1.0.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: [pyproject.toml](https://gist.github.com/DylanLukes/cda4d382f14f876dddf8ce1bbb1765ed)

## Issue

I've been running into an odd case where something like this happens:

```zsh
$ poetry shell
$ python
>>> import jsonschema
# ok
```

And yet when I activate my virtualenv manually (as does PyCharm):

```zsh
$ source /Users/dylan/Library/Caches/pypoetry/virtualenvs/se4ds-erEcrwtc-py3.7/bin/activate
$ python
>>> import jsonschema
ModuleNotFoundError: No module named 'jsonschema'
```

`poetry` is not using a _different_ virtual environment, nor is it using a different version of python. However `poetry shell` is _also_ extending `PYTHONPATH` beyond what `virtualenv` does on its own.

Furthermore, `poetry` seems to be installing some dependencies in its own `vendor/lib/<pyversion>/site-packages`, which the virtualenv simply doesn't know about.

```zsh
$ source /Users/dylan/Library/Caches/pypoetry/virtualenvs/se4ds-erEcrwtc-py3.7/bin/activate
$ python
Python 3.7.6 (default, Dec 30 2019, 19:38:28)
[Clang 11.0.0 (clang-1100.0.33.16)] on darwin
>>> import sys
>>> sys.path
['', 
'/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python37.zip',
'/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7',
'/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload',
'/Users/dylan/Library/Caches/pypoetry/virtualenvs/se4ds-erEcrwtc-py3.7/lib/python3.7/site-packages']
```

versus...

```zsh
$ poetry shell
$ echo $PYTHONPATH 
/usr/local/Cellar/poetry/1.0.2/libexec/lib/python3.7/site-packages:/usr/local/Cellar/poetry/1.0.2/libexec/vendor/lib/python3.7/site-packages
$ python
Python 3.7.6 (default, Dec 30 2019, 19:38:28) 
[Clang 11.0.0 (clang-1100.0.33.16)] on darwin
>>> import sys
>>> sys.path
['', 
'/usr/local/Cellar/poetry/1.0.2/libexec/lib/python3.7/site-packages',
'/usr/local/Cellar/poetry/1.0.2/libexec/vendor/lib/python3.7/site-packages',  # <= ⚠️  
'/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python37.zip',
'/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7',
'/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload', 
'/Users/dylan/Library/Caches/pypoetry/virtualenvs/se4ds-erEcrwtc-py3.7/lib/python3.7/site-packages']
```

Note the `/usr/local/Cellar/poetry/1.0.2/libexec/vendor/lib/python3.7/site-packages`. Inspecting this directory reveals that the "missing" `jsonschema` is installed here.

**Comment by DylanLukes** [comment] 2020-01-21 23:18
My main question is: why is `poetry` installing _some_ dependencies but not all into its own `libexec/vendor/lib/<pyversion>/site-packages` directory, but others (most) into the virtual environment? 

Some packages I've seen end up in that directory (for the above `pyproject.toml`) include `more-itertools`, `six`, `zipp`, `attrs`, `importlib-metadata`, `ptyprocess`, `pyrsistent`, `jsonschema`, `pexpect`, `webencodings`, ...

**These are all dependencies of `poetry` itself.**

So it seems like `poetry` is avoiding installing a second copy of a dependency it already has for itself inside the virtual environment. It feels like at least it should symlink them into the virtual environment's site-packages? As it is, if you share any dependencies with `poetry`, your virtual environment is incomplete when used outside `poetry`.

**Comment by sdispater** [comment] 2020-01-24 08:39
From what I can see your are using an Homebrew version of Poetry. I don't know what the Homrebrew formula does but this is not an official nor recommended way to install Poetry.

You should report this issue to the people in charge of this formula.

Closing since the issue is not with Poetry itself.

**Closed by sdispater** 2020-01-24 08:39 UTC
Labels: Bug, Virtualenvs

**Comment by nils-werner** [comment] 2020-02-13 08:59
I can confirm, removing Poetry from Homebrew and installing it using `get-poetry.py` fixes this issue.

**Comment by CircleOnCircles** [comment] 2020-03-06 08:53
> I can confirm, removing Poetry from Homebrew and installing it using `get-poetry.py` fixes this issue.

https://github.com/Homebrew/homebrew-core/pull/51121 fixed the issue, you can try poetry again
