### ISSUE TITLE
`poetry publish` doesn't publish to set private package repository

### ISSUE THREAD

**Issue by John15321** [python-poetry/poetry#5966] opened 2022-07-07 14:58 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 12.4
- **Poetry version**: `1.1.13`
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**:
```toml
[tool.poetry]
name = "hello_world"
version = "0.3.0"
description = "Prints out Hello World!"
authors = ["myemail@mail.com"]
repository = "https://devpi.xxxcompanyxxx.net/username/username/+simple"

[[tool.poetry.source]]
name = "devpi"
url = "https://devpi.xxxcompanyxxx.net/something/prod/+simple"
default = true

[tool.poetry.dependencies]
python = ">=3.8, <3.11"

[tool.poetry.dev-dependencies]
pytest = "^5.2"



[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

## Issue

When running `poetry publish` Poetry should try to publish the package to the set repository, in this case it would be called `devpi`. But instead it ignores `pyproject.toml` and tries yo upload to PyPi. That is not the case if I specify the repository , login and my password as arguments when calling `poetry publish -r repositoryname -u username -p mypassword`.

```bash
$ poetry publish -vvv

Username: username
Password:
Publishing hello_world (0.3.0) to PyPI
 - Uploading hello_world-0.3.0-py3-none-any.whl 100%

  Stack trace:

  7  ~/.poetry/lib/poetry/_vendor/py3.8/clikit/console_application.py:131 in run
      129│             parsed_args = resolved_command.args
      130│
    → 131│             status_code = command.handle(parsed_args, io)
      132│         except KeyboardInterrupt:
      133│             status_code = 1

  6  ~/.poetry/lib/poetry/_vendor/py3.8/clikit/api/command/command.py:120 in handle
      118│     def handle(self, args, io):  # type: (Args, IO) -> int
      119│         try:
    → 120│             status_code = self._do_handle(args, io)
      121│         except KeyboardInterrupt:
      122│             if io.is_debug():

  5  ~/.poetry/lib/poetry/_vendor/py3.8/clikit/api/command/command.py:171 in _do_handle
      169│         handler_method = self._config.handler_method
      170│
    → 171│         return getattr(handler, handler_method)(args, io, self)
      172│
      173│     def __repr__(self):  # type: () -> str

  4  ~/.poetry/lib/poetry/_vendor/py3.8/cleo/commands/command.py:92 in wrap_handle
       90│         self._command = command
       91│
    →  92│         return self.handle()
       93│
       94│     def handle(self):  # type: () -> Optional[int]

  3  ~/.poetry/lib/poetry/console/commands/publish.py:77 in handle
      75│         )
      76│
    → 77│         publisher.publish(
      78│             self.option("repository"),
      79│             self.option("username"),

  2  ~/.poetry/lib/poetry/publishing/publisher.py:93 in publish
      91│         )
      92│
    → 93│         self._uploader.upload(
      94│             url,
      95│             cert=cert or get_cert(self._poetry.config, repository_name),

  1  ~/.poetry/lib/poetry/publishing/uploader.py:119 in upload
      117│
      118│         try:
    → 119│             self._upload(session, url, dry_run)
      120│         finally:
      121│             session.close()

  UploadError

  HTTP Error 403: Invalid or non-existent authentication information. See https://pypi.org/help/#invalid-auth for more information.

  at ~/.poetry/lib/poetry/publishing/uploader.py:216 in _upload
      212│                     self._register(session, url)
      213│                 except HTTPError as e:
      214│                     raise UploadError(e)
      215│
    → 216│             raise UploadError(e)
      217│
      218│     def _do_upload(
      219│         self, session, url, dry_run=False
      220│     ):  # type: (requests.Session, str, Optional[bool]) -> None
```

If I use the version of the command with login, password and repository as arguments it works and the package gets correctly uploaded.

**Comment by John15321** [comment] 2022-07-09 13:01
@Secrus so if Im reading it right, the only way to configure it is to run commands such as this:

```bash
poetry config repositories.foo-pub https://pypi.example.org/legacy/
poetry config http-basic.foo-pub <username> <password>
```
?

Does that mean there is no way to select a target repository using `pyproject.toml`?

**Comment by John15321** [comment] 2022-07-20 11:02
> Sorry, it took so long to get back to you. There is no way to add the target repository to `pyproject.toml`. However, as target repositories are configured by the `config` command, you could theoretically use the `--local` switch and make the target in `poetry.toml` file.

Great, that's what I need thanks! But I don't see it mentioned in the docs anywhere?
Could you just confirm that I am not missing something?
https://python-poetry.org/docs/master/repositories/

**Comment by Secrus** [comment] 2022-07-20 11:09
> > Sorry, it took so long to get back to you. There is no way to add the target repository to `pyproject.toml`. However, as target repositories are configured by the `config` command, you could theoretically use the `--local` switch and make the target in `poetry.toml` file.
> 
> Great, that's what I need thanks! But I don't see it mentioned in the docs anywhere? Could you just confirm that I am not missing something? https://python-poetry.org/docs/master/repositories/

Here: https://python-poetry.org/docs/master/configuration/#local-configuration
https://python-poetry.org/docs/master/cli/#config

**Comment by John15321** [comment] 2022-07-20 11:15
> > > Sorry, it took so long to get back to you. There is no way to add the target repository to `pyproject.toml`. However, as target repositories are configured by the `config` command, you could theoretically use the `--local` switch and make the target in `poetry.toml` file.
> > 
> > 
> > Great, that's what I need thanks! But I don't see it mentioned in the docs anywhere? Could you just confirm that I am not missing something? https://python-poetry.org/docs/master/repositories/
> 
> Here: https://python-poetry.org/docs/master/configuration/#local-configuration https://python-poetry.org/docs/master/cli/#config

Hm okay tho Im not gonna I think it would be nice to mention that you can do it just locally when it comes to config file creation using the `--local` flag

**Comment by Fabhi** [comment] 2022-09-19 15:29
Does it work? It is still using PyPI and not the set repository 😐

**Comment by John15321** [comment] 2022-09-19 15:35
> Does it work? It is still using PyPI and not the set repository 😐

What I have is:

```toml
[repositories]
[repositories.repo-name]
url = "https://devpi.dolby.net/registry-index/prod/+simple"
```

But as of now I'm using devpi-client to upload stuff, its kind of not working I think. Try to use it in your project. And if that does not work I will investigate further

**Comment by neersighted** [comment] 2022-09-19 17:21
When publishing, the default repository is always PyPI. If you want to use a different publishing target, you must use `poetry publish -r repo-name`, where `repo-name` is the name you gave the target during `poetry config`.

**Comment by neersighted** [comment] 2022-09-19 17:22
I'm going to close this for now as the original reporter seems to have things working (and it was a support question, not a bug).

**Closed by neersighted** 2022-09-19 17:22 UTC
Labels: area/publishing, kind/question
