### ISSUE TITLE
Poetry 1.4.0 uninstalls charset-normalizer when resuming install on Windows

### ISSUE THREAD

**Issue by l0b0** [python-poetry/poetry#7589] opened 2023-03-02 00:50 UTC
- **Poetry version**: 1.4.0 _only_
- **Python version**: 3.8, 3.9, 3.10 and 3.11
- **OS version and name**: Microsoft Windows Server 2022 10.0.20348 Datacenter (`windows-2022` GitHub runner)
- **pyproject.toml**: [Gist](https://gist.github.com/l0b0/5e94af02d56838bcf7fa19ec16963195)

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below. See [gist](https://gist.github.com/l0b0/fdc6b2fb6d36c23e0a86f5b10658e4e0) from [this PR](https://github.com/linz/emergency-management-tools/pull/173).

## Issue

To work around [broken Poetry package installs on Windows](https://github.com/python-poetry/poetry/issues/1031) I've set up a retrying job which uses the latest version of Poetry. Since the release of Poetry 1.4.0 this broke further, since now repeated package install attempts _uninstall_ the charset-normalizer package, which is required by the request package to continue installation.

Proving that this is a Poetry and not a Conda/Windows/other issue is that [reverting to Poetry 1.3.2 fixes the issue](https://github.com/linz/emergency-management-tools/pull/172).

**Comment by dimbleby** [comment] 2023-03-02 07:18
poetry is trying to upgrade charset-normalizer: the process for upgrading a package has always been to remove the old version and then install the new version.  You just happen to be hitting #1031 between those two actions.

This is therefore a duplicate of #1031: it will be fixed if/when that is fixed, and cannot be fixed independently of that

**Comment by l0b0** [comment] 2023-03-02 07:30
@dimbleby I don't think it's *exactly* the same as #1031, because that is intermittent while this is 100% reproducible across tens of builds.

**Comment by dimbleby** [comment] 2023-03-02 08:09
plausible that the new installer disturbs the balance as to what files are open at what time so that the frequency or exact realisation of this changes.  You could experiment iwth disabling the new installer.

Still: your logs pretty clearly show that this _is_ a duplicate, in the way that I described in my previous comment.

**Comment by dimbleby** [comment] 2023-05-20 12:15
should have been closed long ago as a duplicate, a fix for the thing that it is a duplicate of has now been released too.  So this should be closed twice!

**Comment by radoering** [comment] 2023-05-20 12:55
Duplicate: #1031

**Closed by radoering** 2023-05-20 12:55 UTC
Labels: kind/bug, status/duplicate
