### ISSUE TITLE
[Feature request]: Add an option in `poetry install` to ignore `develop = true`

### ISSUE THREAD

**Issue by HHK1** [python-poetry/poetry#3786] opened 2021-03-15 18:47 UTC
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

I'm installing a local dependency by specifying the path, along with `develop = true` to ease local development:

```.toml
[tool.poetry.dependencies]
my_lib = {path = "../../my_lib", develop = true}
````

I build my final service relying on this dependency with Docker, and I would like to have an option when running `poetry install` to ignore `develop = true` and have my dependency installed inside my venv rather than having to manually copy it.

For example:

```bash
poetry install --ignore-develop
```

**Comment by sinoroc** [comment] 2021-03-28 11:06
Consider doing this instead:

```
[tool.poetry.dependencies]
my_lib = {path = "../../my_lib", develop = false}

[tool.poetry.dev-dependencies]
my_lib = {path = "../../my_lib", develop = true}
```

See if that works for your use case.

**Comment by HHK1** [comment] 2021-04-26 15:45
I tested that and it works indeed, thanks 🙏 
When running `poetry install --no-dev` the lib is installed inside the venv and I don't have to do an extra copy to build my final docker image.

Maybe add a section in the documentation to cover this use case ? If you deem it's unnecessary I'll let you close the issue.

**Comment by flupke** [comment] 2021-04-29 08:02
Hello, FYU @sinoroc this trick does not work as expected. With poetry 1.1.6, doing `poetry install --no-dev` with always installs the path dependencies in editable mode, i.e. it creates a `.pth` in the venv's `site-packages` instead of copying the sources there. I will file a new issue for this particular matter.

**Comment by flupke** [comment] 2021-04-29 09:55
Actually thinking about it a bit more, I don't see how this trick could work. Each package has only one entry in `poetry.lock`, `my_lib` cannot be in `develop = true` and `develop = false` at the same time, only one of the definitions will win.

**Comment by sinoroc** [comment] 2021-04-29 19:20
> Hello, FYI @sinoroc this trick does not work as expected. With poetry 1.1.6, doing `poetry install --no-dev` will always install the path dependencies in editable mode, i.e. it creates a `.pth` in the venv's `site-packages` instead of copying the sources there. I will file a new issue for this particular matter.

Yes, I recall reading this limitation already. But I don't recall it being reported in an actual bug ticket yet, so feel free to double check and report it.

In my opinion: path dependencies should only be allowed in development dependencies (never in normal dependencies) to begin with. Maybe that would simplify this whole topic.

> Actually thinking about it a bit more, I don't see how this trick could work. Each package has only one entry in `poetry.lock`, `my_lib` cannot be in `develop = true` and `develop = false` at the same time, only one of the definitions will win.

Not sure I am following your reasoning here.

Anyway I don't think it's officially documented anywhere, so it's just a trick. If it works for you: great.

**Comment by flupke** [comment] 2021-04-29 19:58
What I mean is this `pyproject.toml`
```
[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["Luper Rouch <luper.rouch@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
dep = {path = "../dep", develop = false}

[tool.poetry.dev-dependencies]
dep = {path = "../dep", develop = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```
Gives this `poetry.lock`:
```
[[package]]
name = "dep"
version = "0.1.0"
description = ""
category = "main"
optional = false
python-versions = "^3.7"
develop = true

[package.source]
type = "directory"
url = "../dep"

[metadata]
lock-version = "1.1"
python-versions = "^3.7"
content-hash = "50420fca277bfed35d8ab92a367e278e66c78813e9c71d2375311e5bef2b9af4"

[metadata.files]
dep = []
```
The `develop` flag is baked in the lockfile, you can't have it both `true` and `false`. What happens here is probably the entry in the lockfile being written twice, the second write overwriting the first.

Poetry should actually error out when trying to add the same dependency twice in `dependencies` and `dev-dependencies`.

**Comment by flupke** [comment] 2021-04-29 20:01
Here is example if you want to try yourself, this trick cannot work :)
[poetry-path-deps-issue.tar.gz](https://github.com/python-poetry/poetry/files/6401315/poetry-path-deps-issue.tar.gz)

**Comment by neersighted** [comment] 2022-10-04 08:06
Specialized duplicate of #1168, as it would be the 'Poetry way' to solve this use case.

**Closed by neersighted** 2022-10-04 08:06 UTC
Labels: kind/feature, status/triage
