### ISSUE TITLE
Should pyproject.toml configs always be required to use poetry?

### ISSUE THREAD

**Issue by indigoviolet** [python-poetry/poetry#3443] opened 2020-12-02 21:25 UTC
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duxplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Issue

I encountered a case where I wanted to use poetry just to manage the virtualenv in a project (which uses setup.py for its build/config), and that leaves me with two options:

1. Add a "fake" config in `[tools.poetry]` that isn't synced with `setup.py`

2. Use a tool other than poetry to manage the virtualenv.

Wouldn't it be better to only require the config for situations that actually need the config keys?

**Comment by finswimmer** [comment] 2020-12-13 13:07
Hello @indigoviolet,

could you please describe your use case a bit more in details? It's unclear to me for what you want to use poetry.

fin swimmer

**Comment by indigoviolet** [comment] 2020-12-14 00:32
@finswimmer : Let's say I want to do a bugfix on an open source project that doesn't currently use poetry to represent their dependencies. An example is https://github.com/python-attrs/attrs/. I still do want a virtualenv while doing this. 

Normally I use poetry for my own projects, so I'm familiar with its commands, but now I have to either figure out how to use some other tool to create a venv, or I have to add a "fake" `pypoetry.toml` with the minimal config that poetry demands to run any commands. 

My suggestion was that poetry shouldn't require pypoetry.toml at all to run `env` related commands - why should poetry require a `name`, `description`, `version` and `authors` until it is actually going to use them?

**Comment by finswimmer** [comment] 2020-12-14 07:34
Hello @indigoviolet,


this sounds similar to this feature request: https://github.com/python-poetry/poetry/issues/1132

fin swimmer

**Comment by finswimmer** [comment] 2021-08-03 13:10
Duplicate of #1132

**Closed by finswimmer** 2021-08-03 13:10 UTC
