### ISSUE TITLE
Failing to upload to Bitbucket + JFrog

### ISSUE THREAD

**Issue by markussc** [python-poetry/poetry#1835] opened 2020-01-06 13:50 UTC
Poetry: v1.0.0
Python: 2.7.14
OS: Windows 10

When trying to upload to either Bitbucket or JFrog, I always get HTTP errors (501). Authentication seems to work correctly as I am prompted for username/password. When entering wrong credentials, there is error 401 instead (which makes sense).

The URL for Bitbucket looks like this: https://mycompany.com/scm/myproject/myrepo/
The URL for JFrog looks like this: https://mycompany.com/artifactory/myproject/

Please note that we are using Atlassian Server (not Cloud!).

Any advice how to debug this further?

**Comment by ronyrun** [comment] 2020-01-14 09:26
Hello, what is the issue you encounter ?
On my side I got a specific folder on Bitbucket, that I can't use properly.
![image](https://user-images.githubusercontent.com/7273443/72331350-5a97c680-36b8-11ea-8a4c-66d86cff1dc9.png)


Best regards,

**Comment by markussc** [comment] 2020-03-06 11:04
I found out that the error message from Bitbucket is as follows:
`Invalid request from host x.y.z.q: Note that Bitbucket does not support Git's legacy HTTP transport protocol.`

Is there a way to tell poetry to not use the legacy (dumb) but the smart Git protocol?

**Comment by abn** [comment] 2022-05-09 23:36
That error message seems to be related to git pushes/pulls. Publishing to bitbucket/jfrog repos should work. Can you try `poetry@master`?

**Comment by neersighted** [comment] 2022-10-05 16:51
Closing for now as there are no reproduction steps and the issue appears to be user confusion.

**Closed by neersighted** 2022-10-05 16:51 UTC
