### ISSUE TITLE
Poetry 1.1.6 does not resolve dependencies for "nested"package in develop mode

### ISSUE THREAD

**Issue by pdeszynski** [python-poetry/poetry#3956] opened 2021-04-16 11:05 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Docker python:3.9.2
- **Poetry version**: 1.1.5/1.1.6
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: A repo to reproduce this bug: https://github.com/pdeszynski/poetry-fail-example

## Issue
In case you have such dependencies: `proj1 -> proj2 -> proj3` marked as develop, newest poetry (1.1.6) will not install proj3 dependencies whether previous release will handle that case. This occurs ONLY if `poetry.lock` is present.

To reproduce:

```
git clone https://github.com/pdeszynski/poetry-fail-example
cd poetry-fail-example
docker build -f Dockerfile-1.1.5 -t poetry-1.1.5 .
docker build -f Dockerfile-1.1.6 -t poetry-1.1.6 .

docker run --rm -it poetry-1.1.5 python proj1/proj1/__init__.py  # <- this will succeed
docker run --rm -it poetry-1.1.6 python proj1/proj1/__init__.py # <- this will fail with pydash missing error

```

**Comment by marns93** [comment] 2021-04-28 11:51
Poetry is very nice tool to manage python dependencies!

Unfortunately the problem prevent us to upgrade to the new version 1.1.6.
We would like to upgrade, but the only solution, until this bug is fixed is to bump all our `poetry.lock` files at this moment.
This is not suitable, because we have lots of repositories.

I can reproduce problems with nested dependency resolution as well.

With the following steps you can reproduce the problem with nested git dependencies without develop mode.

```shell
# checkout repository
git clone https://github.com/marns93/test-poetry-nested-deps-1.git
# ensure old poetry version is installed
poetry self update 1.1.5
# install dependencies with old poetry version
poetry install
# update poetry
poetry self update 1.1.6
# try to install dependencies as well
poetry install
```
Now you can see that all dependencies of the nested git dependency (test-poetry-nested-deps-3) will be removed.

```shell
# rollback to old version
poetry self update 1.1.5
# try to install dependencies again
poetry install
```
The nested git dependencies will be installed.

If there is no `poetry.lock` I can't reproduce the problem. Only if a `poetry.lock` exists created with poetry 1.1.5.

@abn Could you please have a look?

Thanks!

**Comment by sdispater** [comment] 2021-06-23 10:25
The root cause has been identified (see #4202) and this will be fixed in the next bugfix release.

Note that you will to regenerate the lock file for the fix to take effect.

**Closed** 2021-06-23 16:14 UTC
Labels: Bug, Triage
