### ISSUE TITLE
Poetry can not build Universal2 or arm64 wheels for macos

### ISSUE THREAD

**Issue by Lunarmagpie** [python-poetry/poetry#7107] opened 2022-11-27 21:15 UTC
- **Poetry version**: Locked to `>=1.0.0` for CI
- **Python version**:  3.9 to 3.11
- **OS version and name**: macos12 (aka macos-lastest in GitHub Actions)
- **pyproject.toml**: https://github.com/Lunarmagpie/pycooldown/blob/482e5d06475c728fd1f0332b6952586dcc15a920/pyproject.toml

- [x ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

When experimenting with mypyc/cibuildwheel I found that poetry can not build wheels for macos arm64 or universal2. I have used setuptools with similar configuration and wheels have built correctly.

I have opened this issue with cibuildwheel (more detailed information is here. Repo locked to commit with error & logs) https://github.com/pypa/cibuildwheel/issues/1349
I think this is a problem with poetry though and not cibuildwheel.

**Comment by joerick** [comment] 2022-12-02 09:58
For context, cibuildwheel sets _PYTHON_HOST_PLATFORM and ARCHFLAGS for cross-compilation e.g. `_PYTHON_HOST_PLATFORM=macosx-10.9-universal2` and `ARCHFLAGS=-arch arm64 -arch x86_64`

https://github.com/pypa/cibuildwheel/blob/5c7fc8d7ca3acffd41f7a63a2358f6dc84f4546a/cibuildwheel/macos.py#L220-L232

**Comment by neersighted** [comment] 2022-12-02 15:29
Going to call this a duplicate of #2051, with the added flavor that there are evidently standard cross compilation environment variables we can use as the knobs to customize the wheel tag.

**Closed by neersighted** 2022-12-02 15:29 UTC
Labels: kind/bug, status/triage
