### ISSUE TITLE
Add a command-line option to use PyPI mirror during resolving dependcies

### ISSUE THREAD

**Issue by mnixry** [python-poetry/poetry#3553] opened 2021-01-08 14:03 UTC
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

In some country such as China, the native PyPI source speed is extremely slow, so most of Chinese users had to choice some mirror of PyPI to alter the default pypi.org settings.
https://github.com/python-poetry/poetry/blob/de0b32c245c72568cf546090600d4626917cd3a4/poetry/repositories/pypi_repository.py#L48-L72
According the code, it's seems possible to change the site domain, but unfortunately this argument is not been used in anywhere.
I hope to add a global option to change the pypi domain instead of [add a hard-coded config](https://python-poetry.org/docs/repositories/#install-dependencies-from-a-private-repository) in `pyprojce.toml` file, because different mirror speed will be different in different region, I don't think directly submitted to the Git repository and forced all users to use a same mirror is a wise choice.

related: #3552 #3261

**Comment by sinoroc** [comment] 2021-01-08 14:34
We should probably close this ticket in favor of https://github.com/python-poetry/poetry/issues/3479 (or maybe there is an other, even more complete ticket).

**Comment by sinoroc** [comment] 2021-05-01 18:20
@mnixry There is a PR that could solve this issue. Would you be able to test it, give feedback? https://github.com/python-poetry/poetry/pull/3624

**Comment by dimbleby** [comment] 2022-10-23 16:50
this probably wants absorbing into #6713

**Comment by neersighted** [comment] 2022-10-23 16:51
This is actually a duplicate of #1632 instead. Thanks for spotting it!

**Closed by neersighted** 2022-10-23 16:51 UTC
Labels: kind/feature, status/triage
