### ISSUE TITLE
Confusing exception on unexpected author

### ISSUE THREAD

**Issue by viraptor** [python-poetry/poetry#1847] opened 2020-01-08 10:03 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**:  fedora 31
- **Poetry version**:  0.12.17

## Issue

When using an author in an unexpected format - like `just@email.com` or `<just@email.com>`, poetry throws a bare exception:

```
[AttributeError]               
'NoneType' object has no attribute 'group'
```
from `.../site-packages/poetry/packages/package.py in author_name() at line 130`

The handling/message could be improved.

**Comment by finswimmer** [comment] 2020-01-08 10:14
Hey @viraptor,

this is a duplicate of #1143. So I will close this here.

fin swimmer

**Closed by finswimmer** 2020-01-08 10:14 UTC
Labels: Bug
