### ISSUE TITLE
poetry is using dev releases even when no --allow-prerelease flag is set

### ISSUE THREAD

**Issue by shughes-uk** [python-poetry/poetry#3653] opened 2021-02-05 20:55 UTC
- [x ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [ x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: OSX Big Sur
- **Poetry version**: 1.1.4

## Issue
Assuming you have a package with a two versions like `0.1.10` `0.1.10.post1.dev0` on pypi

`poetry add package` pulls in `0.1.10.post2.dev0` instead of the expected `0.1.10`

`pip install` correctly pulls `0.1.10` unless you pass the `--pre` flag

this also applies to `poetry update`

**Comment by finswimmer** [comment] 2022-05-24 08:32
Hello @shughes-uk,

your post is missing a reproducible minimal example. However, this topic is evolved a lot since you've open this ticket. Please try with the latest stable and pre-release version.

I'm closing this for now.  Feel free to leave a comment if you disagree.

fin swimmer

**Closed by finswimmer** 2022-05-24 08:32 UTC
Labels: Bug, Triage
