### ISSUE TITLE
[__NSCFType bytes]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by harrycis** [python-poetry/poetry#7060] opened 2022-11-19 04:58 UTC
Having a issue running poetry on Mac M1, macOS 12.6.1
python 3.10.8

Prior similar issue closed https://github.com/python-poetry/poetry/issues/5596
```
python[3063:17725] -[__NSCFType bytes]: unrecognized selector sent to instance 0x145e29040
2022-11-18 20:55:23.808 python[3063:17725] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFType bytes]: unrecognized selector sent to instance 0x145e29040'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000180609148 __exceptionPreprocess + 240
	1   libobjc.A.dylib                     0x0000000180353e04 objc_exception_throw + 60
	2   CoreFoundation                      0x000000018069cef8 -[NSObject(NSObject) __retain_OA] + 0
	3   CoreFoundation                      0x0000000180568494 ___forwarding___ + 1764
	4   CoreFoundation                      0x0000000180567cf0 _CF_forwarding_prep_0 + 96
	5   libffi.dylib                        0x000000018e750050 ffi_call_SYSV + 80
	6   libffi.dylib                        0x000000018e758ae8 ffi_call_int + 1208
	7   _ctypes.cpython-310-darwin.so       0x00000001062ac4b4 _ctypes_callproc + 1272
	8   _ctypes.cpython-310-darwin.so       0x00000001062a5768 PyCFuncPtr_call + 1168
	9   python                              0x0000000104666bf4 _PyObject_MakeTpCall + 360
	10  python                              0x000000010473e06c call_function + 524
	11  python                              0x000000010473b89c _PyEval_EvalFrameDefault + 24576
	12  python                              0x00000001047357a0 _PyEval_Vector + 148
	13  python                              0x000000010473e00c call_function + 428
	14  python                              0x000000010473b89c _PyEval_EvalFrameDefault + 24576
	15  python                              0x00000001047357a0 _PyEval_Vector + 148
	16  python                              0x000000010473e00c call_function + 428
	17  python                              0x000000010473b82c _PyEval_EvalFrameDefault + 24464
	18  python                              0x00000001047357a0 _PyEval_Vector + 148
	19  python                              0x000000010473e00c call_function + 428
	20  python                              0x000000010473b80c _PyEval_EvalFrameDefault + 24432
	21  python                              0x00000001047357a0 _PyEval_Vector + 148
	22  python                              0x000000010473e00c call_function + 428
	23  python                              0x000000010473b82c _PyEval_EvalFrameDefault + 24464
	24  python                              0x00000001047357a0 _PyEval_Vector + 148
	25  python                              0x000000010473e00c call_function + 428
	26  python                              0x000000010473b80c _PyEval_EvalFrameDefault + 24432
	27  python                              0x00000001047357a0 _PyEval_Vector + 148
	28  python                              0x000000010473e00c call_function + 428
	29  python                              0x000000010473b80c _PyEval_EvalFrameDefault + 24432
	30  python                              0x00000001047357a0 _PyEval_Vector + 148
	31  python                              0x0000000104669150 method_vectorcall + 168
	32  python                              0x000000010473e00c call_function + 428
	33  python                              0x000000010473b90c _PyEval_EvalFrameDefault + 24688
	34  python                              0x00000001047357a0 _PyEval_Vector + 148
	35  python                              0x0000000104669150 method_vectorcall + 168
	36  python                              0x000000010473e00c call_function + 428
	37  python                              0x000000010473b90c _PyEval_EvalFrameDefault + 24688
	38  python                              0x00000001047357a0 _PyEval_Vector + 148
	39  python                              0x000000010473e00c call_function + 428
	40  python                              0x000000010473b80c _PyEval_EvalFrameDefault + 24432
	41  python                              0x00000001047357a0 _PyEval_Vector + 148
	42  python                              0x000000010473e00c call_function + 428
	43  python                              0x000000010473b80c _PyEval_EvalFrameDefault + 24432
	44  python                              0x00000001047357a0 _PyEval_Vector + 148
	45  python                              0x0000000104669150 method_vectorcall + 168
	46  python                              0x0000000104666fc0 PyVectorcall_Call + 144
	47  python                              0x000000010473bb1c _PyEval_EvalFrameDefault + 25216
	48  python                              0x00000001047357a0 _PyEval_Vector + 148
	49  python                              0x0000000104669150 method_vectorcall + 168
	50  python                              0x000000010473e00c call_function + 428
	51  python                              0x000000010473b90c _PyEval_EvalFrameDefault + 24688
	52  python                              0x00000001047357a0 _PyEval_Vector + 148
	53  python                              0x000000010473e00c call_function + 428
	54  python                              0x000000010473b80c _PyEval_EvalFrameDefault + 24432
	55  python                              0x00000001047357a0 _PyEval_Vector + 148
	56  python                              0x000000010473e00c call_function + 428
	57  python                              0x000000010473b80c _PyEval_EvalFrameDefault + 24432
	58  python                              0x00000001047357a0 _PyEval_Vector + 148
	59  python                              0x000000010473e00c call_function + 428
	60  python                              0x000000010473b80c _PyEval_EvalFrameDefault + 24432
	61  python                              0x00000001047357a0 _PyEval_Vector + 148
	62  python                              0x000000010473e00c call_function + 428
	63  python                              0x000000010473b80c _PyEval_EvalFrameDefault + 24432
	64  python                              0x00000001047357a0 _PyEval_Vector + 148
	65  python                              0x000000010473e00c call_function + 428
	66  python                              0x000000010473b80c _PyEval_EvalFrameDefault + 24432
	67  python                              0x00000001047357a0 _PyEval_Vector + 148
	68  python                              0x000000010473e00c call_function + 428
	69  python                              0x000000010473b80c _PyEval_EvalFrameDefault + 24432
	70  python                              0x00000001047357a0 _PyEval_Vector + 148
	71  python                              0x0000000104669234 method_vectorcall + 396
	72  python                              0x00000001047c658c bounded_lru_cache_wrapper + 268
	73  python                              0x0000000104666bf4 _PyObject_MakeTpCall + 360
	74  python                              0x000000010473e06c call_function + 524
	75  python                              0x000000010473b82c _PyEval_EvalFrameDefault + 24464
	76  python                              0x00000001047357a0 _PyEval_Vector + 148
	77  python                              0x0000000104734320 min_max + 512
	78  python                              0x00000001046ab8b4 cfunction_call + 84
	79  python                              0x0000000104667158 _PyObject_Call + 172
	80  python                              0x000000010473bb1c _PyEval_EvalFrameDefault + 25216
	81  python                              0x00000001047357a0 _PyEval_Vector + 148
	82  python                              0x000000010473e00c call_function + 428
	83  python                              0x000000010473b80c _PyEval_EvalFrameDefault + 24432
	84  python                              0x00000001047357a0 _PyEval_Vector + 148
	85  python                              0x000000010473e00c call_function + 428
	86  python                              0x000000010473b80c _PyEval_EvalFrameDefault + 24432
	87  python                              0x00000001047357a0 _PyEval_Vector + 148
	88  python                              0x000000010473e00c call_function + 428
	89  python                              0x000000010473b90c _PyEval_EvalFrameDefault + 24688
	90  python                              0x00000001047357a0 _PyEval_Vector + 148
	91  python                              0x0000000104669150 method_vectorcall + 168
	92  python                              0x000000010473e00c call_function + 428
	93  python                              0x000000010473b90c _PyEval_EvalFrameDefault + 24688
	94  python                              0x00000001047357a0 _PyEval_Vector + 148
	95  python                              0x0000000104669150 method_vectorcall + 168
	96  python                              0x000000010473e00c call_function + 428
	97  python                              0x000000010473b90c _PyEval_EvalFrameDefault + 24688
	98  python                              0x00000001047357a0 _PyEval_Vector + 148
	99  python                              0x000000010473e00c call_function + 428
	100 python                              0x000000010473b80c _PyEval_EvalFrameDefault + 24432
	101 python                              0x00000001047357a0 _PyEval_Vector + 148
	102 python                              0x000000010473e00c call_function + 428
	103 python                              0x000000010473b80c _PyEval_EvalFrameDefault + 24432
	104 python                              0x00000001047357a0 _PyEval_Vector + 148
	105 python                              0x000000010473e00c call_function + 428
	106 python                              0x000000010473b80c _PyEval_EvalFrameDefault + 24432
	107 python                              0x00000001047357a0 _PyEval_Vector + 148
	108 python                              0x000000010473e00c call_function + 428
	109 python                              0x000000010473b80c _PyEval_EvalFrameDefault + 24432
	110 python                              0x00000001047357a0 _PyEval_Vector + 148
	111 python                              0x000000010473e00c call_function + 428
	112 python                              0x000000010473b80c _PyEval_EvalFrameDefault + 24432
	113 python                              0x00000001047357a0 _PyEval_Vector + 148
	114 python                              0x000000010473e00c call_function + 428
	115 python                              0x000000010473b80c _PyEval_EvalFrameDefault + 24432
	116 python                              0x00000001047357a0 _PyEval_Vector + 148
	117 python                              0x0000000104669150 method_vectorcall + 168
	118 python                              0x000000010473e00c call_function + 428
	119 python                              0x000000010473b82c _PyEval_EvalFrameDefault + 24464
	120 python                              0x00000001047357a0 _PyEval_Vector + 148
	121 python                              0x000000010473e00c call_function + 428
	122 python                              0x000000010473b80c _PyEval_EvalFrameDefault + 24432
	123 python                              0x00000001047357a0 _PyEval_Vector + 148
	124 python                              0x000000010473e00c call_function + 428
	125 python                              0x000000010473b80c _PyEval_EvalFrameDefault + 24432
	126 python                              0x00000001047357a0 _PyEval_Vector + 148
	127 python                              0x000000010473e00c call_function + 428
	128 python                              0x000000010473b89c _PyEval_EvalFrameDefault + 24576
	129 python                              0x00000001047357a0 _PyEval_Vector + 148
	130 python                              0x00000001047356f8 PyEval_EvalCode + 108
	131 python                              0x000000010478026c _PyRun_SimpleFileObject + 692
	132 python                              0x000000010477fdcc _PyRun_AnyFileObject + 160
	133 python                              0x000000010479e124 Py_RunMain + 1700
	134 python                              0x000000010479e5ac pymain_main + 340
	135 python                              0x000000010479e628 Py_BytesMain + 40
	136 dyld                                0x0000000104b4108c start + 520
)
libc++abi: terminating with uncaught exception of type NSException
[1]    3063 abort      poetry lock
```

After remove virtualenv, run poetry lock I got
`
[Errno 2] No such file or directory: '/Users/xxxx/Library/Application Support/pypoetry/venv/lib/python3.10/site-packages/xattr/lib_build.h'
`
re-run poetry lock then the same crash shows up again

**Comment by dimbleby** [comment] 2022-11-19 11:11
> Prior similar issue closed https://github.com/python-poetry/poetry/issues/5596

on the grounds that this didn't look like a poetry problem, which seems just as true today.

your second symptom looks like a duplicate of #6891

**Comment by neersighted** [comment] 2022-11-19 19:32
Closing as unrelated to Poetry -- something is happening in CPython or an extension, but given recreating your environment fixed it, it seems unproductive to track here.

If anyone ever manages to reproduce this consistently, feel free to reach out. It's not going to be a bug in Poetry, but we might at least be able to figure out if it comes from a dependency or Python itself and send you to the right place to report it.

**Closed by neersighted** 2022-11-19 19:32 UTC
Labels: kind/bug, status/triage
