### ISSUE TITLE
Error ModuleNotFoundError: No module named '_distutils_hack'

### ISSUE THREAD

**Issue by Vorobeyko** [python-poetry/poetry#9115] opened 2024-03-05 13:19 UTC
### Description

I ran command "poetry lock && poetry install --sync" and giving error like on screenshot.

<img width="1030" alt="image" src="https://github.com/python-poetry/poetry/assets/11293201/396c65ff-a810-4b54-8737-bc430f8d2c9d">

### Workarounds

Command is working, only have a log error

### Poetry Installation Method

install.python-poetry.org

### Operating System

macOS 14.3.1

### Poetry Version

1.8.2

### Poetry Configuration

```bash session
[tool.poetry]
name = "poetry-workspaces-plugin"
version = "0.31.0"
description = ""
authors = [""]
readme = "README.md"
packages = [
    {include = "poetry_workspaces_plugin"}
]

[[tool.poetry.source]]
name = "internal-virtual-pypi"
url = "https://artifactory<own_domain>/pypi-virtual/simple"
priority = "primary"

[tool.poetry.dependencies]
python = "^3.10"
toml = "^0.10.2"
pytest = "^7.4.0"

[tool.poetry.dev-dependencies]
poetry = "1.8.2"
flake8 = "6.0.0"

[tool.poetry.plugins."poetry.application.plugin"]
workspaces = "poetry_workspaces_plugin.plugin:WorkspacePlugin"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

### Poetry Runtime Logs

```bash session
poetry lock && poetry install --sync
Error processing line 1 of /Users/avorobey/miniconda/envs/poetry-workspaces-plugin/lib/python3.10/site-packages/distutils-precedence.pth:

  Traceback (most recent call last):
    File "/Users/avorobey/miniconda/envs/poetry-workspaces-plugin/lib/python3.10/site.py", line 186, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named '_distutils_hack'

Remainder of file ignored
```
```

**Comment by dimbleby** [comment] 2024-03-05 13:54
this isn't going to be a poetry bug.  google search finds lots of similar without any relation to poetry

(also you didn't provide the verbose output that the issue template asks for - so it would be hard for anyone to help anyway)

**Comment by abn** [comment] 2024-03-05 22:44
This looks like an issue caused by the miniconda managed virtual environment used by the project. Try removing the miniconda env and let poetry create a new venv.

Closing as we do not have sufficient information to reproduce the issue. If the issue persists with the latest poetry versions, please raise a new issue with a reproducer and additional information.

Thank you for taking the time to raise this issue.

**Closed by abn** 2024-03-05 22:44 UTC
Labels: kind/bug, status/triage
