### ISSUE TITLE
Incorrect release date for 1.1.7 (https://python-poetry.org/history/)

### ISSUE THREAD

**Issue by vijayparne** [python-poetry/poetry#4319] opened 2021-07-26 16:35 UTC
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

**Comment by vijayparne** [comment] 2021-07-26 16:36
Year value is incorrect.

**Comment by vijayparne** [comment] 2021-07-26 16:36
![image](https://user-images.githubusercontent.com/10782606/127025946-e7e94087-4463-4a9b-a36e-1f1648ad2dab.png)

**Comment by finswimmer** [comment] 2021-07-26 17:03
Duplicate of https://github.com/python-poetry/poetry/issues/4282

**Closed by finswimmer** 2021-07-26 17:03 UTC
Labels: Documentation, Triage
