### ISSUE TITLE
KeyRingError: Failed to create the collection: Prompt dismissed..

### ISSUE THREAD

**Issue by AbstractUmbra** [python-poetry/poetry#3012] opened 2020-10-01 06:38 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Debian 10
- **Poetry version**: Poetry version 1.0.10
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: [Link!](https://gist.github.com/AbstractUmbra/13915cd8f7d7235ab0e6940562afce2e)

## Issue

Hello!
Just starting out using poetry to build and publish a package - when trying to configure my PyPI token with `poetry config pypi-token.pypi <redacted token>` I get the following exception:

```py
Loading configuration file /home/penumbra/.config/pypoetry/config.toml

[KeyRingError]
Unable to store the password for poetry-repository-pypi in the key ring: Failed to create the collection: Prompt dismissed..

Traceback (most recent call last):
  File "/home/penumbra/.poetry/lib/poetry/_vendor/py3.8/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/home/penumbra/.poetry/lib/poetry/_vendor/py3.8/clikit/api/command/command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "/home/penumbra/.poetry/lib/poetry/_vendor/py3.8/clikit/api/command/command.py", line 171, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/home/penumbra/.poetry/lib/poetry/_vendor/py3.8/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File "/home/penumbra/.poetry/lib/poetry/console/commands/config.py", line 216, in handle
    password_manager.set_pypi_token(m.group(2), token)
  File "/home/penumbra/.poetry/lib/poetry/utils/password_manager.py", line 139, in set_pypi_token
    self.keyring.set_password(name, "__token__", token)
  File "/home/penumbra/.poetry/lib/poetry/utils/password_manager.py", line 55, in set_password
    raise KeyRingError(
```

I have searched for this exception and found no other issues. similar. Any help is appreciated!

**Comment by abn** [comment] 2020-10-01 06:44
Duplicate of #2692

**Comment by abn** [comment] 2020-10-01 06:45
@AbstractUmbra please refer to the above issue. This is because your keyring is locked, and seems your shell was not able to create the prompt unlock.

**Closed** 2020-10-01 06:51 UTC
Labels: Question
