### ISSUE TITLE
Add an option to filter out transitive dependencies while checking for updates to available packages

### ISSUE THREAD

**Issue by feierabend654** [python-poetry/poetry#4342] opened 2021-08-02 07:45 UTC
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request
Whenever I want to see which packages can be updated, I do `poetry show -o `. But this command list also updates to transitive dependencies. As I only want to update packages which are directly referenced by me in pyproject.toml i.e. maybe we can offer filtering out the transitive dependencies i.e dependencies of dependencies 

Below is an example of a dependency which is brought in by fastapi transitively, but I am already on the latest version of fastapi
```
$ poetry show -o 
starlette 0.14.2 0.16.0 The little ASGI library that shines.
```

**Comment by mkniewallner** [comment] 2022-07-09 15:59
Duplicate of #4175.

**Closed by mkniewallner** 2022-07-09 15:59 UTC
Labels: Feature, Triage
