### ISSUE TITLE
SolverProblemError with papermill

### ISSUE THREAD

**Issue by AssassinTee** [python-poetry/poetry#2819] opened 2020-08-17 08:47 UTC
## Information

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 18 LTS
- **Poetry version**: 1.0.10 (and 1.0.5, too)
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: Not required

## Issue
When installing [papermill](https://github.com/nteract/papermill) with poetry i got the following error message:

```
[SolverProblemError]
Because no versions of papermill match >2.1.2,<3.0.0
 and papermill (2.1.2) depends on black (*), papermill (>=2.1.2,<3.0.0) requires black (*).
So, because no versions of black match *
 and **myframework** on papermill (^2.1.2), version solving failed.
```

It looks like it failed to find any version of [black](https://pypi.org/project/black/), which is weird.

## workaround

I just installed black by hand and papermill after that with:

```
poetry add black
poetry add papermill
```

This resolved my issue but I leave it here for the poetry devs and other users running into this issue

**Comment by abn** [comment] 2020-08-17 09:04
@AssassinTee can you try the latest release (`1.0.10`) or pre-release (`1.1.0b2`) please? This seems to be resolved.
```console
$ poetry --version
Poetry version 1.0.10
$ poetry add black
Using version ^19.10b0 for black

Updating dependencies
Resolving dependencies... (0.1s)

Writing lock file


Package operations: 8 installs, 0 updates, 0 removals

  - Installing appdirs (1.4.4)
  - Installing attrs (19.3.0)
  - Installing click (7.1.2)
  - Installing pathspec (0.8.0)
  - Installing regex (2020.7.14)
  - Installing toml (0.10.1)
  - Installing typed-ast (1.4.1)
  - Installing black (19.10b0)
$ poetry add papermill
Using version ^2.1.2 for papermill

Updating dependencies
Resolving dependencies... (0.4s)

Writing lock file


Package operations: 27 installs, 0 updates, 0 removals

  - Installing decorator (4.4.2)
  - Installing ipython-genutils (0.2.0)
  - Installing six (1.15.0)
  - Installing pyrsistent (0.16.0)
  - Installing traitlets (4.3.3)
  - Installing jsonschema (3.2.0)
  - Installing jupyter-core (4.6.3)
  - Installing python-dateutil (2.8.1)
  - Installing pyzmq (19.0.2)
  - Installing tornado (6.0.4)
  - Installing async-generator (1.10)
  - Installing certifi (2020.6.20)
  - Installing chardet (3.0.4)
  - Installing idna (2.10)
  - Installing jupyter-client (6.1.6)
  - Installing nbformat (5.0.7)
  - Installing nest-asyncio (1.4.0)
  - Installing textwrap3 (0.9.2)
  - Installing urllib3 (1.25.10)
  - Installing ansiwrap (0.8.4)
  - Installing entrypoints (0.3)
  - Installing nbclient (0.4.1)
  - Installing pyyaml (5.3.1)
  - Installing requests (2.24.0)
  - Installing tenacity (6.2.0)
  - Installing tqdm (4.48.2)
  - Installing papermill (2.1.2)
```

**Comment by AssassinTee** [comment] 2020-08-17 09:34
I updated poetry with `poetry update self` to version 1.0.10 and opened a new **clean** conda environment, **only** installing papermill with `poetry add papermill` still leads to the error:

```
[SolverProblemError]
Because no versions of papermill match >2.1.2,<3.0.0
 and papermill (2.1.2) depends on black (*), papermill (>=2.1.2,<3.0.0) requires black (*).
So, because no versions of black match *
 and poetrydemo depends on papermill (^2.1.2), version solving failed.

```

**Comment by abn** [comment] 2020-08-17 09:49
@AssassinTee whats the python dependency for your project? And what is your python runtime version?

**Comment by AssassinTee** [comment] 2020-08-17 09:50
I am currently using python 3.7 and was able to create the issue with a clean conda environment (without other dependencies)

**Comment by abn** [comment] 2020-08-17 10:02
Thanks for that. I can reproduce the issue now using:

```shell
poetry add --dry-run papermill
```

I was installing black before papermill; missed the part you said about it being the workaround :)

**Comment by abn** [comment] 2020-08-17 16:39
The root cause here is that when provided `black (*)` as a dependency; since `black` only has pre-release versions, no version was detected when resolving for dependencies of `paparmill`. I have attempted to fix it by modifying currrent behaviour such that such packages fallback to returning pre-release versions if constraint is `(*)`. Alternative fix might be in `poetry-core` where a dependency that uses an any constraint is enabled to allow pre-release. The latter might have undesired side-effects.

**Closed** 2020-08-27 14:35 UTC
Labels: Bug, Dependency resolution
