### ISSUE TITLE
pre-commit autoupdate pulls incorrect Poetry version 1.2.2 -> 1.2.0rc1

### ISSUE THREAD

**Issue by danjac** [python-poetry/poetry#7139] opened 2022-12-04 09:06 UTC
- **Poetry version**: 1.2.2
- **Python version**: 3.11.0
- **OS version and name**: Fedora Linux 37

- [x ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [ x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

Running pre-commit version 2.20.0:

I currently have this pre-commit hook to do poetry checks and export requirements in my project, along with multiple other pre-commit hooks (Black, prettier etc):

```
    - repo: https://github.com/python-poetry/poetry
      rev: 1.2.2
      hooks:
          - id: poetry-check
          - id: poetry-export
            args: ["--without-hashes"]
```
Running `pre-commit autoupdate` all hook dependencies are updated correctly to the latest tagged versions, with the exception of Poetry:

```
Updating https://github.com/python-poetry/poetry ... updating 1.2.2 -> 1.2.0rc1
```

Of course `1.2.0rc1` is a broken and outdated earlier version. 

This may be an issue with pre-commit but would like to clarify if there is a problem first on the Poetry side, given all other hooks are updating correctly.

**Comment by neersighted** [comment] 2022-12-04 09:14
Not a bug; this is [by design in pre-commit](https://python-poetry.org/docs/pre-commit-hooks/#faq). There is nothing to be done to resolve this in the Poetry repository. We have considered a separate repo to track Poetry with a synthetic tag/branching structure, but have not committed to supporting such a thing at this time.

**Closed by neersighted** 2022-12-04 09:14 UTC
Labels: kind/bug, status/triage

**Comment by danjac** [comment] 2022-12-04 09:19
Understood, I misread the FAQ. Seems pre-commit & poetry maintainers just have unresolvable difference on opinion here on branching strategy.
