### ISSUE TITLE
poetry tries to install nbformat py3 wheel in a py2 environment

### ISSUE THREAD

**Issue by romaingz** [python-poetry/poetry#1963] opened 2020-01-31 14:38 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: CentOS 7
- **Poetry version**: 1.0.3, 1.0.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 
```
[tool.poetry.dependencies]
python = "^2.7"
```

## Issue
When running `poetry add nbformat` with the only requirement `python = "^2.7"`, poetry tries to install `nbformat==5.0.4` which is py3 only and fails.

I assume from the README that it should find by itself that `4.4.0` is the latest py2 compatible version.

If I pin that `nbformat = "4.4.0"` in my `pyproject.toml` it gets correctly installed, but I get issues later on with `papermill`.

**Edit**
Reproduced on version 1.0.3.

**Comment by s0undt3ch** [comment] 2020-02-02 10:04
Does the `nbformat` package properly set the supported python versions depending on its own version? Ie, seems like version `>=5` should define that it's not Py2 compatible.

I know poetry still has issues resolving complex dependencies(namely if you add platform markers, which is why we still haven't moved to poetry) but this looks like a simple "problem" that, if given enough and proper information, poetry should be able to resolve.

Anyway, just trying to get more information, I'm still pretty new to poetry.

**Comment by s0undt3ch** [comment] 2020-02-02 10:08
Well it does seem that nbformst [does](https://github.com/jupyter/nbformat/blob/master/setup.py#L64) set the right information....

**Comment by romaingz** [comment] 2020-02-02 15:31
Yes, I also checked that they correctly specified their wheel as [non universal](https://github.com/jupyter/nbformat/blob/7c56b0b4fe918448f30a4918d05ded682bccaaab/setup.cfg#L2).

I am taking a look at poetry for migrating our projects so still in the discovering phase also.

**Comment by romaingz** [comment] 2020-02-03 13:03
Reproduced it on 1.0.3.

**Comment by dimbleby** [comment] 2022-06-18 20:07
Another duplicate of #707, #1589, #2171, #5453, ...

**Closed** 2022-09-18 01:58 UTC
Labels: kind/bug, status/duplicate
