### ISSUE TITLE
Display a sign when poetry update downgrade package version

### ISSUE THREAD

**Issue by gsemet** [python-poetry/poetry#5414] opened 2022-04-05 15:11 UTC
When `poetry update` does an downgrade of a package, display a little down arrow to highlight when a package goes backward for some reason.

It happened recently, flake8 has been silently downgraded :
```
Updating flake8 (3.9.2 -> 2.3.0)
```
It is set as `version = "*"` in the toml. Setting `>=3.9` fix the downgrade, but I would have been happy if a simple little sign would display when a package goes down !

**Comment by Rafeqm** [comment] 2022-04-16 03:22
That's a great feature!

**Comment by abn** [comment] 2022-05-25 00:54
Ack. Closing as a duplicate of #1394. Definitely something that will improve UX.

**Closed by abn** 2022-05-25 00:54 UTC
Labels: Feature
