### ISSUE TITLE
poetry -vv

### ISSUE THREAD

**Issue by whoizit** [python-poetry/poetry#1755] opened 2019-12-17 11:04 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **Arch Linux Latest**: 
- **1.0.0**: 

## Issue

this command simply not works. I remember that it used to work, because I created `alias poet='poetry -vv'`
`poetry -vv add wagtail`
it works only as `poetry add -vv wagtail` (but `-v` commands marks as global options)

**Comment by finswimmer** [comment] 2020-02-03 05:22
Hello @whoizit,

your issue seems to be a duplicate of #1502 . So I will close this one here. If you disagree just leave a comment.

Thanks a lot for reporting :+1: 

fin swimmer

**Closed by finswimmer** 2020-02-03 05:22 UTC
Labels: Bug
