### ISSUE TITLE
import modules from one poetry environments to another

### ISSUE THREAD

**Issue by kakyoism** [python-poetry/poetry#4792] opened 2021-11-18 03:15 UTC
- [x ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x ] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Issue

I have a folder structure looking like this
```
- server
  - core.py
  - pyproject.toml
- service_1
  - core.py
  - pyproject.toml
- service_2
  - core.py
  - pyproject.toml
```

Each top-level folder contains a poetry project.
However, `server` depends on `service_1` and `service_2` and must import modules, e.g., core.py, of those services.

Then I got dependency errors in the services because the dependency resolver seems to use the server's poetry context for the services. This certainly won't work because those dependencies are not part of server's .toml. This would then force me to collect ALL the dependencies from all the services, unable to reuse those sub-poetry environments.

This actually beats the purpose of separating the service venv's, and will thus create dependency conflicts down the road.

How should I cope with this?

**Comment by finswimmer** [comment] 2021-12-28 08:03
Hello @kakyoism,

if you need to import `core` from `service_1` there is no other way than define `service_1` as a dependency of `server`. If this leads to dependency conflicts please post the error message and all `pyproject.toml` so that we can reproduce it.

fin swimmer

**Comment by finswimmer** [comment] 2022-01-21 14:04
Because we haven't receive more information I assume the original issue is solved. So I'm closing this. Feel free to leave a comment if you disagree.

**Closed by finswimmer** 2022-01-21 14:04 UTC
Labels: Awaiting Reponse
