### ISSUE TITLE
``poetry install`` doesn't add license files to ``dist-info`` directory

### ISSUE THREAD

**Issue by andreasdoll** [python-poetry/poetry#9836] opened 2024-11-07 10:46 UTC
### Issue Kind

Change in current behaviour

### Description

Hello

I want to add license files to the dist-info directory when using ``poetry install``.

Currently the [automatic inclusion of license files](https://python-poetry.org/docs/libraries#packaging) only applies the wheels/sdist (when using ``poetry build``).
When using ``poetry install``, no license file gets added to ``venv/Lib/site-packages/my_pkg-1.2.3.dist-info/`` directory.

Is it intended behavior that ``install`` doesn't add the license files?
Can I achieve my goal somehow without modifying poetry?
If not: would you rather add the automatic inclusion to ``install``, or manually as

```
[tool.poetry] 
include = [
    { path = "LICENSE.txt", format = "dist-info" },
]
```

### Impact

My motivation is a tool dealing with licenses. In a CI/CD pipeline, I use ``poetry install`` to setup the environment in which I perform unit tests, and in this setup the license files are missing from the dist-info directory.

No issue when installing this tool from a package index, since in this case I use ``build`` outputs (wheel/sdist). which indeed have the license file automatically added.

### Workarounds

No workaround known, since the ``include`` functionality in ``[tool.poetry]`` targets only wheels/sdist.

**Comment by dimbleby** [comment] 2024-11-07 11:46
poetry install is doing an editable install, pretty much all of the files in your project are not copied around.  Why do you want LICENSE to be copied?

Indeed, what is the expected behaviour for an editable install if you update the LICENSE file in your project directory?  Do you want a stale LICENSE file to be left in the dist-info?

**Comment by andreasdoll** [comment] 2024-11-07 13:38
The reason I'd like to have ``LICENSE`` copied is that the package expects its license file to be in the respective ``dist-info`` directory (which is the case when installed from a package index). This is not the case when installed via ``poetry install`` (in a CI/CD pipeline) and thus prevents me from executing unit tests without some mocking.

Regarding your second paragraph: true, ``install`` creates an editable install, yet poetry creates a ``dist-info/METADATA`` which is based on the  information in ``pyproject.toml``. If one updates this information, the ``METADATA`` file is outdated , just like the license file in your example. From my point of view, there is no reason to to treat those two sources of metadata differently, but I accept that there are differing POVs.

After looking a bit into the codebase, I think it will be less effort for me to mock in my tests than to submit a PR.
I understand that you probably have no interest in working on this yourself since it's quire a cornercase.

**Comment by dimbleby** [comment] 2024-11-07 14:24
METADATA is a generated file that poetry is required to create by the spec describing editable installs

In constrast, I see LICENSE as more analogous with any other part of the source tree - therefore in my opinion it would be undesirable to copy it around at an editable install.  

Especially if it's anyway less effort for you not to pursue this then I'd just close it out.

(By the way, it seems curious to be trying to check the license of your own project.  That's surely the one project where you really should already know the answer...)

**Comment by Secrus** [comment] 2024-11-07 14:25
Once we implement PEP 639 this will be a valid request, until then I close it as a duplicate of #9670

**Closed by Secrus** 2024-11-07 14:25 UTC
Labels: kind/feature

**Comment by dimbleby** [comment] 2024-11-07 14:27
I don't see that PEP639 has anything to say about editable installs; but that discussion can wait until someone does something about PEP639

**Comment by Secrus** [comment] 2024-11-07 16:12
> I don't see that PEP639 has anything to say about editable installs

The editable wheels (PEP 660) spec says that they should be installed just like regular wheels, which means that new changes to `.dist-info` from PEP 639 are also included.

**Comment by andreasdoll** [comment] 2024-11-07 16:50
> (By the way, it seems curious to be trying to check the license of your own project. That's surely the one project where you really should already know the answer...)

Of course I know the license of the package itself. The problem lies in running the tests.
The simplified story is: the tool (it's a package) reads for all installed packages the license file from the respective dist-info directory
1. this works if the package is installed from a package index (since it uses wheel/sdist where the license file is in the dist-info directory)
2. this doesn't work if you install the package with ``poetry install`` since then there is no license file in the dist-info directory of this package

During testing in a CI/CD pipeline I'm in case (2) since I haven't built and published the code yet.

As said, I understand that you have a different opinion, thus feel free to close this issue.
By the way: thanks for your work on poetry!
