### ISSUE TITLE
export requirements.txt - local dependency file exported as editable

### ISSUE THREAD

**Issue by visciang** [python-poetry/poetry#897] opened 2019-02-16 15:32 UTC
- **OS version and name**: Linux
- **Poetry version**: 1.0.0a2

## Issue
`poetry export --without-hashes --format=requirements.txt` ouputs local file dependencies as "editable":

```
-e local/path/package.whl
```
This is reported as an error when parsed by `pip install`:

```
local/path/package.whl should either be a path to a local project
or a VCS url beginning with svn+, git+, hg+, or bzr+
```

The correct format should not include the `-e` part (ref. https://pip.pypa.io/en/stable/reference/pip_install/#requirements-file-format).

NOTE:
This is covered in `test_exports.py` https://github.com/sdispater/poetry/blob/develop/tests/utils/test_exporter.py#L353

**Comment by gizmo385** [comment] 2019-07-10 22:03
Bumping this issue. We're noticing a similar problem and it's causing problems for our serverless deployments. Pip is complaining whenever we try to install from the `requirements.txt` file that `poetry export` generates. Is there a fix for this issue?

**Comment by severinsimmler** [comment] 2019-09-30 08:09
+1

**Comment by riclima** [comment] 2019-10-12 18:45
I've come across something similar. My export came with the editable flag for a dependency using a Git url. Had to remove the flag before I could deploy it using Pip in production. Using Poetry 1.0.0b2.

**Comment by iwoloschin** [comment] 2019-10-17 13:46
I think this line here needs to be changed to remove the `-e`?

https://github.com/sdispater/poetry/blob/master/poetry/utils/exporter.py#L84

I see a few other `-e`'s scattered through the file though, so I'm not sure if there's something else that needs to be replaced as well?

In any case, a quick workaround is to use `sed` to strip out the offending `-e`s.
```
poetry export -f requirements.txt | sed 's/-e //'
```

**Comment by filipelbc** [comment] 2020-01-06 21:31
I'm having the same issue here.

**Comment by finswimmer** [comment] 2020-01-07 05:16
Thanks for reporting!

#1840 should fix it.

fin swimmer

**Closed** 2020-01-09 08:31 UTC
Labels: Bug

**Comment by JulianFerry** [comment] 2020-07-12 16:10
Unless I'm mistaken this still adds the -e tag? I'm calling `poetry export --without-hashes -f requirements.txt > requirements.txt` with `Poetry version 1.0.9`

**Comment by finswimmer** [comment] 2020-07-14 08:39
Hello @JulianFerry ,

can you show an example of your output where you think it's still wrong?

fin swimmer

**Comment by JulianFerry** [comment] 2020-07-19 14:08
As a full reproducible example, I did:
```
poetry new dependency
poetry new proj
cd proj
```
then added this to my pyproject.toml:
```
dependency = { path = "../dependency" }
```
then:
```
poetry export --without-hashes -f requirements.txt > requirements.txt
cat requirements.txt
```
returns:
```
-e ../dependency
```

**Comment by finswimmer** [comment] 2020-07-19 18:08
@JulianFerry the behavior is correct here. Path dependencies are installed in editable mode (by default). So it's also exported in editable mode.

fin swimmer

**Comment by JulianFerry** [comment] 2020-08-05 11:39
@finswimmer 
Thanks. Is there a way to override this? I am trying to test both packages together in a fresh docker environment (e.g. CI build), without having to push the dependency to a repository. As it stands I am using `sed 's/-e //'`

**Comment by adamal** [comment] 2020-09-01 19:12
+1 for having the installation _method_ of path dependencies being controllable by a flag.

**Use case:**
When _developing locally_ (i.e. not dockerized) in a monorepo, it could be convenient to have editable installs of path dependencies, so that they are automatically up to date without `poetry update`'ing. 

When build time comes in a Dockerfile, though, a solution to having path dependencies at all is to have them installed (by copy / non-editable) to a venv in a multi-step build, and simply copy the venv from build to final image.

From my experimentation this seems to be accomplishable by either `poetry install` (forcing you to have `develop=false` in path dependencies) or using the above mentioned `sed`-trick and install using pip.
It would be helpful to have flag (perhaps `--no-editable`) that was respected by both `export` and `install`.
