### ISSUE TITLE
Poetry install with github private repo gets stuck resolving dependencies indefinitely

### ISSUE THREAD

**Issue by c-goosen** [python-poetry/poetry#2699] opened 2020-07-22 09:17 UTC
- [ x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu GNU Linux 20.04
- **Poetry version**: 1.0.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue

Output in verbose mode:
poetry install -vvv
....
   1: derived: Unidecode (1.1.1)
   1: derived: coreapi (2.3.3)
   1: derived: sentry-sdk (0.16.1)
   1: derived: django-fsm (2.7.0)
   1: derived: Jinja2 (2.11.2)
   1: derived: djangorestframework (3.11.0)
   1: derived: psycopg2 (2.8.5)
   1: derived: django-deprecate-fields (0.0.4)
   1: derived: jsonschema (3.2.0)
   1: derived: django-cors-headers (3.4.0)
   1: derived: boto3 (1.14.23)
   1: derived: django-cryptography (1.0)
   1: derived: django-health-check (3.12.1)
   1: derived: simple-salesforce (1.10.1)
   1: derived: djangorestframework-jwt (1.11.0)
Username for 'https://github.com': 

Without verbose mode (poetry install) no warning is shown. Dependency check gets stuck indefinitely.

No warning in normal mode

**Comment by dimbleby** [comment] 2022-06-19 12:00
no means to reproduce.  Looks like it's wanting a github password: git-cloning part of the code has been reworked since this was raised to use dulwich - so there's every chance that behaviour today is quite different.

if OP or anyone else would care to provide a pyproject.toml with which to reproduce this, please do so.  Else might as well close it.

**Comment by Secrus** [comment] 2022-06-19 12:02
Closing as no means to reproduce are present. If you still experience this issue, it might be reopened.

**Closed by Secrus** 2022-06-19 12:02 UTC
Labels: Bug, Triage

**Comment by dimbleby** [comment] 2022-06-19 12:35
Turns out that #3222 provides a repro, no need to open a new one even if you are still hitting this
