### ISSUE TITLE
dependency file inheritance

### ISSUE THREAD

**Issue by JudahSchwartz** [python-poetry/poetry#8317] opened 2023-08-16 06:56 UTC
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [FAQ](https://python-poetry.org/docs/faq/) and general [documentation](https://python-poetry.org/docs/) and believe that my question is not already covered.

## Feature Request
Declare that a certain prproject.toml file inherits from another

Usecase:
I manage many different python based docker images, each of which has its own set of python dependencies and os dependencies if relevant. all of them are based on our base_python image (FROM base_python) which has some dependencies (os and python) required for every one of our images.
Certifi, for example, is in our base image. 
Currently each docker image has its own poetry file, some of which redeclare certifi (in either the pyproject.toml or the lock file)
When building the image, if the certifi version is lower than the 1 we have on base, certifi would get downgraded. (relocking the child's file isnt always possible, we maintain more than 100 of these images)

Would be nice if I could have childproject.toml depend on parentproject.toml, so that it would know not to get downgraded (maybe the lock should be inherited somehow? certifi shouldnt be redeclared.)

If you dont think this is the proper solution, any advice on how to solve this problem would be helpful =)

**Comment by wagnerluis1982** [comment] 2023-08-20 21:48
This is a duplicate of the issue #2270, isn't it?

**Comment by abn** [comment] 2024-03-03 17:35
While the use case is not explicitly the same, since #2270 will resolve this use case as well closing as duplicate for now.

**Closed by abn** 2024-03-03 17:35 UTC
Labels: kind/feature, status/triage
