### ISSUE TITLE
Add support for environment variables at pyproject.toml

### ISSUE THREAD

**Issue by loop0** [python-poetry/poetry#208] opened 2018-06-12 18:56 UTC
It would be handy to have support for using values from environment vars on `pyproject.toml`
The use case I have is that I need to use different repository urls depending on my environment.
Something like:
```toml
[[tool.poetry.source]]                                                          
name = "private"                                                          
url = "${PRIVATE_REPO_URL}"
```

I'm still new to poetry, but I could help implementing the feature with some guidance.

**Comment by jordanhamill** [comment] 2018-08-05 20:36
I too would like to not check in a private repo url. Perhaps in this case, the value from `config.toml` could be used for the repository?

The docs already mention adding a repository url for pushing. If `url` was missing from source you could check for the following key:
```py
f"repositories.{source.name}.url"
```

I pushed up a spike 290e8863da8b8596d82f60484dcc08534abb3b3d to see if it would work and it looks like it does, I'm not sure if it is the correct solution though.

**Comment by kofron** [comment] 2018-10-01 21:09
@loop0 did you take a stab at this?  I'd love to see this implemented and have some ideas around how to do it.

**Comment by kofron** [comment] 2018-10-02 00:44
Awesome, great to hear - let me know if I can help at all.

Basically what I was imagining is a new function (or class) that lives in `poetry.util.helpers` called `environment_expander` or similar.  

The basic idea is that after pyproject.toml is read from disk, and after we know that it exists, we take a transformation pass over the TomlFile object, and applying a function to all of the values in the object that evaluate expressions of the form `${SOME_ENV_VARIABLE}` by calling `os.env`.  

I would want to apply this pass as early as often - at `poetry/puzzle/provider.py:161` for example.  

Not sure if you would want to `raise` if `SOME_ENV_VARIABLE` didn't exist...

Thoughts?

**Comment by loop0** [comment] 2018-10-02 00:53
Sounds a great idea! And of course you can help, I will try to make some time tomorrow to write the first code for it. If you feel you want to write it first just mark me on the PR and I can also help you later.

**Comment by kofron** [comment] 2019-03-12 15:35
@dimkirt https://github.com/sdispater/poetry/pull/481 - was closed a couple of days ago by the author, who doesn't want to add this feature.

**Comment by Peque** [comment] 2019-07-06 13:45
Pipenv [implements this feature](https://github.com/pypa/pipenv/blob/master/docs/advanced.rst#-injecting-credentials-into-pipfiles-via-environment-variables). As they mention, it is "*quite useful if you need to authenticate to a private PyPI*". That is my case too.

@sdispater Being ranked as the 11th most popular issue in this repository (out of 400+), would you reconsider accepting pull-requests for this? :innocent:

**Comment by metrofun** [comment] 2019-07-12 14:42
For us it's also a blocker to finally migrate from Pipenv

**Comment by loop0** [comment] 2019-07-12 16:48
We need this feature to migrate to poetry from pipenv as well, that's why I initially open this issue. Unfortunately I didn't have much time to work in the solution, but as far as I remember the code, it shouldn't be hard. We only need the bless from poetry's developers.

**Comment by kofron** [comment] 2019-07-12 20:40
I did actually do this work in this PR: https://github.com/sdispater/poetry/pull/481

However, @sdispater did not want to add this feature to the project.

**Comment by Peque** [comment] 2019-07-12 23:12
Let us hope they eventually change their mind and reconsider adding this to Poetry. :innocent:

**Comment by absassi** [comment] 2019-08-30 08:49
Although this solution would solve the problem, and it's the same solution as Pipenv, it's only good for CI, but terrible for humans. Once you put environment variable names in pyproject.toml, every developer must somehow export the variables to use Poetry, they can't just use `poetry config http-basic` anymore.

It would be much better if Poetry recognized specific environment variables as credentials (such as `POETRY_USERNAME` and `POETRY_PASSWORD` or maybe `POETRY_REPONAME_USERNAME`, to support different credentials for different repositories), like twine does, for instance. Then the environment variables are needed only for CI and humans can do whatever they want in their machines.

But this is not something you can do with an external program, it's something that needs to be implemented in Poetry.

**Comment by delphyne** [comment] 2019-08-31 16:23
@absassi I disagree.  Any large enterprise already has a set of consistent environment variables every developer must export.  These are used across many languages and toolsets (pipenv, cake, gradle, maven, ant, node, yarn, docker, terraform, etc.).  Adding a new set of environment variables is just as bad as using whatever people want.  

Maybe just compromise and do both.  look for some poetry-specific variable, but also allow environment variables to be interpolated like just about every other build tool that exists today.

**Comment by Peque** [comment] 2019-11-13 10:25
Still relevant.

Maybe @loop0 has some updates on this? :blush:

**Comment by loop0** [comment] 2019-11-13 16:06
No updates, sorry. We still want to migrate from pipenv to poetry here, but this issue is a blocker for most projects.

**Comment by loop0** [comment] 2019-11-13 16:29
For instance, there is a way to use poetry with gemfury's repository, but the documentation is not clear, here are the steps:
```sh
poetry config repositories.your_repo https://pypi.fury.io/your_repo/
# at the auth configuration you just repeat your token twice
poetry config http-basic.your_repo YOUR_TOKEN YOUR_TOKEN
```
And then you add the following to your pyproject.toml (after the `[tool.poetry]` block)
```
[[tool.poetry.source]]
name = "your_repo"
url = "https://pypi.fury.io/your_repo/"
```
So with some scripting it is possible to have this running on your CI

**Comment by adawalli** [comment] 2019-12-10 13:56
> For instance, there is a way to use poetry with gemfury's repository, but the documentation is not clear, here are the steps:
> 
> ```shell
> poetry config repositories.your_repo https://pypi.fury.io/your_repo/
> # at the auth configuration you just repeat your token twice
> poetry config http-basic.your_repo YOUR_TOKEN YOUR_TOKEN
> ```
> 
> And then you add the following to your pyproject.toml (after the `[tool.poetry]` block)
> 
> ```
> [[tool.poetry.source]]
> name = "your_repo"
> url = "https://pypi.fury.io/your_repo/"
> ```
> 
> So with some scripting it is possible to have this running on your CI

While this is true, if you are using docker, you run the risk of caching these credentials, which is obviously not good. As it stands, it's not really possible (without jumping through some serious hoops) to write a 12 Factor App (https://12factor.net/) with Poetry + Private Repos without better Environment Variable support.

**Comment by sandroden** [comment] 2020-04-29 08:19
I want o add another reason for using variable interpolation in `pyproject.toml`. When you add a dependency on locally stored projects as in:

```
[tool.poetry.dev-dependencies]
thx-sphinx = {path = "../thx-sphinx"}
```

you're making strong assumptions on where people place their files that is definitely not a nice behaviour. Much better to set a default that users can overwrite. A `.env` is a typical solution in docker environment and not only (ie: autoenv). When you enter a directory the .env is read and configured correctly. This would make `poetry` flexible enought for normal workflow.

**Comment by papagala** [comment] 2020-04-29 16:35
This would be incredibly convenient for CI/CD pipelines and for reusing already available private repository urls in the form of environment variables.

**Comment by absassi** [comment] 2020-05-05 10:45
@sandroden, depending on what you want to accomplish, you might be interested also in the feature request #1168, which can be an alternative to path dependencies.

**Comment by bubthegreat** [comment] 2020-05-29 05:11
@sdispater - Any reconsideration here?  This is difficult when I want to test anything that needs environment variables but I can't set and unset them without editing the virtualenv activate file directly, which is a huge hassle.  It makes it hard to test in multiple packages or environments that might need environment variables set, like DB_HOST, etc.

**Comment by funkyfuture** [comment] 2020-05-30 14:44
the system administrator in me likes that. but apart from it, it would lead to a situation where `poetry.lock` wouldn't be reproducible without sharing all environment variables. and then, what would be the point?

besides, i'm missing defaults being mentioned in this thread for which Docker-Compose has a good syntax, as an example.

**Comment by bubthegreat** [comment] 2020-05-30 17:47
I'm doing my own workarounds by having an .env file and pulling them from there, but my ideal world would be setting them locally in the virtualenv and adding them as checks in poetry.lock with a warning if they're not set.

**Comment by jacebrowning** [comment] 2020-08-23 22:25
Assuming the following environment variables are set:

```
export EXAMPLE_PYPI_URL=https://pypi.example.com/pypi/
export EXAMPLE_PYPI_USERNAME=example
export EXAMPLE_PYPI_PASSWORD=example
```

This is how I handle uploads to a private PyPI server:

```
poetry build
poetry config repositories.example ${EXAMPLE_PYPI_URL}
poetry config http-basic.example ${EXAMPLE_PYPI_USERNAME} ${EXAMPLE_PYPI_PASSWORD}
poetry publish --repository example
```

I can see why adding environment variable expansion to `pyproject.toml` could be too much of a scope creep for Poetry.

**Comment by SpicySyntax** [comment] 2020-09-25 15:41
What should we do in the case that the url for the private repo contains private username and password? I.E.
```
[[tool.poetry.source]]                                                          
name = "private"                                                          
url = "https://${ARTIFACTORY_USER}:${ARTIFACTORY_APIKEY}@artifactory.corperation.com/artifactory/api/pypi/pip-local/simple"
```

**Comment by yousefissa** [comment] 2020-09-25 21:54
+1 

> What should we do in the case that the url for the private repo contains private username and password? I.E.
> 
> ```
> [[tool.poetry.source]]                                                          
> name = "private"                                                          
> url = "https://${ARTIFACTORY_USER}:${ARTIFACTORY_APIKEY}@artifactory.corperation.com/artifactory/api/pypi/pip-local/simple"
> ```

+1 on this. Any tips for poetry with private user/pass?

**Comment by gghildyal** [comment] 2020-10-08 10:17
With AWS codeartifact repository, the authentication token is a part of the URL, so this becomes even more important to get a smooth CI experience. Currently I am having to add git commits every time the token expires which is every 12 hours :(

**Comment by pawel-ch** [comment] 2020-10-20 09:48
> What should we do in the case that the url for the private repo contains private username and password? I.E.
> 
> ```
> [[tool.poetry.source]]                                                          
> name = "private"                                                          
> url = "https://${ARTIFACTORY_USER}:${ARTIFACTORY_APIKEY}@artifactory.corperation.com/artifactory/api/pypi/pip-local/simple"
> ```

Can't do `poetry update` without this and depend on packages from our repository in local development. And yes – we would like CI to work too.

**Comment by absassi** [comment] 2020-10-20 09:54
@SpicySyntax , @yousefissa , @pawel-ch , see comment above from @loop0 on how this can be scripted:

https://github.com/python-poetry/poetry/issues/208#issuecomment-553480601

**Comment by pawel-ch** [comment] 2020-10-20 10:11
@absassi That doesn't solve the problem of storing credentials from URL in repository (both `pyproject.toml` and `poetry.lock`). Ie. for GitLab it looks like this in `pyproject.toml`:
```toml
[[tool.poetry.source]]
name = "gitlab"
url = "https://__token__:mysecrettoken@gitlab.com/api/v4/projects/42/packages/pypi/simple"
secondary = true
```

And like this in `poetry.lock`:

```toml
[[package]]
name = "my-super-package"
version = "0.1.1"
description = ""
category = "main"
optional = false
python-versions = ">=3.8,<4.0"

[package.dependencies]
dj-database-url = ">=0.5.0,<0.6.0"
Django = ">=3.0.0,<3.1.0"
djangorestframework = ">=3.11.0,<4.0.0"

[package.source]
type = "legacy"
url = "https://__token__:mysecrettoken@gitlab.com/api/v4/projects/42/packages/pypi/simple"
reference = "gitlab"
```

**Comment by abn** [comment] 2020-10-20 10:21
@pawel-ch you can also use the environment variables `POETRY_HTTP_BASIC_GITLAB_USERNAME` and `POETRY_HTTP_BASIC_GITLAB_PASSWORD` if you want to use environment variables instead of the config.

**Comment by GuillaumeLegoy** [comment] 2020-11-11 10:56
> With AWS codeartifact repository, the authentication token is a part of the URL, so this becomes even more important to get a smooth CI experience. Currently I am having to add git commits every time the token expires which is every 12 hours :(

Hello @gghildyal and others. I'm working with AWS CodeArtifact and managed to make it work after struggling a little bit, here is how:

1. In Poetry configure your private repository link as follow (note that in AWS CodeArtifact the below link is available when you click "Connection Instructions" and choose "pip"). Make sure to remove the `aws:$CODEARTIFACT_AUTH_TOKEN` part before the `@`:

```bash
poetry config repositories.<your_private_repository_name> https://<your_private_aws_repository_account>.d.codeartifact.<your_private_aws_repository_region>.amazonaws.com/pypi/<your_private_package_name>/simple/
```

2. Export the `$CODEARTIFACT_AUTH_TOKEN` environment variable. Again AWS CA gives us the command when we check the instructions, as follow:

```bash
export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain <your_private_repository_domain> --domain-owner <your_domain_id> --query authorizationToken --output text`
```

3. Configure the authentication in Poetry for the repository we configured in step 1 (make sure to use the same repo name). Here you can see the `aws` and `$CODEARTIFACT_AUTH_TOKEN` constitutes the part we removed from the AWS CA link before the `@`:

```bash
poetry config http-basic.<your_private_repository_name> aws $CODEARTIFACT_AUTH_TOKEN
```

4. Add your private repository to `pyproject.toml` to be able to install your custom packages (again use the same name we setup in 1.):

```toml
[[tool.poetry.source]]
name = "<your_private_repository_name>"
url = "https://<your_private_aws_repository_account>.d.codeartifact.<your_private_aws_repository_region>.amazonaws.com/pypi/<your_private_package_name>/simple/"
secondary = true
```

5. You can now run `poetry add <your_custom_package> in your project and it should work.

**Comment by gghildyal** [comment] 2020-11-16 22:37
@GuillaumeLegoy Thanks for the writeup! This is exactly what I did for local non-dockerized development. Getting AWS credentials to run ```aws codeartifact``` to get the token inside of a docker container at image build time is a bit trickier though.

**Comment by invokermain** [comment] 2021-01-26 20:25
The documentation around this definitely doesn't help, I can add a repository using CLI (and therefore env variables in a build script), but this repository is only used to publish packages but not source them.

Is the answer to this problem not to expose a CLI command like `poetry config sources.pypiproxy https://mypypi.something.org`?

**Comment by rsazima** [comment] 2021-03-12 04:25
Improving on @GuillaumeLegoy's comment, these days one can take advantage of ENV vars directly, no need to run `poetry config http-basic ...`:

1. Add the repo source to `pyproject.toml`:

```
[[tool.poetry.source]]
name = "<REPOSITORY>"
url = "https://<DOMAIN>-<ACCOUNT_ID>.d.codeartifact.<REGION>.amazonaws.com/pypi/<REPOSITORY>/simple/"
```

2. Setup ENV vars (naming **must** follow the [documentation convention](https://python-poetry.org/docs/configuration/#using-environment-variables)):

```shell
export POETRY_HTTP_BASIC_ REPOSITORY_USER=aws

export POETRY_HTTP_BASIC_ REPOSITORY_PASSWORD=`aws codeartifact get-authorization-token --domain <DOMAIN> --domain-owner <ACCOUNT_ID> --query authorizationToken --output text`
```

**Comment by cognitiaclaeves** [comment] 2021-06-16 14:50
This is a little different from the OP's use-case, but AFIAK, it falls under the heading of support for env variables.

I recently wanted to capture everything that would be needed in a python environment created for working with a particular software package's plugins (OBS). But I was unable to do it with poetry because it requires shared libs. The pyenv equivalent is this:

`CONFIGURE_OPTS=--enable-shared pyenv install 3.9.5`

How can this be implemented with poetry?

**Comment by Li-ReDBox** [comment] 2021-06-29 06:50
Can anyone confirm if this works without config? It does not look like poetry's installer looks for envs and insert them at all to form something like `https://$USER:$PASSWORD@some.private.repo`.
```
export POETRY_HTTP_BASIC_LABS_USER=MY_USER
export POETRY_HTTP_BASIC_LABS_PASSWORD=MYPASS
```
```
[[tool.poetry.source]]
name = "labs"
url = "https://some.private.repo"
secondary = true
```

**Comment by alekseysavitskiy** [comment] 2021-06-29 09:36
@Li-ReDBox  I can confirm that this works fine for me.

**Comment by Li-ReDBox** [comment] 2021-06-30 00:41
@alekseysavitskiy I am not sure what I have missed in my set up or misread the code: https://github.com/python-poetry/poetry/blob/22c3aaddc20ad74d3633738093f685fd6dbb998a/poetry/installation/authenticator.py#L111. It looks like poetry can serve private repo by having creds either in the url or in config. But you and @rsazima must have done it. Very strange.

**Comment by alekseysavitskiy** [comment] 2021-06-30 05:43
@Li-ReDBox check this:
 https://github.com/python-poetry/poetry/blob/22c3aaddc20ad74d3633738093f685fd6dbb998a/poetry/config/config.py#L113

**Comment by Li-ReDBox** [comment] 2021-06-30 06:11
@alekseysavitskiy, my understand is that reading env variables are defined for class Config. Could you please help me to understand if there is no configuration has been set, say I do not have the `setting_name` in the [call](https://github.com/python-poetry/poetry/blob/22c3aaddc20ad74d3633738093f685fd6dbb998a/poetry/config/config.py#L105) in my configuration, will `get` be called? In my current testing setup, I have not run any `poetry config`. 

My gut feeling is that you can set a config key by running `poetry config`, then the value of this key can be overridden by an environmental variable later.

Without config, env variables have not worked in my tests. I may have missed something.

**Comment by reitzig** [comment] 2021-07-08 10:56
FWIW, here's another use case that doesn't work with `poetry config` at all: injecting version numbers at build time.

This is popular in my current environment (Java shop; they have Maven do that). You'd also want to do that if you publish on tag builds.

**Comment by sisp** [comment] 2021-07-08 11:07
@reitzig Specifically for your example use case "publish on tag builds", you can set `version = "0.0.0"` in `pyproject.toml` and when a CI job runs for a tagged commit, you can run `poetry version $CI_COMMIT_TAG` (or however your CI service provides the tag) in the CI job before building the package.

**Comment by jybaek** [comment] 2021-08-09 23:30
any update?

**Comment by akvadrako** [comment] 2021-08-12 12:40
> @reitzig Specifically for your example use case "publish on tag builds", you can set `version = "0.0.0"` in `pyproject.toml` and when a CI job runs for a tagged commit, you can run `poetry version $CI_COMMIT_TAG` (or however your CI service provides the tag) in the CI job before building the package.

That only makes sense if building as part of a CI workflow. In our case we use the git tag as the version but do those builds locally. This doesn't work very well with poetry since updating pyproject.toml after creating a tag then makes the checkout dirty.

**Comment by nikhiljohn10** [comment] 2021-08-31 09:42
I have added one feature request #4458 where this issue is addressed in regards to the implementation part.

**Comment by Greedquest** [comment] 2021-11-04 13:34
I would like this because mypy defines a `$MYPY_CONFIG_FILE_DIR` environment variable which I would like to access in my tooling setup.

```
[tool.mypy]
mypy_path = "$MYPY_CONFIG_FILE_DIR/stubs"
```

This works in mypy.ini but not pyproject.toml

**Comment by kraczak** [comment] 2021-12-02 13:32
I am also interested what is best practice to install libraries from Arifactory using `poetry`. Is there any guide on that?

**Comment by timorkal** [comment] 2022-06-23 08:44
For me this could help in the following scenario:
I want my pyproject.toml to behave differently in my ci pipe (dev vs prod).
For example I want for dev ci, the pyproject.toml will have this dependency:
xxxxxxxxx = { version = "^1", allow-prereleases = true }
While in the prod ci, the dependency will look like this:
xxxxxxxxx = { version = "^1", allow-prereleases = false }

So if I could use some ENV_VAR like $ALLOW_PRERELEASES configured in the toml file like this:
xxxxxxxxx = { version = "^1", allow-prereleases = $ALLOW_PRERELEASES }
I could easily handle it.
Now I need to use commands like sed, to overcome this obstacle.

**Comment by blabaschin** [comment] 2022-07-02 22:14
For code artifact this most certainly doesn't work.

The entire conceit behind the environment variables is to avoid adding sensitive information such as one's account number or domain name. I've read the solutions above but they still stick that sensitive info in the pyproject.toml, which would compromise security upon commit to a repo.

**Comment by adamwojt** [comment] 2022-08-09 11:36
This seems like a useful thing. For example it enables to have this:
```company-common = {path = ${LOCAL_PATH_TO_REPO}, develop = true}```
This can be left commented and in VCS and people in company can un-comment it to switch to development mode.

**Comment by neersighted** [comment] 2022-10-04 01:57
This is explicitly out of scope for Poetry -- `pyproject.toml` is declarative, and it's not just Poetry that makes it that way. With support for [PEP 621](https://peps.python.org/pep-0621/) this will be a hard constraint and not just a Poetry-enforced decision, but it's also worth noting that allowing for any sort of environment interpolation in pyproject.toml will break the ability of your project to be understood and installed by most other tools which likely will not have the correct variables available.

It's better to determine what specific functionality people are looking to compute dynamically and look at them individually -- many can be implemented as plugins or small standalone features.

**Closed by neersighted** 2022-10-04 01:57 UTC
Labels: kind/feature

**Comment by rossamurphy** [comment] 2024-01-09 12:41
have the poetry developers seen sense yet and decided to implement this feature that everyone is crying out for? or are we still waiting for the pedantic arguments to end?

**Comment by bubthegreat** [comment] 2024-01-09 17:24
> This is explicitly out of scope for Poetry -- `pyproject.toml` is declarative, and it's not just Poetry that makes it that way. With support for [PEP 621](https://peps.python.org/pep-0621/) this will be a hard constraint and not just a Poetry-enforced decision, but it's also worth noting that allowing for any sort of environment interpolation in pyproject.toml will break the ability of your project to be understood and installed by most other tools which likely will not have the correct variables available.
> 
> It's better to determine what specific functionality people are looking to compute dynamically and look at them individually -- many can be implemented as plugins or small standalone features.

How does that PEP block anything?  There's a section that's specifically for configuring your tools: 
https://packaging.python.org/en/latest/specifications/pyproject-toml/#arbitrary-tool-configuration-the-tool-table

> The [tool] table is where any tool related to your Python project, not just build tools, can have users specify configuration data as long as they use a sub-table within [tool], e.g. the [flit](https://pypi.python.org/pypi/flit) tool would store its configuration in [tool.flit].

Why would we not leverage the `[tool]` section for configurations like this?  It supports arrays, lists, and other mixed values that can be dumped into the os.environ during poetry run for things like unit tests, or it could be injected into the virtual environment - it's been years that folks have been requesting this - are the devs at least open to PR proposals for this?

**Comment by rterbush** [comment] 2024-01-30 14:41
Not understanding why this is closed...

Simple use case:
1. Team of poetry users wants to be able to install a dependency in a local directory and each team member has that local dependency at a different PATH on local disk. 

Solution seems to be that each member sets an environment variable where that code is located on their local disk so that the pyproject.toml can just specify `foobar = {path = $MODSRC}`

**Comment by scottrbrtsn-ata-llc** [comment] 2024-02-14 16:11
😩 

The number of times I look for the thing I want and find something like this.

**Comment by scottrbrtsn-ata-llc** [comment] 2024-02-14 16:35
.envrc and direnv seem like a good alternative tho.

**Comment by danb27** [comment] 2024-03-14 04:51
please?

**Comment by neersighted** [comment] 2024-03-14 14:01
> Why would we not leverage the [tool] section for configurations like this? It supports arrays, lists, and other mixed values that can be dumped into the os.environ during poetry run for things like unit tests, or it could be injected into the virtual environment - it's been years that folks have been requesting this - are the devs at least open to PR proposals for this?

> .envrc and direnv seem like a good alternative tho.

You both are misunderstanding the issue, which is asking for environment variable interpolation in pyproject.toml, and not environment variable declaration for e.g. `poetry run`.

In any case, PEP 621 does preclude this, unless we fall back to `dynamic` and the old project format, which I think we are unlikely to extend at this time.

**Comment by scottrbrtsn** [comment] 2024-03-14 14:38
Ah, I see the distinction.  Sorry for the spam.

**Comment by loop0** [comment] 2024-03-14 14:42
Yeah, I opened this ticket in the past because I was trying to solve the authentication problem with private repositories during CI/CD. And I was able to achieve that in a different way, as I wrote in here:
https://github.com/python-poetry/poetry/issues/208#issuecomment-553480601

**Comment by danb27** [comment] 2024-03-14 14:49
> Yeah, I opened this ticket in the past because I was trying to solve the authentication problem with private repositories during CI/CD. And I was able to achieve that in a different way, as I wrote in here:
> https://github.com/python-poetry/poetry/issues/208#issuecomment-553480601

Am I missing something, or does this still not end up with your private repository URL in both pyproject.toml and poetry.lock? 

I have figured out how to push to and download from my private repository, but not without having the url committed in at least one of these files (but again, could totally be missing something).
