### ISSUE TITLE
Poetry installation fails. Windows 10, python39

### ISSUE THREAD

**Issue by bmosier** [python-poetry/poetry#3388] opened 2020-11-19 22:27 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10 Education edition
- **Poetry version**: 1.1.4
- **Link of a [Gist] with the contents of your pyproject.toml file**: N/A
- **Python version**: 3.9
## Issue
Poetry install fails on windows 10, both recommended installation (powershell) and Pip installation fail. Both methods have been tried in user and admin powershell consoles. My $PATH is correct.

```
PS C:\Users\me\workspace> (Invoke-WebRequest -Uri https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py -UseBasicParsing).Content | python -
Retrieving Poetry metadata

Welcome to Poetry!
... ... ... omitted
Installing version: 1.1.4
  - Downloading poetry-1.1.4-win32.tar.gz (38.82MB)
Traceback (most recent call last):
  File "<stdin>", line 1086, in <module>
  File "<stdin>", line 1082, in main
  File "<stdin>", line 362, in run
  File "<stdin>", line 529, in install
  File "<stdin>", line 676, in make_bin
  File "<stdin>", line 665, in _which_python
RuntimeError: No python executable found in shell environment. Tried: ['python', 'python3', 'py.exe -3', 'py.exe -2']
PS C:\Users\me\workspace> python --version
Python 3.9.0

PS C:\Users\me\workspace> pip install poetry --no-cache
... ... ... omitted
Installing collected packages: tomlkit, pylev, pastel, clikit, cleo, msgpack, lockfile, cachecontrol, poetry-core, cachy, filelock, appdirs, distlib, virtualenv, shellingham, webencodings, html5lib, pkginfo, poetry
    Running setup.py install for msgpack ... done
  WARNING: Failed to write executable - trying to use .deleteme logic
ERROR: Could not install packages due to an EnvironmentError: [WinError 2] The system cannot find the file specified: 'c:\\python39\\Scripts\\doesitcache.exe' -> 'c:\\python39\\Scripts\\doesitcache.exe.deleteme'
```
The powershell installation method tells me that it is unable to find my python executable, but it is certainly in my global PATH.
Using the Pip installation method will result in it being unable to find an exe in "python39/scripts". Running the pip installation again it tells me it can't find a different exe before installation terminates. Indeed, these executables are not in that directory.

These installation methods will place a .poetry directory skeleton in my home, but will not place an executable for poetry in .poetry/bin

**Comment by awburgess** [comment] 2020-11-20 14:59
I'm experiencing the same issue:

- OS version and name: Windows 10
- Poetry version: 1.1.4 (also tried 1.0.10)
- Link of a [Gist] with the contents of your pyproject.toml file: N/A
- Python version: 3.7.9

I can confirm that my python executable is on my `PATH` and I've tried setting `PYTHON_PATH`.

**Comment by jamilraichouni** [comment] 2020-12-06 00:05
Took also an hour for me to get poetry installed on Win10.
In the end the root cause is in

https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py, line 639 where the method
`def _which_python(self):` is defined. Had no time to investigate but the very dirty hack

```python
def _which_python(self):
    return r"C:\python\python38\python.exe"
```

fixed to be able to install poetry.

**Comment by mnslarcher** [comment] 2021-01-27 12:01
Same problem here :(

**Comment by eapetitfils** [comment] 2021-02-12 10:58
I had the same problem on one machine, but not an another. The fix I used was to remove `,shell=True` from the subprocess command [line 651](https://github.com/python-poetry/poetry/blob/cc195f1dd086d1c4d12a3acc8d6766981ba431ac/get-poetry.py#L651)

It ended up working for me but this could break other use cases.

**Comment by eapetitfils** [comment] 2021-02-12 16:15
I fixed the issue properly on my side, this was not a poetry problem, but rather an old installation of Anaconda not properly cleaned up.

Basically, whenever I was starting a command prompt in Windows, there was a message `The system cannot find the path specified.`. I was not alarmed as everything else was working. However, it does change the exit status to 1 instead of 0 when calling something with subprocess if using `shell=True`. You can reproduce the same error directly in the command prompt by doing:

```
cmd.exe /c "python --version"
echo %errorlevel%
```
![Command Prompt Bug Check](https://user-images.githubusercontent.com/1508017/107792644-40159e00-6d4d-11eb-901e-8d5b0dd853c4.jpg)

The way I fixed it is described on [StackOverflow](https://stackoverflow.com/a/13343337):
Open regedit.exe, navigate to `Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Command Processor` and make sure the value of the Autorun key exists. If not, clear the value. In my case, I had an entry for an Anaconda batch file that did not exist anymore.

While this error is not related to Poetry, maybe it would be interested to document it if the root cause is similar for other people.

**Comment by KyryloKaralyus** [comment] 2021-02-13 20:36
this is still a thing :C

**Comment by Dragonlord1005** [comment] 2021-04-08 01:17
Same here, bit different, but still preventing me from using poetry

**Comment by danielbellhv** [comment] 2022-06-29 13:32
I've a similar issue but with a different effect - [Git Issue](https://github.com/python-poetry/poetry/issues/5930)

**Comment by dimbleby** [comment] 2022-07-02 14:08
get-poetry.py is now deprecated, not much point in keeping this one open

**Comment by kitchoi** [comment] 2022-09-06 09:56
I am afraid this issue is still valid with Poetry 2.0 and Python 3.8, on Windows 2022.
The following was captured from running the new Poetry install script on GitHub Actions (windows-2022) self-hosted instance:
```
$ curl -sSL https://install.python-poetry.org/ | python -
  shell: C:\Program Files\Git\bin\bash.EXE --noprofile --norc -e -o pipefail {0}
  env:
    PYTHON_VERSION: 3.8
    pythonLocation: C:\hostedtoolcache\windows\Python\3.8.10\x64
Retrieving Poetry metadata

# Welcome to Poetry!

This will download and install the latest version of Poetry,
a dependency and package manager for Python.

It will add the `poetry` command to Poetry's bin directory, located at:

C:\Users\runneradmin\AppData\Roaming\Python\Scripts

You can uninstall at any time by executing this script with the --uninstall option,
and these changes will be reverted.

Installing Poetry (1.2.0)
Installing Poetry (1.2.0): Creating environment
Installing Poetry (1.2.0): An error occurred. Removing partial environment.
Traceback (most recent call last):
  File "<stdin>", line 930, in <module>
  File "<stdin>", line 909, in main
  File "<stdin>", line 545, in run
  File "<stdin>", line 566, in install
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "<stdin>", line 638, in make_env
  File "<stdin>", line 624, in make_env
  File "<stdin>", line 314, in make
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\venv\__init__.py", line 68, in create
    self._setup_pip(context)
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\venv\__init__.py", line 289, in _setup_pip
    subprocess.check_output(cmd, stderr=subprocess.STDOUT)
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\subprocess.py", line 1311, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by neersighted** [comment] 2022-09-06 13:26
@kitchoi this is for a different installer -- I am going to close this.

Could you please open a new issue on https://github.com/python-poetry/install.python-poetry.org with more instructions on how to reproduce the issue you're having on Windows? Thanks!

**Closed by neersighted** 2022-09-06 13:26 UTC
Labels: kind/bug, status/triage

**Comment by systematicguy** [comment] 2022-10-18 02:40
@kitchoi  I had the same issue when trying to pipe into `python3`, and solved this simply piping into `python`. I am using pyenv-win, my global python is 3.9.6. 
I need to install poetry behind a proxy, so I use `$webClient.DownloadString("https://install.python-poetry.org") | python`
^ this is where I had to use `python` instead of `python3` although both work via the same pyenv-win-managed installation.

**Comment by neersighted** [comment] 2022-10-18 02:45
python-poetry/install.python-poetry.org#46
