### ISSUE TITLE
Install correct local Poetry version

### ISSUE THREAD

**Issue by fhaque** [python-poetry/poetry#1738] opened 2019-12-13 22:38 UTC
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

There was an issue by someone else that recently closed about this and so I raise it: Set the version of Poetry in, for example, the `poetry.toml` file that fixes the version of Poetry to use for the project.

I ran into this issue because I use Poetry as part of my build processes and the version of Poetry changed and caused build issues. Also, I'm sure sharing Poetry projects in teams would be easier with version locking of Poetry.

**Comment by finswimmer** [comment] 2022-03-26 06:50
Duplicate of https://github.com/python-poetry/poetry/issues/3316

**Closed by finswimmer** 2022-03-26 06:50 UTC
Labels: Feature
