### ISSUE TITLE
Unable to resolve simple case w/o a hint on version

### ISSUE THREAD

**Issue by sandroden** [python-poetry/poetry#2171] opened 2020-03-10 22:13 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) (1.0.5) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Linux Ubuntu 19.10
- **Poetry version**: 1.0.5

## Issue
Startin with an empty project and setting python version to ^3.5 as in

```
[tool.poetry]
name = "testipy"
version = "0.1.0"
description = ""
authors = ["Sandro...]

[tool.poetry.dependencies]
python = "^3.5"
```
Now add request for ipython, it won't be resolved, adding the hint ipython=^7 will be resolved:

```
$ poetry add ipython --dry-run 
/home/sandro/.poetry/lib/poetry/_vendor/py2.7/subprocess32.py:149: RuntimeWarning: The _posixsubprocess module is not being used. Child process reliability may suffer if your program uses threads.
  "program uses threads.", RuntimeWarning)
The currently activated Python version 2.7.17 is not supported by the project (^3.5).
Trying to find and use a compatible version. 
Using python3 (3.7.5)
Using version ^7.13.0 for ipython

Updating dependencies
Resolving dependencies... (0.0s)

[SolverProblemError]
The current project's Python requirement (^3.5) is not compatible with some of the required packages Python requirement:
  - ipython requires Python >=3.6

Because no versions of ipython match >7.13.0,<8.0.0
 and ipython (7.13.0) requires Python >=3.6, ipython is forbidden.
So, because testipy depends on ipython (^7.13.0), version solving failed.
```

The temporary solution is to add a hint on the version:

```
$ poetry add ipython^7 --dry-run 
/home/sandro/.poetry/lib/poetry/_vendor/py2.7/subprocess32.py:149: RuntimeWarning: The _posixsubprocess module is not being used. Child process reliability may suffer if your program uses threads.
  "program uses threads.", RuntimeWarning)
The currently activated Python version 2.7.17 is not supported by the project (^3.5).
Trying to find and use a compatible version. 
Using python3 (3.7.5)

Updating dependencies
Resolving dependencies... (1.3s)


Package operations: 14 installs, 0 updates, 0 removals, 2 skipped

  - Installing decorator (4.4.2)
  - Installing ipython-genutils (0.2.0)
  - Installing parso (0.6.2)
  - Installing ptyprocess (0.6.0)
  - Installing six (1.14.0)
  - Installing wcwidth (0.1.8)
  - Skipping appnope (0.1.0) Not needed for the current environment
  - Installing backcall (0.1.0)
  - Skipping colorama (0.4.3) Not needed for the current environment
  - Installing jedi (0.16.0)
  - Installing pexpect (4.8.0)
  - Installing pickleshare (0.7.5)
  - Installing prompt-toolkit (2.0.10)
  - Installing pygments (2.6.1)
  - Installing traitlets (4.3.3)
  - Installing ipython (7.9.0)
```
This time poetry correctly picks 7.9 that is the last release that supported Python3.5. It seems to me that is should have been able to get it even w/o any release constraint. I may not event know which is the last major that supported that python version.

**Comment by mkniewallner** [comment] 2022-09-18 02:02
Duplicate of #707.

**Closed by mkniewallner** 2022-09-18 02:02 UTC
Labels: kind/bug, area/solver, status/duplicate
