### ISSUE TITLE
pip install/download non-binary package failed with err 'ModuleNotFoundError: No module named 'clikit'

### ISSUE THREAD

**Issue by lafrinte** [python-poetry/poetry#2994] opened 2020-09-29 10:44 UTC
get exception `ModuleNotFoundError: No module named 'clikit'`  during pip install with --no-binary argument

```
[root@677f57edf4fd tmp]# pip3 install 'poetry>=1.0.0' --no-binary :all: -i https://mirrors.aliyun.com/pypi/simple/
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Collecting poetry>=1.0.0
  Using cached https://mirrors.aliyun.com/pypi/packages/8e/f8/ee9590a110aa5f9de86e8de6b6f623f4bd5eb8610b719d21cea5d794fd98/poetry-1.0.10.tar.gz (168 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python3.7 /usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpsb8ohx5q
       cwd: /tmp/pip-install-1jspvvyn/poetry
  Complete output (36 lines):
  Traceback (most recent call last):
    File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-04ep172n/overlay/lib/python3.7/site-packages/intreehooks.py", line 53, in get_requires_for_build_wheel
      return self._backend.get_requires_for_build_sdist(config_settings)
    File "/tmp/pip-build-env-04ep172n/overlay/lib/python3.7/site-packages/intreehooks.py", line 38, in _backend
      obj = self._module_from_dir(modname)
    File "/tmp/pip-build-env-04ep172n/overlay/lib/python3.7/site-packages/intreehooks.py", line 25, in _module_from_dir
      mod = importlib.import_module(modname)
    File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
    File "<frozen importlib._bootstrap>", line 983, in _find_and_load
    File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
    File "<frozen importlib._bootstrap>", line 983, in _find_and_load
    File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 728, in exec_module
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    File "/tmp/pip-install-1jspvvyn/poetry/poetry/masonry/__init__.py", line 10, in <module>
      from .builder import Builder
    File "/tmp/pip-install-1jspvvyn/poetry/poetry/masonry/builder.py", line 1, in <module>
      from .builders.complete import CompleteBuilder
    File "/tmp/pip-install-1jspvvyn/poetry/poetry/masonry/builders/__init__.py", line 1, in <module>
      from .complete import CompleteBuilder
    File "/tmp/pip-install-1jspvvyn/poetry/poetry/masonry/builders/complete.py", line 6, in <module>
      from poetry.factory import Factory
    File "/tmp/pip-install-1jspvvyn/poetry/poetry/factory.py", line 10, in <module>
      from clikit.api.io.io import IO
  ModuleNotFoundError: No module named 'clikit'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/bin/python3.7 /usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpsb8ohx5q Check the logs for full command output.
```
```
[root@677f57edf4fd tmp]# python3 -c "from clikit.api.io.io import IO"
[root@677f57edf4fd tmp]#
```

* env:

```
[root@677f57edf4fd tmp]# python3 -V
Python 3.7.2
[root@677f57edf4fd tmp]# pip3 --version
pip 20.2.3 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)
```

**Comment by abn** [comment] 2020-09-29 12:45
Duplicate of #1975. (https://github.com/python-poetry/poetry/issues/1975#issuecomment-693619643)

**Closed by abn** 2020-09-29 12:45 UTC
