### ISSUE TITLE
github action may fail when use the [package.source] in poetry.lock

### ISSUE THREAD

**Issue by youngquan** [python-poetry/poetry#2151] opened 2020-03-08 16:36 UTC
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Issue

I am from China. Because `https://pypi.org/simple` is too slow for me to download package, I often use a pypi mirror. I add cofigurations below to speed up:

```toml
[[tool.poetry.source]]
name = "tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
default = false
```
Recently, I have used Poetry to manage a python project named [goldenmask](https://github.com/youngquan/goldenmask) on Github. However, because the `poetry.lock` file was pushed to the repository, `poetry install` would try to fetch packages from the pypi mirror located in China. These is unnecessary, and **I have to delete the file `poetry.lock` and the cofigurations above**, so github actions could work.

This maybe unreasonable I think, so is there a better solution for developers in China? Could someone give me some advice?

**Comment by Trim21** [comment] 2020-03-18 04:35
you can set mirror in pip config file like `/etc/pip.conf` for you mirror. when poetry call pip to install packages, pip will try to install from mirror instead of pypi. There is no need to add source section in pyproject.toml

**Comment by youngquan** [comment] 2020-03-18 14:27
Thanks for your reply. I have already set the `global.index-url` using `pip config set`：

```bash
$ pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple/
Writing to /root/.config/pip/pip.conf

$ pip config get global.index-url
https://pypi.tuna.tsinghua.edu.cn/simple/
```

However, when I tried to use poetry to add a package, pip was still using `https://pypi.org/simple`, because it was too slow to resolving dependencies. 

I also tried to set mirror in pip config file like `/etc/pip.conf` in old way, however it still did not work:

```bash
$ cat /etc/pip.conf 
[global] 
index-url = https://pypi.tuna.tsinghua.edu.cn/simple/
```

Is there some way to know which pypi mirror that poetry was using? Besides, even I can set the pypi mirror, the `poetry.lock` would still contian information of the pypi mirror I set. I had to delete  the file `poetry.lock` again when I was using github actions, I do not know whether this was reasonable?

Here are the version of poetry:

```bash
$ poetry --version
Poetry version 1.0.5
```

**Comment by Trim21** [comment] 2020-03-18 15:11
no, pip is not using pypi.

poetry is issuing http requests to pypi json api to resolve deps.

I'm not sure if poetry could use json api of mirrors.

I'm doing it this way but I can't find anything about my pypi mirror in my poetry.lock...

**Comment by youngquan** [comment] 2020-03-18 15:23
So when I set pypi mirror in `/etc/pip.conf`, where did poetry try to resolve deps from? From `https://pypi.org/simple` or from `https://pypi.tuna.tsinghua.edu.cn/simple/` ? If I set `[[tool.poetry.source]]` in pyproject.toml, it will be very fast to resolve deps ! 

Here is a picture show how slow the poetry is, when I did set pypi mirror in `/etc/pip.conf`:
![image](https://user-images.githubusercontent.com/8924378/76976664-3df56480-696f-11ea-8dfa-addb5018eaca.png)

**Comment by Trim21** [comment] 2020-03-18 15:50
From pypi, because I often got requests failure exceptions showing host is pypi.
I never wait to resolve whole project, either...
I start from empty pyproject.toml and add deps one by one, to let poetry catch more and more requests.

**Comment by youngquan** [comment] 2020-03-18 15:58
I see! So poetry use pypi json api to resolve deps, and download packages from pypi mirror in `pip.conf`, is that right?

Thanks for your time!

I did start from an empty pyproject.toml and add the `click` package 1 hours ago, poetry has not finished yet:

![image](https://user-images.githubusercontent.com/8924378/76980359-0ccb6300-6974-11ea-9125-3ce26ad585dd.png)

It is so frustrating, so I still have to set `[[tool.poetry.source]]` in pyproject.toml ???!!!

**Comment by NateScarlet** [comment] 2020-03-27 06:58
Related to #1632

**Comment by sinoroc** [comment] 2021-05-01 18:24
@youngquan There is a PR that could help solve this issue. Would you be able to test it, give feedback? https://github.com/python-poetry/poetry/pull/3624

**Comment by neersighted** [comment] 2022-10-04 01:28
Closing as a specialized duplicate of #1632

**Closed by neersighted** 2022-10-04 01:28 UTC
