### ISSUE TITLE
Poetry install two version of pandas library at the same time

### ISSUE THREAD

**Issue by Markovvn1w** [python-poetry/poetry#8407] opened 2023-09-05 11:38 UTC
- **Poetry version**: 1.6.1
- **Python version**: 3.9.17
- **OS version and name**: Ubuntu 22.04 and docker image (python:3.9)[https://hub.docker.com/_/python]

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
When installing a package with special dependencies and extras, poetry fails and decides to install two versions of pandas library at the same time (causing the library to fail).

## Steps to Reproduce
1. Use clear ubuntu with python 3.9 (or docker image python:3.9)
2. Install poetry 1.6.1
3. Create new project:
   ```bash
   poetry new test && cd test && python -m venv .venv && source .venv/bin/activate
   ```
5. Create new nested package with `setup.py`:
   ```bash
   mkdir mypackage
   echo 'from setuptools import setup;setup(name="mypackage",install_requires="pandas>=1.0",extras_require={"all": "pandas<1.6.0"})' > mypackage/setup.py
   ```
6. Install created package to the poetry project: 
   ```bash
   poetry add ./mypackage/ --extras all
   ```
8. Wait for poetry to install two versions of pandas at the same time:
![image](https://github.com/python-poetry/poetry/assets/144119767/d40b0b64-f92c-4d7a-b707-f5c06a386d45)
9. Check that there are indeed two versions of pandas installed: `poetry show`
![image](https://github.com/python-poetry/poetry/assets/144119767/b878f74f-1f83-41df-bbb9-34782a9f3aa6)
10. Check that pandas is broken: `python -c "import pandas"` (Each time there is a different error. if one library is downloaded much faster than the second, there is no error at all):
![image](https://github.com/python-poetry/poetry/assets/144119767/b4c8c5fa-ea38-40ca-a429-106c36ae770c)

## Expected behavior
When installing the `mypackage` nested package with extras=all, the pandas library has two restrictions: pandas>=1.0 and pandas<1.6.0. So I expect poetry to install the latest possible version of pandas (1.5.3)

**Comment by Markovvn1w** [comment] 2023-09-05 11:39
Maybe related to #4703?

**Comment by Markovvn1w** [comment] 2023-09-05 13:40
This was a minimal reproducible example. The most common example uses two extras, where one extras requires pandas<1.6.0 and the other pandas>=1.0. If you install each extras separately, everything is fine. However, when installing them together poetry installs two versions of pandas again.

Use the following setup.py to get this example:
```python
from setuptools import setup
setup(name="mypackage",extras_require={"all": "pandas<1.6.0", "something": "pandas>=1.0"})
```

Use both extras to install nested package:
```bash
poetry add ./mypackage/ --extras all --extras something
```

**Comment by Markovvn1w** [comment] 2023-09-05 13:50
However, if dependencies are added via intermediate packages, poetry works correctly. For example, the `statsmodels` package depends on `pandas>=1.0`. If we replace `pandas>=1.0` with `statsmodels` in our nested package, poetry will correctly install only one version of pandas (1.5.3).
![image](https://github.com/python-poetry/poetry/assets/144119767/bc16ea2d-8340-4ae9-b7e9-2ffbca0c32da)

However, if statsmodels had extras with a restriction to pandas<1.6.0, then poerty would again install two versions at the same time.

**Comment by radoering** [comment] 2023-09-05 14:56
Might be a duplicate of #8380. Please try if the PR that resolves that issue also resolves your issue.

**Closed** 2023-11-03 16:09 UTC
Labels: kind/bug, status/duplicate
