### ISSUE TITLE
`$ poetry update` failes when there is [[tool.poetry.source]] source

### ISSUE THREAD

**Issue by wiltso** [python-poetry/poetry#5637] opened 2022-05-18 13:35 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 21.10 (64-bit)
- **Poetry version**: 1.2.0b1
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/wiltso/64f597cdb30dce0f61166efc84d2a781

## Issue
First here is the stack trace of the issue: https://gist.github.com/wiltso/f06c06987d199e440e1cd257b4fcdcb7

The error only happens when I there is [[tool.poetry.source]] in the pyproject.toml file. If I remove the source everything works fine.

**Comment by wiltso** [comment] 2022-05-19 09:15
I have done that both with python 3.9 and 3.10.

**Comment by wiltso** [comment] 2022-05-19 10:09
The `-vvv` output is in the original post.
I have not tried installed the master version.

**Comment by abn** [comment] 2022-05-19 10:17
Unless I'm missing something, you have only posted the stack trace. Or are you saying that is all you are getting?

**Comment by wiltso** [comment] 2022-05-19 10:19
Yea this "First here is the stack trace of the issue: https://gist.github.com/wiltso/f06c06987d199e440e1cd257b4fcdcb7" is the hole `-vvv` output

**Comment by abn** [comment] 2022-05-19 11:44
This is a duplicate of #3628 #4311 #3625. The root cause here seems to be stray installations (empty dist-info/egg-info) directories in site-packages of the virtual environment used by the project.

Unable to reproduce this issue in a clean environment.

```sh
podman run --rm -i --entrypoint bash docker.io/ubuntu:21.10 <<EOF
set -xe
export DEBIAN_FRONTEND=noninteractive
apt-get -yqq update
apt-get -yqq install python3 python3-pip curl
python3 -m pip install --disable-pip-version-check -q --pre poetry
poetry --version
install -d foobar
pushd foobar
curl -sL --output pyproject.toml https://gist.githubusercontent.com/wiltso/64f597cdb30dce0f61166efc84d2a781/raw/fdaedb6b2e1dd426d7ffc2d95a485b1b0786f3df/toml
poetry install
poetry update
EOF
```

<details>
<summary><b>console output:</b></summary>
<p>

```console
+ export DEBIAN_FRONTEND=noninteractive
+ DEBIAN_FRONTEND=noninteractive
+ apt-get -yqq update
+ apt-get -yqq install python3 python3-pip curl
...
Processing triggers for libc-bin (2.34-0ubuntu3.2) ...
Processing triggers for ca-certificates (20210119ubuntu1) ...
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
+ python3 -m pip install --disable-pip-version-check -q --pre poetry
+ poetry --version
Poetry (version 1.2.0b1)
+ install -d foobar
/foobar /
+ pushd foobar
+ curl -sL --output pyproject.toml https://gist.githubusercontent.com/wiltso/64f597cdb30dce0f61166efc84d2a781/raw/fdaedb6b2e1dd426d7ffc2d95a485b1b0786f3df/toml
+ poetry install
Creating virtualenv testing-lWDpn5M1-py3.9 in /root/.cache/pypoetry/virtualenvs
Updating dependencies
Resolving dependencies...

Writing lock file
+ poetry update
Updating dependencies
Resolving dependencies...
```

</p>
</details>

**Comment by abn** [comment] 2022-05-19 11:44
Closing as a duplicate of #3628 as it has more information.

**Closed by abn** 2022-05-19 11:44 UTC
Labels: Awaiting Reponse
