### ISSUE TITLE
How to upgrade Python version from 3.8.2 to 3.8.5 for an existing poetry environment?

### ISSUE THREAD

**Issue by joyofdata** [python-poetry/poetry#2827] opened 2020-08-18 10:51 UTC
How to upgrade Python version for existing poetry environment?

- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Issue
I manage Python versions via pyenv. But I can't convince poetry to load Python 3.8.5 when the environment is activated. It keeps using 3.8.2.

```
➜  my-project python -V
Python 3.8.5

➜  my-project pyenv versions
* 3.8.5 (set by /home/raffael/PycharmProjects/my-project/.python-version)

➜  my-project poetry shell 
Spawning shell within /home/raffael/.cache/pypoetry/virtualenvs/my-project-L-QBB5_N-py3.8

➜  my-project . /home/raffael/.cache/pypoetry/virtualenvs/my-project-L-QBB5_N-py3.8/bin/activate

(my-project-L-QBB5_N-py3.8) ➜  my-project python -V
Python 3.8.2

(my-project-L-QBB5_N-py3.8) ➜  my-project pyenv shell 3.8.5

(my-project-L-QBB5_N-py3.8) ➜  my-project pyenv local 3.8.5

(my-project-L-QBB5_N-py3.8) ➜  my-project python -V
Python 3.8.2

(my-project-L-QBB5_N-py3.8) ➜  my-project poetry env use 3.8.5
Using virtualenv: /home/raffael/.cache/pypoetry/virtualenvs/my-project-L-QBB5_N-py3.8

(my-project-L-QBB5_N-py3.8) ➜  my-project python -V           
Python 3.8.2
```

**Comment by finswimmer** [comment] 2020-08-18 18:48
Hello @joyofdata,

I believe at the moment `poetry` doesn't take the patch version into account, when checking if there already a venv exists for it. 

fin swimmer

**Comment by joyofdata** [comment] 2020-08-24 17:04
Isn't that a tiny bit ironic that a dependency management system for Python cannot manage the most central dependency - that of the interpreter itself?

**Comment by Zaffer** [comment] 2021-06-25 21:37
Apparently pyenv uses shivs to intercept and reference to python so that it can point to its versions, but this doesn't work when poetry calls python. In my case it is using the default system python version 3.8.5 when the global pyenv version I have is 3.8.10. There is no way for me to change the version poetry uses the version I set using pyenv.

Please can poetry link with pyenv somehow so that poetry uses the pyenv version I set as default?

**Comment by AntonOfTheWoods** [comment] 2022-01-25 00:50
@Zaffer except I want `asdf` not `pyenv`... which is why I guess it is the way it is. Everything should be able to be thrown away and recreated quickly, which is why remove -> create is how it is supposed to be done I guess!

**Comment by finswimmer** [comment] 2022-10-05 13:10
Duplicate of https://github.com/python-poetry/poetry/issues/2619

**Closed by finswimmer** 2022-10-05 13:10 UTC
Labels: kind/feature
