### ISSUE TITLE
Unable to install "farm-haystack[colab,preprocessing,elasticsearch,inference]" but dependency not avaliable

### ISSUE THREAD

**Issue by rtest2344** [python-poetry/poetry#8496] opened 2023-10-02 22:05 UTC
- **Poetry version**: 1.6.1
- **Python version**: 3.10.0
- **OS version and name**: OSX Ventura 13.5.2
- **pyproject.toml**: https://gist.github.com/rtest2344/1e3ff827132ffe47aef33f313a3675e7

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
I am able to run `poetry add "farm-haystack[colab,preprocessing,elasticsearch,inference]"` without any issue and all the dependancies are written to the `poetry.lock` file as expected; however, `elasticsearch` is not installed into the env being used.

For `farm-haystack = {extras = ["elasticsearch", "inference", "preprocessing"], version = "^1.21.0"}` the required elasticsearch version is 7.17.9 and is writen to the lock file approperatly, just not installed. 

In order to fix this, you have to run `poetry add elasticsearch==7.17.9` and then it is installed into the env. Not quite sure if this is a poetry error or somewhere else - please advise. thank you.

**Comment by clintonroy** [comment] 2023-10-02 22:43
Works for me, you're going to have to give more details.

I did have to install some jpeg headers to get pillow to compile, are you sure the poetry add worked flawlessly? There's a reason we ask for logs.

**Comment by dimbleby** [comment] 2023-10-03 09:22
puzzled by that reply: so far as I can see this `pyproject.toml` does not install any `elasticsearch`.

however this looks like a duplicate of https://github.com/python-poetry/poetry/issues/7646: poetry does not support the construction where a package uses extras to install itself with more extras - which is [what `farm-haystack` is doing](https://github.com/deepset-ai/haystack/blob/29acd3c57680049976457f2ece2618d30d41b55a/pyproject.toml#L105-L107).

please close

**Comment by rtest2344** [comment] 2023-10-03 12:23
> puzzled by that reply: so far as I can see this `pyproject.toml` does not install any `elasticsearch`.
> 
> however this looks like a duplicate of #7646: poetry does not support the construction where a package uses extras to install itself with more extras - which is [what `farm-haystack` is doing](https://github.com/deepset-ai/haystack/blob/29acd3c57680049976457f2ece2618d30d41b55a/pyproject.toml#L105-L107).
> 
> please close

Didn't see that ticket, thanks @dimbleby . WIll close the ticket.

**Comment by dimbleby** [comment] 2023-10-03 13:30
feel free to submit a merge request with improvement

either way this one can be safely closed: the existing issue is sufficient to track this

**Closed** 2023-10-03 13:35 UTC
Labels: kind/bug, status/triage
