### ISSUE TITLE
Problem vendoring subprocess32 in Ubuntu

### ISSUE THREAD

**Issue by sklarsa** [python-poetry/poetry#1257] opened 2019-07-26 21:11 UTC
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **Ubuntu 16.04/18.04**: 

## Issue
I'm building a Dockerfile and am seeing a RuntimeWarning after running any poetry command that works with the venv.  Since I'm using  poetry to run a web server (gunicorn), I'm worried that this could have a negative impact on app performance.  I haven't seen this before, so it appears to have been introduced recently?

The warning:
```
/root/.poetry/lib/poetry/_vendor/py2.7/subprocess32.py:149: RuntimeWarning: The _posixsubprocess module is not being used. Child process reliability may suffer if your program uses threads.
  "program uses threads.", RuntimeWarning)
```

I installed poetry using the `get-poetry.py` script, and have even updated to the latest version.  Here is the Dockerfile that I'm using, and the relevant output:
```
FROM ubuntu:16.04
RUN apt-get update && apt-get install -y \
    software-properties-common \
    curl \
    htop \
    python \
    python-dev \
    wget
RUN curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
ENV PATH=$PATH:/root/.poetry/bin
RUN poetry self:update --preview
RUN poetry version
```

And the output for the final command...
```
$: poetry version
/root/.poetry/lib/poetry/_vendor/py2.7/subprocess32.py:149: RuntimeWarning: The _posixsubprocess module is not being used. Child process reliability may suffer if your program uses threads.
  "program uses threads.", RuntimeWarning)

[ImportError]
No module named pkg_resources
```

**Comment by marcelomendes** [comment] 2019-07-29 19:35
I'm having same issue, Debian current, Python 3.4

**Comment by autoferrit** [comment] 2019-07-30 16:22
I am getting this under latest ubuntu 18 under windows WSL. When installing, I used a python 3.7 version to run it, which came from pyenv.

**Comment by michielboekhoff** [comment] 2019-08-21 19:13
Hey there. Upon encountering the same issue, I implemented a quick fix for people using Python 3. The installer previously did not respect the installing Python version, which I propose to fix in #1312.

**Comment by michielboekhoff** [comment] 2019-08-21 21:52
I've done some more investigating on the root cause - why the `import _posixsubprocess32` fails. It appears the SO is built with a Python version that was compiled with UCS2 support, whereas my version is compiled with UCS4. 

I'm running this snippet to confirm what my Python was compiled with:

```
import sysconfig
sysconfig.get_config_var('Py_UNICODE_SIZE') # => 4
```

This is a tricky one to get around, really. You'd have to ship maybe another SO that's compiled for UCS4 and then modify the original `subprocess32.py` to import that if the original import failed or so. Alternatively, you could use Python 3, which avoids these problems altogether (by virtue of not needing this SO at all).

**Comment by brycedrennan** [comment] 2019-08-22 04:59
See also discussion on #1042 

@sklarsa Not sure what your use case is but you might consider using the python base images and installing poetry via pip.  Typically you don't need all the poetry features if you're working inside a docker container. For example:

```dockerfile
FROM python:3.7.4-slim@sha256:4b0cd7cc8a201bd8098adbb2f2ffef55eec1364297b0c1c6630cc4dee41739e3
RUN pip install poetry
# tell poetry to not create virtualenvironments
RUN poetry config settings.virtualenvs.create false
RUN poetry --version
```

**Comment by sklarsa** [comment] 2019-08-22 05:03
That’s what I ended up doing. The main annoyance that I had to work around was the inability to upgrade poetry if I was running a pip-installed version.

**Comment by kierun** [comment] 2019-10-29 10:50
Same problem, no docker and on CentOS 7. 

```
$ poetry debug
/home/usr/.poetry/lib/poetry/_vendor/py2.7/subprocess32.py:149: RuntimeWarning: The _posixsubprocess module is not being used. Child process reliability may suffer if your program uses threads.
  "program uses threads.", RuntimeWarning)

Poetry
Version: 1.0.0b3
Python:  2.7.5

Virtualenv
Python:         2.7.5
Implementation: CPython
Path:           /home/usr/.cache/pypoetry/virtualenvs/devtree-d7S69uV--py2.7
Valid:          True

System
Platform: linux2
OS:       posix
Python:   /usr
```

**Comment by tony** [comment] 2019-12-26 16:11
@autoferrit 

> I am getting this under latest ubuntu 18 under windows WSL. When installing, I used a python 3.7 version to run it, which came from pyenv.


Same/similar issue - I am using WSL 2 and that has 18.04 of ubuntu apparently

If poetry is using `/usr/bin/env python`, that means it's going to hit the distro's python 2:

```
❯ /usr/bin/env python -V
Python 2.7.17
```

**Comment by adamwojt** [comment] 2020-02-22 23:35
> I'm having same issue, Debian current, Python 3.7.4
> 
> Editing ~/.poetry/bin/poetry and changing "/usr/bin/env python" to "/usr/bin/env python3" fix it, but this will be probably overridden after next self:update

Thanks. This helped.

**Comment by brizzbane** [comment] 2020-02-23 02:21
Trying out poetry now...since pipenv domain expired, and ...hasn't seem to have been updated in a while.  I read comments from others saying poetry was nice, so I decided I would try and make the switch.

This is the first issue I came across.

> .poetry/lib/poetry/_vendor/py2.7/subprocess32.py:149: RuntimeWarning: The _posixsubprocess module is not being used. Child process reliability may suffer if your program uses threads.
  "program uses threads.", RuntimeWarning)

The above suggestion (I'm on Debian Stretch)--

> I'm having same issue, Debian current, Python 3.7.4
> 
> Editing ~/.poetry/bin/poetry and changing "/usr/bin/env python" to "/usr/bin/env python3" fix it, but this will be probably overridden after next self:update

also fixed my issue.  Thank you!

***
I did install via python3.7 get-poetry.py.  However, after having problems, I tried Debian Stretch's default 'python' (2.7.16) Then followed Stackoverflow posts saying to install subprocess32 to fix this error ... then messed with re-installing with things under root ...

Finally google'd error with + "poetry", and this was the solution.

**Comment by kierun** [comment] 2020-02-24 10:43
@brizzbane Python 2 is deprecated and should not be used.

**Comment by adamwojt** [comment] 2020-02-24 11:04
@kierun It's easy to say that but poetry entry point uses:
`#!/usr/bin/env python`
Which in most distros still means python 2.7 .

**Comment by kierun** [comment] 2020-02-24 11:24
@adamwojt My apologies. My comment was not meant to be read as harsh. Yes, many distro have not updated to just using solely Python 3 and some even have really valid reasons for not making the jump. However, running Python 2 is a bad thing™ since no updates will be happening.

**Comment by camilonova** [comment] 2020-03-21 22:12
Shouldn't we use?
`#!/usr/bin/env python3`

I don't know if we should use a fallback version to python2 but seems reasonable to support python3 only.

**Comment by louwers** [comment] 2020-04-03 10:30
Yes. This needs to be fixed. It's a problem on Fedora too.

RHEL will also continue to support Python 2. Assuming `python` means `python3` is just not an option, not now and not in the coming years.

**Comment by sondrewb** [comment] 2020-04-30 17:02
With Ubuntu 20.04 released, which does not include python 2.7 by default, this issue should be even more pressing.

**Comment by mblakesley** [comment] 2020-06-07 01:08
Also seeing this on linux mint. Why would poetry run on python 2 by default?

**Comment by newAM** [comment] 2020-06-07 02:04
What needs to be done to move this forward?  Should I open a pull request to change the shebang?

**Comment by finswimmer** [comment] 2020-06-07 12:38
Hello,

the warning about `_posixsubprocess` is just a warning and has no influence on the correct working of `poetry`.

As `poetry` can run with python2 and python3 it assumes, that whatever is linked the to `python` executable is the preferred version by the user. With https://github.com/python-poetry/poetry/pull/1878, which will be included in the 1.1 release, the installer script will be able, to add `python3` to the shebang if there is no `python` on the system. (Which is allowed by PEP397, but personally I would call it a broken system).

**Comment by newAM** [comment] 2020-06-07 21:05
> the warning about `_posixsubprocess` is just a warning and has no influence on the correct working of `poetry`.

This is more of a people problem though.  My workplace experience has been that co-workers are very distrustful of new tools when they give a warning on a fresh install.

Poetry is a wonderful tool, but the warning does make it harder to sell it to new people.

**Comment by finswimmer** [comment] 2020-06-08 04:55
@newAM, I've never found out how to really fix this warning. There is a workaround one can do, see my comment here: https://github.com/python-poetry/poetry/issues/2106#issuecomment-593611628

If anyone, has an idea how to fix it, we would be glad to here.

The easiest fix of course is, to replace the outdated python2 with python3 :grin: 

fin swimmer

**Comment by brizzbane** [comment] 2020-06-11 20:23
> @adamwojt My apologies. My comment was not meant to be read as harsh. Yes, many distro have not updated to just using solely Python 3 and some even have really valid reasons for not making the jump. However, running Python 2 is a bad thing™ since no updates will be happening.

I don't dev in Python 2, and try not to use projects that are written in Python 2, ..unless there is a very good reason to do so.  Even then, I would want to port any projects that are in 2, to 3, if I would end up using them long term... ...as I am currently only working with 3.

But I am using Debian 10...and I like Debian distro a lot.  At this time I don't think it would be appropriate to switch distros just because they haven't upgraded to Python 3.  

Debian lags behind... but whatever--I like it quite a bit.

..anyways..

**Comment by RafalSkolasinski** [comment] 2020-06-14 16:13
> I'm having same issue, Debian current, Python 3.7.4
> 
> Editing ~/.poetry/bin/poetry and changing "/usr/bin/env python" to "/usr/bin/env python3" fix it, but this will be probably overridden after next self:update

Let's hope next `self:update` will bring this patch with it ; - )

**Comment by 8F3E** [comment] 2020-07-04 14:42
I personally found installing poetry using pipx was an easy workaround (inspired by https://github.com/python-poetry/poetry/issues/1543#issuecomment-569709218).

That way poetry's dependencies are restricted to a virtualenv, but it sticks with python3.

Just got to remember to `pipx upgrade poetry` rather than a self update.

**Comment by reedjosh** [comment] 2020-11-11 01:40
For me I just worked around this with a shim that points python to python3.

pwd/.bin/python
``` shell
#!/bin/sh

python3 $@
```

and 
```export PATH=`pwd`/.bin/python:$PATH```
`chmod u+x .bin/python`

This is ugly, but forces the newer version of Python. I'm personally stuck on an older distro at work.

**Comment by finswimmer** [comment] 2021-07-23 09:01
Vendoring is no longer done with the new `install-poetry.py` script. That's why I close this issue.

**Closed by finswimmer** 2021-07-23 09:01 UTC
Labels: Bug
