### ISSUE TITLE
`poetry publish` fails for package with `.` in its name.

### ISSUE THREAD

**Issue by nekitdev** [python-poetry/poetry#5782] opened 2022-06-06 10:45 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

- **OS version and name**: windows 11, also fails on linux
- **Poetry version**: 1.2.0-beta.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/nekitdev/99b0cd36e9fd32712f38401439823cc1

## Issue

For packages with `.` in the name:

```toml
[tool.poetry]
name = "example.py"
```

Poetry correctly builds wheels and sdists with `example.py` in the file name.
However, when uploading to PyPI with the canonical name (i.e. `example-py`), `poetry publish` fails with the following error:

```text
HTTP Error 400: Start filename for 'example-py' with 'example-py'.
```

**Comment by mkniewallner** [comment] 2022-06-06 11:44
According to https://packaging.python.org/en/latest/specifications/binary-distribution-format/#escaping-and-unicode, it seems that the right thing to do for wheels would be to replace `.` with `_` for the distribution name.

Though even if doing so, a bug in warehouse (the backend behind PyPI) may prevent the upload from working: https://github.com/pypa/warehouse/issues/10030.

**Comment by nekitdev** [comment] 2022-06-07 07:34
It seems as though Poetry attempts to publish `example-py` with files containing `example.py`, causing PyPI to return the error above. I have hooked `canonicalize_name` function to see if PyPI allows uploading with `example.py` as the name, which it apparently does. So I'm assuming the mismatch is what causes the error.

**Comment by nekitdev** [comment] 2022-06-07 07:35
Once again, I'm not exactly sure how to solve this issue, though.

**Comment by neersighted** [comment] 2022-06-07 15:56
> Once again, I'm not exactly sure how to solve this issue, though.

We've already got a PR under review that uses the same logic pip does to canonicalize wheel names.

**Comment by nekitdev** [comment] 2022-06-07 16:25
Oh, I see, thanks! I'm looking forward to it. :)

**Comment by NiklasRosenstein** [comment] 2022-07-16 21:52
I just realized that this is an issue with `poetry-core==1.1.0b2`, but not with the latest final release `poetry-core==1.0.8`. 
The way I had set up my build process was that I ended up using the a `poetry-core` beta release.

I also confirmed the issue with `1.1.0b3`.

**Comment by Axelancerr** [comment] 2022-09-03 03:15
I am still getting this issue with poetry==1.2.0 and poetry-core==1.1.0.
Building works fine but I am unable to publish the sdist file and publishes the wheel file results in the package having a dash in the name on pypi which is undesirable.

**Comment by dimbleby** [comment] 2022-09-03 12:57
Situation:

- poetry always normalizes the package name at upload
- poetry-core normalizes package names when building .whl but not when building .tar.gz
- pypi insists that uploaded files start with a prefix that matches the package name

So per this issue, folk who try for un-normalized package names find that poetry normalizes their package name at upload, and they can't upload their source distribution because it has the wrong prefix.

Probably the sensible next step is to normalize .tar.gz names in [poetry-core](https://github.com/python-poetry/poetry-core/blob/e3ea1b1ce873991326823338b7a61afbad65ddee/src/poetry/core/masonry/builders/sdist.py#L68) (and also make the corresponding change in poetry itself - the uploader class currently expects unnormalized source distributions, because it 'knows' what poetry-core did).  

That gets to a place where poetry insists on normalization, but at least it is possible to upload sdists.

Not planning on doing this myself, no doubt MRs are welcome.

**Comment by mkniewallner** [comment] 2022-09-03 15:50
> Probably the sensible next step is to normalize .tar.gz names in [poetry-core](https://github.com/python-poetry/poetry-core/blob/e3ea1b1ce873991326823338b7a61afbad65ddee/src/poetry/core/masonry/builders/sdist.py#L68) (and also make the corresponding change in poetry itself - the uploader class currently expects unnormalized source distributions, because it 'knows' what poetry-core did).

Last time I checked, there was no accepted PEP formally stating that sdists should be canonicalised, though the closest thing there is to that is [this packaging specification](https://packaging.python.org/en/latest/specifications/source-distribution-format/#source-distribution-file-name) which states:
> The file name of a sdist is not currently standardised, although the de facto form is {name}-{version}.tar.gz, where {name} is the canonicalized form of the project name (see [PEP 503](https://peps.python.org/pep-0503/) for the canonicalization rules) with - characters replaced with _, and {version} is the canonicalized form of the project version (see [Version specifiers](https://packaging.python.org/en/latest/specifications/version-specifiers/#version-specifiers)).

There is [PEP 625](https://peps.python.org/pep-0625/) about canonicalising the name the same way as for wheels, but it is still in draft.

Although PEP or not, it would seem more sensible to canonicalise sdists the same way as Poetry already does for wheels, for better consistency, especially since this (probably) shouldn't be a problem for any tool consuming the sdists.

**Comment by dimbleby** [comment] 2022-09-03 15:54
Sure, the proposal to canonicalize sdists in the same way as bdists wasn't intended to rule out the possibility of supporting un-canonicalized project names at some later point (nor to rule it in, come to that!).

I suggest sdist canonicalization as a relatively low risk next step that can be taken without getting into that discussion at all.  It's clearly a bug at the moment that some packages can't upload their sdists, start by solving that.

Then later debate the merits or otherwise of supporting un-canonicalized names.

**Comment by neersighted** [comment] 2022-09-03 15:56
If anything this bug is PyPI being too strict in validation when different names are allowed by the spec -- technically Poetry is doing nothing wrong. However, from a practical standpoint I believe they use filenames to identify releases, so the requirement to match makes sense (even if it's undocumented/not required by spec).

**Comment by SvenBecker** [comment] 2022-09-23 09:35
Is there some way to opt out of the package name normalization or would it be possible to provide such an option? We are using some internal PyPI so I'm not sure if those PyPI validations even affect us.

**Comment by dimbleby** [comment] 2022-09-23 09:37
No.  You will either need to put together an MR changing the code, or hope that someone else does.

**Comment by NiklasRosenstein** [comment] 2022-09-27 11:11
What worked for me is to pin `poetry-core==1.0.8`:

```toml
[build-system]
requires = ["poetry-core==1.0.8"]
build-backend = "poetry.core.masonry.api"
```

But I build with Poetry and publish with Twine; not sure if this still works with `poetry publish`.

**Comment by neersighted** [comment] 2022-09-27 13:42
This will not work with `poetry publish` as Poetry does not use the `requires =` field.

**Comment by neersighted** [comment] 2022-10-10 07:31
Closing as python-poetry/poetry-core#484 is merged.

**Closed by neersighted** 2022-10-10 07:31 UTC
Labels: kind/bug, area/publishing, version/1.2.1
