### ISSUE TITLE
[FileNotFoundError] [Errno 2] No such file or directory: 'git'  - Poetry 1.0.4

### ISSUE THREAD

**Issue by GryshchenkoAndrii** [python-poetry/poetry#2108] opened 2020-02-28 21:58 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: 9.0 Debian 
- **Poetry version**: 1.0.4
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/GryshchenkoAndrii/898534f0fa052bcf3fd3efeb82c642d7

## Issue
On poetry version 1.0.4, whenever command `poetry build` is executed, error is produced:
`
[FileNotFoundError]
[Errno 2] No such file or directory: 'git'
`
It happens in docker-container [python:3.8-slim](https://hub.docker.com/_/python)

**On Poetry version 1.0.3 workflow works as expected.**

Please see the log output:
```
+ poetry -V
Poetry version 1.0.4
+ poetry build -vvv
Skipping virtualenv creation, as specified in config file.
Building ********
 - Building sdist

[FileNotFoundError]
[Errno 2] No such file or directory: 'git'

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/usr/local/lib/python3.8/site-packages/clikit/api/command/command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "/usr/local/lib/python3.8/site-packages/clikit/api/command/command.py", line 171, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/usr/local/lib/python3.8/site-packages/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File "/usr/local/lib/python3.8/site-packages/poetry/console/commands/build.py", line 30, in handle
    builder.build(fmt)
  File "/usr/local/lib/python3.8/site-packages/poetry/masonry/builder.py", line 21, in build
    return builder.build()
  File "/usr/local/lib/python3.8/site-packages/poetry/masonry/builders/complete.py", line 31, in build
    sdist_file = sdist_builder.build()
  File "/usr/local/lib/python3.8/site-packages/poetry/masonry/builders/sdist.py", line 69, in build
    files_to_add = self.find_files_to_add(exclude_build=False)
  File "/usr/local/lib/python3.8/site-packages/poetry/masonry/builders/builder.py", line 135, in find_files_to_add
    if self.is_excluded(file) and isinstance(include, PackageInclude):
  File "/usr/local/lib/python3.8/site-packages/poetry/masonry/builders/builder.py", line 109, in is_excluded
    if exclude_path.as_posix() in self.find_excluded_files():
  File "/usr/local/lib/python3.8/site-packages/poetry/masonry/builders/builder.py", line 79, in find_excluded_files
    vcs = get_vcs(self._original_path)
  File "/usr/local/lib/python3.8/site-packages/poetry/vcs/__init__.py", line 16, in get_vcs
    subprocess.check_output(
  File "/usr/local/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/lib/python3.8/site-packages/poetry/utils/_compat.py", line 188, in run
    process = Popen(*popenargs, **kwargs)
  File "/usr/local/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)

make: *** [Makefile:41: test_deployment] Error 1
```

**Comment by jr314159** [comment] 2020-02-28 22:03
Duplicate of https://github.com/python-poetry/poetry/issues/2107

**Comment by GryshchenkoAndrii** [comment] 2020-02-28 22:16
> Duplicate of #2107

Oh come on, 1 minute difference and my report has logs and all these bells and whistles!

**Closed** 2020-02-29 08:15 UTC
Labels: Bug
