### ISSUE TITLE
Poetry mistakes activated virtualenv for system Python

### ISSUE THREAD

**Issue by qwertystop** [python-poetry/poetry#4030] opened 2021-05-03 14:41 UTC
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).
(no such exception occurs)

- **OS version and name**: Arch Linux, `linux` version 5.11.16.arch1-1
- **Poetry version**: 1.1.6
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/qwertystop/3a42bfc33056336af323607c277aac37

## Issue

Poetry is mistaking any activated virtual environment for the system Python, therefore using the correct Python version but creating new virtual environments in which to install any given project and its dependencies rather than using the existing one in which (for example) my editor runs.

For example:

```
(invdb) ▲ …/inventorydatabase poetry env info

Virtualenv
Python:         3.9.4
Implementation: CPython
Path:           NA

System
Platform: linux
OS:       posix
Python:   /home/qwertystop/.pyenv/versions/invdb
(invdb) ▲ …/inventorydatabase pyenv shell 3.7.4
(3.7.4) ▲ …/inventorydatabase poetry env info

Virtualenv
Python:         3.7.4
Implementation: CPython
Path:           NA

System
Platform: linux
OS:       posix
Python:   /home/qwertystop/.pyenv/versions/3.7.4
(3.7.4) ▲ …/inventorydatabase pyenv shell 3.9.4
(3.9.4) ▲ …/inventorydatabase poetry env info

Virtualenv
Python:         3.9.4
Implementation: CPython
Path:           NA

System
Platform: linux
OS:       posix
Python:   /home/qwertystop/.pyenv/versions/3.9.4
```

I installed Poetry through the install script (though using https://archlinux.org/packages/community/any/python-poetry/ instead did not help with this error). I have tried `poetry env use ~/.pyenv/versions/invdb/bin/python`. I have tried manually `source`-ing the `activate` script in the virtual environment rather than allowing Pyenv to manage it. Neither of these makes a difference.

**Comment by jgentil** [comment] 2021-05-04 16:42
This hits me all the time.  I have to modify the vendored `cacert.pem` file in the certifi module because my corporate environment uses Zscaler which does MITM SSL changes to pypi.  Whenever I am in a virtualenv or inside a `poetry shell` instance this breaks my changes since the interpreter changes.  Until poetry supports setting CA certificates for pypi, I'm stuck with this solution and the virtualenv problem is a constant nag in my workflow.

**Comment by finswimmer** [comment] 2021-05-04 18:24
Hello @qwertystop,

unfortunately I cannot follow you. Could you please add some more information please? What are you doing? What's your expected behavior? What happens instead?

@jgentil How is your problem related to the one @qwertystop reported? :thinking: 

Thanks for adding more information, so we can help!

fin swimmer

**Comment by qwertystop** [comment] 2021-05-09 23:24
@finswimmer 
My issue was: I would create a virtual environment using `pyenv virtualenv`, activate it using `pyenv local`, attempt to run a `poetry` command, and find that `poetry` was ignoring the activated virtual environment and creating a new one. Checks using `poetry env info`, as shown at the top of the issue, found that `poetry` was seeing the currently activated virtual environment as the system python, with no path for a detected virtual environment.

The issue eventually stopped happening after I deleted `~/.cache/pypoetry/virtualenvs/envs.toml`, though I'm not sure why, and said file has not reappeared with continued use of Poetry.

**Comment by milzer** [comment] 2021-11-21 11:43
I have the same problem. I assumed poetry is capable of using existing virtualenv like it says in the front page of python-poetry.org: "Poetry either uses your configured virtualenvs or creates its own to always be isolated from your system.".

```
milzer:~/testenv$ source ~/.virtualenvs/testenv/bin/activate

(testenv) milzer:~/testproject$ which python
/home/milzer/.virtualenvs/testenv/bin/python

(testenv) milzer:~/testproject$ poetry env use ~/.virtualenvs/testenv/bin/python
Skipping virtualenv creation, as specified in config file.
Using virtualenv: /usr

(testenv) milzer:~/testproject$ poetry env info

Virtualenv
Python:         3.8.10
Implementation: CPython
Path:           NA

System
Platform: linux
OS:       posix
Python:   /usr
```

Now if I install any packages, they go to my global python env.

**Comment by finswimmer** [comment] 2021-11-21 12:13
@milzer: Your output says: "Skipping virtualenv creation, as specified in config file."

Check your config by `poetry config --list` and you will see that `virtualenvs.create` is set to `false`. This is not the default. So you must have changed it. Run `poetry config virtualenvs.create true` to set it to `true` again.

fin swimmer

**Comment by milzer** [comment] 2021-11-21 12:25
@finswimmer But I want to skip creating a new environment because I want to use an existing one. Or did I misunderstood something and this is not possible?

**Comment by finswimmer** [comment] 2021-11-21 16:18
> Or did I misunderstood something

I think you misunderstood the use of `poetry env use`. This command tells poetry which python interpreter it should use when creating a venv. 

If you want to use a specific venv you have to activate it on your own and run your poetry command within that venv. Than poetry will not create a new one.

**Comment by milzer** [comment] 2021-11-21 17:59
Ok, now that I tried again without even touching `poetry env use` everything seems to work as I was expecting. Maybe the documentation could use some clarification regarding this? At least I got the impression that `env use` chooses the environment to use.

**Comment by jgentil** [comment] 2021-11-30 16:34
I think I misread the original issue, after it was clarified I think my problem is similar but not the same problem.  I'll create a different issue to elaborate.

**Comment by finswimmer** [comment] 2022-10-04 07:58
Closing this, because the original issue/question is solved/answered.

**Closed by finswimmer** 2022-10-04 07:58 UTC
Labels: area/venv, status/triage
