### ISSUE TITLE
Is there a way to redefine the destination of generated poetry build artefacts?

### ISSUE THREAD

**Issue by coderfromhere** [python-poetry/poetry#2168] opened 2020-03-10 17:02 UTC
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

## Issue

Hi, I'd like to know if there's a way to control the path of `poetry build` command's output. I'm using poetry in the environment that doesn't allow to write sdist/wheel artifacts in the root of the repo. Original `setuptools` has `--bdist-dir` and `--dist-dir` for managing such scenarios.

**Comment by finswimmer** [comment] 2020-03-10 19:37
Hello @max-arrival,

this is not possible at the moment, but sounds like a useful feature.

fin swimmer

**Comment by mkniewallner** [comment] 2022-06-16 22:42
Closing this as a duplicate of https://github.com/python-poetry/poetry/issues/2168, since there is a bit more background and discussion.

**Closed by mkniewallner** 2022-06-16 22:42 UTC
Labels: Feature, Duplicate
